### ISSUE TITLE
Add extra config in loadBackendConfig

### ISSUE THREAD

**Issue by blaryjp** [backstage/backstage#10278]
## Feature Suggestion

Hello,

I'ld like to load configuration from a remote tool (hashicorp vault), and not use env variables or files.

The backend configuration is loaded using `loadBackendConfig` function. We can add a extra option "config", like:

```ts
const config = await loadBackendConfig({
    argv: process.argv,
    logger: getRootLogger(),
    config: await getConfigFromVault(),
});
```

What do you think? If it's ok, I'll implement it of course.

Thank you!

**Comment by freben** [comment]
@Rugvip Is this use case supported using the `remote` functionality?

**Comment by Rugvip** [comment]
Worth checking out whether the `remote` option works in this case indeed.

If not, I think a sensible way to implement this might be to extend the `ConfigTarget` type in the loader. Potentially something like this?

```ts
export type ConfigTarget =
  | { path: string }
  | { url: string }
  | { inline: AppConfig };
```

By making it a config that you pass in rather appending to the returned `AppConfig`s we run the transforms on the provided config as well, allowing you use use env var substitutions and whatnot.

We'd also need to extend the `loadBackendConfig` with something like an `additionalTargets` option.

Would look something like this in the end:

```ts
const config = await loadBackendConfig({
  argv: process.argv,
  logger: getRootLogger(),
  additionalTargets: [{
    inline: { data:  await getConfigFromVault(), context: 'vault' }
  }],
});
```

A very different route would be to provide whatever flexibility is missing in the remote fetching utility. Tbh I would probably prefer that option as it's adding customization a bit deeper in, doesn't feel like it interrupts the API surface as much. That's ofc only if we it works as an option.

Could you give a quick intro to how you'd implement `getConfigFromVault` @blaryjp?

**Comment by blaryjp** [comment]
Yes, it can have any implementation. In my case, it should be something like: connect to Vault, get secrets, create an object matching the app-config shema with secrets, and return it.

A possible implementation can be (regarding [this article](https://codersociety.com/blog/articles/hashicorp-vault-node):

```ts
const vault = require('node-vault')({
  apiVersion: 'v1',
  endpoint: 'https://vault.mycompany.com',
});

const result = await vault.approleLogin({
  role_id: process.env.VAULT_ROLE_ID,
  secret_id: process.env.VAULT_SECRET_ID,
});

vault.token = result.auth.client_token;

const { data } = await vault.read('secret/data/mysql/backstage');

return {
  backend: {
    database: {
      connection: {
        host: data.db_name,
        port: data.db_port,
        user: data.db_user,
        password: data.db_password,
      },
    },
  },
};
```

Btw, I like your solution @Rugvip !

**Comment by jhaals** [comment]
I'm a bit reluctant to add Vault directly into the config reading as there's probably a lot to consider in terms of secret layout in vault plus the ability to configure dynamic secrets. I'm afraid the solution is not going to fit all very well in the end and just add complexity to our already too flexible(in my option) config solution. I'd much rather recommend the integrator rely on some of the many [pre-start](https://github.com/channable/vaultenv) solutions, [Vault Agent Template](https://www.vaultproject.io/docs/agent/template) or one of the [kubernetes](https://learn.hashicorp.com/tutorials/vault/kubernetes-sidecar) integrations to do this.

**Comment by jhaals** [comment]
Don't get me wrong I think vault is a great tool and that having methods for safely getting secrets into the app is important :) I think env or even cmd line is probably sufficiently secure given that runtime privileges are handled correctly.
In any case I'm all for trying out what @rugvip brought up previously in the thread to achieve an "in process" approach that doesn't require us to introduce vendor specific code into the core library.

**Comment by goenning** [comment]
I'm looking for something similar, but using Azure KeyVault instead of HC Vault.

After some digging I found that @backstage/config-loader support some transformations functions. Would it make sense to extend this to allow additional transformations from plugins?

Something like this:

```yaml
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN} # this comes from an envvar
    - host: github2.com
      token: $HashiCorpVault:GITHUB2_TOKEN # this comes from  HashiCorp Vault
    - host: github3.com
      token: $AzureKeyVault:GITHUB3_TOKEN # this comes from Azure KeyVault
```

The actual string 

The transformations could be on backstage itself or community plugins: @backstage/plugin-config-hashipcorpvault, @backstage/plugin-config-azurekeyvault, @backstage/plugin-config-awskms

From a usage perspective, it would be like:

```ts
import { azureKeyVaultTransformer } from "@backstage/plugin-config-azurekeyvault"

  const config = await loadBackendConfig({
    argv: process.argv,
    logger,
    transformations: [azureKeyVaultTransformer]
  });
```

**Comment by goenning** [comment]
I also considered using `experimentalEnvFunc`, something like:

```ts
experimentalEnvFunc: async (name) => {
  if name starts with 'AzureKeyVault:' return getSecretFromAzure(name)
  return process.env[name]
}
```

but that seems to have been remove from `loadBackendConfig`.

**Comment by blaryjp** [comment]
This looks a good idea @goenning . I planned to work on  @Rugvip proposal in the next weeks, but I'll wait the feedback from Backstage's team about your idea so :).

**Comment by Rugvip** [comment]
Transformations were added with that kind of custom transform use-case in mind. At this point I'm not sure it's a good idea though tbh, it does open up a lot of questions about how it's supposed to work with the frontend builds, and perhaps local development. It does have the pretty big benefit of being able to rely on the existing config system to define the secrets that are loaded in, with the readability and flexibility that that comes with.

Very torn on what the best way forward is tbh, I feel both approaches might even have their own benefits. I'd be up for opening up an `experminentalThisWillSurelyChangeInTheFuture*` API to support the custom transform, if you're alright with taking it all the way to reporting findings back so that we can decide whether it's something that makes sense to ship as stable or not.

**Comment by goenning** [comment]
Thanks for your inputs, I might hack something along these lines to see how it'd look.

```
it does open up a lot of questions about how it's supposed to work with the frontend builds, and perhaps local development. 
```

I don't think it impacts frontend build at all (as far as I know), because current transforms are already backend-only anyway. 

As for local dev, it's really up to integrators to decide how they want to setup. They might want the app-config.local.yaml to use env vars and hard codes strings, while on app-config.prod.yaml it might a combination of env vars + vaults.

In our case, we're looking to have vault used for local dev as well, that'll mean devs won't need to share secrets as they'd be pulled directly from the vault. Authentication is seamless so it's all transparent, they can pull backstage and run yarn without setting up anything else (as long as they have acessa to our development keyvault)

**Comment by oconnormj** [comment]
Hi,
wondering if this enhancement was progressed since the discussion back in May '22. I have a requirement to integrate with Azure Key Vault. I've searched but I can't find any related issues that might have been opened back then.

> Very torn on what the best way forward is tbh, I feel both approaches might even have their own benefits. I'd be up for opening up an `experminentalThisWillSurelyChangeInTheFuture*` API to support the custom transform, if you're alright with taking it all the way to reporting findings back so that we can decide whether it's something that makes sense to ship as stable or not.
