### ISSUE TITLE
Scaffolder nunjucks renderer cannot process include tags

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#10312]
## Expected Behavior

Given a `file1.txt` with:

```
Hello {% include "file2.txt" %}
```

and a `file2.txt` with

```
world
```

The output should be 

```
Hello world
```

(or something like that, allowing for line endings and so on)

## Actual Behavior

When rendering `file1.txt`, the VM script errors out with 

```
      TypeError: Cannot read property 'resolve' of undefined

      159 |       }
      160 |
    > 161 |       return vm.run(`render(templateStr, templateValues)`);
          |                 ^
      162 |     };
      163 |     return render;
      164 |   }

      at VM.runScript (../../../node_modules/vm2/lib/vm.js:285:18)
      at VM.run (../../../node_modules/vm2/lib/vm.js:503:16)
      at render (lib/templating/SecureTemplater.ts:161:17)
      at Object.handler (scaffolder/actions/builtin/fetch/template.ts:244:19)
      at Object.<anonymous> (scaffolder/actions/builtin/fetch/template.test.ts:299:9)
```

## Steps to Reproduce

[failing test](https://github.com/tragiclifestories/backstage/commit/118fe232c24357d9f98d1e5b54fb691dfb4c8538)

## Context

Nunjucks officially supports these includes, like other jinja-style engines, and they can be useful for composing different elements together.

## Your Environment

Intel MBP 2019 running macOs Monterey
Intel Ubuntu 20.04
Our Kubernetes cluster
All running node 14.x versions.

But I don't think this is platform specific - the nature of the sandboxing used seems to mean that each file is evaluated completely separately, without the surrounding context of the template directory, so includes are guaranteed not to work.

**Comment by Rugvip** [comment]
I think at the very least we could make it so that it throws an error explaining that file inclusions are not supported. Happy if anyone wants to take a stab at that, it's a little bit tricky because it's gonna be modification to the shim that we use inside `SecureTemplater.ts`

On top of that we could discuss whether this is something we think can be implemented safely and if it's worth the risk/complexity. It's not supported right now because we're being very careful about reading local files. We'd need to make sure path resolution and file access doesn't open up any kind of vulnerabilities.

**Comment by tragiclifestories** [comment]
I understand that obviously a lot of thought has been put into making this safe, but I'm not sure how the risk calculation is different to the many other situations in which this pattern holds. Including template partials is a very common feature of different template languages - how is this more of a vulnerability than just like a Rails template or something?

Could we have an explicit opt-out that would allow us to execute a given template more naively? Like:

```yaml
steps:
  - action: fetch:template
    input:
      unsafeAllowIncludesAndYesIKnowWhatImDoing: true
```

**Comment by jhaals** [comment]
It make sense to give this a try but of course with some validation so that we don't access things outside the workspace. The `resolveSafeChildPath` might be useful for this. I suggest we try to implement this in a good way first and add the flag as a last resort. Are you interested in taking a stab at this @tragiclifestories?

**Comment by tragiclifestories** [comment]
If I can get some time to take a look, sure. I'm not sure how possible it will be, mind. This is a feature built into the templating language, so I guess you'd have to create a parse tree of the templates, evaluate all the include paths and verify that they're all safe as a sort of preflight check. Whether this is possible will depend on the implementation details of nunjucks, of course. You'd still then have to do the templating outside of the VM and so you'd have to audit that there was no other way to unsafely traverse directories and deal with that ... somehow.

**Comment by tragiclifestories** [comment]
Just messing around with nunjucks in the node console, it seems to throw an error if you try to include a file which is above the original file in the directory tree. I can't find the code that does this, though.

**Comment by jhaals** [comment]
We would have to provide our own shim/proxy via the sandboxed VM as we don't want to allow access to the `fs` module directly.

**Comment by tragiclifestories** [comment]
And the `path` module, presumably.
