### ISSUE TITLE
Use title everywhere outside the entity page

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10570]
## Feature Suggestion

When available, I'd like to see the title of each section instead of its name. For example, on my component page I have the following table : 

![image](https://user-images.githubusercontent.com/37327656/161241443-5e4dfd72-6899-4848-bfe1-265080e5aadc.png)

My **backstage** system is titled **Backstage** and my **owner** is titled **CdC Big Data TRVS team**. 

So in my columns, I'd like to see these titles instead of names. 

I think this follows the same logic that you used to describe the `title` field : 

```This field is sometimes useful when the name is cumbersome or ends up being perceived as overly technical.```

## Context

Because the names of entity can be quite technical, we'd like to use the title every where outside the entity page itself.

**Comment by freben** [comment]
Yep this is definitely desirable. The problem is, it's inside the entity body and not available in the initial response from the server, so one would have to perform a lot of additional round trips to the catalog just to grab the titles - which gets costly and slows down the user experience. We've been intending to make this part of the graphql solution when that transpires some time in the future, so that the table can easily grab all that it needs in a single request.

In the mean time, what you can do is to make a custom component that renders an entity ref and is smart enough to fetch (and probably cache) the title in the background, replacing the raw name with the title once it arrives from the backend.

**Comment by antoniordz96** [comment]
Hey we opened https://github.com/backstage/backstage/issues/14398 where we switched our entities to leverage this `Title` field. This works as mentioned perfectly in each entity page but not in tables such as the default catalog table. Is comment https://github.com/backstage/backstage/issues/10570#issuecomment-1085805937 still the only solution today? 

Our team might be interested in contributing this with the right set of guidance.
