### ISSUE TITLE
Reload frontend upon changing configuration

### ISSUE THREAD

**Issue by muhamadto** [backstage/backstage#10735]
Currently the frontend is build and served with the values in `app-config.yaml`. Upon changing the configuration the back end gets refreshed but not the frontend.

## Feature Suggestion
Refresh the frontend to reflect the configuration changed or added, for instance:
* If a new plugin is added and configured in the `app-config.yaml`, that plugin should show up in the frontend when the configuration is read. For instance, if I add a sonar plugin to my config, I don't want to rebuild the frontend, but I want it to show up in the UI once the config is reloaded.
* If an existing plugin config changes, that should be reflected in the frontend configuration is read. For example, if I change the sonarqube url in my config, it should be reflected in the frontend

## Context

We are building an admin page to change the configuration without rebuild backstage with every new plugin we add.

**Comment by freben** [comment]
Hi! This is a neat idea. It'll take some work and requires some form of event bus between the backend and frontend. That's an idea that we've had in the back of our minds before, but no solid plans to work on it in the near term.

**Comment by muhamadto** [comment]
Hey @freben Would you be able to provide us with idea about what needs to be done. And we can get one of our JS dev to try their hands at it? May be we can arrange a virtual meet?

**Comment by freben** [comment]
I think in this instance, I'd recommend holding off a bit. Since we want to get some backing design for this settled first, and we might be looking at that some time in the near-to-mid-term, and the only end user impact is that you have to reload the browser on config changes ... probably best to not do anything for this specific thing right now.

**Comment by Rugvip** [comment]
Realized there's a bit of context lacking here, would this be for local development or production apps? As freben mentions we're not really comfortable with the complexity that this would add to a production deployment, but for local development we could totally get this going.

**Comment by Rugvip** [comment]
Implementing the reload without significant user impact is pretty tricky and adds a lot new complexity into the mix. Local development is simpler because it's just a matter of releasing the page, can't really do that in production tho.

That's unless we're missing something, do you have a high level idea of how it could be implemented with little user impact and not much additional complexity?

**Comment by muhamadto** [comment]
@Rugvip how can refreshing the configuration impact user experience? please bear in mind that I'm not talking about auto refreshing browser. I'm just request when the config changes and the user refreshes the page manually they get new version of the frontend without the need to rebuild/restart backstage.

**Comment by muhamadto** [comment]
Hey @Rugvip, is this something you guys can put on your roadmap?

**Comment by Rugvip** [comment]
@muhamadto sorry, it's not something we have space to prioritize, but happy to guide and/or review contributions!
