### ISSUE TITLE
Add authentication provider for visualstudio.com apps

### ISSUE THREAD

**Issue by shailahir** [backstage/backstage#10776]
Create a new auth provider for visualstudio.com apps

## Feature Suggestion

Currently we have an auth provider for azure. but I am unable to use it with the credentials from visualstudio.com app. Requesting community to help on creating a new auth provider for visualstudio.com host.

## Context

Currently we have an auth provider for azure. but I am unable to use it with the credentials from visualstudio.com app.

**Comment by Rugvip** [comment]
For clarity, what is the difference between visualstudio.com app auth and the existing Microsoft/Azure provider? Do you perhaps have a link to the setup docs for that?

What issues do you encounter when trying to use credentials from the visualstudio.com app with the azure provider?

**Comment by shailahir** [comment]
https://docs.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops

https://app.vsaex.visualstudio.com/app/register for registration.

**Comment by shailahir** [comment]
If we use the publish:azure in the template. the scmauth requests for vso.build and other vso.* scopes and uses microsoft auth provider. but we get error that such scopes does not exist on the microsoft Active directory app. Please give me some hint to solve this issue. I am stuck on this for more than one week.

**Comment by shailahir** [comment]
I just want to use the RepoUrlPicker with allowedhosts dev.azure.com and requestCredentials enabled. it is failing with error. vso.build scope not there. It maybe a bug in the azure side of the Repo picker for software template. I am desparate to solve this and only way to find a solution it seems to use the visualstudio app. Please suggest.

**Comment by shailahir** [comment]
https://github.com/backstage/backstage/blob/45153b3b082d552936075f2fab9f1bd2a07aa327/packages/integration-react/src/api/ScmAuth.ts


Please See forAzure method.

**Comment by shailahir** [comment]
https://github.com/backstage/backstage/issues/10865  #10865

**Comment by jhaals** [comment]
Ping @awanlin and @marleypowell, do you have any input to this problem 🤞

**Comment by awanlin** [comment]
Hi @shailahir, just trying to understand your end goal: as a Software Template user when I run the template it will perform the actions as the current user. Is that a correct statement?

One option that would be worth validating, is to use just a Azure DevOps PAT (Personal Access Token) with the needed scopes. That does work, at least for us using Azure DevOps Server (on-premise), it just won't be using the current user. Doing this would help at least getting things working for you.

**Comment by shailahir** [comment]
Yes @awanlin , you are right.
The requirement is - as a user, I should be able to create a new project in Azure DevOps using software template. It should ask for my credentials and use the access token returned to do the actions [ 1. show the orgs and projects mapping in the form dropdowns ( get this information from rest api using the access token) 2. after selecting the org and project from the dropdowns , finally use the same access token to publish to azure.

**Comment by shailahir** [comment]
And yes If I use the personal access token from Azure Devops it works perfectly. But I am not allowed to use a service account for creating and publishing repo to azure. I must ask the user for credentials using popup and then use the same. And I am using microsoft auth provider (tenantId, clientId, clientSecret)

**Comment by awanlin** [comment]
Ok, thanks for confirming things for me, sadly this does mean I'm not able to help further as we use the on-premise Azure DevOps Server and we aren't using the Software Templates much so I don't have enough knowledge to help with this, sorry :(

**Comment by shailahir** [comment]
np :)

**Comment by jhaals** [comment]
Thanks for checking @awanlin!
I'm equally confused about these additional Microsoft offerings, I thought https://visualstudio.microsoft.com/ was just for the editors and had nothing to do with the repository hosting. As Patrik mentioned we really need community help to tinker with some of these provider specific implementations. We can always help out with guidance into Backstage's code base and how these things are implemented internally but it really tricky and time consuming for us to setup and debug some of these implementations.

**Comment by armandocollazo-tomtom** [comment]
Hello @shailahir I am facing this same issue since decided to create a Software Template that creates a Pull Request in the chosen Azure DevOps repository. 
Have you managed to work around this issue? Did you find a solution for it?

**Comment by brunoscota** [comment]
I'm stuck in the same issue!!

**Comment by marleypowell** [comment]
> Ping @awanlin and @marleypowell, do you have any input to this problem 🤞

I've had a look into this and it looks like it's because the required permissions are `Application` permissions rather than `Delegated` permissions which is what the OAuth scopes can request.

These are the Application permissions:
![image](https://user-images.githubusercontent.com/55280588/219710686-b6f50b14-3ebf-4f4a-8209-8550de1485bf.png)

These are the Delegated permissions:
![image](https://user-images.githubusercontent.com/55280588/219710911-1508f509-6134-4838-a604-c9cda6d0bf4d.png)
![image](https://user-images.githubusercontent.com/55280588/219711389-f4ce52a0-3673-411e-8d8c-6b535f19abf5.png)

For Azure Devops API permissions there's only one delegated scope for `user_impersonation`. I think [this is the documentation](https://github.com/microsoft/azure-devops-auth-samples/tree/master/ManagedClientConsoleAppSample) for that usage.
![image](https://user-images.githubusercontent.com/55280588/219712057-f2de5756-cd44-4309-9560-8614fdcd64ff.png)

I think for using OAuth to get Azure Devops permissions it works slightly differently to normal Microsoft auth setup (used for identity) as documented here: https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/oauth?view=azure-devops&viewFallbackFrom=vsts

You could use the application permissions with the MSAL client library to act as an application to make source control API requests (the same method as the Azure plugins that fetch repo data although I think they might use a PAT because it's easier).

For user impersonation I think you might be better off using the MSAL library to get the auth token that can be used and I don't think it will work with the current OAuth implementation in the scaffolder.

docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-7.1#authenticate

**Comment by punkle** [comment]
I am also having trouble getting the scaffolder oauth token via the azure integration. Same error `vso.build` error that's been seen. Has anyone managed to get through this?

**Comment by Phiph** [comment]
I'm hitting this issue too. 


<img width="837" alt="image" src="https://github.com/backstage/backstage/assets/8458416/ca66edf8-5ec9-4658-a33d-98f0ef8b79af">


I am a global admin in this tenant, and I can't select application permissions. Am I doing something wrong?
