### ISSUE TITLE
[RFC] Make existing components configurable

### ISSUE THREAD

**Issue by acierto** [backstage/backstage#11035]
**Status:** Open for comments

## Need

As a platform developer by using backstage as a foundation I would like to have an instrument to modify existing components with ease: 

replacing a nested component
modifying the parts of components through configuration, like for example:

- adding additional labels/texts
- providing custom icons
- making buttons/icons/labels/links enabled/disabled based on custom logic.  

## Proposal

The proposal is to use a metadata configuration to loading and configuring the components.

The more straightforward and mostly used in React application is to provide it via properties.

As the input of configuration is going to be defined on the top level, then the properties could be provided in a hierarchical way. 

For example:
```

{
  plugins: {
    component: {
      name: 'AboutCard',
      disableIconButton: (context: Context) => context.entity.metadata.annotations?.['backstage.io/edit-url'] && context.permissions.hasRole('ADMIN')
    }
  }
}
```

which will be supplied with an appropriate schema. Like for the above-mentioned example:

```
type Context {
  entity: Entity;
  permissions: Permissions
}

type Properties = {
  plugins: {
    component: {
      name: string;
      disableIconButton: (context: Context) => boolean
    }
  }
}
```

The disadvantage could be with the hassle of propagating the tree of properties across all components.

## Alternatives

Other way could be the alternative way to define metadata/configuration via external configuration files like yaml/json.

### Alternative #1

Same way as now app-config.yaml is used for more high-level configuration.

```
- plugins:
    - name: catalog
      component:
        - name: AboutCard
          disableIconButton: /path/to/file/with/defined/disableIconButtonFunction.ts
          title: /path/to/file/with/defined/renderTitleFunction.ts
```

Where the file contains only 1 function and get a context, based on which the logic of enabling/disabling could be decided. 

For example:

```
type Context {
  entity: Entity;
  permissions: Permissions
}

export default function (context: Context) {
  return context.entity.metadata.annotations?.['backstage.io/edit-url'] && context.permissions.hasRole('ADMIN');
}

```
Same way could be done the replacement of the components.

If for example I would like to replace AboutCard to MyAboutCard cause I want to see it absolutely differently then now, I can do like:
```

- plugins:
    - name: catalog
      component:
        - name: AboutCard
          location: /path/to/file/with/defined/component.ts

```
The concept one of the ways how to make dynamic loading of components is here: https://javascript.plainenglish.io/how-to-load-a-dynamic-script-in-react-2940d30998dd

For this format also can be used type definitions supplied in typescript and validated during runtime with [https://github.com/gcanti/io-ts/](https://github.com/gcanti/io-ts/blob/master/Schema.md)

And on top of that to generate API documentation with tools like http://typedoc.org/

### Alternative #2

It could be also the approach in the middle of the initial proposition and alternative #1.

By supplying as a configuration not a file, but typescript object, which will be consumed with the underlying components not via properties but via Redux store (or similar). 

That way each component "knows" which section of redux store to read. 

This is quite similar how in backstage now works useEntity( ) and other similar methods.

## Risks

The codebase will have an extra abstract layer which has to be propagated to all configurable embedded components and plugins.

Keeping straightforward implementation which can't be extended/modified is more simple to develop and maintain.

But such approach has limitations when it is used by other vendors which would like to do certain things in an own way.

UX decisions, look and feel can have different standards from company to company.

Current approach of copy pasting the code, making a fork of certain part of backstage won't play well in a long run, as it entails the high maintenance costs especially after each major backstage release.

P.S.

This is a quite crucial feature for us in bol.com. 
In case of getting to a mutual conclusion we are open to volunteer our help to implement the proposal.

**Comment by Rugvip** [comment]
Sorry to leave this hanging! It slipped through the cracks :<

Before diving deeper I wanna clarify whether you're looking to primarily configure the components provided by Backstage itself, or also configure components that are internal to plugins as well?

**Comment by acierto** [comment]
I'd say primarily configure the components provided by Backstage itself.
But maybe it's better to design an architecture/solution which will cover both cases, do you have any concerns already about it in mind?

**Comment by Rugvip** [comment]
@acierto ah alright! We actually have something in place for that already, so it may just be a matter of expanding capability/usage of that. It's the [app components](https://github.com/backstage/backstage/blob/8386a32644fe253ec0890a3cf0c6bf29c6faec41/packages/core-app-api/src/app/types.ts#L68-L86) configuration provided to `createApp`, where we could add support for customizing more components, as well as adding more wrappers around them so you don't need to be accessing the app context all the time.

Tbh I'm a bit hesitant to add a lot more options there though, it's not an API that's particularly easy to evolve. I would love to explore more options that perhaps cover both plugin and app customization.

So continuing with the broader scope of a more open customization I'd put this in the area of plugin integration, as in taking an external plugin and customizing it to fit within your app. I think there are a couple more gaps than only customizing components, and I actually suggest we keep the scope broad so we don't need to have too many separate solutions for different aspects of the integration. For example, I actually think there's some overlap between this and #10256.

Before diving into details I wanna highlight some patterns/types of information that we might want to configure:

 - **Static data**: By this I mean plain typically primitive values, such as `title` in your example. Most importantly this information is JSON serializable and can be loaded form any source at runtime.
 - **Dynamic values**: Basically anything that isn't static data, i.e. not JSON serializable. This would include things like custom components or callback functions. These have to exist in the frontend at compile time with our current system.

Another dimension that we can slice things by is the scope of the configuration:

- **Global**: This would be global configuration with a fixed schema that applies to any plugin. The ownership metadata would be an example of that, as well as the app components discussed above.
- **Plugin**: This is configuration that is essentially owned by the plugin. If a plugin is not installed the customization is not available. This tends to be a lot trickier because the available configuration depends on what plugins you have installed. The plugin specific app-config schema would be an example of this.
- **Extension**: This is configuration that is applied to individual plugin extensions, which typically ends up being React component props.

For each solution we can see what dimensions they cover. For example the app components would be a global configuration of dynamic values, while app-config.yaml lets us do both global and plugin configuration of static data. The extensions themselves are a solution for both static and dynamic configuration of extensions, since they are added to the app and configured through code.

The one combination that's completely missing that we really don't have a nice solution for is plugin-specific configuration of dynamic values. Utility APIs are definitely a solution to this, but they don't really work well for more detailed configuration as the overhead of them is quite large. I have some early ideas here but I'm interested what ideas might pop up if we open up the floor :grin:

Sorry if this derails the RFC. If you want to focus on the app components and that part of the problem first then I think we can move this discussion somewhere else, although I'm avoiding driving this too much atm in order to keep our focus in other areas.

**Comment by acierto** [comment]
Hi @Rugvip, good morning! 

Thank you for the detailed answer, let me comment out on these points:

As you mentioned evolving AppComponents can be tough, as this context passed everywhere, and providing more options there will make it harder to work with. What I also see, that this approach completely replaces the component, for some cases it could be a bit too much, if the intention only to hide the button or add some label somewhere. 

Regarding https://github.com/backstage/backstage/pull/10256, it’s more of adding extra metadata to the plugin. I see it more useful when you want to categorise the plugins and create some market place to show them, add ability to add/update/delete on frontend (We did the same thing when I worked in Digital.ai). 

Regarding a split to static and dynamic. That’s not really necessary to keep it on compile time. We still can do a dynamic loading (https://javascript.plainenglish.io/how-to-load-a-dynamic-script-in-react-2940d30998dd?gi=29a316d46369). The main benefit that no backstage core recompilation needed for that. Or maybe I didn’t get you here completely, we can dive deeper in that topic.  

Completely agree with dimensions of configurations. One remark regarding `plugin` configuration. We can avoid trickiness by ignoring the provided configuration for a missing plugin.

“The one combination that's completely missing that we really don't have a nice solution for is plugin-specific configuration of dynamic values.” -> not really sure what kind of challenges do you see here. I described the solution for that in RFC, maybe it wasn’t clear enough :(

No, that definitely doesn’t derail the RFC, it’s more of creating the core and then gradually make each component configurable. I see that exercise well splittable to avoid the avalanche of changes :) 

Please let me know who would be the best person to drive it, where is better to continue the discussion and how can we help with a contribution to make it happen.

**Comment by sagacity** [comment]
@Rugvip

(FYI: I am a coworker of @acierto, so this is not a distinct POV from a different company, but I have some thoughts on the subject as well, maybe it helps spark some more conversation or clarifies things)

So, our goal is to be able to change various aspects of existing components, whether it's changing the title on a button or sometimes adding or removing an additional UI element somewhere nested inside the component.

As far as I understand `AppComponents` is used for really broad customisations at the global level, like replacing the entire theme, the entire sign-in page, etc.

What we'd like to explore is indeed how to perform customisation of both static and dynamic values in various UI components, regardless of whether they're built-in or provided by plugins.

# Approaches
IMO there are a few approaches:

## Approach 1: Configuration based on property names
UI components expose a list of well-known properties. For instance, `MembersListCard` could provide a `noMembers` property that is a `string` with the default value of `This group has no {memberDisplayTitle.toLocaleLowerCase()}.`. Clearly this makes all sorts of assumptions regarding string interpolation and so on, so that might not be desirable. But conceptually it would be similar to what you'd build if you wanted to provide UI translation strings.

Since components can be nested, the property name would have to follow suit: We wouldn't necessarily want to configure the `noMembers` property of _all_ `MembersListCard ` components, we might want to only configure `noMembers` for the `MembersListCard ` that is shown on a certain page. The property names would then have to be nested (e.g. `somePage.membersListCard.noMembers = ...`).

This won't work for dynamic properties, e.g. for properties that are not of type `string` but of type `React.Element`. So...

## Approach 2: Configuration based on types
UI components expose a configuration `type`. Conceptually it would be the same as approach 1, except everything happens in TypeScript and these configuration types can be nested just like you'd nest any kind of type.

Configuration could be made quite extensible, since these types could contain callbacks (e.g. a `shouldShowButton` callback).

At app instantiation this configuration could be provided by the Backstage integrators, similar to how `AppConfigurations` work right now. On top of this a loader could be provided that 🌈  magically 🌈  reads properties from an app-config yaml. This loader would enable the same features as in approach 1.

Plugins could register their configuration types in a central registry so that the integrators' configuration code can access these types via a well-known key (and typed via types provided by the plugin package).

# Challenges
* What is the point where things become TOO configurable and you should just replace the entire component with a custom one?
* How to document and version all of these properties?
* How much performance impact will this have?

Anyway, just my two cents :)

**Comment by acierto** [comment]
As a user of backstage, the access to `createPlugin` or to `createPlugin.provide` is not accessible. In both cases I would need to copy paste `plugins.ts` and provide modifications there. 

Of course this is a viable option. 
But would be nice to minimise it. 
As especially with Backstage migration from one version to another, these `plugins.ts` files would be tend to be modified what will lead to upgrade pain.

What about to provide configuration in less intrusive way, like for example as

![Screenshot 2022-05-06 at 14 28 28](https://user-images.githubusercontent.com/2265094/167131402-0c9f299b-5f76-4ab4-8035-ab2bf31e3337.png)

And in case when nothing was provided, it will just ignore it

![Screenshot 2022-05-06 at 14 28 11](https://user-images.githubusercontent.com/2265094/167131444-2f8d4de3-704e-4b62-af23-606abbca4e6f.png)

It will align with your idea where to apply it, just with slightly different way of supplying the input.

**Comment by Rugvip** [comment]
@acierto I don't really see why we would want to add the complexity of loading in arbitrary external resources tbh? We should be able to organize things so that they are all available at build-time. Loading in a single JS file might be fine, but if we also want that file to be able to access components, React, etc. we immediately end up with some pretty big changes needed.

**Comment by grantila** [comment]
An alternative would be to think of customizing as api-refs. So a component has a default "api" which contains its titles, enable/disable and other properties. Then you can _override_ the api. It might not naturally fit api-refs as is today, but I'll leave that as a mental model for this idea:

To achieve the same customizability, perhaps have a default Provider (i.e. react context) for each customizable component would suffice, if you're then able to replace it with our own custom provider.

You could then configure the plugin by replacing the default Provider for MembersListCard by your own, potentially re-using the default one internally (`useDefaultProvider` here). This would allow for async work to happen too, to lookup how to actually configure.

Super-pseudo:
```tsx
export MyMembersListCardProvider() {
    const defaultValue = useDefaultProvider(MembersListCardProvider);

    const value = {
        ...defaultValue,
        title: 'Not available',
        enabled: false,
    };

    return <MembersListCardProvider value={value}>
        {children}
    </MembersListCardProvider>
}

somehowReconfigure({
    MembersListCardProvider: MyMembersListCardProvider
});
```

This could surely be generalized and become an architectural design pattern, with helper functions / hooks etc. to make it very easy to work with and not add too much boilerplate everywhere. It would also make it relatively easy to replace individual sub-components (if they're in the provider) if you can wrap them around your own customizations. It would ultimately be very composable, and easily testable too.

**Comment by Rugvip** [comment]
@grantila I think that's a pattern that can make sense as an internal implementation of this, but perhaps not what you'd expose as the top-level API? Even with your example it's totally up to each plugin whether to implement the configuration like that though.

One thing that I feel is really important to strive for is to keep the external API surface input only, so that for example moving a field from required to optional is not a breaking change. There can be some subsets where that isn't true, but overall it simplifies the maintenance of the plugins a lot if you lean towards that. For example in this case, removing the `title` field from the default values might be breaking.

**Comment by acierto** [comment]
I agree with you @Rugvip, `reconfigure` shouldn't allow to add extra fields, but only override default. 

I incorporated feedback given @grantila to keep the configuration in registry with an ability to look it up with help of React context.

I kept the naming of it as `metadata`, not `provider`, as `provider` in backstage codebase is appended to Api, Routing, Themes, etc.

PR: https://github.com/backstage/backstage/pull/11404

**Comment by acierto** [comment]
![Screenshot 2022-05-17 at 20 17 44](https://user-images.githubusercontent.com/2265094/168883004-addeb957-5b5a-43c9-8704-c2d222ea1b29.png)

**Comment by ericis** [comment]
This would also be interesting from a corporate design system perspective. We have our own design system and it would be AMAZING (and complicated) to be able to swap out entire components to implement an even deeper corporate "theme" for Backstage that goes beyond styles.
