### ISSUE TITLE
[Feature Request] Storybook controls

### ISSUE THREAD

**Issue by leschaller1** [backstage/backstage#11042]
## Feature Suggestion

It would be valuable to add Storybook controls to components within the component library so developers/designers can explore the different variations available for use.

https://storybook.js.org/docs/react/essentials/controls

**Comment by Rugvip** [comment]
@leschaller1 Agreed! 👍 

Perhaps also aggregate some of the very similar stories as well, using a control to select the styles, like all the [header stories](https://backstage.io/storybook/?path=/story/layout-header--apis). Either way we should ofc start with enabling the controls addon as the first step.

Is this something you would like to contribe? Otherwise I think we could open this up as a good first issue

**Comment by leschaller1** [comment]
Awesome! Yeah I think that's a great idea re: aggregating similar stories. I could definitely help out and start by enabling the controls addon

**Comment by leschaller1** [comment]
I've made the changes locally - how do I go about getting write access to create a PR?

**Comment by leschaller1** [comment]
PR here :) https://github.com/backstage/backstage/pull/11344

**Comment by Rugvip** [comment]
Done!
