### ISSUE TITLE
Authentication Error | User not found [Google Provider]

### ISSUE THREAD

**Issue by padupe** [backstage/backstage#11049]
## Expected Behavior
Authentication Plugin allow the user to access the platform.

## Actual Behavior
Error message.
![image](https://user-images.githubusercontent.com/72894267/164817859-b2e38730-23a6-4cd7-8cfd-1271511fd031.png)

## Steps to Reproduce

`packages/backend/src/plugins/auth.ts`
```typescript
import {
  createRouter,
  providers,
  defaultAuthProviderFactories,
} from '@backstage/plugin-auth-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    ...env,
    providerFactories: {
      ...defaultAuthProviderFactories,
      google: providers.google.create({
        signIn: {
          resolver:
            providers.google.resolvers.emailLocalPartMatchingUserEntityName(),
        },
      })
    },
  });
}
```

## Context
After releasing https://github.com/backstage/backstage/blob/master/plugins/auth-backend/CHANGELOG.md#0130 we started to encounter this issue.

## Your Environment
Node.js v16.14.2
Yarn 1.22.17
Ubuntu 20.04.4 LTS

**Comment by marcus-crane** [comment]
Is there a User entity in Backstage with that email address? To be clear, Backstage has no concept of accounts but rather just matches the identifying user to a User entity registered within Backstage.

**Comment by jhaals** [comment]
As Marcus points out the resolver used tries to match with an existing user in the catalog. It's recommended to ingest your users into the catalog if possible.

There's currently no out of the box resolvers for scenarios without users in the catalog but documentation explains how to craft your own resolver function if need be https://backstage.io/docs/auth/identity-resolver#sign-in-resolvers

**Comment by padupe** [comment]
Hello @marcus-crane  and @jhaals , as I informed you, before the release of this new version, the Google authenticator worked perfectly.
With this new release, will it be necessary to register the employee's e-mail database?

**Comment by radicaled42** [comment]
> As Marcus points out the resolver used tries to match with an existing user in the catalog. It's recommended to ingest your users into the catalog if possible.
> 
> There's currently no out of the box resolvers for scenarios without users in the catalog but documentation explains how to craft your own resolver function if need be https://backstage.io/docs/auth/identity-resolver#sign-in-resolvers

Sorry, to step-in in this issue, but I'm having the same issue with the microsft provider.
I need to do this to "ingest" the user for the microsoft provider?

https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/README.md

Thanks

**Comment by dmckernanacv** [comment]
Same issue with Okta, we use the github-org discovery to read in users / groups for code ownership, but Okta for logging into backstage.
Since updating authentication is totally broken and **there is no way to link Okta emails to Github users**, and **Github does not provider user emails** when syncing users to Backstage, so I cannot even write a custom resolver if I wanted to.

This was a bogus move to require catalogged Users in order to authenticate, it severely restricts the product.

**Comment by MartinWallgren** [comment]
We (Axis Communications) just got bitten by this using the Microsoft provider.

Are there any arguments against creating a user entity as part of the auth resolver?

**Comment by Rugvip** [comment]
Sorry we didn't document the pattern of bypassing the catalog during login more clearly. It's apparent it's something a lot of you do. Here's an example of a sign-in resolver that uses the local part of the email directly as the user entity name, without looking up the user in the catalog:

```ts
okta: providers.okta.create({
  signIn: {
    resolver: async ({ profile }, ctx) => {
      if (!profile.email) {
        throw new Error(
          'Login failed, user profile does not contain an email',
        );
      }
      const [localPart] = profile.email.split('@');

      const userEntityRef = stringifyEntityRef({
        kind: 'User',
        name: localPart,
        namespace: DEFAULT_NAMESPACE,
      });
      return ctx.issueToken({
        claims: {
          sub: userEntityRef,
          ent: [userEntityRef],
        },
      });
    },
  },
}),
```

The example here is with the Okta provider, but the general pattern applies to all providers. `stringifyEntityRef` and `DEFAULT_NAMESPACE` are both imported from `@backstage/catalog-model`. We'll probably have a few more of these built in in the future, gonna make sure we add it to docs too.

Regarding the removal of the default sign-in resolver for each provider, it was partly to remove confusion, but most importantly a security fix. Allowing all providers to be used for sign-in by default leads to at best confusing behavior, and at work an insecure setup.

**Comment by MartinWallgren** [comment]
Is there any downside to actually create a catalog item in the resolver as opposed to just bypass the catalog?
That way the catalog would be populated as needed.

**Comment by Rugvip** [comment]
> Is there any downside to actually create a catalog item in the resolver as opposed to just bypass the catalog? That way the catalog would be populated as needed.

There is no way to do that atm, since the catalog does not have a write API. A generic write API opens up for some pretty tricky questions wrt security, so we'd be very cautious going down that route.

A possible way forward could be an optional entity provider for the catalog that is able to dynamically create catalog users if they are missing, and have that tightly coupled with the auth backend with access control. I'm a bit torn on the value of that though, since you'd be missing out on the overall organizational data with groups represented. There also not a ton of benefit on top of the existing method of not representing users in the catalog that I can see. Could still be something to pursue as an option though.

**Comment by simonstamm** [comment]
Hey @Rugvip, I'm also interested in creating user entities when they sign in. The benefit of it is the possibility to add users to defined groups like `members: ["@John.Doe", "@Foo.Bar"]` without defining them manually as user entity in a yaml file. Unfortunately I can't use an entity provider which syncs the organization to the catalog because our Active Directory has more than 300k groups (it's... well... a bit old :-)). Or is there any other way I can make use of the "Owned" feature in the catalog view (thats actually what we want to achieve with the member definition)?

**Comment by jkNC** [comment]
Since changing to this endpoints under /catalog/api seems to get an unauthorised? I am not sure if it related
