### ISSUE TITLE
plugin-catalog: entity validation endpoint

### ISSUE THREAD

**Issue by zhammer** [backstage/backstage#11179]
## Feature Suggestion

provide an endpoint from backstage that receives entity defintions and returns at the least validation errors, at most a diff of the catalog were those entities to be ingested (a la `https://<backstage-host>/api/catalog/locations?dryRun=true`

## Context

one of the biggest inhibitors to backstage adoption / experimentation in our organization has been a lack of quick feedback validation of entities (e.g. `catalog-info.yml` files.) the initial recommendation for validating an entity was to register changes from a dev branch to a staging instance of backstage, though this has become less ideal due to related entities not existing on our staging instance and `$text:` references (i.e. for openapi specs) not being accessible from our staging environment.

we see that the "analyze" step of the "Register an existing component" flow hits `https://<backstage-host>/api/catalog/locations?dryRun=true`, which could potentially be hit from CI runs to inspect `catalog-info.yml` changes from CI runs (e.g. are there validation errors, what entities will be created/changed, etc.). however, this step requires a location that can be accessed from our backstage instance, e.g. a url to a branch on our VCS. ideally, developers could get feedback on an entity configuration from their local environments, without pushing code to a remote, allowing for quick iteration on creating new entities and exploring new backstage features for existing ones.

it could be nice to have an endpoint where we can send an entity configuration blob in the payload and receive back information similar to what `/location?dryRun=true` returns. (of course this would be a bit different as there wouldn't actually be a location being generated.) we would potentially be interested in wrapping a call to that endpoint with some custom yaml validation to match our own conventions. though if this endpoint could take into account any [custom validators](https://backstage.io/docs/features/software-catalog/extending-the-model#changing-the-validation-rules-for-the-entity-envelope-or-metadata-fields) that could be great.

fwiw we haven't tried out https://github.com/RoadieHQ/backstage-entity-validator yet.

**Comment by marcus-crane** [comment]
This actually exists already and was added in v1.1.0: `https://backstage.service.us-west-2.aws.vendhq.com/api/catalog/validate-entity`

You can POST a JSON object with the following shape:

```json
{
  "entity": "<json representation of catalog entry",
  "location": "<location of the entity, can be stubbed out>"
}
```

It returns a 200 if the entity is valid or a 400 if there are issues

![CleanShot 2022-04-30 at 18 59 01](https://user-images.githubusercontent.com/14816406/166095553-70363b83-1783-43e8-b273-4c60abc3b047.png)


![CleanShot 2022-04-30 at 18 59 30](https://user-images.githubusercontent.com/14816406/166095614-1825b3c7-0b37-4ff2-a77a-fd5a98767247.png)

Having said that, it can do with some enhancement as it only shows you the first detected issue. If you fix that and another one shows up, you basically have to rinse and repeat than fixing everything in one go.

It also only supports one entity whereas a repo may commonly have multiple entities (system + components) so each entry has to be posted separately rather than checking all entities at ones.

Personally, I opted to use the RoadieHQ entity validator but also has the same issues of only showing the first detected issue, even if there are multiple. Your CI pipeline may not necessarily have network reachability of your Backstage instance, as ours doesn't in which case, a locally run validator is a better choice.

If you do opt to use the Roadie validator, I can recommend using it in conjunction with xargs to "autodiscover" catalog files or else it may discover other yaml files that will choke the tool: https://github.com/RoadieHQ/backstage-entity-validator/issues/28#issuecomment-1112096677

**Comment by zhammer** [comment]
Ahhh interesting. I’ll take a look at both. Also going to take a look at the code behind the location register dry run endpoint. Very curious if that could be exposed.

**Comment by benjdlambert** [comment]
@zhammer can we close this now?

**Comment by zhammer** [comment]
sure - i may make another issue once we give the current validation endpoint a look!

**Comment by benjdlambert** [comment]
Perfect! thanks!
