### ISSUE TITLE
ADR plugin does not support location references

### ISSUE THREAD

**Issue by julioz** [backstage/backstage#11247]
## Expected Behavior

Similar to how the TechDocs annotation supports location references via prefixes like `dir:` and `url:`, I would expect the ADR plugin annotation to do the same.

## Actual Behavior

The plugin hardcodes file paths or URLs with the location reference prefix. 

## Steps to Reproduce

1. Set up the ADR frontend and backend plugins
2. Set an entity with annotation (replace `my-org` and `my-project` with suitable values)
```
backstage.io/adr-location: url:https://github.com/my-org/my-project/tree/master/docs/adrs
```
3. Frontend displays an error:
```
Warning: Failed to fetch ADRs

No auth provider available for 'url:https://github.com/my-org/my-project/tree/master/docs/adrs', see https://backstage.io/link?scm-auth
```

## Context

This makes it confusing for engineers (i.e they need to look up the docs for each annotation instead of following a single pattern everywhere).

cc @kuangp Curious on your opinion on how the plugin should work.

**Comment by kuangp** [comment]
I [initially considered](https://github.com/backstage/backstage/pull/10817#discussion_r855392246) supporting `dir:` and `url:` prefixes in a similar manner to the TechDocs plugin (as a future enhancement). However, I was advised that I can achieve similar support using `ScmIntegrations` without the need to explicitly parse prefixes. As a result, you're able to reference relative/absolute locations simply by specifying them directly eg. `backstage.io/adr-location: docs/adrs` and `backstage.io/adr-location: https://github.com/my-org/my-project/tree/master/docs/adrs` should be parsed correctly without the need for prefixes.

I don't there is a standard convention for annotation formats that reference URL locations (at least there is no [ADR](https://backstage.io/docs/architecture-decisions/adrs-overview) for it 😅 ). I imagine there shouldn't be one since each plugin is self contained and developed individually, typically by external contributors.

cc: @Rugvip @iamEAP on their thoughts here regarding consistency among plugins in this area. Perhaps there's a way to provide more standard plugin "dev utils" so each plugin can easily reuse common logic? eg. a `readLocationAnnoation(entity: Entity, annotationName: string): string` util function that given a annotation name will read and resolve a "location-type" annotation value from the entity for you (that supports relative/absolute values)

**Comment by Rugvip** [comment]
@backstage/techdocs-core curious what your thoughts are on the dir/url prefix, is it needed still or mostly there because of history? I imagine removing it would likely be a somewhat straightforward backwards compatible change?

**Comment by iamEAP** [comment]
> _is it needed still or mostly there because of history?_

The distinction is quite intentional these days. `dir:` is shorthand for "the given directory, relative to the entity's location."

And it's there to make it so that one does not need to know the semantics/details of ScmIntegration/UrlReader to be able to enable TechDocs for an entity (which App Integrators might know but which End Users would almost certainly not know)

**Comment by Rugvip** [comment]
@iamEAP `dir:` does use the resolve logic from the integrations though right? Afaik it kind of just acts like an explicit relative URL specifier

**Comment by iamEAP** [comment]
> _`dir:` does use the resolve logic from the integrations though right?_

Hmmm....  Yeah, I suppose so.  @ottosichert, I remember you had a hand in reviewing the PR that introduced location-relative TechDocs ref annotation values; I don't remember why we landed on explicitly specifying `dir` and `url`.  Do you recall?

**Comment by batazor** [comment]
@kuangp Can you suggest which format should I use in the end?

I tried to use `backstage.io/adr-location: https://github.com/my-org/my-repo/tree/main/services/service-A/docs/adrs` but I got `Warning: Failed to fetch ADRs`

**Comment by PepeuCps** [comment]
> @kuangp Can you suggest which format should I use in the end?
> 
> I tried to use `backstage.io/adr-location: https://github.com/my-org/my-repo/tree/main/services/service-A/docs/adrs` but I got `Warning: Failed to fetch ADRs`

Hi @kuangp ... Don't use the absolute path with "tree", instead use "blob", like:  https://github.com/my-org/my-repo/**blob**/main/services/service-A/docs/adrs

Regards,
Pedro
