### ISSUE TITLE
NotFoundError: Unable to read url

### ISSUE THREAD

**Issue by shivampathak** [backstage/backstage#11296]
I have been trying to register an existing repository to my local backstage.
I created a github app and linked the client id and secret. I created a dummmy catalog-info.yaml in my repo but when I try registering it, it gives the following error:

```
{"error":{"name":"Error","message":"NotFoundError: Unable to read url, NotFoundError: https://github.com/shivampathak/trial/tree/main/blob/main/catalog-info.yaml could not be read as https://api.github.com/repos/shivampathak/trial/tree/main/contents/catalog-info.yaml?ref=main, 404 Not Found","level":"error","service":"backstage"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":500}}
```

**Comment by lalit774** [comment]
@shivampathak  Check Github integration or it is duplicate to  #11149

**Comment by freben** [comment]
Yeah indeed check the integration, `shivampathak/trial` seems to be a private repo or not exist (it's a 404 either way) and you have to make sure that the configured token in your github integration has access to it.

**Comment by lfialho** [comment]
I have the same problem, I believe itts happening because our repositories implement group based access. I had to setup token authentication using the token from a user that is in a specific github group and this group have access to the repositories that we are trying to discover. Setting the github integration using app authentication is not working for us

**Comment by phil1234567891011** [comment]
same issue here, it is a private repo as I make a backstage integration poc for our organization

how can we solve this ?
