### ISSUE TITLE
Enable access to DefaultEntitiesCatalog

### ISSUE THREAD

**Issue by tkrop** [backstage/backstage#11614]
## Feature Suggestion
Please expose the `(Default)EntitiesCatalog` so that `EntityProviders` and `EntityProcessor` can make use of them to access information in previously stored entities.

## Possible Implementation
Just export the `DefaultEntitiesCatalog` (and possibly the `AuthorizedEntitiesCatalog`) so that we can create an instance using the database client.

## Context
We are trying to increase the reliability of `EntityProviders` and `EntityProcessors` by falling back to previously stored entity information instead of failing to create/update entities in case of missing information through failing service requests. The most simple way would be to reuse the information in previously stored entities instead of implementing an new fallback caching solution.

Unfortunately, the access to the `EntitiesCatalog` that we used for this was removed (pull request backstage/backstage#10196), so that we currently have no advanced API to access the entities in a database agnostic way - if I have not overlooked an option. Using a copy of the `DefaultEntitiesCatalog` is as little preferable as accessing the database directly. So exposing the `DefaultEntitiesCatalog` seems the natural solution for all Providers, Processors, and backend-plugins that need to access entities - for `backend-plugins` exposing the `AuthorizedEntitiesCatalog` may also be helpful.

**Comment by Rugvip** [comment]
Hi! Wondering whether you've considered using https://backstage.io/docs/features/software-catalog/external-integrations#caching-processing-results for this use-case? One of the ideas with the caching is to be able to provide a fallback to cached information in case of an error fetching up-to-date information.

**Comment by tkrop** [comment]
Nice, but unfortunately not available in most of our services especially not in the Data Lake we are mainly trying to address here.

**Comment by Rugvip** [comment]
Could you elaborate a bit more on why it's not available?

Let's also pinpoint the pieces from the `EntitiesCatalog` that you need, is it only the `entities` method? In that case it may be that what you want to do here is to simply provide a `CatalogClient` instance to your processor so that it can call back to the catalog read API? I'm feeling that at a high level that is the correct abstraction, because catalog ingestion and reading are quite far separate and can potentially even be deployed as separate services.

**Comment by tkrop** [comment]
> Could you elaborate a bit more on why it's not available?

Often we have just not implemented `ETags` in our RESTful APIs since, e.g. since we utilize event streams via [Nakadi](https://nakadi.io/) we rarely poll on RESTful APIs to check for updates. So the pressure is low to implement this feature.

> Let's also pinpoint the pieces from the EntitiesCatalog that you need, is it only the entities method?

Yes, it is only the `entities` method we are currently going for, but it is not necessarily the previous version of the entity we are going to load.

> In that case it may be that what you want to do here is to simply provide a `CatalogClient` instance to your processor so that it can call back to the catalog read API?

Not a _remote_  `CatalogClient` as defined in Backstage currently (see https://github.com/backstage/backstage/blob/master/packages/catalog-client/src/CatalogClient.ts), but making a _local_ abstraction available would be very appreciated - but the differences to what I asked for would not be huge I think.

**Comment by Rugvip** [comment]
Alright, is using a remote `CatalogClient` good enough for you do you think? It'll resolve to local loopback so you're mainly paying for a bit of serialization, but I'm assuming you're not shipping any big amounts of data anyway?

**Comment by tkrop** [comment]
Using a _remote_ `CatalogClient` would create a lot of unnecessary overhead. Why should we create this overhead for a simple database query?

However, since you already exposed a _remote_ `CatalogClient` this has technically creating a similar _local_  `CatalogClient` abstraction. Why don't you expose this abstraction, if you are reluctant to export the `DefaultEntitiesCatalog`?

**Comment by tkrop** [comment]
Using a _remote_ `CatalogClient` would create a lot of unnecessary overhead. Why should we create this overhead for a simple database query?

In addition, since you already exposed a _remote_ `CatalogClient` this technically creates a similar binding to a _local_  `CatalogClient` abstraction. Why not exposing this abstraction of a `LocalCatalogClient`, if you are reluctant to export the `DefaultEntitiesCatalog`?

**Comment by Rugvip** [comment]
@tkrop A local one could be alright, I think we could even leave most of the methods as throwing `NotImplementedError`s? We'd need to be a bit careful with it to make sure that we don't end up bypassing access control checks, and probably discourage use from other plugins too.

Is it's something you'd like to contribute?

**Comment by jhaals** [comment]
Hi, I realise that I'm slightly late in this discussion but it really sounds like the cache abilities in the processing API would allow for having a fallback returning cached/stale data in the case of a service failure. Etag is just an optimisation that you do not have to support for this use case. I'm afraid that just exposing a local client which also has a security implications is a slightly hacky solution for something that should be available in the existing processing APIs.

**Comment by tkrop** [comment]
@jhaals After considering your comment some time, I think the envisioned fallback is assuming a different entity provider and processing model.

Our entity providers integrate multiple data sources into a complex base entity. We use processors only to enrich entities with derive relations and calculated facts. This approach keeps the responsibilities of providers and processors as clear and separated as possible.

Anyhow, as far as I can see, the fallback to the previous entity is not available for manually scheduled entity providers. If it would be available, this would be an option, however, I'm a bit reluctant to resolve information by default that is only needed in exceptions.

**Comment by freben** [comment]
Here comes an angle that's even later to the game.

When there's merging and processing of data going on, some have opted to do that collation in a separate, stateful service. This of course sounds like extra work, and it is, but it also means that you are free to use any technology and setup that your company are already familiar with and can maintain the easiest. If you have an event based setup with a fixed set of sources, maybe you will even be able to store a couple of contributing pieces of info from those sources, trigger the catalog entity provider ALSO with an event when something changes somewhere - and then the provider just mass-mirrors the already baked-and-ready data that your collating service holds. That statefulness completely sidesteps any catalog specific semantics in terms of refreshes - your newly made authority already holds all the required information at all times.

Let me know if you think that that's compelling or just crazy talk :)

**Comment by tkrop** [comment]
@freben may totally make sense to allow providers to inject their entities via an external interface, however, I would still expect the injected entities to be processed by the processing pipeline and stitched together. I remember we have started a similar model in the beginning. Do you plan to introduce a RESTful API for this?

**Comment by tkrop** [comment]
Anyhow, we are loosing track here.

Contributing a `LocalCatalogClient` would be our first choice, to enable local resolution of entities from providers and other backend plugins. Please vote :+1:  or :-1:  whether this contribution would be acceptable.

If you plan to release an API to enable remote entity providers, we may reconsider our contribution to speed up the API development - you may signal this plan by :rocket:

**Comment by tkrop** [comment]
@freben Okay, I get your point. I can see the caveats of providing a `POST /entities`-endpoint too and would not use it in this simple barely authorized form.

I must admit that an`authoritative gateway` for a presentation specialized, single use case entity provider is not a service I would design - since I don't see that the value justifies the development and maintenance overhead it creates. In my opinion a service should always cover more than a single use case to justify its overhead.

Leaves the question about :+1: and :-1: on contributing a `LocalCatalogClient`?

**Comment by freben** [comment]
So we talked about it this morning, and would prefer if we didn't add extra code for this unless absolutely strictly necessary, and instead first evaluate the path that everybody else uses - namely using the plain catalog client. The serialization / deserialization is generally not a big concern, even though of course it may depend on the circumstances. Calling out to another host can sometimes even be beneficial, depending on how you do your load balancing and routing, since the other host may be struggling less than the one you are currently making the call from.

What you can do, is to create a catalog client instance in your catalog setup code (with basically a plain `new CatalogClient`), but passing in the `discoveryApi` as a custom-made one that only supports `catalog` as the plugin ID and always resolves to the correct port on localhost. That will at least get rid of the network hop, if that's a concern.

There's one more thing, as you alluded to, which is authorization. You'd likely not pass along any auth at all for these calls, but this is one of the things that start to turn into a bit of a gray area - your processing is now non-local and may become less stable, and it may be a bit unclear what the processing should have access to or not, in the surroundings - what if you start to leak "private" entity data from other parts of the catalog into entities that aren't protected by permissions? What about the nature of distributed processing where you get read/write races between entities that depend on each other ... Etc.

I'll reiterate that we slimmed down these interfaces and removed almost all exports very explicitly before the 1.0 release, because we felt that maintaining them and the promises they make would hamper our ability to quickly iterate on the internals going forward. The public API surface was a good "firewall", we felt. We may want to make things event driven, caching, CQRS style etc in new ways, and any surfacing of imperative stuff like this put plans like that at risk.

I'm in no way making any promises and let's not go along this path at this moment because we likely aren't able to commit to that kind of change short term, but another angle just to show alternative lines of thought ... it might be to extend the Connection object of entity providers to let them grab the previous bucket contents if they want to, only paying that read cost if you ask for it. That would be a lot more purpose driven and contained, than to expose internal API surfaces and their entire contracts as a general purpose use-at-any-time-in-any-way surface.

I still like the external service approach. For us, this service was a useful aggregator not just for us, but for general consumption. Often when these needs arise, you'll find that the rest of the org really would appreciate such an aggregated view of things as well because they have similar needs.
