### ISSUE TITLE
Document the backend architecture 

### ISSUE THREAD

**Issue by freben** [backstage/backstage#1169]
It's currently not clearly documented how the frontend-backend integrations are meant to look, and what choices there are to make when building plugin backends.

Now that things are solidifying, we should add this documentation, probably copying parts of the internal backend RFC. Make sure that it contains overview diagrams detailing the various possible architectures:

- Frontend calls services directly 
- Frontend proxies through the backend to reach services
- Frontend calls small "glue" backend plugin that talks to services
- Frontend calls separate integration backend that talks to services 
- Other?

**Comment by dtuite** [comment]
A section on when to use a database would also be great.

In addition to explanations of each of the possible plugin architectures it would be great to understand the pros and cons of each architecture and the reasons a plugin author would choose one of the others.

For example, it seems like the lighthouse plugin has a backend because lighthouse has no internal concept of storing results and viewing their change over time. CirclCI, on the other hand, does this automatically.

It would also be great to get a sense of how plugins exist inside Spotify for each type of arch. This would help people estimate how complicated it will be to stand up a large Backstage application with many plugins.

**Comment by daviddyball** [comment]
Will this include swagger docs or similar for call/responses to backends? Currently it's hard to decipher exactly what format the front-end requires from a backend service without understanding the front-end code.

**Comment by adamdmharvey** [comment]
Reviewing the PR @dtuite added about a month after this ticket was opened via https://github.com/backstage/backstage/pull/1685, I have a feeling this story is completed. Could be further clarified, but the listing of the different types of plugin styles I think gets to the root of the ask in this ticket: 
https://backstage.io/docs/overview/architecture-overview#plugins-and-plugin-backends

Suggest could be closed?

**Comment by freben** [comment]
Agreed. I think this is covered well enough. Thanks for checking in on these old tickets!
