### ISSUE TITLE
Identity Backend: Github Adapter (Stretch)

### ISSUE THREAD

**Issue by soapraj** [backstage/backstage#1192]
Add a GitHub adapter that can read user, teams and org information from GitHub

**Comment by adamdmharvey** [comment]
I believe this has been implemented via: https://github.com/backstage/backstage/pull/2669

Though to be honest, it doesn't seem to me to be fully documented.  Wonder if to close this out, we want to add something here?

https://backstage.io/docs/features/software-catalog/configuration#static-location-configuration

**Comment by benjdlambert** [comment]
Think we can close this legacy thing now anyway! :)

**Comment by dekoding** [comment]
Hey guys, I'm a developer with HP, and this still isn't working - we can authenticate with Github (or Github Enterprise), but we don't get identity.

We're actively working on this, and may put in a pull request if we can get it working. Is this closed prematurely? Or is this one of those cases where it's not going to be fixed because the IdentityApi is going to be replaced with the Ownership model?

**Comment by dekoding** [comment]
> Hi! Can you describe what seems to be missing or not matching? Am I understanding you correctly that it's the "Owned" part that isn't working the way you expect it to?

Hi, thanks for the quick reply! We're still learning our way around Backstage, so this may be a knowledge deficiency more than anything else. Is it expected that if you authenticate with Github Enterprise, a user is created in the catalog, which you could then put in the `spec.owner` field and have it listed? If so, that is something I'll reach out on Discord about. Like I said, we are **very** new to this, but excited about Backstage's possibilities, and want to get a POC working as soon as possible.

**Comment by freben** [comment]
Alright, let's continue on Discord! I saw you posted the question.
