### ISSUE TITLE
scaffolder: Gitlab Ci/Cd project vars publisher for scaffolding 

### ISSUE THREAD

**Issue by aurorasean** [backstage/backstage#12014]
## Summary

When publishing GitLab template, some pipelines might/will require a Ci/Cd setting to be applied before the pipeline will work

## Context

For a given project/template output the pipeline might require extra vars to be set before it will build

Example: 
ENV vars for Security scan (password for dev/prod env version)

(yes the password should not be stored there, but it is an example)

## Use case example
In a template
![image](https://user-images.githubusercontent.com/5121342/173563642-de4f764b-b8e6-4b0b-811f-6ad77a655005.png)

Outputs onto the project
![image](https://user-images.githubusercontent.com/5121342/173563909-33d6e384-8a2c-4e5a-aff5-84e1446b9e26.png)

When specifying "DEFAULT_VALUE" it should look in the app-config for the key

**Comment by darylgraham** [comment]
I don't know if the Gitlab variables implementation has been improved since issue was raised, but as of now you can specify variables at a group level and they are automatically inherited to all sub-groups and projects within. To my mind this reduces the need for this issue, but I obviously can't speak for everyone's Gitlab implementation.
