### ISSUE TITLE
Catalog table filters are not cleared when changing entity kind

### ISSUE THREAD

**Issue by jkNC** [backstage/backstage#12081]
## Expected Behavior

Filter to be cleared when changing type

## Actual Behavior

Filter is still applied when it make no sense

## Steps to Reproduce

View Catalog Components
Filter Catalog by a tag
Change to View Catalog Users (that cannot have tags)
No results shown however tag option disappears so unclear results are filtered

**Comment by jhaals** [comment]
Hi @jkNC, thanks for noticing this. I can confirm that this is the case and we should make sure that the filters are reset when the entity kind changes.

**Comment by benjdlambert** [comment]
Do you want to contribute this @jkNC? Maybe if the filter is not available for the new kind it should be cleared but others should be persisted? Think that this is the most broken behaviour right now at least I feel.

**Comment by sarahpmedeiros** [comment]
Hi, are there any plans to tackle this bug? This is a blocker for my team and I am willing to take on the work.

**Comment by freben** [comment]
@sarahpmedeiros Go right ahead! We'd appreciate the help.

**Comment by sarahpmedeiros** [comment]
@freben any ideas on the approach? I was thinking some logic along the lines of:
in the onchange from kindA to kindB
ForEach enabled filter, is it available for kindB? if no then update the filters 

But I cannot figure how to check if the filter is available for kindB.

Any suggestions would be appreciated!

**Comment by freben** [comment]
I don't have any specific tips off the top of my head, sorry - essentially, making filtering systems is really tricky, and this probably needs some digging and thinking and mild restructuring.

It seems to me that, whenever ANYTHING changes in a filter set, ALL of the other filters might conceivably need to reconsider themselves entirely, and probably that work has to happen inside the filter itself since it's the only one that knows its own semantics. Like, for example, if you have a type filter enabled with selected value "type-foo", and then you switch kind and the new kind DOES have types but "type-foo" has zero hits, then maybe that filter should just clear itself automatically. Or should it? What would a user really expect to happen under those circumstances - is it unexpected that you switch one thing and then other things "magically" happen behind your back that weren't your own doing? :) Another approach that some filter systems use is that they _allow_ you to make the change in kind, but it's clear to the user that doing this particular switch will lead to zero hits, because the filter option had a zero next to it before I clicked it.

I dunno. These are important questions and I'm no UX expert myself honestly :) I just want users to have the largest amount of capability, with the least amount of surprise.

**Comment by sarahpmedeiros** [comment]
@freben thank you for the advice! I wasn't sure if I was missing something obvious, I will keep brainstorming!

**Comment by sarahpmedeiros** [comment]
After spending time getting to know the filter space, I have a couple of questions I was hoping you could answer:

Why is `queryParameters` in `plugins/catalog-react/src/hooks/useEntityListProvider.tsx` only set when there are external source changes to the URL? On lines 127-130 there is an explanation for what the code does but not the why. 

I would like to know why because currently the way it is being set is creating an issue with my proposed solution, I would like to refactor the functionality but I don't want to unknowingly break something. 

For my solution I was thinking we could clear the selected filters on kind change. But when you clear the filters using `updateFilters()`, queryParamters does not get updated. I will include a screen recording of this behavior. 

https://user-images.githubusercontent.com/14253893/205385490-15e1f9e7-ce91-4b28-bd3d-38fc42f588c0.mov

**Comment by freben** [comment]
I'm not personally 100% in the know about this code either. What I can say is, there's an important balance to strike regarding what reacts to what - i.e., in what direction that the flow of control travels. You can easily get into a situation where a location update triggers a filter update which then updates the location which again triggers filter updates ... ad infinitum. At the same time, you need to be able to have a Link inside the catalog page, which links to the same page with different query parameters set, and the filter sets updating themselves to mirror that.

I think the most important point about this whole ticket is: If a control on the left side is hidden, _it should not have an effect on filtering_. Other concerns and tweaks can be sugar on top of that foundation, since the biggest confusion is when the "owner" picker disappears and you still see zero things because it keeps filtering ownership on a kind that doesn't even have owners, or something equally silly.

**Comment by sarahpmedeiros** [comment]
@freben I created a draft PR https://github.com/backstage/backstage/pull/15058 could you take a look?

**Comment by benjdlambert** [comment]
Closing as this got merged! 🎉
