### ISSUE TITLE
[azure-devops] Improve CI/CD features for multi-stage pipelines

### ISSUE THREAD

**Issue by nmarinel** [backstage/backstage#12093]
## Feature Suggestion

The Azure Devops release pipeline UI (e.g. https://dev.azure.com/org/proj/_release?_a=releases&view=mine&definitionId=1) leaves something to be desired. For a given release definition, you can bring up a list of every release created for that definition and the deployment status of every stage in the release. It would be nice to have a view with a single row per release definition that shows the latest _version_ deployed to each stage. Of course, the obvious complication is that stages can change from release to release as the definition changes, but that's not insurmountable. 

A page in Backstage that provides this view would solve this shortcoming in Azure Devops.

## Possible Implementation

| Release Definition | | | | | 
| -- | -- | -- | -- | -- | 
| MyAwesomeProduct | Dev:v2.9.0 | QA:v2.8.1 | Staging:v2.8.0 | Production:v2.8.0 | 
| MyOtherProduct | Dev:v2.0.1 | QA:v2.0.0 | Staging:v2.0.0 | Prod:v1.3.0 | 
| SomeInternalTool | Dev:v1.1 | Prod:v1.1 | | |

## Context

The ability to see a single page that shows all release definitions, their stages, and the latest version deployed to each stage would benefit release managers who want to see the latest version of a given service in each environment at a glance.

This issue was created to help @awanlin, @nmarinel, and... perhaps @Balfa (???) coordinate their efforts.

**Comment by Balfa** [comment]
My understanding is that you're wishing that ADO itself had a view like the following:
| Release          | Dev    | QA     | Staging | Production |
|------------------|--------|--------|---------|------------|
| MyAwesomeProduct | v2.9.0 | v2.8.1 | v2.8.0  | v2.8.0     |
| MyOtherProduct   | v2.0.1 | v2.0.0 | v2.0.0  | v1.3.0     |
| SomeInternalTool | v1.1   | v1.1   | v1.1    | v1.1       |

But it doesn't, so you're hoping to implement something in backstage?

And the complication you're talking about is that not every product lines up as above with a "Dev", "QA", "Staging", "Production", so one naiive workaround might be:

| Release          | Dev        | QA        | Staging        | Production        |
|------------------|------------|-----------|----------------|-------------------|
| MyAwesomeProduct | Dev:v2.9.0 | QA:v2.8.1 | Staging:v2.8.0 | Production:v2.8.0 |
| MyOtherProduct   | Dev:v2.0.1 | QA:v2.0.0 | Staging:v2.0.0 | Prod:v1.3.0       |
| SomeInternalTool | Dev:v1.1   | Prod:v1.1 |                |                   |

...? except with pretty iconography rather than my terrible markdown tableness :)

**Comment by nmarinel** [comment]
@Balfa Yup, exactly. I think the first table you have is probably not going to work out for most people, so the second is more what I had in mind. Thanks for writing that up, I'll update the top post if it lets me...

**Comment by awanlin** [comment]
Ok, this is great, thanks for getting this started. I'd like to clear up some terminology as it will help make sure we are on the same page and clarify our needs

1 - Multi-stage pipelines are created in YAML and are tied to Environments, here is some documentation:
- https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops
- https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/multi-stage-pipelines-experience?view=azure-devops
- https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/key-pipelines-concepts?view=azure-devops

2 - Releases are created using the Web UI and are tied to Deployment Groups, here is some documentation:
- https://docs.microsoft.com/en-us/azure/devops/pipelines/release/releases?view=azure-devops
- https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deployment-groups/?view=azure-devops

Getting the data we need will require different APIs based on if we want 1 or 2 or some way to do both. Worth mentioning is that Multi-stage pipelines in YAML are slowly replacing Releases. We currently use both but are moving towards Multi-stage pipelines in YAML
