### ISSUE TITLE
Be able to render code docs into backstage (e.g. JavaDoc, PythonDocs, etc.)

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#12260]
## Feature Suggestion

We'd like to add the possibility the code docs  (e.g. JavaDoc, PythonDocs, etc.). This would allow developers to easily find the technical documentation about the components they are using and avoid companies to deal with multiple host managers (e.g. **javadocs.io**, **readthedocs.io**, etc.) in case of internal documentation.

## Possible Implementation

I don't if we need a new plugin of just add this feature to the **techdocs** plugin. *IMHO, this should be a separate plugin. If this is not a new plugin, then this could be related to #12259 ?* 

At least I think that the features described in #12259 should be supported. 

I don't know about any other features that should be supported. 

May be it's worth to add a generic HTML renderer ?

## Context

Companies have many live version for each components. These components may be used by several developers. These developers want to be able to look at the doc of the specific version of the component they use in backstage.

**Comment by ahhhndre** [comment]
@LvffY, could you maybe revise this issue? The Possible Solution and Context are identical to #12259. It might also be worth linking to the other similar issues asking for support for other generators or tooling like: #8642, #1147, or #4548

**Comment by LvffY** [comment]
@ahhhndre I reword my issue. 

The context is the very similar as #12259 but here it's pointing developers use case, on #12259 it's pointing backstage users more generally.

In any case, thanks for pointing other issues :)

**Comment by garyniemen** [comment]
@LvffY Can you clarify why you think this issue is similar to the TechDocs version issue. Also, are you imagining this in-code documentation being part of another doc site, in other words - being injected into it. Or are you imagining it as a separate doc site?

**Comment by garyniemen** [comment]
@iamEAP Can you comment on this. TechDocs Addon vs separate Plugin? Anything to say about the relationship between this issue and other issues (including #12259 )

**Comment by iamEAP** [comment]
Hmm...  Whaddya think of this thought, @garyniemen: maybe the use-case of displaying code docs is closer to API docs than it is to TechDocs?

e.g. This is [an example of an API definition of type "grpc"](https://demo.backstage.io/catalog/default/api/hello-world/definition)...  But what if there were also an API definition type `JavaDoc`?

**Comment by LvffY** [comment]
@iamEAP This seems to be more something like that I had in mind :)

@garyniemen WIth the last answer of @iamEAP I don't think the two problems are related anymore and I was more thinking about another doc site TBH.

**Comment by iamEAP** [comment]
Nice.  Maybe @freben, how does that sit with you from a Catalog / API perspective?  To represent APIs that aren't necessarily "over the wire" but instead, something more akin to classes/functions/methods/etc for a package/module.

**Comment by freben** [comment]
One might say that the API kind is there as a helper for modelling communications patterns. You want to be able to express that a service Component exposes two APIs A and B, and then other Components can say that they consume A or B, rather than consuming the Component that hosts them.

For API docs for _a component itself_ that is more library-like, I'm not sure that this view of the abstraction holds. So far, we've said that a service Component might relate directly (not via an API) to a library Component if you wanted to express that relation (and even that is not quite as common a granularity to reach for).

So with that in mind, it sounds like it'd be a modelling inconvenience to introduce API entity middlemen basically in order to just house the API docs. Its actual work to just get that yaml in place and having it visible in search results, and inventing unique names for them etc. Spontaneously, it sounds like maybe `metadata.links` on the services, pointing to externally hosted api docs, could be more lightweight from the catalog's POV?

Let me know if that makes sense.

**Comment by iamEAP** [comment]
Mmmm.  Thanks for the clarity @freben, that makes a lot of sense.

To be honest @LvffY, we regularly have folks request this kind of library documentation internally (for a variety types of libraries in a variety of languages), but haven't _quite_ found the best way to solve this generally and at scale.

Because we use the [recommended](https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach) deployment approach to TechDocs internally, we're able to offer a workaround: some teams are able to generate markdown from language-specific inline docs at build-time, and inject those markdown files into a TechDocs site's `mkdocs.yml` configuration.  ...But the solution is imperfect: it's brittle, it's hard to integrate the TechDocs content and language-specific docs, and there isn't a unified way to discover those library docs.

It's like we want an experience like that of the API plugin for _end users_, but with the _authorship_ experience of TechDocs.  The API Docs and TechDocs plugins have some useful primitives internally (e.g. API Docs' ability to render different kinds of API definitions or TechDocs' prepare/generate/publish steps), but those primitives aren't really composable into a solution that fits this need, at the moment.

So maybe a new, separate, `library-docs` plugin is the way to go?  I dunno.  Whaddya think @garyniemen?

**Comment by LvffY** [comment]
@iamEAP do you have any examples on how to generate markdown from Javadoc, PythonDoc and so on ?

I've never heard (or TBH search) for such features, but this could be quite a good temporary workaround :)

@soapraj did you get time to review this issue ?

**Comment by fsmaia** [comment]
Up
