### ISSUE TITLE
Allow guests to generate tokens for development

### ISSUE THREAD

**Issue by mclarke47** [backstage/backstage#12394]
## Feature Suggestion

@freben and I discussed this offline.

When using the sign in as guest feature it would be great if tokens were generated by the fetchApi and token manager. This would reduce the friction to getting a local development Backstage up and running.

## Possible Implementation

Possibly a `allowGuestMode` flag in `app-config.local.yaml` that generates tokens from a random seed.

## Context

While setting up some new endpoints for the Kubernetes backend (https://github.com/backstage/backstage/pull/12393) it was quite difficult to get started. The new endpoints call the catalog api which needs a Backstage token, so I had to login using a local auth setup rather than just using a guest account.

This complicates the setup process and creates friction when developers are trying to explore Backstage.

**Comment by waldirmontoya25** [comment]
We are checking how to enable it. Is this the file where token setup is done for guests? cc @jamieklassen @luchillo17 

packages/core-components/src/layout/SignInPage/GuestUserIdentity.ts

**Comment by luchillo17** [comment]
Indeed, I would guess the `getIdToken()` function is responsible for generating a valid backstage token with the correct permissions.

**Comment by RubenV-dev** [comment]
@mclarke47 @freben  Good Morning, I am beginning to look at this feature request but would love some further clarity on some of the things mentioned in this issue.

What do you mean by backstage token? Are you referring to a service to service auth tokens that backend plugins need to communicate with one another if auth is enabled?

Are there examples of which fetchApi or tokenmanagers supply backstage tokens?
I can see when service to service auth is enabled there is a token manager change required
`const tokenManager = ServerTokenManager.fromConfig(config, { logger: root });`
could this be the token manager you are referencing?
Unsure what the fetchApi could be.

Im trying to identify some acceptance criteria, what are some expected outcomes for this change?

do you want a specific plugin to work when this is enabled? Im curious which plugins could be used for testing of this feature to ensure that changes work properly.

Any further context would be appreciated. Im also available on discord if that makes things a bit easier. Thanks.

**Comment by freben** [comment]
This is related to #15999.

There are parts of the auth system that are in need of being filled in; one of the gaps is that guests don't have a Backstage token issued for them. Guests actually don't have a sign in flow at all; they don't talk to the auth backend to get signed in - a [guest identity](https://github.com/backstage/backstage/blob/master/packages/core-components/src/layout/SignInPage/UserIdentity.ts#L48) is currently a special implementation [that never has a token to return](https://github.com/backstage/backstage/blob/master/packages/core-components/src/layout/SignInPage/GuestUserIdentity.ts#L55) at all.

Most frontend plugins that talk to a Backstage backend use the `fetchApi` to do so. It is a wrapper for an actual fetch, but also [injects the user's Backstage token](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/apis/implementations/FetchApi/IdentityAuthInjectorFetchMiddleware.ts#L60) _if it is available_. So when a guest uses Backstage, it means that requests to backend plugins will have no `Authorization` header added at all. Sometimes that's OK, sometimes (especially when the permissions framework is enabled), it leads to 401 errors.

The acceptance criteria for this issue, it seems to me, is to somehow make it so that guest users do get Backstage Authorization headers injected in requests. You can't just make it a fake token though. The receiving end typically uses [the IdentityApi](https://github.com/backstage/backstage/blob/master/plugins/auth-node/src/IdentityApi.ts#L34) to check the token, which in the default implementation calls out to the auth backend to validate against what its JWKS endpoint claims that it has issued.

We want to entirely rework parts of the auth flows eventually. As #15999 mentions there's a bunch of cool features that we'd like to enable: admins impersonating users, server identities, server on-behalf-of-user handling, and more. But short of doing all of that:

One could envision an `auth.allowGuestMode` flag as mentioned at the top. It could have two effects when enabled:

- In the frontend, [`GuestUserIdentity.getCredentials`](https://github.com/backstage/backstage/blob/master/packages/core-components/src/layout/SignInPage/GuestUserIdentity.ts#L55) would start returning some form of a fake token. Possibly even a static fixed JWT that isn't signed, or so.
- In the backend, [`DefaultIdentityClient.getIdentity`](https://github.com/backstage/backstage/blob/master/plugins/auth-node/src/DefaultIdentityClient.ts#L81) could start accepting that exact token on top of its existing behavior

Good thing about that flag is that we could still keep it in a future scenario where the auth backend truly starts issuing proper guest tokens that can be verified against it.

Ping @Rugvip here too

**Comment by RubenV-dev** [comment]
Hello,
I want to ask your opinion on something i ran into while trying to figure out an implementation for this allowguestmode flag. I made a few local changes where a configApi can be introduced via parameter to the [guestUserIdentity class](https://github.com/backstage/backstage/blob/cb31ea1da1753fcb1c9caa493d444bdcd13a5cd4/packages/core-components/src/layout/SignInPage/GuestUserIdentity.ts#L23). This unlocks the ability to check the config for whether or not that flag value exists. Now when i move up the callstack to the classes that call and use the guestUserIdentity class i ran into the [userIdentity](https://github.com/backstage/backstage/blob/master/packages/core-components/src/layout/SignInPage/UserIdentity.ts#L48) that has a static method that can create guestuserentities. For this specific case im wondering if there are any preferences to how we can introduce this config to that static method?

I can see introducing the configApi via parameter to the createGuest Method that can then be passed down to the guestUserIdentity, I can see a change of that static method to an instance method that would require the UserIdentityClass be instantiated before we can make use of it. 

Does anyone have an opinion on what the better approach might be to this problem?

**Comment by freben** [comment]
Would it make sense to add a static `GuestUserIdentity.fromConfig(config: Config)`? It would set a private optional token field to some value if the config flag mentioned above is true. If that field is undefined (for example if the bare class constructor is used which doesn't even have a token option), it behaves like it used to do before.

You'll see that [the provider](https://github.com/backstage/backstage/blob/54a0b4b524796c66234bef945c48de5ff2e6bdd4/packages/core-components/src/layout/SignInPage/guestProvider.tsx#L58) has access to the apis both in the loader and in the component. In the former, the first parameter passed in to a `ProviderLoader` is an apiHoder that has all of them available. In the component, you can use `useApi(configApiRef)` as usual.

Interestingly, [`UserIdentity.createGuest`](https://github.com/backstage/backstage/blob/54a0b4b524796c66234bef945c48de5ff2e6bdd4/packages/core-components/src/layout/SignInPage/UserIdentity.ts#L48) isn't even in use in the repo at all. But it's part of the public interface, so it stays for now. What you could do is to add a new optional parameter to it, `createGuest(options: { config?: Config })` which makes it backward compatible, and leveraging that config when it's given.

**Comment by RubenV-dev** [comment]
Awesome, thanks for the reply I will get to work on this and give this implementation a try.

**Comment by foot** [comment]
Nice! We bumped into this when trying to make use of all the new Kubernetes helper hooks. We're writing a plugin that that shows custom resources, and would be nice to not require devs setup token-supporting-users.

- [`useCustomResources`](https://github.com/backstage/backstage/blob/master/plugins/kubernetes/src/hooks/useCustomResources.ts#L36) uses BE endpoints that [require a token](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/routes/resourcesRoutes.ts#L47-L49)
- `useCustomResources` seems to work fine as soon as you connect BS up to github-oauth signin flow.
- Working around it for now by using the kuberenetes proxy endpoint and re-implementing (copy/pasting) the `getKubernetesObjectsByEntity` logic to build the labelSelectors etc.

**Comment by jslott2sigma** [comment]
I am running into this as well. My solution was to create a new auth provider on the backend, fronted by a `ProxiedSignInPage` that has a sign-in resolver that always generates a token for `user:default/guest`. There is no need for any special "guest" handling logic with this approach. In production, I'd imagine the sign-in page would be replaced with a "real" sign in page, with suitable errors for using this special "guest" auth provider too. Is the Backstage team set on the approach as described above however?

**Comment by axie10** [comment]
hello very good morning. How can I have an administrator token in my backstage application (that does not expire) to be able to call endpoints that have backstage or the different plugins like RBAC to be able to do actions in cdoigo that do not require the token of the user who is logged in. Is there any way to generate one and configure it? Thank you very much!

**Comment by freben** [comment]
@axie10 sounds like you want https://backstage.io/docs/auth/service-to-service-auth#static-tokens

**Comment by axie10** [comment]
@freben Hello! this is what I have configured (the static token) but it still doesn't work. Reviewing the plugin code requires in this type of requests such as update or create a token type user does not fit a token type service. Any solution to create a token type user that allows to make all this type of requests. Thanks in advance!
