### ISSUE TITLE
[RFC] Kubernetes CRD UI plugins

### ISSUE THREAD

**Issue by mclarke47** [backstage/backstage#12455]
## Need

Many modern infrastructure tools use Kubernetes as a control plane, examples include:
[argo]([argoproj](https://argoproj.github.io/))
[istio](https://istio.io/)
[crossplane](https://crossplane.io/)

Creating plugins for these tools would be beneficial to the users of Backstage. However, to use these tools, each one would need to create a separate plugin backend, increasing duplicated code (Kubernetes clients / auth / fan-out requests) and time to launch. 

## Proposal

The Backstage community should create patterns for plugins based on Kubernetes Custom Resources. This would include:

Creating a Kubernetes Backend Client that different plugins could use
Plugins could then fetch their data via the Kubernetes backend plugin and become frontend-only plugins
Create a template for Kubernetes Custom Resource-based plugins to speed up the initial development of these plugins

![image1](https://user-images.githubusercontent.com/6514980/177402410-6dcb7f3f-f65e-43d1-a6bd-0273c92af503.png)

## Alternatives

Each service could implement its own backend, introducing disparate features/interfaces for interacting with Kubernetes.

## Risks

Each plugin could need access to different Kubernetes clusters increasing the complexity of configuring the Kubernetes backend and reducing performance.

**Comment by jamieklassen** [comment]
(co-authored with @chinigo)

At VMware we had 3 different teams building plugins for visualizing CRDs related to their domains of expertise, and ended up building a similar kind of client library. We found those teams had some common needs that this library supported:

* Querying for all objects of a given type (potentially constrained to a label selector or namespace) -- this has since been at least partially addressed by the new [`/resources/custom/query` endpoint](https://github.com/backstage/backstage/pull/12393)
* Querying for owners/ancestors of a given object via ownerReferences
* Auto-refreshing/real-time updates to the set of objects
* Showing “status” on objects as an aggregate of various conditions

A natural model here (given the capabilities of the kubernetes-backend API at the time) was a kind of Repository pattern exposing an ORM: a react hook exposed a Repository which would make a giant upfront query against `@backstage/plugin-kubernetes-backend`, load it into the browser’s memory and opaquely refresh it on an interval. The repository exposed methods to filter that dataset by type or relationships.

These two components — Repository and ORM — could be shipped separately or combined together. This RFC sounds like it contemplates something like what we've developed with our Repository.

The Repository is a good place to:
* Centralize the request/response handling against the backend. This part is tightly coupled to the wire format specified in `@backstage/plugin-kubernetes-backend`.
* Present a clean API for accessing objects that's unrelated to the wire format (e.g. client code can rely on `repository.ofType(Pod)` instead of `response.items[].resources[type="pods"].resources`).
* Cache data between responses and provide fast, in-memory access. We structured our implementation so that most accessors return an in-memory result in O(1) time.

The ORM is a good place to:

* Allow consumers of a client library to be able to inject some business logic for the domain of their particular CRDs.
* Define relationships, including those expressed in ways other than ownerReferences (tools like [kapp](https://carvel.dev/kapp/) and [cartographer](https://cartographer.sh/) make use of certain conventions around labels and annotations that help to establish relationships between objects, sometimes even objects on different clusters)
* Present an aggregate “status” from the various conditions known to occur on a given resource type.
* Integrate detailed CRD definitions using the `@kubernetes-models` project (and allow third-party typedefs using the machinery in that library).
* Allow client code to traverse a typesafe object graph naturally via references, e.g. `pod.replicaSet.deployment.spec.selector`.

**Comment by jamieklassen** [comment]
#12950 adds a CRD UI plugin to the marketplace, with its own backend plugin with a bespoke [CRD-fetching function](https://github.com/jquad-group/backstage-jquad/blob/a3d5bb3bead5e06905578d0a61308fc4a87a4ac4/plugins/tekton-pipelines-backend/src/service/pipelinerun.ts#L26). I wonder if @rannox considered using the existing kubernetes-backend plugin to perform these queries? If so, why did they choose not to?

**Comment by jamieklassen** [comment]
@mclarke47 last I recall you were planning to make a PR with something like the "Present a clean API for accessing objects" capabilities described in the "Repository" part of my comment [here](https://github.com/backstage/backstage/issues/12455#issuecomment-1209858207) -- am I remembering this correctly?
