### ISSUE TITLE
Make backend-tasks retry logic configurable

### ISSUE THREAD

**Issue by N426ER** [backstage/backstage#12704]
## Feature Suggestion

- If a scheduled backend task cannot complete, Backstage enters a high-frequency retry loop with a random retry interval that does not stop until the task is successful.
- I want to open a discussion to understand if the retry interval can be configurable and what that would look like. 

## Possible Implementation
- Have a bool flag on TaskScheduleDefinition that would enable an exponential backoff retry algorithm. I imagine this could retry for a configurable amount of time or n times. Ideally, it would give up after these limits are reached and wait until the next scheduled task invocation based on the defined frequency.

## Context

- We have three external integrations that talk to apis under our control. One of these integrations has an s3 backing store.
- We recently migrated our entity ingestion pattern from processors to providers, as outlined in the [docs](https://backstage.io/docs/features/software-catalog/external-integrations).  We use the built-in full diffing option, since we get a snapshot of entities from the external apis every hour.
- Once we deployed our Backstage instance to a new platform, we began seeing tasks timing out and Backstage retrying those tasks every 10 seconds to a few minutes. This was overloading the external api, causing fetch errors, and possibly hitting AWS rate limits. We have work in-progress to improve that api itself to better handle more load. Right now, Backstage is the only app using this particular endpoint.
- The short term fix for us was to increase the task timeouts to five minutes rather than the default 60 seconds we set. We never saw this issue locally because we have to mock the long running api call locally due to environment constraints.
- https://github.com/backstage/backstage/tree/master/packages/backend-tasks

**Comment by freben** [comment]
Hi! Hmm.

[Here](https://github.com/backstage/backstage/blob/8448b53dd6f5366ce27337e3a473b08b1d23b89d/packages/backend-tasks/src/tasks/TaskWorker.ts#L55) is the main worker function that stays alive for the lifetime of the service.

You'll see a tight inner loop that tries to run once, and then waits for `workCheckFrequency` (5 seconds).

But inside `runOnce`, if we ever get to the point of becoming the chosen runner, the function invocation is wrapped in a try/catch, and if it throws, we [release the task](https://github.com/backstage/backstage/blob/8448b53dd6f5366ce27337e3a473b08b1d23b89d/packages/backend-tasks/src/tasks/TaskWorker.ts#L149). Releasing it SHOULD move the next-invocation timestamp forward to the next time slot. There's no intentional high-frequency retry loop as far as I know; as a matter of fact, there are no retries whatsoever 🤔 

You'll see in the task-releasing code that it unconditionally [computes the next time slot and writes that](https://github.com/backstage/backstage/blob/8448b53dd6f5366ce27337e3a473b08b1d23b89d/packages/backend-tasks/src/tasks/TaskWorker.ts#L316) to the database. So this is all a bit surprising. I could try to reproduce this, but if you have a very small reproduction case that I can copy-paste it might help.

**Comment by freben** [comment]
Second reproduction attempt:

```ts
  await env.scheduler.scheduleTask({
    id: 'test',
    frequency: { seconds: 10 },
    timeout: { seconds: 1 },
    fn: async () => {
      console.log(`### ${new Date().toISOString()}`);
      await new Promise(resolve => setTimeout(resolve, 2000));
    },
  });
```

This triggers timeouts.

```
### 2022-09-20T08:33:35.007Z
2022-09-20T08:33:36.007Z catalog warn Task worker timed out: test type=taskManager task=test
### 2022-09-20T08:33:45.047Z
2022-09-20T08:33:46.049Z catalog warn Task worker timed out: test type=taskManager task=test
### 2022-09-20T08:33:55.068Z
2022-09-20T08:33:56.069Z catalog warn Task worker timed out: test type=taskManager task=test
```

(actually you won't see those "timed out" logs, i just added those because i realized they would be really helpful to have)

Seems to still stay on a ten second cadence

**Comment by freben** [comment]
Third reproduction attempt, with a timeout that's _longer_ than the frequency:

```ts
  await env.scheduler.scheduleTask({
    id: 'test',
    frequency: { seconds: 10 },
    timeout: { seconds: 15 },
    fn: async () => {
      console.log(`### ${new Date().toISOString()}`);
      await new Promise(resolve => setTimeout(resolve, 20000));
    },
  });
```

Gives:

```
### 2022-09-20T08:35:33.975Z
2022-09-20T08:35:48.976Z catalog warn Task worker timed out: test type=taskManager task=test
### 2022-09-20T08:35:54.080Z
2022-09-20T08:36:09.081Z catalog warn Task worker timed out: test type=taskManager task=test
### 2022-09-20T08:36:14.185Z
2022-09-20T08:36:29.185Z catalog warn Task worker timed out: test type=taskManager task=test
```

Interestingly, now it runs every 20 seconds (the timeout of one run affects the interval - but upwards, not making it shorter).

Hm I seem to be unable to trigger this, at least with a single worker machine.
