### ISSUE TITLE
Scaffolder editor in the new backstage 1.3.0 is not working

### ISSUE THREAD

**Issue by Vegim** [backstage/backstage#12734]
## Expected Behavior

The template should be triggered by the new scaffolder editor.

## Actual Behavior
The create button on the end of the input-providing step is always disabled

## Steps to Reproduce
Fill in the required inputs in the scaffolder part of the app and the create button is always disabled.
This is happening with the example template that is provided by backstage and also with all other templates that we actually have.

![image](https://user-images.githubusercontent.com/7684612/179777176-7a400965-9669-49ed-a7f9-427e60862f74.png)

**Comment by Vegim** [comment]
Do you have any idea why this is not working? I couldn't find any additional configuration that I needed to do to make this feature work.

**Comment by namco1992** [comment]
I think it's intended that the "Edit Template Form" action only allows "Preview and edit template form", as the description indicated. However it seems no particular reason to restrain it when I asked last time https://github.com/backstage/backstage/issues/12304#issuecomment-1181420856.

**Comment by Rugvip** [comment]
The form preview and template editor are quite different, I think you're using the form preview in this case right? which doesn't have the dry-run capability. With form preview you can load forms from the catalog, because it only needs the template yaml itself. For the template editor you need all of the surrounding file contents, which is why you can currently only load templates that are available from the local filesystem into the template editor.
