### ISSUE TITLE
Failed to read response error using UrlReader with Bitbucket Server

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#12740]
## Expected Behavior

Reading URLs with the `UrlReader` and Bitbucket Server should continue to work without errors as it previously was

## Actual Behavior

Using the `UrlReader` with Bitbucket Server we are getting the following error: "Failed to read response from <Url that was passed to the `UrlReader`>

## Possible Solution

From debugging this the issue seems to come from the assumption that the response has an `id` property on the `commit`:

https://github.com/backstage/backstage/blob/b67946b7f03cc0a33b36f3e48ec8d4382080ba39/packages/backend-common/src/reading/BitbucketServerUrlReader.ts#L208

This was changed as part of PR #12485 

In our case the response looks like this:

```json
{
  "values": [],
  "size": 25,
  "isLastPage": false,
  "start": 0,
  "limit": 25,
  "nextPageStart": 25
}
```

No `id` so it throws the error.

What seems to be a working solution for this is to add this code before throwing the error:

```ts
if (commits && commits.values && commits.values[0]) {
  const lastCommit = commits.values[0].id.substring(0, 12);
  return lastCommit;
}
```

## Steps to Reproduce

This is pretty complex to get setup, you need to create a plugin which uses the `UrlReader`, set that up with the backend and tries to read a URL from a Bitbucket Server instance. If I get time I will create a branch with a working sample but I'd like to focus on a PR with a fix first

## Context

This has broken several of our internal plugins that need to be able to read data from our Bitbucket Server instance

## Your Environment

We are using Bitbucket Server 7.2.4, which is fairly old, but this was working before without any issues

**Comment by awanlin** [comment]
@carlitose @pjungermann @dhruvaldarji could use your thoughts on this, please

**Comment by awanlin** [comment]
As I debug `branch` for me at the end of this URL is an empty string, I'm wondering if that's why I'm getting different results then when this was implemented/changed in #12485

https://github.com/backstage/backstage/blob/b67946b7f03cc0a33b36f3e48ec8d4382080ba39/packages/backend-common/src/reading/BitbucketServerUrlReader.ts#L192

The URL I'm using is formatted like this: `https://bitbucket.company.com/projects/myproject/repos/myrepo/browse/myfolder`

Work mentioning that I get the same error with URLs that don't have a folder so like this: `https://bitbucket.company.com/projects/myproject/repos/myrepo/browse`

**Comment by awanlin** [comment]
OK, looking more closely at #12485 it seems this was removed so I think this would be a slightly better solution then mine above

```ts
if (
      commits &&
      commits.values &&
      commits.values.length > 0 &&
      commits.values[0].id
    ) {
   return commits.values[0].id.substring(0, 12);
}   
```

**Comment by dhruvaldarji** [comment]
@awanlin, the above pageable response you are seeing occurs when the Backstage Backend cannot determine what the `branch` ref is and sends the Bitbucket requests with an improper or missing branch reference. In this situation, Bitbucket returns its pageable API response instead of its commit HEAD response. This typically means that the branch you are looking for either could not be parsed from the source URI or something prevented it from being passed to the `UrlReader`. 

This is also mentioned in my note at https://github.com/backstage/backstage/pull/12485#issuecomment-1178337978.

---

For debugging purposes, I suggest making sure that your `apiBaseUrl` is properly configured and is set in the following format:
```
https://bitbucket.company.com/rest/api/1.0
```
This should result in the following request being attempted by the Backstage Backend:
```
https://bitbucket.company.com/rest/api/1.0/projects/myproject/repos/myrepo/commits/{target_branch}
```

--- 

Nevertheless, I agree that it wouldn't hurt to add a fallback mechanism here to be able to read from the pageable response instead of the commit response. If Bitbucket performs a "graceful fallback" and returns a successful response, then perhaps we should do so here as well.

**Comment by awanlin** [comment]
@dhruvaldarji, thanks for the details, glad to know my understanding matches other Bitbucket Server users. 

I'm pretty close to having a PR in place to fix this just need to sort out the tests
