### ISSUE TITLE
Custom explore page: AcmeInnserSourceExplorerContent not defined

### ISSUE THREAD

**Issue by cinlysobin** [backstage/backstage#12786]
## Expected Behavior

The toolset currently used by the organization needs to be displayed in the Tools session of explore page

## Actual Behavior

The default page is giving a common set of tools that are not currently used by the organization. On customization ExplorePage.tsx error like "AcmeInnserSourceExplorerContent" not defined. 

## Context

Need to get a customized Tools page with currently used tools. Do we have any reference to AcmeInnserSourceExplorerContent 
## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by awanlin** [comment]
Hi @cinlysobin, `<AcmeInnserSourceExplorerContent />` is just example code and not a real component. This is just trying to show you that you need to create your own content for this. You could put `<div>My Company Inner Source</div>` instead of <AcmeInnserSourceExplorerContent />` for example. Once you go down the path of customizing this you need to build up how you want this to look for your needs
