### ISSUE TITLE
Split categories in search results

### ISSUE THREAD

**Issue by viraptor** [backstage/backstage#12877]
## Feature Suggestion

Introduce headings / groupings in the search results.

## Possible Implementation

Make it possible to either click a name of a category to skip to it or (un)fold specific categories.
Possibly just having a Docs/Catalog split may be enough.

For inspiration, here's how AWS console search does it:

<img width="904" alt="Screen Shot 2022-07-28 at 10 09 21 pm" src="https://user-images.githubusercontent.com/188063/181501440-5961937b-23ea-471e-8fcd-9d6c849df5ba.png">

## Context

Almost every time when I use search, I know what category of result I expect. At least on the level of a catalog entry -vs- documentation. Browsing through the list to find the right entry is a bit annoying, especially if I'm trying to find a component name between a lot of docs headings/extracts.
Allowing me to concentrate on just one of those categories quickly would make the UX a lot better.

**Comment by viraptor** [comment]
TIL what the "View full results" that I've been ignoring does and that it solves my problem :D
So I guess my question turns into - any reason most of those small improvements couldn't move into the quick results as well?

**Comment by iamEAP** [comment]
Hey @viraptor!  Since you opened this issue, we actually introduced a new component `<SearchResultGroup />` in https://github.com/backstage/backstage/pull/13561, which implements exactly this.  You can check out what it looks like and how to use it in [the storybook](https://backstage.io/storybook/?path=/story/plugins-search-searchresultgroup--default).

We're not sure it's appropriate for _everyone_ out of the box, which is why we haven't wired it up in `create-app`, but it's definitely there for you to experiment with in your own app!
