### ISSUE TITLE
401 - A JSON web token could not be decoded when following App example

### ISSUE THREAD

**Issue by hanysf** [backstage/backstage#12887]
## Expected Behavior

I am following the [example](https://docs.github.com/en/developers/apps/guides/using-the-github-api-in-your-app) of using GitHub API's in a GitHub app. This page links to [another page](https://docs.github.com/en/developers/apps/getting-started-with-apps/setting-up-your-development-environment-to-create-a-github-app) showing how to setup the development environment to do this. 
I followed the instructions on that page, with one difference, for testing, I kept the contents of the pem file in the code 64-encoded. The code then proceeds to decode that string to get the actual content of the pem file, and use that to construct the `PRIVATE_KEY`. So, it looks like this

```
  PRIVATE_KEY_ENCODED = "some long string"
  PRIVATE_KEY_DECODED = (Base64.decode64(PRIVATE_KEY_ENCODED)).gsub('\n', "\n")
  PRIVATE_KEY = OpenSSL::PKey::RSA.new(PRIVATE_KEY_DECODED)
```

## Actual Behavior

When I install the GitHub app in a new organization, I the following error:
`POST https://api.github.com/app/installations/27776345/access_tokens: 401 - A JSON web token could not be decoded // See: https://docs.github.com/rest (Octokit::Unauthorized)`.

This error occurs when the code tries to [get the token of a specific installation](https://github.com/github-developer/github-app-template/blob/master/template_server.rb#L117)
`@installation_token = @app_client.create_app_installation_access_token(@installation_id)[:token]`

## Steps to Reproduce

Follow instructions in https://docs.github.com/en/developers/apps/getting-started-with-apps/setting-up-your-development-environment-to-create-a-github-app.

## Context

In testing the code, in a Ruby console, I debugged the ran the template_server.rb file and placed a `binding.pry` right before [the error is thrown](https://github.com/github-developer/github-app-template/blob/master/template_server.rb#L117).
I did the following:

```
# This is taken from https://github.com/github-developer/github-app-template/blob/master/template_server.rb#L94

payload = {
          # The time that this JWT was issued, _i.e._ now.
          iat: Time.now.to_i,

          # JWT expiration time (10 minute maximum)
          exp: Time.now.to_i + (10 * 60),

          # Your GitHub App's identifier number
          iss: APP_IDENTIFIER
      }

# Calculate a jwt
jwt = JWT.encode(payload, PRIVATE_KEY, 'RS256')

# display the installation id
@installation_id
```

Then I ran the following cURL command in a command line.

curl -i -X POST \
-H "Authorization: Bearer  <jwt>" \
-H "Accept: application/vnd.github+json" \
https://api.github.com/app/installations/<@installation_id>/access_tokens

I received a valid response that did include a token. So, it doesn't seem that the problem is in the code itself, but that for some reason the `Octokit::Client` is not doing the right thing in calling the intended API.

**Comment by Nmnjainsite** [comment]
I am encountering an issue while making API calls in my ReactJS application. The API calls are returning a 401 Unauthorized error. I have implemented the GitHub App authentication flow and generated a JWT token using a Node.js server. However, I am facing difficulties in using this token for authentication in my API requests.

useEffect(() => {
  const fetchToken = async () => {
    try {
      const response = await axios.get("http://localhost:8080/generate-jwt");
      setJwtToken(response.data);
    } catch (error) {
      console.error("Error fetching token:", error);
    }
  };

  fetchToken();
}, []);


useEffect(() => {
  const fetchInstallations = async () => {
    try {
      const response = await axios.post(`https://api.github.com/app`, {
        headers: {
          Authorization: `Bearer ${jwtToken.token}`,
          Accept: "application/vnd.github.v3+json",
          "X-GitHub-Api-Version": "2022-11-28",
        },
      });
      console.log(response);
      // Process the installation details here
    } catch (error) {
      console.error("Error fetching installations:", error);
    }
  };

  fetchInstallations();
}, [jwtToken, profile]);

Additional Context:

I have successfully generated the JWT token on my Node.js server using the GitHub App private key.
The token is obtained by making a GET request to http://localhost:8080/generate-jwt.
The token is then used in subsequent POST requests to the GitHub API for fetching installations.
Expected Behavior:
I expect the API calls to be authenticated successfully using the generated JWT token, allowing me to fetch the installation data from the GitHub API.

Actual Behavior:
However, the API calls result in a 401 Unauthorized error, indicating that the authentication is failing.

Please let me know if any additional information is required to investigate and resolve this issue. Thank you for your assistance.

Best regards,
Naman

**Comment by Olinari** [comment]
likewise

**Comment by daniel-oh-sunpower** [comment]
same

**Comment by edbighead** [comment]
for anyone stumbling upon this error, I was able to solve it with updating github app permissions according to https://backstage.io/docs/integrations/github/github-apps/ 

> * `Administration`: Read & write (for creating repositories)
> * `Contents`: Read & write
> * `Metadata`: Read-only
> * `Pull requests`: Read & write
> * `Issues`: Read & write
> * `Workflows`: Read & write (if templates include GitHub workflows)
> * `Commit statuses`: Read-only

**Comment by RajuGangitla** [comment]
Hey Naman
Have You solved this issue

**Comment by Nmnjainsite** [comment]
Yes @RajuGangitla.

**Comment by ujain6** [comment]
@Nmnjainsite How did you resolve the issue? Can you please post the solution here? Facing the same problem

**Comment by Nmnjainsite** [comment]
hey utkarsh have you fixed it?
