### ISSUE TITLE
"Filter" text field is confusing in Entity Catalog Table

### ISSUE THREAD

**Issue by iriswang233** [backstage/backstage#12890]
## Feature Suggestion
Changing the "Filter" field to "Search" with search placeholder and icon in entity catalog because this field is doing search not filtering.  Filtering is more related to those selectable dropdown in the left.
Or allowing customising this UI.
<img width="307" alt="Screenshot 2022-07-29 at 12 38 30 PM" src="https://user-images.githubusercontent.com/49713904/181683914-706f3baa-91ac-4546-ab27-70312534df5b.png">

## Possible Implementation
https://backstage.io/storybook/?path=/story/data-display-table--filter-table
1. Add a prop in core-component **Table** to allow customisation Filter text area
2. Change Filter to Search placeholder and icon in entity catalog
<img width="587" alt="image" src="https://user-images.githubusercontent.com/49713904/181686273-5f26e870-8470-43e7-89d5-938e1508b217.png">

## Context
Filtering is more related to those selectable dropdown in the left.
Meanwhile, under smaller screen, 2 filters are causing confusion.
<img width="910" alt="Screenshot 2022-07-29 at 12 54 21 PM" src="https://user-images.githubusercontent.com/49713904/181685501-8c5008ba-5e4f-48a9-9590-7b7951358f1d.png">

**Comment by kuangp** [comment]
Ironically the base material-table displays "Search" and the associated icon as the default behavior and a past [change](https://github.com/backstage/backstage/pull/7567) actually modified it to show "Filter" instead 😅 (reasoning described in the linked PR).

The solution here probably is to allow this to be fully configurable. You can already modify the placeholder text by configuring the [`localization`](https://github.com/backstage/backstage/blob/686c6454cd84dead8211c1a62fd3b930605f4107/plugins/playlist/src/components/PlaylistPage/PlaylistEntitiesTable.tsx#L199) param. Changing the icon is also possible through the `icons` param but it a bit messier now since you would also need to redefine all the defaults icons used elsewhere in the table. I have a pending [change](https://github.com/backstage/backstage/pull/12870/files#diff-79e85773470f382e49d81f9084274aaeaaa29cfd1025843a35536d686d068731R526) that exports the default icons used by the `Table` which would allow you to just override the search icon like [this](https://github.com/backstage/backstage/blob/686c6454cd84dead8211c1a62fd3b930605f4107/plugins/playlist/src/components/PlaylistPage/PlaylistEntitiesTable.tsx#L192-L197)

**Comment by iriswang233** [comment]
Hi,

Thanks for this information. The change to allow customise search icon in Table is helpful for our use case. Looking forward to it.

**Comment by freben** [comment]
I'd argue the opposite (which also led to this change initially) - "search" is a word that's reserved for the actuals search functionality of the overall Backstage, while "filter" means "cut down this set to a smaller one by filtering it".

> this field is doing search not filtering

I'm not sure that this is right, in a linguistic or logical sense 🤔
