### ISSUE TITLE
New document on backstage.io website explaining entity naming strategies.

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#12897]
There seems to be a conflict between global uniqueness of entity names and human readableness. Im sure I am not the first to come across this.

Given that the name (along with namespace and kind) is the unique key of the entity we must choose a name that is unique. By way of example if I have a user entity, lets say the email address is brian@example.com and the users id is bb246164ff3b0941cc95bda4e34c4ee7. I believe the @ symbol is not supported in the entity name so I dont think we can use the email address as the entity name. I could strip off the domain and set it to  user:default/brian, I could use the id user:default/bb246164ff3b0941cc95bda4e34c4ee7, or I could slugify the email address user:default/brian-example-com. Is there any other options.

The first challenge with all of these options is that in order to set the ownedBy field on a component entity, I must know how to construct this reference. Whatever of the above options I pick, it is derived from the user entity in my organization and the derivation must be known by the user making the entity.

The second challenge with using the slugified or domain stripped ones is that they may not be unique across my org. e.g. imagine we have two users with brian@example.com, brian@aquiredcompany.com, they would both result in user:default/brian and conflict with one another.

My initial temptation is to use the user id as it is going to be unique across my organization, however then the human readableness is lost.

I suppose I could create a new annotation and an entity processor that sets the ownedBy field but that seems to be breaking new ground.

backstage.com/owned-by-query: 'spec.profile.email=brian@example.com'

I thought maybe there might be standards around this already, so I thought I would ask. Is there any knowledge about this area?

This question bleeds into another area. A (maybe) obvious choice for a globally unique id for an aws resource might be its arn.. and that is longer that 63 characters and requires a couple of other special character that are not supported.

## Feature Suggestion

Create a document to explain how naming is suggested to be done on entities in backstage around Users, Resources and Compnents.

## Possible Implementation

backstage.io document somewhere near the backstage model documentation explaining suggestions around how to approach naming entities

**Comment by freben** [comment]
> There seems to be a conflict between global uniqueness of entity names and human readableness. Im sure I am not the first to come across this.

And human writableness! As in, it should be intuitive and easy for people _in other parts of the org_ (without your intimate deep knowledge of your things and elevated access etc) to type out relations by hand to your thing.


> Given that the name (along with namespace and kind) is the unique key of the entity we must choose a name that is unique. By way of example if I have a user entity, lets say the email address is [brian@example.com](mailto:brian@example.com) and the users id is bb246164ff3b0941cc95bda4e34c4ee7. I believe the @ symbol is not supported in the entity name so I dont think we can use the email address as the entity name. I could strip off the domain and set it to user:default/brian, I could use the id user:default/bb246164ff3b0941cc95bda4e34c4ee7, or I could slugify the email address user:default/brian-example-com. Is there any other options.
> 
> The first challenge with all of these options is that in order to set the ownedBy field on a component entity, I must know how to construct this reference. Whatever of the above options I pick, it is derived from the user entity in my organization and the derivation must be known by the user making the entity.

Indeed. Some naming patterns and taxonomies (proper use of kinds, types, labels etc) always need to be established when designing your org specific entity system, and then documented and taught to users, and also maintained over time. This is an important job for the adopter, that maybe we don't highlight enough.

There's a lot of room for tooling to be helpful here; your initial catalog info file should ideally be created by a machine (e.g. when scaffolding your thing). You can even make a "Change owner" flow in the frontend that uses the same helpful hypothetical autocomplete component as the create flow, and then issuing a pull request for it.


> The second challenge with using the slugified or domain stripped ones is that they may not be unique across my org. e.g. imagine we have two users with [brian@example.com](mailto:brian@example.com), [brian@aquiredcompany.com](mailto:brian@aquiredcompany.com), they would both result in user:default/brian and conflict with one another.

Yes, scoping does become important. You can just change the naming rules though; adding support for `@` as a valid name character is easy. As a matter of fact, I think we should probably have that be allowed by default because this is such a common use case.

For this particular use case, you could also use namespaces: `user:acquiredcompany/brian`.


> My initial temptation is to use the user id as it is going to be unique across my organization, however then the human readableness is lost.

That's for sure a poor fit, given the above discussions. Yeah full email is likely the most straightforward one here.

It often boils down to what your _authority_ thinks is the "public" primary key. For a lot of systems, the entire email is indeed chosen for that. If it were ldap and your ldap IDs are the left side of the `@`, then you'd already be in a situation where acquired companies might see their users have to change their IDs to avoid collisions, so then could use that.


> I suppose I could create a new annotation and an entity processor that sets the ownedBy field but that seems to be breaking new ground.
> 
> backstage.com/owned-by-query: 'spec.profile.email=[brian@example.com](mailto:brian@example.com)'

This means that the processor that creates actual relations from this, will have to have "global" insight into the catalog. It'll have to make actual lookups instead of just locally looking at the current entity, which is generally frowned upon because it leads to weird stability issues / data races with the model.


> This question bleeds into another area. A (maybe) obvious choice for a globally unique id for an aws resource might be its arn.. and that is longer that 63 characters and requires a couple of other special character that are not supported.

The underlying mindset should be that entities are named by humans, using some taxonomy or thought process that has been agreed upon. An ARN isn't suitable. Even if the ARN of a database were a long complex string of chars (which encodes runtime aspects like the region and other unwanted things), you should name it `myservicename-db` instead, no matter what the URN was. If you moved it to a different region, or if you changed the database type, even if you stopped using AWS entirely and switched over to GCP - the name shouldn't need to change. You might want to have an annotation like `aws.com/urn` or whatever (maybe we already have one for this, I forget) that points to what the actual URN is though.


> ## Possible Implementation
> backstage.io document somewhere near the backstage model documentation explaining suggestions around how to approach naming entities

That's a good idea. I'll put it on my todo.

**Comment by punkle** [comment]
Thanks @freben

**Comment by taras** [comment]
> There seems to be a conflict between global uniqueness of entity names and human readableness. Im sure I am not the first to come across this.

We're encountered this as well with importing people. We went through a few iterations and eventually settled on using employee numbers from LDAP. They were the only thing that was truly unique and not changeable. 

The ability to build relationships without needing to look them up in the catalog is very important. I think this should be a recommended best practice.

**Comment by jpeach** [comment]
>  I could slugify the email address user:default/brian-example-com.

FWIW, I used the email domain name as the namespace, so brian@example.com becomes`example-com/brian`

**Comment by Rugvip** [comment]
Another approach for namespaces that I wanted to get out there is to treat namespaces similar to K8S namespaces, ofc skipping infra related ones like `kube-system`. This is of course going to vary a lot across different orgs, but if your org already has an established pattern for K8S namespaces, then it might make sense to re-use them in the catalog.
