### ISSUE TITLE
Losing Sign-in on every refresh

### ISSUE THREAD

**Issue by skgandikota** [backstage/backstage#13091]
We are using two sign in providers - Microsoft & Github ; Microsoft is our primary where we validate users and github  sign for working with templates where  we have git based scaffolder actions .  On every refresh - we are loosing github sign in - here is my auth.ts.   All preloaded groups  are populated with the microsoft sign in name, so we decided add github name as new entity to the user 

```
providerFactories: {
      ...defaultAuthProviderFactories,
      microsoft: providers.microsoft.create({
        signIn: {
          resolver: async ({ profile }, ctx) => {
            if (!profile.email) {
              throw new Error(
                'Login failed, user profile does not contain an email',
              );
            }
            const [name, domain] = profile.email.split('@');
            if (domain !== '*****************') {
              throw new Error(
                `Login failed, this email ${profile.email} does not belong to the expected domain`,
              );
            }
            return ctx.signInWithCatalogUser({
              entityRef: { name },
            });
          },
        },
      }),
      github: providers.github.create({
        signIn: {
          resolver: async ({ profile }, ctx) => {
            if (!profile.email) {
              throw new Error(
                'Login failed, user profile does not contain an email',
              );
            }
            const [localPart] = profile.email.split('@');
            const userEntity = stringifyEntityRef({
              kind: 'User',
              name: localPart,
              namespace: DEFAULT_NAMESPACE,
            });
            return ctx.issueToken({
              claims: {
                sub: userEntity,
                ent: [userEntity],
              },
            });
          },
        },
      }),
    },
  });

```

![github-sign-in-issue](https://user-images.githubusercontent.com/24265936/183960934-7400be8e-d413-43e8-9f83-5847f164e7bb.gif)

<hr>

Backend  Package.json : 

    "@backstage/plugin-app-backend": "^0.3.33",
    "@backstage/plugin-auth-backend": "^0.14.1",
    "@backstage/plugin-auth-node": "^0.2.2",

**Comment by MadhumithaMarane** [comment]
Same issue need help

**Comment by Divyenth-K** [comment]
Facing the same issue as well, would be great if someone could help on this.

**Comment by VladMasarik** [comment]
@jhaals I have been looking at the issue for the last two days, and I would like to be the the "community" :D However, can you help me better understand it?

1. Is my understanding correct that authentication works fine, it is just this settings page, which incorrectly represents the sign in status?

2. > The page only checks the session which isn't a good way to verify that the user is actually logged in.

Do you mean this code?
https://github.com/backstage/backstage/blob/2881c53cb383bf127c150f837f37fe535d8cf97b/plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx#L51 , and that the current session can represent only one provider, which is why the second provider shows as signed out?

3. > In order to fix this page every auth provider should call `api.getProfile({ optional: true })` and display the profile information, this would verify that the you're actually logged in and provide some profile information. The `getProfile` method already exists today but we need to add the `optional` option in order for it not to throw when you're not logged in.

Do you mean that we should use the `getProfile` to figure out whether the user is logged in, and based on that decide whether to show them that they need to sign it? The `getProfile` already has an `optional` setting, so you mean to just set it, and not implement it right? https://github.com/backstage/backstage/blob/2881c53cb383bf127c150f837f37fe535d8cf97b/packages/core-plugin-api/src/apis/definitions/auth.ts#L87

**Comment by Rugvip** [comment]
> 1. Is my understanding correct that authentication works fine, it is just this settings page, which incorrectly represents the sign in status?

Yep!

> 2. > The page only checks the session which isn't a good way to verify that the user is actually logged in.
> 
> Do you mean this code?
> 
> https://github.com/backstage/backstage/blob/2881c53cb383bf127c150f837f37fe535d8cf97b/plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx#L51
> 
> , and that the current session can represent only one provider, which is why the second provider shows as signed out?

Kind of, it's the fact that that code only subscribes to the current session state, but there's nothing that actively checks whether the session exists. Important part of this is that initially the session only exists as a cookie in your browser, it's not until you try to perform an action and actually use that cookie that the frontend realizes that a session already exists.

> 3. > In order to fix this page every auth provider should call `api.getProfile({ optional: true })` and display the profile information, this would verify that the you're actually logged in and provide some profile information. The `getProfile` method already exists today but we need to add the `optional` option in order for it not to throw when you're not logged in.
> 
> Do you mean that we should use the `getProfile` to figure out whether the user is logged in, and based on that decide whether to show them that they need to sign it? The `getProfile` already has an `optional` setting, so you mean to just set it, and not implement it right?
> 
> https://github.com/backstage/backstage/blob/2881c53cb383bf127c150f837f37fe535d8cf97b/packages/core-plugin-api/src/apis/definitions/auth.ts#L87

Yep! 👍 And it does indeed already have that option. The only snag is that the `ProviderSettingsItem` currently only asks for an implementation of `SessionApi`, so we'd need to add `ProfileInfoApi` too. It should be possible to do without a breaking change by making it optional with `ApiRef<SessionApi & Partial<ProfileInfoApi>>` afaik.
