### ISSUE TITLE
Gitlab Discovery Processor should automatically add the project-id if not present in catalog-info.yaml / backstage.yaml

### ISSUE THREAD

**Issue by chaughawout** [backstage/backstage#13118]
## Feature Suggestion

The `@loblaw-sre/backstage-plugin-gitlab` depends on the gitlab project-id to be added to the entity in a specific location. It would be great if the discovery processor could automatically populate that id into that location so that users don't have to specify it in their yaml files. If the user does specify a project-id in the yaml file, the plugin could skip the attempt to populate it so that it doesn't override the value set by the user.

## Possible Implementation

I don't have context into the discovery processor to provide implementation suggestions, but I know there might be alternatives to the gitlab discovery processor to populate those entities, and it would be great if this same feature could be implemented by them as well.

I believe these changes would live in this plugin:
`@backstage/plugin-catalog-backend-module-gitlab`

## Context

- https://github.com/loblaw-sre/backstage-plugin-gitlab/issues/154
- Step 5 in the [Setup Guide](https://github.com/loblaw-sre/backstage-plugin-gitlab#setup) outlines the location in the yaml

**Comment by freben** [comment]
If I understand the situation correctly, the discovery processor does have knowledge of what the project ID is, but later down the line when the `UrlReader` wants to read the contents of the generated `Location` entity, this knowledge is lost because it's not encoded in the URLs. Is that a correct assessment?

If so, then yeah, something needs to be added that lets this contextual information be passed down through the layers. Not sure what the best solution would be, off the top of my head, but suggestions are welcome.

**Comment by freben** [comment]
For context, I see this comment in the discovery processor: https://github.com/backstage/backstage/blob/45681c215b456a88f7b3a915898a6ee4a02f4cbf/plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts#L153

> The format expected by the GitLabUrlReader:
> `https://gitlab.com/groupA/teams/teamA/subgroupA/repoA/-/blob/branch/filepath`
>
> This unfortunately will trigger another API call in `getGitLabFileFetchUrl` to get the project ID.
> The alternative is using the `buildRawUrl` function, which does not support subgroups, so providing a raw
> URL here won't work either.

**Comment by freben** [comment]
This is how the code then fetches the project ID based on the URL where the file is stored:

https://github.com/backstage/backstage/blob/45681c215b456a88f7b3a915898a6ee4a02f4cbf/packages/integration/src/gitlab/core.ts#L103

This is something that anybody can do at a later time, for example a processor that fills in these IDs in annotations in a pre-processing step. Unfortunately that would lead to more API hammering of your GitLab instance - but the calls could be heavily cached, so maybe that actually can be sidestepped to a large degree.

To be clear, the UrlReader can't have this type of knowledge, since it's way more low level and should not modify data.

**Comment by jwnmulder** [comment]
A solution that currently works very well with the backstage-plugin-gitlab plugin is using 'gitlab.com/project-slug' instead of 'gitlab.com/project-id'.

After adding the [AnnotateScmSlugEntityProcessor](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/modules/core/AnnotateScmSlugEntityProcessor.ts) to your catalog configuration like this
```
  builder.addProcessor(
    AnnotateScmSlugEntityProcessor.fromConfig(env.config),
  );
```
the project-slug annotation is automatically added for all entities originating from a GitLab repository.
