### ISSUE TITLE
contact catalog item owner from dropdown

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#13678]
## Feature Suggestion

A little widget that can be a drop in replacement of the owner field in the catalog table list view that instead of linking to the group/user, renders a drop down offering options such as: email, slack, discord links as well as bringing them to their profile if they prefer.

## Possible Implementation

I would imagine that the dropdown list would be driven by annotations (e.g. slack or discord links) on the user or group entity as well as profile info such as email.

## Context

The idea is that users would be able to more quickly contact owners of components from different parts of the backstage application without having to drill in with a few clicks.

**Comment by benjdlambert** [comment]
Do you want to try and mock something like this up? :pray: Sounds pretty interesting!

**Comment by freben** [comment]
If I understand the idea right, the outcome basically is one less click. Well - same number of clicks, but not having to go to the user's page to find a card that has the same action items on it.

Bear in mind that at the time that the link is rendered, we usually don't have all of the user data present, so we'd have to load the entity asynchronously from the catalog based on the ref, to know what items to show. I'd really want the click on the ref itself to not have its behaviour change at all, so if there were to be a dropdown like this it'd probably have to hang off of some little chevron icon to the right of the user, or be shown in a popover on hover. This also lets us defer the catalog query so we don't have to do that eagerly all the time for every single link that's rendered.

I gotta say I like the idea as such. It makes for a neat interface feature to be able to hover over entity ref links and seeing a popover card (almost like a tooltip) with some peek info. It could be extra useful in result tables, to be able to quickly hover over entries one by one to see some more details about them that isn't rendered in the table itself. Like the description, which is kinda nice to NOT have a column for because it eats so much screen real estate.

It could actually be a pretty rich little card. It could show the ref, title and description standard fields. For users and groups it could show the avatar image and other profile data. It could indeed have action items for stuff like sending an email to the person etc.

All of the above would be builtin behaviors though. Circling back to your actual issue, what you may want in the end is to make this a tweakable card that can render MORE contact details and custom things as well. But maybe it would be a good start to just make it "good enough" for starters, supporting some well known annotations / profile fields. Then eventually, we might be able to put that card into `createApp({ components: { EntityPeekCard: ... } })`

Would you like to whip something up to this effect? 🙏

**Comment by Shayon** [comment]
Commenting to keep this issue alive since I think it's a neat idea :smile:

**Comment by punkle** [comment]
Does something like this look like a good start:

![image](https://user-images.githubusercontent.com/553697/205582952-cf143b96-5383-4f9f-95f9-a6095fd322e8.png)

**Comment by punkle** [comment]
I created a pull request to look something like that.
