### ISSUE TITLE
[Search] Incremental index updates

### ISSUE THREAD

**Issue by taras** [backstage/backstage#13681]
## Context

One of our clients has a huge catalog - over 200k entities and growing. We use Elastic Search to search all these records using the Search Plugin. We have a single collator that populates over 100k documents in an Elastic Search index. It currently takes 7 minutes to populate the index. 

We have features on our roadmap where users will be contributing entities to the catalog that will be stored in an external system. We want these records to appear in our index as soon as the user creates them in the external system. We're working on improving our ingestion to make it as close to real-time - we already optimized it from 2.5 hours to 20 minutes. 

In parallel, we need to make our index updates as real-time as possible: **from >7 min to <200ms**

## Feature Suggestion

Currently, the Elastic Search Engine creates a new index every time a collator runs. We would like to change the behavior of the Elastic Search Engine to allow indexing to update the existing index instead of creating a new index every time.

## Possible Implementation

We spiked making Elastic Search Engine reuse indexes, but we found that we need information we do not have. We need to know when entities are deleted so we can remove their documents from the index. It would also be helpful to know when an entity is updated so we can update the corresponding document.

The functionality we need to make Elastic Search Index updates incremental is blocked by https://github.com/backstage/backstage/issues/8219

**Comment by iamEAP** [comment]
Thanks for opening this up, @taras.  After you (and a handful of other folks in the `#search` channel in discord) had brought up incremental index updates as a possible need, we had a brief discussion on our side as well.

Some notes/questions that came up:

- **Simultaneous Incremental + Full Rebuild**: We had difficulty envisioning how the full rebuild and incremental refreshes could coexist in a single deployment (e.g. managing how an incoming document update would be committed against the existing, live index as well as a new index in the process of being built up).  Sounds like you were thinking of making it possible to keep reusing a single index; how do you imagine the full + incremental processes running together?
- **Decorator Design**: As an example, we have some decorators that pull in data about how many times a given document in an index was accessed; we designed the decorator to pull in that data for _all_ documents at initialization, and then during execution, it just performs a fast lookup in-memory and appends the data to the document.  We would likely design the decorator differently, if it were to be spun up every time a document update comes through.  What's your thinking on how decorators fit in an event-based world?  
- **Index Consistency**: As you mentioned, one low-key advantage of the current architecture is that we don't really have to worry about deleted documents; the next time an indexer runs, any deleted documents just won't be picked up in the latest index.  How to handle in an incremental world?
- **Document _Schema_ Consistency**: Corollary to the above, if you roll out changes to the search backend that update the schema associated with an index (e.g. adding, updating, or removing fields), there's no worries because the next time an indexer runs, every document in the index will conform to the given schema.
- **Disaster Recovery**: Another low-key advantage of the current architecture is that a basic form of DR is handled for you; in case of catastrophic problems, you can flip on the search backend somewhere else or point at a fresh ES instance and eventually have a fully populated index again; do you envision pushing a little more of that responsibility on to adopters, in this scenario?

**Comment by taras** [comment]
Hi @iamEAP, thank you for a thoughtful response.

> Sounds like you were thinking of making it possible to keep reusing a single index; how do you imagine the full + incremental processes running together?

I don't have a complete answer to this question, but it bares some resemblance to the problem of doing full ingestion and webhook-based ingestion in the Catalog. Even the APIs that Entity Providers expose to commit entities resemble those of the ingestion mechanism in Elastic Search. Creating [Incremental Backend Ingestion](https://github.com/thefrontside/backstage/tree/main/plugins/incremental-ingestion-backend), lead us to the idea that we can treat full ingestion as a series of incremental ingestions by converting an initial set of records into a stream. Perhaps, the same approach can be used here.

> What's your thinking on how decorators fit in an event-based world?

This also has some parallels to the needs of ingestion in the Catalog. Catalog Policies annotate entities on their way into the final_enties table. We found that this approach doesn't scale well for catalogs with more than 100k+ entities because as the number of entities with asynchronous policies grows, the processing loop slows down for all entities behind the current entity. The impact of policies was significant but not visible until we had the requirement for user's items to show in the catalog in real-time. 

We're experimenting with moving asychronous policies from the processing loop into entity providers to reduce the work performed in the processing queue. We hypothesize that it'll improve performance by ensuring that asynchronous policies are only applied when an entity is added. With event-based ingestion using webhooks, this will mean that the processing queue will be empty unless it receives an entity from an event.

Perhaps decorators could have a similar model - apply the decorators when the event arrives. Since some items might not get updated frequently but their decorator values might still need to be updated, then we'll likely need some way to continuously update the decorator values. One possibility could be to have stateful decorators that subscribe to a stream or poll an external source and emit diffs into the index to update specific parts of each document.

> How to handle in an incremental world?

We'll need a delete event. In the Incremental Backend Ingestion, we generate a delete event by comparing entities discovered in the current ingestion cycle with entities in the catalog commited by the same entity provider. Anything that was not seen is deleted - equivalent to generating the delete event.

> Document Schema Consistency

This is a tricky one because the new schema may not be compatible with the existing index. The Elastic Search engine allows using existing index while the new index is being created, but if the schema is expressed as code then  the new schema will be running on the existing, possibly incompatible index. We have some ideas of how this could work with structured concurrency, but it's very speculative.

> do you envision pushing a little more of that responsibility on to adopters, in this scenario?

No, I think if we're able to rebuild the index from scratch by generating a stream of events for the existing source, then we might be able to rebuild the index when necessary. 

Look forward to your thoughts.
