### ISSUE TITLE
Allure Plugin: Allure report not getting populated

### ISSUE THREAD

**Issue by cinlysobin** [backstage/backstage#13821]
## Expected Behavior

Allure report get populated in backstage once configurations in the following documentation is done.
https://github.com/backstage/backstage/blob/master/plugins/allure/README.md

## Actual Behavior

Report is not getting populated
![image](https://user-images.githubusercontent.com/47130315/191912213-d4e2703c-b5a1-4c27-a979-1f7a83494d9a.png)

## Steps to Reproduce

Followed all the steps in the above document in addition to it added     qameta.io/allure-project: project-name in catalog-info.yaml

## Context

Our allure env is password protected. I am not sure how to pass the username and password in backstage for the same
Also, to fix the error shown in the console

Please advise me
## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by freben** [comment]
The error seems to be a CSP violation. Do you use the `@backstage/plugin-app-backend` plugin, i.e. serving the frontend from the backend service? If so, you can set CSP policies in your backend config, at `backend.csp`. For example,

```yaml
backend:
  csp:
    'frame-src': ["'self'", 'https://my-other-server']
```

Otherwise you'll have to make sure in whatever other applicable way in your serving infra, that the right `Content-Security-Policy` headers are set.

As for passwords, I do not know this works in Allure myself. Do you mean that a certain header has to be set when speaking to the web frontend? The only thing the plugin does, is to compute what the right URL should be for the report data, and then rendering an iframe with that URL.

https://github.com/backstage/backstage/blob/c02fda193d4d582ff955e007e1eebb3afe3d1206/plugins/allure/src/components/AllureReportComponent/AllureReportComponent.tsx#L36

If your Allure instance is behind SSO or similar, then there's very little that the plugin can do to help with that.

**Comment by cinlysobin** [comment]
@freben ,
adding backend.csp solved my issue. 

Thanks for the solution.

**Comment by rahulsaw2003** [comment]
Hey @freben I am also doing same but I am facing this error:
`Refused to display 'https://example.xyz.com' in a frame because it set 'X-Frame-Options' to 'sameorigin'.Understand this error`
