### ISSUE TITLE
Permission authorization happening inside of the permission policy

### ISSUE THREAD

**Issue by Joonpark13** [backstage/backstage#13891]
## Expected Behavior

We actually could see a few alternatives on expected behavior - would love consultation of intent from plugin author

## Actual Behavior

If an adopter installs the playlist plugin, features within the playlist plugin do not respect the [(presumably) intended behavior](https://github.com/kuangp/backstage/blob/3b8eb1500723dfc56ea46660b4c7a11367825011/plugins/playlist-backend/src/permissions/DefaultPlaylistPermissionPolicy.ts#L77).

## Context

[Original PR](https://github.com/backstage/backstage/pull/12870#discussion_r961573814)

So sorry to mislead you in the comment in the original PR! Upon some further thought and discussion, we've discovered some issues with the pattern established by the playlist plugin inside the [permission policy here](https://github.com/backstage/backstage/blob/26c32ef614ec9733477dd15262b25028e06ee842/packages/backend/src/plugins/permission.ts#L41). We understand that the exposed `DefaultPlaylistPermissionPolicy` is only meant to be a default version of a possible policy that an adopter could implement. However, the structure of the current policy means that authorization is happening inside the policy instead of inside the plugin. This is an anti-pattern since it places the protection of possibly sensitive data under the control of the adopter's policy. If the adopter installs the plugin but does not configure the policy, for example, you may be exposing entities/access/features that you do not intend.

Of course, the nature of what is considered sensitive is highly dependent upon the context of the plugin, and we're not sure if the plugin author, in this case, is ok with this exposure, but regardless of intent we think it would be good to do the following:

- move the authorization out of the policy and inside the plugin (this should be fairly straightforward since the plugin is already integrated with the permission framework)
- rollback to the AllowAllPolicy in the example backend
- consider refactoring the permission framework integration, with more of a focus on exposing sensible permissions instead of exposing a default policy

**Comment by kuangp** [comment]
hmm ...

The original intent here was to follow the same convention as the catalog plugin as the example. In the same way that the default out of the box experience (from my understanding) does not inherently enforce any default policy (eg. any user can read/delete any entity) and it's up to the adopter to author their own policy as part of the permissions backend configuration to place the proper access controls desired. 

In the same manner, the out of the box experience of the playlist plugin also does not make any assumptions on how to enforce access control (anyone user can edit/delete any playlist), it has the permissions framework integrated in appropriate access points the same way as the catalog and also relies on the adopter to write the desired policy. With the `DefaultPlaylistPermissionPolicy`, I was hoping to provide a "batteries included" (though not "batteries installed") experience where the adopter can make use of a sensible default (by installing said included batteries if desired or using different batteries, to continue this analogy 😄)

>This is an anti-pattern since it places the protection of possibly sensitive data under the control of the adopter's policy. If the adopter installs the plugin but does not configure the policy, for example, you may be exposing entities/access/features that you do not intend.

I'm am not sure I understand your statement here as I thought this was the purpose of the permissions framework? Shouldn't the adopter be responsible for configuring the desired policy? 

I do understand the concern of possible footguns due to shipping plugins that are by default "open-access" but I'm also not sure what the current stance is on what warranties we explicitly provide if the adopter doesn't correctly configure their desired access control (again pointing to the catalog plugin as an example where by default is also "open-access")

However I do fully support additional enhancements to the permissions framework to be able to provide a better "batteries included & preinstalled" approach 😁 The shipping of a default policy was just my initial idea of introducing this kind of pattern that works with the current framework.

Let me know if I misunderstood anything here!

**Comment by Rugvip** [comment]
I think the main thing to focus on are private/public playlists, the rest I believe is more of a grey area that is most likely fine to keep.

As a user I think it's fair to assume that private playlists are private, and that apart from perhaps some admins, I'm the only one that can see them. There also isn't any other use of the private/public distinction a part from access control. The tricky bit then is if you don't install the default permission policy, where all of a sudden there's no distinction between private and public playlists at all. In the end it means that if you don't install the default permission policy, you end up with unexpected behavior, and that's the core of the issue.

**Comment by kuangp** [comment]
> As a user I think it's fair to assume that private playlists are private, and that apart from perhaps some admins, I'm the only one that can see them.

Fair point! I guess one thought I had was that an adopter may not want to support the distinction of private vs. public playlists and would like everything to always be pubic. However that would probably also require additional customization of the frontend UI to remove that option completely (which could potentially be part of future changes to expose more customization options, listed under "Future enhancements" in my original PR 😁)

Either way, this was originally implemented to be as flexible as possible to leave it up to the adopters interpretation how public vs private, personal vs team owned, etc. should be enforced and instead of making just an exception for the public vs private use-case, I like the following idea by @Rugvip:

> I would add that if there's a strong desire to keep the existing flexibility in the access control, it could make sense to expose an option (probably in code) to disable the built-in authorization and defer that to the permission policy, just like it works today.

My vote is that we probably want it to be an opt-in to the built-in authorization instead of opt-out if we're establishing this as a general pattern and want the adopters "master policy" to always take precedence (though this brings us back to the original problem at hand of the adopter mistakenly misconfiguring their policy 😕)

**Comment by Rugvip** [comment]
@kuangp I think as a general pattern it's best to make sure that a plain installation of a plugin does not lead to surprising or insecure behavior, even if it skips parts of the README. I feel that in this case it's perhaps not critical, but since you've ended up in the situation of setting a bit of a precedent here, I'd say it's needed. With that all I mean we should go for opt-out. That's unless we can find some other way to handle it that is also safe, but all out of ideas atm.

**Comment by kuangp** [comment]
hm fair enough! Then perhaps we can do something like 
```tsx
router.get('/:playlistId', async (req, res) => {
  const decision = useDefaultPolicy ? await defaultPolicy.handle(...) : await permissionEvaluator.authorize(...);
  ...
});
```
where `useDefaultPolicy` defaults to `true` is is overridable through the `createRouter()` options.

Or, alternatively if we can modify `PermissionEvaluator` with an API to accept and apply a default policy if enabled 🤔

**Comment by Rugvip** [comment]
Yep I think something like the first thing you're suggesting, can iron out details in review.

The `PermissionEvaluator` approach sounds like a more complex way to achieve the same thing I would think? So probably not that 😅

**Comment by kuangp** [comment]
> The `PermissionEvaluator` approach sounds like a more complex way to achieve the same thing I would think? So probably not that 😅

Ah this idea was more for abstracting this pattern into the permissions framework so other plugins can easily apply the same convention in the future but probably something to revisit down the road 🙂

**Comment by mtlewis** [comment]
What about handling this logic in configuration, rather than through createRouter options? Feels like it makes it a bit easier to document the behaviour, and also seems like a nicer standard to encourage people towards: you can enable and disable the permissions framework completely by toggling `permission.enabled`, and you can enable and disable integration with permissions per-plugin by toggling a configuration option too?

**Comment by kuangp** [comment]
> you can enable and disable the permissions framework completely by toggling `permission.enabled`, and you can enable and disable integration with permissions per-plugin by toggling a configuration option too?

That is definitely an interesting idea! There could be a parallel with the `backend.database` config where we follow the same pattern by establishing something like the following:
```yaml
permission:
  enabled: true | false
  plugin:
    [pluginId]:
      enabled: true | false
      policy: 'default' | 'master' # might need to iron out the details here a bit
``` 
@Rugvip thoughts?

**Comment by Rugvip** [comment]
Hmm, what does this mean?

```ts
permission:
  enabled: true
  plugin:
    playlist:
      enabled: false
```

I'm feeling that the sensible way forward would be to add it to the `createRouter` options, since switching off the auth checks are tightly coupled with updating the entity policy, both of which are in code. You also wouldn't ever be varying the setup in different environments either I would think, which is the primary purpose of the configuration.

**Comment by Rugvip** [comment]
Related: #18064
