### ISSUE TITLE
Support Post-Query Per-Record Authorization Checks in Catalog Plugin

### ISSUE THREAD

**Issue by sennyeya** [backstage/backstage#13981]
Happy to work on this.

## Feature Suggestion

Support checking entities returned through `AuthorizedEntitiesCatalog.entities` against an authorizer endpoint to ensure fine grained access control.

Desired flow is check if user has access to read records -> pull records from database -> verify that user has access to pulled records through external system -> return only records user has access to.

## Possible Implementation

Before the return on https://github.com/backstage/backstage/blob/71a0780ac32401176b70c0527daf376afa27dcd6/plugins/catalog-backend/src/service/AuthorizedEntitiesCatalog.ts#L65, add a filter function similar to https://github.com/backstage/backstage/blob/71a0780ac32401176b70c0527daf376afa27dcd6/plugins/search-backend/src/service/AuthorizedSearchEngine.ts#L211.

## Context

Currently, the AuthorizedEntitiesCatalog only supports discrete DENY/ALLOW checks and synchronous database level filters. My organization uses an external API for access control checking, which would need to be called at runtime after all records are loaded from the database. At the moment, I would need to add distinct PermissionRules for each entity I wanted to hide from the home page.

**Comment by mtlewis** [comment]
This is a really interesting question. Today, the catalog only asks for authorization _without_ a resource when filtering entities, and that happens before hitting the DB, we will always have a result of ALLOW, DENY, or CONDITIONAL by the time we go to the database. Even if we add some post-DB per-record filtering, we would need a third status to represent the fact that the policy doesn't support CONDITIONAL responses for this request, and that it wants to be asked result-by-result.

It seems like we need something new in the permission framework to handle this requirement. Either a new AuthorizeResult like `AuthorizeResult.CONDITIONAL_UNSUPPORTED`, or support for metadata returned along with decisions. In either case, we're looking to signal to the caller "I can't give you a conditional decision, but I want to authorize resource-by-resource". 

WDYT @Rugvip / @vinzscam?

**Comment by mtlewis** [comment]
Note by the way, that even once we've addressed the above, we'll need to think carefully about how we handle record-by-record authorization. This is a thorny area, since it doesn't play nicely with pagination. The user will have asked for a specific number of entities at a specific offset, and if for example the permission policy is extremely restrictive, such that only a very small subset of entities in the catalog are actually visible, building this page of entities can be extremely expensive when filtering result-by-result. We handled this in the search plugin by using a latency budget, and aborting the operation (and returning what we found so far) when it takes too long, but since the catalog is the canonical source of truth, that approach probably isn't good enough in this case.

**Comment by vinzscam** [comment]
Yeah, I share all the concerns expressed above.
It doesn’t look like it would be possible to build something scalable using this approach, given that you are using an external system for performing authorization. More specifically, let’s say the catalog returns 10k entities, what do you do? Do you send 10k REST requests to the external system or a single big request containing everything? Neither approach seems to scale.
In my opinion I don’t see a good reason for including such logic in the Catalog, since this looks a very specific use case. I would consider a different approach, where you create a new catalog proxy plugin which exposes the same endpoints as the catalog, fetches the data from the catalog and applies all the custom authorization logic before returning all the entities.

**Comment by sennyeya** [comment]
Thanks for the input y'all and I definitely agree. It 100% ends up as a scalability problem for larger catalogs.

I guess I'm still confused by why search has it implemented in the first place, why would we want just search to do resource level authorization checks and not the overall catalog? I'd expect to be able to do resource-level authorization across the entire catalog, if it's enabled initially in a single place.
I'll also add that I don't think it's _quite_ a unique case, there was a similar question in Discord about using Github repo access controls, https://discord.com/channels/687207715902193673/978977570852835379/1026945801097855026. 

That being said, I like the direction that @vinzscam proposed, so I'm gonna take a stab at it.

**Comment by mtlewis** [comment]
> I guess I'm still confused by why search has it implemented in the first place, why would we want just search to do resource level authorization checks and not the overall catalog? I'd expect to be able to do resource-level authorization across the entire catalog, if it's enabled initially in a single place.

The problem with resource-level authorization is that it doesn’t mesh well with database-backed paginated queries. If an individual authorisation is needed for every entity, then you have to:
1. Load a page of data from the DB
2. Run authorization for each entity, filter out unauthorized
3. Load more entities to fulfil the initial page size on the request and authorise them too, repeating as necessary until you have either run out of entities in the db, or you hit the requested limit. 

Note that 3 above is not just a nice-to-have. If we didn’t backfill filtered entities with more data, we would be leaking the fact that more entities matching the user’s query exist but are invisible to them. It’s also potentially hugely expensive - consider a catalog with 100,000 entities, but only 5 visible to the logged-in user. 

These problems actually all hold true for the search system too, but we can relax the constraints a bit for search given the different use cases compared to catalog itself.

**Comment by mtlewis** [comment]
> That being said, I like the direction that @vinzscam proposed, so I'm gonna take a stab at it.

The proxy approach sounds like a great idea to me too - it means you can build a solution that works for your individual use case, which is likely a lot more manageable than trying to solve this in a general-purpose way in catalog-backend.
