### ISSUE TITLE
[catalog] Configurable Field Filters

### ISSUE THREAD

**Issue by daviddyball** [backstage/backstage#1400]
## Feature Suggestion

Make it possible to configure arbitrary `CatalogFilter`s via the shared backend config. This would be particularly useful for filtering by team (not just the team you are part of)

## Possible Implementation

In `app-config.yaml` have something like:
```
catalog:
  filters:
  - field: owner
    value: some-team
  - field: owner
    value: another-team
```

I was going to comment on https://github.com/spotify/backstage/issues/1220, but I wasn't 100% certain that the two were related. Is the GraphQL API how this would be implemented (GraphQL is new to me)?

## Context

My understanding is that the identity work allow users to be a member of a "team" and then filter `CatalogPage` components via the "Owned" filter, but even if you are in a different team it can be useful to drill down into per-team ownership outside of your own team.

Being able to specify arbitrary filters via the config would be handy for this. Right now my example above is literally just filtering on `owner === <value>`... which seems pretty simple. In my use-case I wouldn't need anything more complex than string matching on fileds. This would also be useful for `lifecycle === <value>` to filter items by release status.

**Comment by marcuseide** [comment]
@daviddyball Hey and thanks for the issue! We currently don't have any plans on implementing this right now.
We are always open for contributions if you feel that this is something you'd want to add? If not we might revisit in the future.

**Comment by daviddyball** [comment]
@marcuseide OK cool. I haven't written any TypeScript before and have zero experience with GraphQL.... but there's no time like the present to learn.

Do you have any pointers on an implementation approach? Is GraphQL something worth diving into for this, or would it just be easier to do in TypeScript with the config object?

**Comment by freben** [comment]
Hey!

So since the config is central to the Backstage deployment, is this for a use case where all/many users in an org have a recurring common need to select a certain filter? And in this case, for ownership by some other central team than their own? E.g. that it's very common to want to filter by e.g. "owned by infra-core@example.com" or so.

warning: solution-mode loosely-weaved ideas follow below: :)

Firstly, the "owned by" dimension could conceivably be made into a filter where you have the options "me", "team a" (that i happen to be a member of), "all", and then "custom", letting you select any number of known teams. That way at least the ability would be there to select other teams than your own.

Secondly, one could conceivably build filter saving, such that you can save the current query and quick-select it at a later time.

Thirdly, if there is a common request to have centrally stored such queries that all users can select, then maybe it could be built as such instead, on top of the second point above.
