### ISSUE TITLE
Make it easier to merge configuration into config at runtime

### ISSUE THREAD

**Issue by taras** [backstage/backstage#14084]
## Context

Related #13952 

We're experimenting with different ways to satisfy security requirements for one of our clients, where they're not allowed to use environment variables to store secrets. We tried a bunch of different approaches; one of them is to load secrets before reading configs and merging them into configuration. This proved surprisingly difficult.  We tried to modify `main()` in `packages/backend/src/index.ts` to read secrets before calling `loadBackendConfig,` but we couldn't figure out the right way to load those values into the config object.

## Feature Suggestion

Provide an API to merge or derive a config object by merging a POJO into a config.

## Possible Implementation

Something like this would be great,

```ts
const static = await loadBackendConfig({
  argv: process.argv,
  logger,
});
  
const config = static.merge({
  backend: {
     database: {
        password: await readFromSecretStore('db_password')
     }
  }
})
```

Is this possible?

**Comment by OrkoHunter** [comment]
I have recently also seen companies frown up secrets in configs via environment variables - they are so peculiar about their own secret managers, and want to use that only. So +1 to updating configs during runtime or #13952. :)

**Comment by andrewthauer** [comment]
I don't recall, but at what point do the `config.d.ts` files get validated? This approach seems feasible assuming the validation of required secrets values in the config doesn't occur when reading the initial config (prior to the merge).

I suppose if this is a problem then you would just add some dummy values that get replaced (or some special placeholder)? If that's the case, another consideration is the dummy values essentially bypass validation or required fields. This could lead to errors occurring only when the secret is used and thus making it more difficult troubleshoot the root cause. However, I'm sure there is a solution to mitigate this as an extension to the proposal.

**Comment by taras** [comment]
> I don't recall, but at what point do the config.d.ts files get validated? This approach seems feasible assuming the validation of required secrets values in the config doesn't occur when reading the initial config (prior to the merge).

Validation happens when a configuration consumer attempts to read the configuration value because they specify whether the value is required or optional.

**Comment by taras** [comment]
@OrkoHunter we could provide the merge API as a recommended solution when environment variables are not allowed. #13952 might require breaking changes which is going to take a while.

**Comment by shailendra-ahir-cbre** [comment]
#following this issue for updates

**Comment by Rugvip** [comment]
Wanna chime in with that I think a refactor of the mid-level config loading APIs could help quite a lot here. Something like a concept of "config sources" that essentially stream config data into the loader, which takes case of schema filtering etc. Right now the config loader is growing quite large and complex, so feeling that refactor is starting to be necessary to add more features.

The current API is very much built around `loadBackendConfig` and supplying options and getting a completed config object out of that. I'd say any additions we make need to be new inputs to `loadBackendConfig`, rather than modifying the output.

**Comment by freben** [comment]
@shailendra-ahir-cbre There's a "Subscribe" button in the right sidebar for that purpose.

**Comment by rachedanis** [comment]
Hello, I just want to add our voice and say that we have a similar need ( or maybe a bit more complicated ) in our company ( ~+100k employes ) in which we want to proove that backstage is cool and could be used as the developer portal of the company.

We have many IT teams, each team has their own namespaces/accesses to the common IT services of the company ( Sonar, K8S, ... ). Hence with backstage, we need to restrict access of the authenticated user to its own scope... and it seems very complicated.

We're not Backstage experts but we tried to design a very high level architecture for that :

![backstageSecrets-Sol1](https://user-images.githubusercontent.com/12943924/207098350-9d245868-523a-4846-b8ac-9284c19255d8.png)

Do you think it's feasable ? If yes, we would like to contribute ( with some guidance ) to make it work for us and for the people following this feature request.

**Comment by jhaals** [comment]
@rachedanis I'm not sure if vault is a requirement here but or a proposal to the problem.
I just want to point out that a general advice is to act using the users OAuth token from authenticating to GitHub instead of a service token with higher access than the user. Scaffolder can for example perform actions with the user token instead so the user wouldn't be able to overstep their permissions granted in GitHub by leveraging the scaffolder token. Backstage does come with a [Permissions Framework](https://backstage.io/docs/permissions/overview) and there was also a recently announced a [RBAC plugin](https://backstage.spotify.com/plugins/rbac/) built on top of that as you express a need to restrict access.

**Comment by taras** [comment]
Not stale :)
