### ISSUE TITLE
checksId prop in EntityTechInsightsScorecardCard not working

### ISSUE THREAD

**Issue by ydeng-splunk** [backstage/backstage#14140]
## Expected Behavior

When checksId is passed to EntityTechInsightsScorecardCard, should only list the check in the list
 <EntityTechInsightsScorecardCard
            title="Scorecard 1"
            description="This is a sample scorecard no. 1"
            checksId={['titleCheck']}

## Actual Behavior

The component page still lists all checks.

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by freben** [comment]
@Xantier @Irma12  maybe you could have a look at this?

**Comment by freben** [comment]
I note that [the component](https://github.com/backstage/backstage/blob/de676888bc96e6a45e4b2b36fa6bff479da9c076/plugins/tech-insights/src/components/ScorecardsCard/ScorecardsCard.tsx#L35) doesn't react to changes in the check ids list. Maybe the useAsync should depend on `[api, entity, JSON.stringify(checksId)]` or something, so that it'll properly react to updates there? Not sure if that's what is affecting things here though.

**Comment by freben** [comment]
Made [this one](https://github.com/backstage/backstage/pull/14161) to at least get the reloading behavior in place.

**Comment by Irma12** [comment]
Hey @freben I took a look and I think problem is in TechInsightsClient.ts component. I think the error source is not defining the specific header type when POST request is made. I will create a PR in order to make it work, I think it should resolve the issue.

**Comment by Irma12** [comment]
I think [this](https://github.com/backstage/backstage/pull/14164/files) should do the trick :)

**Comment by Rugvip** [comment]
Fine to close this? Seems like it's fixed by #14135

**Comment by freben** [comment]
Closing as fixed.
