### ISSUE TITLE
Error installing Shortcuts Plugin in Backstage

### ISSUE THREAD

**Issue by prasoon-pxc** [backstage/backstage#14241]
### Discussed in https://github.com/backstage/backstage/discussions/14240

<div type='discussions-op-text'>

<sup>Originally posted by **prasoon-pxc** October 20, 2022</sup>
I am trying to install Shortcut Plugin in Backstage and able to install it successfully but when I am trying to overwrite default implementation as mentioned in plugin doc then it is giving below error:

```
[0] ERROR in ./src/apis.ts 13:0-42
[0] Module not found: Error: Can't resolve '...' in '/home/backstage/backstage-conf-repo_my/packages/app/src'
[0] 
[0] webpack compiled with 1 error

```

-- Below is the code which I am adding in api.ts file:

```
import { shortcutsApiRef } from '@backstage/plugin-shortcuts';
import { CustomShortcutsImpl } from '...';

export const apis = [
  // ...
  createApiFactory({
    api: shortcutsApiRef,
    deps: {},
    factory: () => new CustomShortcutsImpl(),
  }),
];
```

I am thinking that ```import { CustomShortcutsImpl } from '...';``` line is creating the problem

Plugin Documentation Link --> https://github.com/backstage/backstage/blob/master/plugins/shortcuts/README.md</div>

**Comment by Rugvip** [comment]
The `import { CustomShortcutsImpl } from '...';` is an example that you need to replace with an import of your own implementation. The `'...'` path is not a valid import path in TypeScript.

Will close this since it's working as expected. Don't hesitate to open up a PR if you want to suggest improvements to the README though!
