### ISSUE TITLE
Enable re-use of frontend app through more dynamic configuration

### ISSUE THREAD

**Issue by djetelina** [backstage/backstage#14365]
## Feature Suggestion

As I've been moving my backstage instance from localhost to some kind of hosting, I came across an issue where it seemed like the application just ignores my configuration, namely baseUrl. Auth plugin tried to open a popup with `localhost` address. After many hours of debugging, I was able to figure out the root cause only when I resorted to asking on Discord (side personal note: boo Discord).

I don't know how exactly this 'problem' affects people deploying frontend and backend separately, but I imagine it's very similar. In my workflow, I am building a single monolithic Docker image which I would like to later apply to multiple environments (local, testing, pre-production, production). However currently, configuration gets baked in into the javascript files served to users, meaning that it is impossible to reuse the compiled/transpiled frontend application across multiple environments. 

I was a bit unsure whether to file this as a bug or a feature request, because it's a little bit of both. This behavior is unfortunately not documented anywhere I could find (and I looked hard), which might be considered a bug. But despite my humble opinion that this doesn't look like the best practice/pattern, I believe that there's a reason behind it and resolving this isn't simply fixing a bug, so I deem this a feature request, sorry if it's not :).

## Possible Implementation

Unfortunately, my area of expertise is in the backend/infrastructure, so I don't fully understand the possibilities of configuring a statically served frontend application. One though I had was to put (duplicate or split) the needed configuration into a special javascript file, which could be overwritten in the environment (e.g. through mounting of k8s configmap over the file included in the Docker image).

## Context

What I am trying to accomplish - I am hoping to build backstage image once, but use it multiple times :)

**Comment by TBragi** [comment]
I have just encountered the exact same challenge.

I have a buildpipeline which uses a `app-config.yaml` with `baseUrl` set to `localhost` since that is what I use for local development and testing, while my deploypipeline injects an environment specific `app-config.yaml` with a new relevant `baseUrl`.

This results in the same behavior described, where the webpage will be served correctly on the new `baseUrl`, but all plugins will return and `URL` pointing towards `localhost/<plugin>`.

Is this an feature which requires the building stage to now about the deployment environment, or is it a bug? 😸

**Comment by Rugvip** [comment]
Sounds like this should be fixed by #13927/#13872, right?

**Comment by djetelina** [comment]
Looks that way if it gets merged, using relative paths is a great solution 👍

**Comment by TBragi** [comment]
Looks really good!
Since I am not an experienced software developer I would like to ask:

This solution will allow an image build using the domain `my-domain.com` to serve frontend/backend at runtime on `my-domain.com/<Relative Path>` but it wont allow one to change the domain at runtime to e.g. `localhost`, correct?

**Comment by freben** [comment]
That's correct. What's the use case for doing that?

**Comment by TBragi** [comment]
In my situation my deployment environment is not reflected in my build pipeline (I thought it should only be reflected in the `app-config.yaml` file of the deployment). I am developing locally, thus using `baseUrl: localhost`, and my build pipeline uses that same configuration or whatever is last pushed to GIT. 

But my deployment environment could be  `baseUrl:` `backstage-staging.company.com` or `backstage.company.com` or something entirely different `temporary.domain.com`.

 I guess my question is towards is it intended that the build process must have knowledge of the deployment environment?  Is this due to the nature of a static frontend? If so I just have to change my build pipeline to allow for this 🆗 .

**Comment by Rugvip** [comment]
No it's actually the case that #13872 should allow you to build a frontend bundle that doesn't require any particular origin. The backend will still need a specific app URL with origin at runtime to manage CORS and login though.

**Comment by TBragi** [comment]
Awesome! So the backend app URL used in the build stage will be "overwritten" by the app URL given in the deployment `app-config.yaml` file? 😄 
If so then it also fixes my challenge! 👍

**Comment by Rugvip** [comment]
Closed along with #13872

**Comment by Silthus** [comment]
How can I use this with the new change from the PR?

I can't get the deployment to work with feature branches setting the same URL. The AzureAD OAuth Provider always redirects to the wrong localhost url and not the origin. Do I need to change something there as well?

```yaml
app:
  baseUrl: http://localhost:8080

backend:
  baseUrl: http://localhost:8080
  cors:
    origin: http://localhost:8080 # ?? what do I need to put here?
```

**Comment by Rugvip** [comment]
@Silthus this PR only applies to the frontend configuration. The backend configuration isn't capable of the same discovery by origin and must always have correctly configured `app.baseUrl`, `backend.baseUrl`, and if needed, `backend.cors.origin`.
