### ISSUE TITLE
🚀 Feature: Allow updating components generated from scaffolder templates

### ISSUE THREAD

**Issue by taras** [backstage/backstage#14416]
### 🔖 Feature description

As a DX engineer who maintains a Backstage portal or a platform engineering, I want to ensure that all components scaffolded from a template are updated whenever the template changes. Ideally, the Backstage App would show all of the components that were created from a specific template, allow rolling out changes to each component by creating PRs in repositories for these components and show the status of these updates.

### 🎤 Context

This request often comes up in Discord. I'm creating this feature request as a placeholder. If you need this feature, please 👍 .

### ✌️ Possible Implementation

There are several tools that list support for this,

* [copier](https://copier.readthedocs.io/en/stable/)
* [cruft](https://cruft.github.io/cruft/)
* [update](http://update.github.io/update/)

Both of them are written in Python just like [cookiecutter](http://cookiecutter.readthedocs.io) which was the original scaffolding tool before Nunjucks-based scaffolding was introduced. The challenge with Python is that it requires system-level access which is difficult to secure.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Pike** [comment]
Thanks for filing.

I think there are two dimensions we have to tackle here.

One is figuring out which components got generated. And the challenge in the scope of backstage is that the templating engines don't matter for that one. The real-world impact of the scaffolding process happens inside actions, commonly outside of the actual templating action. Most often, the templating will happen in `fetch:template`, but impacting external components will happen in `publish:github`. And each custom action can create an arbitrary amount of external components or just side-effects.

I have no idea how one would build the mapping here.

The other is how to map local changes to remote changes. Our templates for example have quite a bit of example boiler plate that we expect to be modified heavily.

Is there a good way to separate boilerplate from essentials?

**Comment by regicsolutions** [comment]
Distributing the templates as versioned NPM packages is an option, actions like @Pike mentioned will be tricky maybe appending a version to the action within the template is an option? 

```
steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
         version: 1.0.0
```

**Comment by tomas-mota** [comment]
We could add a field to the component which might look like something like this:

```
    templatedFrom: github.com/myorg/templaterepo/commit/6f7faf5333f63620c05ab08edc7922053e647362
```

The problem is that unlike other tools, which assume everything comes from a single template, skaffolding in Backstage allows for fetching different templates and merging them into a final result, which makes it quite hard to track the source.

**Comment by regicsolutions** [comment]
Wondering if anyone has come up with a solution to keeping templates up to date?

**Comment by sharadpattanshetti** [comment]
One of the possible solutions is to leverage `[cruft ](https://cruft.github.io/cruft/)` framework and track the component status wrt template from which it was generated. Backstage can help track status contiguously.

**Comment by regicsolutions** [comment]
> I would like to see support for [copier](https://copier.readthedocs.io/en/stable/)
> 
> I matters less to me whether backstage can track projects needing update, than it does being able to update the generated project. Directly using copier cli to update generated repository with template changes will be fine.

Looks like there is already a module out there: https://github.com/telia-oss/scaffolder-backend-module-copier

**Comment by lhupfeldt** [comment]
Thank you, great news.

**Comment by Carl132** [comment]
Hey all - just wanted to follow up on this. I tried using the module here: https://github.com/telia-oss/scaffolder-backend-module-copier but was met with an error:

![copier-yarn-error](https://github.com/backstage/backstage/assets/22191995/33857f24-1d9f-4fa5-8749-d35f2d127268)

and upon further investigation it seems that the yarn module for this has just been deleted from the registry:

![image](https://github.com/backstage/backstage/assets/22191995/290c6736-a57f-4a12-9870-66b8de072989)

I think I'm right in saying that, because of this, there is currently no support for `copier`, which I can see for a few people (including myself) would be great to see.

@mspiegel31 did you ever get anywhere with an implementation? I know you had a PR here: https://github.com/backstage/backstage/pull/20362 that got closed because the author of the github repo above never responded...

Might be worth revisiting this now that we know the `copier` implementation that was taken to already exist now doesn't.

**Comment by OSobky** [comment]
Hello all & @vinzscam & @freben, would it be possible to plan & reopen this feature in the upcoming releases? 😄 

I think it is very useful to support Copier (or other templating engine) to allow a workaround for updating created entities through templates. or do you have another apporach on mind for handling the updates?

**Comment by raihle** [comment]
The module linked above was never published under that name (given that Telia does not have access to the `@backstage` organization in NPM). The install instructions probably never worked, or if they did then they only worked internally with a specific registry mirror.

But there is a fork that seems to be better maintained and properly published: `@diamondlightsource/plugin-scaffolder-backend-module-copier` (https://github.com/DiamondLightSource/scaffolder-backend-module-copier)

**Comment by rdnkmrr** [comment]
@raihle Thanks for the details, looks like the above example looks like it is designed for old backstage backend version. Can we have some examples for new backstage, or do we need to explore the same?

**Comment by dgenio** [comment]
I think there may be a smaller primitive here that addresses the hardest part of this issue without requiring Backstage to solve template inheritance or three-way merges.

@Pike called out the core difficulty earlier: the real-world effects of a scaffolding run happen inside actions, custom actions can create arbitrary external resources, and a task may compose multiple fetched templates. So a single `templatedFrom` relationship is often too weak, while inferring provenance after the fact is unreliable.

What if Scaffolder actions could explicitly report **standardized external effects** and the task engine aggregated/persisted them?

Conceptually:

```ts
ctx.effect({
  resource: {
    type: 'scm-repository',
    ref: 'github.com/acme/payments-api',
  },
  operation: 'create',
});
```

and later in the same task:

```ts
ctx.effect({
  resource: {
    type: 'catalog-entity',
    ref: 'component:default/payments-api',
  },
  operation: 'register',
});
```

The Scaffolder already knows the task, template, step and action identity, so those could be attached automatically. Built-in publish/register actions could emit well-known effects; custom actions could emit the same provider-neutral shape for their own resources.

This would be deliberately different from normal `schema.output` / `ctx.output`. Action outputs remain action-specific values used by later steps/templates. Effects would be a tiny interoperable semantic layer answering one cross-cutting question:

> **What externally addressable resources did this task create or materially change?**

That would enable a useful set of second-day workflows without making Backstage itself own update mechanics:

- list resources/repositories originally affected by a template or task;
- drive migration/update campaigns that open PRs only where appropriate;
- audit what a scaffolder execution changed;
- let plugins track fleet update/conformance state using one convention instead of organization-specific annotations;
- preserve provenance when one task composes several templates/actions.

One distinction I think matters here: **template lineage is evidence about origin, not proof of current conformance**. A repository may have diverged intentionally, adopted a newer requirement manually, or only need one subset of a template change. Automatically replaying the template is therefore not always the right operation.

So I would separate the problem into:

```text
execution provenance / effects
        ↓
which resources may be affected by a later change?
        ↓
assess current state / applicability
        ↓
choose update mechanism (PR, Copier, OpenRewrite, manual, etc.)
```

This also avoids having to answer “how do we merge boilerplate that teams have heavily edited?” inside the provenance primitive. Copier or another updater can still be one implementation of the final step.

If this direction fits Scaffolder, I would be happy to turn the idea into a smaller focused issue/BEP around the action/task API rather than reopening the full automatic-template-update problem.
