### ISSUE TITLE
💬 RFC: OpenTelemetry-based Discovery

### ISSUE THREAD

**Issue by smithclay** [backstage/backstage#14518]
### 🔖 Need

The [OpenTelemetry Collector](https://opentelemetry.io/docs/collector/) is a vendor-agnostic way to process telemetry data (metrics, logs, and traces). The collector has a [popular and growing ecosystem](https://github.com/open-telemetry/opentelemetry-collector-contrib) of components that allow it to be customized to receive, process, and export data to and from different backends, vendors, APIs.

As more organizations send their telemetry through the collector, it becomes a valuable place to discover cloud infrastructure, microservices, or other resources in a vendor-neutral way. The OpenTelemetry conventions for [describing resources are defined here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md).

The collector could automate discovery for teams that need to include different services and infrastructure in their Backstage catalog by syncing "resources" inferred from their telemetry data and syncing with Backstage.

### 🎉 Proposal

This proposal has two parts:
* Defining the mapping between OpenTelemetry conventions for [describing resources](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md) and Backstage entities.
* Writing an OpenTelemetry Collector [exporter](https://opentelemetry.io/docs/collector/configuration/#exporters) to either pull or push discovered resources to Backstage instances. With distributed traces, service-to-service relationships could also be inferred.

_Not in this proposal_, but a potential future direction: enriching telemetry with Backstage data (i.e. annotating metrics or traces with the Backstage entity id).

### 〽️ Alternatives

* Vendor-based solutions (i.e. discovery via an APM vendor's REST API)

### ❌ Risks

* The OpenTelemetry resource conventions are [not finalized yet](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md), but have been stable recently.
* Discovery will only work if the "thing" being discovered emits metrics, logs, or traces in a standard way

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by freben** [comment]
Hi, and thanks for the RFC!

We're very keen on leveraging OpenTelementry, both within the project so that our services and plugins produce telemetry into it, and also to let users leverage their own service's otel data in Backstage.

Regarding the specific propositions,

We are strong proponents of _declarative_ and _intentional_ entity creation. The ideal case is catalog-info files living right next to the source code that they describe, and those being created automatically and easily as part of scaffolding your service. These files describe _intent_ and often contain human curated information that cannot easily be deduced by automation. You typically do not want entities to be created automagically out of runtime circumstances elsewhere; it typically goes the other way around: the entity comes into play first, often long before the runtime resources have even begun manifesting themselves. And that entity contains enough information (maybe in annotations, or by other means) to be able to get all of the required auxiliary data to power user's Backstage views and to dig deeper into external systems.

The entities are very carefully curated "anchors" for functionality, representing the human mental model of things, and their names and intents may look quite different to the runtime world. For example, a database that has a primary and three slaves in different regions, and which might have some complex identifier in the cloud vendor's eyes, might be represented by a single hand-made Resource entity with the name `frobs-service-database` whose name and ownership makes perfect sense to humans. Then that entity might have an urn or whatnot inside it that lets you fetch rich contextual data about it as well.

All of this is to say, that yes you CAN make an entity provider that produces root entities automatically based on otel data, but that may be undesirable, or at least really suboptimal, for several reasons.

That being said, there's ample opportunity to make a lot of other cool stuff!

One major quality of life improvement would be if we could get automatic deduction of relations between entities. Maintaining a list of "who calls whom" among services is bound to quickly get inaccurate and tiring to maintain. But if we could leverage tracing data to always have an accurate, true image of our consumers, then that is extremely valuable in many scenarios such as resource planning, handling of decommissioning scenarios, etc etc.

And even if we didn't create the "root" entities based on otel data automatically, at least we could make views that identify problems based on it. You could have a banner on the top of your team page saying, hey we found these two deployed services that do not seem to have any catalog registration, here's an article that helps you correct that mistake" etc.

Presenting telemetry directly related to your entity directly in the interface is a no-brainer. But also tricky, because you might not want to reinvent the entire grafana etc interfaces either, so perhaps presenting pertinent and condensed info but linking out into third party tools for the full views?

Once we have foundations for how to express keys from entities to otel, and maybe some abstraction for how to very easily get at that data, I bet you or the community can come up with a lot of other cool usages.

**Comment by smithclay** [comment]
Thanks for the comments, think there's definitely something to explore here:

> One major quality of life improvement would be if we could get automatic deduction of relations between entities. Maintaining a list of "who calls whom" among services is bound to quickly get inaccurate and tiring to maintain. But if we could leverage tracing data to always have an accurate, true image of our consumers, then that is extremely valuable in many scenarios such as resource planning, handling of decommissioning scenarios, etc etc.

Recently, the OpenTelemetry Collector added support for generating service topology from traces using the [Service Graph Processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/servicegraphprocessor). 

A potential direction would be that Backstage uses the metrics from that processor to automatically build relationships between service entities (in the same way other tools like Grafana do to build visualizations). If Backstage is considering at using OpenTelemetry for Observability (previously discussed: https://github.com/backstage/backstage/issues/1519), the same SDK could be used to to consume service topology data and instrument Backstage itself.

**Comment by Rugvip** [comment]
> If Backstage is considering using OpenTelemetry for Observability (previously discussed: #1519), the same SDK could be used to to consume service topology data and instrument Backstage itself.

Yep, but I'd also say we definitely don't need to wait for OpenTelemetry adoption for Observability before building something like what's proposed here.

**Comment by awanlin** [comment]
@jhaals should this be stale? I feel like you have been doing work in this space. Or is this something else we should be using to track this?

**Comment by blakeromano** [comment]
To me this seems more like a way to implement an Open Source APM solution into Backstage (something similar to Signoz or Uptrace). I think there's massive demand for it, and done right it could be really well. It is something that maybe you use Clickhouse as the DB. Or use the eventing structure you have with the OpenTelemetry Kinesis or Kafka exporters to use.

**Comment by ankitnayan** [comment]
> To me this seems more like a way to implement an Open Source APM solution into Backstage (something similar to Signoz or Uptrace). I think there's massive demand for it, and done right it could be really nice. It is something that maybe you use Clickhouse as the DB. Or use the eventing structure you have with the OpenTelemetry Kinesis or Kafka exporters to use.

We would be happy to make this happen. Being open-sourced and native to OpenTelemetry, it makes a lot of sense. If there is enough interest and permitted, we would love to spend time to make an integration.

**Comment by rochaporto** [comment]
This came up during an internal discussion. @ankitnayan are you still looking into it?

**Comment by ankitnayan** [comment]
> This came up during an internal discussion. @ankitnayan are you still looking into it?

Not right now. I don't know the interest level of the maintainers.
