### ISSUE TITLE
🐛 Bug Report: GithubOrgEntityProvider.userTransformer not available in packages

### ISSUE THREAD

**Issue by cthtrifork** [backstage/backstage#14555]
### 📜 Description

The code is available in the `master` branch:
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/providers/GithubOrgEntityProvider.ts#L96

and the usage is documented:
https://backstage.io/docs/integrations/github/org#custom-transformers

But when using the packages, such as 
https://github.com/backstage/backstage/blob/v1.8.0-next.0/plugins/catalog-backend-module-github/src/providers/GithubOrgEntityProvider.ts

It is not available!

### 👍 Expected behavior

Being able to access userTransformer  when configuring GithubOrgEntityProvider

### 👎 Actual Behavior with Screenshots

No screenshot

### 👟 Reproduction steps

Try follow steps in https://backstage.io/docs/integrations/github/org#custom-transformers and see options are missing

### 📃 Provide the context for the Bug.

https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-github/src/providers/GithubOrgEntityProvider.ts#L96

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Wow, that was fast - I [merged the pull request](https://github.com/backstage/backstage/pull/13640#event-7780607533) just four hours ago :)

Essentially this is just how it works today. Docs get pushed to the microsite immediately, without any versioning, and master also gets updated immediately, but we only make releases once per week. New features that have docs, will make the docs out of sync until next Tuesday. So this is just how it is, for a few days more, since the feature isn't released yet. It sure can be confusing.

**Comment by ScottGuymer** [comment]
Thought I had made some kind of mistake for a moment then!

Thanks for clearing it up @freben
