### ISSUE TITLE
💬 RFC: Improve MS Graph Onboarding experience

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#14757]
### 🔖 Need

I've seen a lot of support questions coming into discord around the MS Graph entity provider not appearing to work.  Most of this comes down to a combination of
* Results not showing in backstage until the entire process has been complete
* The default configuration of the entity provider doing a lot of work, which can take a significant amount of time.

### 🎉 Proposal

Whislt there are some small wins that could be made by increasing the page size to the maximum (`$top=999` odata query param) and adding a config option to allow skipping avatar loading, the major issue however comes from the pit of failure you can fall into which is loading more data than you think.  

All users can include:
* Guest accounts from other orgs (`userType eq 'guest'`)
* Service / non human accounts.
* Accounts that are disabled
* Users in non technology parts of the business.

Groups also contain a lot of different things - a lot more than most people realise
* Mailing / Distribution Lists
* Security Groups
* Teams from MS Teams

Whilst some of this can be fixed through improved docs (the current article doesn't make it clear how important it is to restrict the users & groups you import), the default configuration loading everythign can lead to users unintentionally getting stuck loading large volumes of data.

I suggest changing the default configuration to not load anything unless explicitly configured.  When not configured, the provider should log a message indicating so (e.g. "skipping loading of groups groups as no query has been configured")

### ❌ Risks

Changes to the defaults may be breaking changes for some users.  That said, I imagine all would be able to be work around by adding some kind of config to get back to the old configuration (if that was really the behaviour they wanted) so this risk should be mitigated by a well written changeset.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by jhaals** [comment]
I agree that having a more explicit configuration might be a good idea to make a conscious decision about what to ingest. It's probably hard to have something generic that works for everyone as every org probably mark their service accounts and groups differently.

Would love some community input from our msgraph users. I know @pjungermann has worked a lot on these features and might have valuable feedback and suggestions.

**Comment by pjungermann** [comment]
hmm.. even though I get your intention, not sure if this will work so well. At the end, every org is a bit different.

E.g., do you want to exclude users outside of your tech (and product) department(s)? Or do you allow read permissions to everyone? And even if, how you identify them is org-specific.

The readme even contains an example covering some of your points.

If I get you right, you would like to force users to make a conscious choice when configuring their filters.

Maybe it is good enough to make some of the configs required instead of option, if you want to enforce their use. There are a few mutually exclusive settings though.

However, let's say you want to enforce the use of `filter` -- what if someone wants to use `search` instead?

For `user.filter` you could potentially default to `accountEnabled eq true` or `accountEnabled eq true and userType eq 'member'`. It is mutually exclusive to `userGroupMember.filter` (which could be handled while applying defaults).

Another option:
Add a paragraph to the docs emphasizing the importance of setting the right selection of users.

**Comment by afscrome** [comment]
Either Filters or search, in other words consumer would be required to set one or both of `user.filter` or `user.search`.  If none is given, then no users would be ingested. (unless `userGroupMember` is configured)

I think the opt in behaviour is particularly important for Groups as the current set up has no easy way to turn off group ingestion if you want to get membership data from another source.  We've manged to fake this behaviour by writing a query that can never match any group, but that feels like a bit of a hack.

**Comment by pjungermann** [comment]
@afscrome Makes sense to me. No concerns from my side.

We use `filter: displayName eq '__NONE__'` for groups, too, and get groups from somewhere else.
