### ISSUE TITLE
🚀 Feature: Make it possible to specify versions of dependencies

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#14875]
### 🔖 Feature description

It should be possible to specify versions of dependencies in entity definition.

### 🎤 Context

Currently, we can provide dependencies of an entity in the `spec.dependsOn` field. But we can't specify versions of the dependencies. This information is especially valuable in some cases.

For example, when there is a vulnerability in a version of a component, we would want to find the components that are using this particular version and notify their owners. As another example, when a version of a component reaches the end of its life, we would want to analyze the dependencies to find out if there are any components using it.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jhaals** [comment]
Hi!

The Catalog at least in it's current form is not designed to hold versioning and other information of that granularity. For example, internally we might have a "playlist" component that exposes several versions of the playlist API from the same component and generated artifact. In cases where the system get a major rewrite and is essentially a new component we tend to create a `playlist2` component in Backstage but in general we do not store more granular information in the catalog.

As vulnerability scanning goes it's typically done for the package dependencies of the component rather than the API itself. In which tools like Snyk might be a better fit to hold or monitor that data and then visualise it in backstage(there's a plugin for it).

Similarly determining dependencies on an active API is tricky with manually curated files and it's hard to know if the API is still access so that's where tracing or metrics might be a better source to gauge if there are still requests trickling into the service.

A lot of words for me saying that the catalog is at least currently a poor fit for this information and it might be better to call out to auxiliary systems but still display that data on the entity page 😅 I hope my rambling make some sense.

**Comment by omerfarukdogan** [comment]
Hello @jhaals,

Thanks for your comments.

First of all, I would like to point out that we automatically generate dependsOn field based on information gathered from service dependencies etc., therefore we expect this information to be reliable. Otherwise, we would prefer not using that field at all if it was edited manually, since it could contain incorrect information and be misleading.

I think people might want to see which version of the component is depended on at any time. If we have to integrate an external tool for this requirement, doesn't this make the dependencies in Backstage unnecessary? Moreover, Backstage and the external tool could show different dependencies and that would confuse users.

Do you think it would make sense to accept additional information in dependsOn field, and show that information on edges of the relationship graph?

```
dependsOn:
  - component:sample-1@v1
  - component:sample-2@v1.2.1
  - component:sample-2@^2.1.2
```

**Comment by freben** [comment]
We've discussed having metadata ON generated relations (e.g. carrying relation metadata all the way through the model so that they can be read in the other end through the API). Then you could in theory have had versions on the arrows between things. But it turns out to be technically complex and not a heavily requested feature, so it's not something that's prioritised or worked on at this point.

Often when there already exists an external source of information of something, we ask ourselves: "MUST this be in the catalog in the first place, or should we just query that external source on-demand when we want more info?". There's a cost and risk to adding too much to the catalog that doesn't have to be there. Could it be the case that unversioned edges are fine here in the model you already have - as they are automatically generated and they really help forming the knowledge graph in Backstage? And then, only when you click into the entity view, it performs an on-demand query to the backing system what the actual used versions are, and displays that?

If the above is absolutely not an option for some reason, you might consider extending the catalog model. Instead of using `dependsOn`, invent a new `spec.libraryDependencies` or whatever name makes sense. Then you can put exactly what you want in there. As a thought experiment:

```yaml
spec:
  libraryDependencies:
    - entity: component:sample-1
      versionRange: ^2.1.2
      resolvedVersion: 2.1.7
      artifactUrl: https://some-artifactory-link
```

And then you add a processor that iterates through these and emits a `dependsOn`/`dependencyOf` pair for each entry. Then the frontend can read directly out of the entity body to get what it needs.

But again, this may be unnecessary indirection and duplication of data to do.

**Comment by omerfarukdogan** [comment]
Hello @freben,

Thanks for discussing this. We can show dependencies with version information in the Entity page, but we thought it would be useful if the catalog graph included that information.

We will consider extending the catalog, but it seems like too much customization. Would we also need to customize the graph to show version info on the edges?

**Comment by freben** [comment]
Yeah, you'd probably have to make a different graph component, inspired by the standard open source one so it can get additional info to display on the edges - since the edges themselves (as in, the relations info in the core catalog model) don't have any space for additional data directly on themselves.
