### ISSUE TITLE
🔌 Plugin: Allow publishing of dbt docs within TechDocs 

### ISSUE THREAD

**Issue by brandon-segal** [backstage/backstage#15010]
### 🔖 Feature description

This backstage plugin would allow teams to render dbt docs within their backstage instance to allow teams to view the lineage definitions and documentation related to their dbt data models and metrics. 

### 🎤 Context

A dbt docs backstage plugin that does the bare minimum of showing the dbt documentation generated from a dbt project would be greatly helpful for getting increased adoption of Backstage from Tech teams that work with building SQL data pipelines in their data warehouse. 

Data Catalog solutions like [Atlan](https://ask.atlan.com/hc/en-us/articles/4433673207313-How-to-set-up-dbt-Cloud), Alation, [Collibra](https://marketplace.collibra.com/listings/dbt-lineage-to-collibra-integration/), [Metaphor](https://support.metaphor.io/hc/en-us/articles/9302185081627), [Select Star](https://docs.selectstar.com/integrations/dbt/dbt-cloud), [Castor](https://docs.castordoc.com/integrations/dbt), and others.

### ✌️ Possible Implementation

The dbt docs are rendered from an index.html, manifest.json, and catalog.json file generated by a run of `dbt docs generate.` The index.html is an SWA that renders data from the colocated manifest.json and catalog.json files. These files would need to be able to be retrieved from a known location and rendered within a backstage page to accomplish this task. 

Ideally, the location of the manfiest.json and catalog.json would be in some blob storage location like S3 or GCS so that the docs could be updated whenever the dbt pipeline ran and deposited an updated set of the manifest.json or catalog.json. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
I've spent less than a minute thinking about this, but this is the actual dbt docs implementation right? https://github.com/dbt-labs/dbt-docs 😅. Given that it's in JS, I wonder if it's possible to wrap it up in a Backstage backend plugin, using it as a library to serve the docs directly, generated on the fly.

Going via GCS/S3 can be troublesome if the docs require client-side scripts to function, since not removing those scripts will open up for script injection vulnerabilities. Another option if scripts are an issue is if there's a fixed script that we can add to the client to support the HTML, so scripts provided by the client, but HTML loaded from object storage.
