### ISSUE TITLE
🚀 Feature: Add plugin-react template to backstage-cli

### ISSUE THREAD

**Issue by taras** [backstage/backstage#15065]
### 🔖 Feature description

We want to make it easy for Backstage operators to create frontend plugins by adding a new template and an option to `backstage-cli new`. This new command will include frontend plugin functionality. 

### 🎤 Context

This is a follow up based on conversation in https://github.com/backstage/backstage/pull/14840#issuecomment-1339100921

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
This can be a quick followup for #14840, mostly likely being more or less a copy of that. I think it makes sense to explore opportunities for refactoring to eliminate duplication as well, but would consider that optional.

**Comment by taras** [comment]
@AnshumanPadiya https://github.com/backstage/backstage/pull/14840#issuecomment-1339100921 is getting wrapped by @kurtaking but there is no one working on this as I'm aware. You're welcome to pick it up. Feel free to create a draft PR when you're ready for an early review.

**Comment by kurtaking** [comment]
@AnshumanPadiya, if you pick this up and need help, feel free to tag me on a PR. I'll do my best to assist 😃

**Comment by AnshumanPadiya** [comment]
@taras Sure thing! 

@kurtaking Glad to hear that! I am trying to understand the flow of plugins by reading [this](https://backstage.io/docs/plugins/plugin-development) and also by following your commits in #14840. I will let you know if I face any issue

**Comment by kurtaking** [comment]
> @taras Sure thing!
> 
> @kurtaking Glad to hear that! I am trying to understand the flow of plugins by reading [this](https://backstage.io/docs/plugins/plugin-development) and also by following your commits in #14840. I will let you know if I face any issue

The eslint error was a fun thing to get around. Especially since I lacked knowledge around husky and how the pre-commit checks were working. Still not sure I fully understand 😅 . Keep [this](https://github.com/backstage/backstage/pull/14840#issuecomment-1329258223) recommendation in mind.

**Comment by AnshumanPadiya** [comment]
@kurtaking I followed #14840 and tried to replicate what you have created for the web-library-package with plugin-react template as stated in the issue above

![plugin-react](https://user-images.githubusercontent.com/53999212/206871009-2b0568af-d1ad-4f75-90e6-012359679101.PNG)


However, I wanted to confirm the direction I am moving in since I was not able to fully understand the whole conversation in #14840, it would be great if anyone can help me with this.

**Comment by kurtaking** [comment]
@AnshumanPadiya, do you have a draft PR to look at?

**Comment by Rugvip** [comment]
@AnshumanPadiya I think it's best to hold off on this until #14840 is merged, so that we iron out any issues there first. This would be pretty much identical to that template, maybe just differing in name and target path. I'm not sure we'd call this `plugin-react` tbh, it might be `plugin-library` or something like that instead. The package we're looking to create is a `web-library`, it's just that it's tied to a particular plugin rather than being a generic one.

**Comment by kurtaking** [comment]
@AnshumanPadiya https://github.com/backstage/backstage/pull/14840 has been merged. Do you have the direction needed to make progress on this?

**Comment by AnshumanPadiya** [comment]
@kurtaking Sorry for the late reply had my final exams last week. My initial thoughts to move forward with this issue is to create a `plugin-library` template, which will be a new option alongside `web-library`, `plugin`, etc in `backstage-cli new`. Which will be more or less the same thing as #14840 as much as I am able to understand. I can file a PR if this sounds good to everyone.

**Comment by jhaals** [comment]
Sounds good! It will be very similar but plugin specific :)

**Comment by kurtaking** [comment]
> @kurtaking Sorry for the late reply had my final exams last week. My initial thoughts to move forward with this issue is to create a `plugin-library` template, which will be a new option alongside `web-library`, `plugin`, etc in `backstage-cli new`. Which will be more or less the same thing as #14840 as much as I am able to understand. I can file a PR if this sounds good to everyone.

Awesome, good luck with wrapping up the semester. We look forward to the PR 😄

**Comment by kurtaking** [comment]
Hey, checking in on this. @AnshumanPadiya, do you still have the time to look into this? I could pick it up at some point if you are busy with school.

**Comment by malikahmontgomery** [comment]
@freben I am reviewing this issue/new feature.  I would like to pick up if still needed

While reviewing the backstage-cli new feature I am seeing that there is already a plugin-react option.  Is this issue to update that functionality or create a new plugin-library with a set template?  Please confirm 

cc: @freben @kurtaking 

<img width="661" alt="Screen Shot 2023-05-19 at 10 39 23 AM" src="https://github.com/backstage/backstage/assets/48798718/bd02d55b-acd5-4eae-9ada-b267cb66f736">

**Comment by Rugvip** [comment]
Sorry this was added in #16803. Closing this as it's implemented
