### ISSUE TITLE
🐛 Bug Report: Sidebar of components under code insights erratic behaviour

### ISSUE THREAD

**Issue by NivethaJayaveeran** [backstage/backstage#15071]
### 📜 Description

The sidebar of the component increases its width while moving into code insights entity layout page.

![Screenshot (502)](https://user-images.githubusercontent.com/102040284/206113256-03d6a964-7f6e-453e-8b35-72156768ecf0.jpg)

The card space is reflected in the sidebar.

![Screenshot (501)](https://user-images.githubusercontent.com/102040284/206113326-978d212e-f04c-44b8-a7ba-961192d4e708.jpg)

### 👍 Expected behavior

The Grid spacing should be adjusted in such a way that on page load the cards should auto adapt to screen size.
Customize the size of the card relative to the screen size.

### 👎 Actual Behavior with Screenshots

Given in the description above.

### 👟 Reproduction steps

Given in the description above.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Sorry you've got the wrong repo, this plugin is over at https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-github-insights 😅

**Comment by NivethaJayaveeran** [comment]
@Rugvip the above shared screenshot is an example of already implemented github insight plugin in our application while loading the page the cards that get displayed moves to the sidebar depending on the screen size. We tried pull in this plugin into our application but the issue still persists.
Should this concern be solved here?

**Comment by Rugvip** [comment]
I haven't quite understood the actual issue here tbh. If it's the case that the sidebar expands above the content if you hover it while it isn't pinned, then that is intended behavior. If it's a different layout bug to do with sidebar expansion, window resizing, or w/e, then I'm not able to reproduce that with our own card layouts so it might be plugin specific. Either way, if there's a bug here, please reproduce it using plugins or components from this repo.
