### ISSUE TITLE
🚀 Feature: Ability to sync table component filters with URL query string

### ISSUE THREAD

**Issue by yousifalraheem** [backstage/backstage#15106]
### 🔖 Feature description

Develop a feature for the Table component in `@backstage/core-components` library that either enables the Table to automatically update the URL query string when filters change, or enables initialization of filter values. Either way, it should make it easy to have the table read and write to the URL query string.

### 🎤 Context

I work at Zalando on building an internal platform based on Backstage. In the platform, we use your Table component from `@backstage/core-components` library for various purposes but we had to decide to develop a custom look-alike table for few instances because we needed to have sharable URLs to the filtered view of the table. That is still a limitation in the component itself. There isn't a way to pass filter values (as far as I know). The only thing we can access is `onFilterChange` which would be great to update the query string but isn't enough to update the filters upon initialization.

### ✌️ Possible Implementation

- The Table component currently only exposes `onFilterChange` callback. In order to sync properly with the URL query string, we would have to implement a filter `defaultValue` option to be either the value itself or a function that returns the value. That way we can pass a query string reader callback that returns the default value upon initialization.
    ```diff
    -  declare type TableFilter = {
    +  declare type TableFilter<T = any> = {
          column: string;
          type: 'select' | 'multiple-select';
    +     defaultValue: T | () => T;
       }
    ```

- Do the magic behind the scene without having the user care about grabbing values and setting them. The table would just have a boolean toggle of the feature. The table will deal with creating the URL query strings and do read/write operations as necessary.
    ```diff
    <Table
        data={data}
        filters={filters}
        options={{
    +      updateQueryString: true,
        }}
    />
    ```

We could even have this option as an object specifying what to update allowing for more flexibility. For example:
```ts
updateQueryString: {
  sorting: true,
  filtering: true,
  searching: false,
}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Hm. This touches upon the choice of wanting controlled components or components that control themselves.

For the catalog page, we've decidedly gone for the controlled component idea. There's an external filtering and retrieval system that deals with finding the right data to display, and then it force-pushes that data to the table which has no say whatsoever in the matter. Then, the external filter system is also responsible for dealing with the query string.

It may also be worth mentioning that there's a bit of a brewing desire to take a careful look at the component library and streamlining it. Making components more fleshed out and better where that makes sense, and stripping away things that make little sense to wrap anymore and where users are better served to instead just use the underlying library directly.

Given the above, I'd vote to do the first suggestion, if anything. Being able to supply a default value seems very sensible as long as the filtering ability is exposed at all.

In a future iteration of the component library, we'll see if we go in the direction of fleshing out the table _more_... or whether to take a step back and instead promoting the use of the underlying react-table more directly. That may be some ways off though, since there are other more pressing things on the road map first.
