### ISSUE TITLE
🐛 Bug Report: Bitbucket catalog fetch does not allow specifying path or port

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#15233]
### 📜 Description

If the bitbucket integration has a path or port appended to the apiBaseUrl (for example: https://myorganization.com/bitbucket/rest/api/1.0 or https://mybitbucketinstance.com:1234/rest/api/1.0), the catalog fetch fails as it only uses the host and protocol part of the URL for file fetching. 

### 👍 Expected behavior

The bitbucket catalog should include possible paths or ports to the URLs used

### 👎 Actual Behavior with Screenshots

The catalog fetch fails with error "catalog warn Unable to read url, NotAllowedError"

### 👟 Reproduction steps

1. Set up bitbucket server to run in subpath or in different port
2. Set up bitbucket server integration config apiBaseUrl and host to point to the instance
3. Start backstage and wait for the catalog refresh

### 📃 Provide the context for the Bug.

Host and protocol only used here: 

- https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-bitbucket-server/src/lib/BitbucketServerClient.ts#L70
- https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-bitbucket-server/src/lib/BitbucketServerClient.ts#L93

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Also port is not supported, maybe I should update the title of this issue.

**Comment by pjungermann** [comment]
I'm more on the Bitbucket Cloud side of things. However, maybe my generic understanding is enough.

Also, I might need a few more details here :)

Overall, we have two URLs:

1. The Location target pointing to a catalog file. Usually, this is the same URL as you would see in a browser when you open the file there.
2. The " fetch URL" / API URL used to fetch the content of the catalog file.

`BitbucketServerUrlReader` will receive the Location target and uses `getBitbucketServerFileFetchUrl` with that URL as well as the matching integration to convert it into the "fetch URL".

An UrlReader instance is always for one integration and matching for that one is host-based (incl. potential port I believe).

`getBitbucketServerFileFetchUrl` will return

```ts
return `${config.apiBaseUrl}/projects/${owner}/repos/${name}/raw/${pathWithoutSlash}?at=${ref}`;
```

where `apiBaseUrl` is a required config property:

```ts
  /**
   * The base URL of the API of this provider, e.g. "https://<host>/rest/api/1.0",
   * with no trailing slash.
   *
   * The API will always be preferred if both its base URL and a token are
   * present.
   */
  apiBaseUrl: string;
```

Instead of `"https://<host>/rest/api/1.0"` you should be able to add a port there as well.

The code does not care about details of the `apiBaseUrl` value (whether it contains a port or a path prefix. As in the docs, it must not end with a slash character and has to include the API path prefix as of your installation (usually, `/rest/api/1.0`).

`ScmIntegrations` itself will find the right `BitbucketServerIntegration` using the host as matching criteria.

```ts
  /**
   * The host of the target that this matches on, e.g. "bitbucket.company.com"
   */
  host: string;
```

In case your `host` value is not just the host but also contains a port and/or path prefix, this part will fail. (see `ScmIntegrationsGroup.byUrl` implementation of `basicIntegrations` which will use `new URL(url).host` to be matched against the config value).

In that case, you can leave the host only at the `host` config but have port and/or path prefix at the `apiBaseUrl` config (which needs to be valid (base) URL).

@drodil Would be great to share some more details about your config and the whatever you can find about the errors (stacktraces, ...).

**Comment by drodil** [comment]
Hi,
Apparently, this was my own mistake. After reading the source code it looks like the catalog URL is actually using the repository.links.self[0].href as a baseline. Also with a quick look, it seems that neither of those functions outside tests is used in the plugin (?). I am closing this issue, for now, thanks for your quick support!
