### ISSUE TITLE
🐛 Bug Report: Printing via browser does not work (e.g. docs)

### ISSUE THREAD

**Issue by dschwank** [backstage/backstage#15239]
### 📜 Description

Users might want to print pages (like the docs) using the browser built-in print function. Right now this leads in most cases to empty / almost empty pages.

### 👍 Expected behavior

It should be possible to print single backstage pages - especially the techdocs pages. The content should be reduced to a minimum - e.g. the menu shouldn't be on the printed page.

### 👎 Actual Behavior with Screenshots

Right now the printed page has issues with the `dark` / `light` theme and the overall styling. Using the `light` theme some text can be seen (see images below), but the text is quite malformed. Using the `dark` theme the text seems to have a wrong color coding.

For both printed pages the styled pages are malformed, they mainly show the menu and not the content itself.

| `dark` theme | `light` theme |
| -- | -- |
| <img width="245" alt="Bildschirm­foto 2022-12-14 um 15 09 40" src="https://user-images.githubusercontent.com/8232196/207618296-b43853c7-586a-4ff2-aa22-aed65bf6b440.png"> | <img width="242" alt="Bildschirm­foto 2022-12-14 um 15 11 25" src="https://user-images.githubusercontent.com/8232196/207618402-63e446bb-cf4c-4d0a-8f4c-bb377f917d3e.png"> |

Source: https://demo.backstage.io/docs/default/component/backstage/features/software-catalog/

### 👟 Reproduction steps

1. Go to https://demo.backstage.io/docs/default/component/backstage/features/software-catalog/
2. Select "Print page" in the browser menu (or press `Command + P`)

### 📃 Provide the context for the Bug.

Some of our users would like to print backstage pages, especially the techdocs pages. We could provide a special mkdocs plugin to make the print work, but it would be nicer if the printing would work in general via the browser.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ericis** [comment]
Aw... I was really hoping this was not a bug. We can only print the first page, even when the content scrolls for miles below the view-port, and have similar styling problems as described in this issue.

**Comment by freben** [comment]
Gave this a techdocs label since that presumably is the majority use case.

Yeah printing isn't really something that we've deliberately targeted. There's probably a bit of media query CSS that's needed to make this work properly; something tells me that we can get 90% of the way by excluding things such as side bars and parts of the site layout structure in print mode.

We'd really appreciate help getting this into place, if somebody has the time to look into what it entails 🙏  For example, MUI itself [has the `displayPrint="none"`](https://v4.mui.com/system/display/#display-in-print) capability on a lot of components, which might be very useful here.

**Comment by ericis** [comment]
> Gave this a techdocs label since that presumably is the majority use case.
> 
> Yeah printing isn't really something that we've deliberately targeted. There's probably a bit of media query CSS that's needed to make this work properly; something tells me that we can get 90% of the way by excluding things such as side bars and parts of the site layout structure in print mode.
> 
> We'd really appreciate help getting this into place, if somebody has the time to look into what it entails 🙏 For example, MUI itself [has the `displayPrint="none"`](https://v4.mui.com/system/display/#display-in-print) capability some components, which might be very useful here.

TechDocs could be a primary use case for many. However, our primary use case at the moment is that we have an internal "news" plug-in for newsletters that we wanted to print directly to PDF for sharing in chat and e-mail. Since zero pages in Backstage support printing, we had to resort to using the Chrome extension "GoFullPage" in order to get a scrolled screenshot of the whole page (Firefox built-in screenshot support doesn't work because of the print issue either). However, this results in an image for the PDF and does not support any outlining, text, search or link capabilities that are expected from PDF readers.

**Comment by ericis** [comment]
Removing the top navigation and sidebar were very simple, but the Backstage components code base still does not support printing beyond the "above the fold" (first visible part of the page).

```css

body #root nav {
  display: none;
}

#root,
#root > div {
  margin: 0;
  padding: 0;
  width: 100%;
}

/* we auto-centered our newsletter content /*
#newsletter-content {
  margin: auto;
}
```

Again, this hides some elements on the page, but the page cannot be printed properly and workarounds like a scrolling screenshot are not acceptable for most printing use cases.

**Comment by afadil** [comment]
A workaround is to use [mkdocs-pdf-export-plugin](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/) with combined option set to true in order to generate a single PDF file

**Comment by ericis** [comment]
> A workaround is to use [mkdocs-pdf-export-plugin](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/) with combined option set to true in order to generate a single PDF file. If you use [backstage-plugin-techdocs-addon-mermaid](https://www.npmjs.com/package/backstage-plugin-techdocs-addon-mermaid), mermaid diagrams would not be rendered, though.
> 
> Another workaround is to write a techdocs addon to extract the shadowRoot document, apply some print styles, and open it in a new window to print.
> 

These are only workarounds for printing TechDocs sites through MkDocs, not for printing any page on Backstage. The example provided is TechDocs, but applies to all pages. Due to applied styles and themes, it may not be desirable to print a MkDocs version of the documentation.

My most recent printing need was for a custom plugin in Backstage.

**Comment by ericis** [comment]
There is some progress on this in the related screenshot issue:
https://github.com/backstage/backstage/issues/15754#issuecomment-1401910216
