### ISSUE TITLE
🚀 Feature: Add ability to pass props to SwaggerUI

### ISSUE THREAD

**Issue by sqsp-rwatkins** [backstage/backstage#15323]
### 🔖 Feature description

The ability to pass props to the [SwaggerUI](https://github.com/swagger-api/swagger-ui/tree/master/flavors/swagger-ui-react) component to modify its functionality.

### 🎤 Context

I was looking to modify some functionality, specifically, alter [supportedSubmitMethods](https://github.com/swagger-api/swagger-ui/tree/master/flavors/swagger-ui-react#supportedsubmitmethods-proptypesarrayofproptypesoneofget-put-post-delete-options-head-patch-trace).
Because no props are exposed to backstage developers, I had to make a copy of [OpenApiDefinition.tsx](https://github.com/backstage/backstage/blob/master/plugins/api-docs/src/components/OpenApiDefinitionWidget/OpenApiDefinition.tsx) and add the `supportedSubmitMethods` prop there.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Am I getting it right, that you made (or intended to make) a custom [`apiDocsConfigRef` implementation](https://github.com/backstage/backstage/blob/6ab9bfd301aca4b91be74e83aa9e0f79ffca8321/plugins/api-docs/src/config.ts#L22) so that you can return a tweaked openapi page implementation? And the one we had wasn't configurable enough so you had to completely reimplement from the ground up instead of just some light tweaking.

Alright, so let's figure out the best approach. Normally I'd say that copying it is fine, but also noting that there's a ton of [styling and stuff](https://github.com/backstage/backstage/blob/6ab9bfd301aca4b91be74e83aa9e0f79ffca8321/plugins/api-docs/src/components/OpenApiDefinitionWidget/OpenApiDefinition.tsx#L22) so it's a somewhat heavyweight customization.

So the next thing that's tempting is to add a dedicated `swaggerUiProps` prop on `OpenApiDefinitionWidget`. This leaks the internal implementation of that widget. We certainly don't want to make SwaggerUI types part of the public API surface because that affects the API stability of the entire package. We could make it be of type `unknown`/`any` to sidestep that, but that's arguably still very ugly and risks future silent breakage, and still leaks implementation details.

If we pick-and-choose, like adding just `supportedSubmitMethods`, then that's a more neutral choice but still as we evolve the package it might not be possible to retain that prop if it's not supported in the future. Not too shabby though, since the flag is kinda "semantic" in nature.

There's one more option that's a bit more work. We could create a `@backstage/plugin-api-docs-module-swagger-ui`, similarly to [the `protoc` one](https://github.com/backstage/backstage/tree/6ab9bfd301aca4b91be74e83aa9e0f79ffca8321/plugins/api-docs-module-protoc-gen-doc). Then that module is free to export an actual `SwaggerUi` component that IS mirroring swagger props, and which has the right styling in place. And at the same time, the default implementation in the plugin itself will be updated to use that component.

I'm voting for that last approach, I think.

**Comment by sqsp-rwatkins** [comment]
> Am I getting it right, that you made (or intended to make) a custom [`apiDocsConfigRef` implementation](https://github.com/backstage/backstage/blob/6ab9bfd301aca4b91be74e83aa9e0f79ffca8321/plugins/api-docs/src/config.ts#L22) so that you can return a tweaked openapi page implementation? And the one we had wasn't configurable enough so you had to completely reimplement from the ground up instead of just some light tweaking.
> 
> Alright, so let's figure out the best approach. Normally I'd say that copying it is fine, but also noting that there's a ton of [styling and stuff](https://github.com/backstage/backstage/blob/6ab9bfd301aca4b91be74e83aa9e0f79ffca8321/plugins/api-docs/src/components/OpenApiDefinitionWidget/OpenApiDefinition.tsx#L22) so it's a somewhat heavyweight customization.
> 
> So the next thing that's tempting is to add a dedicated `swaggerUiProps` prop on `OpenApiDefinitionWidget`. This leaks the internal implementation of that widget. We certainly don't want to make SwaggerUI types part of the public API surface because that affects the API stability of the entire package. We could make it be of type `unknown`/`any` to sidestep that, but that's arguably still very ugly and risks future silent breakage, and still leaks implementation details.
> 
> If we pick-and-choose, like adding just `supportedSubmitMethods`, then that's a more neutral choice but still as we evolve the package it might not be possible to retain that prop if it's not supported in the future. Not too shabby though, since the flag is kinda "semantic" in nature.
> 
> There's one more option that's a bit more work. We could create a `@backstage/plugin-api-docs-module-swagger-ui`, similarly to [the `protoc` one](https://github.com/backstage/backstage/tree/6ab9bfd301aca4b91be74e83aa9e0f79ffca8321/plugins/api-docs-module-protoc-gen-doc). Then that module is free to export an actual `SwaggerUi` component that IS mirroring swagger props, and which has the right styling in place. And at the same time, the default implementation in the plugin itself will be updated to use that component.
> 
> I'm voting for that last approach, I think.

Yeah, that's exactly what I was doing.

Cool, I'll go with the last approach proposed. I'll try to get around to it soon and I'll put up a PR when ready.
