### ISSUE TITLE
🚀 Feature: [TechDocs] Provide a default MkDocs.yaml configuration file

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#15413]
### 🔖 Feature description

A default `mkdocs.yaml` configuration file should be provided. This file would then be overridden by an existing `mkdocs.yaml` from the source if provided. 

This default config would look something like this:

```yaml
site_name: metadata.title (metadata.name if no title)
docs_dir: docs
plugins:
  - techdocs-core
```  

### 🎤 Context

We have a central app registry that we use to populate our Catalog, this means we have no Backstage metadata in our repos including the `mkdocs.yaml`. The way we've been able to get this to work is that in our CI/CD tool we add a default `mkdocs.yaml` file if it doesn't exist.

We would like to move to an event based model as per #14380 but not having a default `mkdocs.yaml` is blocking us.

This feature could also help adopters who are testing out Backstage as it would make getting TechDocs setup easier as there would be one less things to have to setup and configure.

### ✌️ Possible Implementation

There is already some adjustment being done to the `mkdocs.yaml` file before the generation starts here:

https://github.com/backstage/backstage/blob/02ebf52de303622ae970e1f68966d5521034ebb3/plugins/techdocs-node/src/stages/generate/techdocs.ts#L101

We could potentially inject the default `mkdocs.yaml` file in the same area.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Looking at the code more it seems we don't have easy access to the Entity (open to being wrong though). It looks like we might be able to get the repo name so that probably would be the best option. The idea of this feature is just to get a really bare default not something perfect which you can do by providing a config in the repo

**Comment by awanlin** [comment]
My next thought is how best to add this:

- Do we hard code it? This would be the fastest way to get the feature implemented
- Do we have this as part of the TechDocs config in the `app-config.yaml`? That could work but then we would need to handle all the possible MkDocs config options somehow
- Do we pull the file from a specific location that gets defined in the TechDocs config in the `app-config.yaml`? This feels better than the item just above.

**Comment by andrewthauer** [comment]
> Do we hard code it? This would be the fastest way to get the feature implemented

If this is invoked by the `techdocs-cli` then it could look for a `catalog-info.yaml` file and then fallback to the `basename` of the directory etc.

**Comment by kuangp** [comment]
hmm I swore I've seen a similar ER before ... found it! https://github.com/backstage/backstage/issues/8107 (really excited this is finally getting picked up 😁)

**Comment by andrewthauer** [comment]
Yeah me too. I've been meaning to do this for a long time ... 😂. I'm happy to donate some parts of code we have internally to help with this effort. I'd like to finally deprecate our custom techdocs-cli wrapper once and for all.

**Comment by andrewthauer** [comment]
Beyond this, the other major feature our custom wrapper supports is generating diagrams using plantuml but within a docker image. Funny thing, I actually started looking at what would be required to tack this onto the `techdocs-cli` the other day.

**Comment by awanlin** [comment]
@kuangp thanks for finding that for me, I really felt there had to be something for this already but my searches came up empty.

**Comment by awanlin** [comment]
@andrewthauer I'm happy to work with you on this one. I've just pushed an update to my PR, clearly had missed some things as it was failing a simple `yarn tsc`. 

Now we are moving away from using the CLI to generate TechDocs as we want this to happen based on code push events, see #14380. So that's where my focus has been with the PR. 

The approach I was taking was a sort of "good, better, best" like this:

- Good being the least config possible to be able to generate the site, this is what my PR is going for right now
- Better is using some location that has a pre-built more complex version of the `mkdoc.yml` that it would copy down and use. Maybe this is where your template suggestion comes in
- Best is the `mkdoc.yml` is in the repo already, tailored exactly as needed, this is how things work right now.

Now, we have, I think, 3 cases we want to cover:

1. Creating a config when generating TechDocs from Backstage itself
2. Creating a config when generating TechDocs from the TechDocs CLI
3. Creating a config when serving TechDocs locally

I've got my "good" option working for the above 3 but I could use your help on how we can get the "better" option going

**Comment by andrewthauer** [comment]
@awanlin - Sounds good. I've been away for a couple days but will put some thoughts down on how we can extend this further later today or tomorrow.

**Comment by awanlin** [comment]
No worries @andrewthauer, sounds good to me

**Comment by andrewthauer** [comment]
> Now we are moving away from using the CLI to generate TechDocs as we want this to happen based on code push events, see https://github.com/backstage/backstage/issues/14380. So that's where my focus has been with the PR.

Seems like a nice alternative approach, but I still think the CLI is necessary as an option for the foreseeable future. 2 reasons I can think of are a) the Backstage instance may not be public facing and have the ability to receive events directly, b) The infrastructure running Backstage may not be able to run docker in docker or want to install all the techdocs related dependencies (e.g. python, java, plantuml, etc.).

> The approach I was taking was a sort of "good, better, best" like this:

Agree. I had a look through your PR and it feels like a good starter foundation for supporting auto mkdocs. However, there is one area I see slightly problematic and likely easily fixable.

The current code will create the `mkdocs.yml` if it didn't exist, but not remove it if it did not exist to start. This could work nice for bootstrapping the usage of techdocs, but it can also pose issues if an organization wants to centralize and maintain some of the defaults of the mkdocs file (e.g. custom plugins, etc.). Since the dev might commit the newly created `mkdocs.yml` file if they were previewing locally, it means the file is already there. We had this issue initially and it made it difficult to extend more centrally. So we added some code that will cleanup the file for us. For example something like this:

```ts
process.on('exit', async () => {
  if (useTempMkdocsConfig) {
    console.log('Cleaning up temporary mkdocs.yml file ...');
    fs.rmSync(mkdocsPath, {});
  }
});
```

In this case the `process.exit` is based on `techdocs-cli service` exiting. So, I'm not sure this translates to the general code in `techdocs-node`. However, I think it's pretty vital that it's cleaned up to ensure the above scenario doesn't become a maintenance issue and allow for central management of extra config.

> Now, we have, I think, 3 cases we want to cover

I personally think we can solve all 3 cases in a single solution. We choose to generate the entire `mkdocs.yml` from a handlbars template that is packaged in a wrapper for techdocs CLI (as partially seen in #8107). The `mkdocs.yml` file is never committed. This solves the central management concern, but also introduces other issues such as customization. For example we leverage https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin to avoid needing the `nav` config. I see 2 main approaches that can extend your baseline work:

1. Add additional code to `techdocs-node` to support a config that points to a handbars template file that can be used to generate the entire mkdocs file from scratch over and over (if it doesn't exist). This code could then extract some metadata from the entity, etc. and pass that as context to the template engine.

2. Add some sort of mkdocs config merging or transformation hook. This would allow the config to be modified or extended on top of the base logic within `techdocs-node`. This seems like it might need to be a code based, which could make it harder to re-distrubute and say re-use in CI. However, perhaps it could just be a yaml merging feature similar to `docker-compose.override.yml` or `app-config.local.yaml`.

**Comment by andrewthauer** [comment]
Option 2 seems like a better path forward imo. It appears there are a [few helper functions](https://github.com/backstage/backstage/blob/master/plugins/techdocs-node/src/stages/generate/techdocs.ts#L102-L122) related to building up the mkdocs config. Ideally we can combine these into a single entry point that acts like a pipeline for building the mkdocs configuration, and allow for customizations via a transformer function.

Here is some really rough pseudo code of what I'm thinking ...

```ts
type MkDocsConfigTransformerContext = {
  entity? Entity,
  ...
};

function createDefaultMkDocsConfigTransformer(options: { /* invariants */ }) {
  return (config: MkDocsConfig, context: MkDocsConfigTransformerContext) => {
     // Do default patching, etc.
  }
}

type MkDocsConfig = any; // Make this strongly typed

type MkDocsConfigBuilderOptions = {   
   entity? Entity,
   logger: Logger,
   context: MkDocsConfigBuilderContext,
   transform: (config: MkDocsConfig) => MkDocsConfig
}

function buildMkDocsConfig(inputDir: string, options: MkDocsConfigBuilderOptions) {  
  const yamlPath = getMkDocsConfigYamlPath(inputDir);

  let mkDocsConfig: MkDocsConfig = {};  
  if (fs.fileExists(yamlPath) {
     mkDocsConfig = readMkDocsConfig(yamlPath);
  }
  
  return options.transform(mkDocsConfig, options.context);
}
```

**Comment by awanlin** [comment]
@andrewthauer first week back after the holidays ended up being a lot busier than I expected. Finally got time to pick this up again. 

Something I'd like to clear up: I don't think the CLI is going away. At my Org we will still be using it for a few edge cases where some of our repos aren't in a structure that can easily be generated into TechDocs. Sorry for any confusion.

**Comment by andrewthauer** [comment]
@awanlin - Thanks for clarifying on the CLI. As for your #15417, I think it's a great foundational start and would be happy to have it move forward as a stepping stone. As per my comments, we won't be able to use it until we can customize the mkdocs config with custom plugins etc. But, I'm happy to help on subsequent PRs to add the required changes to support this. When you get a chance, let me know your thoughts on my rough solution/proposal.
