### ISSUE TITLE
🚀 Feature: `catalogProcessingExtensionPoint` supports `addEntityPolicy`

### ISSUE THREAD

**Issue by alecjacobs5401** [backstage/backstage#15455]
### 🔖 Feature description

Within the [New Backend System](https://backstage.io/docs/plugins/new-backend-system), the new concept of [Extension Points](https://backstage.io/docs/plugins/new-backend-system#extension-points) are introduced and called out to be used when defining plugin [Modules](https://backstage.io/docs/plugins/new-backend-system#modules)

As of the latest release (currently v1.9.1), the `catalogProcessingExtensionPoint` that allows modules to hook into the catalog processing setup [only allows for adding new Processors and Entity Providers](https://github.com/backstage/backstage/blob/v1.9.1/plugins/catalog-node/src/extensions.ts#L23-L30).

The [CatalogBuilder itself supports addition of Entity Policies](https://github.com/backstage/backstage/blob/v1.9.1/plugins/catalog-backend/src/service/CatalogBuilder.ts#L183-L199) and as a plugin module developer, it would be nice to be able to add Entity Policies from backend catalog module plugins

### 🎤 Context

Entity Policies are beneficial and a [key concept of the Entity Processing pipeline](https://backstage.io/docs/features/software-catalog/life-of-an-entity#key-concepts:~:text=Policies%2C%20that%20establish%20baseline%20rules%20about%20the%20shape%20of%20entities%2C) within the life of an entity.

Adding Entity policies is the only [key concept in the life of an entity](https://backstage.io/docs/features/software-catalog/life-of-an-entity#key-concepts) that is missing from the current [catalogProcessingExtensionPoint](https://github.com/backstage/backstage/blob/v1.9.1/plugins/catalog-node/src/extensions.ts#L23-L30).

As such, it feels prudent to include it for module development.

### ✌️ Possible Implementation

Add `addEntityPolicy` to the `CatalogProcessingExtensionPoint`
```diff
# plugins/catalog-node/src/extensions.ts

export interface CatalogProcessingExtensionPoint {
  addProcessor(
    ...processors: Array<CatalogProcessor | Array<CatalogProcessor>>
  ): void;
  addEntityProvider(
    ...providers: Array<EntityProvider | Array<EntityProvider>>
  ): void;
+ addEntityPolicy(
+   ...policies: Array<EntityPolicy | Array<EntityPolicy>>
+ ): void;
}
```

Then add the addition of added policies from the extension point during backend plugin initialization
```diff
# plugins/catalog-backend/src/service/CatalogPlugin.ts

class CatalogExtensionPointImpl implements CatalogProcessingExtensionPoint {
  #processors = new Array<CatalogProcessor>();
  #entityProviders = new Array<EntityProvider>();
+ #entityPolicies = new Array<EntityPolicy>();

  addProcessor(
    ...processors: Array<CatalogProcessor | Array<CatalogProcessor>>
  ): void {
    this.#processors.push(...processors.flat());
  }

  addEntityProvider(
    ...providers: Array<EntityProvider | Array<EntityProvider>>
  ): void {
    this.#entityProviders.push(...providers.flat());
  }

+ addEntityPolicy(
+   ...policies: Array<EntityPolicy | Array<EntityPolicy>>
+ ): void {
+   this.#entityPolicies.push(...policies.flat());
+ }

  get processors() {
    return this.#processors;
  }

  get entityProviders() {
    return this.#entityProviders;
  }

+ get entityPolicies() {
+   return this.#entityPolicies;
+ }
}

...

# in `export const catalogPlugin = createBackendPlugin({`

 const winstonLogger = loggerToWinstonLogger(logger);
 const builder = await CatalogBuilder.create({
   config,
   reader,
   permissions,
   database,
   logger: winstonLogger,
 });
 builder.addProcessor(...processingExtensions.processors);
 builder.addEntityProvider(...processingExtensions.entityProviders);
+builder.addEntityPolicy(...processingExtensions.entityPolicies);
 const { processingEngine, router } = await builder.build();

 await processingEngine.start();
 lifecycle.addShutdownHook({
   fn: async () => {
     await processingEngine.stop();
   },
 });
 httpRouter.use(router);
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Yep makes sense! 👍 

Could be that we want to split this out into a separate extension point though. Potentially something like a `catalogModelExtensionPoint`, what do you think?

CC @backstage/maintainers, @backstage/catalog-core

**Comment by freben** [comment]
> `catalogModelExtensionPoint`

As in the entity model? Hm. Since the entity model mainly is driven by processors today, that might be confusing.

I think the mechanism of policies might be one of the first to be revised (or removed / folded into processors) when the catalog processing model evolves in the future. They are a bit of an odd one out at this point and should be looked at some time down the line. So from THAT point of view I can see a temptation to have it as a separate extension point, one which easily can be changed / deprecated in isolation. But apart from that... As long as we don't yet have the time to spend on overhauling the model, it's probably fine to keep with the others in the existing extension point I'd say.

**Comment by alecjacobs5401** [comment]
I'm happy to help push forward either way if y'all would like. Also happy to let y'all discuss best path forward.

Let me know how I can help!

**Comment by knksmith57** [comment]
We are interested in keeping this alive 😄

**Comment by Rugvip** [comment]
We took an initial stab a while back at sorting the different customization points that the catalog builder exposes and how it would be mapped to the new system. Let us know what you think!

## Options
- set processing interval callback
- set the allowed location types

## Extension Points
### ProcessingExtensionPoint
  - set entity data parser, which is available to all processors
  - install entity providers
  - install entity processors
  - replace all existing entity processors, except for BuiltinKindsEntityProcessor and PlaceholderProcessor (maybe?)
  - get the default set of processors so that they can be used when replacing
  - set a custom placeholder resolver

###  CatalogModelExtensionPoint
  - add additional entity policies
  - replace all entity policies with a new set
  - override field format validators, e.g. isValidTag

### LocationAnalysisExtensionPoint
  - set a custom location analyzer
  - add location analyzers

### CatalogPermissionsExtensionPoint *- maybe this one should be an option instead?*
  - install additional permission rules

## Config
- set processing interval in seconds
- can decide whether to start processing engine or not (based on config)
