### ISSUE TITLE
🐛 Bug Report: Unable to Permanently Unregister Entities 

### ISSUE THREAD

**Issue by Trevor-Bond** [backstage/backstage#15467]
### 📜 Description

In our company's fork of Backstage, when we attempt to unregister an entity, we are able to click "Delete Entity" and the entity seems to be deleted, but it returns within a couple of seconds. We spun up a fresh instance of Backstage using "npx @backstage/create-app", and we experience the same issue. Screenshots of the steps we took to delete an entity in the fresh instance are below:

We are deleting the example-grpc-api entity
![Screen Shot 2022-12-29 at 2 59 13 PM](https://user-images.githubusercontent.com/38539480/210010619-1d989ddf-60c8-4df0-8166-f29b1cf3ff8e.png)

![Screen Shot 2022-12-29 at 2 59 23 PM](https://user-images.githubusercontent.com/38539480/210010650-9d7f9564-7fa2-464b-8839-bd01ffafc5ec.png)

The entity returns a couple of seconds later
![Screen Shot 2022-12-29 at 2 59 34 PM](https://user-images.githubusercontent.com/38539480/210010675-bb93811c-aa2d-427f-af96-af2f85d24456.png)

Here is a video of the issue
[screen-capture.webm](https://user-images.githubusercontent.com/38539480/210011956-d8f8d3ed-523b-4607-b42d-56e5bb7cb28e.webm)

### 👍 Expected behavior

When we unregister an entity, it should be deleted. 

### 👎 Actual Behavior with Screenshots

The entity is not deleted and the entity returns within a couple of seconds. 

### 👟 Reproduction steps

1. Go to an entity in the catalog
2. Select "Unregister entity" at the top right of the page
3. Select "Delete Entity"
4. Confirm that the entity is not visible in the catalog
5. Confirm that the entity returns within a couple of seconds

### 📃 Provide the context for the Bug.

Backstage is heavily used at our company, and users not being able to delete entities is leading to confusion about what is and is not current for a team. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Trevor-Bond** [comment]
Here is a video of the above issue:
[screen-capture.webm](https://user-images.githubusercontent.com/38539480/210011866-c77e59a8-f5c5-488f-8f83-c5cf3a876e91.webm)

**Comment by efenner-cambia** [comment]
Was the entity manually registered, or registered by an entity provider?

**Comment by freben** [comment]
The main thing to note here is that the unregister dialog claims it's not from a registered location. Thus it doesn't offer the proper unregistration - which is what you'd normally want - but instead a raw delete. I think that was in error; there probably IS a registered location, and the catalog "heals" by noting that there's indeed some authoritative data (the Location entity that corresponds to the registration) and re-reads it and puts it in place.

I'm not at work to try to reproduce this until next week, but 'til then: How was this file registered? What was the URL you gave? Was it perhaps a file instead of a URL, or was it a URL with globs (asterisks) in it or so?

**Comment by freben** [comment]
I'll also offer as a side note that we acknowledge that these "raw" deletions often are problematic (at least for non-orphaned entities), and we're considering disabling that functionality entirely since it often leads to more issues than solutions.

**Comment by Trevor-Bond** [comment]
@freben We are having the issue in all the scenarios you mentioned. In the fresh instance of Backstage that we created using @backstage/create-app, the entities are being created manually from a local .yaml file. In our company's fork of Backstage, we use both Github and Gitlab entity providers. Both use URLs with globs for registration, and with are having the same issue with both providers.

**Comment by freben** [comment]
Alright.

For local files, those were probably originally coming from app-config locations I presume. Those aren't really deletable so to speak - we should ideally not even have offered the option in the GUI, especially not to regular users. The only proper way of getting rid of those would be to remove those entries from app-config, because they are really "statically" put there by the catalog service itself. The fix for this, is to adjust the frontend code to completely disallow this deletion.

For globs, it'll take a bit more digging. What are the specific providers you use, if I may ask? The class names and the parameters they are initialized with in your backend would help, just remember to redact any sensitive/private parts before posting.

**Comment by Trevor-Bond** [comment]
@freben We are using the GitlabDiscoveryProcesser and GitHubEntityProvider classes, and we have the following in our app-config.yaml:

![Screen Shot 2022-12-30 at 9 57 39 AM](https://user-images.githubusercontent.com/38539480/210089154-f59bbace-aa98-47a9-a892-d939fc90515a.png)

Let me know if you need anything further.

**Comment by Rugvip** [comment]
@Trevor-Bond Could you double check the location of your `example-grpc-api` to make sure it's not actually an example component in one of your own projects in GitLab?

**Comment by Trevor-Bond** [comment]
@Rugvip example-grpc-api is an entity that only exists in the fresh instance of Backstage that we created to demonstrate the bug we are seeing. We are experiencing the same issue with all entities in our company's fork of Backstage.

**Comment by Rugvip** [comment]
Played around with this a bit in a new app and couldn't get the example entity to stick. Tried some combinations of adding/removing it from config and registering `https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/examples/entities.yaml`.

Could you check what the location of your stuck entity is? You can see it in the entity inspector view:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/4984472/210752000-683a84c3-e178-4a6b-b613-b7436c65a0e9.png">

👇 

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/4984472/210753399-8f38b6eb-6849-44f9-a5f0-41b2b75510bb.png">

**Comment by Trevor-Bond** [comment]
@Rugvip In our fork of Backstage, Github entities have the format of 'https://github.com/group-name/repo-name/tree/master/catalog-info.yaml. For Gitlab entities, it is 'https://gitlab.com/organization-name/group-1/group-2/repo-name/-/blob/master/catalog-info.yaml. We have issue with deleting any entity, no matter if it is Github or Gitlab.

**Comment by Rugvip** [comment]
@Trevor-Bond when you are using a discovery you can't permanently delete entities from the catalog if they still exist in the target repositories. You will need to delete the entity definitions from the source code repositories instead, or otherwise exclude them from the discovery.

**Comment by therealak12** [comment]
Same here. We've manually registered a component but we can't unregister it from the backstage instance (it returns after a while).

**Comment by therealak12** [comment]
So it looks like the `Location` resource makes the backstage fetch updates from the git repo and recreate the components. I've deleted the `Location` resources (choose Location in Kind dropdown and delete all) and then the all the related resources such as components and APIs will be deleted automatically (or if not, won't be recreated if you delete them).

**Comment by ValberJunior** [comment]
It seems to me that this is expected behavior, in my case to get around this problem I am going to the project repository and deleting the "catalog-info.yaml" , so next time the backstage informs that there was no interaction with the component and the provider, and so I can delete the component from the catalog.
