### ISSUE TITLE
🐛 Bug Report: microsite adopters form doesn't scroll

### ISSUE THREAD

**Issue by mattbhenley** [backstage/backstage#15466]
### 📜 Description

On the homepage, when selecting "New Adopters" the form is opened but it cuts off and doesn't scroll correctly, blocking the top of the form. 

![bad](https://user-images.githubusercontent.com/29934898/210010437-79e8f4a4-d9f0-4964-8477-e40f434f36a5.png)

### 👍 Expected behavior

scroll correctly OR be able to see the full form 

### 👎 Actual Behavior with Screenshots

![bad](https://user-images.githubusercontent.com/29934898/210010437-79e8f4a4-d9f0-4964-8477-e40f434f36a5.png)

### 👟 Reproduction steps

1. go to https://backstage.io/
2. click New Adopters on the right side 
3. Form opens 

### 📃 Provide the context for the Bug.

I was trying to fill out the form but was unable to the bug 

### 🖥️ Your Environment

Windows 10. Google Chrome browser. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by shardulsrivastava** [comment]
@Rugvip I can work on this issue.

**Comment by jhaals** [comment]
Thanks ❤️

**Comment by pagman77** [comment]
@shardulsrivastava Are you still working on this? I didn't see a PR yet and would love to start contributing. I'm happy to take over if you haven't gotten to it yet!

**Comment by shardulsrivastava** [comment]
@pagman77 I looked into this and tried a couple of workarounds, and it looks like this now:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/9951135/212978779-3219c93f-0245-4be2-80ea-53bda748025e.png">

The changes I added are these :

```bash
.Sidebar__Container {
  top: 50%;
  top: 56.5%;
  right: 0;
  position: fixed;
  overflow-y: scroll;
  color: rgb(0, 0, 0);
  transition: transform 250ms ease-in-out, height 250ms ease-in-out;
  display: flex;

#Sidebar__HubSpotContainer {
  width: 500px;
  height: 810px;
  position: sticky;
  background-color: white;
  border-radius: 8px 0 0 8px;
  padding: 16px;
  padding-bottom: 0px;
  padding-top: 15px;
  z-index: 10001;
  min-height: 260px;
}
```

<img width="494" alt="image" src="https://user-images.githubusercontent.com/9951135/212978944-c70cd97b-d3cd-4c33-876a-989453746faa.png">

After testing extensively, I found that when there are errors for all the fields, there is another problem that it overflows at the bottom.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/9951135/212979557-73ef8fe6-6eaa-40f4-9f38-179fc6db7c18.png">

Would appreciate any pointers to fix this

**Comment by pagman77** [comment]
@shardulsrivastava I started poking around with it and I'm pretty sure the problem lies in the fact that the form is being rendered and injected into the DOM. So you have a container inside of a container and THEN the form inside of that. 

(@mattbhenley  not sure if you want me to dig deeper into this and submit another issue entirely. The hubspot form is being directly injected into the DOM:

```js

import React from 'react';

export class HubSpotForm extends React.Component {
  render() {
    return (
      <>
        <script src="https://js.hsforms.net/forms/v2.js" />
        <div
          className="Sidebar__Container"
          dangerouslySetInnerHTML={{
            __html: `
          <button class="Sidebar__Button" onclick="toggleFormVisibility()">New Adopters</button>
          <div id="Sidebar__HubSpotContainer"></div>
        `,
          }}
        />
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
          if (typeof window !== undefined) {
            window.hbspt.forms.create({
              portalId: '21894833',
              formId: '9a5aa2af-87f3-4a44-819f-88ee243bb61e',
              target: '#Sidebar__HubSpotContainer',
              pageId: '79735607665',
            })
          }

          function toggleFormVisibility() {
            var form = document.querySelector('.Sidebar__Container');
            form.classList.toggle('Sidebar__Container--open');
          }
          `,
          }}
        ></script>
      </>
    );
  }
}


```
There is a 3rd party npm package that just allows you to use a React Component, but I also don't mind building one from scratch if you think it might be necessary. I would imagine this was created before hooks became standard practice)

Heres the fix I have just from a couple of lines:

```css
#Sidebar__HubSpotContainer {
  width: 500px;
  background-color: white;
  border-radius: 8px 0 0 8px;
  z-index: 10001;
  min-height: 260px;
  height: 500px;
}

#Sidebar__HubSpotContainer form{
 overflow-y: auto;
 height: 100%;
 padding: 25px 25px 0px 25px;
}
```

<img width="1440" alt="Screen Shot 2023-01-17 at 1 24 24 PM" src="https://user-images.githubusercontent.com/91204918/212980721-25180b44-b658-476a-9a93-a45ad29aaf8c.png">
<img width="1440" alt="Screen Shot 2023-01-17 at 1 24 28 PM" src="https://user-images.githubusercontent.com/91204918/212980751-ae426062-99e0-4081-a2d1-3538497a63f1.png">

It seems to be fine with errors too:


<img width="1440" alt="Screen Shot 2023-01-17 at 1 27 28 PM" src="https://user-images.githubusercontent.com/91204918/212981264-861a09ee-a9ae-499b-9c19-e9b3aea6adc8.png">


I want to keep messing around with it to optimize it for mobile. I think a few media queries for smaller screen sizes wouldn't hurt. The form and wesbite is completely unusable if you open it on a smartphone.
