### ISSUE TITLE
🚀 Feature: Make PostgreSQL search accent-insensitive

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#15517]
### 🔖 Feature description

Search should be able to match keywords regardless of accented characters.

### 🎤 Context

We have accented characters in the catalog. Entities that include accented characters are hard to find using search.

For example, an entity titled "Ömer" cannot be found when "Omer" is queried (or vice versa).

### ✌️ Possible Implementation

We can use the [unaccent](https://www.postgresql.org/docs/current/unaccent.html) extension while generating the `body` column in the `documents` table, and also while performing the query.

<pre>
table.specificType(
  'body',
  'tsvector NOT NULL GENERATED ALWAYS AS (' +
    "setweight(to_tsvector('english', <b>unaccent</b>(document->>'title')), 'A') || " +
    "setweight(to_tsvector('english', <b>unaccent</b>(document->>'text')), 'B') || " +
    "setweight(to_tsvector('english', <b>unaccent</b>(document - 'location' - 'title' - 'text')), 'C')" +
    ') STORED',
);
</pre>

<pre>tx.raw("documents, to_tsquery('english', <b>unaccent</b>(?)) query", pgTerm)</pre>

The unaccent extension is not installed by default, so we should execute `CREATE EXTENSION unaccent` to install it first. For PostgreSQL 12 and below, this command requires the user to be a superuser on the database, which might be a problem. This requirement no longer exists since PostgreSQL 13:

> This module is considered “trusted”, that is, it can be installed by non-superusers who have CREATE privilege on the current database.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by omerfarukdogan** [comment]
@iamEAP Would you have any comments on this? If this is not possible, we will consider using Elastic search engine.

**Comment by iamEAP** [comment]
Hey!  Thanks for the tag @omerfarukdogan.

When one uses the `unaccent` extension (both at query/index time), does that actually affect the way the data is stored?  (e.g. if you searched for user `Ömer`, would it return the user entity, but with the title of the document showing as `Omer`?

Separately, I'm thinking we'd likely want to make this behavior configurable, rather than the default/only way (I can imagine locales/cases where users would not want this behavior).  If you can imagine a way to implement this where users could enable it via some kind of configuration (whether in config or code), I think we'd be open to it!

But otherwise, it might be easier for you to achieve this using the ES search engine + text analyzers + template / mappings.

**Comment by omerfarukdogan** [comment]
Hello @iamEAP,

The data itself (stored in the `document` column) doesn't have to be affected by this. We can only change the way text search vectors (stored in the `body` column) are generated.

I am not familiar with Knex migrations. Is it possible to dynamically generate or apply specific migrations based on a parameter? We could ask the user during the project initialization (`npx @backstage/create-app` command) and modify how the `body` column is generated. Or is it possible to apply/rollback migrations conditionally during app startup so we can check a parameter in app-config?

**Comment by omerfarukdogan** [comment]
@iamEAP Unfortunately I don't know.
