### ISSUE TITLE
🚀 Feature: Upgrade all AWS code usage to use aws-sdk-javascript v3

### ISSUE THREAD

**Issue by testn** [backstage/backstage#15516]
### 🔖 Feature description

Upgrade all AWS code usage to use aws-sdk-javascript v3 instead of mixing v2 and v3 together

### 🎤 Context

Mixing v2 and v3 together make it quite impossible to test properly

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jamieklassen** [comment]
Seems related to #12066 (stale) which itself references prior art #4415 and parallel issue #12844

**Comment by testn** [comment]
> Seems related to #12066 (stale) which itself references prior art #4415 and parallel issue #12844

But all have been closed. 🥲

**Comment by testn** [comment]
try ```yarn why @aws-sdk/types```

**Comment by clareliguori** [comment]
I don't disagree that everything should be bumped up to v3 for consistency and for the ability to use the new AWS auth utilities from https://github.com/backstage/backstage/pull/14125.  It should be feasible now that those issues have been resolved.

@testn can you help me understand why having mixed v2 and v3 SDKs across packages causes testing issues?  Even though `@aws-sdk/types` is now brought in with v3, v3 has a different package structure from v2 so I'm missing why that causes issues.  The import paths are not the same (`@aws-sdk` vs `aws-sdk`), so my assumption is that as long as we don't try to mix them in the same file, the right SDK will be imported and any testing using mocking should not be impacted because it would mock the right SDK version depending on whether `@aws-sdk` vs `aws-sdk` is mocked.
```
// v3
import { ListObjectsV2CommandOutput } from "@aws-sdk/client-s3";
// v2
import { ListObjectsV2Output } from 'aws-sdk/clients/s3';
```
