### ISSUE TITLE
🚀 Feature: Lighthouse Scheduler

### ISSUE THREAD

**Issue by dpfaffenbauer** [backstage/backstage#15703]
### 🔖 Feature description

The Lighthouse Plugin allows to manually run audits, but we would like to do that automatically every day or so. We'd implement a lighthouse-backend Plugin to automatically run these audits scheduled based on a configuration. Since I am new to backstage, I would need some guidance on following:

 - How do I create a Scheduler? Backstage has a scheduler build-in, but no docs on how I can use it.
 - How do I query the catalog in backend?

### 🎤 Context

Having Lighthouse Audits on a regular basis gives us quite a good understanding on what changes improve or worsen the performance.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @dpfaffenbauer, the `backend-tasks` package is what get used for scheduling things throughout the Backstage codebase, the README is pretty good starting point: https://github.com/backstage/backstage/tree/master/packages/backend-tasks

The `CatalogClient` is what you would use for querying the Catalog from the backend. Sadly the GitHub code search isn't working or I would share some examples.

**Comment by dpfaffenbauer** [comment]
@freben I got it working so far. Should I create a `lighthouse-backend` and `lighthouse-common` module? `common` to share the Lighthouse API and re-use it for backend and frontend. The frequency part is configurable via config. It uses the `backend-tasks` to schedule the audits, as well as for every single website too. We don't wanna "spam" the audit-service with 50 websites at once, so we have a timeout between the websites too.

**Comment by freben** [comment]
Yep that sounds great.

The backend wouldn't really even have a router would it? Well it could, just to hold some status endpoint or whatnot, but it's really stateless and doesn't have anything to keep track of between refresh rounds etc right?

As a future improvement it COULD have a db table that holds a last_refreshed_at timestamp for each remote thing I guess, if we wanted to. Then the scheduled task would be to, for example every 30 seconds or however often we want to call the remote APIs, list auditable items from the service and check the db for whether there's a single item that hasn't yet been run or at least hasn't been run in the last N time units (as per config). This would make items kinda form a queue that workers pick a single thing off of at a time, much like the scaffolder and catalog do. But again, this could be a future endeavour, since it probably won't be all that necessary to be that thorough as long as the number of auditable things is pretty small so we easily can just trigger them all in sequence every now and then.

**Comment by dpfaffenbauer** [comment]
I got it working with a plugin, I will prepare a PR the next days. With a bit of a hacky approach, the scheduler can already do that.
