### ISSUE TITLE
🐛 Bug Report: not getting option to check template in backstage 1.10.1

### ISSUE THREAD

**Issue by prasoon-pxc** [backstage/backstage#15939]
### 📜 Description

I have updated backstage from `1.7.1` to `1.10.1` , after updating the backstage, I am not able to find out the option to check templates in backstage , I am getting `null` option in place of `template` option .

PF
![image](https://user-images.githubusercontent.com/106815018/214485040-06d75523-7bbd-4891-8ddb-c32ebe3c5952.png)

### 👍 Expected behavior

template option should be visible 

### 👎 Actual Behavior with Screenshots

PF 
![image](https://user-images.githubusercontent.com/106815018/214485052-cb8b3eb4-3e95-411e-88c9-566fbae97f32.png)

### 👟 Reproduction steps

update backstage from `1.7.1` to `1.10.1`

### 🖥️ Your Environment

- output of `yarn backstage-cli info`

```
yarn run v1.22.19
$ /home/il58d0/smb/backstage-conf-repo/backstage-conf-repo-original/node_modules/.bin/backstage-cli info
OS:   Linux 5.14.0-1055-oem - linux/x64
node: v16.14.0
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.1

Dependencies:
  @backstage/app-defaults                          1.1.0
  @backstage/backend-app-api                       0.3.1
  @backstage/backend-common                        0.17.0, 0.18.1
  @backstage/backend-plugin-api                    0.3.1
  @backstage/backend-tasks                         0.4.2
  @backstage/backend-test-utils                    0.1.33
  @backstage/catalog-client                        1.3.0
  @backstage/catalog-model                         1.1.5
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.1
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.4.0
  @backstage/core-components                       0.12.3
  @backstage/core-plugin-api                       1.3.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.9
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.41
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.10
  @backstage/plugin-bazaar-backend                 0.2.4
  @backstage/plugin-bazaar                         0.2.3
  @backstage/plugin-catalog-backend-module-github  0.2.4
  @backstage/plugin-catalog-backend                1.7.1
  @backstage/plugin-catalog-common                 1.0.10
  @backstage/plugin-catalog-graph                  0.2.26
  @backstage/plugin-catalog-import                 0.9.4
  @backstage/plugin-catalog-node                   1.3.2
  @backstage/plugin-catalog-react                  1.2.4
  @backstage/plugin-catalog                        1.7.2
  @backstage/plugin-events-node                    0.2.2
  @backstage/plugin-github-actions                 0.5.14
  @backstage/plugin-home                           0.4.30
  @backstage/plugin-org                            0.6.4
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.4
  @backstage/plugin-permission-react               0.4.9
  @backstage/plugin-playlist-backend               0.2.4
  @backstage/plugin-playlist-common                0.1.4
  @backstage/plugin-playlist                       0.1.5
  @backstage/plugin-proxy-backend                  0.2.35
  @backstage/plugin-scaffolder-backend             1.10.1
  @backstage/plugin-scaffolder-common              1.2.4
  @backstage/plugin-scaffolder-react               1.0.1
  @backstage/plugin-scaffolder                     1.10.1
  @backstage/plugin-search-backend-module-pg       0.5.2
  @backstage/plugin-search-backend-node            1.1.2
  @backstage/plugin-search-backend                 1.2.2
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-shortcuts                      0.3.6
  @backstage/plugin-sonarqube-backend              0.1.6
  @backstage/plugin-sonarqube-react                0.1.1
  @backstage/plugin-sonarqube                      0.6.2
  @backstage/plugin-stack-overflow                 0.1.10
  @backstage/plugin-tech-radar                     0.6.0
  @backstage/plugin-techdocs-backend               1.5.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.9
  @backstage/plugin-techdocs-node                  1.4.5
  @backstage/plugin-techdocs-react                 1.1.2
  @backstage/plugin-techdocs                       1.4.3
  @backstage/plugin-todo-backend                   0.1.38
  @backstage/plugin-todo                           0.2.16
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.4
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
Done in 0.80s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by namco1992** [comment]
Hi, we happen to encounter the same problem, and I would like to supplement some of our findings here.

Firstly, I believe it's related to the change introduced by this PR: https://github.com/backstage/backstage/pull/14230. This PR updated the way the entity-facets endpoint works, which is the endpoint used to fetch the available entity kinds in the dropdown.

In that PR, it switched to use `search` table and added a column `original_value`. The new `original_value` column is also used as the return values for the entity facets. So if we try to reproduce the query to fetch entity kinds, we can see there are indeed some records that are missing the `original_value`:
```
backstage=> select search.original_value, count(search.entity_id) from search join final_entities on search.entity_id=final_entities.entity_id where search.key='kind' group by search.original_value;
 original_value | count
----------------+-------
                |  4030
 Location       |  2612
 Resource       |     1
 System         |   179
 API            |     6
 Component      |    92
 Group          |   125
 User           |  2143
(8 rows)
```
So that's the reason we see `null` in the dropdowns.

But why does the `original_value` of some entities remain empty? Afterall, there is a DB migration handles the column value population:
https://github.com/backstage/backstage/blob/ad94577f29e9f8ba3084e612348e7efff1d498ba/plugins/catalog-backend/migrations/20221109192547_search_add_original_value_column.js#L37-L41

I think the issue is that the `final_entities.hash` is updated after the `refresh_state` table updates. The `final_entities.hash` is used to determine if the stitcher should proceed:
https://github.com/backstage/backstage/blob/ad94577f29e9f8ba3084e612348e7efff1d498ba/plugins/catalog-backend/src/stitching/Stitcher.ts#L186-L190

When the `refresh_state` is updated, the processing has begun, and you will see inconsistent behaviours:
- If an entity is processed after `update final_entities set hash='';` is done, then the `search` records will be updated without issue;
- If an entity is processed before  `update final_entities set hash='';` is done, since the entity itself didn't change, therefore the hash won't change, and nothing will be updated.

I tried to reverse the sequence (update `final_entities` first, and then `refresh_state`) and run it on my env, and all records are updated successfully.

**Comment by freben** [comment]
@namco1992 Wow thanks for that very detailed report and solution. Also made #15986 to mimic your fix elsewhere.
