### ISSUE TITLE
🚀 Feature: Customize Scaffolder Component Create using YAML 

### ISSUE THREAD

**Issue by taras** [backstage/backstage#16053]
### 🔖 Feature description

We want to align the embedded and Create Component features to eliminate the discrepancy in what the users see before and after the workflow is executed.

### 🎤 Context

In #15162, we introduced the ability to embed a scaffolder workflow into an entity page. It offers the flexibility to customize what the user sees before they run the workflow and after the workflow is finished. We created [@frontside/backstage-plugin-scaffolder-workflow](https://github.com/thefrontside/playhouse/blob/main/plugins/scaffolder-frontend-workflow) package with a component to streamline this setup process. **However**, an embedded template can still be executed by Scaffolder's Create Component workflow, which lacks the context and configurations of the embedded workflow.

### ✌️ Possible Implementation

Extend the `kind: Template` definition to allow configure components that present information around the workflow using extensions API. 

![Untitled scene-10](https://user-images.githubusercontent.com/74687/215525696-4dfba8d9-add6-4541-bf21-d76a5dd1f874.svg)

1. Customize the header of the current workflow either by referencing a component via YAML or by providing text.
2. Customize the review component that asks user to verify information provided in the stepper
3. Customize the create button text
4. Customize the summary component that is displayed after scaffolder finishes
5. Customize the restart workflow button with an option to remove it

We'd need to figure what API will look like for customizing these.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by taras** [comment]
> I'm feeling that some of this work could be done with the https://github.com/backstage/backstage/pull/11819 work or the plugin configurable options.

I'm not sure if this is the issue that @Rugvip referenced earlier about creating a frontend extension API. Regardless, I was thinking the same. I wanted to create this issue so we have an umbrella to reference the entire use cases. Enabling this level of customization might require a different changes. 

> I'm also cautious of adding more UI properties to the entity yaml to configure this, I think partly this seems on a high level like a good idea because we already have the ui:schema declared in the template entity for the Form, so it kind of makes sense to build on top of that, but it just ends up polluting the entity and maybe not the best place to make these decisions. 

I can see that especially because the extension itself is implemented in React, not in YAML. The extension identifier doesn't mean anything without applying corresponding change to React code. If it was possible to define the extension in YAML, then the extension would be portable and would be meaningful in YAML.

What if we had something like `ui:data` property that could be used as an escape hatch for experimentation? It would accept any data and invoke a hook that could be used to customize the setup of the scaffolder component.

**Comment by minkimcello** [comment]
@benjdlambert There's a team that wants to fork the entire scaffolder plugin because they're unable to modify the header title of the `TemplateListPage` (`1`) and `TemplateWizardPage` (`3`), nor remove `Available Templates` text of the sidebar (`2`).

Could we perhaps find a solution until [#11819](https://github.com/backstage/backstage/pull/11819) is fleshed out?

![Screenshot 2023-03-14 at 11 43 00 AM](https://user-images.githubusercontent.com/29791650/225060671-ba3b5aa3-1831-4ac1-890a-ec65c66f2523.png)

- `1` and  `2` can be addressed by having a prop to override the [default list page](https://github.com/backstage/backstage/blob/f00e03c38f0de6487af990e0410f4219eb1a8e28/plugins/scaffolder/src/next/Router/Router.tsx#L110-L113)
- `3` is [hard coded](https://github.com/backstage/backstage/blob/f00e03c38f0de6487af990e0410f4219eb1a8e28/plugins/scaffolder/src/next/TemplateWizardPage/TemplateWizardPage.tsx#L81-L83) in to replicate [`1`](https://github.com/backstage/backstage/blob/f00e03c38f0de6487af990e0410f4219eb1a8e28/plugins/scaffolder/src/next/TemplateListPage/TemplateListPage.tsx#L80-L84)
  - Since we have the reference to the template, we could use its name and description to populate the header of the `TemplateWizardPage` (see `4`)
    - The `InfoCard` already uses the name for its header so it'll be a little repetitive but it would be much more relevant for all the templates that aren't "components"
- And with `5` I was just illustrating that the header is generic enough to not cause confusion
