### ISSUE TITLE
🚀 Feature: Add CLI command to inject APP_CONFIG into app bundle

### ISSUE THREAD

**Issue by taras** [backstage/backstage#16127]
### 🔖 Feature description

When not using `app-backend` plugin or when using `app-backend` with `disableConfigInjection: true`, you have to manually inject app config into frontend app bundle. This is mentioned in [Separate Frontend](https://backstage.io/docs/deployment/docker#separate-frontend) section of Backstage docs but it doesn't mention how to actually inject the config. 

<img width="835" alt="image" src="https://user-images.githubusercontent.com/74687/216188729-d901dc96-dbef-4e40-bb25-9336f65d3f50.png">

There is a bash script in frontend-with-nginx contrib, but it requires explicitly passing environment variables. It would be helpful if we could generate app-config, the same way that app-backend does.

### 🎤 Context

One of our clients has to run Backstage with readOnlyRootFilesystem: true. This issue was previously reported in https://github.com/backstage/backstage/issues/4135, but there was no easy way to do it.

### ✌️ Possible Implementation

@jbolda [created a script](https://gist.github.com/taras/b50139ea9d7c77327c354e7964817feb) that takes `--config` parameters, stitches together the config and injects frontend config into `packages/app/dist/*.js` files. We could add this as a command to the CLI so it's easily accessible to others.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
There's actually a shortcut we can take here to skip the config schema loading from deps. The config schema is available in serialized form in the frontend bundle as `.config-schema.json`. This is what the app backend uses for the config injection, since the frontend packages won't be available at runtime there at all.

I think this is a good idea in general, probably a `backstage-cli config:inject` command? It does raise the question for me of when you'd actually want to use this. I'm assuming this would essentially be a bit an optimization that allows you to inject config in the frontend bundle rather than building multiple bundles, which is an alright speed improvement.

Is there any other usage of this that you have in mind that unlocks new possibilities?

**Comment by taras** [comment]
> The config schema is available in serialized form in the frontend bundle as .config-schema.json. 
Nice! We'll take a look and adjust the script accordingly.

> `backstage-cli config:inject`

That's what I was thinking.

> It does raise the question for me of when you'd actually want to use this. I'm assuming this would essentially be a bit an optimization that allows you to inject config in the frontend bundle rather than building multiple bundles, which is an alright speed improvement.

I think it's anytime you need to inject config at build-time instead of run-time. 

1. Deploying frontend separate from Backend
2. when using app-backend with a read only container file system which requires `disableConfigInjection: true`
3. when deploying ephemeral environments and want to be able to inject special config into frontend

**Comment by jbolda** [comment]
> The config schema is available in serialized form in the frontend bundle as `.config-schema.json`.

Is the expectation that the schema helps with loading the config? Effectively skipping this step that we have in that script linked in the OP ☝️. I think I would be a bit worried about it becoming stale, but maybe that is unfounded as we should pretty much always run a build followed by an injection.
```js
  const schema = await loadConfigSchema({
    dependencies: packages.map(p => p.packageJson.name),
    // Include the package.json in the project root if it exists
    packagePaths: [paths.resolveTargetRoot('package.json')],
  });
```

**Comment by Rugvip** [comment]
@jbolda yep, you can see what the `app-backend` does [here](https://github.com/backstage/backstage/blob/bf310578fe1a113051bfe90d7fffa5bd1ab14ed6/plugins/app-backend/src/lib/config.ts#L90-L95). The schema being stale shouldn't really be an issue, unless you are providing config for more plugins that are present in the app build. The failure mode is on the safe side though, as in you'll end up with config not being available in the frontend rather than leaking secrets to the frontend.

@taras so I'm seeing this as a build-time optimization where you don't need to build the app multiple times with different configs, but instead you're able to build it once and then inject. There is also the use-case of doing a later injection, but then you'll need the backstage-cli installed in the environment. That isn't really too desirable e.g. in an nginx server, but you could ofc go that route too.

**Comment by mathieu-benoit** [comment]
Hi @taras @jbolda @Rugvip, out of curiosity, any improvements or thoughts about this one?

Here is my setup in the `app`'s `Dockerfile`:
```yaml
...
FROM nginxinc/nginx-unprivileged:alpine-slim
USER root
RUN apk update && apk add jq && rm -rf /var/lib/apk/lists/*
USER 101
COPY --from=build /app/packages/app/dist /usr/share/nginx/html
COPY container-config/default.conf.template /etc/nginx/templates/default.conf.template
COPY container-config/inject-config.sh /docker-entrypoint.d/40-inject-config.sh
ENV PORT=8080
```
But then at runtime, getting this error:
```none
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/40-inject-config.sh
Runtime app config: {
  "app": {
    "title": "Hello, Compose!",
    "baseUrl": "http://localhost:3000"
  },
  "backend": {
    "baseUrl": "http://localhost:7007"
  }
}
Writing runtime config to /usr/share/nginx/html/static/module-backstage.40d4822a.js
sed: can't create temp file '/usr/share/nginx/html/static/module-backstage.40d4822a.jsXXXXXX': Permission denied
```
I'm wondering if there is a better way to inject these env var/ app config at runtime?

**Comment by mathieu-benoit** [comment]
JFYI, to make this fixed and working, I needed to do that in the `frontend`'s `Dockerfile:
```diff
...
FROM nginxinc/nginx-unprivileged:alpine-slim
+ ARG UID=101
USER root
RUN apk update && apk add jq && rm -rf /var/lib/apk/lists/*
COPY --from=build /app/packages/app/dist /usr/share/nginx/html
+ RUN chown -R $UID:0 /usr/share/nginx/html/static/
+ RUN chmod -R g+w /usr/share/nginx/html/static/
COPY container-config/default.conf.template /etc/nginx/templates/default.conf.template
COPY container-config/inject-config.sh /docker-entrypoint.d/40-inject-config.sh
+ USER $UID
ENV PORT=8080
```
JFYI.
