### ISSUE TITLE
🚀 Feature: Possibility to update entities via UI

### ISSUE THREAD

**Issue by yesmanmx** [backstage/backstage#16155]
### 🔖 Feature description

As a user, I want to be able to update entities' data via backstage UI

### 🎤 Context

When working with backstage, to add a link or relation or update some fields of entity - you need to manually update yaml file.
Editing entities via UI will make work with a backstage much more user-friendly. You will not need to edit data in the database (git repo in this case) directly.

### ✌️ Possible Implementation

Backstage already have "view yaml" for the entity feature. 
Few forms can be implemented to update common fields like description or links. On form submission - new yaml will override existing in the git repo and in backstage's database.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Hi!

This can be done in a couple different ways. For data in a version control system, ultimately the end result has to either be a push, or a pull request. That involves making requests using the relevant client library, eg octokit for the case of github. We have the helpers to get the auth set up for that so that it happens on behalf of the actual user performing the action, so that's good. You could make a web interface either for targeted actions as you mention, or in the form of a full YAML editor that helps you do validation and get the indentation right and all of that jazz.

Separate to this, there's an entire track to explore of having direct editor support, as in, building vscode / intellij plugins and thinking about leveraging schemas and/or querying the catalog for automatic validation as you type, and stuff like that.

Ping @taras here for info - these are topics that may be of interest to him, and to the Adoption SIG work that's underway.

**Comment by yesmanmx** [comment]
Thank you for the answer.
I understand, that I can do it on my own, but I want it to be a part of backstage and available out of the box.

Also, if backstage will support some database as a source of truth backend (not git), it will be very helpful for decoupling from code, easy migrations, and consistency checks. 
E.g.: specify postgres as the source backend for storing entities. Add action in templates for entity creation. Implement CRUD API and interfaces for entity management directly in the backstage app. Implement entity provider to sync with the core database.

Disclaimer: I still understand, that all this is possible to do on my own, but I won't be able to support it on my own :)

**Comment by yesmanmx** [comment]
about

> Separate to this, there's an entire track to explore of having direct editor support, as in, building vscode / intellij plugins and thinking about leveraging schemas and/or querying the catalog for automatic validation as you type, and stuff like that.

It is nice to have this, but still, this requires some third-party tool to work with backstage. And my point is that backstage should be self-sufficient and user friendly

**Comment by belech** [comment]
Hi!

We've built something like this internally for our Bitbucket repos:
- a Yaml Editor that is filled with the catalog-info.yaml content from the repo (using monaco-yaml: https://github.com/remcohaszing/monaco-yaml) 
- an endpoint within Backstage that outputs a dynamic JSON Schema based on the whole Backstage catalog data for the different entity types - therefor offering then some predefined Enums and autocomplete functionality to e.g. easier define the correct component name in the dependencies as well as to have some validation like the inbuilt Backstage restrictions e.g. metadata.name must have a certain format
- a save functionality that creates a pull request with the changes

I was thinking about open sourcing it, but there would be needed to do some generalization, since we have some specific scenarios just for us in there right now and it's all put together in one plugin. Might be considering to split the above mentioned functionalites up a bit into seperate plugins and have an "Editor" plugin, that can offers some extendable functionality so other plugins could integrate their own saving logic. There is probably quite a lot to consider to have it generalized.

Here is a screenshot to easier grasp what we've done:
![image](https://user-images.githubusercontent.com/32592620/218134512-b903ca18-4669-4133-82e3-55338a974db8.png)

**Comment by yesmanmx** [comment]
Thank you for the answer
It looks handy, but still not enough for backstage to be an independent tool for all team (not only developers)
Thanks for the link, I will try it. But if you decide to implement CUD UI for entities - I would like to use it.

BTW, backstage is really cool and powerful tool, but a bit complex sometimes

**Comment by aaronnickovich** [comment]
@belech I really appreciate your implementation details! I just found out about monaco-yaml from your suggestion and it looks awesome! We've been trying to build a custom template to download + merge yaml files together but it's not quite working out for us with multi yaml files.

**Comment by efenner-cambia** [comment]
I would also be interested in this

**Comment by dweber019** [comment]
@belech Awesome stuff. Any chance you open source your solution.

**Comment by enryson** [comment]
My company is also interested in this, i see this as one basic feature. And i really hope this will be implemented..

**Comment by jonatasalves-hotmart** [comment]
Hi, I also need this in the company I work for.

**Comment by freben** [comment]
I'd be interested in hearing about end-to-end workflow descriptions. Those of you who expressed interest, how would you envision that this worked from start to finish?

Say you are an org with a couple hundred or thousand repos and teams. You want to start adopting Backstage. What would you like the journey to be like, for your end users to start getting things into the catalog and get all of the right metadata into place, from that blank slate? How would permissions and the lifecycle of things work?

**Comment by enryson** [comment]
> I'd be interested in hearing about end-to-end workflow descriptions. Those of you who expressed interest, how would you envision that this worked from start to finish?
> 
> Say you are an org with a couple hundred or thousand repos and teams. You want to start adopting Backstage. What would you like the journey to be like, for your end users to start getting things into the catalog and get all of the right metadata into place, from that blank slate? How would permissions and the lifecycle of things work?

On the company that i work now, we divided the implementation on stages...

- 1 Stage (we are on this stage right now BTW):
Techdocs + Software Catalog + Users + Groups
We took 2 teams and they are in-charge to catalog and adding they own entities on a catalog repository.

- 2 Stage:
Expand from 2 teams to a tribe.

- 3 Stage:
Expand to all our 6 tribes.

- 4 Stage:
Implementing software templates, CI-CD, centralize all the solicitations of services on backstage.

For now. Stage 1 we encounter some issues.
Th adoption is running really slow, the dev's must clone the backstage service as well the catalog, running both on the machine and fixing entity errors... THEN creating a branch, making a pull request, and other team testing and validating if the PR is ok.
In the future all this entities must have some changes, updates etc.. and this process is slow and not that user intuitive even for the dev's.

Will be really nice to have a interface to help with..

I imagine working something like this..
1 - Developer logging on backstage.
2 - He have a button to CREATE a entities (user, system, api etc..) OR he can select a existing one and just editing that.
3 - The interface will be very similar to CREATE or UPDATE a entities.
will be nice if this will be a complete interface, with selects for choosing TEAMS, APIS from other entities, like form interface, maybe using the entities APIS to bring existing data of the database, like: "i'm creating a new API, this api has a part on a System, or consumes other api, is own by the the team" something like this..
4 - the dev click on save, then backstage makes sure that the entity is all ok.
5 - The dev save the changes directly on the YAML file and the database,( or only the database)

OR maybe like this..

1 - Developer logging on backstage.
2 - He have a button to CREATE a entities (user, system, api etc..) OR he can select a existing one and just editing that.
3 - Brings him to a online text editor, so he can make the changes, with help of ta intelisense, auto-complete, with all the tools need to facilitate this step.. if the user are Creating a new entities maybe given the option to use a template..
4 - the dev click on save, then backstage makes sure that the entity is all ok.
5 - The dev save the changes directly on the YAML file and the database,( or only the database)

On both cases i saw the permissions like this..
Devs/TechLeads can edit and create entities of their own SQUAD.
PrincipalEngineer can edit and create entities of  multiple SQUADS from his tribe
Coordenators can edit and create entities of ALL tribes..

BTW all teams can SEE all the entities from other teams..

This is how i saw on the company that i work... maybe this will not be 100% to other people on this thread..

(i'm not native to English language so, forgive-me if i wrote something not 100% clear.. )

**Comment by freben** [comment]
## Regarding Files

> the dev's must clone the backstage service as well the catalog, running both on the machine and fixing entity errors... THEN creating a branch, making a pull request, and other team testing and validating if the PR is ok. In the future all this entities must have some changes, updates etc.. and this process is slow and not that user intuitive even for the dev's.

Oh hold on, this sounds unfamiliar. When you say "the backstage service" and "the catalog", what are you referring to that's being cloned? Why are they being cloned? Who are the "devs" here - the end users that own the entity, or the infra team that owns the catalog backend service? Did you imply that the catalog source code and the catalog-info files are in the same repo?

To be clear, the intended use is that the catalog is a service owned by an infra team and never cloned by anyone else. The catalog-info files feeding it are distributed throughout the org, in every repo - and are never cloned by the infra team since the service/website/etc owning teams manage that yaml file themselves.

> Will be really nice to have a interface to help with..

The intended interfaces to be used, with the most preferred at the top, is:

- Use the scaffolder to create new things from the Backstage interface. When you create a new service, or website, or whatever it is, your template makes sure to already contain a catalog-info file that gets auto-registered in the catalog, again by URL. Everything is automated from there and the team that created the new repo and entity also manages it from there on in their repo by editing that yaml file when needed. To be clear, having to edit these files is typically very rare.
- Use the import wizard (also under Create), pointing to a repo and letting it create a nice catalog-info file for you. Again, it gets auto-registered and the target repo's owning team will manage it from there on without involving the infrastructure team that owns the catalog backend. The drawback of this approach is that it's not very fleshed out yet; it only is able to make pull requests for github at this point but contributions to extend its abilities are welcome.
- Teams create the catalog-info file by hand, in the target repo like above, and register the full URL to it in the same import wizard.

So editing will be done in a distributed manner by teams, by e.g. changing the owner field in the yaml file in their own repo if that's what they needed to do.

> I imagine working something like this.. 1 - Developer logging on backstage. 2 - He have a button to CREATE a entities (user, system, api etc..) OR he can select a existing one and just editing that.

The CREATE case is covered by the scaffolder.

The EDIT case is today handled in a code editor, as part of their regular development workflows of the source code that it describes. For example adding a `spec.system` field to connect to a system or so.

> 3 - The interface will be very similar to CREATE or UPDATE a entities. will be nice if this will be a complete interface, with selects for choosing TEAMS, APIS from other entities, like form interface, maybe using the entities APIS to bring existing data of the database, like: "i'm creating a new API, this api has a part on a System, or consumes other api, is own by the the team" something like this.. 4 - the dev click on save, then backstage makes sure that the entity is all ok.

So this touches on entity validation. Yes when making changes today, there's not a great story on how to get _early_ feedback that you've made a mistake in your yaml file since the catalog only discovers that some time later when it ingests it after you've already made changes to your repo.

The errors should get surfaced in the Backstage interface of course, but by then it's "too late" and the cycle gets longer than it ideally should be. There's an [entity validation plugin](https://github.com/backstage/backstage/blob/d1aa79a20e66009358e1f0f938977d8a003372c7/plugins/entity-validation/README.md?plain=1) but it'd be better if there were code editor integration etc to get realtime feedback as you are editing the entity. That's still on todo though.

> 5 - The dev save the changes directly on the YAML file and the database,( or only the database)

The thing here is that in the typical existing workflows, the yaml file resides within a version control repo. So if we made a frontend interface to edit entities, the only possible outcome of that editing is that it makes either a push or a pull request toward the repo where the yaml file resides. That's possible to write! I know some actually have. But it'd have to use the user's oauth token to perfrom those actions, because you'll have to deal with write access limitations etc. And you'll have to invent that interface for all possible target version control systems - you need to be able to communicate with github, gitlab, bitbucket, azure, ... etc, to make that feature useful for everyone. So there's a bit of a threshold to building that, and we haven't yet. That's a worthwhile contribution to make though.

There's the extra complexity that not all data is sourced out of version control systems in the first place. They can literally come from anywhere, including being fetched from like LDAP or whatnot. So a FULL editing interface that supports ANYTHING is probably impossible.

> OR maybe like this..
> 
> 1 - Developer logging on backstage. 2 - He have a button to CREATE a entities (user, system, api etc..) OR he can select a existing one and just editing that. 3 - Brings him to a online text editor, so he can make the changes, with help of ta intelisense, auto-complete, with all the tools need to facilitate this step..

Right but this is kind of a technicality then, what the interface looks like (text vs form). And it'd be nice if the integration was within people's code editors instead, eg vscode having a plugin for Backstage files. There's a lot of nuance in getting something like that right, too, but worth considering.

> On both cases i saw the permissions like this.. Devs/TechLeads can edit and create entities of their own SQUAD. PrincipalEngineer can edit and create entities of multiple SQUADS from his tribe Coordenators can edit and create entities of ALL tribes..

As long as the editing is inside remote repos, then those repos are governing the rights, not Backstage itself.

> BTW all teams can SEE all the entities from other teams..

Mm, out of the box that's correct. You can set the permissions differently if you like.

## Alternatives

There's a completely different path, as you have alluded to. You can skip the whole deal with yaml files entirely, and instead making your entirely own store backed by a database. Like, making a plugin with a database whose purpose it is to CRUD entity-like data, and then the catalog ingests from that one. Then you can make entire workflows and interfaces of your own for how to manage entities.

The reason that this is not what we do out of the box, is that it pushes a LOT of responsibility onto the maker of that, that version control systems are already awesome at doing.

- You move the metadata away from the source code, so now you can't see it immediately next to the thing it describes
- You no longer have automated rights management; you have to be very very careful in not letting the wrong people edit an entity that don't have any business doing so - how do you make this sort of mirror what the VCS has set up?
- You have no traceability unless you carefully explicitly build it; for a version control system you can trace the entire lineage backward and blame changes
- You have no conflict handling unless you explicitly build it
- You have to think about how you revert changes
- You can't rely on the existing backups etc that your org's VCS likely have
- You now own and are on-call for this new piece of important infra, rather than the VCS team
- And it keeps going :)

Can be done. Has significant cost and complexity. We don't offer it out of the box since we've been feeling highly successful with the yaml file approach.

**Comment by enryson** [comment]
Tanks for the explanation.
let me explain more about the overall team.
We have 9 tribes, 40 squads and 300 repos.

We know that is a lot for your organization, so will be part of a future job is to merge or refactor some services to make a better infrastructure.
Your first milestone is to catalog ALL that we have, and doing so with new features and integrations as they come. 

A very challenging milestone.

Each team member is constantly changing squads and even tribes, and the services to. We are passing on a re-structure phase as we speak, we hope to get the house in order in the next couple months. So backstage will help to catalog all the teams, repos, users etc. 

> ## Regarding Files
> 

> Oh hold on, this sounds unfamiliar. When you say "the backstage service" and "the catalog", what are you referring to that's being cloned? Why are they being cloned? Who are the "devs" here - the end users that own the entity, or the infra team that owns the catalog backend service? Did you imply that the catalog source code and the catalog-info files are in the same repo?
> 
No, whe have 2 repos,one for backstage and the other for the catalog.
The catalog is where we store all the YAML files from the teams.
By using a single repo to store the catalog we are making the info more accessible to all the teams so they can get examples getting the info from other teams to link APIs services etc. (i know they can see this info directly on backstage, but maybe seeing this info on the YAML file makes more easy to understand)

> To be clear, the intended use is that the catalog is a service owned by an infra team and never cloned by anyone else. The catalog-info files feeding it are distributed throughout the org, in every repo - and are never cloned by the infra team since the service/website/etc owning teams manage that yaml file themselves.
>
All of our repos have user permissions, everyone can clone any repo, but not everyone can submit changes to the code.

> The intended interfaces to be used, with the most preferred at the top, is:
> 
>     * Use the scaffolder to create new things from the Backstage interface. When you create a new service, or website, or whatever it is, your template makes sure to already contain a catalog-info file that gets auto-registered in the catalog, again by URL. Everything is automated from there and the team that created the new repo and entity also manages it from there on in their repo by editing that yaml file when needed. To be clear, having to edit these files is typically very rare.
> 
>     * Use the import wizard (also under Create), pointing to a repo and letting it create a nice catalog-info file for you. Again, it gets auto-registered and the target repo's owning team will manage it from there on without involving the infrastructure team that owns the catalog backend. The drawback of this approach is that it's not very fleshed out yet; it only is able to make pull requests for github at this point but contributions to extend its abilities are welcome.
> 
>     * Teams create the catalog-info file by hand, in the target repo like above, and register the full URL to it in the same import wizard.
> 
> 
> So editing will be done in a distributed manner by teams, by e.g. changing the owner field in the yaml file in their own repo if that's what they needed to do.
> 

On my understanding the software templates works very well on newer services right? with the automation of pipelines and adding automatically on the catalog. But if we have a existing service your suggestion is to use the import.

I see a couple points on using the import. on my understanding each repo have to have their own entity yaml file (correct me if i'm wrong). fist we have to change the structure so each service repo have their own entity(for me this is not a huge problem), but if this entity needs some changes, this changes must be done directly on the catalog repo right? is not wise to import again the same entity right? 

This will be very common on our workflow, entities will be updated, adding new relations to other services/components/apis etc.. change owners, and maybe even the name of the entity.

About the versioning this maybe can be done with a PR automation on backstage


I will take a closer look and test the import plugin, but this points will be a issue for us.
and even that i still think that a GUI will be nice to this. But i understand the complexity and use case will be different for everyone.

> ## Alternatives
> 
> There's a completely different path, as you have alluded to. You can skip the whole deal with yaml files entirely, and instead making your own store backed by a database. Like, making a plugin with a database whose purpose it is to CRUD entity-like data, and then the catalog ingests from that one. Then you can make entire workflows and interfaces of your own for how to manage entities.
> 
> The reason that this is not what we do out of the box, is that it pushes a LOT of responsibility onto the maker of that, that version control systems are already awesome at doing.
> 
>     * You move the metadata away from the source code, so now you can't see it immediately next to the thing it describes. Kinda loses the "connection" between them
> 
>     * You no longer have automated rights management; you have to be very very careful in not letting the wrong people edit an entity that don't have any business doing so - how do you make this sort of mirror what the VCS has set up?
> 
>     * You have no traceability unless you carefully explicitly build it; for a version control system you can trace the entire lineage backward and blame changes
> 
>     * You have no conflict handling unless you explicitly build it
> 
>     * You have to think about how you revert changes
> 
>     * You can't rely on the existing backups etc that your org's VCS likely have
> 
>     * You now own and are on-call for this new piece of important infra, rather than the VCS team
> 
>     * And it keeps going :)
> 
> 
> Can be done. Has significant cost and complexity. We don't offer it out of the box since we've been feeling highly successful with the yaml file approach.

My team thinks that maybe will be a solution for other problems on the future.
Not only the creating and editing entities, but we can implement to another feature that we miss on backstage. The approval for newer services/apis etc.(but this is another topic kkkk).

I think that this thread shows a very complex problem to solve, but shows a need from the community for a better way to validate and editing the entities.

But is nice to heard from others another point of view or solution to this problem..

**Comment by aaronnickovich** [comment]
@belech I was inspired by your reference material and built a clone for myself to help learn React. That monaco-yaml library seems to force me into the low-level javascript event listeners and it felt very difficult to use React other than a way to import a component. Did you experience the same?

I dont know if I just lack some React experience, but for the life of me, l just couldnt get Jest to instrument the monaco-yaml editor.

What was really interesting about this effort was that I didnt realize monaco is the VSCode engine and that IDEs use language-server-protocols (LSP). So the monaco-yaml shims the YAML LSP built by Red Hat and so I built a rudimentary VSCode web editor for backstage files. Anyways, really cool experience!

@freben, I kind of like this plugin because I can reuse a full json schemastore which works beyond just backstage files. However, if I try to contribute this feature back, do you have any ideas where should it be located? I just threw mine on the left nav bar, but I'm wondering if it should be an optional drop-down where people typically select the github ingestion tool

**Comment by freben** [comment]
> I see a couple points on using the import. on my understanding each repo have to have their own entity yaml file (correct me if i'm wrong).

That's right.

> fist we have to change the structure so each service repo have their own entity(for me this is not a huge problem)

Yep, spread them out to where they belong, and leave their management up to their respective owners.

> but if this entity needs some changes, this changes must be done directly on the catalog repo right? is not wise to import again the same entity right?

I am again a bit confused by the wording "catalog repo". :) There should be no catalog repo. You should have catalog-info files spread out all across your version control system, and the catalog (the catalog SERVICE, running in your infrastructure) holds a list of URLs pointing to those files. It updates its internal state all the time, in the background, based on the contents of those files.

If an end user changes a catalog-info file in their own repo, that's already registered in the catalog backend, there's no more action to take. You don't re-register. A short while later, the updated info will just automatically be reflected in the catalog.

**Comment by enryson** [comment]
I'm thinking abbot another suggestion..
When we use templates we can put the properties of the entity..
then we put the steps on the template.. to create new repo or push a file etc...

I wonder if is a great idea to use the templates as a structure to edit a entity..
the way i saw this, the editing page will be similar to the create template..
the editing fields will be the same fields as the create.
(if for some reason the editing has more fields, or some fields are different, this can be solved with dedicated template YAML, OR as a new parameters on the existing template. like "editing_parameters: " and "editing_steps:")

I know that backstage has a route to return a entity data, so the entity fields that are store on the database are display on this editing page. the UI can be customizable by using the "editing_parameters:" on the template..

After the user make the changes the entity can be validate and... if everything is right.. this will RUN the "editing_steps:"

For me this make sense, most of the tools to make this backstage have, like: route to validate a entity, steps to push files to a repo, and the UI..

On my take this is "basically" re-create the create page but using different parameters and steps or even a different template.yaml, the KIND and TYPE on the entity will be the key to determine what  "editing template" to use...
And the steps will be customizable to.. almost the same as the normal template.

this make sense? 
(English isn't my main language, so feel free to ask something)

**Comment by dweber019** [comment]
Maybe something like https://roadie.io/docs/catalog/decorating-components/

**Comment by brunoscota** [comment]
> Maybe something like https://roadie.io/docs/catalog/decorating-components/

This is something very useful for me because I'm importing some resource from external sources like rabbit exchanges and queues but these resources doesn't have any additional information like tags or customized field. In this case all my resources goes to same owner, for example. That would be great if we had a tool to edit these components after the importing.

**Comment by efenner-cambia** [comment]
bump

**Comment by efenner-cambia** [comment]
bump

**Comment by dweber019** [comment]
I have created a plugin which goes into this direction but I'm still testing it internal so consider it alpha.
https://github.com/dweber019/backstage-plugins/tree/main/plugins/accentuate
