### ISSUE TITLE
🐛 Bug Report: Users and groups in backstage UI are not in sync with Github org, GithubOrgEntityProvider has issue?

### ISSUE THREAD

**Issue by yogini-nemade** [backstage/backstage#16162]
### 📜 Description

We are on 1.10.1 backstage version, node v18.3.0 (npm v8.19.1), "typescript": "~4.6.4". But we have observed the issue with "GithubOrgEntityProvider" class. In backstage logs we get below lines which is correct number of users and groups but in backstage UI we can still see deleted users and groups/teams from github org.
{ "class": "GithubOrgEntityProvider", "level": "info", "message": "Committed 245 GitHub users and 72 GitHub groups in 0.3 seconds.", "plugin": "catalog", "service": "backstage", "target": "https://github.com/orgname", "taskId": "GithubOrgEntityProvider:production:refresh", "taskInstanceId": "b7003399-aabe-4582-aa87-acfc3455feaf", "type": "plugin" }
We did not see any error with respect to this class but data in UI is not correct. We tried to check the data in postgres database backstage_plugin_catalog(DB), refresh_state_references(table). We could find multiple db records of users which were removed from github org sometime back. Those references would have been removed or marked them orphan. Not sure why users/records are still present in table. Looks like this github backstage sync is not working as expected, Or let us know how this data can be synced with github?

### 👍 Expected behavior

Number of users and groups in backstage UI should be same as users and teams in github org.

### 👎 Actual Behavior with Screenshots

In Backstage UI we can still see removed users from github. Github has 245 users but backstage shows 299 users.

### 👟 Reproduction steps

1. Integrate github enterprise account with backstage
2. User should see users and groups in backstage UI
3. Add multiple associations or services api to any one user, add him in many github groups, also add groups from ref by location
4. Delete that user from github, also delete some groups from github
Expected result- User should be deleted from backstage UI when github-backstage sync happens and also removed from all his ownership associations
Actual result- User is still present in backstage UI with all associations active. and groups are also visible in UI.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by amritpalnagrame** [comment]
Navigate to those user / group entities view.
At the top you will see prompt for removing the respective entity, if that entity is really orphan.

**Comment by yogini-nemade** [comment]
For those deleted users or group we are not getting prompt on top to remove them, because we are not getting 
 "backstage.io/orphan": "true", in metadata for that entity. That seems to be an issue. What is reason of not marked them as orphan?

**Comment by freben** [comment]
The provider always [issues a `full` mutation](https://github.com/backstage/backstage/blob/bea00428f2977128e094224ae511491ef6d6eaaf/plugins/catalog-backend-module-github/src/providers/GithubOrgEntityProvider.ts#L235) which indeed is meant to replace whatever was there before, eagerly deleting things that are no longer in the input data.

This eager deletion only happens if there's no OTHER thing keeping it alive. This can happen sometimes for YAML files when they are held active both by a discovery processor and by an explicit registration. This shouldn't be the case here though, I think.

However, I am curious about the formulation "also add groups from ref by location", what did you mean by that?

One thing you can check in the database, is what incoming references exist for the entities that you feel that they should have been deleted. Essentially something like

```sql
select * from refresh_state_references where target_entity_ref = 'group:default/whatever';
```

Ideally, there should be only a single row which has `source_entity_ref` as `NULL`, and `source_key` being equal to `github-org-provider:` followed by your org provider's chosen ID (where it was instantiated in your backend).

**Comment by yogini-nemade** [comment]
Sorry for late reply. I checked this query for the user which was deleted from github but present in backstage. 2 rows are written with different 'id'(one id is 141 and other id 4122). For both `source_key` is `"GitHubOrgEntityProvider:production"` and NULL for `source_entity_ref`

**Comment by yogini-nemade** [comment]
"also add groups from ref by location",  this mean some groups are in backstage are coming from some data.yml files e.g owning-team name. which is not in github but in yaml file which are added in app-config.yaml (catalog:locations:target)

**Comment by freben** [comment]
But those YAML-imported groups don't overlap with the GitHub imported ones, right?

Ah interesting, so there's a duplicate edge to the provider itself. That might be a red flag. Let me look into that.

**Comment by freben** [comment]
Alright, I think I know what's going on. The backend correctly understands that the rows should be deleted, but this exact point of the deletion query doesn't deal with the duplicates since they have different IDs. Let's see if I can find a fix.

https://github.com/backstage/backstage/blob/c010a30fe97147b925cc1ef4276291eb17c95169/plugins/catalog-backend/src/database/operations/provider/deleteWithEagerPruningOfChildren.ts#L78

**Comment by freben** [comment]
Alright, I [made a refactor](https://github.com/backstage/backstage/pull/16305) to the internal deletion code to be significantly more robust against unexpected reference edges. Thanks for helping debug it!

**Comment by yogini-nemade** [comment]
Thanks for looking into this issue, Those(from yaml) group names are different that group names/teams coming from github. I can upgrade plugin after it is merged to master right?

**Comment by freben** [comment]
Only if you are using nightly releases. The regular release goes out tomorrow Tuesday.

**Comment by yogini-nemade** [comment]
We have upgraded backstage to 1.11.0. but still we can see deleted users and groups in backstage. Do we have to manually update/delete record in tables?
