### ISSUE TITLE
🚀 Feature: Allow git-flow model

### ISSUE THREAD

**Issue by fsbano** [backstage/backstage#16309]
### 🔖 Feature description

Allow git-flow model in app-config.yaml

### 🎤 Context

Allow multi-versions in the same repository

### ✌️ Possible Implementation

I have a stable version in main/master. However, i'm working in a new feature (develop/feat-breanch) and would like to log the evolution (doc, api) before merging with main/master

I use tag/release (v1.0, v1.2, v2.0) and would like to sse this entry in the catalog

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Please elaborate a bit more on what kind of features or capabilitied you are looking for.

**Comment by fsbano** [comment]
> Please elaborate a bit more on what kind of features or capabilitied you are looking for.

Updated ! 

Best Regards,
Fabio Sbano

**Comment by andrewthauer** [comment]
There was a similar discussion started on this in #14211. My suggestion there was to consolidate thoughts here, as to what you'd like see specifically happen in Backstage and how certain plugins might change behaviour based on your workflow. Otherwise this ends up being a bit hand wavy and not actionable and/or difficult to provide solutions imo.

**Comment by seanevans** [comment]
I am also interested in this feature.  Many software companies have to maintain different releases over time, not only feature branches. 

We can use the following iOS release versions as an example: 
- [iOS 14 / iPadOS 14]
- [iOS 15 / iPadOS 15]
- [iOS 16 / iPadOS 16]

Each release has many components, and the versions will change over time, and the interactions between components will also change over time. 

As we all know, companies use branches or tags on the git repos to identify the version of the component. Usually using semantic versioning. Since a release is a collection of components with specific versions, it follows that it would be useful to reflect this within the backstage components.

Some loose examples:
- As a backstage user, I want to be able to select the branch or tag for each component, allowing me to view the documentation, relationships and dependencies for a specific branch or tag (component release). 
- As a backstage user, I want to be able to define / tag / mark a collection of components at specific version (software release).
- As a backstage user, I want to be able to filter searches by branch or tag or software release.
- As a backstage user, I want to be able to manage CI/CD by branch or tag or software release.

**Comment by andrewthauer** [comment]
Based on the current catalog model, I suspect that each version would probably need to be a different component. Then possibly some grouping component or composite that knows the relation of them. It's maybe possible to hack the usage of entity dependencies or some other entity relationship to do this. However, no plugins are designed really to work this way, so your mileage may vary. I think you'd need to do some experimentation to see what works and doesn't work and then see what gaps are left. Anyways my 2 cents.

**Comment by seanevans** [comment]
Thanks for the response @andrewthauer . I'll start with that approach and see where I get to.
I did see there was a related Open Mic from 2021 "Versioning the cloud" which seems to have the right idea, but didn't seem to get traction.

https://backstage-openmic.com/recording/taras-elrick-versioned-components-backstage/
