### ISSUE TITLE
🚀 Feature: Provide User entity through IdentityApi

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#16316]
### 🔖 Feature description

It would be nice to access the complete user entity using IdentityApi.

### 🎤 Context

We store various information about users in annotations. For example, we store first name and last name separately for presentation purposes. Or we store user id on other systems to provide integration.

When we need to use an annotation, we currently have to send a request to catalog api with `catalogApi.getEntityByRef(userProfile.userEntityRef);`. This results in another request to the catalog. Also, we use this in multiple components, therefore this request is duplicated unnecessarily.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
The auth system in the core API is currently a bit decoupled from the catalog, meaning that entities may not always exist in the catalog. I think for now we should keep doing manual requests to the catalog, but I've added this to #15999 so that we can consider this if we make more broad changes to auth.
