### ISSUE TITLE
🔌 Plugin: Apply git patch

### ISSUE THREAD

**Issue by zdufour-asp** [backstage/backstage#16429]
### 🔖 Summary

For templates that publish to existing repos with `publish:github:pull-request`, some files might already exist that we'd like to modify, e.g. adding a workflow to `.circleci/config.yml`. At the moment, if a directory pulled by `fetch:template` contains that file, it will fully replace the existing file, which makes it a bit painful to merge.

It seems like it might be *relatively* low-effort to implement an plugin that `git apply`s provided patch before / during a `publish:*`.

The biggest question in my head is whether this could be implemented as fully separate from `publish:*` or if it would need to patch those actions. That would probably have a big impact on the overall level of effort

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
This seems reasonable, I would suggest that this be a separate scaffolder action however. I wonder if this is possible in the current setup however, we might need to break up the bigger actions into smaller steps so that you can apply the git patch after the git repo has been created but before the push to the remote.
