### ISSUE TITLE
🐛 Bug Report: Reopen- Users and groups in backstage UI are not in sync with Github org

### ISSUE THREAD

**Issue by yogini-nemade** [backstage/backstage#16523]
### 📜 Description

This ticket to reopen old bug which supposed to be fixed on backstage upgrade to 1.11.0.
Link to old bug https://github.com/backstage/backstage/issues/16162

We are still able to see deleted users from github org in backstage UI.

### 👍 Expected behavior

Number of users and groups in backstage UI should be same as users and teams in github org.

### 👎 Actual Behavior with Screenshots

In Backstage UI we can still see removed users from github. Github has 245 users but backstage shows 299 users.

select * from refresh_state_references where target_entity_ref = 'group:default/whatever';
I checked above query for the user which was deleted from github but present in backstage. 2 rows are written with different 'id'(one id is 141 and other id 4122). For both source_key is "GitHubOrgEntityProvider:production" and NULL for source_entity_ref

### 👟 Reproduction steps

Backstage version 1.11.0
1. Integrate github enterprise account with backstage
2. User should see users and groups in backstage UI
3. Add multiple associations or services api to any one user, add him in many github groups, also add groups from ref by location
4. Delete that user from github, also delete some groups from github
5. 
Expected result- User should be deleted from backstage UI when github-backstage sync happens and also removed from all his ownership associations
Actual result- User is still present in backstage UI with all associations active. and groups are also visible in UI.

### 🖥️ Your Environment

Similar issue was marked as closed https://github.com/backstage/backstage/issues/16162

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Do you have access to the logs of the catalog backend? Looking for messages of this type

https://github.com/backstage/backstage/blob/8f72566485843ea75b58377052225abdf34594ff/plugins/catalog-backend-module-github/src/providers/GithubOrgEntityProvider.ts#L592

Something like `Read 299 GitHub users and 100 GitHub groups in 20 seconds. Committing...`

I am wondering whether that number is 299 or 245. Starting to wonder if deleted users are still being returned but with some form of "archived" marker or similar.

**Comment by paveldedik** [comment]
I seem to be having the same issue.

I can see in the logs the following message:

```
Read 72 GitHub users and 52 GitHub groups in 1.4 seconds. Committing...
Committed 72 GitHub users and 52 GitHub groups in 0.0 seconds.
```

While in Backstage, I have 90 users (as the old ones are not getting removed).

**Comment by freben** [comment]
Alright. For users that you expected to be removed, are they marked as orphans? As in, in their `metadata.annotations`, do they have the annotation `backstage.io/orphan: true`?

If not, do you have the ability to check in the database whether there are any entries in the table `refresh_state_references` that point to those entities, and what do those rows look like?

**Comment by freben** [comment]
Alright.

I want to caution that the `LIKE '%user%'` would inadvertently catch entities that have `user` _anywhere_ in their ref (including in the namespace and name). For the benefit of anyone else reading along and trying commands like those, do something along the lines of `LIKE 'user:%'` instead.

**Comment by paveldedik** [comment]
Thank you, I'll edit the past answear so that no-one copies those queries.

**Comment by beveradb** [comment]
We're encountering the same thing - our github org has 1,247 people, but backstage has 1,447 people.

Our backstage logs show:

```
-- Committed 1247 GitHub users and 457 GitHub groups in 0.2 seconds. |  
-- Read 1247 GitHub users and 457 GitHub groups in 70.3 seconds. Committing... |  
-- Reading GitHub users and groups
```

But I guess the orphaned users aren't getting deleted?

I've inspected the YAML for a couple of users who aren't in our github org anymore but are still in backstage, and they don't have any `backstage.io/orphan: true` annotation or anything else mentioning `orphaned` that I can see.

We haven't run any kind of manual cleanup or workaround yet, and won't do until we've investigated this a bit more deeply - I'd like to get to the bottom of the cause and hopefully fix it properly!

I'm happy to run any queries or do anything which might be helpful - please let me know if you have any ideas @freben 🙇

**Comment by andrewthauer** [comment]
We are experiencing something similar to this issue. We have no orphaned users or groups, however, may of the users and groups have not been in GH for months. I do see refresh state for these entities that should not exist. One thing that sticks out is the `last_discovered_time` is sometimes months old, but they are still being updated with the `next_update_at`. In our case the number of teams read is more then what GH has, but the # of users is the same. However, there are many more users in the actual catalog. Going to do some more digging, but any other advice on what to look for would be helpful.

**Comment by freben** [comment]
Yeah `next_update_at` will always be moving, as long as a row is in `refresh_state`, it will be subject to processing.

Are you on a recent-ish version of Backstage (specifically the catalog backend of course)?

Did you switch from provider to processor some time ago? Or rename a provider ID or so? Anything that might make it so that these are legitimate but left-behind rows.

Are the entities in question at least marked as orphans? Or do they have any `refresh_state_references` rows going into or out of them?

**Comment by andrewthauer** [comment]
We did switch from the processor to provider, but that was many months ago. When we did switch over I noticed duplicates so attempted to unregister and fix things. As far as I can tell there isn't any left over locations, etc.

Nothing shows as orphaned at all. I see `refresh_state_references` for the provider source key. All have `target_entity_ref` and none have `source_entity_ref` defined. I also do not see any groups/users as `source_entity_ref` I'm assuming this is expected?

Is there a safe way or process I can purge everything and start over for all GH uses/groups?

**Comment by freben** [comment]
Thanks for the insight. If I'm reading the explanation right, it basically seems like

- `A`, `B`, and `C` exist in the database, and they all seem to have exactly one `refresh_state_reference` row with the right `source_key`.
- The provider with that key keeps actively submitting `A` and `B`, using a `full` mutation, but that doesn't seem to make `C` get deleted.

I haven't seen that particular situation reported before; the delta computation hasn't been doing the wrong thing in quite some time as far as I can recall. Makes me wonder if maybe the mutation fails outright so that even old pre-existing things aren't being updated correctly anymore. Maybe a conflict has crept in that stopped the entire thing some time back?

> Is there a safe way or process I can purge everything and start over for all GH uses/groups? 

Well deleting `refresh_state` rows should be okay; that should make all related relations and references get torn down because of the foreign key relations in the database. The only tricky thing that remains is that you want to force anything with relations to those rows to get re-stitched (so they don't seem to have dangling relations according to their `final_entities` entries).

**Comment by andrewthauer** [comment]
> The only tricky thing that remains is that you want to force anything with relations to those rows to get re-stitched (so they don't seem to have dangling relations according to their final_entities entries)

@freben - Can you expand on this point a bit more? Which relations are you referring to? Do you mean components that are owned by affected groups for instance? Any further suggestions on how to ensure we don't end up with dangling entities or perhaps a way to identify and fix them after?

**Comment by freben** [comment]
Yeah deleting a `refresh_state` row correctly deletes all `relations` rows that had them as the `originating_entity_id`. However, those rows had `source_entity_ref`/`target_entity_ref` pointers that affected the stitched output of other entities since they get integrated into their `relations` root field. So unless those entities get run fully through the stitcher, their bodies will still make it _look like_ those relations were lingering around.

Unfortunately it's a bit annoying to mark things for stitching (gotta remember to clear those hash fields, and also put it through processing wastefully). This gets a lot easier if #18062 gets accepted; because then the stitcher is truly decoupled and can be run in isolation.

**Comment by andrewthauer** [comment]
@freben - Thanks for the detailed information and suggestions. I ended up clearing the existing `refresh_state` rows related to the GH org provider, waited until the next refresh and then confirmed the teams & users match. I also removed an old GH team and confirmed it was also removed from Backstage on the next refresh as well. I haven't tested removing users or members of groups, but am hopeful this is also working as expected now.

For reference all I did was run the following SQL in the `backstage_plugin_catalog` db:

```sql
# <id> is the id used when configuring the provider
delete from refresh_state
where location_key = 'github-org-provider:<id>'
```

**Comment by beveradb** [comment]
We did the same ^ in staging but haven't done it in prod yet as we haven't found an easy way to to it without downtime;
I don't suppose you know if there's any easy way to trigger a refresh immediately afterwards? e.g. run GithubOrgEntityProvider.read() or temporarily override the schedule set up by the `frequencyMinutes` config or something?

**Comment by andrewthauer** [comment]
So, doing this will clear out the groups/users until the next refresh. If you time it, you could minimize the impact. I was able to do this off ours and folks could still login with our identity provider, but the ownership features, etc. were not working. But the more critically used parts were still working. But I think mileage may vary depending on setup.

**Comment by andrewthauer** [comment]
Oh, actually you should be able to trigger refresh manually with some code. The `catalog` instance of the `PluginTaskScheduler` had a `triggerTask` method. I suspect you could code something up to call that to invoke the refresh manually.

**Comment by freben** [comment]
Or if you're already in the database messing around, you can set the next-run timestamp for the task to the current time (`backstage_backend_tasks__tasks.next_run_start_at`).
