### ISSUE TITLE
🐛 Bug Report: GitHub code snippets links should be code blocks

### ISSUE THREAD

**Issue by schultzp2020** [backstage/backstage#16648]
### 📜 Description

GitHub code snippets links should be code blocks in case the line number changes in the future. 
e.g.https://github.com/backstage/backstage/blob/master/docs/api/deprecations.md?plain=1#L167

There are potentially 65 issues currently in backstage.
![image](https://user-images.githubusercontent.com/52387464/221942318-00a90d1d-ee65-4a45-8509-42d537a51eb7.png)

### 👍 Expected behavior

N/A

### 👎 Actual Behavior with Screenshots

N/A

### 👟 Reproduction steps

N/A

### 📃 Provide the context for the Bug.

N/A

### 🖥️ Your Environment

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Not sure what you mean, could you please clarify the issue @schultzp2020?

**Comment by adamdmharvey** [comment]
@schultzp2020 I believe you're referring to the line references where sample code is linked to the repo, rather than inline?

When you link lines to a branch, especially one that is so frequently updated like `master`, I'd agree with you.

However, the example you link to above links actually to a git hash. Given that, it's immutable, meaning line 35 in git hash a3ec122170e0205fd3f9c307b98b1c5e4f55bf5f will always be the same, because changes can't be made to it:

https://github.com/backstage/backstage/blob/a3ec122170e0205fd3f9c307b98b1c5e4f55bf5f/plugins/user-settings/src/components/AuthProviders/DefaultProviderSettings.tsx#L35

But that same file linking to a line against `master` indeed allows it to drift making the value of linking a line not worth it:

https://github.com/backstage/backstage/blob/master/plugins/user-settings/src/components/AuthProviders/DefaultProviderSettings.tsx#L35

So given your feedback, if I search the repo, I do find a few such references which could potentially be updated. A few are `CHANGELOG.md` related, so their value depending on age could be negotiated.

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/33203301/224217284-14c6c3f9-0d2c-4775-a1da-07acb5bbbb86.png">

Is that maybe where you were heading?  And if so, might you be willing to help contribute fixes for those to link to a git hash as *opposed* to `master`?

**Comment by schultzp2020** [comment]
@adamdmharvey Yeah, that's more or less what I was referring to. If needed, I can try to work on it sometime this month.

**Comment by JaanJah** [comment]
I saw this issue had a "good first issue" label, so I decided to pick it up myself.

PR: https://github.com/backstage/backstage/pull/17484
