### ISSUE TITLE
Entity Feedback plugin not saving feedback🐛 Bug Report: <title>

### ISSUE THREAD

**Issue by carlossmartini** [backstage/backstage#16755]
### 📜 Description

I just installed the entity feedback plugin (awesome plugin idea btw!).  However, it doesn't seem to be working correctly.  Whenever I submit a feedback for an entity the post request is successful and comes back as a 201.  In addition, there are no errors in the logs.  This is true if I do a thumbs up or down and whether or not I submit some additional details when it's a thumbs down.

When I navigate to the feedback tab though there is no feedback for that same entity.

### 👍 Expected behavior

It should display feedback in the feedback tab for that entity

### 👎 Actual Behavior with Screenshots

It actually displays a blank feedback tab  after feedback is submitted for the entity.

### 👟 Reproduction steps

1. Submit feedback in the entity page
2. Go to the feedback tab in the entity page
3. Nothing shows up

### 📃 Provide the context for the Bug.

Installed frontend and backend plugins 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by kuangp** [comment]
hmm will need a bit more info to debug this ...

When you submit a rating (thumbs up/down) for the entity and come back to the entity page, does it remember your previous rating? The thumbs up/down icon for the most recent rating should be highlighted (filled in). (Trying to determine if it's saving your rating at all)

Also when you go to the Feedback tab, can you inspect the backend request (should be hitting the `/responses/` endpoint of the entity feedback backend) and see if that's successful/what the payload is? 

Lastly, are there any errors in the backend logs when you're interacting with the frontend plugin?

**Comment by carlossmartini** [comment]
I don't believe it's saving the feedback at all, but don't see anything that looks like an error.

1.  Does not remember previous rating.
2. Getting a 304 response from the /responses/   endpoint.  Response comes back as an empty array.
3. There are no errors or even anything useful in the backend logs and I have logging level all the way down to info.  Just shows the endpoint was called and the 304 being returned.

One thing I was thinking about this morning.  For my backend database I have pluginDivisionMode: schema.  Does the plugin support this or would it try to create a new DB?

**Comment by kuangp** [comment]
hm very strange ... 304 is not a defined response that the feedback backend [specifically returns](https://github.com/backstage/backstage/blob/master/plugins/entity-feedback-backend/src/service/router.ts#L190-L211) so this might be coming from the Backstage backend at a different abstraction level 

The plugin doesn't explicitly _not support_ schema DB division mode since it just relies on the [`PluginDatabaseManager`](https://github.com/backstage/backstage/blob/master/plugins/entity-feedback-backend/src/service/router.ts#L56-L57) to allocate a DB connection for use in this plugin.

Can you share what your backend setup looks like for this plugin?

**Comment by carlossmartini** [comment]
i think the backend is the problem.  When I query the Postgrest backend directly I can see the entityFeedback schema along with the ratings and responses tables.  However, if I try to do a select on either one of those tables I get a 500 error from Postgrest.  I can query other schemas and tables from other plugins just fine.  So not sure if it's not being set up correctly from the start or what.  I deleted the schema and started up the application again to create the schema and even then I couldn't query it even though I hadn't yet tried to submit any feedback so i would've expected the tables to be empty still at that point but got the error anyway.

**Comment by carlossmartini** [comment]
I think I figured out the issue.  The schema name is in camel case :) if I change the schema name to underscore then I'm able to query  the tables.

**Comment by kuangp** [comment]
ah I think I recall that PG specifically doesn't support camel casing (by default) for identifiers (it auto lowercases) so it makes sense that in the schema scenario that this is not working when you name it `entityFeedback`

I think the issues stems from here: https://github.com/backstage/backstage/blob/1af49d62e78b470898238be1f0ecb455dbcc9a85/packages/backend-common/src/database/connectors/postgres.ts#L165-L174

In the above code where the schema is created, any camel cased names will be auto lowercased in PG while the [knex query](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/database/connectors/defaultSchemaOverride.ts#L27) ensures that [casing is retained](https://github.com/knex/knex/blob/master/lib/dialects/postgres/index.js#L177) (via double quoting) which I believe explains the your situation where you're not able to query correctly due to the casing mismatch.

I think the fix here might be to update the SQL to double quote the schema name to ensure casing is retained: 
```ts
admin.raw(`CREATE SCHEMA IF NOT EXISTS "??"`, [database]);
```

Would you be willing to take a stab at this change and see if it fixes your issue (and open a PR with the fix 🙏 ) ?

cc: @Rugvip to double check my notes 😁

**Comment by carlossmartini** [comment]
Actually that didn't solve my issue completely.  I can see that it's saving the feedback on the database, but still don't see a retrieval.  In other words, the entity page is still blank and it does not remember the previous feedback.  Still seeing the 304 being returned and I don't see anything in the logs.  Any other suggestions on what else to look for?

**Comment by kuangp** [comment]
hm the only other thing I can think of right now is if your rating/responses are being filtered out via the [mechanism](https://github.com/backstage/backstage/blob/master/plugins/entity-feedback-backend/src/service/router.ts#L198-L208) which cross checks with the catalog plugin to only return data for entity refs for which you have access to. This would be dependent on the permissions policy you have setup. Do you have permissions enabled and could you share the current policy you have defined?

**Comment by carlossmartini** [comment]
Very odd.. Yea I don't have permissions setup yet as we're still in POC mode.  If I hit the ratings endpoint then I can see the count for each entity. Doesn't look like there is a plain responses endpoint without the component.  The endpoint with the component keeps giving me a 200 with an empty response and nothing in the logs.

**Comment by kuangp** [comment]
Since you're still in PoC, do you have users defined in your catalog? It might be returning empty since its checking with the catalog to only return data for users you're able to read from the catalog and if you have no users then that might be why its not returning your info.

**Comment by kuangp** [comment]
glad we were able to solve this! 😁 

in terms of this issue, I do believe that the original bug is still relevant (PG connector not handling case sensitivity for schema names) since this should work with the default plugin naming so lets keep it open for now. I might have some time later this week to implement the fix

**Comment by carlossmartini** [comment]
sounds good.. thanks for the help! I'm hoping to be able to help soon as well.. This is a great plugin!

**Comment by kuangp** [comment]
@sharadpattanshetti the error message you referenced looks like it's coming from the catalog plugin and shouldn't be related to this plugin. Do you see any other errors in the logs that look like they originate from the feedback backend?

**Comment by sharadpattanshetti** [comment]
@kuangp there are no other errors as such. Below is the request which I see from browser network tab 

https://mydomain.com/api/entity-feedback/responses/component%3Adefault%2Fmy-svc

Request Method: GET
Status Code: 500

**Comment by kuangp** [comment]
hmm going to need more info here to debug this. Can you share what your backend setup looks like for this plugin ?

**Comment by sharadpattanshetti** [comment]
Hi @kuangp I have followed the steps mentioned as here - https://github.com/backstage/backstage/tree/master/plugins/entity-feedback-backend

Added entityFeedback.ts and below code in the index.ts file. 

 ` const entityFeedbackEnv = useHotMemoize(module, () => createEnv('entityFeedback'));`


`  apiRouter.use('/entity-feedback', await entityFeedback(entityFeedbackEnv));`

One thing I see that is when the entity overview page is loaded and below GET api is called returning 500 error code : 
https://mydomain.com/api/entity-feedback/ratings/component%3Adefault%2Fmy-svc

**Comment by kuangp** [comment]
Can you also share what your `packages/backend/src/plugins/entityFeedback.ts` looks like (as a sanity check)? 

I'm surprised there's no other errors in the backend logs if you're getting 500s 🤔. Would you mind also sharing what the rest of your `backend/src/index.ts` looks like?

**Comment by sharadpattanshetti** [comment]
@kuangp I just checked other functionality like feedback responses for the kind:Group. It seems to be working fine. The issue is more to do with user identity and feedback mapping, I am checking if the user identity (catalog user) is properly loaded or not. 
I will get back to you asap.
