### ISSUE TITLE
🚀 Feature: (Entity feedback plugin) Calculate average score

### ISSUE THREAD

**Issue by Roohn** [backstage/backstage#16771]
### 🔖 Feature description

I would like to display per entity what the average score is that users have given as feedback.
While trying to calculate it myself I came across the "accessible entity filter" that filtered out any ratings that were not my own.
This means I can not calculate it on the client side. 

### 🎤 Context

We would like to use the average scores to let users know what catalog entity/item is most popular to aid in their decision.

### ✌️ Possible Implementation

Some api endpoint that accepts a entityRef and returns:
- for star ratings: a float between 1 and 5
- for like/dislike ratings: percentage? or maybe somehow convert the likes to a number between 1 and 5 🤔 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kuangp** [comment]
hm this might be more of a permissions restriction on the catalog side rather than an ownership restriction

There are 2 options to retrieve ratings for entities:
- Hitting the [`/ratings/:entityRef` endpoint](https://github.com/backstage/backstage/blob/master/plugins/entity-feedback-backend/src/service/router.ts#L147-L168) (possibly using the [`.getRatings(entityRef)`](https://github.com/backstage/backstage/blob/master/plugins/entity-feedback/src/api/EntityFeedbackApi.ts#L41) method on the `EntityFeedbackApi`) which would give you all ratings for a particular entity filtered to only ratings belonging to users that you can access 
- Hitting the  [`/ratings` endpoint](https://github.com/backstage/backstage/blob/master/plugins/entity-feedback-backend/src/service/router.ts#L62-L128) without specifying an owner (possibly using the [`.getAllRatings()`](https://github.com/backstage/backstage/blob/master/plugins/entity-feedback/src/api/EntityFeedbackApi.ts#L35) method on the `EntityFeedbackApi`) which would give you all ratings (aggregated to total per rating value) for all entities filtered to only ratings belonging entities that you can access 

Both options above should give you enough data to calculate rating averages over entities. However, this plugin aims to respect the permissions defined by the catalog plugin to not expose any entities that the user doesn't have access to which sounds like is the problem you're running into. Maybe adjusting the catalog permissions you have defined is a potential workaround here? 

I agree that it could be useful and more efficient to implement additional endpoints to just return averages to reduce the burden of sending all the ratings data over the wire for client side calculation but it gets tricky when dealing with non-numeric ratings. Maybe something like `/ratings/:entityRef/aggregate` makes sense to return just the total count per rating value (eg. 7 Likes, 2 Dislikes or 3 1-star, 4 5-stars) similar to the `/ratings` endpoint (but if you only care about a specific entity) and let the client handle calculating the average that makes sense off that data. It will also anonymize away  who applied which rating so it would work around needing to filter against entity refs with the catalog permissions.

Let me know if this makes sense!

**Comment by Roohn** [comment]
Thanks for the clear explanation. I believe I got two things mixed up, first things is that I wanted to use `/ratings/:entityRef` because then I didn't have to filter on the entityRef on the client but this only returns your own ratings. The second thing is that `/ratings` filters the entities you don't have access to, which in my case is fine. 

So a workaround for me is to use `/ratings` and filter on the entityRef on the client, but it might be a better experience to just do `/ratings/:entityRef/aggregate` and not filter on the client. 
I don't know if this is something that is going to be used by more people. I can see that it is not very good for performance to fetch all ratings if you are interested in just the one.

Let me know what you thing a good next step would be, we can leave it like this for now or if you agree I can create a PR?

**Comment by Roohn** [comment]
I created a PR to add the aggregated results. Please let me know what you think, especially the naming 😬 
https://github.com/backstage/backstage/pull/16833
