### ISSUE TITLE
🚀 Feature: Enhance "Your Starred Entities" component in Home Plugin with Kind

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#16909]
### 🔖 Feature description

Enhance the "Your Starred Entities" component from the home plugin to indicate the type of the entity which has been starred.

### 🎤 Context

I have a particular situation where the name of a template wasn't super clear, and I actually had forgotten if it was a template or not, and realized there's no way to know that on the starred entities component. It's a nice simple list, but it doesn't have either a visual indicator, parenthetical text, or anything of the like, to tell me if my entity I've starred is a template, a component, a document, etc.

<img width="653" alt="image" src="https://user-images.githubusercontent.com/33203301/225697676-94a17a13-074b-402f-8bd4-a27e41865501.png">

### ✌️ Possible Implementation

https://github.com/backstage/backstage/blob/master/plugins/home/src/homePageComponents/StarredEntities/Content.tsx

Ideas:

1. Grab a visual indicator different for each entity type so that I could visually identify if a starred entity is a template or a component, or a resource, or a document, or a system, etc.
2. In smaller text, possibly visually indicate like `[template]` or something after the entity name.

I haven't mocked anything up so not sure the best approach.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by adamdmharvey** [comment]
For sure.  A common helper function to display an entity throughout the site could be useful, say something which even could display in the catalog links or in search, etc, and I like your idea on large + small, and then we just reuse it here in this plugin maybe?  I believe there's already one which properly displays the full entityRef, prefixing namespace and such, so sort of taking that to the next level as a React component.

**Comment by freben** [comment]
Another complication is that it ties into the need for extendable / replaceable components throughout the interface. The [popover direction](https://github.com/backstage/backstage/pull/16878) has started to be explored, and the contents of these things is very likely to need to be customizable. A function may turn out to be too low level; a (possibly to-be-) pluggable component that has access to some form of a caching metadata batch fetcher might be the future proof way

**Comment by antoniobergas** [comment]
Hi! We actually have this need also internally.

For now I will try to make some small modifications to show at least the kind and maybe the spec.type (just some simple coloured chip) 

If that helps I can show my progress when I'm done and later maybe help to continue with this feature 😊

**Comment by benjdlambert** [comment]
#17474 could be a solution here as it can display icons for the kind. :pray:

**Comment by antoniobergas** [comment]
Hey! Just want to share what I did in our instance and works good

![image](https://user-images.githubusercontent.com/26031467/234825133-e26142ef-dcce-4cb7-bb8f-10f0489edbb4.png)

Simple chip with preestablished background per kind, orderer per kind and then per entity name (just to bring a bit more of order instead of a picasso of chips)

For now I just wanted to start simple so having some constants with the backsgrounds (cause not sure where to put this on the theme)

![image](https://user-images.githubusercontent.com/26031467/234825708-e28f7741-c83c-44f4-861d-8ca6bca62e58.png)

And then just a simple EntityKindChip component using a map to set the background depending on the kind from the props

![image](https://user-images.githubusercontent.com/26031467/234826049-a2437fbc-e872-4525-b63a-f34cb0cda864.png)

Things like size, color of this can be outputed thourgh the props I guess

Not sure about the map but wanted to close this fast internally cause we have different kind of entities with the same exactly name.

So any suggetions to do it better will be appreciatted.

If this fits in the ideas for #17474 I can work on that part 😄

PD: While I love to have icons to reference objects or elements, I think that maybe could be hard for the users of adopters to map which icon is what cause first of all they need to know whats an entity and whats each kind

**Comment by freben** [comment]
Yeah. The design there is up for discussion. Note though, that there's a tooltip so you can hover over to learn what something is at any point in time

**Comment by antoniobergas** [comment]
Can you please point me to that tooltip? That will help a lot to know quicker what is for something (entities, sidebars, etc) Thanks 😄

**Comment by freben** [comment]
You can check out the branch in #17474 and run it locally to try it out (check out the catalog page).

The code that renders the tooltip [is here](https://github.com/backstage/backstage/blob/78407a479dd00b3db7879616cd4292320db9d3dd/plugins/catalog-react/src/components/EntityName/EntityName.tsx#L86) in that PR.

The default renderer that supplies the text to be shown in the tooltip (you can supply your own instead!) [is here](https://github.com/backstage/backstage/blob/78407a479dd00b3db7879616cd4292320db9d3dd/plugins/catalog/src/apis/EntityPresentationApi/defaults.tsx#L62).

**Comment by antoniobergas** [comment]
Thanks @freben I will take a look when I have time 😄

**Comment by drodil** [comment]
@antoniobergas any updates on this work? Thanks!

**Comment by antoniobergas** [comment]
Hi @drodil, I have not had time to do anything, nor am I 100% sure if the approach we have used internally is valid for this feature?

I can create a PR with the codeI have now internally and we can work together to shape it to best fit the overall needs? Sound good?

**Comment by drodil** [comment]
Sure, sounds good. We also had internally a design for this but not sure if that makes the list a bit too long, anyhow here it is:

![image](https://github.com/backstage/backstage/assets/1178319/7ba60ea0-fa8f-4eee-bfdb-58e7f9da0ced)

Already pondered if we should make our own widget for this but I think the component needs some sort of categories since there can be same names for example for systems and components.

**Comment by antoniobergas** [comment]
So instead of showing extra info of each entity just group them ?

**Comment by drodil** [comment]
Yeah that was our plan but I don't know which is better. Any opinions from maintainers, @freben @benjdlambert ?

**Comment by antoniobergas** [comment]
I'm sorry but I'm not up to date on all the latest changes. Is there anything I should be aware of? 
About the tooltip we internally put it because we are in an early phase of adoption and people are still not 100% clear about what is an entity and the differences (thats why we point to documentation)

It's probably not necessary? At least for the first iteration?

**Comment by freben** [comment]
Sure grouping could work. I had some high hopes for https://github.com/backstage/backstage/pull/17474 to make things more easily (and consistently!) discernible, but haven't had the time to finish it off and get it past reviews yet

**Comment by antoniobergas** [comment]
![image](https://github.com/backstage/backstage/assets/26031467/e66fa307-87e3-4112-8155-0b7e2658d2e7)

I think I rather prefer this approach, as most of the times you dont have a huge naming in the components, so there's a lot of space to use on the right, instead of making bigger the card. 

But now it comes something to my head. There's already the catalog which groups owned entities and show you a table view.

Isn't there a bit of redundancy? Or the idea is to make it modular, so the user decide which info show? (I base this thought on the new modulable Home Page)

**Comment by adamdmharvey** [comment]
I too like smaller, more condensed view preferably with an icon as opposed to a card?  But any smaller, condensed visual indicator is good.

> But now it comes something to my head. There's already the catalog which groups owned entities and show you a table view.
> Isn't there a bit of redundancy? Or the idea is to make it modular, so the user decide which info show? (I base this thought on the new modulable Home Page)

Note this enhancement is regarding the starred entities card in the home plugin, not the owned ones or the ones in the catalog table listing.  So for example, I may have a few favorites, or templates, that I want to refer to often as a USER, but I may not OWN them. So I never see them unless I star them, and having them handy right when I login I've found is useful. Hope that makes sense?

**Comment by antoniobergas** [comment]
Yeah, make sense. So then as user how much info you will like to see? Just the kind? maybe the type also? Should be something you can choose maybe??

**Comment by adamdmharvey** [comment]
I like the first diagram you shared, TBH, but I *personally* like icons vs. badges?  So then what you show in your catalog view, with the little component kind icon shown next to the name?  Just having that SAME view in the home starred entities card.  This goes back to the concept that if there was a reusable component to "display the name and it's kind as an icon", we could use the same in both the catalog AND this card. (rather than something custom)

But that's just one person's opinion ;)

**Comment by antoniobergas** [comment]
Yeah I prefer also icon vs anything else. 

Not sure if its already defined in a RFC but also I think that represents entities with icons could be challenging.

If I remember correctly you can extend the entity model, which means that the default ones could not represent the custom modeling maybe?

Also every icon must be far recognizable and different enough from the rest.

From our experience we found sometimes difficult to understand and associate the model with your software/project models, probably even more to associate icons. 😅

As I said I rather prefer icons but looks more difficult to achieve 😜

**Comment by antoniobergas** [comment]
> Just to throw another option: would it make sense to use the `PeekAheadPopover`, examples here: https://backstage.io/storybook/?path=/story/catalog-peekaheadpopover--default and PR that added it here: #15014

Yeah that could work also at least to see more details. But still rather prefer something quick to see and far recognizable😜

**Comment by antoniobergas** [comment]
If it serves as data to make a decision, we internally have equipment, domains, systems and components with the same name.

More and more developers are starting to use the developer portal and we haven't had that problem since we put the label on.

**Comment by drodil** [comment]
> Note this enhancement is regarding the starred entities card in the home plugin, not the owned ones or the ones in the catalog table listing. 

This made me think, why not also do a card for the owned entities on the home page? That would be more useful for new users than the starred entities, as they have none, but might have some owned. 

Anyhow, the conversation here is bouncing to quite many different topics, could we agree on how the starred entity kinds should be rendered in the card? 😄

**Comment by antoniobergas** [comment]
Agree with the owned card 😋

So I think we all agree on show the kind (also thats what the feature ask for at first).

Then about the UI, we agree on make a first iteration with the colorful labels? I think that will be a faster first approach.

If yes then I could make a PR with the changes, only thing I will need to know probably its what properties need to be exposed (like for example the colors? Or maybe we can start with a plane color also instead of one per kind?)

**Comment by drodil** [comment]
@antoniobergas I think that could work as the first approach but I am afraid of using some custom colors since there can be quite a lot of theming done by the application developers. Either it should use some colors from the theme or then not at all. A plain chip could work as the first step IMO. But as @freben said, the grouping could also be an option. So not sure anymore 😆

**Comment by antoniobergas** [comment]
We are on he same about the colours, or we use a single plain color or if we use one per kind then should come from the theme and something very good defined.

Okey good! let's see whats the others opinion 😁

**Comment by freben** [comment]
Yeah colours are probably unfortunate for several reasons, including accessibility concerns for the colourblind. I wouldn't mind the grouping-with-titles solution while waiting for https://github.com/backstage/backstage/pull/17474

**Comment by antoniobergas** [comment]
Hey! I had some time to make a PR for this, #20121

**Comment by antoniobergas** [comment]
Hi everyone! After some suggestions from @emmaindal and @creecree10 we change the design to instead of just grouping, split them in tabs by kind.

![image](https://github.com/backstage/backstage/assets/26031467/76cb1fe1-7a6d-4527-b9d2-86155bdf488d)

What you think? This should cover the problem and be user friendly at the same time

Let us know your feedback!

**Comment by emmaindal** [comment]
Hello, closing this issue as https://github.com/backstage/backstage/pull/20121 is merged, feel free to open it again if you have more ideas! Thanks all and thanks @antoniobergas for contributing this!
