### ISSUE TITLE
🐛 Bug Report: resourceRef in RequirePermission

### ISSUE THREAD

**Issue by athifongoqa** [backstage/backstage#17328]
### 📜 Description

I am trying to add read permissions for a plugin and I am confused because in the [documentation](https://backstage.io/docs/permissions/plugin-authors/05-frontend-authorization) there is no mention of a resourceRef when using a RequirePermission component but it seems to require one. What exactly am I supposed to pass in?

### 👍 Expected behavior

I only pass in the permission to the RequirePermission component. 

### 👎 Actual Behavior with Screenshots

Just passing in entity info as the resourceRef:
![Screenshot 2023-04-12 at 09 12 43](https://user-images.githubusercontent.com/59336133/231381821-27d970e8-b81b-4063-81f5-7c4834c9931f.png)

Excluding the resourceRef param:
![Screenshot 2023-04-12 at 09 13 57](https://user-images.githubusercontent.com/59336133/231381829-98325901-f53a-4707-b46a-0f0334264f92.png)

RequirePermission props:
![Screenshot 2023-04-12 at 09 14 16](https://user-images.githubusercontent.com/59336133/231381834-58ceca1d-c28a-449e-b457-e9ed185dc5cf.png)

### 👟 Reproduction steps

1. [Setting up the example plugins](https://backstage.io/docs/permissions/plugin-authors/01-setup)
2. [Add basic permission check](https://backstage.io/docs/permissions/plugin-authors/02-adding-a-basic-permission-check)
3. [Use RequirePermission conditionally render a component](https://backstage.io/docs/permissions/plugin-authors/05-frontend-authorization#using-requirepermission)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I would be willing to work on it with someone else

**Comment by Rugvip** [comment]
I'm assuming that your custom `fluxWebReadPermission` is a `ResourcePermission`, i.e. it as a declared `resourceType`. There's more info about resource permissions over at https://backstage.io/docs/permissions/plugin-authors/03-adding-a-resource-permission-check.

Given that it seems to behave correctly, and you'll need to pass along a `resourceRef` so that the permission system has the context of which exact resource you want to try to read. Since it's a custom permission I don't know exactly what that ref would look like though.

Throwing in another test for the `RequirePermission` component as well in #17354, just to make sure we've covered that path.
