### ISSUE TITLE
`AnnotateScmSlugEntityProcessor` should also work for `Template`s

### ISSUE THREAD

**Issue by Pike** [backstage/backstage#17351]
### 📜 Description

I realized that the slugs from AnnotateScmSlugEntityProcessor are only added to Components.

### 👍 Expected behavior

I was expecting the slugs to also work for Templates

### 👎 Actual Behavior with Screenshots

It only works for Components, as can also be verified by https://github.com/backstage/backstage/blob/7deaa96b8e55e422e956ac39abc1aaa59c19474b/plugins/catalog-backend/src/modules/core/AnnotateScmSlugEntityProcessor.ts#L51.

### 👟 Reproduction steps

Use the AnnotateScmSlugEntityProcessor, and inspect the entities for Components from GH and Templates from GH

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Technically `Template` is outside of the core kinds; it's provided from the scaffolder plugin.

Could have put it in [the `ScaffolderEntitiesProcessor`](https://github.com/backstage/backstage/blob/54f741d1f0229f0b7026f485d48307a8cb33ba8f/plugins/scaffolder-backend/src/processor/ScaffolderEntitiesProcessor.ts) perhaps?

Or should we invert the logic in the `AnnotateScmSlugEntityProcessor` so that it either doesn't check the kind at all, or just excludes some well known kinds perhaps, such as Domain, System, Group and User?

What do you think would be best here?

**Comment by freben** [comment]
Yep that works too.

**Comment by Pike** [comment]
Created a PR for this.

**Comment by kuangp** [comment]
Implemented in https://github.com/backstage/backstage/pull/18918
