### ISSUE TITLE
🐛 Bug Report: create-app version

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#17590]
### 📜 Description

When installing `@backstage/create-app@latest`, the version number comes out as 0.5.0.  I would expect the version number to match the backstage version number from https://github.com/backstage/backstage/releases .

### 👍 Expected behavior

Version number should match the latest release at https://github.com/backstage/backstage/releases (i.e. 1.13.2)

### 👎 Actual Behavior with Screenshots

```
$ npx @backstage/create-app@latest
Need to install the following packages:
  @backstage/create-app@0.5.0
Ok to proceed? (y)
```

### 👟 Reproduction steps

```
npx @backstage/create-app@latest
```

### 📃 Provide the context for the Bug.

Whilst I understand the technicalities of how the create-app component can be versioned separately from the core product, `create-app` is the recommended entry point to people getting started with backstage, and it's quite confusing when it doesn't match the latest version in the documentation

It's also particularly surprising that it displays a 0.x (i.e. pre-release) version number when backstage itself no longer has a pre-release version number.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by benjdlambert** [comment]
I think that this is a good idea, I know we spoke about this amongst ourselves in @backstage/maintainers before, but I think that there is some things to think about. Theres a problem that arises when we want to make breaking changes to the `create-app` CLI. We'd need to explicitly call out that this package no longer adheres to semver and that we're free to break that at any time, and that it follows the Backstage Release version instead.

Any other comments from other @jhaals @Rugvip @freben?

**Comment by jhaals** [comment]
We discussed this amongst the maintainers and decided that it make sense to version `create-app` with the Backstage version and exclude it from the versioning policy 👍 

There are a few hoops to implement this as changesets is going to try to manage the create-app version so we would have to update it after changesets has triggered. We currently have some logic inside [prepare-release.js](https://github.com/backstage/backstage/blob/master/scripts/prepare-release.js) that currently always make sure that there is a bump for create-app. That's probably a good place to start in order to tweak the workflow.
