### ISSUE TITLE
🚀 Feature: Custom filters in default catalog page

### ISSUE THREAD

**Issue by JoseHervas** [backstage/backstage#17668]
### 🔖 Feature description

Currently the `DefaultCatalogPage` component accepts several props (`columns`, `actions`, `tableOptions`, etc...) which allows devs to customize the rendered `CatalogTable` without having to rewrite the whole `CatalogPage`. This is a really useful feature, and it would be great to somehow be able to do the same customization with the filters.

Right now [the recommended approach on the docs](https://backstage.io/docs/features/software-catalog/catalog-customization/) is to re-write the whole `CatalogPage` whenever you need to add a new filter. This solution works but, as stated on the same doc, it has a downside:

```
creating a copy [of the CatalogPage] does introduce a possibility of drifting out of date over time (...)
```

This downside is affordable if you're doing a lot of changes on the CatalogPage. But if you just want to add a very simple extra filter, it would be great if we could just pass it as a prop to `DefaultCatalogPage` the same way you can pass `columns`

### 🎤 Context

There's been [a long historical debate on Backstage](https://github.com/backstage/backstage/issues/8336) around the idea of customizing the components of the top-level pages that assemble them. 

At the same time, I've seen some devs asking to customize very basic things of the `DefaultCatalogPage` filters (for example: https://github.com/backstage/backstage/issues/8459, https://github.com/backstage/backstage/issues/17172, https://github.com/backstage/backstage/issues/16118, etc...), as well as other devs asking to access the `kind` filter events outside of the `CatalogPage` component.

All this kind of situations could be fixed by allowing devs to pass their own `filters` to `CatalogPage` 

I aknowledge that we have to be careful with the "props boom" effect, but this simple `filters` prop would fix a lot of multiple use-scases where the devs would need to copy-paste the whole `CatalogPage` just to make one tiny change. 

We started accepting props to customize the `CatalogTable` on `CatalogPage` here https://github.com/backstage/backstage/pull/10516

### ✌️ Possible Implementation

A possible implementation would be to replicate what we already have with the table props:

- The `CatalogPage` already accepts custom columns:
https://github.com/backstage/backstage/blob/ae172d461a30b0d6c14afca59b2e49b6f76c7be2/plugins/catalog/src/components/CatalogPage/DefaultCatalogPage.tsx#L59-L61

- The `CatalogPage` passes them to `CatalogTable`:
https://github.com/backstage/backstage/blob/ae172d461a30b0d6c14afca59b2e49b6f76c7be2/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L231-L233

Similarly, we could accept filters on the `CatalogPage`

```typescript
export function DefaultCatalogPage(props: DefaultCatalogPageProps) {
  const {
    columns,
    actions,
    initiallySelectedFilter = 'owned',
    initialKind = 'component',
    tableOptions = {},
    emptyContent,
    filters?,
  } = props;

  ...

  <EntityListProvider>
    <CatalogFilterLayout>
      <CatalogFilterLayout.Filters>
        {filters || defaultFilters}
      </CatalogFilterLayout.Filters>
    </CatalogFilterLayout>
    ...
  </EntityListProvider>

}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
@timbonicus spent a fair bit of effort to make the copy-paste as small and as unintrusive as possible. While I understand your angle here, it's still a matter of "just one more" (again) prop, and there'll be the inevitable debate and additions and tweaks because people want to sometimes replace, sometimes amend, sometimes prepend, sometimes just rearrange - and they want easy access to the default set of filters for that, so now there's an export for that too and interface evolution for those to worry about :)

It grows pretty quickly. And it also digs further into the code-only patterns, while we're trying to investigate what a world would look like where things are more config driven instead.

I think it's rather that we slightly regret some of the additions we've already made along these lines - but since wholesale "deep" component replacement / modding isn't yet really solved, we've taken some shortcuts. Hopefully we'll get those patterns settled in some future release, and accepting some mild inconvenience until then.
