### ISSUE TITLE
🚀 Feature: Provide the ability to hide/show the Feature Flags tab in User Settings

### ISSUE THREAD

**Issue by pisethdanh** [backstage/backstage#17726]
### 🔖 Feature description

Provide the ability to hide/show the Feature Flags tab in User Settings

### 🎤 Context

For our use-case, we would like to have control over which users are able to see and toggle feature flags.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by awanlin** [comment]
Thanks for logging this @pisethdanh, was going to log something similar. So you can control what tabs are available as per the instructions here: https://github.com/backstage/backstage/tree/master/plugins/user-settings#tabs (the Tabs heading under the Props heading)

But, if you want to control what users can see them by using the permission framework for example you'll run into an error. We tried to do this by wrapping the tab with the `RequirePermission` like this:

```tsx
<RequirePermission
      permission={someCustomPermission}
      errorPage={<></>}
    >
      <SettingsLayout.Route path="feature-flags" title="Feature Flags">
        <UserSettingsFeatureFlags />
      </SettingsLayout.Route>
    </RequirePermission>
```
    
We got the following error though once we ran the app and navigates to the settings area: Child of SettingsLayout must be an SettingsLayout.Route

**Note:** what I'm doing here would allow users to see all feature flags or no feature flags not see or not see specific feature flags

**Comment by awanlin** [comment]
Again, funny, we are doing the same thing. So when we hit that error we moved the `RequirePermission` just like you did. Now you can actually override the error page by providing the `RequirePermission` with an `errorPage` prop like this:

```tsx
<RequirePermission
      permission={someCustomPermission}
      errorPage={noPermissionPage}
    > 
        <UserSettingsFeatureFlags />
    </RequirePermission>
```

Now `noPermissionPage` is just an `InfoCard` with some helpful details for the user like if they need access who to contact and how but it can be whatever you want

**Comment by kallayj** [comment]
IMO this issue reflects that the out-of-the-box "Feature Flags" feature is half-baked -- it is stuck somewhere between what I believe is the industry standard meaning for Feature Flags, which is a feature release methodology, and a more generic user-configurable setting.

The ability to show the feature flags to specific users would make the feature usable in the industry-standard way: the feature could be released with the flag off by default, the validated by a limited set of users, and finally turned on for everyone and the feature flag removed.

Otherwise, Backstage's Feature Flags are a like an extensibility mechanism for what appears on the Settings page but limited to settings that can only be turned on or off, which seems like a strange limitation.
