### ISSUE TITLE
🐛 Bug Report: Namespace format rules mismatch between Code and Documentation

### ISSUE THREAD

**Issue by langeno** [backstage/backstage#17730]
### 📜 Description

Implementation behavior and documentation mismatch:
The test cases at https://github.com/backstage/backstage/blob/ec66834af30f3e0eb8ab1352d282eee5eec851da/packages/catalog-model/src/validation/KubernetesValidatorFunctions.test.ts explicitly test that a namespace containing '.' or '_' are invalid.

The documentation at https://backstage.io/docs/features/software-catalog/descriptor-format/#namespace-optional states that namespace follows the same format restrictions as name, which in turn states that names can contain any of '._-'.
(also the test cases for isValidObjectName confirm that a name indeed can contain these characters).

### 👍 Expected behavior

Test cases/implementation behavior and documentation should match.

### 👎 Actual Behavior with Screenshots

See description, screenshot of running system rejecting a namespace with '_'
![image](https://github.com/backstage/backstage/assets/128791938/675ba08f-9ae4-4ac9-9a3a-f3037bf0f4c8)

### 👟 Reproduction steps

1. Navigate to <your backstage URL>/catalog-import
2. Try to onboard a catalog-info.yaml file which has "namespace: namespace_with_underscore"
3. See error pop up
4. Read navigation at https://backstage.io/docs/features/software-catalog/descriptor-format/#namespace-optional and see that underscores in theory are allowed.

### 📃 Provide the context for the Bug.

I am unsure if the documentation or the source code is wrong.
If the documentation must be updated, I am willing to submit a PR.
If is is the code, I would first need to check how big the changes are, but likely also willing to submit a PR.

### 🖥️ Your Environment

As this is about a mismatch between documentation and code the output should be irrelevant.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
When designing this catalog file format, we obviously borrowed most of the k8s object format. The code follows what k8s does, which is to [limit it to the DNS-label compatible set of characters](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns), which indeed makes it so that only letters and dashes are allowed. So the docs are the one to update, would be happy for a contribution to that effect 🙏 

As a separate discussion, I'm feeling that this was probably unnecessarily strict in our context. We could probably have made this default more forgiving. But it's so easy to change to one's own needs, that maybe it's not worth changing the default at this point.

**Comment by langeno** [comment]
Merge request is open: https://github.com/backstage/backstage/pull/17770

**Comment by benjdlambert** [comment]
Closing as this is fixed in the aforementioned issue! :tada:"
