### ISSUE TITLE
🐛 Bug Report: invalid SearchBar and SearchModal styles 

### ISSUE THREAD

**Issue by ilya-kochetkov-cko** [backstage/backstage#17740]
### 📜 Description

Recent changes of Search components that were introduced in https://github.com/backstage/backstage/pull/16647 resulted in incorrect rendering of Search components that rely on the Custom style suggested in the storybook as can be seen in the storybook [here](https://backstage.io/storybook/?path=/story/plugins-home-templates--default-template), [here](https://backstage.io/storybook/?path=/story/plugins-home-components-searchbar--custom-styles), and [here if you toggle modal](https://backstage.io/storybook/?path=/story/plugins-search-searchmodal--custom-modal)
This makes going from 1.13.* to 1.14.* a bit problematic for anybody who relied on these styles. 

### 👍 Expected behavior

The custom style suggested by the storybook should have been adjusted accordingly to minimise the impact on the end users. Also given that the introduced change has a visible impact on the standard components, it'd be great to have some migration guide in the correspondent change report if possible

### 👎 Actual Behavior with Screenshots

Custom SearchBar is rendered incorrectly on HomePage after bumping Backstage to 1.14.0-next.0 and further

Screenshot from the storybook
![image](https://github.com/backstage/backstage/assets/52493287/2e793768-f2cc-45f1-866b-21eef4d7f307)

Screenshot from my instance's homepage, just in case (we try to stay as close to your styles as possible when displaying the standard components)
![image](https://github.com/backstage/backstage/assets/52493287/e816f6d2-4d8a-4cb0-aa81-358927fc7369)

The same applies to the custom search modal in the storybook
![image](https://github.com/backstage/backstage/assets/52493287/faa7c736-4b88-48d9-927e-d63bc85d76bd)

### 👟 Reproduction steps

1. Open the storybook [here](https://backstage.io/storybook/?path=/story/plugins-home-templates--default-template), [here](https://backstage.io/storybook/?path=/story/plugins-home-components-searchbar--custom-styles), and [here if you toggle modal](https://backstage.io/storybook/?path=/story/plugins-search-searchmodal--custom-modal)
2. See the incorrectly rendered component 

### 🖥️ Your Environment

Chrome 112

```
OS:   Windows_NT 10.0.22621 - win32/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.22.7-next.0 (installed)
backstage:  1.14.0-next.1

Dependencies:
  @backstage/app-defaults                          1.3.1-next.1
  @backstage/backend-app-api                       0.4.3-next.1
  @backstage/backend-common                        0.18.5-next.1
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.2-next.1
  @backstage/backend-tasks                         0.5.2-next.1
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.7-next.0
  @backstage/config-loader                         1.3.0-next.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.8.0-next.1
  @backstage/core-components                       0.13.1-next.0
  @backstage/core-plugin-api                       1.5.1
  @backstage/dev-utils                             1.0.15-next.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.13-next.1
  @backstage/integration                           1.4.5-next.0
  @backstage/plugin-api-docs                       0.9.3-next.1
  @backstage/plugin-app-backend                    0.3.45-next.1
  @backstage/plugin-auth-backend                   0.18.3-next.1
  @backstage/plugin-auth-node                      0.2.14-next.1
  @backstage/plugin-catalog-backend-module-github  0.2.8-next.1
  @backstage/plugin-catalog-backend-module-ldap    0.5.12-next.1
  @backstage/plugin-catalog-backend                1.9.1-next.1
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.30-next.1
  @backstage/plugin-catalog-node                   1.3.6-next.1
  @backstage/plugin-catalog-react                  1.6.0-next.1
  @backstage/plugin-catalog                        1.11.0-next.1
  @backstage/plugin-events-node                    0.2.6-next.1
  @backstage/plugin-github-actions                 0.5.18-next.1
  @backstage/plugin-search-backend                 1.3.1-next.1
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.6.0-next.1
  @backstage/plugin-search                         1.3.0-next.1
  @backstage/plugin-techdocs-addons-test-utils     1.0.13-next.1
  @backstage/plugin-techdocs-backend               1.6.2-next.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.13-next.1
  @backstage/plugin-techdocs-node                  1.7.1-next.1
  @backstage/plugin-techdocs-react                 1.1.6-next.0
  @backstage/plugin-techdocs                       1.6.2-next.1
  @backstage/plugin-user-settings                  0.7.3-next.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.1-next.1
  @backstage/theme                                 0.2.19
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
Ping @backstage/discoverability-maintainers 

Thanks for reporting!

**Comment by ilya-kochetkov-cko** [comment]
Hi, I have a slight addition to this issue. Last week we noticed that the search bar in TechDocs looked a bit weird after update to 0.14.0-next.v1. Something tells me there's a chance it's related to the change mentioned in the description.

Before
![image](https://github.com/backstage/backstage/assets/52493287/e7ad26e6-f098-4997-b4bb-d8fe6e44711b)

After
![image](https://github.com/backstage/backstage/assets/52493287/c94b1411-4962-43aa-832c-4277bbc70c5d)

You can see this in action on your demo page [here](https://demo.backstage.io/docs/default/component/backstage)

**Comment by luchillo17** [comment]
Hi there, starting to work on this, definitely an oversight on my side about custom styles for the search bar.

**Comment by luchillo17** [comment]
So far I can tell this is currently happening:

1. The issue stems from changing the `InputBase` for a `TextField`, while the base has little styles by default, the text field uses the input variants, it was ok as long as you use the default `SearchBar`, but since there's no way to disable the variant styles, the custom styles will need to override them.
2. The `MuiFormControl` added by the `TextField` has by default margin-top `16px` & bottom `8px`, in the default input it doesn't show because it blends with the background, but as soon as you wrap it in a Paper it shows.
3. The custom styles are being applied to the form control that wraps the `input`, while the `input` gets the outlined variant styles, I'll try and make the `styles` apply to the `input` instead of the MuiFormControl.

So far I see 2 ways to fix this:

1. Revert back to `InputBase` and manually replicate the outline variant styles, that way there will be no `MuiFormControl` to mess up the custom styles application & overriding the manual variant styles.
2. Remove the margins of the `MuiFormControl`, then make sure to apply the custom `root` styles to the input instead of the `TextField`'s `MuiFormControl` so anyone can override the styles properly, not sure how to do this since I have yet to understand the `root` classes and how those are passed down to the components.

This is how the storybook custom styles SearchBar would look if I manage to remove the margins and apply the custom `root` styles to the input, it does need some tweaks to the padding/margin on the sides though:

![2023-05-16_18h19_56](https://github.com/backstage/backstage/assets/9698639/d5634641-a987-40fd-960f-8844c99c8fc0)

@freben @ilya-kochetkov-cko Which of these 2 solutions should I go for?

**Comment by luchillo17** [comment]
Hmm there's something interesting in the StoryBook:

1. There's 2 sections for custom styles SearchBar, one is the [Search Plugin](https://backstage.io/storybook/?path=/story/plugins-search-searchbar--custom-styles) version and the other is the [Home Components](https://backstage.io/storybook/?path=/story/plugins-home-components-searchbar--custom-styles) version.
2. The plugin version does remove the outline properly using the `notchedOutline` class & applying on it the `borderStyle: none`, so the only issue with this example is the Form Control extra margin.
3. The HomePageSearchBar seems to be adding a custom border but not removing the `notchedOutline`, I'm thinking about removing that by default and rely on the custom border, which the dev can easily change it like before, the issue is that the way you customize the styles for the plugin version & HomePageSearchBar would differ...

**Comment by luchillo17** [comment]
@ilya-kochetkov-cko I've created a PR that fixes the margin on the `MuiFormControl` & updates the StoryBook stories to show how to remove the border properly.

**Comment by ilya-kochetkov-cko** [comment]
> @ilya-kochetkov-cko I've created a PR that fixes the margin on the `MuiFormControl` & updates the StoryBook stories to show how to remove the border properly, may need to update the changeset to reflect the change in the classes.

Hi, thank you very much for working on it 🙇  
I'll try to bump our version from 1.13.0 to 1.14.0-next.* once again when your changes are merged.

**Comment by luchillo17** [comment]
Created a new PR to address the custom SearchModal story in StoryBook as mentioned by @emmaindal in this [comment](https://github.com/backstage/backstage/pull/17856#pullrequestreview-1441188343):

https://github.com/backstage/backstage/pull/17960
