### ISSUE TITLE
🚀 Feature: shell into pods

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#18024]
### 🔖 Feature description

A new button on the Container card in the Pod drawer,

![exec_button](https://github.com/backstage/backstage/assets/22056320/86b9ac52-c963-4eb5-8628-5d993ac27c11)

which, when clicked, opens a modal dialog containing a working terminal emulator, connected to the container in question (indirectly) via the [`exec` subresource](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#exec), similar to the one in the Kubernetes Dashboard:

![k8s_dashboard_terminal](https://github.com/backstage/backstage/assets/22056320/7c0c44dc-36e0-46bb-8939-971778a413f9)

### 🎤 Context

So that a [Software Engineer](https://backstage.io/docs/overview/glossary#backstage-user-profiles) can debug/troubleshoot a service without dealing with the location or authentication strategies of the underlying cluster, and without leaving Backstage!

### ✌️ Possible Implementation

I have a lot of ideas here, but it might be easier to focus a discussion around concrete PRs. Mainly I'd expect to see:
* an in-browser terminal emulator
* a multiplexed (parallel streams for stdin/stdout/stderr) bidirectional streaming protocol between the browser and Backstage -- I've only genuinely considered WebSockets for this.
* a database table of websocket sessions to allow authentication and horizontal scaling of the backend. [This article](https://devcenter.heroku.com/articles/websocket-security#authentication-authorization) from Heroku is my standard reference justifying the need for this.
* a translation/tunneling layer in the backend to convert between the browser-friendly protocol and SPDY, which the kubernetes API uses. There's a lot of background to this, so I'll just mention kubernetes/kubernetes#7452 as the tip of the iceberg.

There are a number of "shell into pod" features in other OSS Kubernetes web apps, as well as closed-source commercial products.
* The Kubernetes Dashboard uses hterm for the emulator and SockJS for the wire protocol. This seems like a strong reference implementation; I mostly learned about it from the initial PR kubernetes/dashboard#1939.
* The OpenShift Console uses a dedicated [web terminal operator](https://cloud.redhat.com/blog/a-deeper-look-at-the-web-terminal-operator-1) and doesn't seem to be built from raw `exec`s, rather it is a full-featured solution with a dedicated tooling container, etc. Also see [this guide](https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/parksmap-rsh.html#remote_shell_session_to_container_using_webconsole).
* I've heard that the rancher UI does the same thing, but I haven't looked at the code.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by luchillo17** [comment]
It is worth noting the PR @jamieklassen mentions from the K8s Dashboard in the current implementation differs drastically from the PR, it has since updated to a recent angular version, dropped bower in favor of NPM, and moved from hterm to xterm.js.

About what it means for this issue, I'm having a hard time analyzing the Go server (know little to nothing of Go), but the client is easier to read now that is an updated Angular version, the bulk of the UI logic is in the [Shell](https://github.com/kubernetes/dashboard/tree/master/modules/web/src/shell) folder, specifically here:

- [setupConnection](https://github.com/kubernetes/dashboard/blob/master/modules/web/src/shell/component.ts#L177-L196) will construct a terminal session url, which as far as I can gather from code goes to the Go backend to create the shell session and returns an ID, which is then used to establish the socket with SockJS and it's event listeners, which are in charge of handling shell output messages being written in Xterm.
- [initTerm](https://github.com/kubernetes/dashboard/blob/master/modules/web/src/shell/component.ts#L137-L175) Initializes the XTerm.JS UI and event listeners, seems this bit has nothing to do with the K8s or socket stuff, so `setupConnection` would be the important method.

**Comment by jamieklassen** [comment]
Found some [docs](https://pkg.go.dev/k8s.io/apiserver/pkg/util/wsstream#pkg-constants) on the WebSocket subprotocols supported by the k8s API server
