### ISSUE TITLE
🐛 Bug Report: TS errors when running `tsc:full` with `@types/react` 17.0.58

### ISSUE THREAD

**Issue by mtlewis** [backstage/backstage#18039]
### 📜 Description

`yarn tsc:full` currently produces compilation errors inside Mui when the installed version of `@types/react` is 17.0.58. To work around this issue, upgrade to 17.0.60 (I suspect 17.0.59 will work too).

### 👍 Expected behavior

Since the [create-app package.json](https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/package.json.hbs#L41) resolves `@types/react` versions to `^17`, I'd expect any version compatible with that range to compile.

### 👎 Actual Behavior with Screenshots

With version `17.0.58`, compilation errors are produced. Here's an example error:

```
node_modules/@mui/base/useTabs/TabsProvider.d.ts:18:71 - error TS2694: Namespace 'React' has no exported member 'JSX'.

18 export default function TabsProvider(props: TabsProviderProps): React.JSX.Element;
```

### 👟 Reproduction steps

1. Scaffold a new Backstage instance
2. Ensure the version of @types/react installed is 17.0.58
3. Run `yarn tsc:full`

### 📃 Provide the context for the Bug.

It looks like this is caused by Mui depending on the JSX namespace introduced to @types/react in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64464. 

### 🖥️ Your Environment

Observed the issue in a Github actions build.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR! Would like to discuss options for fixing though. It seems like the simplest fix might be to update the resolution inside create-app to be more restrictive, but this won't help for existing instances. Perhaps worth also exploring whether it makes sense to open an upstream issue against Mui.

**Comment by Rugvip** [comment]
Potentially something to report to MUI, at least for the error you highlight in your example: https://github.com/mui/material-ui/blob/3cab2428c9ede4507c3040023aff31fd07eff76b/packages/mui-base/package.json#L44

That fix wouldn't help us because of the resolutions though. I think the way to go is to bump our resolution range to `^17.0.60` for `@react/types`. That'll at least make it visible for anyone keeping an eye on the upgrade helper, while the rest that run into this issue would hopefully find this issue or simply bump `@react/types` themselves. Don't think there's a lot else we can do here, no way to ship this to existing projects without manual intervention.
