### ISSUE TITLE
🚀 Feature: disable the "Retry runs" workflow option in GitHub Actions plugin

### ISSUE THREAD

**Issue by wanisfahmyDE** [backstage/backstage#18203]
### 🔖 Feature description

Hi there,
I am wondering if there is an option to disable or hide the "Retry runs" button While using `<EntityGithubActionsContent/>.`

### 🎤 Context

The problem is that at the moment any team can trigger the workflow from another team if they access their Component from the Catalog view, even they can't do this in GitHub

Here is a snippet of how the plugin is used:

import EntityGithubActionsContent from '@backstage/plugin-github-actions';
...
```TypeScript
  <EntityLayout.Route path="/github-actions" title="GitHub Actions">
            <EntityGithubActionsContent />
  </EntityLayout.Route>
```

### ✌️ Possible Implementation

an attribute maybe that can be optionally set in `<EntityGithubActionsContent enableActionsRerun = "false"/>.`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Interesting! The GitHub Actions plugin uses delegated user auth via OAuth from the frontend, so access should be the same as the user access in GitHub. When you say that they can trigger the workflow from another team, do you mean that they are able to successfully do so? Or just able to attempt but it leads to an error.

Either way we'd want to add some form of access check to only show that action if they have access to re-trigger builds. Although if it's the case that they actually are able to re-trigger them this might be a bit tricky to solve, since we'd need to replicate some form of access check on GitHub's side which we don't even really know if it would be desirable for all users.

**Comment by wanisfahmyDE** [comment]
Hey @Rugvip, testing this again actually worked as expected. Initial testing was false from my side, apologies.

If a user is not owning a given component, hitting the "retry run" button returns a 403 error in the console and a UI error message additionally, the workflows in GitHub are not triggered.

**Comment by Rugvip** [comment]
Alright, well in that case it's a bit more straightforward. If we can find a way to check upfront whether the user has access then it'd make sense to hide the retry button
