### ISSUE TITLE
🐛 Bug Report: Incremental Ingestion returning cursor in wrong type

### ISSUE THREAD

**Issue by jaeeunl** [backstage/backstage#18222]
### 📜 Description

This bug concerns [Incremental Ingestion plugin](https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-incremental-ingestion). If the type of `cursor` that you return  in `next` method is `object`, the parameter `cursor` comes back as `string` sometimes for the subsequent iterations. This seems to happen only when you use in-memory sqlite database.

### 👍 Expected behavior

Type of `cursor` that is given as a parameter for `next` should always be the same type as what you return in the first iteration, i.e. the type you define initially.

### 👎 Actual Behavior with Screenshots
`cursor` parameter comes back as `string` sometimes when it was returned as `object` in the previous iteration. This behavior is inconsistent and how exactly it happens seems to depend on the burst length. The screenshot shows the behavior when burst length is set to be 10 seconds.
<img width="549" alt="Screenshot 2023-06-12 at 5 34 17 PM" src="https://github.com/backstage/backstage/assets/5856835/a4172034-4e6a-4b02-b815-990d0b2e34ba">

### 👟 Reproduction steps

Follow the steps in this doc, and make the type of `cursor` `object`, the same as in the doc.

https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-incremental-ingestion#installation

### 📃 Provide the context for the Bug.

We want to implement Incremental Ingestion plugin to improve our database performance. We'd like to follow the pattern in the documentation and keep the `cursor` as `object`.

### 🖥️ Your Environment

```
OS:   Darwin 22.5.0 - darwin/arm64
node: v16.14.2
yarn: 1.22.15
cli:  0.22.6 (installed)
backstage:  1.13.2
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
@dekoding Are you around to have a look at this one?

I see that [it uses a JSON type column](https://github.com/backstage/backstage/blob/b8374d5d93b6edbff5290f85e5107ec09b3728ce/plugins/catalog-backend-module-incremental-ingestion/migrations/20221116073152_init.js#L118) in the database.

It [reads the rows as-is from knex](https://github.com/backstage/backstage/blob/b8374d5d93b6edbff5290f85e5107ec09b3728ce/plugins/catalog-backend-module-incremental-ingestion/src/database/IncrementalIngestionDatabaseManager.ts#L541) and [pass them through](https://github.com/backstage/backstage/blob/b8374d5d93b6edbff5290f85e5107ec09b3728ce/plugins/catalog-backend-module-incremental-ingestion/src/engine/IncrementalIngestionEngine.ts#L194) without any further action.

I wonder if it's the case that SQLite actually doesn't natively support JSON columns well, or alternatively that Knex handles them poorly with that driver, such that it returns a JSON serialized string of the data, rather than the actual data, only on SQLite.

**Comment by devonpaluso** [comment]
I found this as well. From my logging, it looks like when a burst is complete, the next burst starts with the cursor as a string. Using SQLite if relevant.

**Comment by Rugvip** [comment]
Wanted to make sure you'd seen this one too @taras

**Comment by taras** [comment]
@Rugvip thank you for pinging me. 

@jaeeunl are you using Postgres or SQLlite?

**Comment by freben** [comment]
Yeah a coercion would be needed. We do that in a few places already, like where for some reason counts sometimes [come out as strings](https://github.com/backstage/backstage/blob/85617f898d72d9ee19e672c2c3f90e2971e67e23/plugins/catalog-backend/src/service/DefaultEntitiesCatalog.ts#L695) or time columns [are communicated differently](https://github.com/backstage/backstage/blob/85617f898d72d9ee19e672c2c3f90e2971e67e23/plugins/catalog-backend/src/database/tables.ts#L40)...

**Comment by namco1992** [comment]
This bites us too. I think something like `typeof lastMark.cursor === "string" ? JSON.parse(lastMark.cursor) : lastMark.cursor;` works, WDYT?

Btw I think we should fix the `MarkRecord` type here too since it's not only a string:
https://github.com/backstage/backstage/blob/b8374d5d93b6edbff5290f85e5107ec09b3728ce/plugins/catalog-backend-module-incremental-ingestion/src/database/tables.ts#L88-L94

**Comment by dekoding** [comment]
Hey, sorry for not responding to this earlier, everyone. Life found a way... to block me at every turn.

Anyway, I went looking through my records, and I don't think we ever tested this with the in-memory sqlite DB. I tested it with Postgres, and couldn't reproduce the problem, so I'm sure that this is specific to sqlite.

If it's coming back as a string instead of the correct type, you should verify that the string is in fact the expected cursor, just stringified. If that's consistent, then coercing it into an object should be easy. If not... Bug report to knex or sqlite, maybe? It would depend on which one is at fault.

@namco1992 The `MarkRecord` type for cursors could potentially be replaced with `unknown`. When it comes out of the database - well, a Postgres database, anyway - it comes out as a string that just needs to be parsed into the appropriate object. If that's not the case with sqlite, what format does it come out as?
