### ISSUE TITLE
🐛 Bug Report: console errors while testing the page with Tech Radar

### ISSUE THREAD

**Issue by ypetrych** [backstage/backstage#18348]
### 📜 Description

If the appication is redirected to Tech Radar page by default then there are console.error messages while running initial test (App.test.tsx)

### 👍 Expected behavior

App.tsx file:
`const routes = (
  <FlatRoutes>
    <Route path="/" element={<Navigate to="tech-radar" />} />
    ....
    <Route
      path="/tech-radar"
      element={<TechRadarPage width={1500} height={800} />}
    />
   .....
  </FlatRoutes>
);`

Errors: 
`
 console.error
    Error: Uncaught [TypeError: textElem.current.getBBox is not a function]

`

### 👎 Actual Behavior with Screenshots

No console errors in such case

### 👟 Reproduction steps

1. Run App.test.tsx test

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
`getBBox` is not available in the JSDOM environment, so you will need to mock it yourself, for example like this:

https://github.com/backstage/backstage/blob/126e862ece05028ac0de4cff0b2fd9285131621a/plugins/explore/src/components/GroupsExplorerContent/GroupsDiagram.test.tsx#L29-L32

Seeing as this is something that is required due to changes in your own app we won't want to make any changes to the default template, so will close.
