### ISSUE TITLE
🐛 Bug Report: techdocs-cli 1.4.1 is broken likely due to unpinned dependencies

### ISSUE THREAD

**Issue by kunickiaj** [backstage/backstage#18403]
### 📜 Description

In our CI we're using techdocs-cli 1.4.1 and it started failing after the 1.15 backstage release (or within 24 hours of it).
Since we pin the version (`npx techdocs-cli@1.4.1`) I suspect there's a version constraint that is broken.

Updating to 1.4.3 of the techdocs-cli resolved the issue.

### 👍 Expected behavior

Still work even when newer versions are available.

### 👎 Actual Behavior with Screenshots

The generation of techdocs failed. Trace submitted below.

### 👟 Reproduction steps

Try to generate techdocs with `npx @techdocs/cli@1.4.1 ...`

### 📃 Provide the context for the Bug.

```
[2023-06-22T21:16:44Z] /usr/local/lib/node_modules/@techdocs/cli/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-common/dist/index.cjs.js:110
--
  | [2023-06-22T21:16:44Z] const redacter = backendAppApi.WinstonLogger.redacter();
  | [2023-06-22T21:16:44Z]                                              ^
  | [2023-06-22T21:16:44Z]
  | [2023-06-22T21:16:44Z] TypeError: Cannot read properties of undefined (reading 'redacter')
  | [2023-06-22T21:16:44Z]     at Object.<anonymous> (/usr/local/lib/node_modules/@techdocs/cli/node_modules/@backstage/backend-app-api/node_modules/@backstage/backend-common/dist/index.cjs.js:110:46)
  | [2023-06-22T21:16:44Z]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
  | [2023-06-22T21:16:44Z]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
  | [2023-06-22T21:16:44Z]     at Module.load (node:internal/modules/cjs/loader:1119:32)
  | [2023-06-22T21:16:44Z]     at Module._load (node:internal/modules/cjs/loader:960:12)
  | [2023-06-22T21:16:44Z]     at Module.require (node:internal/modules/cjs/loader:1143:19)
  | [2023-06-22T21:16:44Z]     at require (node:internal/modules/cjs/helpers:110:18)
  | [2023-06-22T21:16:44Z]     at Object.<anonymous> (/usr/local/lib/node_modules/@techdocs/cli/node_modules/@backstage/backend-app-api/dist/index.cjs.js:24:21)
  | [2023-06-22T21:16:44Z]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
  | [2023-06-22T21:16:44Z]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
  | [2023-06-22T21:16:44Z]
  | [2023-06-22T21:16:44Z] Node.js v18.16.1
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hmm well this is interesting - I'm guessing that this is due to some duplicate dependencies looking at the resolution path that it's using. I'd recommend using `yarn backstage-cli versions:bump` to de-duplicate these deps and upgrade to the latest version and see if that fixes the issues you're seeing?

**Comment by agentbellnorm** [comment]
@kunickiaj, I'm sorry to hear it broke for you. I guess it probably resolved to a new version of a dependency within a specified version range, introducing a bug/incompatibility.

I just tried running `npx @techdocs/cli@1.4.1 generate` and it did not break.

To have more deterministic execution with `npx` we'd have to stop using version ranges, and I think that's unlikely. I'm not sure about your setup, but I'd recommend installing the cli in the environment you use to generate docs (e.g. a docker image) rather than executing it with `npx`. This is what we internally at Spotify.

I'll close this issue as I don't see a clear action. Feel free to reopen if you have suggestions for actions or if I've misunderstood something!
