### ISSUE TITLE
🐛 Bug Report: TechDocs navigation does not work if Backstage is not in domain root

### ISSUE THREAD

**Issue by x3ro** [backstage/backstage#18441]
### 📜 Description

In our upgrade from v1.12 to v1.14, we noticed that TechDocs navigation stopped working in our staging environments, which have URLs like `https://staging.example.com/name-of-the-branch/`.

As far as we can tell, this is caused by the changes introduced in #16682. 

### 👍 Expected behavior

Given a TechDocs page with a link in the navigation sidebar such as `https://staging.example.com/name-of-feature-branch/docs/default/component/some-entity/this-is-a-subpage/`, the following should behave the same:

* Clicking on the link
* Right-click > Open link in new tab

Both of these should lead to the desired documentation page.

### 👎 Actual Behavior with Screenshots

Opening the link in a new tab works, because the underlying `href` is correct. Clicking on the link results in the browser navigating to

`https://staging.example.com/docs/default/component/some-entity/this-is-a-subpage/`

instead of

`https://staging.example.com/name-of-feature-branch/docs/default/component/some-entity/this-is-a-subpage/`

Note the missing `/name-of-feature-branch/` URL segment, which is part of the `app.baseURL`.

### 👟 Reproduction steps

1. Install Backstage so that it is served from a sub-directory and not from the domain root
2. Create a TechDocs page that has a navigation link
3. Click on the link

### 📃 Provide the context for the Bug.

I tried to show the problem in the following debugging session.

* In 1.12 the `fullPath` passed to `navigate` works as expected
* In 1.14 the path returned by `resolveUrlToRelative` is missing the sub-directory from the `app.baseURL`.

![CleanShot 2023-06-26 at 13 58 41@2x](https://github.com/backstage/backstage/assets/243719/baceaf5f-56d3-4fed-aa8b-fbfcce7f6b0e)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sennyeya** [comment]
Hey 👋 , I worked on the linked PR. Can you verify for me if you're using the stable version of React Router? https://backstage.io/docs/tutorials/react-router-stable-migration/#migration. 

Basically, what you're seeing is the expected state. We want to remove the base url from the routing URL as it causes a double routing issue, ie `localhost:7007/test/docs/default/component` -> `localhost:7007/test/test/docs/default/component`. You can see the test cases [here](https://github.com/backstage/backstage/pull/16682/files#diff-d3a60283caa6fd8e089b208b32dc6c7437d9420b9d730d026dcf1c094a544f97R38). We need to do this because React Router uses relative URLs within the app to route.
