### ISSUE TITLE
🚀 Feature: Review Possible support for `http2`

### ISSUE THREAD

**Issue by guigiani** [backstage/backstage#18454]
### 🔖 Feature description

Revisit possible support for `http2`.

### 🎤 Context

Based on this [thread](https://github.com/search?q=repo%3Abackstage%2Fbackstage+http2&type=issues) it was decided not to support `http2` since node did not supported it natively at that time. Perhaps now it supports on v20: https://github.com/nodejs/node/blob/32eb4921db2993b579bc801399038610c1edb5e8/lib/internal/http2/core.js#L3329, so I wonder if this is something already under Backstage's radar or is it still out of scope?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
I think that we can maybe revisit this ticket when v20 because LTS, which I think is scheduled towards the end of this year.

The issue that we would have though is that we would have v18 and v20 to support, and one can have http2 and one cannot, so it would need to built in a way that can support both.

**Comment by jslott2sigma** [comment]
@benjdlambert Is Backstage now only supporting node 20? If so, it would be good to revisit http2 support.
