### ISSUE TITLE
🐛 Bug Report: kubernetes plugin with serviceAccountToken no longer supported

### ISSUE THREAD

**Issue by cthtrifork** [backstage/backstage#18490]
### 📜 Description

Trying to use the following documentation:
https://backstage.io/docs/features/kubernetes/configuration/

`clusters.\*.serviceAccountToken` can not be retrieved by
```
kubectl -n <NAMESPACE> get secret $(kubectl -n <NAMESPACE> get sa <SERVICE_ACCOUNT_NAME> -o=json \
| jq -r '.secrets[0].name') -o=json \
| jq -r '.data["token"]' \
| base64 --decode
```

Change is documented here since Kubernetes v1.24:
https://kubernetes.io/docs/concepts/security/service-accounts/#get-a-token

```
[Service Account Token Secrets](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount) (not recommended): 
You can mount service account tokens as Kubernetes Secrets in Pods. These tokens don't expire and don't rotate. 
This method is not recommended, especially at scale, because of the risks associated with static, long-lived credentials. 
In Kubernetes v1.24 and later, the [LegacyServiceAccountTokenNoAutoGeneration feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features) prevents Kubernetes from automatically creating these tokens for ServiceAccounts. LegacyServiceAccountTokenNoAutoGeneration is enabled by default; in other words, Kubernetes does not create these tokens.
```

### 👍 Expected behavior

Being able to use kubernetes plugin without using a cloud specific approach

### 👎 Actual Behavior with Screenshots

No token can be retrieved

### 👟 Reproduction steps

Try set up a new backstage instance with kubernetes plugin

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by cthtrifork** [comment]
As minimum, I think the backstage documentation should be updated

**Comment by cthtrifork** [comment]
I think we should try and support:
[Token Volume Projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#serviceaccount-token-volume-projection) (also recommended): In Kubernetes v1.20 and later, use the Pod specification to tell the kubelet to add the service account token to the Pod as a projected volume. Projected tokens expire automatically, and the kubelet rotates the token before it expires.

**Comment by jamieklassen** [comment]
@cthtrifork FWIW the `oidc` authProvider is also not cloud-specific since all apiservers support [authenticating via OpenID Connect Tokens](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens), but I totally agree that we should still update the docs to give instructions that work for Kubernetes 1.24+ (i.e. using a [Service account token Secret](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets)).

Furthermore, you did spot an undocumented feature which was introduced in #9045 -- if you don't specify a `serviceAccountToken` and you are running Backstage "in-cluster", the service account associated to the running pod will be used. Perhaps it's time we document this too!
