### ISSUE TITLE
🚀 Feature: Implement MySQL database support

### ISSUE THREAD

**Issue by dalvarado** [backstage/backstage#18668]
### 🔖 Feature description

Implement MySQL support in Backstage

### 🎤 Context

At present, Backstage is compatible with two commercial databases, PostgreSQL and SQLite.  However, we require MySQL support in Backstage and its included plugins. Taking inspiration from a [previously-submitted issue](https://github.com/backstage/backstage/issues/6281) and a [PR](https://github.com/backstage/backstage/pull/13432) that added MySQL support in the Catalog plugin, we hope to continue that work to bring MySQL compatibility to Backstage. Since knex already supports MySQL as a backing store, these changes don’t require swapping out the existing DB abstraction layer.

### ✌️ Possible Implementation

As stated above, our planned strategy to extend MySQL support would be to follow the example of the PR that updated the Catalog plugin. We plan to run Backstage against an instance of MySQL and rely on tests, the startup sequence, and its migrations to discover and fix any errors related to how the knex library is used to interact with the database.  This includes adding MySQL as a testing option to the corresponding tests for the changed files and possibly to any database related tests.
We have started making changes following the proposed strategy and these are the affected packages and plugins we have made changes to so far:

- Packages

> - Backend

- Plugins

> - App (backend)
> - Catalog
> - Code Coverage
> - Linguist
> - Tech Insights
> 

Examples changes we’ve made:
Migrations:
Certain data types that are used to define columns will have to change to make them MySQL compatible, because of the need to have a size specified (string has implicit size of 255 chars): 
```js
- table.text('value').nullable().alter();
+ table.string('value').nullable().alter();
```

Plugins:
Format for date and time types and database specific functions in raw SQL will have to be accounted for as well.  MySQL needs YYYY-MM-DD hh:mm:ss.s’ while Postgresql and sqlite need ‘YYYY-MM-DDThh:mm:ss.sZ’:
```js
if (this.knex.client.config.client.includes('sqlite3')) {
    startAt = this.knex.raw('datetime(?)', [time.toISO()]);
} else if (this.knex.client.config.client.includes('mysql')) {
    startAt = this.knex.raw(`?`, [time.toSQL({ includeOffset: false })]);
} else {
    startAt = this.knex.raw(`?`, [time.toISO()]);
}
```

If there are any associated tests for the affected files, they may need to be updated to include MySql as a test database:.
   ```js
- ids: ['POSTGRES_13', 'POSTGRES_9', 'SQLITE_3']
+ ids: ['MYSQL_8', 'POSTGRES_13', 'POSTGRES_9', 'SQLITE_3']
```

### Questions
In order to cover all our bases before submitting a PR for our proposal, we were hoping to get some information regarding the the following questions:

- The above package and plugins that have been affected by the changes were due to fixing errors encountered during the start-up process.  However, there are more plugins that interface with the database (they have migrations) that haven’t required any changes to make them compatible with MySQL.  If these plugins have tests that already include MySQL as one of their testing databases, is it safe to assume that they are ready to go, or is there additional scope that we are not aware of?

> These are plugins:

> - Auth
> - Badges
> - Bazaar
> - Entity Feedback
> - Playlist
> - Scaffolder
> - Search

- The “backend-task” package had some changes that were required for MySQL support, along with a test that needed to have MySQL to be added to a list of test databases.  Are there any other “backend” packages that should be in scope for this project, for example “backend-common”?

- Are there any implications that we should be aware of with duplicating the Postgresql end-to-end test Github action?

- For integration (Cypress) tests, we noticed that these tests live in the top-level Cypress directory for plugins, but within local “cypress” directories for packages, we just wanted to verify that this is indeed the pattern we should follow if we add any integration tests.

- Not every plugin or package has an integration spec that tests them, can it be assumed that if there is no existing integration test for a changed plugin / package, we don’t have to add one?

- Are there any integration tests outside the Backstage repo?

Please let us know if you have any feedback on our plan, additional scope that we missed, or suggestions to help us with this effort. Thanks!

Apologies, as stated in the "Context" section, we did find [Issue 6281](https://github.com/backstage/backstage/issues/6281) asking for community help to add additional DB support to Backstage, but it had gone stale and was eventually closed.  So we decided to create this new one.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by waldirmontoya25** [comment]
cc @Rugvip @freben @jamieklassen

**Comment by freben** [comment]
Hi, some quick responses here. Overall, cool that you are looking into this, but also, we've been a bit hesitant to add more engines officially supported, since it turns out that the burden is actually pretty significant as that number increases. Knex helps, but there are some much more subtle and tricky things to navigate.

> Since knex already supports MySQL as a backing store, these changes don’t require swapping out the existing DB abstraction layer.

No, but as you've seen, in practice things are pretty complex and the capability differences of these engines can't really be hidden by that abstraction layer. So in some cases, it's been tempting to consider making an adapter layer _inside_ some plugins to get away from all of these `if` statements all over the place that do slightly different things depending on the engine. Haven't gone there yet ... but the thought has occurred to us.

> Examples changes we’ve made: Migrations: Certain data types that are used to define columns will have to change to make them MySQL compatible, because of the need to have a size specified (string has implicit size of 255 chars):
> 
> ```js
> - table.text('value').nullable().alter();
> + table.string('value').nullable().alter();
> ```

For text columns, it [seems to work](https://github.com/backstage/backstage/blob/23347b795f8915970597b4da2f0d3c52618c1e28/plugins/auth-backend/migrations/20230428155633_sessions.js#L31) to use the two-argument form of `.text` to supply an explicit column width.

`.text('the_column_name', 'longtext')`

You still need to be careful not to use these for indexing, of course, since you'll hit database limits.

> Plugins: Format for date and time types and database specific functions in raw SQL will have to be accounted for as well. MySQL needs YYYY-MM-DD hh:mm:ss.s’ while Postgresql and sqlite need ‘YYYY-MM-DDThh:mm:ss.sZ’:
> 
> ```js
> if (this.knex.client.config.client.includes('sqlite3')) {
>     startAt = this.knex.raw('datetime(?)', [time.toISO()]);
> } else if (this.knex.client.config.client.includes('mysql')) {
>     startAt = this.knex.raw(`?`, [time.toSQL({ includeOffset: false })]);
> } else {
>     startAt = this.knex.raw(`?`, [time.toISO()]);
> }
> ```

Same thing goes for computing time deltas.

```ts
const nextUpdateAt = (refreshInterval: number) => {
  if (tx.client.config.client.includes('sqlite3')) {
    return tx.raw(`datetime('now', ?)`, [`${refreshInterval} seconds`]);
  } 
  if (tx.client.config.client.includes('mysql')) {
    return tx.raw(`now() + interval ${refreshInterval} second`);
  }
  return tx.raw(`now() + interval '${refreshInterval} seconds'`);
};
```

> * The above package and plugins that have been affected by the changes were due to fixing errors encountered during the start-up process.  However, there are more plugins that interface with the database (they have migrations) that haven’t required any changes to make them compatible with MySQL.  If these plugins have tests that already include MySQL as one of their testing databases, is it safe to assume that they are ready to go, or is there additional scope that we are not aware of?

I think there are no guarantees whatsoever anywhere, unfortunately. Since MySQL has never been an officially fully supported database, we may have added some spot checks here and there but they can't be seen as reliably battle tested etc, in particular since none of the maintainers have any active usage of MySQL in production at all. There will surely be a lot of code that happens to work, but it needs to be checked and maybe tests need to be amended in some cases, to ensure that all paths are exercised.

> * The “backend-task” package had some changes that were required for MySQL support, along with a test that needed to have MySQL to be added to a list of test databases.  Are there any other “backend” packages that should be in scope for this project, for example “backend-common”?

`backend-common` for sure. That's where all of the central database connection setup code lives, for example. I would have said `backend-app-api` too, but that one currently just leverages the old `backend-common` for all database related code I believe.

> * Are there any implications that we should be aware of with duplicating the Postgresql end-to-end test Github action?

Hm. Nothing that springs to mind spontaneously 🤔 

> * For integration (Cypress) tests, we noticed that these tests live in the top-level Cypress directory for plugins, but within local “cypress” directories for packages, we just wanted to verify that this is indeed the pattern we should follow if we add any integration tests.

Will you be using cypress for backend database related testing too?

> * Not every plugin or package has an integration spec that tests them, can it be assumed that if there is no existing integration test for a changed plugin / package, we don’t have to add one?

If it's needed to get confidence in the MySQL work's correctness both now and over time as more development happens in these plugins and packages - then having them probably is a good thing.

> * Are there any integration tests outside the Backstage repo?

Not really.

**Comment by Rugvip** [comment]
Just wanna highlight that we only use Cypress for frontend integration tests and whatever backend features you may reach via that. For backend integration-like tests we still use Jest, see for example https://github.com/backstage/backstage/blob/e3f5d95a4cd95cb53073e8fda9b7025c66974aac/plugins/catalog-backend/src/tests/integration.test.ts#L360

**Comment by Rugvip** [comment]
@jamieklassen I think "officially supported" most often translates to "maintained by the owners". There's a bit more nuance here though, since a Backstage backend plugin **can** support MySQL, but it **must** support Postgres. It is effectively a requirement from the core framework that anyone maintaining a Backstage backend plugin that uses the database service for persistent storage should support Postgres. So in that sense it's perhaps most accurate to say that there is an "official requirement to support" Postgres.

Regarding CVEs we (core maintainers) care about them regardless of the level of support or owner. If there's a CVE affecting the main repo we aim to have it fixed, with higher severity and broader usage receiving higher priority.

**Comment by freben** [comment]
Unstaling, but just noting here that MySQL still remains at a best-effort, community-contributed, support level.
