### ISSUE TITLE
🚀 Feature: Customize API page 

### ISSUE THREAD

**Issue by prasoon-pxc** [backstage/backstage#18700]
### 🔖 Feature description

Customize main API page of backstage in a way that we can show column like: Version-No., Last updated(date-time) and a cloumn for URL/PATH.

### 🎤 Context

It will help in filtering APIs based on version number or URL/PATH

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by efenner-cambia** [comment]
This seems like the sort of thing that you would be able to create a custom plugin for and then embed that plugin in the API page of your deployment

**Comment by prasoon-pxc** [comment]
Thanks @efenner-cambia for your reply, but honestly I do not have any idea how can I create plugin for it.

**Comment by freben** [comment]
Firstly, your app's `App.tsx` file will contain the route entry itself, [like this](https://github.com/backstage/backstage/blob/ef4379c55a1d727f6c1fe8486b653150b968253c/packages/app/src/App.tsx#L276). You can choose to render anything there instead of the default `ApiExplorerPage`, if you want to replace it wholesale.

But the `ApiExplorerPage` happens to be a bit customizable in and of itself. It [has a `columns` prop](https://github.com/backstage/backstage/blob/ef4379c55a1d727f6c1fe8486b653150b968253c/plugins/api-docs/src/components/ApiExplorerPage/DefaultApiExplorerPage.tsx#L57) that lets you define the set of columns yourself. You can see a few lines higher up how the default columns are made.

**Comment by freben** [comment]
Relatedly, [this page](https://backstage.io/docs/features/software-catalog/catalog-customization) describes how a custom catalog page can be made, and the API docs landing page is basically a catalog page with some specializations, so the examples there partially apply.

**Comment by prasoon-pxc** [comment]
Thanks @freben , I will check and let you know.
