### ISSUE TITLE
🚀 Feature: Graceful rate limit handling in scaffolder

### ISSUE THREAD

**Issue by Andrei-Predoiu** [backstage/backstage#18866]
### 🔖 Feature description

Add functionality in scaffolder to handle rate limiting when interacting with SCM providers(github, bitbucket etc).

### 🎤 Context

Rate limiting is a common topic among backstage adopters and usually, there are several issues, especially related to secondary rate limits. 
There are many things that organizations can do to mitigate the issue. In my opinion adding rate limit handling or throttling are last resorts when everything else has been exhausted.

That being said, there are situations, like scaffolder, where failing to create a repo or commit or PR can put developers in a situation from which they cannot recover without help from SCM admins.

### ✌️ Possible Implementation

Implement a common a loop backoff mechanism that can be added to the api-clients where rate-limiting should be handled.
This mechanism will only retry when detecting rate limiting.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
This is a complex subject and it's for sure come up a few times. It's often in the context of the catalog which is more automatedly aggressive overall, but I agree that in the scaffolder which is more single-issue and user-triggered, it might make sense to make targeted efforts.

Overall, I think we're open to suggestions here. We've not had the time to look into how to best achieve this, but if you are able to dig into it and find a good solution (if even for one of many providers), we'll be glad to hear of it! 🙏

**Comment by codesandtags** [comment]
Hi @Andrei-Predoiu @freben  I'm having the same situation as an adopter at the company where I'm working.

The first approach we were using, was trying to have a `distributed catalog`, but we realized it generates tons and tons of request to our Version Control System API, so it generated some performance issues. 

The second approach we are trying to have is: `Having a centralized catalog` and grouping entities in fewer files to reduce network request.

I don't have many details about other approaches or solutions, but by managing the lifecycle or rules to update some entities that would be useful to handle this issue.

**Comment by Andrei-Predoiu** [comment]
Hi, scaffolder fails due to other backend traffic or sue to traffic caused by scaffolder itself hitting secondary rate limits

**Comment by taras** [comment]
Do you know under what conditions the scaffolder can create enough traffic to hit secondary rate limits?

**Comment by taras** [comment]
@codesandtags are you using the same credentials for ingestion and scaffolder in tests?

**Comment by codesandtags** [comment]
Hey @taras  and @Andrei-Predoiu , 

I'm going to give you a little more of context about my situation:

## Overview
1.  `Size of catalog` = ~10,000 entities (for now, because we have probably 8,000 active repositories). This entities include (group, users, systems, domains, components, apis, tech-docs)
2. `Version Control System API`: Bitbucket Server 7
3. `BitbucketDiscovery`: Right now is disabled, we were using it but it created too much request to our big VCS.
 

## Process
1. We have several instances deployed.
  - Oficial instance for internal community 
  - Instances for testing
  - Instances for specific onboardings
2. We have several teams working with those instances, and we have trunk based model.
3. We are using a `Service Account` which uses an `Access Token` and it's shared by the instances.

## Problem
1. We started to notice pretty bad high performance issues consuming the VSC, and affecting other users.
2. After investigation we realized that Backstage were making up to `63 request per second` 🤯

## Approach for now until a solution
1. We turned off many of those instances running.
2. Bitbucket Server API now has a rate-limiting rule enable
3. Once these rate-limit is reached, it starts generating too many `429 Too Many Request` Error. (Similar to other issues related to this topic in Gibhub for Backstage)
4. We are grouping distribute catalogs into bigger files to reduce the amount of request to Backstage (it has shown significantly performance)
5. Our Backstage entities are being centralized now in a set of repos.
6. This week we will keep reviewing in more details this issue.
7. We have pending to split up the Services Account to differentiate the instances.

## Concerns
- How to handle recurrent requests when our catalog have more than 20,000 or 50,000 entities mapping our ecosystem.
- How will be the performance for our catalog when we start adding our planned plugins.

## Possible solutions
- Modify how works the Scaffolder logic function to implement additional rules. PENDING TO VALIDATE
- Add a proxy between Backstage and Bitbucket Server API, to cache some information and avoid the `429 Too May Errors`. PENDING TO VALIDATE

I hope these points, help to create a better big picture about the issue.

**Comment by taras** [comment]
@codesandtags I realize that it's not the desired state, but I just want to make sure I understand - are you getting rate limiting errors when running scaffolder with discovery disabled?

**Comment by codesandtags** [comment]
@taras Yes I do. But probably it's because of the multiple instances sharing the same `Access Token`, which at the end represents more requests than the rate-limiting rule setup. For further references, I think this link can help to many people working with `Bitbucket Server`

https://confluence.atlassian.com/bitbucketserver/improving-instance-stability-with-rate-limiting-976171954.html

**Comment by taras** [comment]
Atlassian rate limiting scheme is real something. It sounds that requests to Atlassian need to be throttled to refill rate. Do you know if there is a way to get refill rate from the headers?

**Comment by codesandtags** [comment]
That's what I was thinking, but given I don't have the control to throttle the request to refill the tokens available, my first approach is to group the entities, and turn off instances sharing the same `Access Token`, to avoid duplicated request. According to Bitbucket Server rate-limiting the refill occurs every second, adding 5 tokens.

---

## How rate limiting works

Rate limiting targets HTTP requests with basic or bearer authentication (such as REST API requests). It operates using the token bucket algorithm. When it’s turned on:

- Each user is given a ‘token bucket’ containing the maximum number of tokens they can hold (this is their token bucket size).
- Every time they make an HTTP request one token is taken out of their bucket.
- New tokens are added into their bucket at a constant rate until it is full (this is their token bucket refill rate) If their bucket is empty, they cannot make requests.

## How to turn on rate limiting

You need to be a System Admin or Admin to turn on rate limiting. The first time you do this you’ll see default values for:

- Token bucket size - This is the number of tokens that are available to a user. It determines the maximum number of requests they can send in a burst. By default, `this is set to 60`
- Token bucket refill rate - This is the number of tokens added to a user’s bucket per second. It determines their throughput. By default, `this is set to 5`

**Comment by codesandtags** [comment]
Hi @taras  today I'm doing a test setting up the  setProcessingIntervalSeconds however as you mention, this is not the final solution, it only adds a longer interval, but at the same time, the bulk of requests will be the same.

```ts
// catalog.ts
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  builder.setProcessingIntervalSeconds(300); // Time in seconds

  const { processingEngine, router } = await builder.build();

  await processingEngine.start();
  return router;
}
```

For now,  the approach of  `removing Backstage instances`  sharing the same `access token` is working, and also grouping the entities in less files,  because it reduce the amount of requests made by the same user. ✅ 

I'll perform more test playing with the `catalog.ts` and the `event-based approach` shared by @awanlin 

https://backstage.io/docs/integrations/bitbucketCloud/discovery/#installation-with-events-support

I'll back to you soon guys, after my tests.

**Comment by rmartine-ias** [comment]
re:
> [Once these rate-limit is reached, it starts generating too many 429 Too Many Request Error. (Similar to other issues related to this topic in GitHub for Backstage)](https://github.com/backstage/backstage/issues/18866#issuecomment-1678200589)

Linking https://github.com/backstage/backstage/issues/17188 (Bug Report: `publish:github:pull-request` fails with `HttpError: You have exceeded a secondary rate limit`) for context.

**Comment by Andrei-Predoiu** [comment]
@benjdlambert >we would recommend using the users auth token when scaffolding 

We blocked users from being able to create repos outside of backstage so we can't use their access tokens.

**Comment by benjdlambert** [comment]
@Andrei-Predoiu would it be possible to generate a new token for the scaffolder especially then, and then deploy the scaffolder separately with a different token?

**Comment by codesandtags** [comment]
@kmatyukhin Please could you provide me an example about your implementation?

**Comment by kmatyukhin** [comment]
Hi @codesandtags! You can familiarize with proposed solution in my declined PR #18096. BTW it doesn't cover Scaffolder fetches but the idea is the same.

**Comment by codesandtags** [comment]
https://github.com/backstage/backstage/assets/5404833/5ea86fc2-357f-479a-a68b-791a5abe0ae9

<img width="879" alt="image" src="https://github.com/backstage/backstage/assets/5404833/8e143982-c3c6-45b5-b7f9-d6518fdddee3">

<img width="787" alt="backstage-approaches" src="https://github.com/backstage/backstage/assets/5404833/7204c27e-ad48-4e0e-a1f0-555bb87c374c">

Hey guys! Just to give an update about the topic related to the `429 - Too Many Request` I have several insights. 

1. Having a centralized is NOT a good idea if we have Locations.
2. To handle the `Too Many Request` is better to leverage on a custom strategy to throttle
3. NEVER use the same `Access Token` on other Backstage instances (if you have them), because it duplicates the amount of request for your user, generating `rate limit exceeded`
4. From the very beginning define a strategy to scale your catalog, it takes time to understand the best strategy, but it may help you to avoid issues later.

**Comment by Andrei-Predoiu** [comment]
I think the thread got sidetracked a little bit. The catalog crawler model discussion is another topic.
I am proposing implementing checks and retries in the ***template  engine*** that detects timeouts to the various SCM services and handles it gracefully. 
The goal is to eliminate half templated, broken repos.

**Comment by kmatyukhin** [comment]
@Andrei-Predoiu in our organization we've implemented pRetry approach patching integrations package so every call from catalog provider, processor or scaffolder is repeated with exponential back-off time according to p-retry options and as I said before it is working pretty well for us.

**Comment by Andrei-Predoiu** [comment]
@kmatyukhin I'd love to see how you solved this by implementing your own integrations package. 

As far as i can tell you'd have to put the checks in places like these:
`plugins/scaffolder-backend/src/scaffolder/actions/builtin/github`
`plugins/catalog-backend-module-github/src/processors`

**Comment by pedronastasi** [comment]
At expedia group, we encountered this issue as it was provoking a memory leak... Has it happened to any other team?. the memory leak?

**Comment by pedronastasi** [comment]
Here's you've more info about the leak https://github.com/backstage/backstage/issues/17188#issuecomment-1695696241

**Comment by Lowballs** [comment]
I am receiving rate limit exceeded 403 issues with Github apps also. We probably only have around 700 entities in our environment. We have 3 environments for which I've created an individual app for each. 

I'm not savvy enough in this space to correct it. For such a small (seemingly) amount of entries. Also, why does the catalog look for commits? Is that due to wildcard catalog entries?
