### ISSUE TITLE
Support "SAML" and/or "OpenID Connect" with OKTA Integration

### ISSUE THREAD

**Issue by YToutah993** [backstage/backstage#1891]
## Feature Suggestion

While I was trying to onBoard Backstage to our OKTA platform, I was asked to provide the protocol/method .. and I have only 2 options; either `SAML` or `OpenID Connect`. So, it would be nice to consider these options (especially the `SAML` one).

**Comment by jibone** [comment]
Hey, I'm trying to implement SAML login for backstage as our organization's identity provider supports SAML. I've submited a PR (still WIP) #2284 :)

**Comment by adamdmharvey** [comment]
Based on #2284 for SAML and https://github.com/backstage/backstage/pull/3309 for OpenID, and even Okta in https://github.com/backstage/backstage/pull/1455, I think the ask in this issue is covered. Those methods are available auth providers for backstage.

![image](https://user-images.githubusercontent.com/33203301/107309463-7a82f080-6a58-11eb-89f3-9bd00ab7dfb3.png)

Closing!
