### ISSUE TITLE
🚀 Feature: Upgrade to Storybook v7 (to fix security vulnerabilities in Webpack 4)

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#18942]
### 🔖 Feature description

The Backstage Storybook is currently on Storybook v6.  This version added Webpack 5 support, but kept Webpack 4 to maintain backwards compatibility.  Although the project storybook is built with Webpack 5, the core Storybook dependency package includes multiple bundled dependencies supporting Webpack 4 which cannot be removed without upgrading to Storybook v7.

Because of this, the mono repo reports that it is "exposed" to multiple security vulnerabilities which cannot be otherwise patched. (because they are transitive dependencies of Webpack 4)  Two of them have been in the wild for ~2 years.

(For maintainers: https://github.com/backstage/backstage/security/dependabot?q=is%3Aopen+manifest%3Astorybook%2Fyarn.lock )

This is a request that we upgrade the Storybook to v7, which would potentially gain some small features, but more importantly due to Backstage being a monorepo, it would better report from a security perspective the proper state of the project.

### 🎤 Context

https://github.com/storybookjs/storybook/discussions/21040

### ✌️ Possible Implementation

Following the implementation guide here:

https://storybook.js.org/docs/react/migration-guide

Much of it is automated (scripts you can run locally), but some of the Backstage Storybook config was customized and will either need to be re-customized or refactored to support the new version. In addition there seems to be one small plugin which may need to be re-written.

Testing the storybook is quite straight forward locally: in the storybook folder, you simply `yarn install` and then `yarn start`!  Then you try the upgrade, until it will properly start again.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by gashcrumb** [comment]
Hey @adamdmharvey  I ran into the same issue on your branch (as expected), then decided to start the process from start with the idea of just trying to keep most of the config as-is.  I got this to a working build and storybook runs but interestingly enough I find I hit the same hook error on every story, which appears to be actually due to [this line of code](https://github.com/backstage/backstage/blob/master/packages/core-app-api/src/apis/system/ApiProvider.tsx#L44) since `TestApiProvider` is loaded in the decorator used for every story.  Here's what I see in the console:

![image](https://github.com/backstage/backstage/assets/351660/b5a87d5e-1b10-4918-8db2-75afe5a4fb33)

So I suspect this line of code spreading the props needs to first be moved after the hook call, but I wonder if there's more cases of this that'll show up.

**Comment by gashcrumb** [comment]
Yup, a bit of digging and it [looks like the 7.x upgrade enables `use strict`](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#add-strict-mode) which then also enables these kinds of checks.  I can see how feasible the workaround given is, but this upgrade could require some refactoring of the codebase potentially to sort these out-of-order hook calls.

**Comment by gashcrumb** [comment]
I haven't had luck working around this.  This [setting doesn't seem to make a difference](https://storybook.js.org/docs/react/configure/frameworks#configure) here, and [this discussion](https://github.com/storybookjs/storybook/issues/20198#issuecomment-1359269018) seems to imply there's cases where it can't be turned off.

**Comment by efenner-cambia** [comment]
This still seems important

**Comment by vinzscam** [comment]
Closed by #27124.
