### ISSUE TITLE
🚀 Feature: Custom ruleset for entity validation

### ISSUE THREAD

**Issue by julianEbenhoferDyna** [backstage/backstage#19316]
### 🔖 Feature description

Add the possibility to define a custom ruleset for the entity validation plugin which will be checked additionally.

### 🎤 Context

At the moment the entity validation plugin only checks whether the syntax is valid. I think it would be a great addition to be able to add custom rules that will be checked additionally. Specifically every backstage instance should be able to have custom rules.

Examples: 
- type of owner needs to be a group
- a description must be set
- each system must have a domain as parent
- etc.

### ✌️ Possible Implementation

The ruleset should be defined in `app-config.yaml`.  Moreover, the implementation should be generic and easy to upgrade.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Do you mean the catalog backend plugin itself or something different? In case of the catalog backend you can define your own validation logic through custom processors, see [this](https://backstage.io/docs/features/software-catalog/extending-the-model#changing-the-validation-rules-for-the-entity-envelope-or-metadata-fields) and below as well as [this](https://backstage.io/docs/features/software-catalog/extending-the-model/#implementing-custom-model-extensions). Since #14898 all these validators will run as well, not just the first one the matches.
