### ISSUE TITLE
🐛 Bug Report: techdocs navigation bar & toc not hiding

### ISSUE THREAD

**Issue by panditha** [backstage/backstage#19324]
### 📜 Description

As per mkdocs documentation when we put following metadata content in a markdown page then that page should not show navigation bar (left side) and table of content bar (right side). 

```yaml
---
hide:
  - navigation
  - toc
---
```

But currently the side bars are still occupying their spaces though content within them is not displayed. Below is a screenshot of the issue.

![image](https://github.com/backstage/backstage/assets/1615122/f8be7850-d1aa-47a4-92aa-0a727dd69eeb)

### 👍 Expected behavior

The left and right side navigation bars should be hidden and content area should occupy 100% of the page width.

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/1615122/53f6fdd7-32ad-4390-8958-13b14275cb2a)

### 👟 Reproduction steps

---
hide:
  - navigation
  - toc
---

Paste above in index.md file and open it. We still see content not occupying full 100% width of the page.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by adamdmharvey** [comment]
(added a code fence around your YAML front matter example; otherwise it was being displayed as content in this issue :) )

**Comment by squid-ney** [comment]
This issue is occurring because of styles that TechDocs applies to override the default Mkdocs styles. These styles are applied so that the footer is sticky. The Mkdocs footer is not sticky out of the box. This is a TechDocs feature. In order to have a sticky footer, styles are applied to the mkdocs sidebar and footer that get calculated on every page resize and scroll in dom.tsx, code [here](https://github.com/backstage/backstage/blob/044e8146f5ebc3ee8758027893edfb499651926d/plugins/techdocs/src/reader/components/TechDocsReaderPageContent/dom.tsx#L76). The styles that are applied make the assumption that both a navigation and table of contents sidebar are always present, assumption [here](https://github.com/backstage/backstage/blob/044e8146f5ebc3ee8758027893edfb499651926d/plugins/techdocs/src/reader/transformers/styles/rules/layout.ts#L104).

Resolving this issue while also supporting the sticky footer gets very complex because without both fixed position sidebars, the `.md-content` overlaps with the sticky footer. To prevent this, the `.md-content` needs to have a fixed position. While this can be calculated in the same way the position is calculated for the sidebars, it does not do well at a small page height. In order for the calculations to work, another callback is required in the `dom.tsx` file that needs to run on every `scroll` and `resize` event. Additionally, logic is needed to determine the width and margins of the `.md-content` depending on which sidebars are present. Overall, I don't think TechDocs can cleanly support the 'metadata for hiding the sidebars' mkdocs feature and also support the sticky footer.

**Comment by binaryPUNCH** [comment]
+1 would really like to use the right side of the screen for a particular techdocs page that has tables - gets squished on smaller screens. Any chance we can revisit this?

**Comment by evanbb** [comment]
I have a similar situation where the navigation is rather redundant once you get into a content area.

Since the `hidden` attribute is added to the navigation when it's hidden, can the styles applied inspect the transformed contents and apply as appropriate?

Happy to PR a fix if that's a reasonable approach here, and open to other ideas 😄

**Comment by mrfelton** [comment]
Would also like to see this addressed. Pages can easily become hard to read when squashed into the middle content area. The ability to hide the toc or navigation is a great feature of mkdocs as it enables page layout to be tailored for a pages individual needs. Would be great techdocs could support this.

**Comment by stephenglass** [comment]
Has anyone found a workaround for this issue? @squid-ney I see your two closed PRs #19589 and #19856 - were these solutions incomplete? I'd love to help putting this across the finish line.

**Comment by nickhudkins** [comment]
Hey @stephenglass, as of today I believe you would need to provide your own `TechDocsReaderLayout` component, which is possible but does require a bit more effort than I'd hope to be required. I have been actively working on a lot of TechDocs general improvements / changes, and am happy to contribute to this effort as well. That said, if we can get sign-off on an approach from the core maintainers, I'm sure there's plenty of people to "do the work" 🤩

**Comment by awanlin** [comment]
Just wanted to note that the PRs you referenced @stephenglass came before @squid-ney's post here - https://github.com/backstage/backstage/issues/19324#issuecomment-1718301163 - which is the outcome of that work. If you are willing to pick this up again keeping what was said in mind I'm sure you'll get support from the TechDocs maintainers 👍

**Comment by stephenglass** [comment]
> Just wanted to note that the PRs you referenced @stephenglass came before @squid-ney's post here - https://github.com/backstage/backstage/issues/19324#issuecomment-1718301163 - which is the outcome of that work. If you are willing to pick this up again keeping what was said in mind I'm sure you'll get support from the TechDocs maintainers 👍 

Thanks @awanlin ! And in regard to the comment, it raises a question - what are TechDocs maintainers opinions on continuing to support the sticky footer? It reads like per @squid-ney experience, it would require additional complexity to have both hidden TOC feature and sticky footer feature. A solution would likely lead to further difficulty in code maintainability. 

Personally, if it becomes a blocker I'd prefer to sacrifice the sticky footer (adding little value IMO) if it meant achieving greater usability gains to overall TechDocs.
