### ISSUE TITLE
Entity Feedback plugin not saving feedback🐛 Bug Report: get API returning blank response with 200 

### ISSUE THREAD

**Issue by amitg8** [backstage/backstage#19340]
### 📜 Description

I just installed the entity feedback plugin (awesome plugin idea btw!). However, it doesn't seem to be working correctly. Whenever I submit a feedback for an entity the post request is successful and comes back as a 201. In addition, there are no errors in the logs. This is true if I do a thumbs up or down and whether or not I submit some additional details when it's a thumbs down.
When I navigate to the feedback tab though there is no feedback for that same entity.

### 👍 Expected behavior

It should display feedback in the feedback tab for that entity

### 👎 Actual Behavior with Screenshots

It actually displays a blank feedback tab after feedback is submitted for the entity.

### 👟 Reproduction steps

Submit feedback in the entity page
Go to the feedback tab in the entity page
Nothing shows up

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by adamdmharvey** [comment]
@amitg8 Your description looks *very* similar to a report from a number of months ago. In that case, the user's issue was that they were not logged in as a real user and thus it was not saving.

Can you cross check this issue report and see if there are any relations?

https://github.com/backstage/backstage/issues/16755#issuecomment-1460803060

Also, the environment info is really important here - you can collect it by running `yarn backstage-cli info` and it'll include your OS, all plugin versions, core versions, etc, for help in troubleshooting.

Thanks!

**Comment by amitg8** [comment]
Right @adamdmharvey, its similar issue, but my ask is how we can add use in catalog.
Bcz In the backstage dashboard I can see my profile.
Still not able to see any feedback.

**Comment by adamdmharvey** [comment]
I fired a PR to help with debugging, but that would only help if you have guest provider configured.

So @amitg8 at this point there's not enough info for anyone to help troubleshoot.  Do you mind please editing the details in the original post, ideally not copying the test from someone else's post, and just helping give us all *your* data?

In particular, having the environment info is critical. You can get this using `yarn backstage-cli info` and pasting it in that section. In addition, providing any logs, exact error messages, any sample code you've added, etc, and I'm sure lots of folks could jump in to help!!

**Comment by Pvv7707** [comment]
I am experiencing a similar issue where I am unable to view feedback after submission. I am using a GitHub OAuth app for authentication and login. 
In this post (https://github.com/backstage/backstage/issues/16755#issuecomment-1460803060), it is mentioned that the issue was resolved by adding the user in the catalog. However, there is no information provided on how to add ourselves as a user in the catalog, or if there is an alternative method to retrieve those entity responses.

**Comment by adamdmharvey** [comment]
@Pvv7707 Thanks for some insight!

Users can be added to the catalog in a variety of ways, but you mentioned you've got the GitHub OAuth app, so you can actually use that to ingest organizational data.  There's info on that here:

https://backstage.io/docs/integrations/github/org

In addition, the key concept at play is identify, described here:

https://backstage.io/docs/auth/identity-resolver

Essentially, the authentication system ONLY authenticates, but it doesn't *identity* the user in Backstage. It just "lets you in" to everything, then *identity* drives who you are while using it, and finally you can bolt on permissions to say the identity can do X but not Y:

https://backstage.io/docs/permissions/overview/

So @Pvv7707 , a quick shoehorn way to test your issue here could be to create a single static entity representing a user, matching your user ID, and manually registering it such as by adding it to your `app-config.yaml` at start time?  

The main repo has that example here:

https://github.com/backstage/backstage/blob/61db72d9dd4e823b9c3125b3a448b60aaa126eb2/app-config.yaml#L272-L276

And a specific user file is:

https://github.com/backstage/backstage/blob/61db72d9dd4e823b9c3125b3a448b60aaa126eb2/packages/catalog-model/examples/acme/team-a-group.yaml#L15-L24

But both of these to me perhaps indicate there's a nuance to the plugin where the identityProvider is actually failing, but accidentally returning a 201 to the frontend.  @kuangp I'm wondering if maybe there are a few more test cases for the Entity Provider Backend plugin needed maybe with like PARTIAL identity data or some such?  Any ideas?

This may essentially split into a) how do we improve the plugin to better explain the issue these users may be having (that is, they don't have a full authentication/identity system functional yet), rather than returning successful if it's NOT, and then b) how do the Backstage instructions better elaborate on authentication vs. identity.

**Comment by Pvv7707** [comment]
HI @adamdmharvey,
thanks for the quick reply 
As you asked to add or ingest the org data by following this https://backstage.io/docs/integrations/github/org
so it says add this code inside my catalog.ts

 builder.addEntityProvider(
    GithubOrgEntityProvider.fromConfig(env.config, {
      id: 'production',
      orgUrl: 'https://github.com/backstage',
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 60 },
        timeout: { minutes: 15 },
      }),
    }),
  );
  
  so when run yarn dev after adding this 
  I cant see my entities inside catalog and in console i am getting this error
  
   GithubOrgEntityProvider:production refresh failed Expected a URL pointing to /<org> type=plugin target=https://git.backstage.com/ class=GithubOrgEntityProvider taskId=GithubOrgEntityProvider:production:refresh taskInstanceId=14f2edc9-609d-4342-a7d2-ad3fbf22ef36 stack=Error: Expected a URL pointing to /<org>
   
 below code is from auth.ts of my app
 
 github: providers.github.create({
        signIn: {
          resolver: async (info, ctx) => {
            const username = info.result.fullProfile.username;
            if (!username) {
              // This should never happen...
              throw new Error('No username found for the user.');
            }
            const userRef = `user:default/${username}`;

            return ctx.issueToken({
              claims: {
                sub: userRef,
                ent: [userRef],
                
                
              and the below is my app.config.yaml for oauth
              auth:
                    environment: development
                    providers:
                    github:
        development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        enterpriseInstanceUrl: https://git.marriott.com

can you check if  I miss anything here to create idenetity user for checking the entity feedback responses 
Thanks in advance.

**Comment by adamdmharvey** [comment]
Yep.  So you're closer.

Note in the integration config, you still need to set an integration in your config.  the `auth` key is ONLY for auth.  Some integrators may use one way to auth, and an ENTIERLY different way to load data. (e.g., you could use LDAP to load users into Backstage, but Okta to authenticate)  In your case, you may be wanting to try GitHub for both.

```typescript
builder.addEntityProvider(
  GithubOrgEntityProvider.fromConfig(env.config, {
    // this is the ID you've configured in your config. 
    // your config example shows you set one up called "development"
    id: 'production',  
    // the host and org you want to ingest; you likely don't want to load this org,
    // but your OWN org. maybe https://git.marriott.com/org ?
    orgUrl: 'https://github.com/backstage',  
    logger: env.logger,
    schedule: env.scheduler.createScheduledTaskRunner({
      frequency: { minutes: 60 },
      timeout: { minutes: 15 },
    }),
  }),
);
```

But you'll still need an `integration` key as identified here:

https://backstage.io/docs/integrations/github/org/#configuration

Note instead of using a TOKEN, just use your GitHub App details: clientID, secret, etc.

In my case, I had them injected into a Kubernetes pod as an env var, and used the same env var for both. You can do the same if you load from a file, too.  Here's how I had that - file based - setup on my local:

```
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-backstage-local-credentials.yaml

auth:
  environment: development
  providers:
    github:
      development:
        clientId:
          $include: github-app-backstage-local-credentials.yaml#clientId
        clientSecret:
          $include: github-app-backstage-local-credentials.yaml#clientSecret
```

**Comment by Pvv7707** [comment]
actually I already have auth and integrations in app.config.yaml

integrations:
  github:
    - host: git.backstage.com
      apiBaseUrl: https://git.backstage.com
      token: 
      
      but still I was unable to fetch the responses 
      below is the error when i click on identities 
      
![bs](https://github.com/backstage/backstage/assets/142504329/bf88725f-0597-4917-b7d5-1b9deb941d83)
![bs1](https://github.com/backstage/backstage/assets/142504329/52c3d373-4ed9-4274-974c-8a80f29aaf14)

**Comment by Pvv7707** [comment]
Hey @adamdmharvey can you check this i am stuck here 
 Now i am able to see the user identities in profile section after adding GithubOrgEntityProvider instead of GithubEntityProvider
in catalog.ts file like below as you suggested and also 
```
builder.addEntityProvider(
  GithubOrgEntityProvider.fromConfig(env.config, {
    // this is the ID you've configured in your config. 
    // your config example shows you set one up called "development"
    id: 'development',  
    // the host and org you want to ingest; you likely don't want to load this org,
    orgUrl: 'https://github.com/backstage',  
    logger: env.logger,
    schedule: env.scheduler.createScheduledTaskRunner({
      frequency: { minutes: 60 },
      timeout: { minutes: 15 },
    }),
  }),
);
```
and have added custom file for user and provided locataion in app config 
but now after adding this GithubOrgEntityProvider i was not able to load the components in catalog 
am i missing anything here
![image](https://github.com/backstage/backstage/assets/142504329/ab05ed01-dd9b-44a8-be01-6dfce22989a9)

**Comment by Pvv7707** [comment]
Thanks for the help
