### ISSUE TITLE
🚀 Feature: Update Config Values without Restarting Services

### ISSUE THREAD

**Issue by ptcrash** [backstage/backstage#19349]
### 🔖 Feature description

When a config file value is changed, Backstage frontend and backend services will detect that change, reload the config values, and continue serving automatically and without service interruption.

### 🎤 Context

As a Backstage operator, I want to be able to manage secrets in a secrets manager, like Vault or via AWS ECS Env variables. In its current iteration, Backstage _can_ pull values from ENV values but if those values change in runtime, it is not reflected in Backstage. According to the Backstage docs, there is no way to update configuration values after start-up. [1]

If Backstage were to pick up config value changes, either through changes to the config.yaml files or through changes to environment variables, then I could easily rotate secrets and even set up secret auto-rotation from a secrets manager without needing to worry about restarting or redeploying Backstage services.

[1] Writing Backstage Configuration Files  - Includes and Dynamic Data (https://backstage.io/docs/conf/writing#includes-and-dynamic-data)
> All includes are loaded at startup, so changing the contents of files or environment variables will not be reflected at runtime.

### ✌️ Possible Implementation

A possible implementation would be to create a watcher that would watch for updated config files and reload the file data into the ConfigAPI.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
This is actually already part of the config system! There's a `.subscribe()` method that plugins can use to subscribe to config changes. You can see it in action [here](https://github.com/backstage/backstage/blob/80ba0a280f2bccae705b120a4156a66bc83132a9/plugins/catalog-backend/src/modules/core/ConfigLocationEntityProvider.ts#L40-L55) for example. Under the hook all files included in deriving the config are watched, so including any types of includes, multiple config files, etc.

Now it's up to plugins to implement support for this, either via calling `.subscribe()` and reacting to changes, or by making sure that values are read from config on-demand, rather than upfront, since the underlying config data will update at runtime too.

Regarding ENV vars we don't react to changes to those, because apart from runtime representations like `process.env`, environment variables of a running process can't be changed, at least in any unix-based OS.

**Comment by ptcrash** [comment]
That's great! Is there any interest in creating a strike force to update popular plugins?

**Comment by benjdlambert** [comment]
Hey @ptcrash! PR's  are welcome, maybe you can create a ticket with some smaller subtasks for the plugins and the community can contribute smaller parts as I don't think we'd want to do this totally everywhere, but there's maybe some quick wins that we can do short term.
