### ISSUE TITLE
🚀 Feature: browser-friendly API for authenticated websocket sessions

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#19581]
### 🔖 Feature description

#19001 implements a nice steel thread, but it only works for the narrow case when there is a single, server-side-authenticated cluster, and it doesn't work when the permissions framework is enabled. Let's improve our backend to allow shelling into pods in general.

### 🎤 Context

The browser's [WebSocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) has no means of specifying additional headers (it knows how to supply the headers required for a WebSocket handshake, but no others). This makes the browser not an ideal client for the kubernetes-backend's existing proxy endpoint (which relies on headers to specify a Backstage token and cluster name), or the k8s API's `exec` subresource on pods (which uses the `Authorization` header in the usual fashion). The key use-cases that would be unblocked here would be shelling into pods from the browser (cf #18024) when:

* the permission framework is enabled
* there is more than one cluster registered with Backstage
* the targeted cluster is configured with a client-side auth provider

all of which should be considered typical, recommended configurations.

### ✌️ Possible Implementation

I imagine a new API at `/api/kubernetes/websocketproxy` with a few operations:

1. `POST /api/kubernetes/websocketproxy/sessions` accepts a cluster name, Backstage ID token and auth data for a client-side auth provider. It does some light validation (Is the Backstage token valid? Does the permissions framework authorize the user to access the proxy endpoint? Does the referenced cluster exist?) and in the happy path returns a base path like `/api/kubernetes/websocketproxy/sessions/:uuid`. Under the hood, it should create a row in a database table, perhaps called `websocket_sessions`,  which contains the supplied cluster name and client-side auth data, generating a securely-random UUID for the session and marking it to expire in a very short time (say, 1 minute).
1. Any HTTP verb at `/api/kubernetes/websocketproxy/sessions/:session_id/*`. This endpoint should be accessible with no headers, completely unauthenticated. Backstage should look up a session with the specified ID, and if it exists and has not expired, proxy the request to the associated cluster with the wildcard `*` portion as the path (the main use case being a path like `/api/kubernetes/websocketproxy/sessions/:session_id/api/v1/namespaces/:ns/pods/:pod_name/exec`), injecting the associated auth data. This endpoint should support WebSocket upgrades. Once a connection has been opened to a given session, it should immediately expire so it can't be reused if the session ID gets compromised.

Finally, it might make sense to have some asynchronous background operation which cleans up expired WebSocket sessions in case people initiate them and then walk away without opening a connection.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mclarke47** [comment]
We could make this pretty generic for websocket to frontend communciation? WDYT @Rugvip

**Comment by Rugvip** [comment]
What do you think about communicating the session details in-band within the WebSocket connection instead? That way we'd avoid the need to store this session state in the DB as we wouldn't need to handle the case where the initial POST hits a different node than the followup WebSocket connection?

**Comment by jamieklassen** [comment]
@Rugvip I remember trying to do something similar to that on a project in the past. We were thinking you would have to send a special WebSocket message with all the sensitive stuff before the server would take you seriously, like a custom WebSocket subprotocol just for the auth stuff... I think we were instructed to avoid it for security reasons.

In my context, folks were concerned with attacks where you could connect to the unauthenticated WebSocket endpoint and leave the connection open, never sending any auth information. Even with judiciously-chosen idle timeouts, a burst of these malicious connections could exhaust open file handles (at least at the ingress), denying service to any other APIs.

Now Backstage isn't necessarily in the same boat. I am definitely biased because I have successfully built an API like the one in this issue in the past. Especially if the security concern doesn't apply, I'd be pretty interested to see/do a comparison of maintainability/operability between the two approaches.

**Comment by Rugvip** [comment]
@jamieklassen yep seems like a valid concern. I'm not entirely sure what the real differences are between a WebSocket connection flood vs e.g. a plain HTTP Slowloris DoS, but I do see that WebSockets are a bigger surface.

I'm a bit wary of trying to harden Backstage itself too much against these kind of attacks. While I do think we want to provide reasonable protection for internet-facing deployments in the future I don't think we'll ever want to aim for more sophisticated DoS protection and the like. If that's needed it'll be better to offload that to some form of gateway. That said we'll want at least some base level of protection where it's not trivial to bring down a deployment.

We could also go for a cookie-based approach. It would be somewhat similar to what you describe where a WebSocket connection first needs a HTTP call to set a cookie, although we'd still need an extra in-band or origin check because of the lack of CORS protection.

Overall I would be quite interested in what an authorized WebSocket helper could look like. I'm thinking something like

```ts
router.use('/websocketproxy', websocketMiddleware({
  authenticated: true,
  async handle(socket) {
    // ...
  }
}))
```

Or w/e API makes sense, potentially wrapped up in a service too. Although it might not be the right approach either. I'm quite interested in the continuation of #18153 too, which gives us transport fallbacks in case WebSockets aren't available, which I think makes sense for the majority of usages.

**Comment by luchillo17** [comment]
I'm not an expert on WebSockets, the only think I've build with sockets was a SocketIO server before, I was wondering why can't we just authenticate the handshake? is it because we're not the end server but a proxy middleware? or is it the WebSocket server we want to enable (pod exec) doesn't support it?

**Comment by jamieklassen** [comment]
@luchillo17 the cross-browser `WebSocket` object we use here:

https://github.com/backstage/backstage/blob/d5105d8cdf325fe2be0a41db19e7bafe5802d6b9/plugins/kubernetes/src/components/PodExecTerminal/PodExecTerminal.tsx#L100

doesn't have any way of specifying headers for the handshake. The pod exec API in Kubernetes does authenticate requests via their `Authorization` header, but our client code has no way to provide that sort of metadata to our proxy. It's a limitation of the browser as a client rather than any of the servers involved.

SocketIO has its own abstractions and features on top of WebSockets, so an [Engine.IO handshake](https://socket.io/docs/v4/engine-io-protocol/#handshake) (even when your transport is WebSockets and not HTTP long-polling) is very different from a vanilla WebSocket upgrade. That said, we might be able to build a custom SocketIO-based protocol for this purpose. If I understand how SocketIO works (I just read the page I linked in the last couple minutes, so I might be wrong), I think this is one approach to the "custom auth message/subprotocol" @Rugvip suggested above.

**Comment by luchillo17** [comment]
What would be the alternative? sessions with authentication through the socket connection? meaning the WebSocket would start unauthenticated?

**Comment by luchillo17** [comment]
What is the state on this? also can we take the K8s subprotocols as example?

**Comment by luchillo17** [comment]
While looking for info on this subject I came across this article [How to secure your WebSocket connections](https://www.freecodecamp.org/news/how-to-secure-your-websocket-connections-d0be0996c556/).

Based on the 4th point, it states we should be implementing authentication before the WS connection is set up because its usually expensive to set up WS connections (at least more so than HTTP ones), however @jamieklassen has stated there's no way to add headers to the `WebSocket` browser API instance, digging a little it seems this 2018 article was written with the `ws` package in mind instead of the browser's `WebSocket` implementation.

Then this more recent article [Essential guide to WebSocket authentication](https://ably.com/blog/websocket-authentication) goes into multiple implementations, pros, cons & limitations of them like:

- Send access token in the query parameter: Query params usually get logged in the server, so not good.
- Send an ephemeral access token in the query parameter: Stateful approach that adds complexity to reduce the cons of the previous approach.
- Send access token over WebSocket: Custom protocol adds complexity & is prone to DOS as discussed, not to mention WebSocket connection setup cost.
- Send credentials in a HTTP cookie: Limited to same domain for the web app & server so browser sends cookie properly, non issue for us, and needs to disable CORS manually so only our web app can connect to our server, may need CRSF token setup.
- Send credentials with the Sec-WebSocket-Protocol header (didn't knew this existed): Non standard, hack, depending on logging setup in server might end up logging the credential itself.
- Forget about WebSocket authentication (mostly) with Ably (this is the Ad part of the article, so ignore).

Based on this and the limited knowledge I have, it looks the best way right now would be to use Cookies to authenticate the handshake.

Then I found an actual tutorial for Cookie/token based WebSocket auth, not sure if its standard but at least there's an example in the video how it could be implemented: https://youtu.be/twNgfrE4ShE?si=EMRgyYh9Zw_1xru0

**Comment by Rugvip** [comment]
@luchillo17 +1 to a cookie approach. My immediate thought is that we'd scope it to the plugin itself rather than a more deployment-wide approach. Something like this:

1. GET `/api/plugin-x/gimmie-cookie`
2. CONNECT `/api/plugin-x/websocket`

**Comment by Rugvip** [comment]
With the new auth APIs in flight and another implementation in the signal backend, I'd suggest that we settle on using the `sec-websocket-protocol` header to carry a user token. It's extremely simple compared to a cookie-based flow, with an example implementation here: https://github.com/backstage/backstage/blob/87e9ed3ccc64074fe21d123e16199b54a55bc41e/plugins/signals-backend/src/service/router.ts#L89-L95

The downside is the risk of leaking this header in logs, as opposed to the `cookie` header which might not be logged as often, but I think that's an acceptable risk.

Bit of a nit in the example implementation above: I think it's best to prefix the token, since one might want to specify multiple values. Just something fairly simple like `backstage-user-token-:`. Again taking inspiration from the k8s implementation: https://github.com/kubernetes/kubernetes/blob/b3926d137cd2964cd3a04088ded30845910547b1/staging/src/k8s.io/apiserver/pkg/authentication/request/websocket/protocol.go#L57-L81
