### ISSUE TITLE
🐛 Bug Report: Missing ADR for apiRef

### ISSUE THREAD

**Issue by taras** [backstage/backstage#19653]
### 📜 Description

Backstage provides `apiRef` mechanism that serves the same purpose as a custom Context Provider. It additionally provides a mechanism to configure dependencies of an apiRef, which is more challenging with the Context Provider. We're noticing some friction where teams are unfamiliar with Backstage adding Context Provider where they should use the `apiRef`.

Additionally, I couldn't find any documentation about the apiRef mechanism. 

### 👍 Expected behavior

I was expecting to see an ADR for apiRef that I could use as a resource for developers who are new to Backstage. 

### 👎 Actual Behavior with Screenshots

I couldn't find an ADR for apiRef.

<img width="281" alt="image" src="https://github.com/backstage/backstage/assets/74687/6600cf02-4494-4051-95bc-85b4ce28f663">

### 👟 Reproduction steps

1. Go to https://github.com/backstage/backstage/tree/master/docs/architecture-decisions
2. List doesn't have the ADR

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
I don't really think this is a good fit for an ADR tbh. They tend to be used for decisions regarding development in Backstage project itself, rather than design decision, although we do have some precedent against that. More importantly I'd say it's not a good place for documentation though, and I would expect it to not be a place that people look very frequently.

I feel that the best place to highlight Utility APIs is in an introduction to plugin development, i.e. golden path.

**Comment by taras** [comment]
I see. Ok, that makes sense.

**Comment by tudi2d** [comment]
Thanks - will close this for now.
