### ISSUE TITLE
🚀 Feature: Automatically filter Cloud Build workflow runs

### ISSUE THREAD

**Issue by ghost** [backstage/backstage#19685]
### 🔖 Feature description

Automatically filter Cloud Build history to the specified component name or source name.

### 🎤 Context

Using the Google Cloud Build plugin, it currently shows Cloud Build history in the CI/CD page starting from the most recent build. If you do many builds in the specified project-slug, then the history will show these builds. It does not make sense to show builds not related to the component. Also, there appears to be no way to filter based on source using the filter at the upper right of this page.

### ✌️ Possible Implementation

There should be a way to automatically filter or only show the results that match the component that has the CI/CD entityContent. Either by component name (default?), or something added to a component annotation (google.com/cloudbuild-source-name: myapp).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by cl-christschantz** [comment]
I wonder if you could do something like this:
```
  async listWorkflowRuns(options) {
    const workflowRuns = await fetch(
      `https://cloudbuild.googleapis.com/v1/projects/${encodeURIComponent(
        options.projectId
      )}/builds`,
      {
        headers: new Headers({
          Accept: "*/*",
          Authorization: `Bearer ${await this.getToken()}`
        })
      }
    );
    const builds = await workflowRuns.json();
    const { entity } = useEntity();
    const filter = builds.filter(b => b.REPO_NAME = entity.metadata.name)
    return filter;
  }
  ```
  
  I noticed projects.builds.list has a filter parameter, however It does not seem to work (INVALID_ARGUMENT):
  https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds/list?

**Comment by Rugvip** [comment]
Yep sounds like a good addition, but it might indeed need a new annotation or potentially configurable way of filtering things. Leaving this one open for contributions

**Comment by cl-christschantz** [comment]
This is still very much desired.

**Comment by cl-christschantz** [comment]
I figured out how to use the filter parameter properly. I believe the below should be a viable option:

_Requires useEntity import: `import { useEntity } from '@backstage/plugin-catalog-react';`_

```
  async listWorkflowRuns(options: {
    projectId: string;
  }): Promise<ActionsListWorkflowRunsForRepoResponseData> {
    const { entity } = useEntity();
    const entityName = entity.metadata.name
    const cbFilter = "substitutions.REPO_NAME=" + entityName
    const workflowRuns = await fetch(
      `https://cloudbuild.googleapis.com/v1/projects/${encodeURIComponent(
        options.projectId,
      )}/builds?filter=${encodeURIComponent(
        cbFilter,
      )}`,
      {
        headers: new Headers({
          Accept: '*/*',
          Authorization: `Bearer ${await this.getToken()}`,
        }),
      },
    );

    const builds: ActionsListWorkflowRunsForRepoResponseData =
      await workflowRuns.json();

    return builds;
  }
  ```
  
 Assuming that the above would work, it uses the "substitutions.REPO_NAME" filter parameter with the entity.metadata.name as the value. I am sure this could be expanded upon so that the entity name is used by default unless there is an annotation that is specified (annotation TBD).
 
 So for example, lets say your entity name is "MyLegitProject", then the listWorkFlowRuns function would fetch a URL like below:
 
 `https://cloudbuild.googleapis.com/v1/projects/<project-slug>/builds?filter=substitutions.REPO_NAME%3DMyLegitProject`
 
 Ive tested the substitutions.REPO_NAME filter using "Try this Method" on the projects.builds.list method page:
 
` https://cloud.google.com/build/docs/api/reference/rest/v1/projects.builds/list`

At least in my use case, this would be exactly what I need. However, other use cases may require defining what repo name is used in the filter (different from entity name), or possibly a completely separate filter which could get complicated quickly.

I am happy to work with anyone to see this though to completion.
