### ISSUE TITLE
🚀 Feature: Implied Relations visible in catalog-graph plugin

### ISSUE THREAD

**Issue by jahluwalia** [backstage/backstage#19708]
### 🔖 Feature description

I'd like a feature that is similar to the implied relationships that structurizr provides like: CreateImpliedRelationshipsUnlessAnyRelationshipExistsStrategy. 

See here: 
https://github.com/structurizr/java/blob/master/docs/implied-relationships.md

### 🎤 Context

This is beneficial for situations where we want to look at a higher level of the system. ServiceA --> LibraryX --> ServiceB. If I want to filter out Libraries from catalog-graph, I should still see that ServiceA --> ServiceB. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Hm.

Should this one be completely automatic, just doing its thing without any kind-specific logic? If you look at the image in that link, the set of possible relations grows quickly and sometimes don't provide a ton of value. What if you have nested systems (so that they can have a parent system) and then domains above that? That's an exponential number of new relations to deal with.

It's almost like you'd want to have the set of generated relations be different depending on where you're focused and/or what "zoom level" you are at.

This seems a bit nontrivial 🤔

**Comment by jahluwalia** [comment]
You're right, the relationships can get out of control, but are valuable when you want to start looking at higher level pictures (e.g. look only at services but not APIs and Libraries, or look only at domains and filter everything else out). I've used C4 in the past and turned on implied relationships, feed the model to a graph database, and query at the level I want.  

 I'm exploring backstage and I think there are other GitHub issues (logged [here](https://github.com/backstage/backstage/issues/15769)) that discuss not seeing that higher level picture or having that higher level documentation. Spotify had a blog post about an architecture plugin (referenced [here](https://engineering.atspotify.com/2022/07/software-visualization-challenge-accepted/)) that they use in-house, but I don't think it's publicly available. So just looking at alternative ideas before we commit to backstage adoption.
