### ISSUE TITLE
[Plugin] AWS Lambda

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#1988]
We are starting work on this now. 

We will start with:

 1. A way to authenticate with AWS.
 2. Request and view a list of lambdas, along with basic information like the function name, run time, last modification, etc.
 3. A way to associate catalog entities with the functions that run them.

Comment here with are other features you would like to see.

@stefanalund please assign to me.

**Comment by stefanalund** [comment]
I've assigned you @dtuite 👍

**Comment by tomek-ifm** [comment]
Hello, I work with @dtuite on backstage AWS plugins and we already fetch data from AWS by using google as identity provider (first we use Login with google which is already plugged in to backstage, and then we use google's ID token to perform requests to AWS. This is the most simple/secure way to access AWS resources that we could think of. 
In backstage codebase it would look like this:

```
    const token = await googleAuth.getIdToken();
    AWS.config.region = 'us-west-2';
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: 'us-west-2:66ec5b99-b0d6-4cc6-9018-aaaaaaaa',
      Logins: {
        'accounts.google.com': token,
      },
    });
```

On AWS side 3 things have to be created:
- identity pool which allows particular GOOGLE_CLIENT_ID to pass authentication
- a policy to access desired aws resources (in our case lambda:ListFunctions action)
- a role to which a policy will be attached, role would be assigned only to user with email addresses we specify in idenity pool configuration

Steps are visualized here:
**1.** Create a google signin account on https://console.developers.google.com/
**2.** Go to AWS and go to Cognito service. Create an identity pool (not user pool!). Connect idenity pool with the google signin account you created in step 1 (type in the GOOGLE_CLIENT_ID in google+ tab)

![Zrzut ekranu 2020-08-18 o 17 03 28](https://user-images.githubusercontent.com/59601819/90533039-3fbe9080-e178-11ea-9815-aa91401da077.png)

**3.** When you click next the roles for authorization in identity pool would be summariozed. Don't change anything. Save the identity pool


**4.** In AWS go to IAM service. Create a new role. Type in identity pool id that you created in previous step.

![Zrzut ekranu 2020-08-18 o 17 12 06](https://user-images.githubusercontent.com/59601819/90533304-9926bf80-e178-11ea-8ec5-312219c9a728.png)

**5.** You need a policy for your role to access you AWS resources. Which can be created in different browser tab. The Principle of Least Privilege applioes here, so the best case would be to grant only list/get access to your resources and specify which types of resources you want to give access to. In our case it was list/get on lambda. Name and save the policy.

![Zrzut ekranu 2020-08-18 o 17 07 24](https://user-images.githubusercontent.com/59601819/90533593-089caf00-e179-11ea-8b38-d67e4f18c17c.png)

**6.**  Go back to create role tab, refresh policies, select your new policy so it is attached to your new role.

![Zrzut ekranu 2020-08-18 o 17 08 18](https://user-images.githubusercontent.com/59601819/90533796-44377900-e179-11ea-916e-a3bb5893a38d.png)


**7.**  Save your role as e.g.RoleForGoogleUser.

**8.** Go to identity pool and click edit. Click on Google+ tab and instead of using default role choose "choose role with rules". type email of a person you want to grant access to your aws resources (the Role you created in previous step). Value: equals, then there is an input for email (not role, some html bug), and last input is a dropdown where you select a role from previous step (RoleForGoogleUser in my case)

![Zrzut ekranu 2020-08-18 o 17 43 52](https://user-images.githubusercontent.com/59601819/90534909-97f69200-e17a-11ea-95cb-f12588a890af.png)


**9.** Voila,  the code snippet from above should work and you should access your resources from SDK.

**Comment by iain-b** [comment]
Just relaying a screencast with some of the progress on this by @tomek-ifm. We're also planning to facilitate integration to the service catalog by allowing users specify which functions map to a particular service as an optional annotation.  

https://www.loom.com/share/1f14f7c353354b51be5f5c8c9c6d87ec

**Comment by LukvonStrom** [comment]
@stefanalund @dtuite is there any possibility to help here as part of my Hacktoberfest participations?

And @iain-b If you integrate the service catalog with lambda functions, a reverse mapping from the lambda-native applications would be cool, which already indicate the relationships for some lambdas

**Comment by dtuite** [comment]
@LukvonStrom Hi! The open source repo for the plugin [is here](https://github.com/RoadieHQ/backstage-plugin-aws-lambda). We are more than happy to accept contributions so please do get involved, and I agree that a reverse mapping would be fantastic.

There is a relatively big change being worked on for the plugin right now https://github.com/RoadieHQ/backstage-plugin-aws-lambda/pull/2. We initially designed the plugin so that a single Backstage Component could refer to multiple Lambda functions. Based on a second reading of [ADR 5](https://github.com/spotify/backstage/blob/master/docs/architecture-decisions/adr005-catalog-core-entities.md) however, that doesn't seem to be correct. After learning this, we decided to switch out the lambdas tab on the entity page for an overview widget instead.

My username on Discord is `David Tuite (roadie.io)#1010`. You should be able to add me there or just email me at david@roadie.io. I'm happy to discuss more.

/cc @tomek-ifm @iain-b

**Comment by adamdmharvey** [comment]
@dtuite The Roadie AWS Lambda plugin was published up to the Backstage marketplace already:

https://backstage.io/plugins
https://github.com/RoadieHQ/backstage-plugin-aws-lambda

Thinking the root of the ask here is satisfied and thus issue could be closed, would you agree?

**Comment by dtuite** [comment]
@adamdmharvey agreed. Still lots to do but there is a foundation in place.

**Comment by freben** [comment]
Done!
