### ISSUE TITLE
🐛 Bug Report: Flaky Tests

### ISSUE THREAD

**Issue by jrwpatterson** [backstage/backstage#19915]
### 📜 Description

Hey there, it seems that tests in the build are becoming more and more flakey. 

I'm finding more and more, submitting prs, random tests break in the build process even though you haven't touched them. Its very annoying!

Especially as you can't run `re-run failed pipes` in this account at the moment

### 👍 Expected behavior

Tests should always be working if they work

### 👎 Actual Behavior with Screenshots

tests are flakey and keep randomly failing

### 👟 Reproduction steps

Create a pr and run the tests multiple times

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
Agreed, it's getting annoying.

The only major source of flakiness I have seen the last couple of weeks is the database related errors. They can happen in several different places of the code, and seem to be because the [GitHub actions database services that we use](https://github.com/backstage/backstage/blob/dfbea4a71cd1f3109270224d73236dfb92a3fb45/.github/workflows/ci.yml#L145) get torn down. Maybe the tests are too long running at this point so it shuts down? Maybe it's a side effect of some error elsewhere that is yet to be found?

We'd love some help with pinning down this particular flakiness.

But now that I look through recent CI runs the [kubernetes test failure](https://github.com/backstage/backstage/actions/runs/6164386583/job/16730045416) stood out and is new to me. Let's look into that too.

**Comment by jrwpatterson** [comment]
@freben yup I've been looking at the kubernetes test failure. I can't replicate it locally and as it happens at the end of an 18 min run its a killer... 😢

**Comment by jrwpatterson** [comment]
I'm wondering if that is getting run on in a different order in local vs on the action and that means that the test is picking up something
