### ISSUE TITLE
💬 RFC: New Catalog UI Plugin

### ISSUE THREAD

**Issue by morganmspencer** [backstage/backstage#19911]
### 🔖 Need

We would like to enhance the catalog view to better support the user experience of users who utilize their developer portal for both discovery of your organization's reusable solutions as well as operating and developing against a portfolio of components.

Pain Points addressed:

🤯 Our users found the current filters to be a bit confusing and the table to be overwhelming.
🤔 As a new user, it's difficult distinguish between reusable solutions and MY stuff.
🤑 When modifications are necessary, it required duplicating the catalog code, making it difficult to maintain and justify the small enhancements desired

### 🎉 Proposal

![software-catalog-spotify-demo](https://github.com/backstage/backstage/assets/10109983/35a20214-3f25-41f5-ac7c-261f93fae9fa)

We are proposing an alternate Catalog UI for adopters with similar use cases and pain points. We want to make this available to others as a plugin and want feedback from the community on the layout, features, and applicability to other’s use cases.

✅ We updated the catalog view with a focus on usability and configurability.
✅ We created two layouts that users can toggle to support an explorative workflow where users are interested in the descriptions and tags and a more detailed view where users can see additional meta data.
✅ We updated how the tags visualize to provide more information and grouped categories and filters together

We believe this design will enhance the user experience of the catalog. This design was positively received during our user testing.

#### Usability

- **Full width table**: Making the table full width allows users to see more information without scrolling horizontally
- **List and detail views**: Two views to allow users to control the amount of information they want to see
- **Kind tabs**: Utilized tabs for switching between entity kinds and extended it to allow multiple kinds at once
- **Quick filters**: Updated the filters to show a series of quick filters with additional filters in an expandable panel. Use of a quick filter with custom filter implementation to identify reusable solutions.
- **Slide out drawer**: Each table element has a drawer for quickly viewing more details without having to go to a component page. Great for people just exploring the catalog.

#### Configurability

Allow users to pass in customization to the page component as props without having to copy and recreate it.

- **Tabs** - Developers can provide an array of tab objects to customize their table. For each tab the user provides an array of strings for the kinds that should be included on that tab (ex. `['component', 'template']`). Next, an array of column elements for that tab. The default columns are exported from the plugin so they can be easily referenced and extended. Finally, an array of filters that should be available for the tab. There is a default tab configuration that comes with the plugin but developers can also customize each aspect.
- **Initial tab** - Ability to select an initial tab on page load
- **Custom button title** - Change the label for the create button
- **Page title** - Change the page title

### 〽️ Alternatives

When needing to make minor changes the catalog view we had to recreate it as a whole. When we decided to create an updated version based on several iterations of user feedback, we determined we had to recreate the table from scratch. We thought a better solution would be to make it easier to configure the table, reducing the need to duplicate Backstage code.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by jrwpatterson** [comment]
I love this design anything I can do to help?

**Comment by morganmspencer** [comment]
@jrwpatterson Thanks so much! As of right now we are working with our organization to make the code available. In the meantime, we would love any general feedback you have or any pain points you experience that this would solve.

Also we could include you on future technical RFCs if you're up for it.

**Comment by freben** [comment]
First: YAY! 🥳 

On the question of pain points:

- I hope this happens to use the new paginating endpoint of the catalog (`/entities/by-query`) and doesn't load the entire catalog in the background even though only the first page is seen. This would instantly resolve some issues that have been around for a long time, which would be wildly popular!
- I hope the filter sets are a bit more robust than the current ones, with fewer spurious repaints and stuff like that.
- Plus it looks GREAT! Can't claim that the old one does :)

Random thoughts:

- Make sure that it fully supports custom / extended entity models and doesn't make assumptions about what kinds or fields exist etc. But it seems you probably have that covered, from the description!
- You mention the name of the create button and page title.  It may be the case that those could be covered by the recent i18n efforts rather than as props?
- Custom filter controls, custom cell renderers, custom tile renderers (in the expanded mode), and the ability to customize what goes in the flyout "quick peek" pane could come into play here.

**Comment by sevedkim** [comment]
Hi @morganmspencer!

Thank you for this amazing write up and proposal. In addition to feedback from the rest of the community, we're going to bring this to our internal design team to critique and come back with feedback. Hopefully we should get back within 2 weeks.

**Comment by awanlin** [comment]
Just wanted to say I really like this as well and I think it's cool to see a few things here:

1. This wider style with tabs for Kinds is also something that Roadie just release so clearly this is a pattern other have been independently thinking about so another confirmation of the research done for this design: https://roadie.io/blog/august-2023-product-updates/#new-catalog-page-preview
2. This is a bit on the fun side but what is old is new again, back in the early days of Backstage it did have tabs for the Kinds. You can see that in this PR from August 2020: https://github.com/backstage/backstage/pull/2076

**Comment by aaronnickovich** [comment]
I have to agree the filters at the top are better because of the wasted space under the filters. I'm a maybe on the kind tabs. Someone might have more custom kinds which can make the tabs unwieldy. Maybe you can turn it into a drop-down or a carousel if there are more than standard 8 or so kinds

**Comment by djspotify** [comment]
Hey, thanks for presenting this proposal! 
After taking a quick look it seems to be a solution catered to a specific need and may clash with a larger set of needs across Backstage adopters.

Some points that jumped out to us, going over this for the first time

- Icons without labels are less accessible, perhaps try to clarify the intentions to help guide user's expectations.
- Is the side drawer overlay necessary? It's a little hard to tell from the video because it is showing so quickly. But it seems as though it offers a new view of what's already displayed in the rows.
- In general, the UI uses lots of icons, some interactive, some for orientation and others for state. The UX could benefit from using them more consistently.
- The initial table view is highly complex and quite dense, it may be beneficial to save the user some processing by instead displaying some of the information in their respective detail views.
- Horizontal tabs have been problematic for us, if there are more tabs, what will happen? What if the browser window is narrow?

It appears to us as if this solution tries to do everything at once, which seemingly helps those users who built it and are already familiar with it. For first time users, it's complicated to get going and may break for a different set of data/requirements.

**Comment by sevedkim** [comment]
@morganmspencer we will be considering some holistic improvements to the catalog page in the upcoming year and would love to involve your ideas and feedback. 

For now I'm going to close this out but we'll hope to re-open once we re-approach this topic next year. Thank you for contributing your ideas!
