### ISSUE TITLE
🐛 Bug Report: Tabs that change the active route (such as EntityPage tabs) should use a link element

### ISSUE THREAD

**Issue by kunickiaj** [backstage/backstage#19912]
### 📜 Description

Tabs that change routes use the incorrect element for display,

### 👍 Expected behavior

They should instead use links like demonstrated here: https://mui.com/material-ui/react-tabs/#nav-tabs

Because the current element is a button with an onClick handler it is impossible to copy link or open in new browser tab. This _may_ fail some a11y s tandards.

### 👎 Actual Behavior with Screenshots

Tabs that change routes such as the "routable extensions" that show up in the EntityPage use a button element from which you cannot copy a link or open in a new browser tab.

### 👟 Reproduction steps

1. Go to an EntityPage in the catalog
2. Try to middle click or right click any of the tabs

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Indeed. For the interested reader, [here](https://github.com/backstage/backstage/blob/40c96b1562a27e5e73fab1a44ac3ff34f48a4c50/packages/core-components/src/components/TabbedLayout/RoutedTabs.tsx#L83) is the click handler, and the underlying tab bar [uses](https://github.com/backstage/backstage/blob/40c96b1562a27e5e73fab1a44ac3ff34f48a4c50/packages/core-components/src/layout/HeaderTabs/HeaderTabs.tsx#L18) plain MUI `Tabs` and `Tab`.

We have some faint memory of this having some historical meaning, maybe due to not wanting to nav backwards when on subroutes in some case? Either way, gonna put a `help wanted` on this, might be worth exploring this.

**Comment by tudi2d** [comment]
This still seems to be happening & I can reproduce it e.g. on https://demo.backstage.io/catalog/default/component/artist-lookup. There is no one working on this at the moment & it is open for contribution.

**Comment by denxychen** [comment]
I'd like to work on this if nobody has taken it up :)

**Comment by camilaibs** [comment]
Yes, your help is welcome @denxychen 🎉
I assigned the issue to you 🙌🏻
