### ISSUE TITLE
[RFC] The Future of Locations

### ISSUE THREAD

**Issue by freben** [backstage/backstage#2001]
# The Future of Locations

This RFC suggests some changes to the concepts of "locations" within the service catalog, to enable a clearer model, add some features, and remove some old limitations.

The short version:

- Remove the `locations` table
- Make full use of the `Location` kind entities
- Change the refresh loop such that entities are self-sufficient and update "themselves", and `Location`s are mainly seen as a bootstrapping mechanism

## Background

The Backstage software catalog has inherited the concept of "locations" from the old catalog used internally at Spotify. The basic idea is that users register such locations - for example a URL pointing to a yaml file in GitHub - that ultimately lead to raw entity data. Then, the catalog makes sure to keep itself up to date with changes in that location. This is the primary means of populating the catalog.

The way that the software catalog implemented these locations has become limiting, primarily:

- They are a concept entirely of their own, in a separate table. This leads to duplication of efforts to get logs and statuses stored in the database.
- There is a foreign key relationship between the entity and location tables that restricts or confuses the ability to add data in more flexible ways (through separate POST, through automated migrations, etc).
- There exist both the location table, AND entities of kind `Location`, leading to confusion
- There is some unclarity on how locations should map to the lifecycle of entities, in particular regarding deletions and moving from one location to another

This RFC proposes changes to the way that locations are used, both under the hood and as an end user of the APIs, to enable better use of this facility.

## Scope

The following pieces of the catalog model are affected by this RFC:

- *The `/locations` section of the catalog API*: This is where locations are added and removed.
- *The `locations` database table*: When a location is added to the catalog, it ends up being written to this table.
- *The `entities` database table*: Entities have a foreign key pointing to the location that spawned them.
- *Entity annotations: The annotation `backstage.io/managed-by-location` is added to entities automatically, pointing to the actual location type/target that the entity was read from
- *The location refresh loop*: There is a loop inside the catalog backend that periodically goes through all locations, reads them, and updates entities accordingly

## Proposal

We suggest that locations as a separate table and concept are eliminated, and that we instead lean into using the `Location` entity kind. Users will register `Location` entities using direct POST requests to the entities API, and these will be used as sources for finding more entity data during the update loop.

This has a number of implications.

The `entities` table will have its `location_id` column dropped and the corresponding field removed from the TS types.

The `locations` table will be dropped and the corresponding TS types removed. In doing so, the migration step will have to translate each entry into a `kind: Location` entity in the `entities` table, with the corresponding data. This also means dropping the `location_update_log` table and the `location_update_log_latest` view.

The `LocationsCatalog` type and its implementation are removed and all of the corresponding routes are removed.

The addition of an entity via POST request needs to gain the ability to to a "bootstrap refresh run" if it happened to be a Location, like the old locations do upon creation, to verify that the location was valid and useful.

The frontend code needs to be updated to create an entity instead of using the separate API, when users register a location.

The mock-data scripts need to be updated similarly, as do some other parts of the frontend code (e.g. the button for mocking data into an empty catalog).

The frontend may want to assist the user when unregistering entities. If unregistering a Location, the user should be asked if they want to also unregister other entities that belong there (e.g. they have a `backstage.io/managed-by-location` annotation that points to the same type/target). If unregistering a non-Location, if there exists a Location object that points to the same type/target, the user should be informed about that because otherwise there's the risk that the same entity almost instantly reappears as part of the refresh loop of that Location.

Finally, the refresh loop inside the catalog backend needs to be updated. It would look for all Location entities, and fetch the contents of all of them. The resulting entities will be given a `backstage.io/managed-by-location` annotation pointing to the same type/target as the Location that spawned them, and stored. Then, the loop will look at all the remaining entities that already had a `backstage.io/managed-by-location` but haven't yet updated (meaning, they once had a Location but it was removed), and fetch updated contents for them too.

This way, entities will be self-sufficient in terms of refreshes. Locations will be regarded more as bootstrapping sources, that continuously spawn entities that can then be refreshed on their own.

**Comment by Rugvip** [comment]
> * Remove the `locations` table
> * Make full use of the `Location` kind entities

👍 

> * Change the refresh loop such that entities are self-sufficient and update "themselves", and `Location`s are mainly seen as a bootstrapping mechanism

Do you envision that that will be the loop-driven update method too? Or that we would have both full location-driven refreshes in addition to being able to refresh individual entities. I'm having a hard time seeing what the use-case and benefit of refreshing individual entities in isolation would be. Unless we of course are talking about individual refreshes of location entities, as that would be used to drive refreshes from webhooks.

> * They are a concept entirely of their own, in a separate table. This leads to duplication of efforts to get logs and statuses stored in the database.
> * There is a foreign key relationship between the entity and location tables that restricts or confuses the ability to add data in more flexible ways (through separate POST, through automated migrations, etc).
> * There exist both the location table, AND entities of kind `Location`, leading to confusion

👍 

> * There is some unclarity on how locations should map to the lifecycle of entities, in particular regarding deletions and moving from one location to another

Is it in the scope of this RFC to figure out how to move and delete entities?

> We suggest that locations as a separate table and concept are eliminated, and that we instead lean into using the `Location` entity kind. Users will register `Location` entities using direct POST requests to the entities API, and these will be used as sources for finding more entity data during the update loop.

I think we actually need to move away from supporting direct `POST` of entities to the catalog. It has some security implications that are tricky to deal with, and we could allow for a separate plugin to cover the same functionality. I'm actually not sure what the use-case for `POST`ing non-location entities to the catalog even is?

For the location registration use-case I'd actually suggest that we look into making that part of the `register-component` plugin, basically making it a separate backend that can be used to keep track of locations. Those registered locations are then in turn brought into the catalog using whatever method we choose ¯\\\_(ツ)\_/¯. That'll let organizations that don't want the manual registration feature to simply not have the plugin at all, and it kinda makes sense that it comes as a frontend + backend package too.

> The frontend may want to assist the user when unregistering entities. If unregistering a Location, the user should be asked if they want to also unregister other entities that belong there (e.g. they have a `backstage.io/managed-by-location` annotation that points to the same type/target). If unregistering a non-Location, if there exists a Location object that points to the same type/target, the user should be informed about that because otherwise there's the risk that the same entity almost instantly reappears as part of the refresh loop of that Location.

I suggest we use relations as proposed in #1964 to model the `managed-by-location` relationship. It'd simply be a `1-N` relationship between any kind of entity to a `Location` entity. With that we can easily look up the other entities that share the same location.

This and other things brings up the problem of naming the locations. One possibility if we can't find something else is to simply name it `location-<type>-<target-sha>`.

> This way, entities will be self-sufficient in terms of refreshes. Locations will be regarded more as bootstrapping sources, that continuously spawn entities that can then be refreshed on their own.

So to re-iterate, what is the benefit of self-sufficient non-location entities? 😅

**Comment by freben** [comment]
> > * Change the refresh loop such that entities are self-sufficient and update "themselves", and `Location`s are mainly seen as a bootstrapping mechanism
> 
> Do you envision that that will be the loop-driven update method too? Or that we would have both full location-driven refreshes in addition to being able to refresh individual entities. I'm having a hard time seeing what the use-case and benefit of refreshing individual entities in isolation would be. Unless we of course are talking about individual refreshes of location entities, as that would be used to drive refreshes from webhooks.

See below - it is the same loop as before essentially, it just basically feeds itself from Location entities and entity annotations instead of from the locations table.

> > * There is some unclarity on how locations should map to the lifecycle of entities, in particular regarding deletions and moving from one location to another
> 
> Is it in the scope of this RFC to figure out how to move and delete entities?

I started out with that, but backed off a bit. Should have updated up here too to reflect.

But in summary:

I think that moving will sort itself out based on the proposed structure. Consider entity A at location a, and entity B at location b. If we start the loop and find `[a, b]` and a now returns `[A, B]`, then the end result will be that we write A with location-annotation a, and B with location-annotation a.

Removal is harder. We could easily detect orphaned locations (that no longer have any entities with matching location-annotations) and orphaned entities (that no longer have a matching Location entity equal to its location-annotation). So we may choose to do that from the frontend, informing users to do the unregistrations, instead.

> > We suggest that locations as a separate table and concept are eliminated, and that we instead lean into using the `Location` entity kind. Users will register `Location` entities using direct POST requests to the entities API, and these will be used as sources for finding more entity data during the update loop.
> 
> I think we actually need to move away from supporting direct `POST` of entities to the catalog. It has some security implications that are tricky to deal with, and we could allow for a separate plugin to cover the same functionality. I'm actually not sure what the use-case for `POST`ing non-location entities to the catalog even is?

I kinda argue the other way around, that that should be the only proper way. It does require authorization to work before being secure. I argue that the refresh loop is what should be a completely external process, that reads Location entities and POSTs updates back based on what it reads.

Web hook driven workflows would be the exact same. An external process receives the webhook, reads out the actual entity data in the manner that fits the originator of the webhook, and POSTs that to the catalog. The catalog would be reduced to not much more than a dumb datastore in that regard.

> For the location registration use-case I'd actually suggest that we look into making that part of the `register-component` plugin, basically making it a separate backend that can be used to keep track of locations. Those registered locations are then in turn brought into the catalog using whatever method we choose ¯\_(ツ)_/¯. That'll let organizations that don't want the manual registration feature to simply not have the plugin at all, and it kinda makes sense that it comes as a frontend + backend package too.

Hm, not sure I follow this one. You mean to NOT use Location entities but instead just move the locations table to an entirely separate database (so to speak) owned by a different plugin? Then what means would that backend actually use to update the resulting entities, if not via POST? How does that interact with a refresh loop?

> > The frontend may want to assist the user when unregistering entities. If unregistering a Location, the user should be asked if they want to also unregister other entities that belong there (e.g. they have a `backstage.io/managed-by-location` annotation that points to the same type/target). If unregistering a non-Location, if there exists a Location object that points to the same type/target, the user should be informed about that because otherwise there's the risk that the same entity almost instantly reappears as part of the refresh loop of that Location.
> 
> I suggest we use relations as proposed in #1964 to model the `managed-by-location` relationship. It'd simply be a `1-N` relationship between any kind of entity to a `Location` entity. With that we can easily look up the other entities that share the same location.
> 
> This and other things brings up the problem of naming the locations. One possibility if we can't find something else is to simply name it `location-<type>-<target-sha>`.

Good point about the naming in any case. That IS an unsolved problem in the current catalog. But as far as I'm concerned, we could just keep giving them UUIDs as names, because nobody ever looks at those besides from an API + code standpoint.

We used to have the managed-by-location point to a location ID instead of a type/target, and I argue that after changing it to the current method we have a better model to stand on. If we go back, it's just "the old locations table but with extra (worse) steps" :)

> > This way, entities will be self-sufficient in terms of refreshes. Locations will be regarded more as bootstrapping sources, that continuously spawn entities that can then be refreshed on their own.
> 
> So to re-iterate, what is the benefit of self-sufficient non-location entities? 😅

That the refresh loop works no matter what, and the use of Location kind entities actually becomes entirely optional. They are just a way of saying "keep looking in this place for new entities". It lets you have a place to put the fact "keep refreshing from the legacy catalog". At Spotify, we could add a single `styx` location. Then everything would flow from that, in terms of that source. If that one is accidentally removed or whatever, things keep working, the entities keep getting refreshed. If the entities start arriving from a different source (a hypothetical `styx2`) it'll just transition silently to that if you add that as a source.

But that last point, to me, rather highlights that maybe this should ALL be external processes in the first place. Maybe the catalog should not even know of these things, but be fed reactively from outside sources instead, that may have the smarts to talk to those outside systems.

**Comment by Rugvip** [comment]
> See below - it is the same loop as before essentially, it just basically feeds itself from Location entities and entity annotations instead of from the locations table.

Ok, sounds like we agree we want to keep the global refresh loop around as is then? I got the locations now being entities bit, just wondering if we would also have a separate loop that updates individual entities.

Note that just because we're switching to not having a locations table doesn't mean we have to start being able to refresh based on locations stored in the catalog itself. The root of all the processing can still be the single "bootstrap" location or similar concept, that in turn causes various processors to go fetch data from various sources and build out the location tree.

> > > We suggest that locations as a separate table and concept are eliminated, and that we instead lean into using the `Location` entity kind. Users will register `Location` entities using direct POST requests to the entities API, and these will be used as sources for finding more entity data during the update loop.
> > 
> > I think we actually need to move away from supporting direct `POST` of entities to the catalog. It has some security implications that are tricky to deal with, and we could allow for a separate plugin to cover the same functionality. I'm actually not sure what the use-case for `POST`ing non-location entities to the catalog even is?
> 
> I kinda argue the other way around, that that should be the only proper way. It does require authorization to work before being secure. I argue that the refresh loop is what should be a completely external process, that reads Location entities and POSTs updates back based on what it reads.
> 
> Web hook driven workflows would be the exact same. An external process receives the webhook, reads out the actual entity data in the manner that fits the originator of the webhook, and POSTs that to the catalog. The catalog would be reduced to not much more than a dumb datastore in that regard.

Building the catalog from a collection of microservices will make it very complex imo. I'd prefer to keep the core part of the catalog contained in a single service, that being the processing pipeline and entity cache.

> > For the location registration use-case I'd actually suggest that we look into making that part of the `register-component` plugin, basically making it a separate backend that can be used to keep track of locations. Those registered locations are then in turn brought into the catalog using whatever method we choose ¯_(ツ)_/¯. That'll let organizations that don't want the manual registration feature to simply not have the plugin at all, and it kinda makes sense that it comes as a frontend + backend package too.
> 
> Hm, not sure I follow this one. You mean to NOT use Location entities but instead just move the locations table to an entirely separate database (so to speak) owned by a different plugin? Then what means would that backend actually use to update the resulting entities, if not via POST? How does that interact with a refresh loop?

Nop, still keeping location entities, but demoting manual registration of locations to a separate use-case the you need a plugin to support. We basically already have that though, since the frontend part of it is a plugin.

Being overly verbose and explicit here, but imagine a static location like this on top of a separate location DB:

```yaml
locations:
  type: locations-db
  target: http://location-registry-plugin:7000/api/location-registry/locations
```

Although I could already imagine a more general thing like this :grin:

```yaml
locations:
  type: rest
  target: plugin://location-registry/locations
```

> Good point about the naming in any case. That IS an unsolved problem in the current catalog. But as far as I'm concerned, we could just keep giving them UUIDs as names, because nobody ever looks at those besides from an API + code standpoint.

Yeah UUIDs should work fine too. Either way we'd probably have to tie in some name generation logic into the processing loop. We could strive to make it more human readable if we've got that logic in place anyway though.

> That the refresh loop works no matter what, and the use of Location kind entities actually becomes entirely optional. They are just a way of saying "keep looking in this place for new entities". It lets you have a place to put the fact "keep refreshing from the legacy catalog". At Spotify, we could add a single `styx` location. Then everything would flow from that, in terms of that source. If that one is accidentally removed or whatever, things keep working, the entities keep getting refreshed. If the entities start arriving from a different source (a hypothetical `styx2`) it'll just transition silently to that if you add that as a source.

I don't think this is tied to whether we push or pull from the catalog. With both methods we can choose to either delete all downstream entities instantly or defer deletion to a later point. If we're pulling data from styx, we can simply halt the processing of that sub-tree if styx was down, and simply leave all those entities in place. Eventually they might time out and disappear however, and there could possibly be some user interaction involved there too.

I'd need a better example for the individual entity refresh use-case tbh, if styx is down we can't go refreshing the individual entities anyway? Unless we make assumptions about where we can resume entity processing knowing that there's missing data, but that seems very risky and error-prone. Basically if any node in the tree is broken I think we have to stop processing there and serve old data, regardless of whether we're using a push or pull model for the storage.

> But that last point, to me, rather highlights that maybe this should ALL be external processes in the first place. Maybe the catalog should not even know of these things, but be fed reactively from outside sources instead, that may have the smarts to talk to those outside systems.

In addition to the concerns about complexity above, this really just converts the "catalog" into a schema-enforcing document storage. Our actual catalog would be that and the collection of services built around it. I think that's a fine design of the catalog service itself, but not an area were we should be traversing network boundaries.

**Comment by Fox32** [comment]
One thing I prefer about the location entity compared to the other locations is, that you can pass additional metadata in them. Maybe a location needs more than a type to be interpreted correctly. What I'm thinking about:

I have a `openapi.yaml` file in my repository, that is not yet wrapped in an entity. I could create location that tells the processors that the file has to be converted to an entity first, e.g.:

```yaml
metadata:
  kind: location
  annotations:
    backstage.io/generate-api-entity: Petstore API Name
spec:
  type: url
  target: http://server/openapi.yaml
```

With the API name we can generate an API entity before further processing.

**Comment by freben** [comment]
@Rugvip I'll set aside the external vs internal refresh process discussion, that was an unnecessary distraction for me to bring up anyway :) More of a philosophy / north star goal far-future thing.

On the standalone refresh question: I think my point wasn't about broken original locations. It's actually sort of like using the set of all registered locations + all managed-by annotations, and using that as the input to the existing refresh loop. Slightly simplified.

There may be something to be said here about the distinction between the root of a source of entities, and the location of an entity itself. We may have one single location pointing to the root of a large monorepo, but the 150 actual components therein may want to refer to their actual paths inside of that root. Doubly so if this happens through a location that generated a location that generated a location that generated an entity :)

**Comment by freben** [comment]
Also point taken regarding what the actual roots are. One of the sources for the refresh loop may actually be locations specified in config, i.e ones that were never Location entities at all in the first place.

**Comment by freben** [comment]
@Fox32 Hmm, interesting thought. We haven't yet considered what the model would look like if there were ways of NOT having to write the actual yaml spec for every entity.

Another way could be if a component entity could say essentially `exposesApis: { MyApi: ./openapi.yaml }` in its metadata (just an example, not actual syntax suggestion), which would lead to an API entity with that name automagically being registered and linked on the fly. Kind of like a sidecar to another entity, based off of that entity's info.

You can also do some nifty things with processors in  that regard - you could make one that auto-discovers nearby openapi files that lie next to entity spec files for example. Then it could spawn an "implicit" (file-less) API entity, specified as exposed by that service. Doesn't solve the naming, but there could be ways for that too.

Likewise, finding a pom file next to a service component file and auto-tagging it "java" or similar. I hope to get to experiment with things like that later.

**Comment by mbruggmann** [comment]
@freben Overall I think this will be a good improvement, but I'm wondering if you have considered to be stricter about only processing `Location`? As in, could we drop this:

> Then, the loop will look at all the remaining entities that already had a backstage.io/managed-by-location but haven't yet updated (meaning, they once had a Location but it was removed), and fetch updated contents for them too.

If we only ever refresh from the set of Location entities, that seems more predictable and would more cleanly separate the update loop from the catalog itself. Then we could also be stricter about entities managed by that location, for example to not allow to unregister them at all, you'd need to unregister the Location itself.

**Comment by mbruggmann** [comment]
It's nice though if `Location`s are entities just like the other ones, so we don't need to have a dedicated table? 

In a mixed setting, entities could have annotations like this:
* `backstage.io/managed-by-location: /locations/namespace/location-name` pointing to the `Location` entity that referenced it during the refresh loop
* `backstage.io/managed-by-hook: /hooks/namespace/hook-name` pointing to the `Hook` entity that ingested it (for example one that is backed by a Github app installation)
* `backstage.io/vcs-location: github.com/org/repo/path/to/entity.yaml` (could be there in either case)

Hooks could work similar to Location, in that unregistering a Hook would remove all associated entities from the catalog. Maybe this is touching on something different than the original RFC though, essentially the question of "should you register/unregister components" or "should you register/unregister locations and hooks, which in turn registers/unregisters all components within". Happy to defer that to a later discussion as well.

**Comment by freben** [comment]
Right, but I was thinking about the actual HTTP request mechanics and responsibilities in a push model - if we register a webhook in GHE, where do we point it? How does that lead to entities actually entering the catalog? I was envisioning that mechanic being driven by a small receiver service (possibly as a backend plugin, or hidden entirely within a GitHub app if that's a possibility), that issues a POST creation/update request to the catalog API. I.e. not via any refresh loop system at all.

(yes this is totally a separate offshoot of the original location discussion - maybe i should be asking this elsewhere to not pollute too much - but i find the strict pull refresh loop model limiting :))

**Comment by mbruggmann** [comment]
Not super familiar with this, but something along those lines?
1. Create a GitHub app with a webhook that points to a known endpoint in a Backstage plugin. Probably only need to do this once per Backstage installation.
2. Every time the GitHub app gets installed into a repository, create a Hook entity in the catalog for that repo. We should get an install event in the plugin that we can trigger this on. Scan the whole repo for definition files. 
3. Every time files change in the main branch, check if they are Backstage definitions and update the corresponding entities in the catalog accordingly. We should get a push event in the plugin that we can trigger this on. The catalog updates could be direct API access (since both are running in the Backstage backend in the end) or REST calls. Set the `managed-by-hook` annotation.
4. If the GitHub app gets uninstalled from a repository, remove the Hook and all entities managed by it.
5. Periodically mark entities as stale if the Hook doesn't point to a valid repo anymore, or an entity is managed by an unknown/invalid Hook

Bit unclear how we would do the full repo scan in (2), but should be possibly to list all yaml files, and detect if they fit the expected Backstage schema?

**Comment by freben** [comment]
So 3. relies on them being two different plugins, that are in-process from each other. OK, that clarifies it, even though I would have appreciated if that could eventually be relaxed into using actual REST calls to the catalog (with a service-to-service auth setup).

We have talked about "scannability" for definition files, for example whether we should have some naming pattern that makes them very easily discernible without having to read and parse them. Which of course also helps human eyes. `catalog-info.yaml` is the winning suggestion so far, I believe.

**Comment by Rugvip** [comment]
Webhook change updates can be modeled just like locations, i.e. type + target, for example `github` + `https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/hello-world-api.yaml`, and I think that's really what we could add as an API to the catalog. For example

```bash
curl -X POST localhost:7000/catalog/refresh -d '{"locations":[{"type":"github","target":"https://..."}]}'
```

Given that it's the catalog location processors that know how to fetch new data, refreshing should just become a matter of filtering the refresh locations to only process actual locations covered by the catalog. That's kind of what 3 is in your suggestion above right @mbruggmann? I can think of a couple of other ways of doing that too:

- **A** - Keep the locations table and check if a location exists there, I think this is what you were talking about earlier @freben?
- **B** - Keep in-memory cache of all locations covered by previous refresh loops, and use that for the look up. Each catalog instance would have to do a refresh at startup, at which point we could make the catalog a complete in-memory thing.
- **C** - Treat locations as entities, so that we can look them up in the entities table itself, preferably just by name if we can have a fixed mapping.

You'll notice that C is  what we're discussing in this RFC, so what I'm saying is that treating locations as entities is a solution to how to do individual location refreshes. We simply need to go check if the location exists in the catalog, and if it does we fire that location entity into the processor chain and let that sub-tree of the catalog be refreshed. Deletion would really be handled in exactly the same way as any kind of location deletion, so we can handle that separately too.

The tricky bit would then be additions. This is where the discussion around having external entity registration vs a mutable catalog picks up, since there's really no other way of adding locations atm. Tbh I would love to not have the catalog be any kind of source of truth, that there is no loss of data if you just kill all catalog instances and their DB. With external registration it would be very straight-forward to refresh the entire DB, but adding a single location without a full refresh might require some trickery. Most likely we could add support for individual refreshes in the catalog processor that would be reading from the external service.

Another thing to note is that we might not want to support separate namespaces for locations since that would make  refreshes a bit strange and allow for duplicates. My thinking is that we could force all locations to be in a `locations` namespace? Basically defaulting to that and throwing an error if a location specifies anything else.

Should we make a quick PoC of this RFC along with a refresh API? I would really like to keep the location modelling discussion and the webhook implementation discussion apart, but they do seem a bit too intertwined.

**Comment by andrewthauer** [comment]
I'm not sure if this is relevant to this conversation, #1964, or potentially a new RFC. However, I've been thinking about how API entity spec definitions can be externally read from a different location then the spec. Here's a couple of examples that hopefully highlight what I'm thinking.

```json5
// https://some-host/api-specs/some-service/openapi.json
{
  // openapi spec
}
```

```yaml
# some-service/catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: some-service
  description: some service
spec:
  type: service
  implementsApis:
    - some-service-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: some-service-api
  description: some service api
spec:
  type: openapi
  definition: uri:https://some-host/api-specs/some-service/openapi.json
```

Or perhaps it would introduce a location like:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: some-service-api-location
  description: some service api location
spec:
  uri: https://some-internal-host/api-specs/some-service/openapi.json
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: some-service-api-location
  description: some service api
spec:
  type: openapi
  definition: Location:some-service-api-location
```

**Comment by mbruggmann** [comment]
@Rugvip Not as nice drawings as yours (gotta teach me how you made those some day), but for completeness, I tried to visualize what I meant with the simplified location model:

![catalog](https://user-images.githubusercontent.com/24575/91043630-3b7cf200-e614-11ea-91bf-98aab0d6b83e.png)

Looking at the catalog as a raw entity store, we'd start with POSTing `Location` entities there (1). A location here could refer to a source code repository, a URL, a directory on disk, or some other type of location that has an associated processor. The processors then generate entities for every location (2) either periodically, when a location gets added/updated/deleted in the catalog, or when we get an event on a webhook (matching it to a location first). While the processors could treat their location however they want (eg traversing a file tree on disk), it would not be allowed to generate new locations for other processors. As in, all `Location` entities in the catalog need to be added through the API.

In addition to the entities that are generated by processors from locations, we could still allow manually pushing entities to the catalog (3). Note how treating the location as an entity itself makes (1) and (3) the same API, so it doesn't need a separate endpoint or storage location in the catalog.

![Processing Tree](https://user-images.githubusercontent.com/24575/91044078-fc02d580-e614-11ea-9023-4864020afde7.png)

This approach essentially forces the processing DAG to have depth two, one set of locations which generate one set of entities each. The root, static configuration or location-db use cases would need to instead POST their locations into the catalog through the API. Yaml files with additional "locations" could not cross into other processors at all, eg a yaml in a Github repository root could only refer to other Backstage yamls in the same repository. Not sure if those are acceptable constraints, otherwise we'll probably need something like you proposed.

**Comment by freben** [comment]
@mbruggmann This is pretty much what I had in mind. Thanks for putting it in image and text better than I can.

Just one difference:

> The root, static configuration or location-db use cases would need to instead POST their locations into the catalog through the API.

I think that these could still be "just one more set of inputs to the refresh loop". In my mind Location entities are just one of many possible sources of entities and there's nothing special about them. The catalog could work perfectly fine with only one single config entry that points to a location-db. Or with a single Location entity that points to a location-db. The remaining question then becomes, what will the annotation on the resulting entities look like? Again, in my mind, that's also symmetric with all the rest - a Location entity is just a source of a `type:target` pair, just like a config entry is, just like a location-db entry is. That's what I meant with my comments earlier of continuing to use that pair as the location data vehicle through the processors.

I think it adds up, and has some simplicity benefits.

**Comment by Rugvip** [comment]
@mbruggmann @freben I'm not too fussed about whether locations are entities or not. I'm more concerned with the UX and DX os not properly surfacing each location that is traversed, and the complexity brought in by allowing entities to be posted to the catalog, especially from a security and consistency point of view.

What are you thoughts on why we should prefer the flatter and mutable model? Are there some use-cases that aren't covered otherwise or what's the benefit?

**Comment by Nek** [comment]
Just have to say it. Looking at the proposed architecture and especially global update loop, it looks like we are pretty close to implementing Entity–component–system pattern, except we don't have a generalization typical ECS implementation has (yet). To avoid confusion with our terminology, ECS entities map to our entities, ECS components map to the data our system's entities have, ECS systems are processors. The main difference is entities+components in ECS are basically a flat data storage you can query and are not modelled as a hierarchy of classes. The drawback is not having strictness while developing, the benefit is high flexibility and extensibility of the system. I've started having thoughts about it looking at all the juggling we do with classes to model the system. Not sure if this is helpful for the any actual code changes, but could be as a mental model. Would like to hear opinions if this is actually close to what we have now and if this is useful in any way.

**Comment by benjdlambert** [comment]
Ongoing work still 👍

**Comment by freben** [comment]
It's time to close this RFC! For the interested reader, here's a summary of what the design ended up looking like.

The core of the catalog processing engine has seen a major rewrite, with the goal of being able to properly distribute work among multiple catalog service instances and opening up for future capabilities. As part of this rewrite, we decided to keep the `locations` table intact. However, on a code level, a new interface called `EntityProvider` was broken out from the previous monolith. There are two providers out of the box - the app-config based provider, and the location database based provider. They both serve as "seeds" of machine generated `Location` kind entities into the processing loops. After that, the regular catalog processors go to work on the emitted locations which ultimately results in a directed graph of processed entities that relate to each other.

This also opened up for a future possibility of making a third `EntityProvider` - one that has its own backing entity storage that users can POST/PUT/DELETE full entities into via a REST API, and which then is also "seeded" into the processing loops. Nothing else in the catalog core has to change for this. This provider is probably not something we'll build ourselves but it can easily be contributed by the community.

The discussions also touched on event driven updates. That is another possibility which was largely enabled by the catalog rewrite, but the mechanics of what the interface for such updates should look like, is still under consideration.

Thanks for all of your input and valuable discussion on this RFC. <3 Let us know on Discord or in issues if there's additional design or further needs that should be considered.
