### ISSUE TITLE
🐛 Bug Report: CostInsight interval doesn't look consistent 

### ISSUE THREAD

**Issue by Nereis** [backstage/backstage#20035]
### 📜 Description

Today is the 2023-09-20

In my understanding of ISO8601, intervals are defined such as repetition/interval/startdate. I'm getting the following readings from cost insight intervals:

Past 6 months: R2/P90D/2023-01-02
Past 60 days: R2/P30D/2023-01-02
Q3 vs Q4: R2/P3M/2023-01-01

Start date is always more or less the beginning or year while it should be the beginning of the interval.

Side note: IMHO the interval for the total cost looks also wrong as it's not a comparison requiring R2 but a full range requiring R1. 

In the meantime, is there anyway to override the interval calculation to provide custom display name and intervals? Our company bill monthly and reports with yearly comparisons.  

### 👍 Expected behavior

Start date should be now()-repetition*interval for the last X Days/Month. Standard range for quarters. 

Past 6 months: R2/P90D/2023-03-24
Past 60 days: R2/P30D/2023-06-22
Q3 vs Q4: R2/P3M/2023-07-01

### 👎 Actual Behavior with Screenshots

Past 6 months: R2/P90D/2023-01-02
Past 60 days: R2/P30D/2023-01-02
Q3 vs Q4: R2/P3M/2023-01-01

### 👟 Reproduction steps

Start costinsight and logs intervals from getGroupDailyCost and getProductInsights methods

### 📃 Provide the context for the Bug.

To calculate the interval to query the db, we can't use the startdate from the interval. last X D/M is easy to fix by using today date as starting point but P3M requires a distinct mapping breaking generic compatibility of interval conversion. 

### 🖥️ Your Environment

```
OS:   Linux 5.15.90.1-microsoft-standard-WSL2 - linux/x64
node: v18.13.0
yarn: 3.6.3
cli:  0.22.12 (installed)
backstage:  1.17.5

Dependencies:
  @backstage/app-defaults                          1.4.2
  @backstage/backend-app-api                       0.5.2
  @backstage/backend-common                        0.19.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-openapi-utils                 0.0.3
  @backstage/backend-plugin-api                    0.6.2
  @backstage/backend-tasks                         0.5.7
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.3
  @backstage/cli                                   0.22.12
  @backstage/config-loader                         1.4.0
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.9.1
  @backstage/core-components                       0.13.4
  @backstage/core-plugin-api                       1.5.3
  @backstage/dev-utils                             1.0.20
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.18
  @backstage/integration                           1.6.2
  @backstage/plugin-api-docs                       0.9.10
  @backstage/plugin-app-backend                    0.3.50
  @backstage/plugin-app-node                       0.1.2
  @backstage/plugin-auth-backend                   0.18.8
  @backstage/plugin-auth-node                      0.2.19
  @backstage/plugin-catalog-backend-module-ldap    0.5.17
  @backstage/plugin-catalog-backend-module-msgraph 0.5.9
  @backstage/plugin-catalog-backend                1.12.4
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.35
  @backstage/plugin-catalog-import                 0.9.13
  @backstage/plugin-catalog-node                   1.4.3
  @backstage/plugin-catalog-react                  1.8.3
  @backstage/plugin-catalog                        1.12.4
  @backstage/plugin-cost-insights-common           0.1.1
  @backstage/plugin-cost-insights                  0.12.12
  @backstage/plugin-events-node                    0.2.11
  @backstage/plugin-github-actions                 0.6.4
  @backstage/plugin-home-react                     0.1.2
  @backstage/plugin-home                           0.5.7
  @backstage/plugin-org                            0.6.13
  @backstage/plugin-permission-backend             0.5.25
  @backstage/plugin-permission-common              0.7.7
  @backstage/plugin-permission-node                0.7.13
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.3.2
  @backstage/plugin-scaffolder-backend             1.16.5
  @backstage/plugin-scaffolder-common              1.4.0
  @backstage/plugin-scaffolder-node                0.2.2
  @backstage/plugin-scaffolder-react               1.5.4
  @backstage/plugin-scaffolder                     1.14.4
  @backstage/plugin-search-backend-module-catalog  0.1.6
  @backstage/plugin-search-backend-module-pg       0.5.11
  @backstage/plugin-search-backend-module-techdocs 0.1.6
  @backstage/plugin-search-backend-node            1.2.6
  @backstage/plugin-search-backend                 1.4.2
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.4
  @backstage/plugin-search                         1.3.6
  @backstage/plugin-tech-radar                     0.6.7
  @backstage/plugin-techdocs-backend               1.6.7
  @backstage/plugin-techdocs-module-addons-contrib 1.0.18
  @backstage/plugin-techdocs-node                  1.7.6
  @backstage/plugin-techdocs-react                 1.1.9
  @backstage/plugin-techdocs                       1.6.8
  @backstage/plugin-user-settings                  0.7.8
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.2
  @backstage/theme                                 0.3.0, 0.4.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Nereis** [comment]
Playing around, it looks intervals are tied to the function getLastCompleteBillingDate(). 

I'm not getting the point as interval display name are last XXX Days/Month and quarter Q3/Q4 Interval should always be based on today date or display name should be update to reflect such behavior to the user. 

Nonetheless, it looks still wrong. Today is the 2023-09-26 and getLastCompleteBillingDate() is the same (_Billing data as of 2023-09-26_)

Past 6 months: R2/P90D/2023-09-27 
Past 60 days: R2/P30D/2023-09-27
Q3 vs Q4: R2/P3M/2023-07-01

Intervals start date look to be equal to getLastCompleteBillingDate() + 1 which is still wrong since it would be the enddate. Quarter startdate still doesn't match the effective quarter as of the display name (Q3 Q4)

**Comment by Rugvip** [comment]
@timbonicus in case you want to have a look 🙏

**Comment by timbonicus** [comment]
@Nereis Thanks for filing, catching up on this and looking to understand the bug report.

> In my understanding of ISO8601, intervals are defined such as repetition/interval/startdate

This is incorrect, [ISO8601](https://en.wikipedia.org/wiki/ISO_8601#Repeating_intervals) defines intervals in the format used in Cost Insights as repetition/duration/**enddate** (rather than startdate). There are other formats one can use to define the start date, but of primary interest in this case is the end date.

As you point out, the end date Cost Insights uses comes from `getLastCompleteBillingDate`. This is due to the fact that billing data necessarily lags behind reality, sometimes on the order of days or weeks (depending on the billing delivery completeness of a given cloud provider).

> Interval should always be based on today date or display name should be update to reflect such behavior to the user.

Basing intervals on today's date would lead to the undesirable result of graphs appearing to drop suddenly to 0, as billing data for at least the current day is usually not yet available. I agree that "Past 60 days" and "Past 6 months" are slightly misleading; we display the last complete billing date above the charts to try and signal the nuance. This was done in the interests of having a brief, mostly-understandable-if-slightly-inaccurate label for the period selection. Do you have a suggestion for a terse alternative to show in the dropdown?

Cost Insights does take some liberties with the P3M duration, as [mentioned here](https://github.com/backstage/backstage/blob/b5b00b3af1bbe568c02917b1dda331f72186fbae/plugins/cost-insights/src/types/Duration.ts#L18), to interpret as "Last two completed quarters". This should be handled internally within Cost Insights and calculated based on `getLastCompleteBillingDate` again.

> In the meantime, is there anyway to override the interval calculation to provide custom display name and intervals?

This is not possible at the moment; PeriodSelect [accepts options](https://github.com/backstage/backstage/blob/b5b00b3af1bbe568c02917b1dda331f72186fbae/plugins/cost-insights/src/components/PeriodSelect/PeriodSelect.tsx#L52), but this called [without that argument](https://github.com/backstage/backstage/blob/b5b00b3af1bbe568c02917b1dda331f72186fbae/plugins/cost-insights/src/components/CostOverviewCard/CostOverviewCard.tsx#L120) in Cost Insights and there's no config to override the default options right now.

**Comment by Nereis** [comment]
@timbonicus Thank you for checking! Indeed, I read your link and the format use is enddate and with the getLastCompleteBillingDate explanation, it make more sense. I'm not sure where I read startdate, sorry for that. 

> I agree that "Past 60 days" and "Past 6 months" are slightly misleading

You could replace the Past by Interval _60 days interval_, emphasis the Billing date with an explanation or put a tooltips somewhere ( (i) close to the dropdown?)

> Cost Insights does take some liberties with the P3M duration 

I miss the documentation note but now I fixed the date, I have the following 

![image](https://github.com/backstage/backstage/assets/4352982/fecb4ada-024b-4213-a345-3b062f5e3afe)

IMHO you can't keep the current label with your calculation. Q2 is Q2 with a fixed date. From the user point of view looking at the graph, it would mean a comparison of the two ended quarter to see the evolutions. Since Q2 is now done, this is even more misleading. If you want to keep the last completed quarter it's basically the last 9 month thus you could name it "9 Month interval" to avoid confusion but I think have the true quarter is a nice feature too.

**Comment by Nereis** [comment]
> This is due to the fact that billing data necessarily lags behind reality

Indeed but user also want to follow the current cost. It could be nice to have both interval like "Ongoing cost past 90 days" from today with ongoing cost and "Billed 90 days interval" calculated for the two last month since most cloud looks to have correct calculation by month.

**Comment by timbonicus** [comment]
@Nereis Sorry for the delayed reply, this one fell through the cracks.

> IMHO you can't keep the current label with your calculation. Q2 is Q2 with a fixed date. From the user point of view looking at the graph, it would mean a comparison of the two ended quarter to see the evolutions.

I'm afraid I don't understand your point here, could you elaborate? The "Q1 2023 vs Q2 2023" will show costs for those two completed quarters. That is, this will pull costs from the 6 month period of 2023-01-01 to 2023-06-30. Cost data from **after** 2023-06-30 will not be shown with this option select, even if it's 2023-09-10 today.

> If you want to keep the last completed quarter it's basically the last 9 month

I'm not following, there is no selection in this dropdown that will show 9 months of data.

> Indeed but user also want to follow the current cost. It could be nice to have both interval like "Ongoing cost past 90 days" from today with ongoing cost and "Billed 90 days interval"

Is the difference you perceive between these two that "ongoing cost" will show potentially incomplete costs? That is, we can show some cost data for **today**, for example, but it may not be complete?

In actual usage of this plugin at Spotify, we found this strongly undesirable because it appears completely misleading. You'll frequently have a chart that drops to 0 on the current day, which many users find alarming. We also had instances where cost data spiked **up** dramatically when showing incomplete cost data, because in GCP's case the SKU credits tend to be added into billing data after raw resource utilization is calculated.
