### ISSUE TITLE
🐛 Bug Report: Techdocs heading navigation is broken

### ISSUE THREAD

**Issue by user1bh** [backstage/backstage#20159]
### 📜 Description

Hello :) Locally and when using live Backstage demo (https://demo.backstage.io/docs/default/component/backstage/conf/writing/) navigation backwards and forwards between Techdocs heading links (e.g. root and headings, or between headings, or from current page position and heading) is broken.

### 👍 Expected behavior

When going back and forward between headings and the previous page position - the page positions should be adjusted accordingly. An example of proper navigation: https://www.mkdocs.org/getting-started/ check how it works when navigating from current position to heading and then back.

### 👎 Actual Behavior with Screenshots

[backstage-navigation.webm](https://github.com/backstage/backstage/assets/146061710/bec6215a-19cb-4838-a12b-e9743d8d5bff)

### 👟 Reproduction steps

Reproduction steps are shown on the attached video using live Backstage: https://demo.backstage.io/docs/default/component/backstage/conf/writing/

### 🖥️ Your Environment

Tried in both latest Chrome and Firefox browsers.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by squid-ney** [comment]
Hi there! Thanks for reporting.

Digging into the code a bit, I noticed that there is logic to scroll to the correct anchor/heading when a page refresh happens. The `transformer` , [scrollIntoAnchor.ts](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/transformers/scrollIntoAnchor.ts), handles this. The transformer listens for the `SHADOW_DOM_STYLE_LOAD_EVENT` before scrolling to the correct anchor. The event `SHADOW_DOM_STYLE_LOAD_EVENT` is not triggered by browser forwards and backwards navigation through the TechDocs headings. This explains why if you open a link to a TechDocs heading in a new tab, you will be scrolled to the correct heading, but if you use browser forwards and backwards navigation, you will not be scrolled to the correct heading.

I am looking into a fix that will listen for changes in the `window.location.hash` instead of for the `SHADOW_DOM_STYLE_LOAD_EVENT` event.

**Comment by user1bh** [comment]
@squid-ney thanks for your time fixing the issue 🙏
