### ISSUE TITLE
🚀 Feature: Name aliases for Group entity

### ISSUE THREAD

**Issue by kiranbayram** [backstage/backstage#20230]
### 🔖 Feature description

At our organisation we have aliases for Group name which enables us to link components with groups without big migration effort. I couldn't find a related issue, so I'm sorry in advance if this is duplicate. Thanks 🙏 

### 🎤 Context

At our organisation we have aliases for Group name which enables us to link components with groups without big migration effort. I couldn't find a related issue, so I'm sorry in advance if this is duplicate. Thanks 🙏 

### ✌️ Possible Implementation

I do not know

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kiranbayram** [comment]
Hey @freben, could you please have a look at this and let me know how easy/hard to implement this? Thanks in advance

**Comment by freben** [comment]
How are those aliases stored? Can you describe a bit more what your data looks like?

One requirement from the catalog is that relations between entities must point to the actual entity refs of the targets - no aliasing can be had at that level. So whatever we do, it needs to result in valid entity refs in the end.

I guess you have the option of

- Either setting `metadata.name` to the alias, and referring to that alias everywhere, always - but at that point they are not really aliases anymore, but just regular names behind a curtain
- Or putting the aliases somewhere else in the entity body, and using a custom processor for the entities which looks up the aliases to translate them to entity refs.

```yaml
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nigel.manning
  alias: user-alias-444
spec:
  memberOf: [group-alias-555]
```

when processing that entity, the processor would look up in its cache what group that alias `group-alias-555` really refers to, and emits a relation that points to that real `metadata.name` instead of the alias.

I'm not entirely sure about all of this, just some ideas to get you started, since I don't know the full picture.

**Comment by kiranbayram** [comment]
Thanks for the response, let me try the explain my usecase with some example data

I would like to have the group entity defined as below:
```
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: some-group
  aliases:
    - crazy-group
    - finance-team

```

And whenever a Component entity has `spec.owner` field with `group:finance-team` value, then Backstage should recognize that the referred group is in fact `some-group` and show the correct owner link in the UI.

I think the second option you explained looks more fitting to the usecase.
