### ISSUE TITLE
Plugin: Notifications

### ISSUE THREAD

**Issue by mareklibra** [backstage/backstage#20312]
### 🔖 Summary

The Notification API and its front-end representation is a long-time requested feature (upstream [RFC 10652](https://github.com/backstage/backstage/issues/10652), issue [639](https://github.com/backstage/backstage/issues/639)).

The result of this effort will be implementation of both the back-end and front-end parts.

The API will be exposed as a REST service, implemented as a back-end plugin, backed by a relational database (for the time being the PostgreSQL).

In addition, there will be a front-end plugin implemented providing alerts and a page listing/managing the notifications.

### ✌️ Context

- https://github.com/backstage/backstage/issues/10652
- https://github.com/backstage/backstage/issues/639

We recently plan to deliver that feature as a part of the Janus IDP backstage plugins project and further work on promoting it to the Backstage upstream: https://github.com/janus-idp/backstage-plugins/issues/817

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Awesome! 😁 

What's the scope of the notification area that you're looking at? I can see at least the following angles to a full-fledged notification system:

1. Frontend notification popups - and API for showing and interacting with notifications popups, probably including the Web Notification APIs. An important aspect of this is that each individual plugin likely needs to be able to control the rendering of their own notifications and respond to actions, a bit like the result items in the search plugin
2. Signalling channel - #18153, a channel for sending messages from backend plugins to frontend users, just a piece of underlying infrastructure
3. Notification service - A backend service for backend plugins to post notifications, important part is an agreed upon contract for the serialized notification format so that plugins know how information to provide
4. Persisted notifications - frontend and backend plugins for a more persistent space to view new and past notifications with read receipts, shared across user devices, etc
5. External notifications - connections to send notifications to external systems, slack etc. Either a separate service or built directly into a notifications backend in a pluggable way

From what you describe I gather than you're at least looking at (4) and potentially anything above. I'm curious if you have a different view of the architecture as well, or does what I listed above make sense?

**Comment by mareklibra** [comment]
@Rugvip , thank you for shaping the view on the requirements.

As mentioned, a complete notification system is complex, a lot of different parties involved and with different priorities for its subparts. A solution might be in their identification and phasing-out delivery of the features. Probably a solution one-fits-all is not a good approach either.

My original motivation is close to the point 4 - external systems or plugins can send status messages or hints for the next user actions.
That's the point of having a persistent storage and a REST API in place.
I am considering leveraging WebSockets to support the "watch" feature instead of just polling.

By having such REST service, the point 5 gets perfectly feasible. The "additional adapters" can be added to monitor the notifications and eventually forward them to other cosumers (like SMTP or slack).
They can be implemented and deployed independently, without any changes needed to the REST service.

**Comment by mareklibra** [comment]
Can you please clarify what is the difference between point 2 and 3?
I am not sure about the use-cases behind them - they would drive the decision about reusability of the same REST with its persistence.
Or maybe a second API/service is needed, not sure at this moment.
Amount, size, flexibility, delivery delays, type, durability and count of consumers - they all need to be considered here.

**Comment by mareklibra** [comment]
As a part of this effort, a front-end Notifications API will be introduced - shielding the frontend-plugin developer from the communication with backend.
Such new Notificaitons API can even merge notifications from multiple sources or provide primitives to access each of them from the single point, making it compact by reusing TypeScript definitions for the different kinds.

**Comment by mareklibra** [comment]
**The point 1,** the use of [Web Notification API](https://developer.mozilla.org/en-US/docs/Web/API/Notification)  can be implemented independently on this effort. Maybe on top of it or just providing primitives to ease ad-hoc firing of desktop notifications by plugins at their will. Since none of these two approaches contradicts to what I am recently aiming at, I would keep that for an independent effort or addition.

**Comment by sharadpattanshetti** [comment]
It is better to provide option to configure different notification mechanisms like MS Teams channel or Email or Slack. Something similar to New Relic destinations. This way if there is connectivity from backstage instance to respective notification tool then it can easily set up.

**Comment by Rugvip** [comment]
@sharadpattanshetti we actually discussed this a bit and think that we can keep the implementation of a in-app notification system completely separated from external notifications for now. That is, we could build a solution that lets you send notifications through for example MS Teams as a standalone service for now. We may then in the future connect the two by introducing logic to the notifications backend that calls to the external notifications service.

**Comment by Rugvip** [comment]
Hi @mareklibra, what's the status of your work towards this? Does it fit to set something up to dive into more details?

**Comment by freben** [comment]
@mareklibra @drodil closing this now that this is on a roll!
