### ISSUE TITLE
🐛 Bug Report: ResizeObserver loop completed with undelivered notifications [CustomizableHomepageGrid]

### ISSUE THREAD

**Issue by kunickiaj** [backstage/backstage#20712]
### 📜 Description

When using the new backend system (1.19, or 1.18) when the CustomizableHomepageGrid is used an error will display "ResizeObserver loop completed with undelivered notifications". The movement of widgets and resizing of widgets is completely broken (resize vertically only, cant be moved horizontally).

### 👍 Expected behavior

It should not have ResizeObserver errors and widgets should work properly.

### 👎 Actual Behavior with Screenshots

<img width="1201" alt="Screenshot 2023-10-20 at 08 54 43" src="https://github.com/backstage/backstage/assets/746474/4ae93a05-0530-4457-bae8-276da5541b96">

### 👟 Reproduction steps

1. Install the home plugin
2. enable the customizable homepage
3. migrate to the new backend system
4. open the customizable homepage

### 📃 Provide the context for the Bug.

Some other reports of this issue as well in [Discord](https://discord.com/channels/687207715902193673/687235481154617364/1153712531429396534)

This appears to be caused by the measureBeforeMount flag which prevents the widgets from showing any resize animation on mo

https://github.com/backstage/backstage/assets/746474/401bb4f6-33ef-4283-ac77-47578dbabce5

https://github.com/backstage/backstage/assets/746474/ee549af9-41e5-4970-a315-f2f2c3247707

unt. Disabling this flag will resolve the error but will cause the unwanted resize animation.

### 🖥️ Your Environment

Backstage 1.19.1, home plugin 0.5.9
migrated to new backend system.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kunickiaj** [comment]
Actually finding the grid is pretty broken on 1.19.x -- resizing a widget only seems to work vertically and undesired resizing sometimes happens on load/reload/save

**Comment by awanlin** [comment]
Have the same issue with enabling this on the Demo site today, can't resize horizontally. I didn't get the error though

**Comment by kunickiaj** [comment]
I'm still trying to pinpoint the reproduction scenario because I got upgraded and new back ended and still working by ensuring not to upgrade any packages unnecessarily. Running a yarn upgrade I think will break things though and not sure which is the offending package or packages.

**Comment by camilaibs** [comment]
@awanlin could this be related?
https://github.com/react-grid-layout/react-grid-layout/issues/1940
Note: I was able to reproduce the resizing error here: https://github.com/camilaibs/backstage-issue-20712.

**Comment by awanlin** [comment]
Looks like it @camilaibs, thanks for the fix. Not sure if that would also resolve the "ResizeObserver loop completed with undelivered notifications" error as I can't reproduce that myself. @kunickiaj, any thoughts?

**Comment by camilaibs** [comment]
> Looks like it @camilaibs, thanks for the fix. Not sure if that would also resolve the "ResizeObserver loop completed with undelivered notifications" error as I can't reproduce that myself. @kunickiaj, any thoughts?

Thanks for quick replying @awanlin 🙏🏻 

I believe it should prevent the resize error as well because the library started using `ResizeObserver` on version 1.4.0, [here](https://github.com/react-grid-layout/react-grid-layout/pull/1839/files) is the pull request.

According to [this](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors) documentation, the error can occur when the resize callback is invoked before the screen painting.
To verify it I created a [patch](https://github.com/camilaibs/backstage-issue-20712/compare/patch-react-grid-layout?expand=1) to try out wrapping the resizing callback in a `requestAnimationFrame` and that apparently prevent the error, the fix could be simple on the `react-grid-layout` side.

Would you like to open an issue on the [react-grid-layout](https://github.com/react-grid-layout/react-grid-layout/issues) repo for the resize-specific error @backstage/discoverability-maintainers ?
