### ISSUE TITLE
🚀 Feature: MAX_CONTENT_SIZE should be configurable

### ISSUE THREAD

**Issue by fyyyyy** [backstage/backstage#20760]
### 🔖 Feature description

`const MAX_CONTENT_SIZE = 64 * 1024;`

If there is no specific reason for this limitation, MAX_CONTENT_SIZE should be made configurable via ENV

https://github.com/backstage/backstage/blob/b24a1cb45d8f87307f8ecf19471f79eaab1ee854/plugins/scaffolder/src/next/TemplateEditorPage/DryRunContext.tsx#L64

### 🎤 Context

Max content size is hardcoded, which results in my template schema file with 6000 lines to be rendered as `<file too large>`

### ✌️ Possible Implementation

`const MAX_CONTENT_SIZE = process.env.MAX_CONTENT_SIZE  || 64 * 1024;`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
This limit was actually even reduced from a higher value in https://github.com/backstage/backstage/pull/12176, see the related issue for some discussion on how this actually has effects on the back end side of things because of the express body parser.

**Comment by freben** [comment]
Note also that the process env isn't available in the code you linked to, since it's on the browser side.

**Comment by fyyyyy** [comment]
> This limit was actually even reduced from a higher value in #12176, see the related issue for some discussion on how this actually has effects on the back end side of things because of the express body parser.

Is there a way to fix this on the backend side? Its a limitation for us with enterprise schema files which are a couple thousand lines.

**Comment by freben** [comment]
Yeah [this](https://github.com/backstage/backstage/blob/88bc6e27a213fd8ecb24d91ad809864ac6dfb29e/plugins/scaffolder-backend/src/service/router.ts#L224) is where it's being set to a fixed value at the top of the router chain.

We talked about this, and one idea was that maybe we could set the body parser only on the dry run route with a much higher value, and with a more sensible value on all of the other routes.

But whether we do that or keep it at the top, I realize we will have to make this a config parameter so that both the frontend and the backend obey the same limit. So that would entail something like adding a `scaffolder.servicePayloadSizeLimit` or so, with a `@visibility frontend` on it.
