### ISSUE TITLE
🐛 Bug Report: kubernetes.proxy permission is not working

### ISSUE THREAD

**Issue by deepan10** [backstage/backstage#20791]
### 📜 Description

`kubernetes.proxy` permission is not working, I followed the document `https://backstage.io/docs/features/kubernetes/proxy`  to set the permission policy.

### 👍 Expected behavior

I could get the `request.permission.name` to `kubernetes.proxy` but I am not getting the permission

### 👎 Actual Behavior with Screenshots

When I access Kubernetes entity it should undergo permission backend to validate the kubernetes.proxy permission

### 👟 Reproduction steps

1. Create a new app with the latest version
2. Install and configure Permission, Kubernetes plugins 
3. Access the newly created Backstage app
4. Navigate to the entity where it has Kubernetes Resource 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jamieklassen** [comment]
Can give a little more detail regarding the expected behavior? It sounds like you configured a policy like this:

https://github.com/backstage/backstage/blob/3c2eae109fd8d42248d7c4977476fb7383d924bb/docs/features/kubernetes/proxy.md?plain=1#L80-L92

and when you visit the kubernetes tab, were you expecting it to be completely disabled? The only way I can think to observe the effect of disabling the proxy is that the pod logs dialog should fail with a 403. Otherwise the other kubernetes-related features (which do not depend on the proxy endpoint) are unaffected.

**Comment by deepan10** [comment]
Hello @jamieklassen ,
I misunderstood that the Kubernetes proxy permission for the resources too. Thanks!!
