### ISSUE TITLE
[TechDocs] optional techdocs-ref annotation. 

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#2099]
Right now, you need to define a techdocs-ref annotation pointed to where your documentation lives in your `something-info.yaml` file ([example](https://github.com/spotify/backstage/blob/master/catalog-info.yaml#L10)) to get documentation generated and available in TechDocs. 

To avoid this step of configuration, one should be able to use the annotation to connect for example a standalone docs project to your entity **but** if you have docs with code in the same project, you should not have to define the techdocs-ref.

**Comment by freben** [comment]
I think it's worthwhile to always show a docs tab on the entity at least, unconditionally. When the user visits the tab, we can inspect whether there actually seems to exist docs for the entity (through any means necessary - looking for an annotation, and if none exists, go looking in some default place, etc). If they don't, show an empty state that helpfully explain how to get going.

**Comment by freben** [comment]
It could even offer to show the README.md of the project or the docs folder itself, if it's a github location - etc.

**Comment by kuangp** [comment]
I have a use-case that might relate to this issue.

We have a standalone docs project that we've registered as a separate entity. We also have multiple components that is associated with the standalone documentation. We would like to be able to connect those components to the same standalone doc entity so that their 'Docs' tab will display the same documentation. 

Currently adding the annotation pointed to the same doc source repo creates a separate identical doc entry for each component in the techdocs catalog. An alternative could be to split up the documentation itself for each component but that is less desirable since the content is very closely related semantically.

**Comment by awanlin** [comment]
+1 to @kuangp's comment. We are in a similar spot. Our repos contain multiple things - website, service, API, etc. - and the documentation for all of them are in a Documentation folder at the root. Would be awesome if they could be pointed to the same TechDocs site and not have to generate the same thing individually.

**Comment by jh-sh** [comment]
@kuangp @awanlin not sure, just thinking. Have you tried to refer to the existing tech doc ref in the template you create new repos from? If that works with the v2beta schema, you may try to target any standalone repo, on some special step.

**Comment by taras** [comment]
@awanlin have considered [mkdocs-monorepo-plugin](https://github.com/backstage/mkdocs-monorepo-plugin)? I'm curious if it'd work for you.

**Comment by taras** [comment]
It looks like @Fox32 already implemented this in their project https://discord.com/channels/687207715902193673/714754240933003266/832281192635695104

**Comment by kuangp** [comment]
I'm still interested in this enhancement

**Comment by taras** [comment]
@kuangp I can share with you the implementation that @Fox32 shared with me.
