### ISSUE TITLE
🔌 Plugin: Service Health

### ISSUE THREAD

**Issue by sammbetts** [backstage/backstage#21262]
### 🔖 Summary

This plugin displays the status and active incidents of third party services directly in Backstage.

### 🌐 Project website (if applicable)

https://github.com/sammbetts/backstage-plugin-service-health

### ✌️ Context

- This plugin uses the third party services public status API.
- Real time display of services current status.
- If an active incident is happening, a drop down will appear below the service to display more details.
- Only the most recent incident update message is displayed.
- Links to the services full public dashboards and to the specific ongoing incident.
- A Card component to display an overview of the status's on the homepage.
- Ability to enable slack notifications for alerting of new incidents.

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @sammbetts, this is a nice plugin and would be super handy! Did you want to add it to the Plugin Directory? Would be great to see it there. Docs on how to do that are here: https://backstage.io/docs/plugins/add-to-directory. Feel free to tag me in the PR and I can help review 🚀

**Comment by ChrisJBurns** [comment]
We just realised this would be really handy. There are things like https://github.com/louislam/uptime-kuma out there but in tandem with the philosophy of Backstage and it being **the** portal for all important information about organisations services estate, it would make sense to make a plugin that does StatusChecks to avoid having to have extra URLs bookmarked for people.

In general there is the wider question for people who install Backstage into a Kubernetes cluster, which is, would you want to use Backstage as a status check? Because what happens if the Cluster goes down, or if Backstage goes down? Status Check applications are sometimes seen to be special software that sits in it's own isolated world where it is far away from anything that changes from day to day operations that could disrupt it. However, I think that's more of a question for those adopting Backstage into their organisations, as opposed to something Backstage needs to worry about.

I still think that it would be a great plugin to have! ❤️

**Comment by Rugvip** [comment]
Gonna close this since the suggested plugin exists
