### ISSUE TITLE
🐛 Bug Report: DaemonSets do not appear in cluster accordion

### ISSUE THREAD

**Issue by kerenbenzion** [backstage/backstage#21427]
### 📜 Description

I have installed the k8s plugin and I am monitoring couple of my k8s clusters

When I have the labels both on my daemonset and on the pods it shows the following: 
![image](https://github.com/backstage/backstage/assets/48645213/151e8329-346d-480c-969b-5da14ced34fc)

but when I remove it from my daemonset and keep it on the pods I see it: 

![image](https://github.com/backstage/backstage/assets/48645213/290b9dfa-45bb-44aa-b72c-155395f7d40b)

### 👍 Expected behavior

I expected to see the daemon set the same as I see the deployment, that backstage will show me the deployment information and also how many pods we have in that deployment only for daemonset

### 👎 Actual Behavior with Screenshots

When I put the labels on the daemonset I did not see any data for this specific cluster

### 👟 Reproduction steps

1. go to a component which have k8s resources 
2. add annotation to the daemonset 
3. check if you see data in backstage
4. remove annotation from the daemonset and leave it on the pods only 
5. check what you see in backstage

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jamieklassen** [comment]
Giving a little context: you can see here:

https://github.com/backstage/backstage/blob/297e9a5d801bdbce87ed035ba696e274c666176c/plugins/kubernetes-react/src/components/Cluster/Cluster.tsx#L141-L172

that the cluster accordion only has entries (sub-accordions) for the following types:
* custom resources
* Deployments
* StatefulSets
* Ingresses
* Services
* CronJobs

so maybe it makes sense to add a case for DaemonSets.

In fact, digging in to the history, #11505 is a nice example of a PR adding support for a new workload type in the front- and back-end. However DaemonSets were added a bit later in #13053 by @Smorenoz -- we happen to work together and he only needed the backend change since our backstage app uses a custom frontend plugin for Kubernetes. So naturally we missed this!

**Comment by hwlee96** [comment]
Could I propose for Jobs to be considered as a sub-accordion under the cluster accordion as well? And not require it to be encapsulated by a CronJob accordion, since Jobs can be created, independent on a cronjob.

**Comment by jamieklassen** [comment]
> Could I propose for Jobs to be considered as a sub-accordion under the cluster accordion as well? And not require it to be encapsulated by a CronJob accordion, since Jobs can be created, independent on a cronjob.

Probably a fine feature as well; maybe worth filing a separate issue, since a comment on this issue might get missed.

**Comment by andmagom** [comment]
PR https://github.com/backstage/backstage/pull/23034
