### ISSUE TITLE
🚀 Feature: A mechanism to allow entity "previews" from PR's, Gerrit-changes, etc.

### ISSUE THREAD

**Issue by GLundh** [backstage/backstage#21444]
### 🔖 Feature description

Hi!

Our team at Axis have experimented a lot with different methods to allow the users to preview their catalog-info.yaml changes in Backstage. Engineers really don't want to create additional PRs/Commits/Changes just to correct a small (or large) error in a catalog-info.yaml file.

And we have found one method that worked quite well for our use case. We have only implemented it for Gerrit (in our case, we call it the gerrit-open-changes-provider).

It works like this:
1. Every few minutes, we query Gerrit for open changes where the commit delta includes catalog-info.yaml changes.

2. From that change, we generate a completely new entity. 

To avoid naming collisions we suffix the entity name with the Gerrit change number. So if the name of the entity is usually `backstage`, the new name would be `backstage-change-984734`.

This is a temporary entity. It will be removed when the change is submit:ed into main, and replace the old "real" entity.

(I should also mention that every time the Gerrit change is updated, so is the the Backstage Preview Entity.)

To help the user navigate these previews, we introduced some changes in the UI our users find them:
![image](https://github.com/backstage/backstage/assets/300900/28174c55-e336-4ed2-b778-c3e6c9f98473)

Notable changes is:
1. The filter to allow us to only show the "Open Changes", e.g. the preview entities.
2. All preview entities are suffixed with a '*'

When you visit a Preview Entity, you get a nice warning text and a link back to the code change it is previewing:
![image](https://github.com/backstage/backstage/assets/300900/4dc4ad64-1bb9-4497-ab6e-dafe3b94c2dc)

We also have a Gerrit plugin to allow us to jump from a Change in Gerrit to the generated preview entity in Backstage.

This solution have worked really, really well. And helped our users experiment with different annotations and features in Backstage with less frustration.

However there are a few caveats:
1. The techdocs version is still generated from main/master for the preview entity. This should be easily fixed by allowing techdocs to pick-up all kinds of refs.

2. The preview entities are added to the node graphs. It can be a bit annoying. So we need to figure out how to handle that in a nice way.

The main point of this request, is to figure out if we want to generalize some implementation points to allow easy implementation for various entity providers and UrlReaders. Also, we need to figure out what parts of the UI should be updated for a better experience.

Thoughts about this approach?

### 🎤 Context

See description.

### ✌️ Possible Implementation

See description.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Interesting approach.

We do lack a nice way of previewing / linting entities. As you know, doing that properly requires catalog backend support since everybody's catalog is uniquely set up, what with processors and all of that jazz.

Ideally, that check should be done with a dedicated request to the backend, rather than putting something INTO the actual catalog. Doing so is kind of unfortunate since it has persisted side effects and leads to churn.

The `locations` endpoint [has a `dryRun` flag](https://github.com/backstage/backstage/blob/c492d55499013a154598cc579cbd7c8a07c58130/plugins/catalog-backend/src/service/createRouter.ts#L250). This endpoint is used by the catalog-import plugin, made for when you want to register a URL and see what the effects will be before committing them.

It's a bit crude, but does that help for your use case?

In an ideal world, these integrations become more feature rich, and move closer and closer to the start of the user journeys. So instead of getting the errors after actual registration in the catalog, you get early warnings by the lint step in your CI environment, or in a pre-commit hook locally on your computer, or even directly in your code editor.

**Comment by GLundh** [comment]
> We do lack a nice way of previewing / linting entities. As you know, doing that properly requires catalog backend support since everybody's catalog is uniquely set up, what with processors and all of that jazz.

Yes. We tried different ways to write a "WYSIWYG"-editor with preview functionality. But it was hard to handle various processors and stuff. By actually importing the entities from PRs/Changes, we get the full pipeline.

The users also have a small editor, where we use catalogs validate-entity API to check for errors:
![image](https://github.com/backstage/backstage/assets/300900/d00fdb99-5099-41c3-a3d0-a94b20d7e19d)

This one is usable for checking syntax-faults and similar.

> Ideally, that check should be done with a dedicated request to the backend, rather than putting something INTO the actual catalog. Doing so is kind of unfortunate since it has persisted side effects and leads to churn.

Sorry, what do you mean with "persisted side effects"?

> 
> The `locations` endpoint [has a `dryRun` flag](https://github.com/backstage/backstage/blob/c492d55499013a154598cc579cbd7c8a07c58130/plugins/catalog-backend/src/service/createRouter.ts#L250). This endpoint is used by the catalog-import plugin, made for when you want to register a URL and see what the effects will be before committing them.
> 
> It's a bit crude, but does that help for your use case?

Not sure. By actually importing the temporary entities, the engineers get's the full visual aspect, which is where most faults in catalog-infos issues are catched (like bad paths to links, CI-annotations etc).

> In an ideal world, these integrations become more feature rich, and move closer and closer to the start of the user journeys. So instead of getting the errors after actual registration in the catalog, you get early warnings by the lint step in your CI environment, or in a pre-commit hook locally on your computer, or even directly in your code editor.

We are doing that to. Very helpful to get a catalog-info.yaml linting from the CI-system as part of the review.

/Gustaf

**Comment by freben** [comment]
> Sorry, what do you mean with "persisted side effects"?

Ideally, a validation flow should not have to touch the database tables of the catalog at all, not have an effect that is visible to anyone else. It's kinda like mixing preprod and prod instead of having them walled off from each other, and increases noise and mess in the catalog itself. If you were to keep the current suggested flow, I'd prefer if the validation stuff happened in a completely dedicated separate catalog installation, or so.

> By actually importing the temporary entities, the engineers get's the full visual aspect, which is where most faults in catalog-infos issues are catched (like bad paths to links, CI-annotations etc).

Yeah making the validation complete is tricky. Especially when the entities go through really complex processing, and/or depend on other catalog state, and/or fetch information from files nearby (example: getting ownership from nearby codeowners files), and/or in other ways are location dependent.

And sometimes people want to not just do this for one entity at a time. Some may want to point to a new repo that's a candidate for autodiscovery, and ask "what's the sum total effect if I committed this change?".
