### ISSUE TITLE
🚀 Feature: Improve sidebar submenu UX 

### ISSUE THREAD

**Issue by Bogdan-Lyashenko** [backstage/backstage#21534]
### 🔖 Feature description

User keeps losing opened submenu while trying to move from hovered item to its subitems. Especially if they are far apart - like shown on the image below, the only way to select submenu item is to strictly follow red line to not accidentally close submenu.
![image](https://github.com/backstage/backstage/assets/2098309/65668632-d121-40c6-b5ba-e014c91ebe3e)

### 🎤 Context

Current behaviour with on hover-only makes it quite hard to use if menu item and its subitems are far apart, can be improved. 

### ✌️ Possible Implementation

Possible (alternative) solutions:
1) Add configuration to opt in for 'onClick' behaviour to open submenu (and not just on mouse over by default).
2) Align submenu vertically so it always next to the right of it's parent (and not sticking to the top of the page)
3) Make desktop submenu to behave same way as mobile submenu (open down relative to the parent item and not to the right)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by camilaibs** [comment]
Hi @tudi2d , could you share your recommendations?

**Comment by tudi2d** [comment]
Tja @Bogdan-Lyashenko - raising a good point! 

First the hit box of the sidebar items could be improved. I'm thinking of this code example since I saw it the first time - it makes so much sense: https://codepen.io/hakimel/pen/joQZbq.
<img width="347" alt="Screenshot 2023-11-27 at 13 58 12" src="https://github.com/backstage/backstage/assets/8904624/0ddfae9c-aad8-493b-abda-1478abb4f320">
This is not a solution to your specific problem, but might be a addition to the felt frustration when navigating.

Also I like your second suggestion. It could make sense to introduce a different type of the submenu component similar to WordPress, where the submenu is only showing at the specific item. 
<img width="282" alt="Screenshot 2023-11-27 at 14 48 58" src="https://github.com/backstage/backstage/assets/8904624/615c6987-b2e2-4aab-a37b-ee31454ec039">
A way to implement this is through the Material UI `Menu` component, which is build on top of the `Popper` (https://mui.com/material-ui/react-popover/#anchor-playground). It should make it easy to place the component & keep consistent styling with the theme.

Additionally I want to raise the point that you could rethink the order of the items in the first place. In Backstage `Settings` is at the bottom of the Sidebar per default as it is rarely used & kind of out of the context of the normal user flow. If you now move `Docs` & `Admin` down there as well users might need to move a lot of pixels for commonly used features - a different kind of submenu would not change that. This now looks especially odd with both groups having 3 items each - I imagine this being unfortunate on a bigger screen. Could there be a chance to move `Docs` & `Admin` above the items? Can `Settings` be just directly called `Configuration` for admins including `Settings` & `Admin` behaviour on a single place?

**Comment by Antrakos** [comment]
One of the easier way of achieving better UI for submenus is a **close delay** instead of [immediate state change](https://github.com/backstage/backstage/blob/1d7c989db2ad74450c2fa9731b9abd2e341aa196/packages/core-components/src/layout/Sidebar/Items.tsx#L512). This is already implemented in the [main Sidebar](https://github.com/backstage/backstage/blob/1d7c989db2ad74450c2fa9731b9abd2e341aa196/packages/core-components/src/layout/Sidebar/Bar.tsx#L172) and it would be great to have configurable delays for submenus as well. Borrowing that code it would look something like this:
```diff
 
+enum State {
+  Closed,
+  Idle,
+  Open,
+}
+
 const SidebarItemWithSubmenu = ({
   children,
   ...props
 }: SidebarItemBaseProps & {
   children: React.ReactElement<SidebarSubmenuProps>;
 }) => {
   const { sidebarConfig } = useContext(SidebarConfigContext);
   const classes = useMemoStyles(sidebarConfig);
-  const [isHoveredOn, setIsHoveredOn] = useState(false);
+  const [state, setState] = useState(State.Closed);
+  const hoverTimerRef = useRef<number>();
   const location = useLocation();
   const isActive = useLocationMatch(children, location);
   const isSmallScreen = useMediaQuery((theme: Theme) =>
     theme.breakpoints.down('sm'),
   );
 
   const handleMouseEnter = () => {
-    setIsHoveredOn(true);
+    if (hoverTimerRef.current) {
+      clearTimeout(hoverTimerRef.current);
+      hoverTimerRef.current = undefined;
+    }
+    if (state !== State.Open && !isSmallScreen) {
+      hoverTimerRef.current = window.setTimeout(() => {
+        hoverTimerRef.current = undefined;
+        setState(State.Open);
+      }, 10); // <- open timeout, should come from config
+
+      setState(State.Idle);
+    }
   };
   const handleMouseLeave = () => {
-    setIsHoveredOn(false);
+    if (hoverTimerRef.current) {
+      clearTimeout(hoverTimerRef.current);
+      hoverTimerRef.current = undefined;
+    }
+    if (state === State.Idle) {
+      setState(State.Closed);
+    } else if (state === State.Open) {
+      hoverTimerRef.current = window.setTimeout(() => {
+        hoverTimerRef.current = undefined;
+        setState(State.Closed);
+      }, 300); // <- close timeout, should come from config
+    }
+  };
+
+  const isHoveredOn = state === State.Open && !isSmallScreen;
+
+  const setIsHoveredOn = (value: boolean) => {
+    if (value) {
+      setState(State.Open);
+    } else {
+      setState(State.Closed);
+    }
   };
 
   const arrowIcon = () => {
     if (isSmallScreen) {
       return isHoveredOn ? (
         <ArrowDropUp fontSize="small" className={classes.submenuArrow} />
       ) : (
         <ArrowDropDown fontSize="small" className={classes.submenuArrow} />
       );
     }
     return (
       !isHoveredOn && (
         <ArrowRightIcon fontSize="small" className={classes.submenuArrow} />
       )
     );
   };

   return (
     <SidebarItemWithSubmenuContext.Provider
       value={{
         isHoveredOn,
         setIsHoveredOn,
       }}
     >
       <div
         data-testid="item-with-submenu"
         onMouseLeave={handleMouseLeave}
         onTouchStart={isHoveredOn ? handleMouseLeave : handleMouseEnter}
         onMouseEnter={handleMouseEnter}
         className={classnames(isHoveredOn && classes.highlighted)}
       >
         <SidebarItemBase
           hasSubmenu
           className={isActive ? classes.selected : ''}
           {...props}
         >
           {arrowIcon()}
         </SidebarItemBase>
         {isHoveredOn && children}
       </div>
     </SidebarItemWithSubmenuContext.Provider>
   );
 };
```

Unfortunately I don't see a way of augmenting this component in isolation for local backstage apart from forking the whole Sidebar component.

**Comment by O5ten** [comment]
reopen

I'm also looking for a fix for this. My users are very frustrated about the behavior. It doesn't matter much to me if the hitbox is increased of if there is a delay, but i'll try to weigh in on it. 

The delay would probably work but it gives a laggy feel. The hitbox solution means the UI wouldn't look like it is lagging as long as it works as suggested. 

![](https://media.discordapp.net/attachments/696709358544879716/1212678119685627944/menu-problems.gif?ex=65f2b582&is=65e04082&hm=92c59ed9723d321b84458b1477b0cd34feecb3234f1535245f99a027e775f93a&=&width=958&height=738)

**Comment by O5ten** [comment]
I made a PR with an attempt at fixing my own issue @tudi2d.  
https://github.com/backstage/backstage/pull/23333

**Comment by tudi2d** [comment]
Tack @O5ten! Issue continues to stay open for releated issues to Sidebar Submenu UX.

**Comment by O5ten** [comment]
> Tack @O5ten! Issue continues to stay open for releated issues to Sidebar Submenu UX.

Sure thing! No arguments from me there. :)

**Comment by roadgork** [comment]
this shouldn't be stale as it isn't solved. And it should be a bug instead of a feature

**Comment by bsiedleckiallegro** [comment]
shouldn't be stale, UX still needs improvements

**Comment by ppiwow-apay** [comment]
any update or workaround, it is really frustrating to users

**Comment by amhassen97** [comment]
> Tja [@Bogdan-Lyashenko](https://github.com/Bogdan-Lyashenko) - raising a good point!
> 
> First the hit box of the sidebar items could be improved. I'm thinking of this code example since I saw it the first time - it makes so much sense: https://codepen.io/hakimel/pen/joQZbq. <img alt="Screenshot 2023-11-27 at 13 58 12" width="347" src="https://private-user-images.githubusercontent.com/8904624/285899215-0ddfae9c-aad8-493b-abda-1478abb4f320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc2Njg5MjcsIm5iZiI6MTc0NzY2ODYyNywicGF0aCI6Ii84OTA0NjI0LzI4NTg5OTIxNS0wZGRmYWU5Yy1hYWQ4LTQ5M2ItYWJkYS0xNDc4YWJiNGYzMjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MTlUMTUzMDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDYxNTIzMjQ3OGM3MTVlZjEwYjZiMjBhNzM0ZWU1MmNkYjQ3NGY0YjI4Zjc1NmFkZmI0OGJhZDdkZjI5OGE2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3IDtZT-r9Xzmti9x_3IeebZIGFyoVdl-yr6BclrDpcA"> This is not a solution to your specific problem, but might be a addition to the felt frustration when navigating.
> 
> Also I like your second suggestion. It could make sense to introduce a different type of the submenu component similar to WordPress, where the submenu is only showing at the specific item. <img alt="Screenshot 2023-11-27 at 14 48 58" width="282" src="https://private-user-images.githubusercontent.com/8904624/285892915-615c6987-b2e2-4aab-a37b-ee31454ec039.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc2Njg5MjcsIm5iZiI6MTc0NzY2ODYyNywicGF0aCI6Ii84OTA0NjI0LzI4NTg5MjkxNS02MTVjNjk4Ny1iMmUyLTRhYWItYTM3Yi1lZTMxNDU0ZWMwMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MTlUMTUzMDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzg5NzAyYTRiZmM0ZTc0NWNiMzcyYzU2OTliOTU3YzY4YzI1MzE1YjkxZjc3MzY3YmNkYTFhMmYyOTJhNDgxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Q2Txqonxfgv8v5wsaCkl5a-vVyjW4xXn8DnM94tAftY"> A way to implement this is through the Material UI `Menu` component, which is build on top of the `Popper` (https://mui.com/material-ui/react-popover/#anchor-playground). It should make it easy to place the component & keep consistent styling with the theme.
> 
> Additionally I want to raise the point that you could rethink the order of the items in the first place. In Backstage `Settings` is at the bottom of the Sidebar per default as it is rarely used & kind of out of the context of the normal user flow. If you now move `Docs` & `Admin` down there as well users might need to move a lot of pixels for commonly used features - a different kind of submenu would not change that. This now looks especially odd with both groups having 3 items each - I imagine this being unfortunate on a bigger screen. Could there be a chance to move `Docs` & `Admin` above the items? Can `Settings` be just directly called `Configuration` for admins including `Settings` & `Admin` behaviour on a single place?

@tudi2d I've created a PR [here](https://github.com/backstage/backstage/pull/30002) based on your recommendations regarding the popover element. I've found the ease-of-use/accessibility/UX is much better. Would appreciate your feedback 😄 .

**Comment by awanlin** [comment]
Hi @amhassen97, just a heads up that @tudi2d isn't active in the project anymore so he might be very slow to reply here. Your PR has been assigned to the Framework Maintainers and they do a review 👍

**Comment by amhassen97** [comment]
> Hi [@amhassen97](https://github.com/amhassen97), just a heads up that [@tudi2d](https://github.com/tudi2d) isn't active in the project anymore so he might be very slow to reply here. Your PR has been assigned to the Framework Maintainers and they do a review 👍

Cool thanks for the feedback @awanlin 👌 !
