### ISSUE TITLE
🐛 Bug Report: Getting started not working on lts versions gallium, hydrogen and iron (16.20.2, 18.19.0, 20.10.0)

### ISSUE THREAD

**Issue by divad1196** [backstage/backstage#21723]
### 📜 Description

I am following the [Getting started](https://backstage.io/docs/getting-started/) tutorial, and at some point I am getting blocked.

I have seen other similar, but different, issues like:
* https://github.com/backstage/backstage/issues/20881
* https://github.com/backstage/backstage/issues/20001

### 👍 Expected behavior

To be able to follow the whole "getting started" without issue.
- Recommended node version should be mentionned explicitly at the start of the "Getting Started"
- The whole process must be working

### 👎 Actual Behavior with Screenshots

The situation is explained in the description

For version 16, I am receiving:
>   executing     yarn install ◠ error root@1.0.0: The engine "node" is incompatible with this module. Expected version "18 || 20". Got "16.20.2"

For version 18:
  
![image](https://github.com/backstage/backstage/assets/43037556/0a5c99a8-339d-4c25-be53-8109da98b66d)

and using the version 20, it breaks at the ["Register an existing component"](https://backstage.io/docs/getting-started/configuration#register-an-existing-component) part:
![image](https://github.com/backstage/backstage/assets/43037556/b826281b-677a-450f-89c0-a40260d6095a)

Trying another value, it seems to be specificly related to the demo file.

(and latest node version doesn't work but this is normal)

### 👟 Reproduction steps

Just follow the tutorial

### 🖥️ Your Environment

I am using ubuntu 22.04

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Apeksh742** [comment]
Adding some more details on it. 
Downgrading backstage to v19 made it run again with the same node version (18.19.0)
So maybe there are some changes required for the latest update?
Here is the output for `yarn start-backend` :

```
yarn run v1.22.19
$ yarn workspace backend start
$ backstage-cli package start
(node:42502) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///Users/username/frontend_projects/backstage/node_modules/%40esbuild-kit/esm-loader/dist/index.js", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
Loaded config from app-config.yaml, app-config.local.yaml
2023-12-05T05:48:19.690Z backstage info Found 12 new secrets in config that will be redacted 
....... Expected logs..........
```

Please let me know if you need any other info.

**Comment by awanlin** [comment]
I've logged a separate issue specifically focuses on "Error: tsx must be loaded with --import instead of --loader" as this one has multiple things noted in it and it will be hard for others to find it based on the title

**Comment by Apeksh742** [comment]
I have tested it and [v1.21.0-next.3](https://github.com/backstage/backstage/releases/tag/v1.21.0-next.3) seems to fix it.

**Comment by freben** [comment]
Thanks!

**Comment by awanlin** [comment]
Hi @divad1196, I know has been closed but would still like your feedback on the this and the other items when you have time, please?

**Comment by divad1196** [comment]
@awanlin I was able to run backstage and using the link from the image instead of the one of the documentation registered the component. Here is a first feedback on my current situation:
* I already managed to reach this situation before (even if I don't recall how)
* I am not sure which version I am trying and if this is really what fixed my issue.
* I am still having other errors like:
  * In the logs:
    ![image](https://github.com/backstage/backstage/assets/43037556/fbad6730-2365-402c-a995-ef25746e4d77)
  * from the interface:
    > Failed to load entity kinds

    ![image](https://github.com/backstage/backstage/assets/43037556/319361db-8424-4ce1-bb1d-c7449551113c)
  * the component registered doesn't seem right 
    > This entity has relations to other entities, which can't be found in the catalog. 

    ![image](https://github.com/backstage/backstage/assets/43037556/ef29ba50-52fb-4c2d-90d8-dd2878b3da2f)

  Nb: This may be related to the fact that I didn't change my database for postgresql, but since the default one is sqlite, I assumed I could keep using it for my tests. I also skip the OAuth2.0 part. These are great for production, but not necessary for testing. Also, right after having added a component, we add another one witht another method without testing the first one. I think that most people starting with this tool are more interested in seeing how you can add and use a component, then see the variations/configurations/... I have more than 20 solutions to try and compare, on the paper backstage is the most promizing one so I will keep digging a bit more but this is requires a lot more self-learning and digging than expected.

I will keep you informed

**Comment by awanlin** [comment]
Hi @divad1196, sorry for the slow reply, I've been pretty busy. I'll start off by saying a new version of Backstage - `1.21.0` - was just release a few minutes ago, that most likely should resolve any potentials issues you have encountered already.

Regarding the other errors:

- For the Failed to load kinds error, I would need to see what the browser console says to help more, it's also possible that it just needed to be refreshed.
- The warning message is by design, it's there to help show when related items are missing. In this case you don't have a CNCF group and so Backstage it just trying to point that out for you.

Regarding your more general question about Backstage: you expectations are how you it can work but the way to get there may not be clear. There's two parts to this: 

- Use the Catalog to register your Components, this helps you track your various Services, Websites, etc. and who owns them along with other benefits. There's various ways to automatically discover your components as well. Catalog documentation is here: https://backstage.io/docs/features/software-catalog/
- Use the Software Templates to allow people to self service building new services, as part of the template workflow they would also get registered in the Catalog. Documentation on Software Templates (often refer to as the Scaffolder) are here: https://backstage.io/docs/features/software-templates/

Hopefully that helps?


The Backstage would work is via two method in what you have described: you would register Components in the Catalog

**Comment by divad1196** [comment]
Hi @awanlin and thank you for the work.
The response delay is absolutely not an issue.

I will re-check again but it was already working better last time.
My issue with the warning is that I am not expecting one from a "Getting started", or at least I would expect the next steps to explain what it means and how to fix it.

I will try again when possible and send you the console logs. But as for the warning previously mentionned, this is misleading more than blocking.

I will at the template aspect more deeply, but I wonder if it is suitable for non-technical employees.

Thank you again and have a nice evening.
