### ISSUE TITLE
🐛 Bug Report: Duplicated components in explore plugin

### ISSUE THREAD

**Issue by cursedcoder** [backstage/backstage#21742]
### 📜 Description

I don't know if that's by design, but:

https://github.com/backstage/backstage/blob/master/plugins/explore/src/components/EntityCard/EntityCard.tsx
https://github.com/backstage/backstage/blob/master/plugins/explore/src/components/DomainCard/DomainCard.tsx

are 99% identical, and looks like DomainCard is never used anywhere

### 🖥️ Your Environment

windows 95

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
We don't really know where they are used, since they can be consumed anywhere out there by people depending on the package.

But good catch, they are truly identical which is just wasteful and confusing. A PR to mark the Domain one as deprecated for starters (with a reference to use the other one) sounds like a good thing!

**Comment by npiyush97** [comment]
@freben removing both domaincard and domainexplorecontent is good solution?

**Comment by vinzscam** [comment]
good point @cursedcoder, let's open a PR so that we can discuss what's the best way to improve the structure of the components
