### ISSUE TITLE
Platform: Allow proper segregation of testing responsibilities for contributors and integrators

### ISSUE THREAD

**Issue by lowjoel** [backstage/backstage#2178]
## Context

(I'm bringing this to the top because of the terminology)

I am using the definition of Contributor and Integrator in the [Product FAQ](docs/FAQ.md).

In a set up as described, the Contributors do need to be able to assert that the version of the plugin they are releasing works well (in isolation, via unit tests), but also that the integrator has properly set up the infrastructure/skeletons that the plugin needs.

Therefore, in this issue we will be discussing three kinds of tests:
 - Unit tests (isolated within plugin alone)
 - Functional tests (possibly tested against mock services, spanning components in the application)
 - System tests (does the system work as a whole after integration?)

## Feature Suggestion

Today, there is some support in the scaffolds produced by `backstage-cli` for System tests on the frontend (using Cypress.) The way this is currently set up, it would be easy for the integrators to write System tests. It's not directly obvious to me if a similar concept exists for the backend.

Today, unit tests also seem to be fairly straightforward to write for all plugins.

There are thus two major gaps in the test taxonomy today, by nature of the fact that Backstage is plugin centric:
 - As a contributor, it is difficult for me to test my plugin in isolation with everything else (is this desirable? What if I have a dependency on another plugin to function?). This is for functional tests.
 - As a contributor, it is difficult for me to ascertain that when deployed by the integrators, my plugin works as expected (system testing-wise.) The dual of this applies to the integrator: how do I know that I integrated all the plugins correctly?

 Test taxonomy | Integrator | Contributor |
----------------|-----------|-------------
Unit tests | X | X
Functional tests | X | ?
System tests | X (if he writes all the tests, which isn't scalable) | ?

## Possible Implementation

Possible ideas:

 - I was trying to have a system where my integrated system tests would pull in system tests from plugins, but I wasn't too successful. I can't dynamically list all the packages being imported and include a specific known module name... or can I?
 - Have some kind of command that will dynamically assemble a Cypress test suite for frontend, with the corresponding logic for backend (details TBD), based on the imported packages.

**Comment by Rugvip** [comment]
+1 for this. I think it makes sense to spawn a couple of issues from this, and keep this as the meta-issue of improving confidence in published plugins and deployments.

Some initial thoughts:

- https://github.com/spotify/backstage/issues/2182 should help out a bunch when it comes to avoiding broken plugins due to missing APIs, since the plugins will be providing the APIs themselves. In addition I think we might want to add a `requiredApis` type-thing for plugins to define, that breaks the entire app if some API is not installed. Right now you can get failures way too late, i.e. only when you visit a specific page.
- I think a test harness for plugins might make sense. Either as a separate CLI command, or as a unit test utility. Something that might run e2e tests, but at least ensures that all things that the plugin exports function, are named correctly, etc.

**Comment by lowjoel** [comment]
One thing I posted in the original [Discord thread](https://discord.com/channels/687207715902193673/687207715902193679/749803622719553665) which I don't think I carried over here is our intent to use [GitLab Review apps](https://docs.gitlab.com/ee/ci/review_apps/). That which allows us to set up ephemeral test environments, which gives us the ability to preview changes before it goes live.

In my current test taxonomy that counts as a functional test (because we can't connect prod upstreams, e.g. GitLab or Spinnaker or the like) but it allows us to see what changes were made. We can also run assertions over those ephemeral test environments.
