### ISSUE TITLE
🐛 Bug Report: Techdocs ERROR 404: NotFoundError: Page not found.

### ISSUE THREAD

**Issue by thuantvrs** [backstage/backstage#21819]
### 📜 Description

The component "[shopify-integration-service](https://backstage.rewardstyle.com/docs/default/component/shopify-integration-service)" could not display the docs.
<img width="874" alt="image" src="https://github.com/backstage/backstage/assets/66709220/e4a38ded-6ba8-4b67-b4c2-328b25025cb6">

### 👍 Expected behavior

<img width="1112" alt="image" src="https://github.com/backstage/backstage/assets/66709220/b458b85b-f4c3-4fee-bce1-43067937dc32">

### 👎 Actual Behavior with Screenshots

<img width="874" alt="image" src="https://github.com/backstage/backstage/assets/66709220/439d08c5-4c03-499a-a1f3-31fe340cdd47">

### 👟 Reproduction steps

1. Go to the docs: https://backstage.rewardstyle.com/docs?filters%5Buser%5D=all
2. Enter 'shopify-integration-service' in the Filter input.
3. Click on "shopify-integration-service" in the filter result.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by johnphilip283** [comment]
Hey @thuantvrs! Since this issue seems specific to your Backstage instance that is gated by Okta, I don't have enough information to reproduce this issue. I'd double check to make sure that your `/docs` directory has the right structure expected by TechDocs, and that if you're generating docs in CI/CD, that you have the right publishing setup as specified here: https://backstage.io/docs/features/techdocs/getting-started#choosing-storage-publisher and here: https://backstage.io/docs/features/techdocs/using-cloud-storage.
