### ISSUE TITLE
🚀 Feature: expose all schedulers via API (or coreServices)

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#21951]
### 🔖 Feature description

In the old backend code you could do something like this:

```typescript
async function makeCreateEnv(config: Config) {
  const pluginSchedulers: ExtendedTaskScheduler[] = [];
  // ...
  return { 
    createEnv: (plugin: string): PluginEnvironment => {
       // ...
      pluginSchedulers.push({ name: plugin, scheduler });
      return {
        // ...
      }
    },
    pluginSchedulers: 
}
```

And that way you get hold of each and every scheduler in the system. I could not find a way to do it in the new backend system. The way of how the new backend system isolates each plugin into it's own environment makes it really difficult to trigger other schedules or even fetch information about scheduled tasks.

### 🎤 Context

DevTools (https://github.com/backstage/backstage/blob/master/plugins/devtools/README.md) would be a natural place for showing what kind of scheduled tasks the system has. Or even better, have a button that triggers given task.

### ✌️ Possible Implementation

Not sure how to approach this keeping scalability (https://backstage.io/docs/deployment/scaling) & architecture in mind. Maybe each plugin should expose 'standard' schedule api that could be queried by other plugins? Each endpoint should be behind authorization / authentication to prevent DOS attacks and such, but the idea itself sounds reasonable.

Other option would be exposing the schedulers via coreServices but I'm not sure how well that works with multiple instances.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
Ping @pjungermann on this one too

**Comment by awanlin** [comment]
@webark can't remember if you are on the new backend system yet, wondering if this impacts you?

@drodil same, didn't you also have something like this? Yeah, you did it was this PR: https://github.com/backstage/backstage/pull/17711

**Comment by webark** [comment]
we have yet to move to the new backend system.. :/ 

I was planning on wrapping the current scheduler in our own service. We do this in the way you can in our current legacy backend implementation. Is the current scheduler a service? I haven't looked at the code yet. If it was, you could overwrite it right? I thought services work kind of like apiFactories in that way.

**Comment by freben** [comment]
Yes, you can replace the implementation for a given service ref in a sort of similar way as utility APIs in the frontend. But we've a couple of times now encountered use cases for services and plugins to communicate events outward to others, and this seems to me to fit the bill.

**Comment by freben** [comment]
cross linking this to https://github.com/backstage/backstage/pull/22671

**Comment by webark** [comment]
```typescript
export const backendTasksManagerServiceRef = createServiceRef<PluginBackendTasksManager>({
  id: 'backend-tasks-manager.service',
  scope: 'plugin',
  defaultFactory: async service =>
    createServiceFactory({
      service,
      deps: {
        scheduler: coreServices.scheduler,
        rootLogger: coreServices.rootLogger,
        config: coreServices.rootConfig,
        pluginMetadata: coreServices.pluginMetadata,
      },
      async createRootContext({ config, rootLogger }) {
        return BackendTasksManagerService.fromConfig(config, { logger: loggerToWinstonLogger(rootLogger) });
      },
      async factory({ scheduler, pluginMetadata }, backendTasksManager) {
        return backendTasksManager.forPlugin(pluginMetadata.getId(), scheduler);
      },
    }),
});
```

We are doing this under the new backend to access all schedules from all plugins. as an FYI.

@freben is this what you would expect?

**Comment by freben** [comment]
Is this an alternative reimplementation of effectively the entire task manager? I'm not sure what it is I'm looking at, not recognizing the `BackendTasksManagerService` type etc.

I mean, sure. I've been meaning to look into adding a dependency on `coreServices.rootHttpService` in the `coreServices.scheduler` factory, and adding a `.backstage/scheduler/v1/tasks` route or similar that offers up the node's overview state. But even if I did, that'd only be a piece of the puzzle since we don't have plugin / deployment discovery as a feature yet. That is, even if we can inspect the state of a given node in a sensible way, there's no way yet to enumerate all nodes and unifying their states.

**Comment by freben** [comment]
Aight, no it's all good, I was just wondering how it was interacted with - thought there would be an httpRouter dependency or so in there at least. And yeah the problem remains to make it possible to enumerate and reach all backend instances (or at least one instance of each type of deployment, since the state is in their shared database).

**Comment by webark** [comment]
There's a separate router that uses the root service to look up the schedules and adds api actions to them. Right now that's a legacy plugin integration still, but will be its own service later.

And each plugin still stores thier tasks in thier own DB, this just, due to the root class being created, can talk between them.

once we start to break up the backed, some could get peeled off from the backend that is serving the UI, but i think you could use the discover service to find all those hosts i believe. Right? This aspect i'm hoping can have a way to get it out of the existing apis, but there might have to be some kind of "hosts" array that we manually define and iterate over. Some backends might not be connected to the ingress network, but if you add that plugin to a backend that is at some level, it should expose the schedules I haven't tested the split deployments, and are still about 3 months out from that.
