### ISSUE TITLE
Backstage and Backstage Helm Chart need a community push

### ISSUE THREAD

**Issue by sspreitzer** [backstage/backstage#22375]
### 📜 Description

The Backstage Helm Chart at https://github.com/backstage/charts does not get enough attention and progress.

Multiple community requests are not handled and substantial Q&A questions evaded instead of directly answered:
 * backstage/charts#160
 * backstage/charts#140

A couple of pending PRs.

### 👍 Expected behavior

Add a product vision to Backstage to be a easily deliverable product for the CNCF community. Eg. in form of a Helm Chart that works out of the box.

Follow the ‹[12 app factor principles](https://12factor.net)› and segregate **all** config from code. 
Backstage has a plugin system that needs manual code integration, which is hard to integrate in containerisation and Helm Charts.

### 👎 Actual Behavior with Screenshots

Backstage Helm Chart is not working out of the box. Thus Backstage is not packaged properly for the container ecosystem.

### 👟 Reproduction steps

*not applicable*

### 📃 Provide the context for the Bug.

*not applicable*

### 🖥️ Your Environment

*not applicable*

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by sennyeya** [comment]
👋 , I can't talk to that repo's maintenance, but I can try to give some context on why it is set up like it is and paths forward for documentation changes.

> As a user of other CNCF projects / other projects that have helm charts, I should be able to easily deploy and install Backstage with a helm chart.

This is a common misconception. Backstage is not a single project with config changes, it is a platform for developers to create their own customized internalized IDP. We provide the tooling, wrappings and common library, but you have to bring the implementation and customization. The existing helm chart is set up to provide a demo instance similar to [demo.backstage.io](https://demo.backstage.io/).

There is some ongoing work to get us more in line with the config based model you describe, see [Quickstart](https://www.youtube.com/watch?v=bUdaO9NKXJY&list=PLj6h78yzYM2PxiInfZi2OKu1KluNfbLtc&index=12), [Frontend DI](https://www.youtube.com/watch?v=8hVMNMXXN44&list=PLj6h78yzYM2PxiInfZi2OKu1KluNfbLtc&index=8), [Dynamic Backend Plugins](https://github.com/backstage/backstage/pull/18862), but we're not at a place where we can just offer a customizable helm chart.

There is a disclaimer to this effect on the helm chart README,
> Disclaimer: This Helm chart deploys a pre-packaged container image which contains a vanilla Backstage instance for demo purposes. This image is probably not suitable for use in production. For further customization of the Backstage instance (plugin installation, UI changes, etc.) please create your own custom instance and container image. For details please consult the [Backstage documentation](https://backstage.io/docs)

All that to say, there is an existing vision to make set up easier, but we haven't delivered on it just yet :)

re: documentation updates, I agree there is room for improvement here and I'm sure the maintainers would be happy to have contributions to that effect. Some more relevant docs from the Backstage.io side would be [deploying on Kubernetes](https://backstage.io/docs/deployment/k8s#creating-the-backstage-instance) and [building the docker image](https://backstage.io/docs/deployment/docker).

**Comment by sspreitzer** [comment]
Hi @sennyeya 

> This is a common misconception. Backstage is not a single project with config changes, it is a platform for developers to create their own customized internalized IDP. We provide the tooling, wrappings and common library, but you have to bring the implementation and customization. The existing helm chart is set up to provide a demo instance similar to [demo.backstage.io](https://demo.backstage.io/).

I am trying to describe in my own words, what you describe that Backstage is:
 * *Backstage is a microservices architecture oriented nodejs application framework to build a customised development platform.*

Maybe the common misconception about Backstage could be prevented by clearly naming it the «*Backstage Framework*». That could maybe inspire others to create an off-the-shelf implementation/product of the Backstage Framework with best practices, such as the «[Red Hat Developer Hub](https://developers.redhat.com/rhdh)», which was released this week. 

Hoping forward for an out-of-the-box Backstage experience.

**Comment by sennyeya** [comment]
I think we're a little late to rename the project ;)

There's definitely more nuance to my definition of what Backstage is, more than I can describe in a Github comment. I'd recommend reading through [the documentation](https://backstage.io/docs), Backstage has a bunch of facets that make it much more than just a framework.

**Comment by freben** [comment]
Adjusted the title and labels a bit.

The helm charts are not maintained in this repo for a reason, and the core maintainers are not looking at them. I realize that this issue is here to call for attention toward that other rrepo, and I'll leave the issue around for a bit to see if someone steps in. But it's not going to be worked upon by the core maintainers.

**Comment by sspreitzer** [comment]
Hi @sennyeya 

> There's definitely more nuance to my definition of what Backstage is, more than I can describe in a Github comment. I'd recommend reading through [the documentation](https://backstage.io/docs), Backstage has a bunch of facets that make it much more than just a framework.

Interpretation of qualitative content varies subjectively. I respect your point of view about Backstage. I have to share mine, so that this project sees another point of view. This is important in qualitative content analysis.

My understanding - after reading the documentation a couple of times and the disclaimer you provided - is that the Backstage project on GitHub factually is a pluggable application framework. The documentation is describing Backstage as an open platform to build developer portals. It is unspecific about Backstage being a software development framework or being an application itself. It does not provide a substantial definition of what the Backstage project effectively is creating.

My conclusion is that Backstage has an ambiguous definition, which can lead to common misconceptions. Which as a result can lead to misunderstandings and unmet expectations for contributors and users.

By various statements made, there seems to be a common agreement that the documentation needs to be improved in certain aspects.

**Comment by tumido** [comment]
Hi @sspreitzer,

I agree with the sentiment that documentation should be improved in various areas and we maybe should advertise/explain the chart and a Backstage instance relation better.

However, as the Backstage chart maintainer I would like to understand which part of it is lacking or inferior?

> The Backstage Helm Chart at [backstage/charts](https://github.com/backstage/charts) does not get enough attention and progress.

We don't see much technical progress to be needed at this point. To us the chart appears feature complete. We do accept any suggestion and if you have an idea how the chart should be improved and what Kubernetes concept we do not support, feel free to open an issue.

> Multiple community requests are not handled and substantial Q&A questions evaded instead of directly answered:

> https://github.com/backstage/charts/issues/160
> https://github.com/backstage/charts/issues/140

Not sure what you find evasive or not handled. Since one of these issues is just a spin-off from the other (for tracking purposes), I kinda considered them as a single discussion thread in the "discussion" sense. As you can see in the https://github.com/backstage/charts/issues/140 issue, I've tried to gather information about what is not OK with the chart, though I've received no response.

> A couple of pending PRs.

All of these are stale and we gave the community contributors a chance to either explain themselves or adjust their PRs. Neither of which has happened. Maybe we should consider closing them for inactivity. We do that irregularly.

> Add a product vision to Backstage to be a easily deliverable product for the CNCF community. Eg. in form of a Helm Chart that works out of the box.

The helm chart works out of the box just fine. As part of our chart CI we test every chart change against vanilla Backstage image whether it deploys a healthy deployment or not.

> Follow the ‹[12 app factor principles](https://12factor.net/)› and segregate all config from code.
> Backstage has a plugin system that needs manual code integration, which is hard to integrate in containerisation and Helm Charts.

That is correct. We have multiple initiatives across the Backstage space to address this issue to make the plugins declarative and allow for dynamic extensions to Backstage through external plugin mounts. However, this system is not yet fully in place therefore you are correct. Manual changes to the code are still required and there's not much the chart itself can do about this.

> Backstage Helm Chart is not working out of the box. Thus Backstage is not packaged properly for the container ecosystem.

The chart works out of the box. If you see any errors, please open an issue against the chart repository. We would love to help.
