### ISSUE TITLE
💬 RFC: Make `gitilesBaseUrl` required for `Gerrit` integrations

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#22500]
### 🔖 Need

The current integrations with Gerrit are implemented in a way that if you the `gitilesBaseUrl` config option is not required, we end up `git clone`ing the repository in order to do things like `readTree` as it's impossible to download a tar of the archive without the `gitiles` plugin.

This plugin AFAIK is installed on all Gerrit instances by default, so my question is, in order to improve the portability and performance of the `GerritURLReader`, and bring it more into line with how the other integrations work, can force Gerrit Users to have to supply this config option and remove the `git clone` approach downloading the source?

My questions is for Gerrit users if this is possible, and how often do you not have the Gitiles plugin installed?

### 🎉 Proposal

Force Gerrit users to supply `gitilesBaseUrl`. Removing the need to clone the repository in order to `readTree` from Gerrit.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by anicke** [comment]
The "readUrl" could also be made a lot easier using gitiles since you can just add "?format=TEXT" to the url to get the base64 content. We would also not need to parse the location url like we do today, and support all types of location.

**Comment by benjdlambert** [comment]
cc @GLundh I've seen you in some gerrit issues :)

**Comment by GLundh** [comment]
I think it sounds great! The cloning stuff sucks, gitiles makes everything so much more effective when readTreeing etc.

**Comment by Rugvip** [comment]
Yep, let's do it! 👍 

Discussed a bit and we're thinking the best way to roll this out is to start by making the gerrit URL reader throw an error on startup if `gitilesBaseUrl` is not provided, but provide an escape hatch via an env var for now in case someone isn't able to use gitiles. Error message would be something like `A gitilesBaseUrl must be provided for the gerrit integration to work. You can disable this check by setting DISABLE_GERRIT_GITILES_REQUIREMENT=1 but that will be removed in a future release. If you are not able to use the gitiles gerrit plugin, please open an issue towards https://github.com/backstage/backstage`. Then we wait one or two release to make sure it's all good, before moving on to actually require gitiles.

Anyone that would like to contribute that? The check would mirror the logic [here](https://github.com/backstage/backstage/blob/b623c9fc1c16b13cf59329111ff73ec5013cab1b/packages/backend-common/src/reading/GerritUrlReader.ts#L187), but would need to happen on startup in the factory over [here](https://github.com/backstage/backstage/blob/b623c9fc1c16b13cf59329111ff73ec5013cab1b/packages/backend-common/src/reading/GerritUrlReader.ts#L83)

Q from me from understanding though: the `gitilesBaseUrl` is [always set](https://github.com/backstage/backstage/blob/6673babab99f37be1c7f75f81c9336807b338ca6/packages/integration/src/gerrit/config.ts#L105-L109). Is the `https://${host}` ever a valid value or should we remove that default? If it is valid, do we instead risk breaking setup that should be working with check because we're rejecting a valid configuration?

**Comment by anicke** [comment]
Sure, we can do I it. I can check the local gerrit admins if that is valid.

**Comment by anicke** [comment]
BTW, the check if gitiles is available only works if the baseUrl does not contain a path. The "default" gitilesBaseUrl will never match the baseUrl if there is a path.

```ts
// with the default "https://${host}"  where host is from the baseUrl.
// If baseUrl has a path this will always be false. For example "https://acmecorp.com/gerrit"
if (this.integration.config.gitilesBaseUrl !== this.integration.config.baseUrl) {
      return this.readTreeFromGitiles(url, branchInfo.revision, options);
    }
```

**Comment by freben** [comment]
Closing as fixed!
