### ISSUE TITLE
🚀 Feature: Multiple tokens for gitlab integration

### ISSUE THREAD

**Issue by dariozachow** [backstage/backstage#22643]
### 🔖 Feature description

This feature includes the usage of multiple tokens per integration depending on the context used.
This would make it possible to have a access token set, which can be used for Scaffolder actions e.g. listing just specific groups/projects. And the orgprovider makes use of a different token to fetch more Groups. 

### 🎤 Context

In our use case the Entityprovider for gitlab requires a global access token to list any Project/Group on our private instance.
This global(admin) token is available to any user, because we want to allow everyone to use and create templates in backstage, therefore giving the user more privileges than their normal gitlab user account. Under the hood template actions like fetch:plain/fetch:template and gitlab actions without a set oauth token are using this high privilege token to make http requests to gitlab. This leads to a high security issue on our side, because users can edit, checkout and do any kind of stuff within gitlab even tough their user does not have the privilege to do so.

### ✌️ Possible Implementation

I think one solution to this problem is to have multiple access tokens in the configuration file and use the token depending on the current context. If something happens inside a scaffolder action, we could just use a low privilege token so the user does not have greater permissions than their normal account. But I can imagine that this approach leads to many changes to the current codebase und complex verification of the context.

In alternative blocking the token from any template action with an extra flag or config setting solves this problem and all actions are done in the user context with an oidc-token.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by horsfallnathan** [comment]
Just came here to write a similar issue. Right now integrations are matched using the host, could we add ids to the integration and instead of matching via host we use their ID. 

``` yaml
integrations:
  gitlab:
    - host: gitlab.company
      credentials:
        - integrationId: id1
          token: token1
        - integrationId: id2
          token: 2
catalog:
  providers:
    gitlab:
      group1:
        integrationId: id2
      group2:
        integrationId: id1
```

**Comment by dariozachow** [comment]
I think your solution to have multiple tokens identified with an ID would be nice but the use of a different token per group is maybe not required. I'm thinking about having a techuser and create a token for them, so if you need to add a new group to the catalog, just add the user to the group instead of creating an extra access token for each.

The main concern of my issue was the fact, that having a shared token between the catalog and the scaffolder leads to security issues

**Comment by benjdlambert** [comment]
Hey :wave: 

Thanks for raising this! 

Yep, it's indeed a problem, and something that we want to make easier to enable. 

Little bit of background here, is that the `user` auth part came after the initial work around Personal Access Tokens and GitHub Apps etc for authentication, and it's still not fully implemented in all actions. See https://github.com/backstage/backstage/pull/22521 for the start of the work, but basically some actions like `fetch:*` didn't support only users auth. With this coming after the integrations config approach, we didn't want to force this onto all adopters, so it's very much opt-in at this point, but maybe something we can look to force in the future.

There's of course ways around it, like deploying the scaffolder separately, with it's own `app-config.yaml` which doesn't have any token, or maybe just a read-only token for example. Or doing something like `token: ${{ secrets.userAuthToken or false }}` which will throw when it gets to the mutating actions.

I'm thinking that what we could do, is implement a `scaffolder.forceUserAuth` config setting or something, which could be implemented in a few ways, and wanted to throw some ideas out there for what would be the best solution here.

1. This config option could strip the tokens from `integrations` all together for the `scaffolder-backend`. This could be pretty tricky to implement, as we don't really have the knowledge as to where the keys are for the provider. This might need to be done at the URL reader level, but unsure what's best here.

1. We could make this option available to actions, like `publish:github` and `fetch:*` so that if this option is enabled, and there is no user token passed, it will throw an error. This is much easier to implement, but it does require that all actions are written in a way where they actually check if this config is applied and that there is a present user token.
This gives a little more flexibility, because sometimes you might want to use the user token, but sometimes you might want to try without a token in the first place for things that might be public? 

Any immediate thoughts here?

**Comment by dariozachow** [comment]
Hi, thanks for your ideas.

I think the better way of doing this is, is the second, but I see a problem with the contribution of new actions. How do people know that there is such a config for forcing user auth, which needs to be implemented.
If a new action comes to our system not enforcing this flag, the admin token can be misused again.

The approach with having multiple tokens per context or entirely striping the tokens from the scaffolder-backend would be safer, but I see the problem with implementing that as well.

**Comment by awanlin** [comment]
Would it be possible to clarify some of this? It's a bit confusing as there seems to be two things going on here: support for multiple tokens and isolating the Scaffolder from the tokens.

Part of the confusion for me is that the first items seems very GitLab specific. The Azure integration already supports this and perhaps could be used to help design support of this for GitLab. 

The 2nd item I'm very much onboard with as I've seen many people ask about this on Discord for various integrations.

Maybe it would make sense to break this into two issues and update the content of this one?

**Comment by dariozachow** [comment]
Hey, thanks for your reply.

your right about the two different issues in here. I've initially created this post, with both options to get some answer what is the preferred way for backstage as both solution would fix our security concern .

I'm open to create another issue just containing the part with having a option to isolate tokens from the scaffolder and specify this one to have multiple tokens per integration.

**Comment by awanlin** [comment]
That's fair, there is a need for both IMO based on what I've seen on Discord (I'm not a GitLab user) and breaking them up would allow us to properly tackle both problems. I think @benjdlambert has a good handle on the Scaffolder part (not saying he will do all the work to be clear), but I think we for sure need help with supporting multiple tokens on the GitLab side from the broader Community of GitLab users.

**Comment by horsfallnathan** [comment]
I can tackle the multiple tokens part by taking a cue from the Azure implementation if that's ok.

**Comment by dariozachow** [comment]
> I can tackle the multiple tokens part by taking a cue from the Azure implementation if that's ok.

Sure, this would be awesome.

**Comment by benjdlambert** [comment]
Been thinking about this a little bit, but I'm wondering if something like `plugin` scoped `integrations` config could work best.

```yaml
integrations:
  plugins:
    catalog:
      github:
        - host: github.com
          token: abc
     scaffolder:
       github:
         - host: github.com
           token: def
```

Or something like this? It's quite a large refactor to how things work today, so it's for sure not gonna happen over night, but thinking as we get to more config driven integrations of Backstage, this kind of allows that without writing code to make this happen.

**Comment by MonicaG** [comment]
I'm also interested in this feature

**Comment by azimkhank** [comment]
I'm interested, too.
