### ISSUE TITLE
🚀 Feature: OpenAPI v3 output format for config:schema command

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#22646]
### 🔖 Feature description

A flag that allows the output of the `config:schema` command to be consumed by OpenAPI tools; e.g. it'd be nice if you could use something like [`swagger-cli`](https://apitools.dev/swagger-cli/) to run something like

```bash
swagger-cli validate -d <(yarn backstage-cli config:schema --openapi)
```

without errors.

### 🎤 Context

The [Tanzu Developer Portal](https://tanzu.vmware.com/developer-portal) involves packaging a Backstage app as a [Carvel Package](https://carvel.dev/kapp-controller/docs/v0.49.x/packaging/#package) for installation on Kubernetes. In general these packages describe their configuration parameters with an OpenAPI schema -- this is where it would be really helpful to be able to use the output of `config:schema` in the `valuesSchema` field verbatim.

### ✌️ Possible Implementation

I'm really drawing a blank here -- in theory I can imagine there would be an isomorphism between OpenAPI schemas and the JSON schema used by backstage:

https://github.com/backstage/backstage/blob/f600aa87a3b3f7700544653b8560c86cba3cd479/packages/cli/src/commands/config/schema.ts#L31-L43

but I'm not sure if there are packages out there that perform the transformation.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sennyeya** [comment]
👋 ! This one's tricky, both because of OpenAPI to JSON schema constraints (OpenAPI 3 is a subset of JSON Schema 5) and because of #20424. Depending on the default behavior of Carvel (`additionalProperties: true` or `additionalProperties: false`), the lack of objects in the generated schema could cause issues for base functionality.

If that's not an issue, I whipped up a script to do this for you,
```ts
import { writeFileSync, readFileSync } from 'fs';
import { jsonSchemaDocumentToOpenApi } from 'openapi-json-schema';
import { load } from 'js-yaml';
import * as jsonTraverse from 'json-schema-traverse';
const { default: traverse } = jsonTraverse;

const schema = load(readFileSync('./test.yaml'));

traverse(schema, currentSchema => {
  // get rid of custom keys
  delete currentSchema.visibility;
  delete currentSchema.deepVisibility;
  delete currentSchema.$schema;

  // deprecated should always be a boolean not truthy.
  if (currentSchema.deprecated) {
    currentSchema.deprecated = !!currentSchema.deprecated;
  }
});

// JSON Schema to Open API
const openApi = jsonSchemaDocumentToOpenApi({ definitions: { schema } }, {});

openApi.info.title = 'My Application';

openApi.info.version = '1';

let spec = JSON.stringify(openApi);

// there's a bug in the underlying library for the config:schema command that creates an invalid schema for `allowedContexts`.
spec = spec.replaceAll(
  `"items":[{"enum":["*"],"type":"string"}]`,
  `"items":{"enum":["*"],"type":"string"}`,
);

writeFileSync('test.openapi.json', spec);
```

OpenAPI v3 is a subset of draft 5 JSON schema (https://swagger.io/docs/specification/data-models/keywords/), but our CLI outputs draft 7 JSON schema (https://backstage.io/schema/config-v1). They can be converted back and forth but not easily, thankfully there is a library for such a thing from grantila (who once contributed to this project), https://github.com/grantila/openapi-json-schema. I think it would solve a lot of your use cases. The gotcha here is that it's an ESM module and doesn't support CJS 😞 , meaning it would be difficult to add to the CLI.

I'm not confident this is something that would make sense in the CLI itself (@Rugvip 👀). From the above script, there are a few bugs in the output config already that we'd want to fix before creating an output, as well as what would the OpenAPI `info` version and title be?

**Comment by jamieklassen** [comment]
@sennyeya wow, thank you so much for your deep insight and fully worked example!

**Comment by Rugvip** [comment]
Do you feel strongly about having this be part of the CLI? I'm feeling it's perhaps a bit of an odd use-case compared to using JSONSchema tools directly? or it would be more of an implementation detail of how we do the config validation
