### ISSUE TITLE
💬 RFC: Backend Plugin Outbound Metrics with OpenTelemetry

### ISSUE THREAD

**Issue by sambutler98** [backstage/backstage#22665]
### 🔖 Need

Hi all,
I’m working at a large organization with our own implementation of Backstage and are leveraging external services such as Jira, Jenkins, Spinnaker, and more. We do not operate these external services and want to ensure we do not overload them.

We anticipate a substantial number of API requests being made to these external services and feel that it would be useful to us to be able to monitor these requests we are making towards them.

The goal would be to track key metrics, including the total number of requests over periods of time, their duration, and the success or failure rates. By monitoring these parameters, we aim to gain insights into the overall health and efficiency of our interactions with external services.

### 🎉 Proposal

We have two different solutions to the problem above and would like input on which of these is better or even if there is another better way. We would also be willing to contributing one of these if it is wanted by the community. For both of the solutions we have we are using OpenTelemetry to gather the metrics and to make API requests to these external services we are using fetch.

**Solution 1**
Simple diagram of solution:

![appMetrics1](https://github.com/backstage/backstage/assets/78928533/303fd283-f655-46bf-8cfb-d461741f37ca)

In the createPlugin function of the plugin that metrics are to be collected we are passing an optional metricsHandler object in the router options. (Shown below)

```
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    discovery: env.discovery,
    identity: env.identity,
    tokenManager: env.tokenManager,
    // If metrics collection is not wanted remove the below line
    metricsHandler: new CustomMetricsHandler('**pluginName**')
  });
}
```
Then, when performing the API call we do:
```
const response = await metricsHandler.fetch(**someUrl, someInit**)
```
If the user has passed a metricsHandler object, this will perform (in our case) CustomMetricsHandler.fetch() which:

- Does fetch()
- Increments a counter
- Measures the time taken for the request

On the other hand if the user doesn't pass this metricsHandler, DefaultMetricsHandler.fetch() is performed which simply performs a fetch().

**Pros:**
- Passing the users own implementation of metricsHandler in the createPlugin gives flexibility, so if someone does not use "fetch" but other functions to make rest calls, then can pass their own implementation and not use CustomMetricsHandler/DefaultMetricsHandler
- Metrics gathering is separated from plugin implementation in a way, that plugin does not know how metrics are being gathered
- User can enable/disable in createPlugin function, which is unique to each user

**Solution 2**
Simple diagram of solution:

![metrics2](https://github.com/backstage/backstage/assets/78928533/313b4564-a452-4a62-b43b-cb362a29060d)

In this solution we are using the app-config.yaml file to set/unset flags that enable or disable metrics collection for plugins. We have created a fetchApi function (shown below) that uses the CustomMetricsHandler.fetch() if the flag is set and DefaultMetricsHandler otherwise.

```
export const fetchApi = (config: Config, url: URL | RequestInfo, init?: RequestInit | undefined) =>{
  let metricsHandler: any;
  if(config.has('metrics.plugins.jira')){
    metricsHandler = new CustomMetricsHandler(**pluginName**)
  }else{
    metricsHandler = new DefaultMetricHandler();
  }
  return metricsHandler.fetch(url, init)
}
```

And then when we are making the API call we can do:

```
const response = await fetchApi(config, **someUrl, someInit**)
```

**Pros:**
- Less of plugin code changed - only have to change where fetch() was used to use fetchApi() instead
- Enabling/disabling metrics are done by simple flag in app-config

We are wondering which of these is the best solution or if there is another better way. We're also wondering if it would be acceptable to contribute any of these solutions (perhaps to backend-common) so that it could be used in plugins as we also plan on contributing some plugins to Backstage which would be using one of these metrics gathering solutions. If there is any more clarification needed please do not hesitate to ask. Thanks!

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by sennyeya** [comment]
👋 , this would be really cool to have set up! Are you current using `node-fetch` or experimental `fetch` in your plugin code? I raise this because, there's [some concern](https://github.com/backstage/backstage/pull/22658#discussion_r1475962316) with using Node's `fetch`  and the general Backstage default is `node-fetch` for now.
- If you're currently using `node-fetch`, have you already taken a look through [this issue](https://github.com/open-telemetry/opentelemetry-js/issues/1315) on the OTEL side? It looks like it may do what you're looking for without changes to library code.
- If you're currently using Node `fetch`, have you taken a look through https://www.npmjs.com/package/@opentelemetry/instrumentation-fetch? In addition to the `node-fetch` solution (for code in this repository), this may provide the instrumentation you're looking for.

**Comment by freben** [comment]
First, the above response in reference to opentelementry and its instrumentations is probably the right way forward. We are [leaning into otel](https://backstage.io/docs/tutorials/setup-opentelemetry) fully now.

Adding some more extracurricular context:

It would be unexpected to have a metrics handler expose fetch itself. What if there's a tracing handler? And a rate limiting handler? And an auth injection handler? :)

If you can't use otel instrumentations, you still have the option of accepting a fetch implementation as input upon construction of your code, similarly to [what the catalog client does](https://github.com/backstage/backstage/blob/d3a9cd3afa5c27ef38b413e166e258b5d42beb87/packages/catalog-client/src/CatalogClient.ts#L59). Then anyone is free to pass in a clever wrapped fetch version to it.

In the frontend this is trivial, because of the existence of [the `fetchApiRef`](https://backstage.io/docs/reference/core-plugin-api.fetchapiref/) which all frontend code [is expected to use](https://backstage.io/docs/architecture-decisions/adrs-adr013).

In the backend, we have not yet made such a wrapping concept. Instead people generally just use `node-fetch` directly. With the emergence of [the new backend system](https://backstage.io/docs/backend-system/architecture/index) and its [builtin services](https://backstage.io/docs/backend-system/core-services/index), it's a fairly low hanging fruit to consider introducing a `coreServices.fetch` there for plugins to use, and for adopters to replace with richer implementations of.

But specifically for basic telemetry of fetch - yeah, direct usage of otel should be sufficient as far as I know.

**Comment by fordneild** [comment]
I would also like to implement OTEL in backstage to track 
- performance of custom endpoints
- current rate limit info for the various 3rd party services like the GitHub API
- Catalog information

But im really unsure how to get started. Does anyone have a simple example of how we can do this in a backend plugin?

**Comment by freben** [comment]
@fordneild Backstage doesn't get itself involved much in telemetry. Since you control the code yourself, you set it up mostly according to regular opentelemetry docs, and then emit signals following regular opentelemetry docs. There's a [tentative setup tutorial](https://backstage.io/docs/tutorials/setup-opentelemetry/) and then there's a couple usages [throughout the main code base](https://github.com/backstage/backstage/blob/e8cbcfd9c2c62cac1d3e53c2c89d233b9303db9c/plugins/catalog-backend/src/stitching/progressTracker.ts#L33) you can look at for inspiration. The rest is mostly up to you to figure out, regarding where to inject those meters.
