### ISSUE TITLE
💬 RFC: Enable AutoLogout by default to follow Secure by Default principles

### ISSUE THREAD

**Issue by coreydaley** [backstage/backstage#22692]
### 🔖 Need

Following Secure by Default principles, it would make sense to enable the AutoLogout feature by default and provide documentation for how to configure or disable it. Most web applications have this feature enabled by default for security purposes and I would think that the percentage of users that want it enabled would far outweigh the percentage of users who do not.

### 🎉 Proposal

Update the App.tsx file to include `<AutoLogout />` and update app-config.yaml with options to configure the `AutoLogout` feature via environment variables.
Example pull request: https://github.com/backstage/backstage/pull/22691

### 〽️ Alternatives

None

### ❌ Risks

The only risk that I can think of is if someone was using a script to login and scrape the web page, they would have to update their script to deal with logging back in if the session times out.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Won't jump on this immediately as I imagine this might be a slightly controversial topic due to the end user impact. Will look for feedback on the community for this one (please 👍 / 👎)

On a separate note we'll want to make it easier to install if anything, might be something we ship later on as part of the new frontend system (#19545) though

**Comment by coreydaley** [comment]
@afscrome I saw you gave a thumbs down, would you mind elaborating on your reasoning for not wanting it enabled by default so that the community can discuss? Thanks!

**Comment by coreydaley** [comment]
@Rugvip I am definitely looking forward to the feedback and discussion around this, and thank you for the link, I will check it out.

**Comment by afscrome** [comment]
Generally on the topic of Auto Logout, it is security control that intentionally trades off usability for security.  Whilst some organisations may wish to make that trade off, many won't. Backstage is a Developer Experience tool.  One of the major ways of improving developer experience is by eliminating unnecessary busy work / toil.  There is something ironic about the default configuration of a developer portal enforcing toil by making a user re-authenticate if they leave the tool idle for short periods of time.  

On a more personal note, the only websites I've really seen that have idle based auto logouts are 1) websites I hate to use or 2) banking websites.  (And arguably 2 is a subset of 1 🤣).  My use of backstage is primarily one where it is open all day in the background, and I'll then refer back to it every so often.  An auto logout implementation would likely mean I'd have to re-authenticate every time I have to use backstage, which would put me off using it.

On the current implementation of auto logout, from what I can tell the original PR (#18188) is purely a browser based implementation, with no changes made to the auth backend.  At a high level, it calls the browser based logout apis based on some kind of idle activity timer.  Security controls in the browser can't be relied upon as they can be bypassed by the end user, so from your threat modelling you would have to assume that Auto Logout could be bypassed in turn meaning you'd have to effectively assume that Auto Logout wasn't there.  To be relied upon, I think the auto logout needs some kind of integration with the auth backend - likely through some kind of implementation of sliding expiration.  I also haven't looked into whether the backstage sign out implements any form of revocation - i.e. if the backstage auth token / cookie is exfiltrated before the auto logout kicks in, can they be re-activated.

On top of that, depending on the upstream authentication provider, auto logoff may be completely worthless.  Logging out of backstage doesn't necessarily sign the user out of the single sign on session of the upstream auth provider.  Once you log out of the Microsoft provider in backstage, it only logs you out of backstage not Microsoft itself.  Meaning that when you click the sign-in button again, Microsoft will log you in to backstage again as you're still signed in to the underlying single sign on session with Microsoft.  Meaning the auto logout causes purely user frustration, and no security benefit.  I suspect proxied sign in providers suffer from a similar issue.  Again, auto logout likely needs some more integration with the underlying auth backend - both in terms of knowing whether auto logout is effective, but also in terms of working with the session lengths of the underlying auth provider.

Overall, I'm not sold on auto logout being a default, and in particular I think having the current implementation enabled by default will only provide a false sense of security, rather than any meaningful security benefits.

**Comment by benjdlambert** [comment]
@coreydaley I agree with @afscrome that it's a lot of false sense of security. 

I wonder if it makes sense to adjust your PR so that it's included in `create-app` but it's disabled by default or something?

**Comment by coreydaley** [comment]
@benjdlambert @afscrome According to the official documentation (https://backstage.io/docs/auth/autologout/), AutoLogout provides `optional added security to Backstage`, if that is not the case, I feel as though the documentation is lulling people into a false sense of security and that the feature does not actually provide any security at all according to @afscrome . Should, then, the documentation be updated with a warning of some kind? Or maybe the feature should be pulled until it does, in fact, actually provide the security that it says it does?

**Comment by Rugvip** [comment]
@afscrome not sure the brower-only implementation is too much of an issue tbh? If an attacker has that level of control no kind of backend integration is really gonna help right? The actions of the attacker would be indistinguishable from the user.

I do think the auto-logout (and logout in Backstage in general) does have some security benefit. It clears the refresh session cookie and calls the logout endpoint of the upstream provider, which would typically invalidate any active access tokens for the provider. It's a fairly minimal benefit though tbd, since it really just shrinks the window for session hijacking. Physical access is still the same unless you've configured a very strict auth provider - which you can do, and I think that's when it really starts making sense to use auto logout.
