### ISSUE TITLE
🚀 Feature: Move to Yarn v4

### ISSUE THREAD

**Issue by tudi2d** [backstage/backstage#23327]
### 🔖 Feature description

Yarn v4 has been out for a while & is considered stable. As we moved to Node 18+ support it should be compatible with our current technologies. The migration from v3 to v4 seems to be more straightforward than v1 to v3.

### 🎤 Context

Blog post: https://yarnpkg.com/blog/release/4.0

### ✌️ Possible Implementation

Breaking changes, which would affect us:

- All official plugins (typescript, interactive-tools, ...) are now included by default.
- The yarn [workspaces foreach](https://yarnpkg.com/cli/workspaces/foreach) command has a slightly altered syntax.

As the migration from v1 to v3 was more difficult a migration guide exists. This guide should be updated & adjusted for v4 allow people to potentially still migrate.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by ourchitectureio** [comment]
https://github.com/backstage/backstage/issues/23176#issuecomment-1971956262

**Comment by tudi2d** [comment]
Does this mean you want to pick up this issue? As you mentioned it should work, but still there are different explicit references to the 3.x version & the breaking changes should be respected & reviewed.

**Comment by alper98** [comment]
I started work on this, feel free to assign me

**Comment by taliesins** [comment]
I raised this PR https://github.com/janus-idp/backstage-showcase/pull/1145 to upgrade from Yarn 1 to Yarn 4. Might be useful looking to do the upgrade.

**Comment by tonglil** [comment]
Chiming in as a plugin developer, I would prefer if the backstage ecosystem switched off of yarn to something else.

After bitten by juggling different default versions of yarn locally, in CI, and in Dockerfiles, it makes me think twice to work in this ecosystem.

**Comment by benjdlambert** [comment]
@tonglil I appreciate your thoughts here, we've also looked at how to remove `yarn` as a dependency, see #20658.

It's something we're hoping to support as we're not /super/ coupled to `yarn` but there's some things that we need to update in different bits of tooling to get us to that stage.

**Comment by ourchitectureio** [comment]
From v1, Yarn supports forward compatibility by providing support for pinning project-specific versions. The biggest leap in compatibility was v1 to v2.

That means a project can run v4 while v1 is globally installed, and v4 will run from the existing v1 install (it's weird and cool). Another project might use v3. That's okay and also very cool.

Upgrading Backstage to v4 yourself is not only easy, but it is recommended to pin your own version and regularly upgrade it to the latest (just like following Node LTS).

Example:

1. Run the node docker image as an interactive shell `docker run --rm -it node`.
2. Run `corepack enable` to turn on Node's built-in support for alternative package managers.
3. Run `yarn --version` and notice we are on version 1.x.
4. Make a random directory and switch to it `mkdir ~/mysandbox && cd ~/mysandbox`.
5. Run `yarn set version stable && yarn --version` to upgrade yarn for this specific directory ("project"), and you will see version 4.x
6. Check elsewhere `cd .. && yarn --version` and you will see v1.x.
7. Bonus: Visit yarn releases on GitHub and copy the release path to a specific version of Yarn's. "cjs" release file and run the same example but with `yarn set version [URL]`. This is the preferred method of pinning a specific yarn version to a project.

Do this same command to a Backstage instance to upgrade to v4.x. Keep in mind that upgrading an older instance that was using v1.x will likely involve a lot of work. It's usually best to install a fresh, new instance code base and then compare your version with the new one.

All that said, I agree, though. Backstage project itself should upgrade along with the generated template output.

P.s. I'm familiar with npm, pnpm, yarn, and more since they all started, and my best recommendation for using other projects is to just use what they use and embrace that different projects will pick different things. Or, make a pull request that introduces a fully functional alternative that still satisfies the project's needs while making a clear case for extra value to the project, its maintainers, and the community. It's probably best to also get buy-in from existing and prominent maintainers. If it smells like a person's opinion, the comments and likelihood for merge will probably be disappointing. For your own stuff, feel free to have an opinion.

**Comment by Rugvip** [comment]
Closed by #26610
