### ISSUE TITLE
💬 RFC: Modifying navigation and global header

### ISSUE THREAD

**Issue by ShiranHi** [backstage/backstage#23424]
### 🔖 Need

We faced a situation where the side navigation was getting crowded with items. The flexibility of each plugin to add more navigation items makes the side menu busy and makes it hard to scan it and find the right action.
Some [research](https://www.nngroup.com/articles/vertical-nav/) supports keeping the main navigation concise and above the fold area. It helps new users scan and learn what they can do using the product and is faster and easier to navigate between the pages. In addition, it was found that locating the search action on top header makes it easier for users to find it.

### 🎉 Proposal

It seems that there are some actions users regularly find on the header, such as the search bar, profile, settings, and help. In addition, adding a “Create” button on the header can help users find all actions they can perform in one place. Currently, a global header component does not exist in Backstage and I'll be happy to hear your opinions. 

![01 Global header](https://github.com/backstage/backstage/assets/77277517/515c1b87-a6e7-447d-82c5-e1b813828f2f)
 
<img width="4752" alt="Navigation" src="https://github.com/backstage/backstage/assets/77277517/c939ab19-72a8-4496-9890-e23da387450d">

### 〽️ Alternatives

Also tried a bright mode for the navigation and the header components:

<img width="3019" alt="Bright" src="https://github.com/backstage/backstage/assets/77277517/8ed1fda5-cfd8-480c-af31-6d2a56bb4373">

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by alper98** [comment]
We have this in our app.

We're quite happy with it 😀

**Comment by emmaindal** [comment]
Hello @ShiranHi, thank you so much for presenting this proposal which also links out to research on the subject! Super valuable. I think this is a great point, and as you touch on already - especially when the number of nav items grow. I think at least we can offer it as an option for adopters to bring in to their Backstage instances, however - I'm not sure if we should provide a specific Backstage component for it, or just an example of how one can bring in the Mui AppBar component. 

For me to easier understand the value of a custom component or not, i'm curious to know - if you customize the App and bring in the [AppBar component from Mui](https://mui.com/material-ui/react-app-bar/) today, does that require a lot of changes to how the layout currently is rendered? I can play around with this on my side as well but interested to know if you have been looking into it? 

Maybe @alper98 you can answer this too if you have it in your app?

In any way, I'll run it by our designers and see if they have any input as this is a bigger change to the App layout. 

Thank you!

**Comment by alper98** [comment]
I should have been more clear, i didnt mean we have **exactly** this. 
However, we do have something resembling the AppBar, with the search bar, the top right settings etc.

What we're happy with, is the top navigation in generel.

**Comment by tcardonne** [comment]
Hello :wave:

At Adevinta we really liked the Spotify's original layout (the one that is showcased in "old" demos, like [this one](https://www.youtube.com/watch?v=1XtJ5FAOjPk)) and we implemented it on our instance with a custom component based on Material UI's AppBar.

![image](https://github.com/backstage/backstage/assets/2379631/5bcab414-1b15-480b-aaf7-53e91f617a8c)

For us, the biggest advantage of this layout is that it gives a lot of space for the content and it allows us to create dropdowns for the user profile menu or the _Manage_ link.

Also, we also forked the EntityLayout component to use vertical tabs instead of horizontal. This is more tricky because it required to copy some Backstage's components in our codebase to update a small part of it.

> if you customize the App and bring in the [AppBar component from Mui](https://mui.com/material-ui/react-app-bar/) today, does that require a lot of changes to how the layout currently is rendered?

Actually for us it was pretty simple to replace the sidebar in the Root.tsx file. There's a small `BackstagePage` style override to add in the theme to avoid a double-scrollbar and an issue with the Scaffolder Template Editor (ie, change the `overflowY` property to `visible` and `height` to `calc(100vh - 55px)`.

The only small drawbacks are that it made us drop the `Shortcuts` sidebar plugin and there's still the "Pin sidebar" setting (a bit hard to remove without forking/copying components).

Hope that helps!

**Comment by vinzscam** [comment]
> Hello 👋
> 
> At Adevinta we really liked the Spotify's original layout (the one that is showcased in "old" demos, like [this one]

wow good job!

**Comment by ShiranHi** [comment]
> For me to easier understand the value of a custom component or not, i'm curious to know - if you customize the App and bring in the [AppBar component from Mui](https://mui.com/material-ui/react-app-bar/) today, does that require a lot of changes to how the layout currently is rendered? I can play around with this on my side as well but interested to know if you have been looking into it?

I haven't had a chance to take a look on that component, but it seems like it could be a promising solution! I'm curious if we can incorporate it into the [Backstage Design System guidelines](https://backstage.io/docs/dls/contributing-to-storybook) and [Figma file](https://backstage.io/docs/dls/figma/).

**Comment by awanlin** [comment]
Wondering if something like this makes more sense as part of the `backstage/community-plugins` repo as a sort of shared components package? Then on the `backstage/backstage` side we should make it easier to create things like this and the proper "slots" to place them.

**Comment by jmtingey** [comment]
We have implemented an across-the-top header to allow utility navigation (top right) to be organized in one place, and expand over time as the system grows. I was the designer on this, not the engineer, so I cannot speak to implementation details. One thing I think would be very awesome, as this is considered, is to figure out if this could be a config option, for example:
 
`  header: full-width
`
or
`  header: nav-adjacent
`

![image](https://github.com/backstage/backstage/assets/127445644/9cd943e0-746a-4c54-be37-8c00f69eabf6)

**Comment by ShiranHi** [comment]
@emmaindal hi, I'm just curious about your thoughts on the best approach here. If we have a Backstage instance and we're considering adding a global header, do you think it will be best to follow the guidelines shared by @tcardonne, or do you believe we could develop a specific Backstage component instead? Just trying to figure out how to move forward and whether we can close that issue

**Comment by webark** [comment]
I think a lot of companies would want to have slightly different layouts. We are about to start on a "re-theme" to redo the sidebar  header, and entity tabs.

What do you think about transitioning this RFC to be about modifying the existing navigation to allow for greater customization, as well as being able to leverage standard mui themes more easily?

**Comment by awanlin** [comment]
Yes, agree with you on this @webark. As we break out the plugins into their own repo the current Backstage repo will be more of a core framework and smaller building blocks. The core should make it easy to build things like this. 

I would still like to see a shared component library with things like this in the community plugins repo though. Some orgs will be happy to pull an opinionated version of this instead of having to build it all.

**Comment by webark** [comment]
> Some orgs will be happy to pull an opinionated version of this instead of having to build it all.

Totally.. ideally that will be as much of a mui theme driven thing i'd say right? I know there are a lot of existing mui themes out there.

**Comment by ShiranHi** [comment]
> What do you think about transitioning this RFC to be about modifying the existing navigation to allow for greater customization, as well as being able to leverage standard mui themes more easily?

@webark makes sense to me, I updated this RFC to gather all the suggestions of the side navigation and the header in one ticket

**Comment by awanlin** [comment]
@ShiranHi, I feel like that's the wrong direction. Would it not make sense to break this up into features? Then orgs can put those together to make a header and sidebar that works for them? I'm thinking like Atoms, Molecules, Organisms, etc. (Atomic Design). As you can see each Org has their own design language which means we should not be forcing one way but have building blocks to make it easy.  

If we are going to do this as some massive change then we probably need to create a BEP for this. That would allow us to better iterate on what the plan would be. I do not use Figma but is there a way to version things there? That might be a better way to track this as well.

**Comment by webark** [comment]
For us, the main benefit would be primarily moving more towards MUI component and react router alignment. Another point we have ran into is that there is no standard way (at least that i'm aware of, do t want to thread the thread) of doing entity sub "tab" linking. 

Like i could see a feature being having the entity link taking a sub route. another one could be easier customization of the entity tabs, perhaps just event exposing some hooks. Same could be done for the side nav, but that appears easier to do at this time already. Another could even be migrating to aligning with react routers route context? 🤔

Anything like a "create" drop down, or an avatar menu, or a header search, etc, could stem from these building blocks, and either just be community contribs, or community plugins.

But i feel the more we can push for standard integrations with industry tools like MUI and react router, the more flexibility it provides It also leads to less maintenance burden and better long term stability.

**Comment by ShiranHi** [comment]
> If we are going to do this as some massive change then we probably need to create a BEP for this. That would allow us to better iterate on what the plan would be.
My original suggestion was to add a global header component to simplify things for users, less clicking around in the side navigation and less crowded navigation overall. If we can find a solution using MUI components, I think we can close this RFC.

>Anything like a "create" drop down, or an avatar menu, or a header search, etc, could stem from these building blocks, and either just be community contribs, or community plugins.
Thank you for explaining that, it wasn't clear to me that these can be part of a plugin instead of making it a core Backstage feature.

> But i feel the more we can push for standard integrations with industry tools like MUI and react router, the more flexibility it provides. It also leads to less maintenance burden and better long term stability.
I believe offering a global header to be used in Backstage, or only using the side navigation could help other organizations who use Backstage. On the other hand, I understand the reasons for following the MUI component and keep it open and flexible.

This RFC was created after we faced issues with growing and cluttered side navigation. I'll bring this issue to our dev team and see if we can incorporate a MUI global header on our UI. For now, I will close this ticket.

Thank you everyone who responded, it was helpful to learn about your solutions!

**Comment by awanlin** [comment]
Hi @ShiranHi, just to be clear my intention wasn't to make you close this - it's an RFC so was sharing my comments on something I feel strongly about. I do think there is huge value in an optional Global Header and there's clear demand for this in Orgs that have a more mature Backstage adoption but I just don't think it should be a default out of the box feature. 

But based on your last comment it does seem that you got the feedback you were looking for in the context of this RFC so would it make more sense to close this as completed?

**Comment by Rugvip** [comment]
Hi @ShiranHi, I re-opened to encourage a bit more discussion. I wanted to highlight that while we might not ship this as the default layout in a new Backstage project, we do think it's a good idea to add components for a top bar alongside our `Sidebar` components so that adopters can use them if desired. It'd likely be an addition to the `@backstage/core-components` library, and by having it be part of the core components we open up for plugins to build integrations for it more directly, or at least making sure things like nav items that they export work well both in the sidebar and top-bar.

👀 @backstage/discoverability-maintainers as well, since I believe you've explored this in the past

**Comment by sgahlot** [comment]
One of the partners we're working with, have a custom solution by adding a menu item that, when clicked, opens up a popup with all the apps that can be navigated to. Is that something worthwhile to look at? 

<img width="1062" alt="sidebar-all-apps-popup" src="https://github.com/backstage/backstage/assets/2349910/e099eefa-a6cb-48c7-9559-fa81a54686ad">

**Comment by nia-potato** [comment]
we are also really interested in the old layout from the original backstage launch video, also from a personal opinion it seems like the layout of using sidebars vs the current implementation for grouping of resources is better of using space rather than scrolling through the tabs. I hope this can at least be optional feature for those who needs this layout instead of just going with default one with no choices. 

<img width="642" alt="Screenshot 2024-05-07 at 15 43 47" src="https://github.com/backstage/backstage/assets/117061613/42d2570f-08d2-46cb-9f0c-869326e48389">

**Comment by rglastra** [comment]
Bringing this discussion back since UX is now a (somewhat) hot topic and Canon being in active development.

I agree with the original sentiment that the main nav gets cluttered quick and there's presently no distinction between nav items - creation vs docs vs otherwise.

**Comment by ShiranHi** [comment]
Red Hat implemented a global header if you want to take a look, it is [here](https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/global-header)

**Comment by lavanya-sainik-ericsson** [comment]
Hello All, 

The global header feature looks really useful. Based on this thread, any update on a recommended approach or something that is already provided by backstage-core as was discussed in some of the comments.
