### ISSUE TITLE
🚀 Feature: Error handling during template execution

### ISSUE THREAD

**Issue by tasiorek27** [backstage/backstage#23708]
### 🔖 Feature description

It would be nice to have a so called [stats check functions](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions). 
Would be nice to introduce such check functions:
- on failure
- success
- always
Similarly to whats available in github actions.

### 🎤 Context

Currently if one of steps fails the whole template fails immediately.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@tasiorek27 this is pretty interesting because I've actually had the thought of bringing this functionality into the software templates over the last few weeks.

I think it's a little tricky though for us to do this in a backwards compatible way. We might have to create `betaV4` of the templating syntax to do this.

We currently don't check the `if` statements when a task fails. If we were to start doing that, there could be scenarios where the `if` starts to pass even though we don't want to run the step. I'm struggling to find out if this also happens with github actions, or if they do some special checking to see if you have things like `failed()` or `always()` in the templating string itself and then evaluate those only.

We would have to change some of the `if` statements to be `if: success() and  ...` or something like that.

**Comment by regicsolutions** [comment]
@benjdlambert was this feature ever implemented? We have a use case where we need to track the failure of a template run and call a API to open an incident. It would be nice to be able to provide that API details on what action failed, the error message and the spec.owner of the template to assign the incident to the right group.

**Comment by its02003** [comment]
> @benjdlambert was this feature ever implemented? We have a use case where we need to track the failure of a template run and call a API to open an incident. It would be nice to be able to provide that API details on what action failed, the error message and the spec.owner of the template to assign the incident to the right group.

Similar question... not being able to try something in the scaffolder that you know may fail is kind of debilitating on certain actions like pulling files from specific repo branches, etc. Where we really notice this is when we're using templates to manage catalog info files and a developer is making 3 annotation changes over the course of a few hours and never merged the previous changes. In this case, we'd like to try to pull the WIP file from the pending branch and simply update the PR when merged, but we also need the same workflow to be able to open a new branch and new PR if one doesn't currently exist

The `http:backstage:request` action includes a `continueOnBadResponse` input option that already seems to solve for this... simply including this by default in all actions would be a relatively simple solve for this...
