### ISSUE TITLE
🐛 Bug Report: Installing latest @techdocs/cli fails due to unpublished version of @backstage/plugin-techdocs-node

### ISSUE THREAD

**Issue by scnewma** [backstage/backstage#23713]
### 📜 Description

Currently if you try and run `npm install -g @techdocs/cli` it fails due to:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @backstage/plugin-techdocs-node@^1.12.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### 👍 Expected behavior

Installing techdocs/cli should work.

### 👎 Actual Behavior with Screenshots

Currently if you try and run `npm install -g @techdocs/cli` it fails due to:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @backstage/plugin-techdocs-node@^1.12.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### 👟 Reproduction steps

Execute `npm install -g @techdocs/cli`

### 📃 Provide the context for the Bug.

The `1.8.6` version of the techdocs CLI was published 20 minutes ago and references:

```
    "@backstage/plugin-techdocs-node": "^1.12.0",
```

However that is not currently published. Maybe there is a race condition in the publishing process?

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by scnewma** [comment]
Note: This is working now that `@backstage/plugin-techdocs-node v1.12.0` is published. But it was broken for ~20 minutes. Maybe the packages should be published for a new release in a different order?

**Comment by benjdlambert** [comment]
@scnewma I'm gonna close this issue as it's fixed, just unfortunate timing.

I think you are right though that there is room for improvement with the publishing. We've got a lot of constraints already around publishing as not to hit rate limits etc, so we could change the order of the packages to do bottom of the dependency tree first. That said, I'm not sure it's worth the time though. 

We're looking at moving out a large amount of plugins from the main monorepo into a community plugins repository, which have their own release flows per workspace, and we expect those releases to be much faster as they're releasing much less plugins and modules rather than the 100 ish that we have to release here.

Does this seem OK?

**Comment by scnewma** [comment]
Sounds reasonable to me. Appreciate you providing context @benjdlambert!
