### ISSUE TITLE
🚀 Feature: creating custom cli template

### ISSUE THREAD

**Issue by hubofgitongithub** [backstage/backstage#23801]
### 🔖 Feature description

Documentation and mechanism to easily plug into the templating mechanism of the backstage-cli. Or being able to override existing templates to create a new plugin.

### 🎤 Context

Our Backstage for instance has been migrated to MUI 5, new front-end plugins are still generated with old material-ui 4 dependencies. This is just one example of us wanting to be more in control of what is generated for people when they run a backstage-cli template, without having to fork the cli package.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Sorry, missed this one! This is something we want but not working on immediately in the maintainer team. @minkimcello has been looking at this though

**Comment by awanlin** [comment]
Hi @minkimcello, any updates on this one? Came up recently on Discord again and I've found myself looking for something like this recently as well.

**Comment by Rugvip** [comment]
To outline a bit more of our idea for the way forward here: Convert the `new` templates into standalone definitions that work like simplified scaffolder templates. We'd also make sure that they're portable so that you can for example link to templates on GitHub as well as in the local file system/repo. We then also add a configuration somewhere where you can list the templates that you want to use in your own repo, likely also with the ability to set default/fixed parameters and so on. Overall this would allow adopters to pick the specific templates that apply to their own project and setup, along with the ability to create custom templates for internal needs.

**Comment by brendaHuang-2023** [comment]
Thanks @awanlin @Rugvip. This is a fairly common use case for us, since we have a steady stream of contributors who need to onboard to our backstage instance and create new plugins.

**Comment by brendaHuang-2023** [comment]
@minkimcello Thanks a lot for helping out. We'd like to have the new plugin set up with MUI 5 and also we use a different eslint config. So it'd be nice to be able to override the default eslint config somehow.

**Comment by Rugvip** [comment]
@minkimcello wanted to check in on your progress as we're looking to work on/ship some of this next week. Would love a draft PR to be able to start up early review/tweaks.
