### ISSUE TITLE
🐛 Bug Report: Disable DynamicPluginsTable thirdClickSort due to bad user experience

### ISSUE THREAD

**Issue by condawrangler** [backstage/backstage#23969]
### 📜 Description

Material UI by default has an odd behavior for sorting tables.
On the third click on column sort, the sorting is cleared and it looks like a bug (as our QE observed)
It's possible to disable it, but the backstage table doesn't by default and so the RHDH catalog has this behavior.
WDYT about disabling this feature?
You can see the behavior by clicking three times on sort on of the columns in the catalog table

### 👍 Expected behavior

The table should always present the data in a user friendly format. 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/142339251/1a80dfd2-c1eb-4998-b396-5ec3093cca2f)

### 👟 Reproduction steps

1. Trigger some workflows
2. go to workflows run table
3. Click sort by started 3 times (until arrow is grey)
4. Observe data in table, it isn't presented in a user friendly format. 

### 📃 Provide the context for the Bug.

It is just an eye sore, table data should always be easy for the user to read and understand

### 🖥️ Your Environment

rhdh deployed on OCP with Orchestrator and Notifications plugins installed

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Just wanted to add on some details. Backstage actually uses [@material-table/core](https://material-table-core.github.io/) for it's tables and not the ones in Material-UI. I learned about that when working on a recent update to the Catalog Index customization docs here: https://backstage.io/docs/features/software-catalog/catalog-customization#table-options

You can see an working demo of this issue here: https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all. Just click on one of the column headers three times. I do find to really notice this you need to cycle through it a few times, the arrow really helps make it more obvious IMO.

@condawrangler, I don't know what "rhdh" is can you share more details? I'm also not familiar with the "Orchestrator" plugin, can you share a link, please? I'm assuming this is what is shown in your screen shot?

**Comment by vinzscam** [comment]
The 'third option sort' is indeed useful in certain cases. However, plugin authors have the option to disable this feature if they prefer. I recommend opening an issue at https://github.com/janus-idp/backstage-plugins, as the plugin you're referring to is managed there.

**Comment by tudi2d** [comment]
Closing this in favour of the "Table improvemnts RFC": https://github.com/backstage/backstage/issues/22735. I also want to mention that the problem you are running into is related to a specific implementation of Backstage (RHDH) so you might want to reach out to that team instead of raising the issue here.

**Comment by awanlin** [comment]
Hi @tudi2d, you can actually see this on the demo site

Catalog: https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all
GitHub Actions: https://demo.backstage.io/catalog/default/component/backstage-demo/ci-cd
Docs list: https://demo.backstage.io/docs?filters%5Buser%5D=all

This does seem to be an Backstage "issue". I don't know the solution but I'll be honest it's confused me often, I've just lived with it.

**Comment by vinzscam** [comment]
> Hi @tudi2d, you can actually see this on the demo site
> 
> Catalog: https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all GitHub Actions: https://demo.backstage.io/catalog/default/component/backstage-demo/ci-cd Docs list: https://demo.backstage.io/docs?filters%5Buser%5D=all
> 
> This does seem to be a Backstage "issue". I don't know the solution but I'll be honest it's confused me often, I've just lived with it.

so what you are seeing is the "default material ui behaviour", which is inherited by all the tables.
However, plugin authors can customize this behaviour by passing custom props to the `Table` component. This is the reason why we believe this isn't a bug affecting Backstage. The behaviour might sound confusing but it actually makes sense if you think about data sorted server side according to some criteria. You can decide to sort the data asc or desc on a column or you can reset to the default sorting.
