### ISSUE TITLE
🚀 Feature: Allow to read default values with SecureTemplater

### ISSUE THREAD

**Issue by matdtr** [backstage/backstage#23983]
### 🔖 Feature description

Allow to read a default json/yaml file using SecureTemplater so it can load default values. Add this feature to the fetch:template action. 

### 🎤 Context

In our use case, we started creating some templates with Cookiecutter but now we would like to adopt more and more Backstage.  Cookiecutter has the possibility to read default values from cookiecutter.json file, but this feature is not available with nunjucks. 
This would allow also to store default values in the skeleton used by the Template and not directly inside the template

### ✌️ Possible Implementation

Combine the default values and input values into a single context object before executing the SecureTemplater render operations

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Hey :wave: thanks for this!

I think this could be a good idea, you can do defaults in the template itself by doing thinks like:

``` yaml
action: fetch:template
input:
  values:
      test: ${{ parameters.test or 'my default value' }}
```

But I guess the problem with that is that it is per `template.yaml` defaults, not per `skeleton` folder which might be what you're looking for.

Maybe we could do something similar to a `cookiecutter.json` file which doesn't get templated into the skeleton, it's just there for setting default values etc.

Do you have any thoughts?

**Comment by benjdlambert** [comment]
@margueritepd 

> (I have not found a conclusive answer)

Nope, unfortunately `fetch:template` is not compatible with `cookiecutter.json`, you would need to use the `fetch:cookiecutter` action instead which is native cookicutter support. 

This issue is about adding some form of support for it's own version and format of that file in `fetch:template`. Perhaps a `template.json` file or something, not sure what's the best direction yet.

**Comment by ChuckCrawford** [comment]
@benjdlambert : we are also thinking that it would be valuable to be able to share default variable values across template files in a single `fetch:template` action. Would you be open to us submitting a patch that did something like the following:

* If a `default_values.json` file is found at the root of the `templateDir`:
  * Run `default_values.json` through the `SecureTemplater`
  * Parse the templated result into a JSON object
  * Merge the templated result into `values` with values taking precedence
  * Exclude the `default_values.json` file from the output
* Continue templating as normal

**Comment by benjdlambert** [comment]
Hey @ChuckCrawford :wave: sorry for the delay in reply here!

Yep this seems pretty reasonable, as mentioned before I think that this is a pretty good idea if you're sharing the `templateDir` across different `kind: Template`'s, otherwise you can use defaults in the `template.yaml` definition by using `or`.

I think that your outline is pretty good, do you wanna whip up a PR and we can discuss a little bit the naming of the special file and maybe if to even have that configurable with a sensible default? I know for a fact there's going to be some repo out there that has `default_values.json` as a file for something 😅 

Thanks!
