### ISSUE TITLE
🚀 Feature: Adding badges to component page tabs

### ISSUE THREAD

**Issue by NiklasDoyle** [backstage/backstage#24094]
### 🔖 Feature description

It would be useful to have badges to the tabs on a component page. This would allow the information contained within the tabs, like status, alerts, or errors, to remain consistently visible to the user.

### 🎤 Context

These tabs are created using the `EntityLayout.Route` component like so:
``` html
<EntityLayoutWrapper>
    <EntityLayout.Route path="/path" title="Tab Name">
      <ChildComponent />
    </EntityLayout.Route>
</EntityLayoutWrapper>
```
 The title prop for this component (which is the one thats displayed) only accepts strings.

### ✌️ Possible Implementation

Add an optional prop to the `EntityLayout.Route` component to pass in a badge or a hook that can be displayed alongside the title.

<img width="712" alt="image" src="https://github.com/backstage/backstage/assets/72467374/8bc010dc-c494-4e73-a0b2-d3468737985a">

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
The "nuclear" option is to make your own `EntityLayout` entirely.

If we were to add this as a feature into the builtin entity layout, it'd probably be in the form of a fixed feature of the Route itself. Not sure if making the title a general Element is a good idea, or whether it should be a new optional `decorators` prop or similar.

An interesting thing to consider though, is what this means for the new frontend system. In that system, navigation entries like tabs and sidebar buttons are more of a "contract" of extensions being passed around, and provided by the source plugin itself rather than the integrator. And it's likely that the page itself wants to control what's being displayed in the decorator, rather than the surrounding elements. Hmmm.

**Comment by NiklasDoyle** [comment]
As a workaround, I have been able to pass a Component through the `tabProps` that returns an icon or `null` depending on the returned value of the same hook used within the tab:
```html
<EntityLayout.Route
    path="/path"
    title="Tab Name"
    tabProps={{
      icon: <StatusBadge />,
    }}
  >
    <EntityDataFlow />
  </EntityLayout.Route>
```
Not a perfect solution, but this seems to get the job done along with some styling done to the theme. It does mean that the status is being loaded in two separate places from the same hook which is a little redundant. The idea of this status badge being controlled by what is in the page itself is a very cool concept, I do wonder if the new frontend system can be used to improve this implementation.

**Comment by camilaibs** [comment]
Hi @NiklasDoyle, thank you for sharing the workaround 🙂 .
Would you like to propose a pull request with a different solution? In the event that you don't have anything in mind for now, we would like to suggest closing this issue and exploring it later if you want to try out the new [Frontend System](https://backstage.io/docs/frontend-system/architecture/index).

**Comment by NiklasDoyle** [comment]
Hi @camilaibs, at the moment I need to get more familiar with the Frontend System before proposing anything. I'll close the ticket for now, but will revisit it later!
