### ISSUE TITLE
🐛 Bug Report: Unable to enter Backstage in a codespace 

### ISSUE THREAD

**Issue by zkdan** [backstage/backstage#24172]
### 📜 Description

I can't seem to enter the instance of Backstage I made in a codespace.

### 👍 Expected behavior

I should be able to create an instance of Backstage in a codespace just like I would be able to locally, right?

### 👎 Actual Behavior with Screenshots

![login](https://github.com/backstage/backstage/assets/7177924/f8319d58-d543-41f0-ad76-e59690d4acb4)
![error](https://github.com/backstage/backstage/assets/7177924/cfc5d475-8cb2-4efa-a638-e7f0b2c59340)

### 👟 Reproduction steps

Create a new codespace and run:
```terminal
npx @backstage/create-app@latest 
yarn dev
```
Go to the URL generated by codespaces, click the `Enter` button to enter as a guest user.

### 📃 Provide the context for the Bug.

I'd like to set up a codespace that makes it easy for front-end developers learning Backstage to get up and running building components quickly.

### 🖥️ Your Environment

Codespace

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
We don't use codespaces and don't know much about its details, so in a sense you're on your own to set the app-config right for the environment at hand, just like any other environment.

When you figure it out, a small contributed guide (maybe in the `contrib` folder) could be nice though!

Anyway, seems like a regular CORS error. You probably want to set something like

```yaml
backend:
  cors:
    origin: https://crispy-happiness-...
```

**Comment by JP-Dhabolt** [comment]
I regularly develop Backstage within a Codespaces environment.  Your issue is that you are using the Browser-based environment, instead of connecting from a local VS Code instance (which will port forward to `localhost`).  In addition to the CORS issue you are running into (as local configuration expects to use `localhost`), you will likely run into issues with OAuth trusts.

This is not a Backstage specific issue, but instead the nature of doing frontend development within a Codespaces environment.  Trusted redirect URLs for local environments are almost always going to be for a `localhost` domain, and as such using the `github.dev` domain provided by the Browser-based IDE will not function.
