### ISSUE TITLE
🚀 Feature: TechDocs comment system

### ISSUE THREAD

**Issue by kissmikijr** [backstage/backstage#24216]
### 🔖 Feature description

Introduce a comment system for TechDocs. A URL-based per page comment support for docs. 

### 🎤 Context

Interacting with software documentation would be a nice addition. Users are already inside backstage to view the documentation. Would be nice to discuss certain things about the docs without leaving backstage. 
Leaving approvals, asking questions about the docs, recording decisions

### ✌️ Possible Implementation

I was thinking for a first step a pretty basic might even say naive implementation. 
Create a new backend plugin: techdocs-comments-backend. Create a table where we would store the comments for each techdocs URL. 
Extend the techdocs addon framework to be able to add a footer component. Provide a techdocs-comments package with the frontend work with the input field and the display components of the comments.
I wouldn't consider adding replies I think a similar system like GitHub PR/Issue comments would work as a starter. Only top-level comments, no replies. One tricky part is we should probably flag comments if the underlying docs changed since the comment and I'm not sure if techdocs currently is versioned or not

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
@alper98 and/or @efenner-cambia didn't you have a similar request before?

@kissmikijr, is it safe to assume that this is something Roadie would be building and contributing as open source? Are you looking for feedback on this?

**Comment by efenner-cambia** [comment]
I don't think I made a similar request, but I do agree that it would be useful. And it has been requested before: https://github.com/backstage/backstage/issues/21091

**Comment by alper98** [comment]
I've not requested it before, i have however seen a similar request.

I'm wondering though, how this seperates it self from the current techdocs reportissue addon

**Comment by kissmikijr** [comment]
@awanlin Right now we won't have time to work on this in company time.
However I personally think it's a nice feature and might going to work on this in my spare time.

 I wanted to raise this request to get a feel for it from you guys what do you think about it. Would it make sense to add something like this to techdocs. I think some changes will be needed in the core techdocs stuff for it to work properly (but might not be the case) most of it could be in their own plugins/extensions/techdocs addons etc.

**Comment by alper98** [comment]
No worries 😀

**Comment by kissmikijr** [comment]
@alper98 Great question
> I'm wondering though, how this seperates it self from the current techdocs reportissue addon

The current report issue addon uses scaffolder templates to interact with your current documentation if you would like to tweak/suggest something.

This addon aims to support comments in the way we do it currently. In the techdocs page somewhere probably under the docs imagine this thread where people can discuss stuff about the docs.

**Comment by efenner-cambia** [comment]
Any update here?

**Comment by johnphilip283** [comment]
Hi there! After some discussion, we're not sure if this is the right type of feature we want to add to TechDocs at the moment, at least not in its proposed form. Following the ethos of "docs as code", we're not sure if introducing context about documentation into a separate backend plugin's database is the right model to follow. If there are comments on certain pieces of documentation, it seems like VCS issues may be the right place for these to continue to live, especially since commenting and comment history are first-class features of VCS issues that may confusingly compete for a techdoc user's attention if both were used. 

However, it seems like there's a desired feature of "we want to view issues on this piece of documentation in context while we read it, much like Google Docs". Perhaps this could be structured as an addon to better display + raise awareness of issues within the page?

Happy to discuss this further. For full transparency, we as maintainers don't have immediate capacity to implement this idea soon, but would like to get this in a state where the community can come up with a solution.
