### ISSUE TITLE
🚀 Feature: Increase the width of the description column and make it more readable

### ISSUE THREAD

**Issue by riginoommen** [backstage/backstage#24296]
### 🔖 Feature description

Currently the description column is having low width and the content in side its truncated . it will be great if we allocate good space for the backstage description field.

### 🎤 Context

In my usecase i browse catalog to understand the s/w components. every time an additional click is needed to read the software description

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Hi! Could you provide a screenshot for context? 🙏

**Comment by starryeyez024** [comment]
@Rugvip  it doesn't seem to matter how much room is available, the description column is always very small:
![image](https://github.com/backstage/backstage/assets/456863/518b18f8-b098-4a64-9e8d-80d573216eca)

![image](https://github.com/backstage/backstage/assets/456863/16dcecd0-3520-4d3d-89e6-4ff469b1424b)

**Comment by camilaibs** [comment]
Hi @starryeyez024, after consulting with @backstage/maintainers we propose removing the description column from the default set. The description is displayed when you hover over the cell, but it doesn't seem useful. What do you think?

**Comment by starryeyez024** [comment]
Hey @camilaibs, just a couple thoughts:
- It probably depends on the team or user's needs as to which columns of data are most useful to display. It could be a great feature to extend this preference as a setting in the sidebar, so the user can toggle visibility on or off for various fields. 
- I'm not sure why the description field is limited to the max width that it is. In the first screenshot you can see that even when there are fewer fields, it doesn't occupy the available space. I would suggest removing the max-width limitation on the description field so that if/when there are fewer columns, that field in particular should be allowed to expand.

**Comment by freben** [comment]
Tables are super finicky... Can't really set an unbounded width on something like a description column, you invariably end up with that column gobbling up almost the full table size because it turned out to be full of prose, and then the name column to the left gets destroyed and clipped to just a few pixels width and one text character per line. :)

Yes resizable and selectable columns are a good thing though. Just have to have size constraints on them.

We've also had ideas floated to us to not use tables (maybe as an option at least) but instead dense card stacks where you can have the description on a row on its own so it doesn't compete for horizontal space, and stuff like that.

**Comment by starryeyez024** [comment]
Yes agreed, min/max widths are a useful approach, it's just that the max width on the description column is very small. I should have written, "I would suggest *increasing* the max-width limitation on the description field".

Also it might be worth considering if table markup is the best option. There are some other approaches using flexbox or grid that might make it easier to display, especially at smaller screen sizes. 
https://medium.com/@snowleo208/how-to-create-responsive-table-d1662cb62075

**Comment by starryeyez024** [comment]
hey @freben @camilaibs @Rugvip , any updates or thoughts on this request? Thank you!

**Comment by freben** [comment]
The [default column width is `auto`](https://github.com/backstage/backstage/blob/1490e585193837baffe97811355cd8c5a443ead0/plugins/catalog/src/components/CatalogTable/columns.tsx#L146) unless I'm mistaken. Any change to that will have significant unwanted impact on other columns, I would assume.

I am not sure what to say for this one. Tables are in general basically a lost cause for large-value columns like this. I would suggest making a pull request that tries to address it somehow and then we can evaluate that for different use cases and screen sizes, and see where it's worse and where it's better. It's so problematic that I cannot offer any kind of black-or-white feedback - have to play with something, or see a completely different solution like a card-based renderer or multi-line tables with the description on the second line, instead of what we have today, to make meaningful progress.

The default renderer for this value is an `OverflowTooltip` which allows setting the max number of rows it can occupy, so the problam can be slightly alleviated by letting these grow vertically too.

**Comment by brenzenb** [comment]
I'm also seeing this as an issue with our teams. In order to use Backstage as a service catalog for discovery, or to learn about what exists at your company and who owns it, more space for descriptions would be very beneficial for new hires. 

In many cases, application names are not going to be descriptive enough to understand at a glance, since they're often shortened due to character limit constraints in other systems. I know this is marked as "not planned", but making this column width configurable would be a nice quality-of-life win.
