### ISSUE TITLE
🚀 Feature: Make all requests use a custom User-Agent

### ISSUE THREAD

**Issue by ivangonzalezacuna** [backstage/backstage#24379]
### 🔖 Feature description

Some developers in our company have suggested us to include the `User-Agent` as part of all the requests that backstage does, whether are internal things or to external services we own.

It would be really nice to support this and allow people to set the header easily. Maybe even set the header to "backstage" per default, which might be super helpful in general for tracing.

### 🎤 Context

Unfortunately, we haven't found any easy way to do such thing. After some research and trials, I came up with a solution which requires adding a middleware in the backend and in the frontend which simply sets the header to the request. This seems to be working for most scenarios (in the frontend it works if you use the `fetchApi`, and in the backend it works always).

The only thing that we found out that is not working is related to the `swagger-ui-react` packagee, which uses its own User-Agent header and is not overridden by own custom one.

### ✌️ Possible Implementation

The solution I found locally was the following:

In the backend (new backend system), you need to override the `defaultConfigure` for the `rootHttpRouter`, and add at the beggining a new middleware which injects the header:

```ts
function userAgent(): RequestHandler {
  return (req: Request, _res: Response, next: () => void) => {
    req.headers['user-agent'] = 'backstage';
    next();
  };
}

export function defaultConfigure(context: RootHttpRouterConfigureContext) {
  const { app, routes, middleware, logger } = context;

  app.use(userAgent());
  // the rest of middlewares, routes, etc.)
```

For the frontend, the solution was kind of similar. In this case, I needed to override the `fetchApi` definition and add it to our ApiFactory list inside the `apis.ts` file:

```ts
class UserAgentInjector implements FetchMiddleware {
  apply(next: typeof fetch): typeof fetch {
    return async (input, init) => {
      const request = new Request(input as any, init);
      request.headers.set('User-Agent', 'backstage');
      return next(request, init);
    };
  }
}

export const apis: AnyApiFactory[] = [
  // FIXME: Overrides the default fetchApi implementation from https://github.com/backstage/backstage/blob/master/packages/app-defaults/src/defaults/apis.ts
  // Make sure it's always up-to-date
  createApiFactory({
    api: fetchApiRef,
    deps: {
      configApi: configApiRef,
      identityApi: identityApiRef,
      discoveryApi: discoveryApiRef,
    },
    factory: ({ configApi, identityApi, discoveryApi }) => {
      return createFetchApi({
        middleware: [
          FetchMiddlewares.resolvePluginProtocol({
            discoveryApi,
          }),
          FetchMiddlewares.injectIdentityAuth({
            identityApi,
            config: configApi,
          }),
          new UserAgentInjector(),
        ],
      });
    },
  }),

  // ...other APIs
];
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Am I misremembering or do some browsers still refuse to change that header in outgoing requests?

Hm are you suggesting that maybe this should be something that's supported out of the box instead of adding it yourself? Haven't heard the request for that before, but happy to leave this up fielding for feedback

**Comment by ivangonzalezacuna** [comment]
> Am I misremembering or do some browsers still refuse to change that header in outgoing requests?

I wasn't aware of such thing, but could be? So far it seems Firefox works fine with the setup I posted above. Not sure about other browsers

> Hm are you suggesting that maybe this should be something that's supported out of the box instead of adding it yourself? Haven't heard the request for that before, but happy to leave this up fielding for feedback

Yes, if that's something that more people might be interesting about, it might be a nice idea to have it integrated without needing developers to use a solution like the one we found instead. At least in our case the User-Agent helps us internally in certain scenarios, that's why some people asked us about making backstage use something more specific instead of the default one.

**Comment by Rugvip** [comment]
More generally on the issue: we have the `FetchApi` in the frontend for exactly this kind of customization to be possible. It could be that we want to provide some utility to make it a bit easier, but that's the facility that we want to be working with. For backend it's a bit trickier to add a `FetchApi` but it's still something that we intend to do at some point, or at least attempt. Right now it's not the highest prio though.

**Comment by ivangonzalezacuna** [comment]
That sounds like a good plan to me. Having some kind of utility which simplifies setting custom headers (not only the user-agent, maybe others as well) sounds like a big improvement already! :sparkles:

**Comment by ivangonzalezacuna** [comment]
Just bringing this up again. Is there any advance in such topics for the frontend and/or backend? It would be really nice to use that. The solution we have is not working at 100% for all cases. Some can be fixed by our internal plugins, but others need changes in public plugins, which I think it's not really a good idea.

**Comment by elaine-mattos** [comment]
Hi, 

that would also help us a lot...is there any development in this direction?

**Comment by emkah-bahn** [comment]
Please reconsider closing this issue because you are not planing to implement this.

Let me add some information from someone from "the other side". 

The user agent header and the ip and - in case of something behind authentication - the user is often the sole source of information for a webserver administrator to find out from which clients/products requests are originated and get in contact with the responsible persons behind that. And backstage plugins are able to hammer webservers **alot**.

@elaine-mattos is a member of a team who wrote a couple of backstage plugins that use some of the REST APIs from platforms my team is responsible for. Looking at the logs we found a massive number of repeating requests from a specific user and within a specific CIDR range which did specific workflows by using our API in a suboptimal way. This challenged the performance of our platform.

So Elaine and me are in the comfortable situation beeing in the same company within an internal network. Because of this my team was able to find out by using the ip and user where the massive number of API requests originated from and together with the other team where able to optimize the usage of our API.

But this will certainly not be the case for most internet exposed services. Administrators will start to implement automatic blocks by ip or useragent or use rate limits for users to prevent something that looks like a denial of service attack on the first glance.

The current situation is not sufficient for webserver administrators to get in contact with either the developers or directly contribute to open sourced plugins to make things better in the long run. But to be able to do this, they must be able to identify the product creating these requests to get in contact with developers.

How a user agent header should be defined is defined in [RFC9119 > Section 10.1.5 User-Agent](https://www.rfc-editor.org/rfc/rfc9110#name-user-agent)

Don't get me wrong ... but `node` or `node-fetch/1.0 (+https://github.com/bitinn/node-fetch)` does not really fit the purpose. Something like `backstage-plugin-<plugin name>/<version> (some additional comment like a reference to a github repo)` would be way better.

**Comment by awanlin** [comment]
Hi @emkah-bahn @elaine-mattos, appreciate the feedback but would like to provide some context that might be missing if you don't follow the project closely. 

This issue was closed stale by a service account, you can see that if you look at the issue history. This simply means that it hasn't gone up in priority and no one from the community ran with it.  The maintainers have mentioned this as well and their rough thoughts here: https://github.com/backstage/backstage/issues/24379#issuecomment-2072157742

If this is something you would like to see in place then please feel free to contribute the changes 👍
