### ISSUE TITLE
🚀 Feature: Reduce (or move) noise in changelog

### ISSUE THREAD

**Issue by mitchhentgesspotify** [backstage/backstage#24380]
### 🔖 Feature description

The changelog for [e.g. 1.26.0](https://github.com/backstage/backstage/blob/master/docs/releases/v1.26.0-changelog.md) is massive! Look at this scrollbar size:

<img width="91" alt="Screenshot 2024-04-19 at 12 04 22" src="https://github.com/backstage/backstage/assets/110673802/6daedd07-1c08-4e69-bb21-7f0a55ce9f4d">

Scanning through the changelog, so many of the changes are `Updated dependencies` where those dependencies are _other packages in this same changelog_.

### 🎤 Context

For example, `1.26.0` appears to have changed the default way that auth is handled, but it's hard to find information about that in the changelog itself

### ✌️ Possible Implementation

Perhaps all the dependency version changes can be moved to the bottom of the changelog, so it's easier to tell at a glance what direct changes have happened in the current version?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Now that we've moved out community plugins there should be a bit less noise, but it's still not gonna be lean 😅

I've added this to the "Release Updates" milestone for us to consider later on. Right now I think it would be a bit too confusing to completely remove the dependency updates, because so many packages would end up with empty changelogs 😅
