### ISSUE TITLE
💬 RFC: Perform sign-in resolution before profile transformation

### ISSUE THREAD

**Issue by Teo-ShaoWei** [backstage/backstage#24442]
### 🔖 Need

Currently in authentication, `profileTransform` is run before `signInResolver` (refactored from `authHandler` and `signIn.resolver` respectively in the old backend), e.g. in `createProxyRouteHandlers`:
https://github.com/backstage/backstage/blob/1d02904ffd7162bcfb37d51f3452391d68d47081/plugins/auth-node/src/proxy/createProxyRouteHandlers.ts#L64-L69

If the Backstage profile is solely dependent on the authenticator, then both orderings are equivalent.

However, in my org's case, we want the profile to be provided by the Backstage catalog entry, and not the authenticator. In general, I think that makes more sense as a Backstage profile of a user should be the same regardless of which authenticator is used to log that user in.

So for example `profileTransform` will retrieve the user identity, but only retain the information needed to create the `profile`. This means that `signInResolver` would need to retrieve the user identity again. Both relies on `result`, which to adhere to good TypeScript practices, we should validation within both functions. This is one of the few examples that demonstrate the murkiness of their roles.

### 🎉 Proposal

Implement the interface as follows instead:
```
const identity = signInResolver(result, resolverContext);
const { profile } = await profileTransform({ result, identity }, resolverContext);
```

This correctly expresses the fact that the `identity` should solely rely on the authenticator's `result`. An identity will always exist, even if it might be a placeholder that isn't a Backstage catalog item. This also correctly expresses the fact that the profile should be obtained from the info of the identified user.

This also allows us to perform the necessary validations just once inside `signInResolver` in the process of retrieving the user.

We can [deprecate the old function signature](https://altrim.io/posts/deprecating-function-signature-in-typescript) during the transition, opting to remove it only in the next major release.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
We'll need to keep the profile transform around because it's used for all setups of an auth provider, while the sign-in resolver is only used if the provider is used for sign-in.

I do see  the need for being able to use profile information from the catalog though. I wonder if it might make sense to add an optional profile to `BackstageSignInResult`, which is returned by the sign-in resolver? If the resolver returns a profile that would override the one returned by the transform. It's something we might even want to build into the existing helper for signing in via the catalog, as in if the catalog entity has a `profile`, it will be used instead.
