### ISSUE TITLE
🚀 Feature: pass user auth token to scaffolder action context

### ISSUE THREAD

**Issue by ZF-fredericvanlinthoudt** [backstage/backstage#24526]
### 🔖 Feature description

Allow passing the user auth token (not a service-to-service one) down to the scaffolder action context

### 🎤 Context

We have an internal API (and a companion CLI) developed in our company which is used to perform some automations.
Calls to this internal API need to be authenticated with a JWT token which we validate based on JWKS keys URL.

We would like to be able to call this internal API from within a Backstage custom template action and pass down the Backstage auth user JWT token, so we can check the validity of the token based on the Backstage JWKS keys URL `/api/auth/.well-known/jwks.json`.
In this way, it would allow us to know which user (including custom claims, like in our case email) is performing the API call.

I've also explored the options to use `ctx.secrets?.backstageToken`, which is available in the context of a custom template action, but if I decode the JWT token it only contains the claim `obo` which resolves to another JWT token that is a limited user token.
The limited user token is not sufficient in our case since we also want to read out custom claims (email in our case), and those are not present.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ZF-fredericvanlinthoudt** [comment]
I have found a way to make get the full user auth token with custom claims but it feels a bit hackish...
Getting a plugin request token on behalf of the initiator credentials and set the target plugin id to a fake one:
```typescript
const { token } = (await auth?.getPluginRequestToken({
  onBehalfOf: await ctx.getInitiatorCredentials(),
  targetPluginId: 'fake-plugin'
}));
```

@Rugvip Would it be possible to get some advice on this? Is a new feature needed for what I want to achieve?

**Comment by Rugvip** [comment]
@ZF-fredericvanlinthoudt hmm, bit of a tricky one and somewhat of a gap in our current implementation. What you've got there I expect to break once you upgrade to the 1.26 release, at which point you'll get a plugin request token with an `obo` claim instead.

One initial question to see if there's a simple parallel solution: are you able to use a different auth provider that happens to have the same information? For example if you can grab an access or ID token via OAuth from GitHub, Google, Microsoft, etc. You can include that as a client secret for the template instead, and then forward that token to the upstream service in the action. If you can use the repo url picker you can get a token from there, otherwise you may need to create a custom field extension, but more info over here: https://backstage.io/docs/features/software-templates/writing-templates/#using-the-users-oauth-token.

If that's not an option and you need to lean on the Backstage an existing option might be to fetch the user entity from the catalog if the information is available there. So validate the token in your service, and then fetch the user entity matching the `sub` claim and use information that might be available there.

If you only have access to the additional user information during sign-in and then there's no great existing solution. I think two potential options for fixing that is either that we allow or just always include custom claims in the limited `obo` token, after all it's all up to the external service to validate the token and token type anyway, and whether a limited token should be enough. Another option is that we build out the user info endpoint in the auth backend (`/v1/userinfo`) to also include custom claims resolved at sign-in, letting you both validate the token get the additional info through that call.

**Comment by ThaSami** [comment]
any workaround?
