### ISSUE TITLE
🚀 Feature: Vulnerability report for backstage

### ISSUE THREAD

**Issue by shoelzle** [backstage/backstage#24556]
### 🔖 Feature description

Currently, there's no vulnerability report for backstage, or I didn't find it.
The vulnerability report should outline all security issues currently contained in the backstage code and all its dependencies.

### 🎤 Context

In my opinion, a vulnerability report for Backstage itself is mandatory. Security is always a big issue and Backstage in its role as a framework for building developer portals should be a showcase project.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Rugvip** [comment]
We do! It's all in the "Security" tab on GitHub -> https://github.com/backstage/backstage/security

There you have the contents of `SECURITY.md` along with all past advisories browsable at the bottom of the page.

We do not generate any reports for the full dependency tree. That's because the list of dependencies is gonna be unique to each individual Backstage setup, so it wouldn't be accurate.

**Comment by shoelzle** [comment]
Thanks @Rugvip
