### ISSUE TITLE
🚀 Feature: Autogenerated sidebar

### ISSUE THREAD

**Issue by npiyush97** [backstage/backstage#24746]
### 🔖 Feature description

Any reason why not using feature avialable with docusaurus 
[link](https://docusaurus.io/docs/sidebar/autogenerated)

### 🎤 Context

devs have too manual manage sidebar.json

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
Worth a shot!

I'd expect things to be reordered in ways that we might not want, but that can be fixed by adopting the numbering system we use in some places though, e.g. https://github.com/backstage/backstage/tree/master/docs/backend-system/architecture

It might also be worth waiting with this until more of the documentation restructure is complete, #21946
