### ISSUE TITLE
🚀 Feature: Scaffolder Plugin Exception Handling

### ISSUE THREAD

**Issue by its02003** [backstage/backstage#24836]
### 🔖 Feature description

This feature aims to improve the end-user experience during scaffolder template executions and provide more explicit guidelines within the project for communicating clear status (and possible instructions) back to the template consumer in the event that an exception occurs during a run

### 🎤 Context

Current behavior:

When workflows and actions run, if they encounter an exception condition, they display the logs in addition to the alert window above the workflow visual. The way most end-users treat this is by focusing on the logs, not the message. Also, given the technical expertise of the average workflow and action *developer*, exception handling and error message "curation" seems to be deferred if the log message sends enough information to find what happened.

Unfortunately, this means that the average **consumer** of the templates and actions must also be able to parse the logs, and typically lack the knowledge of what is happening on the back end to understand the context of the stack trace.

### ✌️ Possible Implementation

The recommendation is to do the following:

1) Move the log output for a template execution to a location that will be linked (likely as a button) from the template execution screen (making it accessible for people who want to read it, but not a default visual on the template)
2) Enhance the documentation around worklows and actions to encourage extra consideration for exception handling during development
3) Enhance the workflow execution view to ensure that the error message alert window is sufficient in helping an end-user sort out the error they have received
4) Ensure some method of backwards compatibility to prevent a breaking change/encourage existing actions to adopt this by enhancing the quality of their error messages to *compliment* their logs, not default to the logs to figure out what happened

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by acierto** [comment]
Hi @its02003 👋 
This is a good initiative to help the end user with handling errors. 
In practice it can be really hard, as many things could be broken on a backend, including 3d party tools which you don't have a control. 

1. There is an option that you can keep logs hidden. It also depends who are the end users, if they are engineers, they would prefer to see logs to see what exactly happened.
2. This is a good one. In scaffolder error handling you can also use markdown, which will allow you to point to a doc link, so that users could be instructed what to do in this case.
3. All actions could be customised and in case of any error it can provide a tailored error message. What UI view can make this error be better perceived? 
4. Can you give some examples for actions what do they error now and how would you make it more compliment?
