### ISSUE TITLE
🐛 Bug Report: Search bar on techdocs is not working

### ISSUE THREAD

**Issue by fedy97** [backstage/backstage#24959]
### 📜 Description

When searching on techdocs, no results are found

### 👍 Expected behavior

Find something when typing on the search bar

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/47827254/c33c9764-4691-4601-acac-4b0ba653de92)

![image](https://github.com/backstage/backstage/assets/47827254/78497942-7bda-49a3-a8f6-887fcbb335a9)

### 👟 Reproduction steps

1. go to https://demo.backstage.io/docs/default/component/backstage
2. search something
3. No results

### 🖥️ Your Environment

https://demo.backstage.io

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @fedy97, do you have this issue with your own Backstage instance? If so can you please include details?

The demo site though handy isn't always the best to use as the source for dealing with bugs. In this case TechDocs search indexing has been disabled due to an [odd OOM error](https://github.com/backstage/backstage/issues/23047) we have as we are using the Lunr in memory search engine which we don't generally recommend for production deployments.

If I uncomment this line and add the related package: https://github.com/backstage/demo/blob/b4d9b44c8cfb8ee5b517a23b91d0de7db12a1b3f/packages/backend/src/index.ts#L31. The search works:

![Screenshot 2024-05-29 at 9 01 17 AM](https://github.com/backstage/backstage/assets/67169551/fd38352d-e85f-4640-97a0-59e1fee46d5f)

**Comment by fedy97** [comment]
Hi @awanlin you are right, we did not add that line. So we will need to change to another search engine nonetheless in prod. Do you have any suggestions? thanks

**Comment by fedy97** [comment]
Hi @awanlin you are right, we commented out that line. We can close this
