### ISSUE TITLE
🐛 Bug Report: GithubIntegration Doc links to itself

### ISSUE THREAD

**Issue by reskin89** [backstage/backstage#25092]
### 📜 Description

https://backstage.io/docs/reference/integration.githubintegration

This document states that this API is obsolete, and the link in that message takes you to this same page, so I am not sure what the replacement API is.

### 👍 Expected behavior

Take me to the non obsolete api

### 👎 Actual Behavior with Screenshots

Just redirects back to the same page you're on.

### 👟 Reproduction steps

go to:
https://backstage.io/docs/reference/integration.githubintegration

click on the link in the box at the top stating that this API is obsolete.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @reskin89, can for sure this being confusing. I "think" the issue is casing.

This is the deprecated code:

https://github.com/backstage/backstage/blob/768d2c42166ef85ae6e3a80d278d40d95f464722/packages/integration/src/github/deprecated.ts#L42

And the code that you should be using is here:

https://github.com/backstage/backstage/blob/768d2c42166ef85ae6e3a80d278d40d95f464722/packages/integration/src/github/GithubIntegration.ts#L34

If I remember correctly a few years ago it was agreed to use "Github" with the lower "h" instead of "GitHub". I do not know the reasoning, sorry, maybe it's here: https://github.com/backstage/backstage/pull/14192. 

To come full circle the URLs are capturing this issue which can lead to confusion as you have seen. We honestly should probably remove the deprecated code!

**Comment by awanlin** [comment]
Hi @reskin89, the deprecated code has been removed and the docs have also been updated to reflect this 👍

**Comment by reskin89** [comment]
Awesome, thanks @awanlin !
