### ISSUE TITLE
🐛 Bug Report: MissingIndexError appears randomly on "results per page" change

### ISSUE THREAD

**Issue by piatkiewicz** [backstage/backstage#25339]
### 📜 Description

I'm changing the number of results on the page and it seems like I've got 3 different results randomly:
1. MissingIndexError
2. "Sorry, no results were found"
3. Actual results

Couple of screenshots of what I've faced. All of them with the same simple string:

![image](https://github.com/backstage/backstage/assets/8793897/d7f07620-e165-4745-91fa-13c1d62695e4)

![image](https://github.com/backstage/backstage/assets/8793897/9f9896c8-ee4b-449e-972e-64c59345efe8)

![image](https://github.com/backstage/backstage/assets/8793897/5829e3cd-5d45-45e9-84b7-e1d37288403a)

![image](https://github.com/backstage/backstage/assets/8793897/86408724-e1b7-4c85-86ce-6f7492669513)

![image](https://github.com/backstage/backstage/assets/8793897/284c0cef-eb5b-413b-beff-a677d67c1c7d)

![image](https://github.com/backstage/backstage/assets/8793897/d67b30fa-75c9-4a66-844f-9dbd12742c4d)

![image](https://github.com/backstage/backstage/assets/8793897/9082e906-0d42-4bf9-87e2-d1a4b5ae0521)

![image](https://github.com/backstage/backstage/assets/8793897/a9a92e2e-67f2-4881-afb7-c1adc69a32b2)

I noticed there is no error when selected "All" on the left, but there's "no results" info sometimes

![image](https://github.com/backstage/backstage/assets/8793897/27b68c6d-1e85-484c-89d9-28cdfed4670c)

![image](https://github.com/backstage/backstage/assets/8793897/94e2db66-9aee-4ae8-a457-d0412e7a4e29)

I usually get this error also right after clicking "View full results" - default Result Type is "Software Catalog" for some reason (it's initially defined like that after creating an app with `create-app` script)

I'm not able to provide detailed reproduction steps including whole environment configuration, but maybe someone could guide me a little on the ways of debugging it?

Similar issues:
- https://github.com/backstage/backstage/issues/15260
- https://github.com/backstage/backstage/issues/14402

### 👍 Expected behavior

If data is found the results should be displayed.
If no data then "no results" message should be displayed.
If data loading then loading indicator should be displayed.

### 👎 Actual Behavior with Screenshots

Random results, screenshots attached above.

### 👟 Reproduction steps

Go to Search -> type a string -> click "View full results" 

### 🖥️ Your Environment

1.27.1 backstage version

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
What storage engine did you configure for your search backend? Pg, elasticsearch, lunr, etc? I'm wondering if this happens because you scaled up your deployment but only some of the nodes actually have search results to serve in the first place.

**Comment by jrkt** [comment]
I am also seeing this issue. We are using Postgres as our search backend.

**Comment by CiscoRob** [comment]
@jrkt what version of Backstage are you running? We had some new plugins added that internally bumped minor revisions due to the "^" appended to all added / bumped versions.

What crept in caused our search to break like this exactly. We're using a container with all the local, local, and local settings with a Postgres database.

Tracked back to sub-dependencies that bumped their dependency on plugin-search-* from 1.2.27 => 1.3.0 / 1.3.1 for some packages for search / techdocs. Ended up finding the right combination (assuming you're on 1.29.2 ... etc) that got us back to a functional state:

```
  "resolutions": {
    "@procore-oss/backstage-plugin-search-backend-module-announcements": "0.2.2",
    "@backstage/plugin-techdocs-backend": "1.10.9",
    "@backstage/plugin-search-backend-node": "1.2.27",
    "@backstage/plugin-search-backend": "1.5.14",
    "@types/react": "^18",
    "@types/react-dom": "^18"
  },
```

@freben this behavior is a recent one we're seeing after bumping to 1.30.x and even with downgrading back to 1.29.2 the catalog worked again, but search was busted.

Ran into the same problem reported in issue #15260 that led me here. We have a single instance deployed to our beta environment but the behaviors matched what was reported and the versions from https://github.com/backstage/backstage/issues/15260
