### ISSUE TITLE
Unable to create a plugin

### ISSUE THREAD

**Issue by saranyavignesh2123** [backstage/backstage#2537]
## Expected Behavior
I have tried to create a plugin for my backstage portal but unable to create it. Below error occurred.

![image](https://user-images.githubusercontent.com/70377631/93776084-ce737100-fc40-11ea-919e-ce7964f90415.png)

## Steps to Reproduce

Take latest from main branch and try to execute below command in parent folder.
yarn create-plugin

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):Windows 10
- Browser Information: Google Chrome latest version

**Comment by benjdlambert** [comment]
hey @saranyavignesh2123 is there any way to get some more logs from this? thanks!

**Comment by saranyavignesh2123** [comment]
hey @benjdlambert The above log got generated whenever i tried to create a plugin using below command
yarn create-plugin 
Second it will ask us to provide the plugin name- provided
Third it starts to install the plugin - Succeeded.
Fourth it starts  executing yarn lint --fix and then i got error as mentioned in above screen shot
Let me know if you need more details

**Comment by erictnilsson** [comment]
@saranyavignesh2123 what folder are you running the command from?

**Comment by adamdmharvey** [comment]
If it's OK, the code has also been vastly updated since Sept, so I wonder if you might still have this issue with a newer version?  If you can, give the newest code a try off `master` and see if you're having the same issue? If so, feel free to reopen this _or alternatively_ open a new issue with any different error codes.  Details for logs, even more specifics on environment (Node version), etc, always help in troubleshooting. I'm sure the community will be happy to dive in and help. Thanks!

**Comment by adamdmharvey** [comment]
And just for reference, but you may already have seen it, some context here: https://backstage.io/docs/plugins/create-a-plugin
