### ISSUE TITLE
💬 RFC: Resource mapping with provides and consumes

### ISSUE THREAD

**Issue by hubofgitongithub** [backstage/backstage#25518]
### 🔖 Need

The current catalog system model is nice! I love the mapping between components and apis, as provides and consumes make a lot of sense. However, this mapping feels lacking in the resource area. You can declare a dependsOn, but would semantics like consumes and provides also make sense in this area?

### 🎉 Proposal

In our current internal backstage we:

- add `consumes` relations between component <> resource, besides the "depends" one
- add `provides` relations between component <> resource and resource <> resource
- add a type for component called "infra", which can be seen as a providing component that provides resources

This allows us to say:
- we have a "infra" component called "postgres", which is owned and worked on by a team (for instance DBA's)
- this component supplies postgres clusters on which databases can run, which are provided as resources
- these clusters in turn provide individual database resources
- a service component in turn consumes such a database resource

This provides a lot of flexibility to make the infra level mapping in the catalog more complex (or not). 

### 〽️ Alternatives

Keep the current dependson structure.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Rugvip** [comment]
Two quick thoughts on your example:

> * we have a "infra" component called "postgres", which is owned and worked on by a team (for instance DBA's)

I find this one a bit interesting and where there might be a bit of a gap. An infra team that owns a component that provides as resource for other teams seems like a useful thing to model. In particular if that resource is having issues it can be good to know what component to look at. It might just be a naming thing here though, as in it would be fine to have those resource be modelled as depending on the component, rather than the component providing the resource.

> * a service component in turn consumes such a database resource

Similar to the above, I think this is just a choice of naming. Seems to me that it would be fine to say that the service component depends on the database resource too?

**Comment by Rugvip** [comment]
Yep sounds good! 👍 

Happy to keep this open for further discussion
