### ISSUE TITLE
🐛 Bug Report: Using gitlabRepoPush or gitlabMergeRequest actions resulting in 400 invalid request of files already existing when using create option to repo

### ISSUE THREAD

**Issue by twoodardgit** [backstage/backstage#25697]
### 📜 Description

We are fetching our template to ./outputs where we think . is a path like tmp/<random string>/outputs and when we debug wait we can validate the files are being fetched. 

In our sourcePath for gitlab we are using ./outputs

The actions are creating the branch and giving 400 on when going to commit the files when using commitAction of 'create'. 

All online examples show something similar to 'src' or './path/to/changes' so it is hard to know for sure but all debugging leaves us to believe we are doing it right and it has access to create the branch and we've got it to create groups so token seems ok

### 👍 Expected behavior

commit net new files that don't currently exist in the repo into the repo using commitAction of create

### 👎 Actual Behavior with Screenshots

400 error invalid request please make sure committed files aren't there

### 👟 Reproduction steps

running template

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
I think that this could help with this issue https://github.com/backstage/backstage/pull/25548

**Comment by Teo-ShaoWei** [comment]
I would suggest that the better solution is to remove `commitAction`, instead of adding `auto` to the list like #25548. The solution of relying on `Repositories.tree` is brilliant and can be applied by default for both `publish:gitlab:merge-request` and `gitlab:repo:push` (which is not covered in that PR).

As a template user, we likely want the same thing: Always be able to push a collection of files to a branch in a repo. This means:
1. If the branch exists, let user choose to create a new commit on top, or drop what we have and create a new one from the latest main branch. These can even be different scaffolder actions instead of via input configuration.
2. If files existed, always update it; else, always create it. Since scaffolder actions are stateless (until `ctx.checkpoint` somehow can help remember previous creations), there is not a use for delete.

My hunch is that during the original design of this scaffolder action, the [gitbeaker's](https://github.com/jdalrymple/gitbeaker/blob/1e9193db2405b7874dec42e120f87545631a23d7/packages/core/src/resources/Commits.ts#L324-L341) `Commits.create` method was not well-understood. This resulted in this configuration flowing outward to become a setting for this scaffolder action.

Instead of further extending that misdirection, let's help to redirect it to do the right thing. Else things get more contrived. E.g. people will not understand why we need `getFileAction` in the future, and take some time to see that it's a hack.

I can implement for us by following @Yghore's code if there isn't any one available, but I would like to seek greenlight to deprecate the `commitAction` configuration first. Also whether there's a need to even set it to deprecate, considering likely no one is using `update` and `delete` by itself imo... 😂

**Comment by benjdlambert** [comment]
@Teo-ShaoWei, feel free to make some improvements to the action. Deprecating the `commitAction` sounds sane to be honest.

Just want to also make you aware of https://github.com/backstage/backstage/issues/22244 that we are considering, but maybe they could be entirely different actions instead to support all providers that don't use specific API's, just use native `git` instead.

**Comment by Teo-ShaoWei** [comment]
@benjdlambert ooooh it's TIL for me, thanks for letting me know about #22244. Am loving it! ❤️ I have a similar thought that we need more design leadership as I was writing the above. I'm glad to know we think alike here.

Once the design has been ironed out, I'll be interested in contributing to #22244 with the community (as long as I can get work hours on it =P). `isomorphic-git`'s commit implementation makes more sense too. Other than processing a local folder as a whole (and deciding this create/update/delete mess for me), it also allows the author to be one of our human users, and Backstage to be a committer with a GPG key, which I think is the correct representation of a user-triggered but Backstage-scaffolded commit.
