### ISSUE TITLE
🚀 Feature: Can Add a Login and Signup Page

### ISSUE THREAD

**Issue by AkshatPandey-2004** [backstage/backstage#25795]
### 🔖 Feature description

A Login And Signup Page Needed to Be added

### 🎤 Context

So any account Progress can be saved 

### ✌️ Possible Implementation

.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Hi, did you open this towards the wrong project? For information about how to set up auth and sign-in, see https://backstage.io/docs/auth

There's not enough information to know what this issue is about, so I'm going to close. Please open a new issue with more information if you have a more concrete ask.
