### ISSUE TITLE
💬 RFC: Documentation should only be in `/docs`

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#25812]
### 🔖 Need

Currently there is documentation scattered across the packages and plugins folders, this makes it hard to find, keep up to date, and trust how accurate it is. 

A good example of this is the Event Framework, there is no documentation for this outside of the plugins and this creates a disjointed experience as there's no end to end flow for all the pieces of this system. This is an awesome framework and could be used by more Adopters if the docs were easier to find.

### 🎉 Proposal

We should enforce that all documentation should be stored in the `/docs` folder. This means it will show up at https://backstage.io/docs and gets index making it easy to find and kept up to date easily.

For documentation that's for something in an Alpha state we can simply note that, this has been done for the New Backend System and the New Frontend System.

### 〽️ Alternatives

We could keep everything as is and create a script that would copy the files at build time so they are included as part of https://backstage.io/docs and they would also get indexed. The downside to this is that it increases confusion as to where the content of the docs lives and we have to maintain the script.

### ❌ Risks

We continue with the current state and new feature get added without proper documentation and end up not being adopted as well as they could be because of it.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by awanlin** [comment]
One edge case are the BEPs I do not know how we can easily handle them. There is this issue requesting them be added to https://backstage.io/docs and a PR was raised but closed with this reason: https://github.com/backstage/backstage/pull/22785#pullrequestreview-1867591438. Maybe we just need to add a BEP index page that lists the BEPs and points to the items on GitHub?

**Comment by awanlin** [comment]
@aramissennyeydd @Parsifal-M would like your thoughts on this one, when you have time, please.

**Comment by aramissennyeydd** [comment]
@awanlin Thanks for opening this! I agree with the goals in this BEP, but I'm concerned about 2 things,
1. Discoverability, is being added to the docsite equivalent to greater visibility? I'm not confident it is, and I think we need to work on #23692 as well as figure out processes for blogs, announcements, etc to get the word out. Do we have GTM (or similar data) for clickthrough rate on the docsite?
2. Gatekeeping, what gets added to the docsite and why? Should we allow community plugins to host their documentation here? I'm concerned that if we don't allow community plugin, that we'd be institutionalizing a (existing) fracture of the ecosystem between per-community plugin docs and other docs.

There's also an important side conversation here about how much of the docs can be autogenerated/generated on the spot. Most Backstage plugin docs are pretty simple "add this config value" or "add this line/file to your backend", can we automate that in a way where we no longer need many of the ecosystem's documentation? That may flip the conversation for the docsite into tutorial/setup more than per-plugin installation steps.

**Comment by awanlin** [comment]
Thanks for the feedback @aramissennyeydd, that does identify some things I missed. My intention for this was that it would be scoped to the `backstage/backstage` repo. I'd like to also not include the `backstage/community-plugins` repo as part of this conversation, I think an RFC on that topic is also worth creating. Though I think it's important we currently don't have any documentation for Community Plugins on http://backstage.io/docs. Does that seem reasonable to you? 

Some thoughts on your comments:

1. The intention was for this not to preclude other ways we could improve discoverability as well as other work being done. I can say for certainty that I've had many cases helping people on Discord where they didn't know to look for something that was only documented in a package/plugin `README`. I've also personally had the experience of learning about more detailed documentation on an existing package that I didn't even know existed until someone pointed it out to me. I have high confidence this for sure helps. Is it the total solution? Probably not but it seems like an easy place to start.
2. I'd say we are gatekeeping now, we know about the events framework and where to find it but it's not in a place where it can be easily found. Could we solve this in a different way, perhaps, but again this seems like an easy step forward.

Another example to highlight is the `@backstage/integration-aws-node` this is not documented anywhere but the packages `README` which partly can be attributed to the confusion in this issue: https://github.com/backstage/backstage/issues/25482

**Comment by darylgraham** [comment]
I'll throw my 2c in as someone new to the Backstage ecosystem:

- There are many different places to look for documentation currently. That is a horrible user experience for someone learning or trying to find help. Consolidating documentation for plugins into the docsite would help with this.  
- On the other hand, the structure of documentation in the docsite can make it hard to find specific help. There are times that I've 'lost' something that I knew I have previously seen in the docs but cannot remember what page it is on. Documentation can be split between several different sections (eg: The main integration plugins generally all have sections for the Catalog Provider, Catalog Discovery, Org Discovery and Auth) as it's organised by subject area rather than by plugin. Browsing readme files in github is sometimes easier because I know that once I find the correct plugin, the docs are all in one place with nothing else to distract or confuse.
  - One caveat to this: When a plugin consists of multiple plugins (`plugin`, `plugin-common`, `plugin-react`, `plugin-node`, `plugin-backend`) the docs can again be fragmented and make you jump around to find a solution. 
- Maybe a solution would be to look at how the [API Reference](https://backstage.io/docs/reference/) docs are structured and do something similar where the docs for a plugin are grouped together but allow you to drill down into the frontend/backend/node etc documentation. This might work well with the alternative proposal of copying the readme files at build time.
- I'd support something similar for the community plugins repo, but I can understand why there is a lack of appetite to have them included in the main site. My suggested compromise would be to have a separate community-plugins-docs page/section of the site (again, like the API Reference), possibly linked from the `/plugins` page, and have the docs consolidated under there. That helps to homogenize the documentation and re-enforce the single pane of glass, but allows for enough separation that the core backstage maintainers are not responsible for the upkeep of the community plugins as well.
- Not part of this RFC, but I think there needs to be a mechanism for readers to understand how up to date a doc is. I've been working my way through a tutorial only to realise that it was already included in the version of `create-app` that I started with. If each doc had an exposed metadata field for the version of Backstage (or plugin) that it applied to, and a mechanism for 'approving' docs against a release, that would make the end user experience a lot simpler.

**Comment by aramissennyeydd** [comment]
@awanlin That scope sounds good! I'm coming around to the idea of everything in the docsite, (kudos @darylgraham for the callout about the plugin/packages issue)

1. Makes sense, I'd rather have duplicated easy to find docs than hard to find "rightly" placed docs. I'm open to try it! My point here was that organic discovery through the docsite might not solve the problem you're looking to solve. Would be awesome to see the GTM data for the docsite if possible to dispute that though 😁
2. Yup, I don't want to block this as a step forward, I just want to make sure we're solving this in a way that doesn't end up causing more fracturing of the ecosystem.

@darylgraham We have an ongoing effort for rearchitecture of the docs (and updating their content after the rearchitecture), but it's been slow going. We empathize with your pain, we know it's wild west-y. We're still going to need to figure out organization and as Andre mentions above, I think we can skip community plugins for now. To your question about version compatibility, I'd like to start with a manual approach before relying on automation, the docs have been a bit stale so we're starting a new SIG/maintainer group to focus solely on documentation. Depending how that goes we may set up automation exactly as you suggest, but I think we're a little while out from those decisions.
