### ISSUE TITLE
🐛 Bug Report: Browser navigation is not working correctly for catalog graph

### ISSUE THREAD

**Issue by sjvaiz** [backstage/backstage#25890]
### 📜 Description

As we navigate through catalog entity graph by clicking on different graph nodes, we would like to use back and forward browser navigation actions (mouse click) to traverse forward and backward in graph. However, the browser navigation doesn't function as expected. You can see the url changing in the browser navigation bar however the view doesn't get redirected to specified url.

### 👍 Expected behavior

Browser navigation should work for traversing the graph in catalog graph component.

### 👎 Actual Behavior with Screenshots

Graph can be traversed by clicking on the nodes

![Screenshot 2024-08-02 at 11 25 50](https://github.com/user-attachments/assets/6b6a098c-acf7-4fc9-b249-7714ff8c1727)

### 👟 Reproduction steps

1. Go to catalog-graph component.
2. traverse through nodes
3. Press back or forward button in browser

### 📃 Provide the context for the Bug.

The bug has been only reproduced on Microsoft Edge browsers. No other browser has been tested.

### 🖥️ Your Environment

This bug can be reproduced on https://demo.backstage.io/

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by mahendra1290** [comment]
Checked on demo application https://demo.backstage.io/catalog, back button just closes the tab when viewing full graph

**Comment by awanlin** [comment]
Go for it @mahendra1290, I've assigned it to you 👍

**Comment by mahendra1290** [comment]
@awanlin The issue lies with one of the useEffect hooks in useCatalogGraphPage.ts, which updates the URL after state changes.

When the user clicks the back button, this useEffect runs and pushes another state to history. Consequently, if the user clicks back again, the whole tab closes. I haven't identified the exact reason, but I tried disabling the history.pushState on back click, and it works just fine.

Instead of managing both URL and state, what if we treat the query as the single source of truth? We can derive our state values from the query. Instead of updating the state and then syncing it, we can just update the query parameter. Since our state is derived from that, it will also stay in sync.

Currently, it works like this:

User action (click on node) -> state update -> URL update // when user clicks on a node
URL -> state update // when user loads the page with a URL
User action (click back button) -> URL change -> state update -> URL change // we don't want this last URL change to happen
Instead, we can have:

URL -> Derived State

User action (click on node) -> update URL -> derived state syncs automatically
User action (back button) -> update URL -> derived state syncs automatically
I implemented a similar solution in one of my projects, where filters are in sync with query parameters:

What are your views on this?

```typescript
 useEffect(() => {
    const rootEntityRefs = rootEntityNames.map(e => stringifyEntityRef(e));
    const newParams = qs.stringify(
      {
        rootEntityRefs,
        maxDepth: isFinite(maxDepth) ? maxDepth : '∞',
        selectedKinds,
        selectedRelations,
        unidirectional,
        mergeRelations,
        direction,
        showFilters,
      },
      { arrayFormat: 'brackets', addQueryPrefix: true },
    );
    const newUrl = `${window.location.pathname}${newParams}`;

    // We directly manipulate window history here in order to not re-render
    // infinitely (state => location => state => etc). The intention of this
    // code is just to ensure the right query/filters are loaded when a user
    // clicks the "back" button after clicking a result.
    // Only push a new history entry if we switched to another entity, but not
    // if we just changed a viewer setting.
    if (
      !previousRootEntityRefs ||
      (rootEntityRefs.length === previousRootEntityRefs.length &&
        rootEntityRefs.every((v, i) => v === previousRootEntityRefs[i]))
    ) {
      window.history.replaceState(null, document.title, newUrl);
    } else {
      window.history.pushState(null, document.title, newUrl);
    }
  }, [
    rootEntityNames,
    maxDepth,
    selectedKinds,
    selectedRelations,
    unidirectional,
    mergeRelations,
    direction,
    showFilters,
    previousRootEntityRefs,
  ]);
```

https://github.com/backstage/backstage/blob/master/plugins/catalog-graph/src/components/CatalogGraphPage/useCatalogGraphPage.ts#L227

**Comment by freben** [comment]
Sure - whichever solves the issue. Does that interact well with the actual filter sets on the left side too though?

I tried the back and forward buttons locally for a bit, and they _sometimes_ work. Not completely broken, but sometimes it just does nothing and skips updating. This is on Chrome on latest master. Seems like a weird race condition of sorts

**Comment by mahendra1290** [comment]
> Sure - whichever solves the issue. Does that interact well with the actual filter sets on the left side too though?
> 
> I tried the back and forward buttons locally for a bit, and they _sometimes_ work. Not completely broken, but sometimes it just does nothing and skips updating. This is on Chrome on latest master. Seems like a weird race condition of sorts

Yes, the left-side filters will work fine because users can update one filter at a time. We can decide whether to set query parameters via replace or push, ensuring that forward and backward navigation functions correctly since our query parameters are always the source of truth. These parameters will be managed correctly by the browser itself when using the back and forward buttons.

This approach seems sound because clicking on some nodes allows forward navigation to work fine. The back button also works the first time, but the second click lands on a new tab screen in Chrome. In Safari, it just gets stuck in a loop.

**Comment by mahendra1290** [comment]
@Rugvip I was trying to update the tests, but still trying to figure out how to test browser navigation.
