### ISSUE TITLE
🚀 Feature: Support permission metadata retrieval of frontend only plugins

### ISSUE THREAD

**Issue by dzemanov** [backstage/backstage#25993]
### 🔖 Feature description

Currently, users can access plugin metadata via the `/.well-known/backstage/permissions/metadata` endpoint, made possible by integrating the `PermissionIntegrationRouter` into the backend plugin router:
```
const permissionsIntegrationRouter = createPermissionIntegrationRouter({
    permissions: examplePermissions,
});
router.use(permissionsIntegrationRouter);
```

Find a way how to expose permission metadata of frontend only plugins without requiring the creation of dummy backend plugins with `permissionsIntegrationRouter` for each of them.

### 🎤 Context

We would like to retrieve permission metadata information of all plugins, including frontend only plugins.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
This is by design. Frontend-only permissions can effectively not be a thing, since there is no resource that the frontend could realistically protect. For example, if a frontend plugin defines a new permission for whether a user is allowed to call a particular upstream service, nothing will prevent a user from modifying the frontend bundle to skip the permission check, or simply calling that service directly.

In the end this would lead to permissions being used as a UI toggle to simply decide whether particular features should be shown to individual users. This is a valid use-case, but not one that we want to serve with the existing permissions system as there is a large risk of encouraging insecure patterns.

**Comment by dzemanov** [comment]
Thank you for the explanation, you're absolutely right.
