### ISSUE TITLE
🚀 Feature: Implement MariaDB database support

### ISSUE THREAD

**Issue by ypetrych** [backstage/backstage#26097]
### 🔖 Feature description

Imlement MariaDB support in Backstage

### 🎤 Context

Currently, Backstage supports PostgreSQL, MySQL and SQLite. However, we also need to add support for MariaDB in Backstage and its associated plugins. Building on previous efforts, such as an issue and a PR that introduced MySQL support in the Catalog plugin, we aim to extend this work to ensure MariaDB compatibility within Backstage. Since Knex already supports MariaDB as a database backend, these updates can be made without changing the existing database abstraction layer.

### ✌️ Possible Implementation

Follow how it was done for MySQL: https://github.com/backstage/backstage/issues/18668
If it's ok with you to have MariaDB support I can look into this and create corresponding PR. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @ypetrych, this seems reasonable to me, would need to be contributed by the Community. I would suggest that we get the maintainers feedback before starting anything on this though. Maybe you could attend one of the [Framework SIGs](https://github.com/backstage/community/tree/main/sigs/sig-framework) to talk about it?

Just wanted to clarify something: Backstage only supports Postgres officially in all environments. SQLite is ONLY supported for local development. MySQL is NOT supported officially though work has been done in place to start building support for it but this is only for Core features and the larger ecosystem of plugins won't have support.

**Comment by freben** [comment]
I'd like to push back gently on this for the time being. We still only officially support postgres, to the point of considering whether it'd be a valuable simplification to tear our the sqlite support and instead use an in-memory postgres for local dev and testing needs.

The mysql support was explored for a while by the community, is spotty, and work on it has stalled. As expected it's a lot of work to support multiple database engines with fully proper behaviours across the board. The code is peppered with if statements doing different things depending on what the current backing implementation is, because it turns out that knex doesn't really help much with glossing over the truly important things; it only covers some superficial differences.

So adding one more engine while the previous one isn't in place nicely feels risky. And even if MariaDB used to be a drop in replacement for MySQL more or less, if I understand things correctly, that picture has shifted a lot over the years. See for example:

https://mariadb.com/kb/en/compatibility-differences-incompatibilities-and-feature-differences-between/
https://mariadb.com/kb/en/incompatibilities-and-feature-differences-between-mariadb-10-5-and-mysql-8-/

The maintainers themselves are still focused on postgres and will be for the foreseeable future. Maybe one day we lean more into putting compartments in place that make different engines more clearly pluggable, but for a project like e.g. the catalog, that's a pretty sizeable surface to cut out cleanly.

**Comment by ypetrych** [comment]
Hi @freben @awanlin! It's a good idea to join your SIGs to discuss why we need this support and possible solutions. I'm a bit confused since the meetings are bi-weekly. Are you going to have it this or next week? Thanks!
