### ISSUE TITLE
🚀 Feature: [catalog-backend/processing] Add possibility to process multiple Entities at once

### ISSUE THREAD

**Issue by knowacki23** [backstage/backstage#26093]
### 🔖 Feature description

I'm cross posting feature opened in backstage/community-plugins - https://github.com/backstage/community-plugins/issues/568
Implementing this feature requires changes on `catalog-backend` side therefore I'm seeking for some help here (I hope that's okay).

We would like to be able to pass multiple entities to the `CatalogProcessingEngine` and instead of getting validation status for a single one we would like to get array of `entities names`, their `validation statuses` and `errors` if occurs so we can then process that data in our custom entity validator.

### 🎤 Context

While using entity-validation we have realized that it is impossible to validate two (or more) separate entities that depend on each other.
For example, if we want to validate new Group entity and a Component that should be owned by that Group entity validator will return error for the Component because it doesn't know about the group entity.
Sample validator input:
```
apiVersion: backstage.io/v1beta1
kind: Group
metadata:
  namespace: default
  annotations:
  name: fake-team
  title: FAKE-Team
  description: This is a fake team for test purposes
spec:
  type: Team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  title: Backstage
  namespace: delivery
  description: Backstage
spec:
  type: website
  lifecycle: production
  owner: fake-team
  system: fake-system
```
validator response:
Validates Group entity correctly.
for the Component entity returns following error:
```
Processor CustomEntityValidationProcessor threw an error while validating the entity component:fake-namespace/backstage; caused by ValidationError: spec.owner: "fake-team" failed endpoint validation as it is not a valid group in backstage; entityOwner: fake-team;
```

In the networking tab of developer web browser tools I see that validator sends two separate POST requests to the `https://<backstage-url>/api/catalog/validate-entity` endpoints. Each of the requests is for each of the components passed to Entity Validator.
![Screenshot from 2024-06-24 16-00-00](https://github.com/user-attachments/assets/56f28db6-2a1e-4711-a02f-281dc1414abd)

The first one is for the Group entity and it returns 200, the second one is for the Component and it returns 400 due to missing Group entity.

### ✌️ Possible Implementation

As mentioned in my [comment](https://github.com/backstage/community-plugins/issues/568#issuecomment-2252718485), I already did some changes to `catalog-backend` in order to be able to send multiple entities in a single API call.
What I did is: 
- added a new endpoint called `/validate-entities` so other plugins using `/validate-entity` endpoint wouldn't be affected by changes. - https://github.com/backstage/backstage/compare/master...knowacki23:backstage:catalog-backend_hadnle_multiple_entities_in_one_api_call_-_validate_entity#diff-4f83d47008b53e1e7842993e99beb5e73fb9e4a160f14278c29d4f4ea0d71df2
that endpoint expects to receive an API call in a following form:
```
{
    "location":"url:https://url-to-file/catalog-info.yaml",
    "entities": [
        {
            "entity":{
                "apiVersion":"backstage.io/v1alpha1",
                "kind":"Component",
                "metadata":{
                    "name":"test",
                    "title":"Test",
                    "namespace":"test-namespace",
                    "description":"Component description",
                    "links":[],
                    "tags":[],
                    "annotations":{}
                },
                "spec":{
                    "type":"service",
                    "lifecycle":"experimental",
                    "owner":"entity-owner",
                    "system":"entity-system"
                }
            }
        },
        {
            "entity":{
                "apiVersion":"backstage.io/v1alpha1",
                "kind":"Component",
                "metadata":{
                    "name":"test",
                    "title":"Test",
                    "namespace":"test-namespace",
                    "description":"Component description",
                    "links":[],
                    "tags":[],
                    "annotations":{}
                },
                "spec":{
                    "type":"service",
                    "lifecycle":"experimental",
                    "owner":"entity-owner",
                    "system":"entity-system"
                }
            }
        }
    ]
}
```

since all the entities sent to validator are coming from the same location we only need one `location` parameter per api call, in the request body we are also passing `entities` array build of `entity`.
Actual response is not yet created, but I'm thinking that it should be an array made of entity name, validation status and errors
- added `processMultiple` function to `CatalogProcessingOrchestrator` interface. - https://github.com/backstage/backstage/compare/master...knowacki23:backstage:catalog-backend_hadnle_multiple_entities_in_one_api_call_-_validate_entity#diff-2af122646a490b82b9ab87dc7e5cca1faaa4fb0b71424d98b5e38386ed46829d
- added `processMultiple` implementation to `DefaultCatalogProcessingOrchestrator` - https://github.com/backstage/backstage/compare/master...knowacki23:backstage:catalog-backend_hadnle_multiple_entities_in_one_api_call_-_validate_entity#diff-8faea90a46bc4a44050ef2e010454224967e1c8f1196e666a7a0a97ead134604
Basically this function is iterating through an array of entities which should be validated and calls `processSingleEntity` function for every entity.
 

And while I'm looking at that solution I'm thinking if it makes sense, or if its even a good solution.

I'm afraid that this might be a bad approach.

Does anyone has some idea or strong opinions regarding this matter?

The problem I want to solve is that we are using a custom validation rules which are checking if an entity under validation has an owner that actually exists in `Software Catalog` or the system that it is going to be a part of exists in the catalog as well.
And in a scenario when we want to validate two entities, let's say `Component` and `System` (both are not yet registered to catalog), and that `Component` is a part of that new `System`. In this case the validation for our `Component` will fail because validator is not aware of the `System` entity existence.

We would like to be able to pass an array of entities to the `validator processor` so our custom validator would receive all of the entities which are being validated so we can check if missing entities for some components are also being validated - if yes then the validation should be successful.
![image](https://github.com/user-attachments/assets/1ddb4b81-38b8-45b6-af92-a7c6a09fbc0d)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Hm this one is tricky. Gonna dump some background:

The catalog is intentionally built to be very scalable across many hosts, who collaboratively process huge amounts of entities off a queue. It does so very myopically by design; a processor is only ever permitted to see one single entity at a time, and we very strongly discourage processors calling out to the catalog itself or in other ways try to gather "context" around the current entity. The reason for this is that it's very easy to accidentally massively slow down the catalog, and to get into interesting complex data races or flickering values that never settle etc. Looking at one entity at a time and accepting the implications of that (more about that soon) makes it possible for us to be fast, and to iterate on things easily.

One outcome of this is that processors blindly emit relations to other entities, without ever validating that the target exists. Dangling relations are "soft" errors and permitted by design. One reason for this is that reality is so messy; even if relations are correct now, they may not be a few milliseconds later because externalities changed. A reorg will lead to things' ownerships being wrong for a moment while you update the metadata. We could never make dangling relations hard errors, since there's no such thing as atomic company wide updates to an entire model.

The validation endpoint wasn't there from the start. It was added at a later point than the rest of the engine, and abuses these properties to some extent. It runs processors on the entity _as if it's just been popped off the queue_, but of course it doesn't actually exist in the database.

Am I right in understanding that you have added a custom processor that actually makes it a hard error to refer to an entity that does not exist? While the motivations of that might be good, it does have unintended consequences such as completely halting processing and ingestion of that entity indefinitely until that one particular error is fixed. And when that error happens not through your own fault, but because some externality changed behind your back, that can be frustrating and risky and take a long time until it's discovered.

In our installation we leave these as soft errors, but make sure to surface the discrepancies to component owners so that they can organically fix things asap. We also have data pipelines keeping analysis going for metadata quality factors across the catalog.

It seems to me that an ideal analysis endpoint that still fulfils your need, is one that not just checks the `ok` flag of the processing result, but also returns details about the outcome including all of the generated relations. Then the a caller can at their own pace afterwards check whether those relation targets exist or not, and show warnings accordingly.

Could it be that the solution here is to expand on the response body of the existing `/validate-entity`, and adding existence checkers to the frontend bit? Then a 400 would mean "this is irrevocably broken and the engine would reject it", while a 200 would mean "the engine would accept this, but check the details if you think they look acceptable".

**Comment by knowacki23** [comment]
Hey @freben,
thank you for looking into that and nice explanation! :slightly_smiling_face: 

> Am I right in understanding that you have added a custom processor that actually makes it a hard error to refer to an entity that does not exist?

Yes, we have added a custom processor which is performing validation of following Entity fields:
Check if fields are not empty in the Entity definition:
   - `apiVersion`
   - `kind`
   - `metadata`
   - `metadata.name`
   - `spec.system` - except for Domain, System and Template
So we require our Entities to have above fields filled out.

Besides that validation we are also checking the actual values provided in Entity definition by performing API call to Software Catalog checking if provided data exists in the Catalog:
- `spec.system`- check if provided system is an actual System Entity registered to Software Catalog 
- `spec.owner` - check if provided owner is an existing Owner Entity in the Software Catalog.

If any of those validation fails then we are throwing custom `ValidationError`which we have defined, the `ValidationError` extends [CustomErrorBase](https://github.com/backstage/backstage/blob/master/packages/errors/src/errors/CustomErrorBase.ts) class from Backstage `errors` package.

Have you ever came across similar use-case to ours?
We are wondering how to tackle this problem...

>In our installation we leave these as soft errors, but make sure to surface the discrepancies to component owners so that they can organically fix things asap. We also have data pipelines keeping analysis going for metadata quality factors across the catalog.

So you are allowing Entities to be registered to Software Catalog despite the validation errors?
Do you have an example of a soft error?

We think that we should change the behavior of validator to allow registering Entities and display a warning on Entity page that the validation failed and Entity definition needs to be fixed.

Thank you for your help!

**Comment by freben** [comment]
> We think that we should change the behavior of validator to allow registering Entities and display a warning on Entity page that the validation failed and Entity definition needs to be fixed.

Exactly. That's what we do! Little panels that contain a few validation rules on the frontend side, nudging people to change. Putting hard exceptions in the processing loop causes a very rough experience for end users, as noted above.

Maybe you can even have some external automation too later on, that every day checks the "metadata quality" correctness in the entire catalog as a whole and pings the people that have entities with bad metadata.

**Comment by samuelstadler** [comment]
Hey @freben, how exactly do you process this validation rules on the frontend side. Is it done every time the user clicks on an entity or is it done during processing and stored e.g.: in the entity `status` field?

I am asking because we would be interested in the later one where we can add the information to the status of the entity. However we are facing the issue that when we throw or emit an error during processing a **new entity**, which is not in the catalog yet, then this entity will not end up in the catalog - hence we cannot show the soft errors to user. Our idea is now to not throw/emit an error but add the information to the `status.items` during processing, but the [documentation](https://backstage.io/docs/features/software-catalog/extending-the-model/#adding-a-new-status-item-type) states: 

> The mechanics for how to emit custom statuses is not in place yet, so if this is of interest to you, you might consider contacting the maintainers on Discord or my making a GitHub issue describing your use case. [This issue](https://github.com/backstage/backstage/issues/2292) also contains more context.

Is there currently any solution to modify this `status.items` either during processing or afterwards? 🙂

**Comment by freben** [comment]
No there's currently no mechanism for emitting "informative" statuses that stay on the entity, sadly. Only hard errors that also break processing. It's been considered but never ended up being a feature so far. We do that checking in the frontend instead.
