### ISSUE TITLE
🚀 Feature: i18n `createTranslationMessages` to support deep objects

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#26122]
### 🔖 Feature description

`createTranslationMessages` should be able to use deep objects for translations. This makes the updating and formatting much easier.  

```ts
const fi = createTranslationMessages({
  ref: qetaTranslationRef,
  full: false,
  messages: {
    answerList: {
      errorLoading: 'Could not load answers',
    },
});
```

Currently it requires to use the flattened keys which makes it a bit hard, should I open an issue for this?

```ts
const fi = createTranslationMessages({
  ref: qetaTranslationRef,
  full: false,
  messages: {
    'answerList.errorLoading': 'Could not load answers',
  }
});
```

### 🎤 Context

Figuring out the flattened key for translations is a pain. Copying those from the original messages object makes translations much easier to do.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
The issue here could be the type hints. When declaring the messages in the translation ref it's kinda easy to flatten them out in the types afterwards. Here we already have a set structure in the types and we'd potentially want to allow both the split and flat form. One approach could be to only support the nested form in `createTranslationMessages`, but not entirely sure that's the best way.

**Comment by drodil** [comment]
Another option was to expose the `flattenMessages` functionality so that it could be used to flatten the messages object, though not sure type hints allow this either.
