### ISSUE TITLE
🐛 Bug Report: catalog backend plugin for MsGraph does not ingest users without email

### ISSUE THREAD

**Issue by JessicaJHee** [backstage/backstage#26137]
### 📜 Description

The default user transformer provided by the [MsGraph plugin](https://github.com/backstage/backstage/tree/918d273bbb843bd09bb6c80d22d87c257a7e5343/plugins/catalog-backend-module-msgraph#readme) does not ingest users who do not have an email included in their profile, preventing those users from signing in. This is an issue because email is not a mandatory field when creating an user and therefore not all users will have this field defined.

### 👍 Expected behavior

Consider ingesting users without email into the catalog by using `userPrincipalName` as the identifier, instead of email by default by changing the default user transformer. Currently, the user transformer [returns the user as undefined](https://github.com/backstage/backstage/blob/918d273bbb843bd09bb6c80d22d87c257a7e5343/plugins/catalog-backend-module-msgraph/src/microsoftGraph/defaultTransformers.ts#L125-L127) if the mail field does not exist.
* The `userPrincipalName` parameter is must exist for each user and is unique

### 👎 Actual Behavior with Screenshots

Users without `user.mail` field defined do not get ingested into the catalog.

### 👟 Reproduction steps

1. Have an user in the Microsoft Org that does not have an email defined
2. Check in the catalog after ingestion that the user has not been ingested as expected

### 📃 Provide the context for the Bug.

Note: A [PR](https://github.com/backstage/community-plugins/pull/862) was created in the community-plugins repo to add a custom transformer but after discussions, we determined it would be best to have this added to the main repo as it may benefit all users.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
This makes a lot of sense to me, if there's no email then fall back to the `userPrincipalName`. We would also need to consider how the resolver works in the Azure auth provider as it looks for email to match on: 

https://github.com/backstage/backstage/blob/50e74610355b300f68316817f5d90c0d69bbd307/plugins/auth-backend-module-microsoft-provider/src/resolvers.ts#L33-L53

@afscrome @pjungermann @drodil, as users of this provider any thoughts on this?

**Comment by drodil** [comment]
Sounds like a valid idea though we haven't encountered such situation yet.

**Comment by JessicaJHee** [comment]
How do we feel about using `userPrincipalName` as the main identifier instead of using it as a fallback with the email so that we don't need to handle 2 cases with the authentication? Is there any reason why email is used in this case?

**Comment by awanlin** [comment]
Hi @JessicaJHee, as email is the current pattern and it seems to be working for many Adopters who use this entity provider it doesn't make sense to introduce a potential breaking change. The email address is often in the profile for the auth provider and is common pattern there to use like this. Having an email address does help power other features in Backstage more generally speaking. 

Anecdotally speaking, based on my experience helping people on Discord, I haven't actually run into this issue till you submitted the PR in the Community Plugins repo. Based on that I'm hesitant to change what is working for many already but do feel like this should be supported as the fallback.

**Comment by afscrome** [comment]
I'll +1 not changing the default behavior to use a UPN over email address - it's a breaking change that'll definitely break my current company's install.  I'm also pretty sure it would have impact at my previous company too.

Whilst a UPN may contain an `@` symbol and look like an email address, it may well not be an address you can contact that user on.  For example at my current company for example, my UPN is for an internal domain (e.g. `name@corp.COMPANY.com`), whereas my email address is `FIRST.LAST@COMPANY.com`.  I will not receive any emails sent to my UPN.  I've also often seen UPNs using the Microsoft default domain (i.e. `@TENANT.onmicrosoft.com`) rather than the company's primary domain.

I don't think it's a good idea to fudge something into a user's `spec.mail` which you can't send an email address to.  And we definitely should not use UPN if a specific email address has been provided. 

Since `spec.email` is optional on the `User` entity, I do think it would be reasonable to modify the `defaultUserTransformer` to not reject users without email addresses completely.  However rather than fall back to UPN, I think we should just leave `spec.email` (as well as the email annotation) blank.  
https://github.com/backstage/backstage/blob/50e74610355b300f68316817f5d90c0d69bbd307/plugins/catalog-backend-module-msgraph/src/microsoftGraph/defaultTransformers.ts#L125 

One knock on effect form this change is that the default email based signInResolver won't work for such users.  Using a UPN wouldn't helper here either as the sign in resolver works specifically with the `mail` provided by Microsoft which is specifically for the user's `mail` field, not their UPN.  This can be solved by creating a user id based resolver - mapping `info.result.fullProfile.id` to the `graph.microsoft.com/user-id` annotation.

**Comment by JessicaJHee** [comment]
@awanlin @afscrome Thank you both for the detailed feedback! I'll go ahead and open up a PR to leave the mail field blank when it does not exist but still allow the user to be added to the catalog. I won't use the `userPrincipalName` as suggested.

**Comment by twanbeeren** [comment]
> How do we feel about using `userPrincipalName` as the main identifier instead of using it as a fallback with the email so that we don't need to handle 2 cases with the authentication? Is there any reason why email is used in this case?

I've been implementing Backstage for a customer that has exactly the same use case:

I also had to build my own transformer to make sure that the userPrincipalName is used as a mail address when the mail address is not provided. Because without a mail the user won't be added to the catalog.

There were some accounts that had no mail, because they didn't have a "mailbox" attached. So they told me to use userPrincipalName instead.

As an extra, I also needed users without any relations to not be added to the catalog. 

```typescript
export async function myUserTransformer(
  graphUser: MicrosoftGraph.User,
  userPhoto?: string,
): Promise<UserEntity | undefined> {
  const backstageUser = await defaultUserTransformer(graphUser, userPhoto);

  if (!backstageUser?.spec.profile) {
    logger.info(`This user ${backstageUser?.spec.profile?.displayName} has no profile so will be undefined`);
    return undefined;
  }
  else if(backstageUser?.spec.profile?.email || graphUser.userPrincipalName){
    if (backstageUser?.spec.profile?.email == null && graphUser.userPrincipalName) {
      backstageUser.spec.profile = backstageUser.spec.profile || {};
      backstageUser.spec.profile.email = graphUser.userPrincipalName;
      logger.info(`The user ${backstageUser?.spec.profile?.displayName} has its mail set manually`);
      return backstageUser;
    }
    else {
      return backstageUser;
    }
  }
  return backstageUser;
}
```
