### ISSUE TITLE
🚀 Feature: Improvement of OpenSSF Scorecard Score

### ISSUE THREAD

**Issue by harshitasao** [backstage/backstage#26147]
### 🔖 Feature description

Hi, I'm Harshita. I’m working with [CNCF and the Google Open Source Security Team for the GSoC 2024 term](https://github.com/cncf/mentoring/issues/1196). We are collaborating to enhance security practices across various CNCF projects. The goal is to improve security for all CNCF projects by both using OpenSSF Scorecards and implementing its security improvements.

### 🎤 Context

As this project already has scorecard action, I'm here to increase the final score by going over each check. I've listed all of the checks where work needs to be done, in order of its criticality. I plan to submit each PR for each fix. Please let me know what you think and for which ones a PR is welcome that I will submit it ASAP.

**Current Score:** 6.3

**Scorecard report:** https://scorecard.dev/viewer/?uri=github.com/backstage/backstage

Here's a few checks we can work on to improve the project's security posture:

- [ ] [Dangerous-Workflow](https://github.com/ossf/scorecard/blob/main/docs/checks.md#dangerous-workflow): Score = 0
     - untrusted code checkout 'refs/pull/${{ github.event.pull_request.number }}/merge': .github/workflows/automate_changeset_feedback.yml:30
    - untrusted code checkout '${{ github.event.pull_request.merge_commit_sha }}': .github/workflows/automate_merge_message.yml:31

- [X] [Token-Permissions](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions): Score = 0
    - The issue here is that many workflows doesn’t have a top-level read-only permissions block like present in the other workflows. Scorecard is quite severe in this check: a single workflow without top-level permissions gets a 0/10 for the check.
    - PR: https://github.com/backstage/backstage/pull/26155

- [ ] [Vulnerabilities](https://github.com/ossf/scorecard/blob/main/docs/checks.md#vulnerabilities): Score = 0
     - After running the [osv scanner](https://google.github.io/osv-scanner/) locally, a significant amount of vulnerabilities were found that need to be fixed.
     - May need to add an `osv-scanner.toml` to mark some of these as not impacting/ignored.
     - Open vulnerabilities are easily exploited by attackers and should be fixed as soon as possible.

- [ ] [Fuzzing](https://github.com/ossf/scorecard/blob/main/docs/checks.md#fuzzing): Score = 0
    - Integrating the project with OSS-Fuzz by following the instructions [here](https://google.github.io/oss-fuzz/). The most difficult one on the list, maintainers help, is highly appreciated. For example, helping in identifying the components where fuzz testing will be added.

- [ ] [Pinned-Dependencies](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies): Score = 8
    - pip commands and container images in dockerfile are not pinned by hash, which results in a low score. But pinning these would introduce the risk of running outdated versions/images.
  
 

/cc @joycebrum @diogoteles08 @pnacht @nate-double-u

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Thank you! 👍 definitely some opportunities here. Diving into each of them a bit

## Dangerous-Workflow & Token-Permissions

Happy for any help with cleaning these up 👍. It might be hard to fix the dangerous workflow warning while maintaining the functionality, but worth a shot.

## Vulnerabilities

Didn't dive into all of these but it seems like at least a majority of these are ones that we have ignored as they are not applicable, see for example 
https://github.com/backstage/backstage/blob/master/packages/cli/.snyk

Best case would be if we did not need to maintain duplicate ignores as Snyk is our primary dependency scanning method.

## Fuzzing

I've chatted with the fuzzing guys at KubeCon a couple of times, and at least since a year ago or so they do have at least minimal support for TypeScript. I'd say the need here is to start a ball rolling and then likely green light an effort from the CNCF side to add fuzzing to Backstage.

## Pinned-Dependencies

A lot and potentially all of these are dependencies that we don't want to pin as they're part of documentation. We do recommend that users of the Dockerfiles pin the deps though, see for example https://github.com/backstage/backstage/tree/master/contrib/docker/minimal-hardened-image#pinning-digest
