### ISSUE TITLE
💬 RFC: Informing users about external links on the navigation 

### ISSUE THREAD

**Issue by ShiranHi** [backstage/backstage#26405]
### 🔖 Need

It is possible to add an external link to the main navigation, but there's no clear indication for users whether this item is a standard internal link or one that will open an external site. 
This ambiguity may surprise users unexpectedly when the navigation item unexpectedly opens a different website.

### 🎉 Proposal

If an external link is added to the navigation:

1. Include an icon next to the navigation item
2. Enable the option to open it in a new tab

![Navigation](https://github.com/user-attachments/assets/df80553d-2ce1-41e3-b226-d7d263a49b03)

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by benjdlambert** [comment]
Hey :wave:

I think that there's already some existing logic that we can maybe hook into the back of in the existing [`Link` component](https://github.com/backstage/backstage/blob/2ff3e6e8a6ffe744f8b299bd5a684288e2ae95cc/packages/core-components/src/components/Link/Link.tsx#L187)

I was wondering if we could also optionally render the `external` icon here too and do it inline?

Might be a nice solution to apply it Backstage wide rather than just in the sidebar. Would be good to call out that these things are external in things like Techdocs etc too.
