### ISSUE TITLE
🚀 Feature: Generic CacheService

### ISSUE THREAD

**Issue by raphtalia** [backstage/backstage#26441]
### 🔖 Feature description

Support `CacheService.withOptions<T>({})` as a way to get a cache supporting non-JSON types.

### 🎤 Context

I'd like to use the built-in cache service for caching Okta users which have properties with `Date` types.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
You'd have to transform those back and forth to a json serializable form yourself, either way.

The cache service is generic. There can be any number of backing storages for it, including ones that we don't know about (private extensions that adopters make, or that SaaS vendors make, etc). It's part of the contract for the cache service that the lowest common denominator for stored data is that it can be json stringified. Without that limitation, it would be impossible or at least hard to make for example a memcached store because it has no intrinsic way of handling complex data types.

Did you mean that you'd want to build model transform logic into the cache service itself? Like making it a `CacheService<TValue = JsonValue>` and having `.withOptions({ valueTransformer: ValueSerde<TValueRaw> }): CacheService<TValueRaw>`? If so, that feels like it would have little value compared to just calling a serialize/deserialize function outside of the cache service. I'd like for it not to be of a generic type; none of the services are.
