### ISSUE TITLE
🐛 Bug Report: TechDocs backstage-auth cookie set failure

### ISSUE THREAD

**Issue by jhl0214** [backstage/backstage#26646]
### 📜 Description

"This attempt to set a cookie via set-cookie header was blocked because its domain attribute was invalid with regards to the current host url." So my company is using 2 different url for ui and backend. For ui, its something like xxx.company.com and for backend, it's xxx-backend.company.com. When I navigate to any documentation page, there is an api call to /api/techdocs/.backstage/auth/v1/cookie and the response header includes set-cookie with backstage-auth and domain. The domain value is xxx-backend.company.com. But since it does not match the domain of the ui, it is failing to set the cookie with above error and because of that, api call to /stylesheets/main.min.css is getting 401. How should I fix this issue?

### 👍 Expected behavior

backstage-auth cookie to be set

### 👎 Actual Behavior with Screenshots

Fails to set backstage-auth cookie with the above error

### 👟 Reproduction steps

Navigate to any page with documentations.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
What domain is the `/stylesheets/main.min.css` and `/api/techdocs/.backstage/auth/v1/cookie` requests towards? The host for the cookie being `xxx-backend.company.com` is correct, since the cookie is needed for requests to the backend rather than frontend. The TechDocs resource requests should also be towards `xxx-backend.company.com` too, as should the request to `/api/techdocs/.backstage/auth/v1/cookie`. It almost seems like those requests are towards `xxx.company.com`, but in that case I wouldn't expect them to work at all?

**Comment by jhl0214** [comment]
All the plugins are making api calls to xxx.company.com url, but they get routed to xxx-backend.company.com eventually, so they are working

**Comment by Rugvip** [comment]
@jhl0214 ah, well in that case the `xxx-backend.company.com` is just an internal detail, you should configure your `backend.baseUrl` to use `xxx.company.com` in both the frontend and backend
