### ISSUE TITLE
🐛 Bug Report: SearchType.Accordion only support collapsable behaviour

### ISSUE THREAD

**Issue by sjvaiz** [backstage/backstage#26818]
### 📜 Description

SearchType.Accordion collapses as you click on a "Result Type". However, it should be possible to control this behaviour such as when user clicks on a search result type, it should stay expanded.

### 👍 Expected behavior

The SearchType.Accordion should be able to stay expanded as the user clicks on a certain result type.

### 👎 Actual Behavior with Screenshots

Check Backstage demo instance's Search Page.

### 👟 Reproduction steps

The demo Backstage site has this behaviour on the search page: https://demo.backstage.io/search?query=

### 📃 Provide the context for the Bug.

The default behaviour is set to toggle:
https://github.com/backstage/backstage/blob/5ec8f4d34572a1e7761138726fea3c1ce59a6136/plugins/search/src/components/SearchType/SearchType.Accordion.tsx#L94

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by freben** [comment]
It's probably complex to control that from "the outside" - it'd lead to some pretty deep prop drilling, most likely. Maybe it could be considered to change the default behavior instead, if it's deemed that that turns out better for users. @backstage/search-maintainers what do you think?

As a side note, in MUI5 or 6 later down the line, there might be an opportunity to tweak this using the theming system with `defaultProps`, but that's not a short term solution.
