### ISSUE TITLE
🚀 Feature: ability to set memberOf when Sign-In without Users in the Catalog 

### ISSUE THREAD

**Issue by leoandrea7** [backstage/backstage#26848]
### 🔖 Feature description

When you authenticate a user from a custom oidc provider, but don't want to have the users in the Backstage catalog, you can create a signInResolver as per the [documentation](https://backstage.io/docs/auth/identity-resolver#sign-in-without-users-in-the-catalog). Here you can set references to entities that the user is an owner of, but you can't set references to groups that you want the user to be a member of.

### 🎤 Context

It will be possible to understand if the user is a member of a group, even if UserEntity is not present in the catalog and, for example, to perform checks on permissions.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
I'll also add that it's an entrenched thing in Backstage, that what gets communicated across boundaries is the user's entity ref _only_, and then if the receiving end wants to know more about the user they turn around and ask the catalog for the full entity. There's no way of really getting around that fact at this point, which is why we very strongly discourage running without org data in the catalog and don't officially support it. The presented need of just group membership that you talk of, is just one of many possible aspects of data that you may encounter wanting to know about the user. It's just the tip of the iceberg, I'd think.
