### ISSUE TITLE
[Plugin] Tech Insights

### ISSUE THREAD

**Issue by masterthefly** [backstage/backstage#2723]
Cloned latest code but dont see Tech Insights plugin ....how to get this one?

**Comment by Fox32** [comment]
The Tech Insights plugin isn't Open Source. I'm not sure if there are plans to change that as it might be quite specific for the internal usage at Spotify.

**Comment by masterthefly** [comment]
oh...thanks for the update. There are videos which are very interesting on TechInsights and I am sure most of the other companies will benefit if this is opensourced. Please consider. Thanks again.

**Comment by stefanalund** [comment]
I've added the [plugin] label so that we can treat this as a plugin suggestion rather than a bug.

**Comment by djsly** [comment]
any skeleton plugin we can based ourselves on to build a plugin similar to Tech Insights ? 

We would like to get a report of SonarQ or XRays reports across the Org/LOB instead of only at the component level.

**Comment by andrewthauer** [comment]
I agree this would be super useful.

We've been thinking about building a metrics/scorecard system that allows arbitrary measures to be associated with entities. It would likely be based on a star schema data model which would allow aggregations across relations.

I can see the presentation and data model being something that could be generalized. However, the process of populating the model for specific measures is likely going to be org specific in many cases. It's possible something like this could use a similar approach to how the cost insights plugin abstracts the underlying data collection.

**Comment by ppetriuk** [comment]
+1 for a skeleton plugin with presentation and data model. "Tech Insights"-like tracking for tech adoption is one of the top use cases for us.

**Comment by samwiskow** [comment]
Echo that sentiment - Tech insights in terms of light dashboarding and creating visibility (someone has to convince management), would be a really good way to get this in the door and then sneak in all the extra tooling for our Dev teams

**Comment by miladr** [comment]
I believe this plugin is a game-changer. We have to build a similar plugin so I guess it's better that we contribute instead of build from scratch.

**Comment by freben** [comment]
To get a little discussion going - what kinds of data would we want to drive these cards? As in, what's the information model.

Obviously one may be interested in a percentage number, so that's one candidate.

Could there be booleans as well? - "have you configured a valid escalation policy for your team"

General numbers? - You have this many pending support tickets.

Could there be action-list-type things? A wheel with some green and some orange slices, kinda like GitHub builds? - Or would that rather be a percentage too?

Basic area/line graphs of how things change over time is definitely of interest.

**Comment by miladr** [comment]
I would say we are mostly interested to see DevOps KPI's there. Cycle time, MTTR, MTTD, Deployment Freq, etc.

**Comment by samwiskow** [comment]
I think the [DORA KPIs](https://storage.googleapis.com/gweb-cloudblog-publish/images/Calculating_the_metrics.max-2800x2800.jpg) mentioned in the [Four keys project](https://cloud.google.com/blog/products/devops-sre/using-the-four-keys-to-measure-your-devops-performance) is a good place to start. It would probably be necessary to show trend + change over time as well as the current metric. What metrics have others found useful?

Obviously, there is some complexity in doing this versus a simple plugin driven by an API request, especially if you want to look at these metrics on an aggregate level versus service by service.

**Comment by adamdmharvey** [comment]
We are also striving for the DORA-style metrics also, but the whole action/completion type tracking at scale is just as important(i.e., just like the examples Spotify has shared publicly via Scio upgrades) are key. Most recent one I can think of for example is the last Node.js LTS retirement and AWS Lambda retiring support for one of the engines. We would have wanted not for a team to go in manually to say "yes I've upgraded" to mark the action complete, but rather a dynamic SCAN to ensure it happens. (because our teams won't go to another system, even if it's not a spreadsheet, to update it)

So from a data model perspective, I wonder if there needs to be a `@backstage/tech-insights-common` and a `@backstage/tech-insights` front end, but then maybe some sort of extensible company specific `@internal/tech-insights-logic` which let's me say do things like define the actions:

```yaml
tech-insights:
  name: Scio Migration
    measurement: scio-lookup
    target: >4           # supports simple number checking
  name: AWS Lambda Node.js Retirement
    measurement: aws-lambda-node
    target: ~10        # also supports semver style notation?
  name: DORA MTBF
    measurement: dora-mtbf
    target: <5 days
```

And then I can define maybe a function called "dora-mtbf" which can go out to my database where I store my metrics to return a number for a given entity. And like cost-insights plugin, I customize my client to FIND this value.  And another function called `scio-lookup` and another function called `aws-lambda-node` which just uses AWS CLI to scan for a value and download say all lambda functions and collects only the engine.

Would be nice to also overlay a caching engine to only refresh the tech-insights cache consistently on a regular interval (or per function maybe, say a scan of a cloud provider is slow but a scan of a database is fast).  And then elevate the most recent scan to the UI.

**Comment by jessebye** [comment]
Love Adam's idea of having the company-specific logic. We have a bunch of things we want to score our services on:
- SonarCloud quality
- Things like "does the Dockerfile comply with all best-practices?" and "does the repo include a `docs` folder?"
- GitHub open vulnerabilities
- % of CI builds passing
- CI build time
- uptime
etc.

We'd combine scores on all those to give services an overall score. Then we'd like to display the overall score and each individual score in a widget, hopefully with a historic graph showing how the score has improved over time.

**Comment by andrewthauer** [comment]
@adamdmharvey - Your line of thinking is very much what we've thought about for this. Every org is going to have a different set of metrics they care about. Sure there will be common ones, but it will be too hard to try and cover all the specific ones. Also, the data capture is likely going to be much different across orgs as well as the metrics themselves.

I could envision there also being a `@internal/tech-insights-backend` that can ingest/store/serve pre-transformed metrics that have been processed through a data pipeline or simple fetch/ingest ETL process. Along with this probably an API that other Backstage plugins or integrators can use to turn raw data into metric ready data.

To @freben point, figuring out the types of metrics to track is one of the most important this to do. Off the top of my head I can see scalar values (`boolean`, `integer`, `decimal`) would cover many cases. But I'd also want to be able to associate those values to various dimensions like time, backstage, entity, owner, etc. That's why I thought a star schema like model could be used to abstract away ingestion / processing from front-end display. At that point @adamdmharvey idea around metric definitions could be extended to include dimensions.

I'm thinking an RFC proposal is probably in order. Building out something like this that is generalized and useful enough for many different organizations to integrate with is not going to be trivial.

**Comment by freben** [comment]
Combining to an overall score can also be a challenge to get right. To be able to aggregate, all of the different insights with their varying models and targets need to be translated to a scalar of sorts. Maybe every insight needs to be two-valued: (1) the actual value, and (2) the score that it corresponds to, also computed in a company specific way. Like, "you are 70% migrated off of java8, which we give 3.5 stars". For another more critical metric, you may harshly give zero stars immediately if they have a single P1 security issue that's more than 5 days old for example.

**Comment by tragiclifestories** [comment]
Adding a comment/sort-of-upvote for this. Internally we're about to build something that will allow us to track which services have gone through a load-testing exercise, but exactly what the test looks like is going to vary depending on the service so really it will be a matter of 'manually' adding data in. 

So really it's going to be defining something similar to the rjsf form schemas in the scaffolder which will walk a team through defining/executing a test plan and let them record results. 

But hypothetically I could imagine combining those very custom test scenarios with other automated checks to produce an overall scorecard-type thing for each component.

**Comment by tragiclifestories** [comment]
I notice that this is one of the features Atlassian are leading with on [their entry into the space](https://www.atlassian.com/software/compass) also.

**Comment by aravindparappil46** [comment]
Adding my upvote to this! Would be an awesome plugin to have!

**Comment by anishdhar** [comment]
hey everyone - we actually built this as a plugin based on our [Scorecards](https://www.cortex.io/products/scorecard) product!

you can learn more [here](https://github.com/cortexapps/backstage-plugin) (https://github.com/cortexapps/backstage-plugin). Our plugin lets you grade the quality of your backstage services, and we can even message engineers about the quality of their services + give you team level analytics. You can track production readiness, security audits, and more!

Feel free to reach out in case you're interested in a demo :)

**Comment by dtuite** [comment]
@joechrisellis and the team at Monzo have built parts of this into their internal Backstage deployment. Joe wrote about their system in detail here: https://monzo.com/blog/2021/09/15/how-we-measure-software-excellence

**Comment by pjungermann** [comment]
@Rugvip et al
I would suggest closing this issue as there is a tech-insights plugin now as well as a few external commercial offers. Additional requests for the tech-insights plugin itself should be more specific feature request issues for it.

**Comment by freben** [comment]
Agreed, thanks
