### ISSUE TITLE
🚀 Feature: provide ability to configure session refresh time

### ISSUE THREAD

**Issue by JessicaJHee** [backstage/backstage#27281]
### 🔖 Feature description

Provide an additional auth config like:
```
auth:
   sessionRefreshTime: { minutes: <user_defined_value> }
```
To customize the value [here](https://github.com/backstage/backstage/blob/6cbe4f999c9c8e9e090d3be5a7c3af71d59e507d/packages/core-app-api/src/apis/implementations/auth/oauth2/OAuth2.ts#L151) that determines or not whether or not a session should be refreshed/ new refresh token should be requested.

### 🎤 Context

For IAM solutions like Keycloak, the default access token lifespan is set to 5 minutes. This means that by default, every single API call will send a request to `http://<backstage-url>/api/auth/oidc/refresh?optional&scope=&env=development` to get a new `oidc-refresh-token`. This slows down the application and sends a lot of unnecessary requests.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Ah, that's certainly unfortunate. That timing was fairly arbitrarily chose when all sessions we where using expired in 1h (and surely no token would only last 5 minutes, right?). I'd be happy to bring that grace period down a bit. It exists be on the safe side when making requests with the provided token that might take a while to complete, but I think we could safely bring it down to at least 3 minutes rather than 5. What value would you want to use if it was configurable?

**Comment by JessicaJHee** [comment]
@Rugvip Sorry about the late response! Bringing down the grace period statically works as well. It's pretty subjective what value is suitable but I would agree with 3 minutes, as long as the refresh request is not being sent per API call it solves the problem :) 

If that sounds good I can make a quick PR to update the grace period?

**Comment by Rugvip** [comment]
@JessicaJHee yep sounds good 👍
