### ISSUE TITLE
🐛 Bug Report: Relationships not properly updated in Entities generated from custom provider/processor

### ISSUE THREAD

**Issue by jslott2sigma** [backstage/backstage#27325]
### 📜 Description

When modifying relationships via a `delta` mutation, the final entity has incorrect relationships. In this specific test case (which mimics our real use case), we have the following:

1. A provider that emits a "raw" (in this case, `rawComponent`) entity initially via a `full` mutation, but over the course of the day via `delta` mutations.
2. A processor converts that raw entity into a final component entity, forming custom relationships.
3. The relationships are not properly updated in the final entity (in the test case below, only one side of the relationship is updated).

### 👍 Expected behavior

Relationships should be properly updated as a result of `delta` mutations, for both sides of the relationship.

### 👎 Actual Behavior with Screenshots

In the test code given below, a "test" provider and processor emit entities. It simulates both a `full` mutation and a `delta` mutation as follows:

1. During a simulated `full` mutation, emits a single group entity (as owner) and three components: `a`, `b`, and `c`. The provider emits `rawComponent` entities that are converted into `component` entities by the processor. As a result of the simulated `full` mutation, `a` has a `testDependsOn` and `testDependencyOf` relationship with `b`.

2. During a simulated `delta` mutation, the providers emits new `rawComponent` entities that cause the processor to switch the relationship from between `a` and `b` to between `a` and `c`. As a result only one side of the relationship is updated, `a` has a `testDependsOn` with `b` still.

Interestingly enough, the problem persists even if in Step 2 a `full` mutation is done to switch the relationships. Also interestingly, if the processor-emitted component has `spec.dependsOn` (to generate the built-in dependsOn relationship), the bug no longer happens!

### 👟 Reproduction steps

I've created a `test` provider in a fork of the Backstage repo, you can see the code here: https://github.com/backstage/backstage/compare/master...jslott2sigma:backstage:relationships-not-being-updated

The test catalog module exposes two endpoints: `/full` to populate the entities initially and `delta` to switch the relationship from between `a` and `b` to between `a` and `c`.

Simply run `yarn dev` to launch the sample app. I am happy to investigate this further if pointed in the right direction and submit a fix.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by aramissennyeydd** [comment]
👋 I tested with this locally, there's an issue in your `postProcessEntity` where you create new `kind=Component` entities, when the core entities you're working with are `rawComponent`s. The database state reflects that as well, 
- this is the set of entities that will get restitched (a new entry in final_entities), https://github.com/backstage/backstage/blob/c7855cd62b3c76ed6d5afce33147ec900c1f79ed/plugins/catalog-backend/src/processing/DefaultCatalogProcessingEngine.ts#L311-L323
- these are the relations that are getting deleted, https://github.com/backstage/backstage/blob/c7855cd62b3c76ed6d5afce33147ec900c1f79ed/plugins/catalog-backend/src/database/DefaultProcessingDatabase.ts#L120-L133

I think what's happening in your demo is that you're creating `rawComponent:a`, `rawComponent:b`, `rawComponent:c`, but making new `component:a`/b/c for each relation and the entity processor is trying to reconcile the differences on the `component`s instead of the `rawComponents`. If you adjust your relations in `TestEntityProcessor` to output `kind`=`rawComponent`, it worked for me, otherwise, you may want to add an additional layer for mapping from rawComponent to component so that both entities get updated.

**Comment by camilaibs** [comment]
Hi @aramissennyeydd, would you like to give it a try and open a pull request to contribute to us 🙂 ?

**Comment by aramissennyeydd** [comment]
@jslott2sigma As the reporter, do you want to pick this up? AFAICT it's a pretty straightforward fix and I linked the code that's likely causing the issue. I can pick it up if you don't want to 😁.

**Comment by jslott2sigma** [comment]
@aramissennyeydd Yup, I can give it a try! Thanks for all the help so far.

**Comment by camilaibs** [comment]
> @aramissennyeydd Yup, I can give it a try! Thanks for all the help so far.

Thanks @jslott2sigma, I assigned the issue to you 🙌🏻

**Comment by jslott2sigma** [comment]
@camilaibs PR submitted! #27417 . Thanks @aramissennyeydd for the help, most appreciated!
