### ISSUE TITLE
Make GaugeProgress sizing more flexible

### ISSUE THREAD

**Issue by iain-b** [backstage/backstage#2738]
## 🗒 General

Hi, I am working on #2709  and there was some discussion around how best to display lighthouse scores - a set of 6 percentages, basically. Lighthouse itself presents these with a set of small "rings" like so:
![image](https://user-images.githubusercontent.com/1415599/95016287-07044900-064a-11eb-82fe-ce02d7d6a1c8.png)

I'd like to be able to do something similar with backstage / material UI components. I looked at the GaugeProgress element however it seems to be fixed size and too large for my use case. It'd be nice if there were variants of GaugeProgress of different sizes or if it were sizeable dynamically.

I'm happy to implement this myself but I'd like some UX/design input first to make sure I'm doing something sensible which fits in.

## 💻 Usage

For context, I'm building a Card which would be placed on the overview of websites in the catalog. I currently have something like this:
![image](https://user-images.githubusercontent.com/1415599/95016553-92caa500-064b-11eb-803a-9ea0b84530ef.png)

But I'd like to do something more along the lines of the screenshot at the top with just a set of small GaugeProgress elements (it would be a different card without the table, this was just convenient to show what a smaller GaugeProgress might look like)
![image](https://user-images.githubusercontent.com/1415599/95016532-762e6d00-064b-11eb-94eb-cf789a39780e.png)

**Comment by DanielArthurUK** [comment]
Hi @iain-b 

The material-ui component [`<CircularProgress />`](https://material-ui.com/api/circular-progress/) uses a `size` prop in order to achieve this. From the source:

```javascript
  /**
   * The size of the circle.
   * If using a number, the pixel unit is assumed.
   * If using a string, you need to provide the CSS unit, e.g '3rem'.
   * @default 40
   */
  size: PropTypes.oneOfType([PropTypes.number, PropTypes.string])
```

It would be good if we could implement something like that, although I suspect there may be some issues with the underlying `<Circle />` component from the [rc-progress](https://github.com/Hipo/rc-progress) package. It looks as though there is no way to specify the size of the circle, rather the radius is [dynamically calculated from the `strokeWidth` prop](https://github.com/Hipo/rc-progress/blob/master/src/Progress.js#L10):

```javascript
const Circle = React.createClass({
  render() {
    const props = assign({}, this.props);
    const strokeWidth = props.strokeWidth;
    const radius = (50 - strokeWidth / 2);
```
