### ISSUE TITLE
🐛 Bug Report: Yarn 4 used in default create app but main project stuck on yarn 3

### ISSUE THREAD

**Issue by deejay1** [backstage/backstage#27443]
### 📜 Description

The used yarn version for new apps is 4, but the backstage project itself uses version 3. Also versions are not in sync between  https://github.com/backstage/actions/tree/main/yarn-install and https://github.com/backstage/backstage/blob/master/.yarnrc.yml

### 👍 Expected behavior

Versions in sync and on yarn 4

### 👎 Actual Behavior with Screenshots

Recommended vs used versions do not really match.

### 👟 Reproduction steps

1. Download https://github.com/backstage/backstage/
2. Install it and see what yarn is used
vs
1. Run npx @backstage/create-app@latest
2. See what yarn is used

### 📃 Provide the context for the Bug.

We shouldn't do 3 different yarn versions between repos

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
Not sure this is a problem. 🤔  Sure we'll update the main repo as well soon, but it's not been a priority. Note also that sometimes we retain certain versions on the main repo - either forward or backward - because we want to ensure that features work as intended.

What was the problem you saw in the actions repo? It intends to support all yarn versions transparently.

**Comment by deejay1** [comment]
It just struck me as odd, that there are 3 different versions used at the same time. If it's deliberate like you said, than we can close this.
