### ISSUE TITLE
🐛 Bug Report: MissingAnnotationEmptyState problem

### ISSUE THREAD

**Issue by sspr007** [backstage/backstage#27588]
### 📜 Description

getting below error when I try to build the code

Packing source code into tar to upload...
Excluding '.git' based on default ignore rules
Excluding '.gitignore' based on default ignore rules
[WinError 3] The system cannot find the path specified: '.\\node_modules\\@oriflame\\backstage-plugin-score-card\\node_modules\\@backstage\\frontend-plugin-api\\node_modules\\@backstage\\core-components\\dist\\components\\EmptyState\\MissingAnnotationEmptyState.esm.js.map'

### 👍 Expected behavior

It should build successfully

### 👎 Actual Behavior with Screenshots

Packing source code into tar to upload...
Excluding '.git' based on default ignore rules
Excluding '.gitignore' based on default ignore rules
[WinError 3] The system cannot find the path specified: '.\\node_modules\\@oriflame\\backstage-plugin-score-card\\node_modules\\@backstage\\frontend-plugin-api\\node_modules\\@backstage\\core-components\\dist\\components\\EmptyState\\MissingAnnotationEmptyState.esm.js.map'

### 👟 Reproduction steps

az acr build -r [azure acr name] -f acr-task.yaml .

Following the steps here:

https://techcommunity.microsoft.com/blog/appsonazureblog/introduction-and-deployment-of-backstage-on-azure-kubernetes-service/4052492

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
I think the article uses the legacy Backend, which isn't used anymore when you bootstrap a new app using `@backstage/create-app`. There is a [migration doc](https://backstage.io/docs/backend-system/building-backends/migrating) in case you want to try to "patch" the steps in the article by yourself. Otherwise I would recommend reaching out to the author of the article.

I'm going to close the issue as this isn't related to the source code of Backstage.
