### ISSUE TITLE
Scaffolding Logs showing a lot of blank lines

### ISSUE THREAD

**Issue by blueelvis** [backstage/backstage#2790]
## Expected Behavior
I expect that there should not be so many blank lines in the logs generated while scaffolding.

## Current Behavior
A lot of blank lines are there like below -
![image](https://user-images.githubusercontent.com/6985763/95389693-d0605400-0911-11eb-9650-3bc50ceb8344.png)

With some lines containing something like the following -
![image](https://user-images.githubusercontent.com/6985763/95389744-e837d800-0911-11eb-974d-0a562b433c57.png)

## Possible Solution
Not sure what is the problem. Probably, the template or the CLI needs to run in a CI mode? Or do we need to expand the size of the log window?

## Steps to Reproduce

1. Create a new Website using the sample React template.
2. Watch the logs waltz when it is trying to do the linking.

## Context
This issue affects because it is very difficult to keep track of what is going (Right now, that is taking around 15 minutes of scaffolding). Furthermore, the Log screen is extremely small and cannot be maximized or log trailing be stopped (Like the option we generally have in CI runners)

## Your Environment

- NodeJS Version (v12): v12.18.4
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 Enterprise Version	10.0.18363 Build 18363
- Browser Information: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by shmidt-i** [comment]
So the reason behind is that `create-react-app` is not super friendly in terms of being used inside CI environment. We mostly included it as a way to show example on how does one create a custom templater for the scaffolder.

The aforementioned empty lines indeed are coming from `cra` being very explicit and interactive and to be fair, not focused on such a use case as being ran inside docker. There are some feature requests, e.g. https://github.com/facebook/create-react-app/pull/5429 being closed by the maintainers due to the lack of interest 😉 

If anybody wants to dig more, most of the action happens in https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/init.js#L133

As a step towards better UX - #2794

**Comment by blueelvis** [comment]
I couldn't understand the reason behind why they decided not to add a silent option :|

If we have some other sample app which can be used for scaffolding, do you think that would make more sense to host instead of this which -
1. Gets initialized in less time (15 minutes is kind of too much)
2. Has the proper logging?


-Pranav

**Comment by shmidt-i** [comment]
Of course you can use whatever fits your use-case, that's the benefit of the architecture 😄  You can define your own cookiecutter-based template or create a totally new templater and tell the scaffolder to use it.

Just to mention, `cra` template in this regard stands out time-wise. If you try `React SSR Template` for example, it will take minute tops.

**Comment by benjdlambert** [comment]
I'm thinking that it might be better to actually capture the output of `create-react-app` and just create cookiecutter from that rather than using the `create-react-app` cli to create the template. The thing that takes the most time is the npm install, but it's not an option you can configure unfortunately.
