### ISSUE TITLE
Improve "Create a new component" UI

### ISSUE THREAD

**Issue by Nek** [backstage/backstage#2794]
A component creation is a long process that can take more than 15 minutes to complete. Current UI uses a modal window to display a status of the process which is misleading and makes it look like leaving the page will stop the process.

![image](https://user-images.githubusercontent.com/132011/95426647-8776c280-0946-11eb-8a07-3db57d70eb2a.png)

The link to the one of the creation templates on the default local installation is http://localhost:3000/create/create-react-app-template

## Feature Suggestion

Use a separate persistent page for showing the status of creation process (maybe even a list of several processes).

## Possible Implementation

TBD

**Comment by adamdmharvey** [comment]
I'm a fan of #2807 👍 I hadn't realized the modal could close so easily by just clicking anywhere else on the site during a scaffold. Ended up running it a second time, for it to fail saying repository already exists. But it existed BECAUSE I had mistakenly closed the previous modal and didn't even know it was still running in the background; it had finished to completion the first run, so my second run failed.  So the idea of keeping it as a hovered, non-closable modal makes a lot of sense!

**Comment by benjdlambert** [comment]
Hey @adamdmharvey, so we merged #2807 but that comined with another PR really broke the create flow. So I completed and merged this #3388 which takes care of some other of the usability. Gonna close this issue now, and the new changes will be published in the next release this week
