### ISSUE TITLE
🚀 Feature: More detailed metadata on `BackendFeatureMeta`

### ISSUE THREAD

**Issue by alper98** [backstage/backstage#27987]
### 🔖 Feature description

To improve the utility and informativeness of the `BackendFeatureMeta` object coming from the new `InstanceMetadataService`, it would be awesome if we could add more detailed metadata fields. These fields can provide valuable insights into the installed features and are useful for communicating essential information on the frontend, such as on a health status page. For a starter, something like `owner` and `description` would be awesome.

### 🎤 Context

We have a use case for displaying the health of the installed features in our Backstage instance. With the introduction of [this pull request](https://github.com/backstage/backstage/pull/27921), we now have a foundation for describing metadata surrounding the features.

This enhancement allows us to provide a more comprehensive view of each feature's status and health, enabling us to quickly assess the operational state and other critical attributes. 

### ✌️ Possible Implementation

I'm imagining `createBackendPlugin` getting a new field like `metadata`, which would be an object containing some information about the plugin.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by aramissennyeydd** [comment]
👋 Glad you're interested in the `InstanceMetadataService`! I think this would make more sense to add to `PluginMetadataService` or similar instead of `BackendFeatureMeta` or `InstanceMetadataService`. 

I recently created something internally for us to track plugin SLO management that allows per-plugin metadata, one big issue you run into with this approach is that the core plugins aren't adjustable without creating your own wrapper. One idea that comes to mind here is the `catalog-info` files that we create for plugins, you could ingest them to your Backstage instance and use that to grab the individual ownership + description for plugins (depending on your entity ref scheme) and allows for easier overriding of core plugins through a custom catalog processor.

**Comment by alper98** [comment]
Thanks for the reply! I'll give it a shot with the catalog info files :) 


I'll close this ticket
