### ISSUE TITLE
[RFC] On specific semantic of systems, components, and resources in Catalog

### ISSUE THREAD

**Issue by tkrop** [backstage/backstage#2898]
**Status:** Open for comments

## Need

While mapping our Zalando "application" universe to the Backstage Catalog, we stumbled across defining the precise semantic and proposed usage patterns when mapping it to  `systems`, `components`, and `resources` (see #390). Since the terms are currently not specific enough defined and the examples do not provide no clear picture, the questions are as follows:

1. Is the common understanding of the `systems` and `components` terminology in the sense of `system`-types and `component`-types, i.e. may they have different manifestations for test, sandbox, and production environments? Or should these manifestations be model as distinct `systems` with distinct `components`?

2. What is the precise definition of a `component` and consequently what exactly distinguishes it from a `resource` - especially in boarder cases? Is a *database* a `resource` or a `component`? What is a *database management system*? What is a *cron-job*? What is a *library*? What is a *Docker image*?

3. How would you express a relation between `components` or between `resources`, e.g. if a *cron-job* is **using** a certain *library* and both are either modeled as `components` or a `resources`? Do you think it makes sense to model this using your terminology at all?

We think that answering these question is important to create a common understanding of what the catalog is supposed to describe as `systems`, `components`, and `resources`, so that plugins will use and represent the catalog entities using the same semantic and are interoperable.

## Proposal

Conduct a survey to understand the expectations of the Backstage stakeholders. Improve the model documentation to be more precise on the expected mapping of real world entities with respect to the catalog terminology, based on the survey results. May be also create an architecture decision record to provide guidance for developers.

## Alternatives

Each backstage user is deciding independently on the semantic.

## Risks

* Survey does not provide consistent perspective on expectations of stakeholders.
* Plugins are not interoperable, because they are base on different mappings of real world entities.

**Comment by freben** [comment]
@mbruggmann may be interested ^

**Comment by Rugvip** [comment]
Also a link to the original catalog model RFC for reference: https://github.com/spotify/backstage/issues/390

Some thoughts from myself:

1. This comes down to whether the software is different. If a piece of software is deployed to a staging and production environment, it is still one component and the difference would rather be modelled as different `deployment`s. If for example the staging environment builds on top of the production environment software to add capabilities like providing mocked data, this might be a separate `system` or `component`.

2. A component has source code associated with it, while a resource at most has some declarative configuration, such as a terraform config.

3. Very much related to https://github.com/spotify/backstage/issues/1964. I think most kind of relations between `components` and `resources` would be expressed as `dependencies` (and `dependents`).

**Comment by mbruggmann** [comment]
Thanks for raising this @tkrop, agree that the definitions would profit from being more clear. 

Trying to summarize my thoughts: I think `components` should map to "pieces of code" in source control. `resources` express the (cloud) infrastructure needed for a component or system at runtime (such as databases, caches, etc). It'll probably be quite hard to agree on how exactly `systems` should be modelled, so I would have started with roughly treating that as a tag on entities to loosely group things together. So that'd leave me with:

1. Yes, those would be types, and they could be deployed in multiple environments. So If I go to a system or a component in Backstage, it would list different manifestations (could be different regions, could be production/staging environments, ...)
2. Roughly, everything that has source code is a component, and everything else a resource. Although some things might be ephemeral and thus not worth tracking in the catalog at all (say, Kubernetes pods or Docker images). Those we could instead look up from a plugin by talking to an external API directly, eg by querying the K8S server with the information contained in the component entity.
3. Given that I see resources as cloud infrastructure, I wouldn't model code dependencies or resource dependencies in the catalog and leave that for other tools like static analysis. As in 2), we could still surface the analysis for a component in Backstage of course, I just wouldn't try to capture those relationships in the catalog due to the fast-changing nature of it. Are you thinking about a specific use-case here? We don't have much tooling in this space at the moment...

Not super set on those, so would appreciate to hear from the community what would make the most sense!

**Comment by freben** [comment]
Agreeing with the above, making some additions:

1. Because you used the word "type", I'd just like to put in a little note that System and Component are overarching entity `kind` s, just so we don't confuse them with Components that can be of different `spec.type` s. :) With that aside, I agree with the above that the base take is that a Component represents a single "unit of code" over time - it doesn't directly concern itself with deployment mechanics, the minutiae of what build artifacts are output, what different versions exist etc. That data is interesting, but might not be modeled directly in the catalog itself. However as an _end user_, I will of course be interested in for example the deployment status in different environment, in _Backstage the user interface_. But that data may be fetched from spinnaker instead. And you may want to see the build artifact statuses and versions, but you may fetch those from artifactory or docker-hub instead. On a technical level, you may choose to do all of the above in the graphql layer so that it's conveniently abstracted for the consumers.
2. For a cron job specifically, if it's a standalone thing with its own source code, you might have a component for that runnable code. But the fact that what triggers it is cron, might not be modeled at all or at most in the form of an annotation that helps consumers look up the actual job externally (inventing `google.com/cloud-scheduler-slug: <project>/<id>` perhaps?).
3. This is one place where we have a strong plan forward as mentioned :) We would love to have your involvement in #1964 when it starts taking shape, to make sure we cover the use cases you have.

**Comment by tkrop** [comment]
@Rugvip @mbruggmann @freben thanks for sharing your insights. I can now see clearer from which perspective you are looking on this terminology. Consent of your comments seem to be the following aspect:

1. `systems` and `components` are manually maintained abstractions (types/classes) of logical software units. They do not describe distinct running systems and deployments, e.g. in Kubernetes, but provide the context information for these running instances.

2. A `component` has source code associated and is supposed to live for a long time (not ephemeral) - while a `resource` has no source code related?

3. The third aspect is supposed to be covered by allowing `dependencies` to be experessed as proposed in #1064.

In addition, I can see two implementation aspects in the [Catalog Docs](https://backstage.io/docs/features/software-catalog/descriptor-format): (1) `systems` are currently modeled as `labels` only, while (2) `libraries` are modeled as components. This suggests, that:

1. a `system` is not a first class model, where I can attach documentation, playbooks, risk evaluations etc.
2. a `system` is optional for `components`, e.g. *libraries* are likely not belonging to a distinct `system`.


Our understanding of this terminology is slightly different - maybe more complex and somehow conflicting:

In Zalando we have an `application-registry`. It consists of the description of *applications systems* which may consist of multiple (logical) *components* interacting with each other and with other systems via APIs. The *components* may come from one or multiple repositories and can be deployed independently to any number of environments and Kubernetes clusters building one common or multiple independent application system instances. In this model, we attach documentation, playbooks, risk-evaluations for GDPR or security, as well as access rights on *application system* level, and support channels. The *components* usually have attached source code repositories, API specifications, build and deploy pipelines, as well as further documentation resources. The `application-registry` is guarding the `deployment` process, i.e. no deployment of an *applications systems component* without referencing an active *application* and provides the means for restricting access.

Since our understanding of *systems* and *components* is focused on the *capability* to be *installed* and *executed* in order to perform a *business function*, as well as on the aspects of security, operation, support, and compliance with regulations, we currently do not model libraries as these  would not match this aspects.

@Rugvip @freben @mbruggmann What do you think about modeling systems as a first class citizen with own entities to attach resources to and resolve the conflict? Not sure how to handle the library challenge yet.

**Comment by Rugvip** [comment]
@tkrop The intention is very much to extend the catalog with a `System` entity `kind`, we're just not there yet.

Clarification regarding (2): All catalog entities are things that we expect to live for a long time.

**Comment by freben** [comment]
I wonder if it would be helpful or just confusing if we added System and Domain today - basically with empty `spec` - and then gave it some time to figure out exactly what fields to add to them. If we decided how to express the relation between them (whether it should go in metadata, as a label, or in spec), then at least users could get going with the modeling.

**Comment by freben** [comment]
In the internal Backstage, the catalog also is instrumental in tying together components with CI/CD systems, somewhat similarly to what you describe. There, components have gained the concept of a "role", which is what binds them into a certain project, guides host naming and to some extent service resolution, defines permissions boundaries etc.

**Comment by freben** [comment]
@tkrop The core team has given some feedback - we welcome further discussion and can provide more clarification of course. How would you like to treat this ticket as such? Should we keep it open until we sorted out how things match your needs, or would you like to branch out to separate action tickets of things that need adjustment, or would you like to wait for community input?

**Comment by tragiclifestories** [comment]
Just quietly bumping this: `system` or `domain` may be a better match for modelling a monolith than components (I suggested a component-based approach in https://github.com/backstage/backstage/issues/3726), which is something that matters to my lot ;-).

Just wondering if discussions on this have moved on since October?

**Comment by freben** [comment]
@tragiclifestories @tkrop See the [newly added issue](https://github.com/backstage/backstage/issues/3765) about introducing `System`, `Domain`, `Resource`

**Comment by tkrop** [comment]
Thanks, resolved.
