### ISSUE TITLE
Remove requirements for Group model

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#3049]
The current group model according to the [docs](https://backstage.io/docs/features/software-catalog/descriptor-format) requires ancestors, children and descendant. 

But this means that if my org is:
root => Engineering -> Platform -> Devtools -> TeamA 
I need to write any of these names in 3 places. Now I want to change "Devtools" to "Internal tools" and need to do modifications in multiple places.

If you want to build a tree of the org, the only required element should be the parent, which interestingly enough is the only optional element currently

**Comment by freben** [comment]
It's optional only because the org root can't have a parent :)

Yep this is on the roadmap. Let's use this ticket to keep track of the progress of this aspect of it.

There is ongoing work (see recent PRs) to implement [relations](https://github.com/spotify/backstage/issues/1964). The end result will be a flexible model where the input yaml can express either side of a relation, but both sides will be generated automatically.

For example, in some data sources, the parent is easily and immediately available as you say. In other data sources, the immediate children are instead easily available. Both should trivially be supported, and should lead to identical sets of relations to be produced.

**Comment by freben** [comment]
Update:

Initial relations support has been implemented.

We are considering removing the `ancestors` and `descendants` fields.

There is some interesting discussion around relations and usage around users and groups for those who may be interested here: https://github.com/backstage/backstage/pull/3293
