### ISSUE TITLE
TechDocs: Improve user experience 

### ISSUE THREAD

**Issue by soapraj** [backstage/backstage#3098]
- speed up the initial load time to improve the user experience of tech docs

**Comment by JacobValdemar** [comment]
+1 for load times for tech docs in general

**Comment by OrkoHunter** [comment]
There have been some efforts to improve the user experience -

- We now have a new preparer (URL Reader a.k.a. readTree) which does not use `git clone` but uses Source Code Hosting Provider's APIs to fetch files. This has improved the build time significantly because we are running some operations in memory and avoiding filesystem.
- Ability to use external storage (GCS) so that docs are not built each time the app restarts.
- Some minor TechDocs Reader improvements.
- Backend periodically building docs in intervals https://github.com/backstage/backstage/pull/3652

Incoming

- Non blocking documentation generation when users open a page. https://github.com/backstage/backstage/issues/3717
- (Doesn't speed up, but improves UX) Show build process https://github.com/backstage/backstage/issues/3579
