### ISSUE TITLE
[RFC] TechDocs URL Inconsistency problem - Each docs page has two URLs

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#3122]
**Status:** Open for comments

## Current situation

There are two ways of reading documentation in backstage.

**1. The `/docs` way**

User opens their Backstage. They see a "Docs" section in the sidebar. They reach `/docs` a.k.a. the TechDocs homepage. They see all the documentation sites that are available for them to read. They choose any entity or docs site and are taken to the docs with URL `/docs/.../:name`.

Example working URL: http://localhost:3000/docs/default/Component/backstage/overview/what-is-backstage/

**2. The `/catalog` way**

User opens their Backstage. They find a particular service they are interested in. They open it and see a "Docs" navigation tab for the service. They click on it and are taken to the docs with URL `/catalog/...:name/docs`,

Example working URL: http://localhost:3000/catalog/Component/default:backstage/docs/overview/what-is-backstage/

1. `/docs` way

![Screenshot 2020-10-27 at 08 02 26](https://user-images.githubusercontent.com/8065913/97267676-d2d80e80-182a-11eb-9d07-050ee3a3106f.png)

2. `/catalog` way

![Screenshot 2020-10-27 at 08 02 34](https://user-images.githubusercontent.com/8065913/97267666-cf448780-182a-11eb-8e31-3d99f223f135.png)

## Is this fine?

In my opinion, having two URLs for the same docs page is not a great user experience. It affects the _flow_. As a user when I have to find documentation and I have to choose between either going `/docs` way or `/catalog` way, it does not feel right.

But, your opinions may differ. You may like it this way. And hence this RFC.

> **Requesting your comments - do you think this is fine or there is a problem?**

## Which way to go - if we have to choose one?

The absolute `/docs` page a.k.a. TechDocs homepage is here to stay. It is a place for the amazing ideas around technical documentation in Backstage and in a company. And we are improving it (#2028).

However, we do not have to serve individual documentation pages on `/docs`. That is up for a discussion. Let's see some pros and cons of going one way.

1. The `/catalog` way

Good:
If I am browsing a service and I find the "docs" tab in the nav bar along with CI/CD, Code Insights and what not, I will be thrilled! Backstage will truly serve as the one place where I go to explore a service.

Not so good:
What about entities which are not services i.e. documentation website?

2. The `/docs` way

Good:
Feels like a space for all technical documentation that I can find in my company. Gives a separate "identity" to documentation.

Not so good:
Documentation feels detached with the actual service and other discoverability prospects of the service i.e. CI/CD, Logs, Code insights, etc.

## Proposal

My proposal here is the following
- There should be one and only one URL when a user is looking at any docs page. They could have been redirected from somewhere else and that is fine.
- Keep the `/docs` page a.k.a. the TechDocs homepage where users can browse documentation sites and all other available service documentation.
- Keep the `/catalog` way of browsing documentation.
- Redirect the `/docs` way URLs to `/catalog` way.

---

Any and all of your comments are appreciated, since this is all about user experience. It is better to address this problem sooner rather than later.

**Comment by dtuite** [comment]
Internally in Spotify, what % of "docs" are pure documentation sites vs documentation which is related to a service or other entity which would live in the catalog?

The higher that percentage is, the more value there is in maintaining a separate UX for it.

**Comment by dtuite** [comment]
I find this confusing for APIs too. My brain doesn't grok why I have to go to a separate page to search for APIs. I thought the idea of Backstage was to have a single catalog to hang functionality off.

(This is a rethorical comment 😀)

**Comment by iamEAP** [comment]
Yeah, this will become a bigger issue when there is an interface for searching things...  Presumably, a documentation site/page should only have a single result, but if so, how do we know where to point them?

To that end, I like your proposal @OrkoHunter, but perhaps with a tweak or two.  Lemme know what you think:

- There should be a way to indicate when a docs site is "documentation only" or attached to a service/other entity.  If it's "docs only," then its canonical URL is at `/docs`, and if it's tied to an entity, it's under `/catalog`.  Otherwise, redirects work the same way.

**Comment by emmaindal** [comment]
Thanks for writing this up @OrkoHunter really good! 

> Not so good:
What about entities which are not services i.e. documentation website?

Since documentation-only sites always will be an entity (of type documentation) - I don't see this will be a problem. It will still have a /catalog page attached to it anyway with a docs tab, ci/cd as well as other things.

I like your proposal, and I +1 one the fact that we do want to keep /docs for discoverability reasons.

**Comment by hooloovooo** [comment]
I really like the idea of treating pure documentation entities as one thing and documentation tied to other entities as another. I think it makes sense that the `/docs` route is for pure documentation entities and serving up the documentation as a part of another entity in the catalog makes sense when the the documentation is an explanation of the entity.

**Comment by emmaindal** [comment]
> `/docs route is for pure documentation entities` 

-> I'm a little bit concerned about this so just wanted to throw the question out here - a documentation entity will also have its own entity page as well as its own "Docs" tab. So by using /docs as route for pure documentation entities we will not get rid of the "problem" that the documentation will have two different locations. /catalog/<entity>/docs... and /docs/<entity>... 

Would like to know more about what you think is the advantages of differentiate the user experience of reading (and finding) documentation for docs-only entities vs docs-with-code entities?

**Comment by hooloovooo** [comment]
My reasoning is the difference is the purpose of the documentation. Since backstage is built around entities it makes sense to be able to get the documentation for those entities where you go to view the entity. A pure documentation entity could be anything. Something like `Coding guidelines and best practices` that doesn't have a logical connection to another entity.

Regarding the documentation entities showing up in the service catalog i think that makes sense in a lot of cases since quite often they'll have a CI/CD pipeline etc. Currently they're only shown if you specifically select the `Documentation` filter in backstage though so they won't show up by accident when looking for other things.

**Comment by hooloovooo** [comment]
> My reasoning is the difference is the purpose of the documentation. Since backstage is built around entities it makes sense to be able to get the documentation for those entities where you go to view the entity. A pure documentation entity could be anything. Something like `Coding guidelines and best practices` that doesn't have a logical connection to another entity.
> 
> Regarding the documentation entities showing up in the service catalog i think that makes sense in a lot of cases since quite often they'll have a CI/CD pipeline etc. Currently they're only shown if you specifically select the `Documentation` filter in backstage though so they won't show up by accident when looking for other things.

Edit:
I guess there's nothing stopping us from linking to the `/docs` url when clicking the 'Docs' tab on a documentation entity if we would like to avoid the confusion of having more than one url.

**Comment by JacobValdemar** [comment]
In terms of user experience I think our developers would want go to the service catalog for technical documentation (and api docs as dtuite said) about a service and go to the documentation page (/docs) for documentation which isn't related to a service e.g. golden paths.

Whatever solution is agreed upon, I think it's important that it respect that this is two different use cases / scenarios.

**Comment by adrianke77** [comment]
My two cents, it would be good to have `/catalog/<entity>/docs` going by the approach that everything is a catalog entity, and any global index page for documentation at `/docs` or other links from elsewhere would have individual hotlinks going to the docs under different entities. So that the urls support the concept of everything being an entity.

**Comment by andrewthauer** [comment]
There is a related discussion going on in #2791, however, you can skip to https://github.com/backstage/backstage/pull/2791#issuecomment-719974174 for the more relevant bits.

**Comment by erikxiv** [comment]
Backstage newbie input: My personal preference is having clear boundaries and ownership on everything, which aligns well with tying documentation to entities. This also seems to aling with how to discover doc references and backstage in general. As the comments above show this preference is not universal, but we might easily cater to both worlds by utilizing documentation entities, or tying documentation to organization entities. The latter could for example be a good fit for best practices (either best practices for a service, a technology, for a team or for the larger organization). (After a number of reorgs and acquisitions, tying stuff to an organization rather than a backstage instance sounds appealing). These different preferences might also be reflected in a customizable doc home page where different types of documentation might be prioiritized or grouped together in user-friendly ways.

Random thought: There might be a use-case also to tag a documentation atom to multiple entities, such as a guide on how to combine mutiple entities together. That would on the other hand suggest making documentation into a primary entity which might not be the path we want to take as it sounds like an edge case which would disrupt the current structure in a bad way.

Consistency is good, so I support that effort and with the rationale that an entity ”owns” documentation rather than the opposite way around, I prefer going the catalog way as suggested. As the catalog entity concepts are wont to dominate backstage and plugins, one might ponder if ”everything” in backstage should be below the catalog url path, but that topic was already raised in the the referenced issue above.

**Comment by adamdmharvey** [comment]
@erikxiv Love your point in "random thought" re: tagging documentation against multiple entities.  We frequently have that, where two or more teams collaborate to a sort of "integration" guide, and while there might be a product manager who coordinates the need with the business/customer, it's _still_ multiple engineering squads with multiple entities (products) who all need to contribute to the integration guide. (and we frequently support them with true tech writers who are non-squad aligned in these scenarios, focusing only on the integration guide for example) Begins to lean to an entity having an `1..n` style list of associated docs (maybe they have their own primary techdocs, available on the `/catalog` URL, but _also_ ref out to three other integration guides, each of which is its own unique entity in the catalog as type docs and thus referenced on the `/docs` URL).  Anyway, +1 for your example case there.

**Comment by emmaindal** [comment]
Also love your point in "random thought" @erikxiv, the use case I can think of is having one piece of "system documentation" that you can tie to all relevant entities that plays a role into the documentation. 

@OrkoHunter One thing I had in mind, we discussed a little bit on additional metadata in the Header we display that will not be displayed here as it will not render the documentation Header. I don't think I see it as a problem anymore as we 1. currently have almost the same metadata as the catalog entity page header anyways. 2. if we add additional metadata in the header (contributors, last updated or other things), we could render this information in the header only when navigating to the Docs tab? or let the Reader display this metadata somewhere else on the page.

**Comment by OrkoHunter** [comment]
@emmaindal I also thought about Reader displaying the metadata of last updated, contributors, etc. But I feel this will reducing the height of the documentation page. So, I feel let's keep the metadata in the header itself. I think it should be feasible to update the Entity header based on what tab is selected (e.g. Docs, CI/CD, API, etc.).

**Comment by adamdmharvey** [comment]
Taking @OrkoHunter 's original proposal up in his description, I might pitch a slight nuance based on the thread here. (specifically changing the "redirection" point)

**Updated proposal:**

* There should be one and only one URL when a user is looking at any docs page.
* They could have been redirected from somewhere else and that is fine.
* Keep the /docs page a.k.a. the TechDocs homepage where users can browse documentation sites and all other available service documentation.
* Keep the /catalog way of browsing documentation.
* Redirection
  * When documentation is attached to an entity, redirect the /docs way URLs to /catalog way.
  * When an entity IS documentation, redirect the /catalog way to the /docs way.

In this way, either link "works" - and they should all be visible on the techdocs homepage. But clicking my service documentation  jumps me to my component entity page in the catalog, showing my service and starting on the docs tab immediately. While clicking on my independent golden path instruction documentation, keeps me in the pink techdocs theme at /docs route and shows me the docs there. In some ways, it begins to lean in to elevating a `kind:component + type:documentation` up to a 1st level `kind:documentation`.

Is that sort of where we've headed?

**Comment by OrkoHunter** [comment]
Yes @adamdmharvey, I agree with your clarification of redirection based on `kind:documentation`.

**Comment by iamEAP** [comment]
Coming back to this almost 7 months since originally posted...

With all of the composability work that's gone into Backstage as a whole, and TechDocs in particular...  Is this perhaps no longer really a decision for us as **Plugin Developers**, and more a decision for each individual **App Integrator**?

One organization may go all-in on the Catalog and customizing the entity page, including embedded docs.  Another organization may choose to forego the docs tab on an entity page, instead only showing them under, e.g. a `/docs` folder.  Yet another could choose to do both!

For us, it's just a matter of ensuring it's _possible_ to have more or less the same experience using one or the other.  ...That may involve a little more work to expose some of the things @emmaindal mentioned (e.g. extra metadata in the header) as composable building blocks.  ...And also perhaps some documentation work to advise on the pros/cons of each approach (or mixing them).

What do y'all think?

**Comment by emmaindal** [comment]
> Coming back to this almost 7 months since originally posted...
> 
> With all of the composability work that's gone into Backstage as a whole, and TechDocs in particular... Is this perhaps no longer really a decision for us as **Plugin Developers**, and more a decision for each individual **App Integrator**?
> 
> One organization may go all-in on the Catalog and customizing the entity page, including embedded docs. Another organization may choose to forego the docs tab on an entity page, instead only showing them under, e.g. a `/docs` folder. Yet another could choose to do both!
> 
> For us, it's just a matter of ensuring it's _possible_ to have more or less the same experience using one or the other. ...That may involve a little more work to expose some of the things @emmaindal mentioned (e.g. extra metadata in the header) as composable building blocks. ...And also perhaps some documentation work to advise on the pros/cons of each approach (or mixing them).
> 
> What do y'all think?

Really good point @iamEAP, when you say "for us, it's just a matter of ensuring it's possible" do you mean as a app integrator it should be possible for me to choose between having two different paths for docs or one? 

I wonder if we should create some new issues out of this one then as action points? Around the things you mentioned, clear documentation on how, what needs to be implemented to support both use cases.

**Comment by mertcb** [comment]
Is this alive @OrkoHunter ? I guess I'm having some problems with that. Let me show you some screenshots. 

On entity page "Docs" tab, plugin tries to go `api/techdocs/static/docs/default/Component/<component_name>` like shown in below. 

<img width="1792" alt="Ekran Resmi 2021-12-06 14 13 13" src="https://user-images.githubusercontent.com/36340604/144836621-bdc611c3-1471-45bb-9a3c-c1a3f8c384d9.png">

But you know, with the Beta migration, the kind is starting with a lowercase letter, so do our files in our storage. 

On the actual docs page, plugin tries to go `api/techdocs/static/docs/default/component/<component_name>` like shown in below. And as it's supposed to be... 

<img width="1792" alt="Ekran Resmi 2021-12-06 14 16 26" src="https://user-images.githubusercontent.com/36340604/144837040-bace95cb-c413-43f2-916b-526f759ee426.png">

I'm using the latest versions of techdocs and techdocs backend plugins.

**Comment by OrkoHunter** [comment]
@mertcb Hey! That sounds like a bug to me. Creating a separate issue or reaching out on #docs-like-code channel on Discord would help more for us to dive deeper. :)

**Comment by mertcb** [comment]
@OrkoHunter I opened an issue at #8381 :) Thank you for your interest 💯
