### ISSUE TITLE
Doco suggests plugins need to hardcode builder.add() calls for catalog: still accurate?

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3167]
The following statements are available on this page:
https://backstage.io/docs/features/software-catalog/installation

Specifically, is this paragraph about adding custom `builder.add()` call for plugins accurate any longer?

https://github.com/spotify/backstage/blob/238715aac2e3cf326b0c82282497d3b1c8e5c8bc/docs/features/software-catalog/installation.md#L55-L59

I noticed they link to an old commit in a file which was pretty broadly refactored, and it looks like whatever it was referring to before is no longer the case?  I'd take a guess this was refactored to use the routes concept in the `app-config.yaml`, but I'm not 100% sure so rather than fixing, reporting as a bug so someone with more knowledge on it might check it out.

**Comment by adamdmharvey** [comment]
Specifically, the `builder.add()` methods were removed from the `apis.ts` file via https://github.com/backstage/backstage/pull/2285, so perhaps @freben you might have insight?

**Comment by Rugvip** [comment]
Yep, docs are indeed outdated, the API is installed automatically nowadays

**Comment by rbideau** [comment]
I think this has been fixed by #4563 and in [536b6b5](https://github.com/backstage/backstage/commit/536b6b5207c5fab3699283e702ce8556b3c61178)

The last reference to `builder.add` is in [/docs/overview/architecture-overview.md#installing-plugins](https://github.com/backstage/backstage/blob/cca03162bcc9a54b01a891e8256101b9e5a16a45/docs/overview/architecture-overview.md#installing-plugins) but i don't know what would be more appropriate to update this doc.

Maybe this could only describe the code change done in the app by the command `create-plugin` ? Something like that:

---

Plugins are typically loaded by the UI in your Backstage applications `plugins.ts` file. For example, [here](https://github.com/backstage/backstage/blob/master/packages/app/src/plugins.ts) is that file in the Backstage sample app.

```tsx
// in packages/app/src/App.tsx

// other import statment ....
import { PluginPage } from '@internal/plugin-name'

// ...
  <FlatRoutes>
          {/* other routes */}
    <Route path="/plugin-path" element={<PluginPage />}/>
  </FlatRoutes>
```

As of this moment, there is no config based install procedure for plugins. Some code changes are required.

**Comment by Rugvip** [comment]
@rbideau Yep can just get rid of the `build.add` bit there. I think your suggestion is good, and we could combine it with asking users to refer to the plugin's README, and then mention that many plugins are installed as top-level pages like in your example.

**Comment by TejasQ** [comment]
Based on the last comment, I'm not entirely sure what's left to do here on this issue, but I'd still like to contribute. Could I ask for some clarification on the outstanding work to be done? Perhaps it's also just _closing the issue_ haha

**Comment by rbideau** [comment]
I didn't have time to update the doc and it seems someone already change the last reference in [Architecture overview](https://backstage.io/docs/overview/architecture-overview).

I think this can be closed.

**Comment by freben** [comment]
Seems alright now
