### ISSUE TITLE
Prettier should automatically fix and commit markdown files

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#3256]
**Status:** Open for comments

## Need

This might be controversial so I added the RFC tag 😄 

The Backstage docs have this "Edit" button, which is (I guess) supposed to make it easy to update the docs using the GitHub UI. I ❤️  this idea and I like to use it. Unfortunately, 2/3 times so far that I have tried to submit changes to docs, prettier fails for me and I have to go and clone the branch locally, run prettier and force push.

## Proposal

 1. Prettier should automatically run in a GitHub action against markdown files in the `/docs` directory.
 2. The `--write` flag should be enabled enabled.
 3. The result should be automatically committed to fix formatting.

## Alternatives

 1. I could try harder to do what prettier demands of me.

## Risks

Automated commits always come with some risk. I feel like the risk can be controlled by limiting the filetype and directories that this runs in.

**Comment by Rugvip** [comment]
I think we should convince GitHub to add a "Format" button in the editor instead :trollface: 

Afaik the best way to implement this is to skip the prettier check of `docs/` in PR builds, and instead add a format + commit step to the master build. That's because there are many cases where we won't be able to modify PRs from forks.

**Comment by dtuite** [comment]
Indeed, that implementation makes sense. This might be the shortest RFC process in history.

Want me to create a new issue or can you just take the labels off this one?

**Comment by Rugvip** [comment]
RFC
<img alt="Approved" src="https://user-images.githubusercontent.com/4984472/98385983-f29fdb80-204f-11eb-986e-e3d69f74badb.png" height="80">


Repurposed this issue :grin:

**Comment by andrewthauer** [comment]
> I think we should convince GitHub to add a "Format" button in the editor instead :trollface: 

It's possible this might actually be a thing soon - https://github.com/features/codespaces 😀

**Comment by padraigobrien** [comment]
I would like to take this ticket on if that is cool with yall?

**Comment by padraigobrien** [comment]
I submitted a PR, https://github.com/backstage/backstage/pull/4340

**Comment by TejasQ** [comment]
So it seems that PR was closed. 😅 

I'd like to take a stab at this. I believe the best way to achieve this goal is to have a _separate_ GitHub action that has a [single responsibility](https://en.wikipedia.org/wiki/Single-responsibility_principle) of formatting docs (and maybe _code_) because it would be easier to debug if/when it breaks, whereas including it in [`ci.yml`](https://github.com/backstage/backstage/blob/99dddfb61001ee823e717047fc3e9e9954a86b04/.github/workflows/ci.yml) could prove harder to identify failures at a glance and require more clicks.

In that spirit, I think we'd meet the need by adding a single workflow, `prettify.yml` that runs _only on merges to `master`_ and formats any changed code that it can, adding an extra commit for formatting. That is all it does. This would also _not_ run on forks and give us trouble there, only formatting code merged to `master` on this repository.

If this satisfies the constraints, I'd love to move forward here.

**Comment by Rugvip** [comment]
@TejasQ We could do that too, as long as we skip any formatting checks in the CI and master builds that the separate workflow is able to fix automatically, but of course skip no more than that.

**Comment by Rugvip** [comment]
Perhaps we could give this a go but only apply it to the `ADOPTERS.md` file in the root to begin with?

**Comment by TejasQ** [comment]
Nice! I will take this!

**Comment by tudi2d** [comment]
Talked to @TejasQ - will work on this 👍

**Comment by benjdlambert** [comment]
Assigned!
