### ISSUE TITLE
TechDocs: Support configurable working directory as temp dir

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#3333]
## Feature Suggestion

There is a `backend.workingDirectory` config option available in `app-config.yaml`. If enabled or set, it tells Scaffolder what path in file system to use for storing files that it needs to do its job. This was implemented by @mfrinnstrom in #3062.

When users are using `techdocs-backend` plugin to prepare and generate their docs, it is currently done using a temporary directory. But we want `techdocs-backend` to use the `backend.workingDirectory` path to fetch and store files in the prepare and generate step.

Note: For the "publish" step of TechDocs, we still want to use the `static` directory inside `techdocs-backend` since it serves a different purpose.

## Possible Implementation

Quite similar to how Scaffolder makes use of `backend.workingDirectory`. See PR #3062 for reference.

## Context

Also see #2998

**Comment by mfrinnstrom** [comment]
Thanks for creating this @OrkoHunter. This is something that would benefit us.

I happened to stumble upon the following PRs last week: #2925 & #3283. When switching to the new `url` format for TechDocs the `ReadTreeResponseFactory` handles the working directory. @Rugvip has added support for GitHub and I'm trying to implement it for Azure DevOps in #3307 

I'm not sure if this needs to be adapted in some way since a new temporary directory is created each time while the current flow tries to keep the cloned folder and merge in changes to that.

**Comment by TejasQ** [comment]
It seems the Azure DevOps PR (#3307) was also merged here! 🎉 

What more is required to complete this issue?

**Comment by freben** [comment]
@OrkoHunter could you give this a look to see if we can close this or not?

**Comment by OrkoHunter** [comment]
Sure! TechDocs takes a "prepared" directory path (where the source code markdown files were cloned/downloaded) and runs `mkdocs build` on the path to generate the documentation site. This is currently being done in a new temporary directory over here

https://github.com/backstage/backstage/blob/99dddfb61001ee823e717047fc3e9e9954a86b04/plugins/techdocs-backend/src/DocsBuilder/builder.ts#L144-L157

I this this issue can be closed if the optional `backend.workingDir` is used for creating this temporary directory where the generated site is stored. :)
