### ISSUE TITLE
[Search] Display empty state if no search results can be displayed

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#3342]
We currently are using the catalogAPI to get all entities to search across, If no results are returned from the request we are currently just returning `null`. We would like to return a EmptyState component here instead. 

[Storybook]( https://backstage.io/storybook/?path=/story/feedback-emptystate--data)

**Comment by magneticz** [comment]
Hi, I would like to work on this. Not sure what is the process, do i need to ask to assign it to me, so others are not working on it as well?

**Comment by emmaindal** [comment]
Awesome! I'll assign it to you @magneticz

**Comment by magneticz** [comment]
@emmaindal I have few questions regarding the issue. I located the check is happening ([here](https://github.com/backstage/backstage/blob/49554d43e37084979c6e3f56f7a3e3f2b9c0c995/plugins/search/src/components/SearchResult/SearchResult.tsx#L163)). 
My question is what do you mean by no results, when `results.length == 0` or when `results == undefined`?. Since api call always returns an array (at least that's my understanding from the code), results are undefined when there is an error, or when it's being loaded (based on types of useAsync). when result is empty (empty array), then right now component returns table with no rows (and a message).

am i correct to assume, that we need to return EmptyState, when the `results` is `undefined`? If so, should we return empty state only when there is an error(results can be undefined when `loading==true`)?

**Comment by emmaindal** [comment]
@magneticz good questions, let's do this. 
1. When loading=true, return the [progress spinner](https://backstage.io/storybook/?path=/story/feedback-progress--progress)
2. When there is an error, return the [Alert component](https://material-ui.com/components/alert/#alert) from material ui with the message "Error encountered while fetching search results. {error.toString()}"
3. When rresults are an empty array, return the [EmptyState component](https://backstage.io/storybook/?path=/story/feedback-emptystate--data) with the text "Sorry, no results were found".

**Comment by magneticz** [comment]
@emmaindal I created PR. One thing to note, is that when user types in a query, filtered result can be 0 as well, in that case, page will show empty table, which is current behaviour. So basically, if the api call result = 0 => show EmptyState, if filteredResult = 0 => show empty table

<img width="1440" alt="Screenshot 2020-11-19 at 13 13 42" src="https://user-images.githubusercontent.com/968005/99664947-3f7cac80-2a69-11eb-9c45-836517d0b47e.png">

**Comment by emmaindal** [comment]
@magneticz I see, I think that is ok for now, the most important part here is that it is clear to the user what is happening! Thank you so much 🎉
