### ISSUE TITLE
[RFC] Shared service breakdowns in Cost Insights

### ISSUE THREAD

**Issue by timbonicus** [backstage/backstage#3357]
**Status:** Closed

## Need

At Spotify, we have shared infrastructure services that are layered on top of cloud services. For example, a build system that reads Pub/Sub messages, executes builds on a VM, and saves the results in BigQuery. The costs for this infrastructure can be allocated to teams using it based on labels, but it would be confusing to present costs in terms of the underlying cloud products; the costs can be grouped instead by the triggering entity.

So far, we've used the notion of `Product` in Cost Insights loosely and had shared services represented as their own product panel. This worked fine so far, but #3268 introduced SKU breakdowns for products which leaks the abstraction a bit. For shared services, there's a different breakdown hierarchy:

**Cloud product**
Product > Entity > SKU

**Shared service**
Service > Entity > Product > SKU

The cloud product breakdown for a shared service is useful to the entity owners since there are configuration options that can control the product usage - for example, whether the data should be stored in BigQuery or GCS, and for how long.

For our current internal examples, the final level of SKU for shared services is not critical and would not provide meaningful value to engineers. The shared service team manages their own infrastructure, so entity owners using the infrastructure have little control or desire to inspect this deep into the service.

## Proposal

Ignoring the SKU-level breakdown of a shared service, the level of hierarchy for the shared service is identical to a cloud product. Therefore, we could re-use the same SKU breakdown concept from #3268 for a product-level breakdown of shared services. 

![sku-modal-breakdown](https://user-images.githubusercontent.com/3030003/98581621-c2468000-228f-11eb-99bc-ecfabf182048.png)

The SKU term is hard-coded right now in `ProductInsightsChart`, the `Entity` type in Cost Insights could have an `entitiesLabel` field alongside the `entities` array. This could be set to "SKU", "Product", etc. as appropriate. I think this would be preferable to each child entity having a label, since you could have a strange situation where an array of entities have differing labels.

## Alternatives

Alternatively, the entity bar charts could use stacked bars to break down the shared service by product and still support the SKU-level breakdown via #3268:

![stacked-bar-breakdown](https://user-images.githubusercontent.com/556258/99732896-896f8d80-2a7d-11eb-930a-1d15e5e53ae0.png)

This falls down a bit when the breakdown exceeds a handful of products, which is why we rejected the approach for SKU breakdowns. Some entities can result in many SKUs, and while a shared service would be less likely to suffer from this, it may still be messy with 4+ products.

The tooltip when mousing over this would need to show a row for each product with columns for the start/end periods. Something akin to this mockup from when we considered a similar approach for the SKU breakdown:

![multirow-tooltip](https://user-images.githubusercontent.com/556258/99733363-48c44400-2a7e-11eb-9823-2c4e22d75eb1.png)

This introduces some confusing interaction where different breakdowns appear both on hover and on click.

## Risks

The advantage of the alternative approach is that SKU-level breakdown can still be supported for shared services. However, this could be overcome in a different way if desired in the original approach. Technically, multiple levels of breakdown are possible with the data model. This is not currently UI-supported, but it could be someday.

Additionally, one could argue that shared services _should_ be represented differently in the data model rather than (ab)using the `Product` type. We may want to revisit this if our needs around shared services expand in Cost Insights.

**Comment by ryanvazquez** [comment]
Some initial thoughts on this:

The concept of a shared service seems distinct enough from "product" from a business standpoint that it should be called out separately in the UI. Since the cost of these services is attributable to multiple owners, it would be somewhat confusing to display them beside products whose costs are attributable only to the user.

That said, users may not necessarily use shared services in the org (though maybe this is unlikely). This lends me to think it should be configured separately from products as well, and optional.

While the `Entity` name has business significance, internally its really intended as a generic container for anything that has cost that is comprised of other things with cost over the same period. This data model is flexible enough to represent any product or service that can be divisible into other entities (or not). There isn't anything I'm seeing here that lends me to believe a shared service would have to be modeled differently.

> the Entity type in Cost Insights could have an entitiesLabel field alongside the entities array

This should be done regardless of this RFC.

So, something like:
```ts
type CostInsightsApi = {
  getSharedServiceInsights()?: Promise<Entity>
}
```

```yaml
products:
    computeEngine:
      name: Compute Engine
      icon: compute
sharedServices:
    eventDelivery:
      name: Event Delivery
      icon: envelope
```

I'm hesitant to employ different UI for a shared service unless there is sufficient guarantee from the data model that there won't ever be more than "a few" entities (however that is defined) but I don't think we can have that confidence. It would make more sense to use the existing comparison bar charts and and generalize the breakdown dialog.

**Comment by timbonicus** [comment]
> Since the cost of these services is attributable to multiple owners, it would be somewhat confusing to treat them as a product and/or display them beside products whose costs are attributable only to the user.

Hmm, what do you mean? The cost of a product is attributable to multiple owners too, we just filter the panel by a given group to only show the entities _you_ own. Shared services seem to match that conceptual model.

**Comment by ryanvazquez** [comment]
> The cost of a product is attributable to multiple owners too, we just filter the panel by a given group to only show the entities you own

Hm, right. We'd be filtering a service (whose cost are attributed to multiple owners), by entities _you own_ , and then from those entities, breaking them into products. It does match the conceptual model, so calling this out separately wouldn't really make sense unless there some other business related reasoning I'm not aware of. My understanding of a shared service was a bit off.
