### ISSUE TITLE
[RFC] Stack Rank Cost Insights Product Panels

### ISSUE THREAD

**Issue by ryanvazquez** [backstage/backstage#3382]
**Status:** Open for comments

## Need
An often requested feature from Spotify engineers is for products to be stacked according to greatest cost.

## Proposal

Stack rank and label products according to greatest cost over a given period. 

## Alternatives

There are multiple possible implementations of the stack rank feature

### Stack Rank Product Panels
Stack rank product panels over a default period. Preserve initial sort order.

This approach is the simplest but potentially misleading. In order for stack rank to be significant, products should be compared according to the same set of criteria. If a user were to toggle a period for an individual product, but the product panels remained in original sort order, it would visually imply that product costs are comparable across disparate periods.

### Global Period Selection

Add a page-level, or panel-level selection that toggles the period selections for each product panel to allow users to compare product costs over the same periods. Selections would refetch product data for each panel and resort product panels. Individual period selections would not trigger a resort.

### Separate Stack Rank Component

A separate stack rank component could be implemented that stack ranked products in a compact display at the top of the page or at the top of the section. The panels themselves would remain in the order according to configuration, not greatest cost.

## Risks

The greatest risks associated with this feature are potentially misleading rank results when comparing product costs across disparate periods. Additionally, more global selections can lead to more visual bloat.

**Comment by timbonicus** [comment]
To expand on this, Cost Insights currently presents products in order of _configuration declaration_. This can be  nonsensical, since a given team may not have costs for a given product. Teams expect that their highest-cost products will be shown first, rather than a product with potentially little or zero cost.

However, sorting by cost has its own caveats since costs can change given different time period selections. Cost Insights allows changing the time period in multiple sections of the page - for the Cost Overview, and for each product panel. The frontend naively sorting by _total_ cost for each product would then errantly order products with disparate time periods selected based on totals that are not comparable (e.g. 2 months cost vs 6 months cost).

A potential solution to _that_ could be to divide total cost by days in the selected period to compare average **daily** cost, but this could still produce a confusing re-ordering when different time periods are selected as new data and new totals would be returned. I'd say that no matter the approach, we should definitely avoid live-reordering based on one panel's selection - as this is quite confusing.

## Global Period Selection
I like the idea of **switching** period selection to be a global selection, but I don't like the idea of having conflicting period selects on the page (e.g. a global + per-panel overrides). This is just confusing UI-wise. If there were a single time period selection alongside the global project selection, we no longer have an issue with different-time-period comparison and could naively sort by product sums.

I see two disadvantages to this approach - foremost that the time period selection would now require a refresh of the entire page. This loses some fidelity; it's most likely that the user is looking at one particular panel and wanting to change the time period. The second disadvantage is that the the project / global period would be at the top of the page and no longer obvious when scrolled down to look at product panels. This could potentially be solved with design, a sticky filter bar or similar.

## Separate Stack Rank Component
I think adding a product breakdown to the top panel would provide something similar to this idea. The advantage I can see here is an argument that the products _should_ be in the same order for every team, though I don't buy this argument.

## Stack Rank Once
An alternative that I think could be reasonable is to stack rank based on the default period in the initial page load, then keep that order regardless of subsequent period selections. This provides what you would on initial load, and it would take a keen eye and some UI effort to trigger and notice a problem with the ranking later.

**Comment by sisidra** [comment]
Another consideration is to consider returning regular users vs new exploring users. While stack-ranking is very useful for exploring users, any changing order might be very distracting for regularly returning users.

I would love to see also exploration into other directions how exploring users can discover most important panel quickly as well as returning users don't get confuser when they point-click-scroll to their expected location but end up in unexpected location.

Maybe defining clear user type/persona type for the Cost Insights might help to answer these questions?
