### ISSUE TITLE
Only consider the configuration schema of a single package

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#3413]
The implementation of the configuration schema in #3264 uses a simple and effective discovery approach for schemas: "For all packages in the monorepo that have at least one `@backstage/*` dependency, use the schemas from the `configSchema` property and merge them." This works in the default monorepo installations with a single app and a single backend, but can break in more complex setups.

Consider the following scenario that uses different backends for security or scalability reasons:
```
- packages/
   |
   |-+- app
   | |---> @backstage/plugin-a-frontend
   | |---> @backstage/plugin-b-frontend
   |
   |-+- backend-main
   | |---> @backstage/plugin-catalog-backend
   |
   |-+- backend-techdocs
   | |---> @backstage/plugin-techdocs-backend
   |
   |-+- backend-third-party
     |---> @backstage/plugin-third-party
```

The schema of the `app-config.yaml` will include all the plugins, regardless of where they are used. If one wanted to split the configs for the individual backends and/or even the frontend, there is no real option to only check against the schemas of e.g. only the `app` or only the `backend-techdocs`. Since the `backstage-cli app:build` enforces the config-validation, one always need to include the configs of all the backends, even though they are not needed there. Or one gets complaints about missing properties in the schema.

Another case would be to have separate app-frontends and backends in the monorepo that (for whatever reason) have disjoint plugins and are configured in independent `app-config.yaml` files. However, I think this is a far less common case than the distributed backends.

## Feature Suggestion

Have a more flexible way to select which schemas apply.

## Possible Implementation

Maybe there could be an option to tell `backstage-cli config:check` a list of `package.json`'s that it should use as a starting point for the discovery. But I am not sure if that would be confusing to use or even possible with the `@lerna/project` library that is currently used.

**Comment by Rugvip** [comment]
@dhenneke Yep, agree that this needs a fix!

The config schema is initially loaded in two places atm, both within the CLI. One is the app bundle/server, and the other is the `config:*` commands. The logic for determining the packages is currently in one place, here: https://github.com/backstage/backstage/blob/a7974a676967ab6b0a69be8d6d1111702f1c9a2f/packages/cli/src/lib/config.ts#L28

For the bundle/serve tasks I think it makes sense to only consider the package that are part of the dependency tree of the app package. That type of discovery is already implemented [here](https://github.com/backstage/backstage/blob/a7974a676967ab6b0a69be8d6d1111702f1c9a2f/packages/cli/src/lib/packager/index.ts#L211) and it's not too tricky to modify to work for this use-case. This would be a breaking change though, and we especially need to make sure that any config schema in backend packages that are making values visible in the frontend are moved to the frontend equivalent packages.

For the `config:*`commands the compatibility is perhaps less of an issue, and more figuring out the behaviour that we want. My hunch is that defaulting to the current behaviour makes sense, but that we add either an arg or an option that focuses the printing/checking to be from the point of view of a specific package instead of for all packages in the monorepo.
