### ISSUE TITLE
[Auth] GitHub provider: only request access to org repos

### ISSUE THREAD

**Issue by JacobValdemar** [backstage/backstage#3474]
## Feature Suggestion

Some developers are using their GitHub account in both private and work-related contexts. To protect their privacy it should be possible to configure the GitHub provider to only request access to the GitHub organizations repositories, and not the developers' individual private and public repositories.

## Possible Implementation

It seems like it's not possible to limit the [scope of the OAuth App](https://docs.github.com/en/free-pro-team@latest/developers/apps/scopes-for-oauth-apps#available-scopes), so I don't think it's possible to just change the scope. Maybe it would have to get the access from the org instead of the users. @freben [said](https://discord.com/channels/687207715902193673/687235481154617364/781496632847761409) in Discord that "it may be the case that this will be entirely circumvented by going for the GitHub app powered flows in the future"

## Context

[Available scopes](https://docs.github.com/en/free-pro-team@latest/developers/apps/scopes-for-oauth-apps#available-scopes)

**Comment by freben** [comment]
Hi! To the best of my knowledge, this unfortunately can't be solved well at all with the current setup. That's one of the reasons that we are so keen on getting the [GitHub Apps](https://github.com/backstage/backstage/issues/1565) based auth in place. There, we'll be able to scope it strictly to those orgs that install it.

We'll close this for now, if that's OK with you, since we are not aware of a way to make this work with the current setup. We'll track alternative implementations of the concepts in tickets targeted at those alternative solutions - like the linked ticket above. If there are ideas or insights that add to this, or if I misunderstood something, feel free to reopen!
