### ISSUE TITLE
Bitbucket support for TechDocs

### ISSUE THREAD

**Issue by flyhard** [backstage/backstage#3525]
## Feature Suggestion

I am looking for a way to generate the techdocs from bitbucket repos. As far as I can see, this is not possible today.

**Comment by goober** [comment]
Maybe I am way out in deep water here, but since backstage already have support for reading files from Bitbucket maybe it is as easy as adding `bitbucket/api` to the following list?

https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/techdocs/stages/prepare/types.ts#L33-L39

**Comment by flyhard** [comment]
No, I don't think so. That addition is only part of it, I believe.

**Comment by hooloovooo** [comment]
This can probably be quite easily added as a git preparer. I would recommend adding this to the UrlReader though since that's the common way to manage downloading files from external sources. TechDocs currently support the UrlReader, but it's not advertised since cache invalidation is missing and it's not that well tested. We will transition to using that by default fairly soon though, and may even remove the current git preparers at some point.

**Comment by hooloovooo** [comment]
bitbucket should now be supported for techdocs when using the `url` type and should be available in the next release. I'm closing this and you're welcome to open up a new issue if you run into any problems. #3609
