### ISSUE TITLE
Techdocs Reader does rendering issues with mkdocs-material >= 5.5.0

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#3558]
This is related to a discussion started on [discord](https://discord.com/channels/687207715902193673/714754240933003266/783644315099987969) about techdocs rendering issues with `mkdocs-material`. Seems to start occurring in version `5.5.5` and beyond.

## Expected Behavior

Pages rendered in backstage with the techdocs component display correctly for new versions of `mkdocs-material`

## Current Behavior

There are 2 known issues (maybe more):

Arrow icons (e.g. in the left navigation tree), display as solid boxes rather then arrows (highlighted in red).

![unknown](https://user-images.githubusercontent.com/6507159/101093133-54d4f900-3588-11eb-9f28-ed461a96687b.png)

Hyperlinks within the page content display as regular text (not styled like links). Think makes it impossible to tell what is actually a link unless you hover over the text (highlighted in red).

![unknown2](https://user-images.githubusercontent.com/6507159/101093254-7df58980-3588-11eb-91a7-a476a597fe4d.png)

## Possible Solution

It's been suggested this is related to a change in `mkdocs-material` and the shadow dom transformations are somehow conflicting. Further investigation is required.

## Steps to Reproduce

1. Upgrade the `techdocs-container`'s version of `mkdocs-material` to >= `5.5.0`
2. Create a docs site that has a navigation with multiple levels
3. Add some pages that include hyperlinks to other pages
4. Build the site and view it in backstage.

**Comment by andrewthauer** [comment]
cc @emmaindal

**Comment by rneumaier** [comment]
@andrewthauer , @emmaindal , and @OrkoHunter ,
My team was recently dealing with what appears to have been a similar issue.
Ultimately I learned that we were creating documents in the latest version of mkdocs-material (6.2.4) and then trying to both process and display them in an older version (5.3.2).  

To fully understand the issue I needed to take a look at the following:
1. Where the document is introduced.
2. What was used to define the process to host and promote the documents.
3. All TechDocs services that host, process, or display the documents.

We would like to use the most recent version of mkdocs-material and not pin a specific version.  So I would love to hear when this issue is resolved so that we can study your findings.

**Comment by OrkoHunter** [comment]
Hey @rneumaier ! Current implementation of TechDocs is very specific to a version of `mkdocs-material` theme. TechDocs depends on the CSS selectors of that particular version to make it work in Backstage. And it does not seem possible to support multiple versions of the theme at a time. Read more in #3998.

Moving ahead, we want to get rid of mkdocs-material and create our own minimalistic mkdocs theme, but continue to support all the mkdocs extensions that mkdocs-material supports. So, you will not have to worry about what version of mkdocs/theme you are using to build docs (as long as you use TechDocs suite to build docs, which are to be displayed in the TechDocs plugin).

**Comment by OrkoHunter** [comment]
Closing this issue since it's a known problem that TechDocs Frontend is sensitive to a particular version of the mkdocs-material theme. Recommendation is to use techdocs-cli/container suite to generate docs, so that the expected mkdocs-material theme version is used.

https://github.com/backstage/mkdocs-techdocs-core/blob/572cb24d133967bb78781e4966c10f7029d25a83/requirements.txt#L5

Or, get rid of the mkdocs-material theme, replace with a simple theme without CSS, and use Backstage's components to style the page. See RFC https://github.com/backstage/backstage/issues/3998
