### ISSUE TITLE
microsite: make the anchor link icon show up

### ISSUE THREAD

**Issue by freben** [backstage/backstage#3707]
## Expected Behavior

When hovering over headings on the microsite (https://backstage.io), there should appear a little anchor link to the left. This is how it looks in GitHub when rendering the same page:

![Screenshot 2020-12-14 at 13 19 52](https://user-images.githubusercontent.com/3097461/102080864-81520600-3e0f-11eb-8d5a-057861f6e38d.png)

## Current Behavior

![Screenshot 2020-12-14 at 13 18 41](https://user-images.githubusercontent.com/3097461/102080873-87e07d80-3e0f-11eb-9c05-192dace4cbaa.png)

## Possible Solution

CSS Wizardry of level 3 or higher.

## Steps to Reproduce

1. Go to https://backstage.io/docs/overview/what-is-backstage
2. Hover over any heading, for example Benefits
3. Notice that there's no link icon on the left side, visually, but that it actually exists and is clickable etc (but black so it can't be seen on top of the background)

**Comment by AdnCodez** [comment]
This is a pretty large project, so this easy fix wouldn't deserve a PR,
`h2:hover .hash-link{
  opacity: 1
}
.hash-link {
  fill:white;
}`

**Comment by freben** [comment]
PRs are how the fixes get in :) Do you want somebody else to make the fix?

**Comment by AdnCodez** [comment]
Okay assign it to me I will get to it ;)
  

  

  

  
  
  
  
  
>

**Comment by AdnCodez** [comment]
The prettier check did pass locally after the `yarn prettier --write filename` command hover the PR code check did not, I am not sure how to solve this.

**Comment by adamdmharvey** [comment]
@AdnCodez You're super close.  So the code you checked in is "not pretty".  So when you ran the `yarn prettier --write filename` command locally, it would have rewritten the file. Once rewritten, you then need to commit and then push that change back up into your pull request. I believe it's very simple - you're just lacking a space between the `.hash-link` and the opening curly brace `{` in your pull request.

So your PR failed because the code you submitted isn't pretty still.

Does that make sense?
