### ISSUE TITLE
catalog model: introduce the System, Domain, and Resource kinds

### ISSUE THREAD

**Issue by freben** [backstage/backstage#3765]
## Feature Suggestion

Before removing the alpha label on the catalog, I think it would be sensible to have at least the `System` and `Domain` kinds in place, and preferably also an outline of `Resource`, as defined in [the system model RFC](https://github.com/backstage/backstage/issues/390).

## Possible Implementation

I would argue that there is value in adding these in a very barebones manner, and iterate. What we need is:

- The skeleton of the kinds themselves
- Adding `system` and `domain` fields in the relevant `spec`s of various kinds where appropriate, such as `Component`
- Defining the relations that the `system` and `domain` fields translate to, probably new ones along the lines of `partOf`, since the [existing ones](https://backstage.io/docs/features/software-catalog/well-known-relations) don't seem like a great match.

## Context

See the following RFCs:
- [Backstage System Model](https://github.com/backstage/backstage/issues/390)
- [On specific semantic of systems, components, and resources in Catalog](https://github.com/backstage/backstage/issues/2898)

**Comment by tragiclifestories** [comment]
> I would argue that there is value in adding these in a very barebones manner, and iterate.

FWIW I agree with this strongly. A `System` spec that simply served as a container for related components would be a significant value add for us.

**Comment by Sinjo** [comment]
Bringing the discussion over from #3726, I'm curious if modelling a monolithic service (specifically: a single codebase, built into a single deployable unit, with distinct owners of different parts of that codebase) came up at Spotify, or if you'd long since left anything that monolithic behind by the time you built Backstage.

My understanding is that `System` is typically used to model a group of microservices that perform strongly related functions. In our case we might end up with it mostly meaning that (for new services we're building), but in one case also representing the monolith.

If Discord is a better place for this sort of discussion then I'm more than happy to move there instead.

Context: I'm in the same team as @tragiclifestories.

**Comment by Fox32** [comment]
We from SDA SE are looking froward to the initial implementation of `System` and `Domains`. If you are interested, we can offer to contribute them (both not before 04.01.2020).

**Comment by tragiclifestories** [comment]
A question that occurs to me - is there an idea of what values might 'emerge' as well-known `type`s for these new kinds? I'm interested mainly in `System` since we want to use it to model a monolith that does not neatly decompose into vertical slice features as described in the existing documentation. So i see (possibly) `feature` and `monolith` or variants of that sort. 

Obviously for `Resource` you've got a more open-ended set of possibly useful values, queues, DBs, etc etc. I'm not sure types are meaningful for Domains.

**Comment by andrewthauer** [comment]
@tragiclifestories - I think `feature` and `monolith` could be well known types for a `System` entity. I'm wondering using the term `bounded-context` might also be worthwhile to consider. There could be some other identifier or classification, like what type of feature. Although maybe the `name` or `description` fits that.

As for domains, I could see `type` being useful to provide a higher level categorization (e.g. `platform` is of type `instrustructure`). Highly subjective per org, but I can see it being useful.

**Comment by freben** [comment]
@mbruggmann I think this interests you!

In the legacy internal catalog, systems aren't typed. And there were Components typed for example `feature` that were a part of a larger whole, such as a client `app` Component. So they were both components, and their relations were only ad-hoc and not necessarily clearly hierarchical.

I had actually not considered yet whether to add types to Systems here. Let's ponder it.

For starters: The types are there for a reason, not just as documentation. They are expected to change the behavior of the entity, and how it's represented in the interface, and what plugins that apply to it. And the Domain and System concepts aren't meant to necessarily convey hierarchy, but are cross-cutting grouping mechanisms.

Let's say you start out with a new webpage. You make it a Component of type `website` and it shows typical website related plugins in Backstage. Over the coming years it grows and sprawls, and you migrate it to become a larger monorepo with split ownership. Would you now change it to be a System instead? I am not sure you do.

The [system model](https://github.com/backstage/backstage/issues/390) says:

> For example, a playlist management system might encapsulate a backend service to update playlists, a backend service to query them, and a database to store them. It could expose an RPC API, a daily snapshots dataset, and an event stream of playlist updates.

But it may also contain the webplayer playlist views, and the corresponding ones for mobile clients etc. And while a `playlist-view-ios` is clearly a Component, perhaps of type `feature`, what is `client-ios` the monorepo? I think that's a software Component too, perhaps of type `app`? It definitely consists of code like components do, and builds and deploys like components do, and has monitoring needs etc. It may use an Apple app store Backstage plugin for some of those.

I think that mostly covers the type needs, in terms of being able to make effective use of these entities in Backstage. That makes it sound like maybe System does not necessarily need a type?

Note also that Domain explicitly calls out the term "bounding context".

**Comment by freben** [comment]
I forgot to add:

We still want to see relations between monorepos and their constituent parts. Maybe there's a place for `spec.partOf` and `relations.isPartOf` + `relations.hasPart` or similar that gets generated from our

**Comment by tragiclifestories** [comment]
Thanks @freben - interesting to see what Spotify had done with this. You may be right and the monolith question is better modelled after all. To put it crudely, I want there to exist a page where I can see all the 'bits' of my monolith in one place, above all else. 

But there are also runtime concerns proper to the monolith itself as a whole - eg, error reports which are impractical to decompose reliably. So we'd reached the hypothetical solution of the 'set that is its own member', ie, a `System` that contained a component specifically to represent those common concerns. With a component/subcomponent relationship no such hack would be necessary, of course, and then we could use `System`s as intended rather than extending their semantics as I previously proposed. In which case I could bring https://github.com/backstage/backstage/issues/3726 back from the dead or turn it into a RFC for monolithic components or something ...

**Comment by freben** [comment]
Oh absolutely, the ability to gather and display data like that is imperative. Sometimes it's tempting to take the shape of such core/important  data and use as inspiration for how to model the catalog, but it may sometimes lead to a worse overall design.

I think it can't be overstated how helpful it is to be able to show in a small widget on a component page,

```
Part of
  [mobile icon] client-ios
  [system icon] playlist
  [domain icon] end-user
```

Just that bird's eye view and quicknav to the place where for example you can see those error reports. Great first step.

Then, breakdowns like for those error reports - that is one of those places where the interaction with the catalog can come to shine. As a longer term investment, maybe you build a backend plugin that regularly based on the properties/hierarchy of components in the catalog, and tags in the bulk imported source data, can produce digests with pertinent summaries and trends, cached and ready for fast display in the frontend, on the particular sub-entities that they apply to.

For a mobile app, the same could be valid for release trains - "how many of my users are exposed to this version of my particular plugin at this point in time?" That kind of analysis and dissection and association of data (that otherwise might feel like it "belongs" on the parent monorepo) is something that we love to work with.

If somebody made a rich apple app store plugin, then for sure it should be extended with monorepo awareness (based on the catalog model for it).

**Comment by mbruggmann** [comment]
Agree that there is a need to cover an entity that acts like a bag of components, for example for a mobile app that contains independently owned features. The proposal we ended up with internally at Spotify is to add an additional concept we call **Application**.  It's defined as follows:

An application is a bundle of components that is packaged, released and operated as one unit. Compared to a system, an application might host components that belong to different systems or are owned by different teams in addition to its own components. Typical examples would be our mobile applications or the Backstage frontend.

I'd be careful to map applications 1-to-1 to repositories though. A single repository might still contain multiple services for example which, in turn, might be composed of multiple components. As such, maybe we should think about how we represent source repositories as well, since that is where certain plugins most naturally attach to (eg CI/CD, commits, developer permissions) rather than to individual components, systems or applications.

**Comment by freben** [comment]
@mbruggmann Right.

does that risk weakening the Component concept? See the discussion above of a website starting its life as a component and ending up as an application when it grows. This changes its kind/namespace/name identifier, and hence urls and references everywhere.

Or do we dive head first into applications and choose to always model websites, services and client apps as applications from the get-go? If we do, and that's OK if we do, I think we need to clearly adjust messaging and docs etc.

**Comment by tragiclifestories** [comment]
I think we've moved beyond the point that this discussion is directly related to this issue so I've raised https://github.com/backstage/backstage/issues/3815 as a strawman proposal specifically focused on modelling monolithic apps.
