### ISSUE TITLE
[Plugin] Splunk On-Call (formerly VictorOps)

### ISSUE THREAD

**Issue by nirga** [backstage/backstage#3790]
## Summary

Create a plugin for VictorOps, similar to current [PagerDuty implementation](https://github.com/backstage/backstage/tree/master/plugins/pagerduty)

## Project website (if applicable)

https://www.splunk.com/en_us/investor-relations/acquisitions/splunk-on-call.html

## Context

We are using VictorOps as our on-duty rotation manager so it will be useful to integrate it into Backstage.

**Comment by ayshiff** [comment]
I would love to work on this 👍

**Comment by freben** [comment]
Assigned, thanks!

**Comment by ayshiff** [comment]
I started working on the plugin and I'm almost done. I will do a PR in the coming days.

I just have one question to ask about the context in which the plugin is used. I don't think you can associate the plugin to an entity like Splunk-On-Call doesn't have a "services" system like the one of PagerDuty. We only get an api-key and an api-id that allow us to do operations at the organizational level.

What we could do to counter this problem is to define that one service = one team. And then use the team system to simulate our services.

Having never used Splunk-On-Call before, I am discovering some concepts and I would like to get your opinion on what you think is good practice and what you think is the right solution to follow. Thank you!

**Comment by Rugvip** [comment]
Not knowing exactly how splunk on-call works, but if it's like pager duty I'd say it's important to associate teams in splunk with components in the catalog, assuming such teams exist. This can be a N-1 relationship though, with multiple components being linked to the same splunk team. The important bit is that someone that want to send a page is able to go to the component page and do so there.

Apart from paging I think any other data could be exposed via group entities, if that's a mapping that makes sense
