### ISSUE TITLE
[RFC] Represent monolithic applications as components

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#3815]
**Status:** Open for comments

## Need

The existing catalog model is well suited to microservice architectures, particularly when the as-yet-unimplemented `System`, `Domain` and `Resource` kinds are added in. However, not all architectures fit this neatly. For example:

* Monolithic backend applications are common in the industry
* Mobile applications are typically shipped as single, feature-rich artifacts

The distinctive features that require modelling in this case are:

1. *Common runtime*. Monolithic applications are deployed as a single unit, and share runtime behaviours (for instance, observability instrumentation, database connection pools, etc). 
2. *Complex structure*. There may be no one 'good' way to divide up a monolith conceptually. It may expose several APIs; it may have distinct subsystems that operate as _layers_ rather than 'slices'; it may have features that are not easily expressed as APIs; etc.
3. *Complex ownership*. As companies scale, understanding what team is responsible for what functionality in a large application becomes important.

## Proposal

Implement `application` as a new `type` of `Component`. Application is apparently a concept internally in Spotify:

> An application is a bundle of components that is packaged, released and operated as one unit. Compared to a system, an application might host components that belong to different systems or are owned by different teams in addition to its own components. Typical examples would be our mobile applications or the Backstage frontend.

The crucial change to the `Component` model will be the addition of new relationships - a `Component` may be *part of* another; a `Component` may *contain* many others. So a YAML may look like:

```yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-ios
spec:
  type: application
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-ios-telemetry
spec:
  type: service # or whatever
  partOf:
    - component:acme-ios
    - system:foo-bar
```

I've proposed a many to many relation here so a Component may also belong to a System - the semantics of the relationship are substantially the same. 

## Alternatives

**Implement Application as a separate Kind.** Rejected because most of the actual functionality we want is common with other components - ie, runtime information like error reports, dashboards, etc. Implementing as a new Kind would increase the complexity of plugins that wanted to support all sorts of running software. 

**Model as a type of System**. Rejected because it semantically overloads System too drastically. A monolithic application may contain many systems, and indeed may contain _parts_ of systems. See discussion on #3765.

## Risks

The risk is that it's not actually a good fit for the applications it proposes to model and it will be difficult to change as and when the wider ecosystem adopts it. I don't see how you can manage this risk except by maintaining a humane deprecation policy with clear migration paths if changes are necessary.

**Comment by freben** [comment]
See for sure the continuing discussion in #3765 that may tip the scales in favor of an Application kind after all, if we make sure to understand the implications.

**Comment by tragiclifestories** [comment]
I'm easy either way, delta my specific point above. Just thought it would be good to have something concrete to talk about.

**Comment by mbruggmann** [comment]
Thanks for writing this up @tragiclifestories. I haven't really thought about it too much at this point, but I'm not entirely convinced that a separate Kind for applications is a bad idea. Maybe I'd rather do it this way:
* Have certain plugins that are attached to application kinds, like mobile releases
* If you need those plugins, you need to add an entity of that kind to the catalog. If you also want to link other components to it (so you can traverse from a component to its application, or inline some plugins on the component page), you'd need to annotate the component with the application it belongs to.

It's true that it might make it more complex for plugins that need to work for both components and applications though. How coupled are those things in the code at the moment? Like, would it be difficult to write a plugin that works for any entity in the catalog that has a given annotation?

**Comment by freben** [comment]
@mbruggmann For a small single purpose app / webpage, would you represent it as only an Application, or as both and Application and a Component?

Enabling features/plugins has been done a lot with annotations so far. It won't make an overly large difference to enable them for more than one kind.

**Comment by mbruggmann** [comment]
@freben Not sure. But I think it'd be convenient if in most cases, it's only a Component until we want to share a plugin across components in different systems (say, mobile releases). In which case we'd add an additional Application entity, and associate the existing component with the new application? That would allow you to move certain annotations from the Component to the Application, and with it, the plugins that make more sense in that scope?

**Comment by andrewthauer** [comment]
It sounds to me like both components and applications could be the same thing. Most of the scenarios described, just shift responsibility of plugin features from a more specific part to a grouping of parts. Could both of these not just be Component kinds? An Application in this case is just a Component that is made up of other components and has had some plugin features transferred to it (eg CI/CD, Releases, etc.).

**Comment by freben** [comment]
The alternative then, would be to make it an Application from the start - that will suddenly become one of the most common kinds. And it stays that way; Components mostly come into play when you feel the need to add the detail of multiple `feature`s inside it.

But then, is an SDK an Application? :) Etc. But that classifying problem applies for types too.

**Comment by freben** [comment]
@andrewthauer Yep that rhymes well with my initial take and @mbruggmann's latest edit. Just want to taste the other approach for a bit before we reject it :)

So let's say we are a user that wants to start making a trading website.

We use the scaffolder. It leads to a `website` Component right? We name it `stonks`. People link to it in docs, make browser favorites, there are refs to it in the catalog, it cements itself. Then it grows and sprawls and teams are spun off to manage different subsystems.

Here's the point where I feel it's important that the original entity stays and has a similar role in the world. Reclassifying established entities is an expensive operation in an org. Therefore I think we should NOT put the owners in a position where they need to (1) remove the entity, (2) change its kind, (3) change its name, (4) change its purpose so much that its original intent is lost which leads to everybody wanting to link to the other one instead.

Therefore I propose that we make the original classification of an app or website "robust" and unchanging, in the face of monorepoization.

If we make a monorepo an "application" TYPE, do we lose the ability to discern between the original types `website` and `service`?

**Comment by freben** [comment]
@andrewthauer Read your comment again - maybe that's exactly aligned with what you said? (I edited my comment a bit if you missed that last paragraph)

**Comment by freben** [comment]
@mbruggmann obviously i would love to hear your take on that thought, and whether that aligns poorly with what you had in mind for the internal model

**Comment by andrewthauer** [comment]
An SDK seems more like a library, which could be associated to other entities. It could very well encompass multiple services and APIs.

I'm not sure I'm too keen on the term Application for this. For me it implies something that is for end users. But what we are talking about to here is how to enable/disable certain features within backstage based on the composition of arbitrary things. The problem is each organization can structure and conceptualize how these fit together in different ways.

Not sure if this is relevant to this discussion, but some examples we have are:

- Various micro frontends and an older monolithic frontend app that composes these. All are different repos, but need to be deployed as a single unit.
- Mobile apps that are split by feature/product category. These don't necessarily map 1 to 1 in the web version exactly.
- Services that are broken down into multiple packages and deployed as a separate unit
- An older monolith that contains remnants of features in newer microservices.

Having flexibility in the model and also being able to de-couple the conceptual and physical representations of these is key I think.

**Comment by freben** [comment]
@andrewthauer Do you feel that the simple `partOf` relation is enough for those listed examples? I think for a human they may be. If it were meant to like drive a CI/CD system it wouldn't be detailed enough, but that's not the goal.

**Comment by andrewthauer** [comment]
I think `partOf` could work with all of them actually. All the examples except the micro frontends are single repos now so most existing plugins work fine modelling them as a single component. If `partOf` were introduced we could further break down some of these if we chose to. This would also help with associating the micro frontends to their parent web app. However things like releases or deploys would only be applicable to the parent web app.

**Comment by mbruggmann** [comment]
@freben Another approach to robustness would be to rely more on systems, and making those the primary entry point for techdocs, urls, search, APIs etc. Because components will likely evolve quicker over time.

@andrewthauer Agree that some flexibility in the model is crucial. Maybe we can be stricter about the core entities (Components, APIs and Resources), while leaving the classifications/groupings (Systems, Domains, Applications, ...) for each organization to define as they see fit?

**Comment by freben** [comment]
> @freben Another approach to robustness would be to rely more on systems, and making those the primary entry point for techdocs, urls, search, APIs etc. Because components will likely evolve quicker over time.

That's a valid point. There's a bit of a mind shift for me to think of Systems as a more central thing.

Hm but the concern of making the unit of deployment and monitoring etc stable (especially if others key into it) still stands I think.

> @andrewthauer Agree that some flexibility in the model is crucial. Maybe we can be stricter about the core entities (Components, APIs and Resources), while leaving the classifications/groupings (Systems, Domains, Applications, ...) for each organization to define as they see fit?

Maybe. However we encode a lot of best practices in how we do things I think, such as how we create our default templates and how plugins by default look at deployment units etc.

**Comment by tragiclifestories** [comment]
I think the point about persistent linking between entities is a good one - it hadn't occurred to me. But it's a problem with this sort of ontology that they tend to capture particular moments and getting from one state to another is sort of undefined behaviour. We should definitely bear it in mind when defining these core types. 

For my purposes, not having an _explicitly supported_ application type in the core model is probably alright? Since a quick'n'dirty plugin would do the job of making my lovely monolith discoverable with minimal effort. 

But I think it might still be worth considering, simply for 'exhaustiveness' - ie, the point of adding support for subcomponents is to support monolithic applications of one sort or another, so we need _some_ value or set of values that we can put in the `type` field other than `service` and friends. Plugins might extend that with, say, an `ios-app` type or whatever, in the same way that you could maybe have variants of `service` with platform specific behaviours (or whatever else). But in the core model you would have the fallback of the ultra-abstract, unopinionated `application` type.

**Comment by GoWind** [comment]
Too many high level "Kinds" would be IMHO, confusing. The way I would approach is to provide the minimum set of building blocks as Kinds and allow organizations/users to put them together to build the model as they see fit. 

The way I see it, a monolithic runtime is still a component, that falls possibly under a system. Each runtime feature / library can be components that are children of that system , with the "application" component depending on the features/libraries.

As for "partOf" relation, I wonder if we can achieve the same relation with the existing  "dependsOn" and "dependencyOf" relationships. 
In the example of micro-frontends to a frontend, we can model the frontend end has "dependsOn" relationship with the micro-frontends. 

Similarly, while it might theoretically be possible to run a micro-frontend by itself, I am doubtful, if they are deployable by themselves (standalone). In such a case (deployable), we can have a one-way link "dependsOn" rather than a 2 way link ( a weak link) to convey that a micro-frontend is a part of a frontend. In the case it isnt, a 2 way relationship will imply that they both need each other to be run together. 
 
As for SDKs, a SDK might  be used by a lot of applications so in such cases a dependencyOf relationship from the sdk to the other components might not even make sense as there might be too many (making it a Directed acyclicl graph).

I think we have sufficient primitives to allow users to model their software ecosystem as they see fit. Rather, the confusion might be on ideas of how to use these primitives to model their software ecosystem. Perhaps this can be addressed by having docs  (Examples, User Guides etc) for users on how to model their domain to fit into backstage, rather than introducing a new relation or a Kind ?

**Comment by freben** [comment]
> Too many high level `Kinds` would be IMHO, confusing. My approach is to provide the minimum set of building blocks as Kinds and allow organizations/users to put them together to build the model as they see fit.

This is a nice way of putting it!

With the caveat that we as makers of Backstage want to hit the just right level of opinionated, where we supply enough clarity and functionality out of the box to be immediately useful - even powerful - while also permitting extensions to that model. The main reason for that baseline need, is that we want plugins made by entirely different third parties to be able to work well together. The catalog is a form of universal "API" across several domains. Inventing one's own kinds and types and annotations etc is great - but sometimes undermines interoperability because others won't understand your semantics. It's all a tradeoff.

> **The way I see it, a monolithic runtime is still a component, that possibly falls under a system. Each runtime feature / library can be components (with type: `library`, `feature`, etc) that are children of that system , with the `application` component depending on the features/libraries.**

Let's see.

<img width="458" alt="Screenshot 2020-12-27 at 21 11 49" src="https://user-images.githubusercontent.com/3097461/103179008-2f39c780-4888-11eb-92f9-db9656b94991.png">

Like that?

> As for `partOf` relation, I wonder if we can achieve the same relation with the existing `dependsOn` and `dependencyOf` relationships. **My reasoning behind this is that even if the claim is that a feature/sub-component that is not a part of the application, but is still run in the common runtime, is sort of a dependency, as your runtime will not function as expected if this sub-component is missing** (a connection pool that is a `partOf` runtime A => A has some sort of `dependency` on the pool, otherwise doesn't make sense to have a partOf relationship).

It's a balancing act between not having too many relation types, and risking things becoming muddled or colliding. Have too few, and you'll either get it linguistically unclear, or start getting tempted to add a "subtype" field to the dependency because purposes start overlapping :)

I guess that essentially, one could argue that the existence of a relation in and of itself is saying "dependency", and the type of relation is, well, the type. Are you saying that "type" could be omitted?

Another angle: As a yaml file writer, would you like a spec to look like the first or second example?

```yaml
# specific
spec:
  system: mySystem
  domain: myDomain
# generic
spec:
  
```

> I have a few other examples for why `dependency` is sufficient.

Let's look for counter examples too!

> 1. In the example of micro-frontends to a frontend, we can model the frontend end has "dependsOn" relationship with the micro-frontends.  Similarly, while it might theoretically be possible to run a micro-frontend by itself, I am doubtful, if they are ever deployable by themselves (standalone). In such a case (deployable), we can have a one-way link "dependsOn" rather than a 2 way link ( a weak link) to convey that a micro-frontend is a part of a frontend. In the case it isnt, a 2 way relationship will imply that they both need each other to be run together.

Fair regarding how one might look at their interrelation. However, we have so far considered relations to be meant to be two-way to allow clear traversal both in the user interface and as an API consumer. Maybe this one-way idea could be a sign that the semantics are stretched a bit?

> 2. SDKs: Components or applications that use SDKs do depend on them. So in this case, a `dependsOn` relationship makes more sense.

Yep. But do you mean specifically a situation where the SDK is in the same monorepo as the main user? But others outside the repo use the SDK as well I presume? Does that mean that you can't discern the difference between depending on the SDK based on usage, and depending on the SDK based on it being part of your actual codebase?

Could it be that the inside-the-same-repo semantics could be TWO relations (both partOf and dependsOn), but the external user just dependsOn it? Is that richness useful?

> 3. Another example is a  "Shopping Cart" feature, that is `ChildOf` of the "WebStore" `system`, but  "Webstore Application" has a `dependsOn` relationship with "Shopping Cart".  Both "ShoppingCart" and "Webstore Application" are children of "Webstore". If you want to be more nuanced you can have a "Shopping cart Tab" micro-frontend and a  "Shopping Cart backend" that implement "Shopping Cart" (`dependsOn` -> Shopping cart tab, shopping cart backend). I dont think a Shopping Cart feature itself would make sense, outside the content of the Webstore, so you might end up modeling the "Shopping Cart" as `childOf` "Webstore"

I think this slices things differently to what I'd expect - but maybe I'm misreading it.

To be clear, a system is an entirely different grouping dimension than the usage "grouping".

I would expect that if there is a `shoppingCart` _System_, then it would be a grouping of some backend, several frontend features, some (e.g.) Cassandra storage resource, some pubsub topics, some batch data pipelines that are used for financial reporting, a realtime data pipeline for fraud detection etc. They would be `partOf` that system, not `childOf`. Note how extremely diverse these entities are. It will be important to users to be able to see them collected as a unit, to understand how they relate and are owned, and to know if alerts/problems spread among them. This is a type of "umbrella" that I think has big implications and we care a lot that it's distinct and useful.

I don't know if a `webApp` _System_ would have any relation to the `shoppingCart` _System_. It would be a kind of transitive dependency and we haven't looked at modelling that yet.

However components under these systems may relate.

- If the shopping cart has a micro-frontend component in it, then the webstore may have a dependency on that one.
- If the shopping cart frontend parts are like a plugin in the webstore, and importantly, if responsibility for that part lies on the team that owns the webstore, then maybe that webstoreCart component is actually inside the webstore system and depends on the shopping cart backend
- If the shopping cart frontend code is more integrated in the webstore and hasn't yet gotten its own component, then then webstore itself may have a dependency on the shopping cart backend.

So it kinda depends. But I think of it in terms of `partOf` for component<->system, and `dependsOn` for component<->component here. I think both feel important and distinct.

> **I think we have sufficient primitives to allow users to model their software ecosystem as they see fit**. Rather, the confusion might be on how to use these primitives to model their software ecosystem. Perhaps this can be _addressed by having docs (Examples, User Guides etc) for users_ on how to model their domain to fit into backstage, rather than introducing a new relation or a Kind ?

Oh yes, docs are definitely in need of fleshing out over time, and we will. But the [extending the model](https://backstage.io/docs/features/software-catalog/extending-the-model) article does address some of these nuances.

> And just to get it cleared, I think custom "types" of "Components" are possible , right ? I recall adding Components with custom "types" to the database , but the only limitation seemed to be that they dont seem to show up in the UI, because the UI only queries for components of type Services ( which potentially can be customized in later versions of the frontend)

Yep this is mentioned in the [extending the model](https://backstage.io/docs/features/software-catalog/extending-the-model) as one of the most low hanging fruits on offer - we expect this extension possibility to happen frequently.

The catalog currently shows all Component kind entities (regardless of type). That will become richer and more fleshed out soon.

**Comment by GoWind** [comment]
> Like that?

Yes, that is what I had in mind.

> I would expect that if there is a shoppingCart System, then it would be a grouping of some backend, several frontend features, some (e.g.) Cassandra storage resource, some pubsub topics, some batch data pipelines that are used for financial reporting, a realtime data pipeline for fraud detection etc. They would be partOf that system, not childOf. Note how extremely diverse these entities are. It will be important to users to be able to see them collected as a unit, to understand how they relate and are owned, and to know if alerts/problems spread among them. This is a type of "umbrella" that I think has big implications and we care a lot that it's distinct and useful.

This is where I am not sure of whether `dependsOn` or `partsOf` is a better approach. For a shopping system, what is the level to which it is coupled to the fraud detection data pipeline ? Is it a hard dependency (aka , pipeline down => system down ) OR a severe issue but not a down time ? Maybe I might model the first one as `dependsOn` and the latter as a `partsOf`. 

But I think as a platform/library, rather than second-guessing how people might model the system, it perhaps is better to provide them with the tools to create a different type of link.  
There is a lot of ambiguity between a `dependsOn` and a `partOf` relationship, but at this moment we do not know for sure when to use what. 
As a pragmatic approach, we can perhaps generate a new type of relationship for users (`partsOf`) and allow them to use it as they see fit. 

I guess the problem might occur when a core plugin or component uses one certain relationship for a certain functionality and latter it is decided that this relationship has to be moved to the other.  Perhaps this can be solved by not using `partOf` to provide any functionality in the core plugins ?

**Comment by tragiclifestories** [comment]
For me, using dependsOn would introduce potentially confusing overloading there. Real-ish life example: we have an intwernal Ruby gem that does structured logging according to our favoured samples. Our monolith _also_ some related layers for logging request data, job data, etc. I'm not sure I want to see both types of 'dependency' listed in one place. Also, maybe it's just I need to finish this coffee next to me, but I don't feel like I have a good intuition for which direction the arrows go between (in your example) the micro-frontends and the 'host' application, whereas it's very obvious in the case of `partOf`/`parts` (or, for that matter, `parent` and `child`).

> Perhaps this can be solved by not using partOf to provide any functionality in the core plugins ?

This might be a good idea. It would allow us all to get started modelling and see if we push in the same direction and then in a future version of the catalog more opinionated approaches to this problem might build on that.

I _think_ we're agreed that we want `partOf` anyway for `component->system` relationships, and merely not forbidding `component-(partOf)->component` would be sufficient support for work to start in the wider ecosystem.

**Comment by freben** [comment]
I second the confusion.

Still leaning towards the "not forbidding" part at least being strengthened to "encouraging", and probably even settling entirely. This may be one place where being opinionated may help long term, is my thinking.

Consider this from the maintainer point of view:

We will have to update the [well-known relations](https://backstage.io/docs/features/software-catalog/well-known-relations) page with examples and instructions. It'll be hard to do that in a useful and clear way without having some direction for the relations and their use.

We will also have to update the [descriptor format](https://backstage.io/docs/features/software-catalog/descriptor-format) page with the corresponding `spec` fields that ultimately generate the relations. How will we do that while saying "this may generate some form of relation (which is the way that we want everybody to consume this info), but not sure which one"? :)

We will also want to put the actual relation-generating code in the [BuiltinKindsEntityProcessor](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.ts#L106). Whatever we put in there will be VERY cemented and, while you could replace the processor with your own, it would be a pretty big thing to do (and to evolve with as things are added to the core one).

Not sure about the ergonomics of leaving this flexible, if you think about it from the angle of the large masses of adopting orgs.

**Comment by tragiclifestories** [comment]
I wonder if there's a little crosstalk going on here - I didn't take @GoWind to mean that we wouldn't process the specs into relation records in the core plugin, merely that building actual user-facing functionality around it could be left out (maybe I misread it myself). I think the latter could be at least deferred until later on and we can experiment a bit in the wider ecosystem.

I think I agree with you that the minimum viable core support would be to update the docs you mention, add the field(s) to the component spec and process the relations in the `BuiltInKindsEntityProcessor` (I've started toying around with that [here](https://github.com/tragiclifestories/backstage/tree/component-partof) FWIW).

**Comment by GoWind** [comment]
> We will also want to put the actual relation-generating code in the BuiltinKindsEntityProcessor. Whatever we put in there will be VERY cemented and, while you could replace the processor with your own, it would be a pretty big thing to do (and to evolve with as things are added to the core one).

Getting this right (or keeping this flexible) would be very important. Currently, I run into a lot of limitations with generating relations when I try to emit them myself as the HigherOrderOperations prevents Location Processors from emitting any relations in the Entity. 

@tragiclifestories 
My question was more along the lines of what EXACTLY is the distinction. between partOf and dependsOf/dependsOn would be, as I am still not 100% sure of when I would use the former vs the latter and is the extra relationship in the model justified. 
If a new relationship were to be added, some opinionated rules might be involved in deciding what relationship it is. 

But I think, since we haven't reached 1.0 yet, maybe it does make sense to allow the new relationship, gather concrete examples of how to use one vs the other and then decide on retaining both or having just one.

**Comment by tragiclifestories** [comment]
@GoWind sorry for delay, thought I'd already replied but obviously not!

For me, something is part of something else if its whole existence is enclosed by the larger aggregate, whereas a dependency implies some kind of 'independent' existence. Examples:

1. Service A **depends on** Library B, since if that link was broken, Library B could equally well be included in any number of other Services. (Although we have a distinct relation type for API dependencies, I think they are closely analogous and I think especially `consumesApi` could be replaced by `dependsOn` more easily than the part/whole relations proposed here.)
2. Service* A **is part of** Monolith B, since it has no possible runtime existence apart from the monolithic deployment.
3. Service A **is part of** System B, since its existence is entirely unnecessary apart from the feature implemented by System B.

In my head, partOf is one-to-one _per kind_, ie, a Component should be part of at most one Component and/or at most one System, etc. I'm sure organisations will find that these rules must be bent now and again as they iterate towards a more 'rational' model.

@freben don't know if you'd have any other thoughts. I'd like to get moving on this really (got an MVP to build for alpha users), so if we could decide which relation pair to use I can get a PR in at least for the catalog backend and model parts pretty quickly. Frankly I can see a use case for having *both* these relations supported in the Component spec, but obviously we still need to hash out the nuances of what the differences are.

\* leaving aside whether 'service' is the appropriate type for this.

**Comment by freben** [comment]
I'm good, and in the camp of using `partOf`, and `hasPart` as the inverse. I'd be happy to review a contribution for it.

We are now more and more, as was noted above, essentially making relations significant as a `[type, target.kind]` tuple. The target kind affects what the relation "means" in a technical sense, even though it commonly doesn't affect what it means from a high level human interpretation standpoint. I think this important realization is part of the basis for making this one distinct from `dependsOn`.

Do note that related work is happening in https://github.com/backstage/backstage/pull/3957, which settles the `partOf` and `hasPart` relations, but in terms of component<->system, and system<->domain. It is likely that that PR lands very very shortly.

**Comment by tragiclifestories** [comment]
Awesome - my branch I think is more or less ready to go so I'll tidy up and make sure it fits around #3957.

**Comment by GoWind** [comment]
@tragiclifestories 

> For me, something is part of something else if its whole existence is enclosed by the larger aggregate, whereas a dependency implies some kind of 'independent' existence. Examples:

This makes a lot of things clearer. Yes, partOf signifies a sort of non-independent existence/.
Now that I see it from this perspective, I am inclined to add this type of relationship to Backstage as well :) 

As for consumesAPI, i think it is ok to have it as a defined relationship type as APIs are first class .

**Comment by tragiclifestories** [comment]
> As for consumesAPI, i think it is ok to have it as a defined relationship type as APIs are first class .

For sure - was just drawing the analogy there really.

**Comment by freben** [comment]
And now #3957 is merged!

**Comment by Rugvip** [comment]
Thanks you @tragiclifestories and everyone else that contributed to the discussion! I feel that with #3957 and #4031 merged we're ready to close this, with any followup e.g. UI changes being handled in new issues.

Happy to close it?

**Comment by tragiclifestories** [comment]
Sure thing - thanks everyone for sharpening this up!
