### ISSUE TITLE
Catalog-import adds component without confirmation

### ISSUE THREAD

**Issue by jvilimek** [backstage/backstage#3971]
in Catalog Import wizard the component is added before user confirms (it is added while review)

## Expected Behavior

1. Go to https://xxx/catalog-import to add a new component
2. enter the url
3. hit next (you should now see the review of the component)
4. cancel the wizard (navigate elsewhere)
5. component is not added

## Current Behavior

1. Go to https://xxx/catalog-import to add a new component
2. enter the url
3. hit next (you should now see the review of the component)
4. cancel the wizard (navigate elsewhere)
5. witness the component was added

## Possible Solution

create the component in the database only after the review by the user is done.

## Steps to Reproduce

see above

## Context

Before I was able to use "/register-component" where was a button "validate". After a hit the component was not added (I believe!) but only validated and only after I hit register the component was added.

## Your Environment

Before we were using 0.4.3 version of backstage bundle, where there was plugin-register-component 0.2.6 and when using /register-component path it worked as expeted (old style with validation)
Broken version: 2021/01/07, the above component was changed to plugin-catalog-import 0.3.3 which is I believe broken

- NodeJS Version (v12): v12.19.1
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 20.04
- Browser Information: Chrome 87.0.4280.88

**Comment by Fox32** [comment]
Yeah that's feature is not available in the new import plugin. The API already allows to dry run the operation. 

I would second the expectation to have a step to review the data. There is a step called review that somehow implies that you can do that, but the import happens directly after the first click on next. In general I think the button descriptions aren't good. Instead of "next" they should describe what action happens next.

**Comment by jvilimek** [comment]
Works now, thanks!
