### ISSUE TITLE
[TechDocs HomePage] Owned Documents

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#4103]
This is a sub-issue out of #2028. 

On the TechDocs HomePage, a new Tab should exist with the text "Owned Documents". When a user clicks on this tab the following should get displayed. 

* Empty state if users don't have any documents, see picture 1.
* Once users have their own docs, they can see a table similar to the table in picture 2.

<img width="909" alt="Screen Shot 2021-01-15 at 3 29 20 PM" src="https://user-images.githubusercontent.com/25153114/104739036-8a076600-5746-11eb-9ef5-0b0d22a49a69.png">

<img width="833" alt="Screen Shot 2021-01-15 at 3 31 55 PM" src="https://user-images.githubusercontent.com/25153114/104739308-d9e62d00-5746-11eb-9820-e1c90f636ac1.png">

**Comment by adamdmharvey** [comment]
My team just had a big internal discussion about this very topic this morning, so it's very top of mind for me!! 🤩 

My understanding of some of the nuances of tech-docs is still building, so pardon the question.  But today I understand I can have:

* Kind: `component`, owner: `group:myTeam`, annotation `backstage.io/techdocs-ref: dir:./docs`
* Kind: `documentation`, owner: `group:myTeam`, no annotation since it is a doc site?

So would the owners here show BOTH, documentation which exists under my owned service, but also a specific documentation site I might also own?  (one might be say the design guide for a product, the other being an end-user guide published separately)

**Comment by emmaindal** [comment]
Hey @adamdmharvey, thank you so much for this comment! My answer to it would be - yes, you should be able to see both:
1. entities you own of the type documentation (standalone docs entities)
2. entities you own, of another type, that has documentation.  (docs with code)

later on eventually also (but left out for):
3. if you are a CODEOWNER of let's say one documentation page of the entire TechDocs site.

**Comment by emmaindal** [comment]
and just to clarify: techdocs annotation always need to exist as it is designed now. 
So even if you have a standalone docs entity, it needs to have the techdocs ref in its yaml file.

**Comment by OrkoHunter** [comment]
Yep! Either a `url:/to/some/external/place` or a `dir:./` to indicate that docs and code are living together.
