### ISSUE TITLE
CheckboxTree doesn't seem exported, therefore is not usable in plugins

### ISSUE THREAD

**Issue by facos86** [backstage/backstage#4198]
CheckboxTree doesn't seem exported, therefore is not usable in plugins
https://github.com/backstage/backstage/blob/master/packages/core/src/components/index.ts

**Comment by adamdmharvey** [comment]
There are four (4) from that package that aren't exported. I won't claim to know why they were individually specified, and not `*`, but just throwing this in for awareness.  One of the core maintainers may have better context or know!

![image](https://user-images.githubusercontent.com/33203301/105445502-1da4cf00-5c3e-11eb-99a4-37818af394ee.png)

**Comment by freben** [comment]
We had a little library of things from the internal legacy Backstage that we ported over early on, to bootstrap the plugin developer experience. To be transparent, we still have on our to-do list to fully and carefully go through the offering here, and possibly extend or even prune it. As such, they are in a slightly varied state of well-being.

While it would be easy to just export the checkbox tree, I am a little bit hesitant because it becomes a contract and a commitment and maybe it could do with a slight overhaul or replacement before doing so. Effectively, it may be the case that it would be better to delete it short term and possibly reintroduce later, in a more deliberate effort. @backstage/maintainers WDYT? Is that an overly careful stance? :)

**Comment by freben** [comment]
Maybe what we need is a `@backstage/core-components-lab` that has always-alpha no-promises-made components in it that gradually can be graduated into core as they mature, à la material-ui lab.

**Comment by Fox32** [comment]
I'm not sure about the CheckboxTree in particular: That code could need a rework. I startet that (together with Select) some time ago, but never finished it.

**Comment by freben** [comment]
Oh sorry, I thought that was from internal. Yeah this isn't meant as a judgment on quality either way, but rather stating that I am concerned that we haven't yet had the time to go over the component library.

**Comment by Fox32** [comment]
`CheckboxTree` is still no exported
