### ISSUE TITLE
Add Same Filtering pane in Software Catalog to Software Templates

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4209]
It would be nice to add the same filter pane that is currently present in the software catalog to the Software Templates page along with the following changes:

1. Update 'Available Templates' header to 'Catalog'
2.  Add Search near catalog
3. Change TAGS header to Category 

## Possible Implementation

![image](https://user-images.githubusercontent.com/6157895/105428368-449ed900-5c1d-11eb-9289-7ffb76855413.png)

![image](https://user-images.githubusercontent.com/6157895/105428383-4c5e7d80-5c1d-11eb-8b45-b7d619a60aea.png)

**Comment by benjdlambert** [comment]
@katz95 there's also this for you to have a look at :)

**Comment by regicsolutions** [comment]
@katz95 i got the idea from the [kubeapps](https://kubeapps.com/) project incase you wanted to take a quick peek. The app is categorized by "Applications" and "Catalog" where backstage is "Catalog" and "Templates"  at the end of the day, in my opinion, it's really one Software Catalog for new and existing software components.

**Comment by mateiidavid** [comment]
@benjdlambert @regicsolutions we were actually discussing this last week in our team. We have quite a high number of templates at Expedia and we'd like to have some sort of search functionality without having to maintain a fork. We'd be interested to do the work involved here :) 

@exp-dev-dj maybe you want to have a look at this?

**Comment by david-2814** [comment]
@mateiidavid Thanks for starting the conversation! 

@benjdlambert @regicsolutions Like @mateiidavid mentioned, at Expedia, we have a good amount of managed templates that will require some sort of template search and filter functionalities.  To make Scaffolder more usable is as a matter of fact one of our top priorities in Q1.  We would like to have dedicated engineers from our team to help build out the feature.  Since this feature contribution is likely to involve design approvals from the Backstage OS community, it would be very helpful if you could provide some guidance how we (possibly 3-4 engineers) can work collaboratively with you and delivery this functionality.

**Comment by regicsolutions** [comment]
Excellent! @katz95 did you have a chance to review my proposed design?

**Comment by OscarDHdz** [comment]
> @mateiidavid Thanks for starting the conversation!
> 
> @benjdlambert @regicsolutions Like @mateiidavid mentioned, at Expedia, we have a good amount of managed templates that will require some sort of template search and filter functionalities. To make Scaffolder more usable is as a matter of fact one of our top priorities in Q1. We would like to have dedicated engineers from our team to help build out the feature. Since this feature contribution is likely to involve design approvals from the Backstage OS community, it would be very helpful if you could provide some guidance how we (possibly 3-4 engineers) can work collaboratively with you and delivery this functionality.


I will be the assigned person :D

**Comment by freben** [comment]
Done, thanks!
