### ISSUE TITLE
TechDocs: Use lowercase entity kind, namespace and name in URLs

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#4367]
## Feature Suggestion

When you open a TechDocs page like https://demo.backstage.io/docs/default/Component/backstage

The entity namespace (e.g. `default`) and kind (e.g. `Component`) and name should be in lowercase.

## Possible Implementation

Look at `/catalog` plugin for inspiration.

https://github.com/backstage/backstage/blob/8e1c7be11c916d95e9281914b98c59a79d0a1ada/plugins/catalog-react/src/routes.ts#L39-L46

**Comment by marcosnils** [comment]
:wave:  I was trying to give this a try but given my little understanding on backstage looks like the implementation is not trivial. 

Looks like the arguments that the tech docs plugin parses come from the URL here: 

https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/reader/components/TechDocsPage.tsx#L27-L33

If afterwards calls the tech-docs backend plugin here using that same arguments:

https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/api.ts#L83-L87

Finally, the techdocs plugin calls the catalog API to fetch the static docs URL the publisher uses to publish the docs here https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/service/router.ts#L202


Problem is.. that if we don't respect the capitalization on the URL, the publisher is not going to be able to find the static content since it's very likely that the underlying publishing target URL is also case sensitive. For what I see we have 3 options here

1 -  Remove the capitalization and make users re-populate their publish URL's (this will be a breaking change of this plugin)
2 - Use lowercase URL's in the front-end plugin and re-capitalize the kind and namespace  in the backend so the publisher can find the information
3 - Leave it as it is :D

Thoughts?

**Comment by adamdmharvey** [comment]
Closure of this potentially also closes https://github.com/backstage/backstage/issues/2269

**Comment by marcosnils** [comment]
> 1 - Remove the capitalization and make users re-populate their publish URL's (this will be a breaking change of this plugin)

Now that I think about it this won't be a breaking change right? Since documentation will get re-generated. The only downside is that garbage will be left since the old docs with capitalized URL's wont be purged.

**Comment by adamdmharvey** [comment]
@marcosnils could add a line for the cleanup to cleanup both the original URL and and old one, and mark it to be deprecated/TODO, such that it gets cleaned up at a later date maybe?

**Comment by marcosnils** [comment]
> Now that I think about it this won't be a breaking change right? Since documentation will get re-generated. The only downside is that garbage will be left since the old docs with capitalized URL's wont be purged.

Hmm just noticed this is only valid for the `local` builder generator. In that case yes, this will be a breaking change that we can't address within backstage since users will have to change their external generators to publish the docs somewhere else.

**Comment by iamEAP** [comment]
We took a look at this and here's our proposed path forward...

1. Create a migration utility (most likely a command in `techdocs-cli`) that will copy any objects in storage from case-sensitive triplet paths to lower-case triplet paths.
2. This migration utility will rely on a new method added to the `PublisherBase` signature (perhaps called `migrateDocsCase` or similar) which handles the logic on a per-storage provider basis.  (We may want to publish this in TechDocs common, followed by the `techdocs-cli` first, to allow time to advertise the change to the community and resolve any issues in the migration command)
3. We'll then update all publishers' `publish` and `docsRouter` methods to lowercase the entity triplet at read/write time.  In the release notes in this PR, we'll advise those who use external storage/generation solutions to run the `techdocs-cli` migration command prior to rolling out the release.  (As noted previously in this issue, folks running local generation will be unaffected)

One additional annoyance: MacOS's file system is case insensitive by default, so testing this locally on a Mac is challenging.
