### ISSUE TITLE
Kubernetes Operator for Backstage

### ISSUE THREAD

**Issue by jessebye** [backstage/backstage#4429]
Create a Kubernetes Operator for installing and managing Backstage deployments.

## Feature Suggestion

We use the operator pattern heavily in our Kubernetes clusters. It works great for complex deployments like Prometheus, where we can use CRs to manage the Prometheus configuration. Those CRs can be bundled into other applications (for example in a helm chart), allowing for easily adding to the configuration without needing to manage a massive central configuration file by hand. A good example of how we'd like to use this feature would be in our internal service helm charts:
- Each internal service we create uses a common helm chart that we've designed.
- The common helm chart could be extended with a Backstage CR that populates its `app-config.yaml` using values we already have in the helm config.
- When we create new services, they'd automatically be added to Backstage as components, with the appropriate metadata from the helm values.

Backstage could benefit from the operator pattern, using Kubernetes custom resources as a way to define the configuration of component types, app config, and other configurable properties. The operator would be responsible for watching these CRs and translating them into Backstage config (with automatic restarting of the backstage containers upon changes to the config).

## Possible Implementation

Some determination would need to be made about which CRs to support. Initially it could just support CRs for app config. 

A new repository or subdirectory of this repo would need to be created to contain the operator. The operator would need to be scaffolded with [`operator-sdk`](https://sdk.operatorframework.io/). Then the operator could be implemented, probably as a Golang-based operator.

## Context

This is a good example of what can be accomplished with the operator pattern: https://github.com/prometheus-operator/prometheus-operator

Operators are very common in Kubernetes as a way of deploying apps, managing the upgrade process, and managing their configuration.

**Comment by Crevil** [comment]
Interresting idea. From the description, I'm a bit unsure whether the operator is to manage backstage instances, ie. multiple backstage deployments, or if it is to collect entities for the service catalog of a single backstage instance?

We have an aggregator at Lunar that generates entities based on Git repositories. We thought about the operator approach to begin with, but it quickly became clear that we wanted to show applications over deployments, ie. a microservice over the environemts it is deployed to.

Bundling of a CR with the application would make us have to deploy backstage in a cluster along with the services. But as we have multiple clusters, eg. dev, prod, where would backstage run?

Long stort short; we now track applications (git repositories) and plan to have a daemon in our workload clusters tracking where an applocation is deployed instead.

**Comment by freben** [comment]
@Crevil What you say resonates a lot with me. It's very familiar from our experiences with Backstage internally. Your instinct to model the applications separately from their deployments is the right one. The runtime aspects of the faceted, changing world should be kept apart from the catalog, and "joined" in into the views in various ways. Being able to find an application, and to see all of its current and historical builds and deployments, and seeing their live statuses at this very instant - and, indeed, to be able to go in the reverse direction too from a troublesome pod in kubernetes all the way back to the component and the source repo and the owning team...

Your daemon would probably be consumed then by backstage, to provide realtime data into the views of catalog entities.

**Comment by Crevil** [comment]
Yes, that was the idea. 

Currently the aggregator merges all found applications into a Location respurce and commits it to a git repository which backstage watches.

**Comment by jessebye** [comment]
@Crevil @freben we ended up going a slightly different direction than the Operator pattern for our Backstage implementation. It sounds somewhat similar to what you did @Crevil - we wrote a catalog processor that scans our Git repos, parses out a few files to scrape the metadata, and emits catalog entries. The main difference is we use the catalog processor in Backstage, not a separate aggregator that commits files to Git first.

Now that we've gotten Backstage up and running in our Kubernetes environment, I'm debating whether an Operator would be all that useful. We ended up wrapping it in our own custom Helm chart and deployed with an AWS Aurora Postgres. But I imagine there could still be a use case for Operators to manage Backstage deployments. This pattern still works nicely to deploy an application that has multiple components and somewhat complicated configuration.

**Comment by Crevil** [comment]
That sounds like a better solution TBH. We should look into that as well.

Your comment brings clarity to the feature, then. It is about deploying backstage _not_ adding entries to the catalog. (Just to be clear though: an operator could provide entity CRDs as well)

To dig a bit further on this. What were the parts of your helm chart that made it complicated?

Operators are great, as you mention, for orchestrating complex applications, but I think I'm missing the point as to where the complexity lies. We use a single Deployment as well.

**Comment by jessebye** [comment]
@Crevil the more I'm thinking about this, it probably isn't needed at this point. Operators are great for multiple deployments of the same app, but can be overkill for a single deployment.

**Comment by Crevil** [comment]
All right. Then I haven't missed some complexity so far.

If some organizations, expectedly larger enterprises, that want to deploy multipel instances it would make sense. Or maybe SaaS companies?

@dtuite you are not using Kubernetes for your services at Rodie?

**Comment by martina-if** [comment]
Hi @Crevil , thank you for the ping! (I am working with @dtuite in Roadie)

Yes, we are using Kubernetes and this is an interesting idea. We are using a combination of [Fluxcd](https://fluxcd.io/) and its Helm Operator to solve this today. I'd be curious to know if this operator could have big benefits over the HelmOperator.

**Comment by Crevil** [comment]
There might not really be that much benefit TBH. As long as the native Kubernetes objects can cover the needs I think we can find little benifit.

Just as a thought experiment though:

An instance of Backstage could be setup by creating a `Backstage` Custom Resource (CR). Configuration parameters would then be served directly from the kubernetes API server. This is a statically typed resource which brings the first limitation. As backstage has a dynamic configuration schema depending on what plugins are registered, we cannot define the schema upfront. Because of this we would have to fall back to a dynamic schema in kunernetes and thus loose the benefit here.

Another approach would be to register plugins in Kubernetes CRs as well and have the operator push these information into backstage,  but in practoce this would not work as the application framework requires pretty custom code to wire stuff up.

Entities in the catalog could be stored as `Entity` CR. Backstage could then have a kubernetes catalog processor to collect them.

To me, at least, it would feel odd to try to model backstage deployments in this way. A more "close to the metal" approach with Helm charts or native Deployment resources feels more right.

**Comment by jessebye** [comment]
I'm closing this for now since we've gone a different route and haven't identified any strong use cases for this.

**Comment by stevehipwell** [comment]
Sorry I'm late to the discussion here but I think there is a strong use case for a Kubernetes operator to manage Backstage deployments with the aim of enabling a "no code" production deployment of Backstage into a Kubernetes cluster (I'm aware that this "no code" would involve yaml config).

I'd propose the following high level design for an operator MVP.

- Operator
  - Installed by Helm
  - Watches CRDs
  - Uses CRD content to generate JavaScript config as configmaps
  - Deploys default Docker image with configmaps mounted as volumes
- Instance CRD
  - Defines a Backstage instance configuration
  - Supports multiple instances
- Plugin CRD
  - Defines a plugin configuration for an instance
  - Has a typed but flexible API to provide plugin customisation

The Helm chart being used to deploy the operator could be used to deploy the default instance CRD and some of the common plugins that are part of the primary project.

As I'm not fully familiar with deploying a complex Backstage instance I'm sure there are a number of things I've missed off at the high level but I think the general principal is sound.

**Comment by freben** [comment]
@stevehipwell Part of the problem is that there basically is no such thing as a "no code" Backstage right now. It's heavily focused on letting adopters dive deep down and wiring things together freely and adapting pages using JSX etc. Until that changes - and that'll be a larger, longer-term undertaking - this may make less sense than otherwise. It'd be a little like making a kubernetes operator for create-react-app. Is that a fair understanding of the ask?

This vision is great, but Backstage may not be ready for it. Again, totally open to not having understood the ask fully :)

**Comment by stevehipwell** [comment]
@freben I agree with what you've said and maybe "no code" was the wrong term to use but I still think this would be useful. I'd like to be able to have a Backstage instance installed by Helm without needing to create any "code" repos. I'd also like to be able to read a blog post about a new plugin and be able to add it to an instance by writing some yaml to the K8s API.

For example a couple of plugin integration points that the operator could implement are as follows.

- Plugin activation
  - Operator templated js
  - Use a configmap to overwrite a noop file on base docker image
- Env variables
  - Operator managed on K8s deployment
- Menu configuration
  - Strongly typed CRD fields
  - Operator templated js
  - Use a configmap to overwrite a noop file on base docker image
- Plugin config
  - Operator templated js file
  - Some strongly typed CRD fields for common config patterns
  - JavaScript passthrough for complex config

This design would allow for the standardisation of plugin config via a data driven model, while still allowing all existing config patterns to work.

**Comment by Crevil** [comment]
This is indeed a great value proposition, but as @freben mentioned: Backstage is not built for this kind of thing.

Maybe we should kick af an [RFC](https://github.com/backstage/backstage/labels/rfc) around getting backstage to that point and what it would require. The k8s operator is really the last step to implement as I see it ie. we need a lot of things cleared out before doing it.

**Comment by stevehipwell** [comment]
@Crevil a RFC would seem to be the next logical progression of this discussion.

Although I agree that the K8s operator could be the last step; it could also be the first step as it would allow the desired pattern of use to be supported at the cost of complex and untyped CRDs. This complexity could be addressed via the strangler pattern allowing an incremental journey to the state dictated by the RFC rather than a big bang.

**Comment by Rugvip** [comment]
👍 to an RFC on the topic. An I think it's good to keep it scoped to what pieces are needed to enable a CRD-way of shipping Backstage rather than an RFC on taking it all the way to CRDs. We've envisioned that a config-driven app is something that could eventually be built on top of the existing APIs, but there may be pieces that we want to add to for example the plugin API to make it easier to build.

I don't think the operator implementation itself is too interesting atm tbh, as it's just one possible ƒ in `YAML --ƒ-> Backstage`. Operators could become a bit more interesting if we start considering deployment patterns where backend plugins are split across instances, and also things like horizontally scaling the catalog and scaffolder processing based on queue times.

**Comment by rosscdh** [comment]
Could have the operator watch for plugins and run a kaniko in cluster build and then update the deployment reference 

Crd for app config is simple but a configmap mounted in place is good enough for most
