### ISSUE TITLE
[Search] Implement index interface for Software Catalog

### ISSUE THREAD

**Issue by emmaindal** [backstage/backstage#4442]
## What / Why
We want to enable end-users of Backstage to be able to search (via a search text field, as well as via filtering) for anything in the Software Catalog by any/all properties.  In order to do so, we need to refine how Software Catalog entities are indexed.

## Scope / UAT
- [ ] It should be possible to configure a path pattern in the backend for the `location` property for a given entity during collation.  (This is necessary because the source of truth for entity page routes is the front-end.)
- [ ] ~~All well-known properties on well-known entity types~~ Properties of catalog entities that make up the current, user-facing search should be exposed on the `Indexable` type and populated during the collation process.  This includes: `owner`, `kind`, `lifecycle`, `description`, `name`, and `namespace`.

## Implementation Details

Note: A skeleton of an implementation for this exists in [DefaultCatalogCollator](https://github.com/backstage/backstage/blob/44ec2571b65de281dd68c669562c1a67dc0976ce/plugins/catalog-backend/src/search/DefaultCatalogCollator.ts), which should be refined in this issue.

**Comment by iamEAP** [comment]
Thought while mobbing on this: instead of going down the Backstage config route for configurable locations...  Let's just expose a public property or something on the `DefaultCatalogCollator` where a path pattern can be configured in code.  (Similar to how path patterns are configured in code / JSX on the front-end).  ...More advanced customization can be handled by extending the collator or writing a new collator.
