### ISSUE TITLE
Embed Backstage Bar into component's README

### ISSUE THREAD

**Issue by taras** [backstage/backstage#4457]
## Feature Suggestion

I need a way to get the organization engaged with our new Backstage portal. It needs to become a place that everyone goes for information. It needs to be always at the developer's fingertips. Switching between GitHub and Backstage should feel natural and seamless. Navigation has to be bi-directional. That means that the linking needs to be bi-directional. GitHub repositories need to link back to their pages in Backstage. There is a way that we could do this that would be both functional but also encourage the kind of behaviour that we want people to exhibit. 

## Possible Implementation

We could introduce a Backstage Bar. It would be an image that is generated from Backstage and embedded into the repository's README. It would show valuable information about the component. It could even include a score for how compliant the project is with organizational requirements. This image would be wrapped in a link back to Backstage. The simplest thing to do would be to automatically include it in the project's README via the template. After that, the image would be automatically generated and cached. The image could be an SVG would be light and editable with React.

## Context

I've seen a scoring system work very well in [EmberObserver.com](https://emberobserver.com) which is a site that rates Ember plugins. The result of the score is that it encouraged people to improve their plugins so their plugin will show a score of 10. It became something to be proud of. I would love to bring that kind of pride to the quality of components within our engineering ecosystem.

Here are some screenshots of how it looks in EmberObserver.com,

![score-breakdown](https://user-images.githubusercontent.com/74687/107354126-c6a35480-6a9b-11eb-9042-56d56a3e62e0.png)

![list-of-scrores](https://user-images.githubusercontent.com/74687/107354136-ca36db80-6a9b-11eb-8e7c-8714f6a21f96.png)

**Comment by dtuite** [comment]
Huge 👍  to this idea. Features like this will be key to driving engagement with Backstage inside organisations.

**Comment by adamdmharvey** [comment]
_Fantastic idea_!  As an incremental, could start with an easy badge a la https://shields.io and then be enhanced overtime.

![image](https://user-images.githubusercontent.com/33203301/107383635-2c550800-6abf-11eb-8d02-2e3cf41b0bee.png)

There's also a suggestion for scoring in #2662 which would tie nicely into this.

**Comment by taras** [comment]
@adamdmharvey this is a good place to start. Agree

**Comment by adamdmharvey** [comment]
Proposal:

* Turns out shields.io provides an NPM library 🎉 : https://www.npmjs.com/package/badge-maker
* We could create a new plugin
* Plugin should allow you to query it and it responds via the frontend raw with a badge
* Now I may be mixing up terminology here, so I think we want URL paths not "React routes" (???) but ending up we end up with a ref of `/badges/Kind/Namespace/EntityName`
* Provide a way for someone to view an entity and "get the badge" so they can then place it in their README
* Start simple with just powered by Backstage or something equivalent that doesn't use any entity data (yet)
* Security Considerations: like Jenkins (and other providers), badges can be authenticated or unauthenticated. If they are to be embedded into a README in SRM, the user may not have ever used Backstage nor have authenticated to it. So the integrator may need to identify if they allow, or not allow, unauthenticated badges?  At first stage, require authentication (which should essentially just be a regular plugin I think?) before figuring out how to separate as unauthenticated with maybe a config flag for the integrator.
* And let future iterations add security, enhance the badge with entity data or scoring, that sort of thing.
 
Thus a target action list of:

* [ ] Creation of a new plugin `@backstage/plugin-badges`
* [ ] Plugin responds to `http://locahost:3000/badges/<kind>/<namespace>/<entityname>` 
* [ ] Creation of a new Card that can be embedded into an app's overview page with a link to "get badge" button - this would generate Markdown relevant for the URL (or just the URL)

Thoughts? Anyone willing to pick up?

**Comment by benjdlambert** [comment]
@adamdmharvey you beat me to it. I was gonna ask the `Anyone willing to pick up?` question..

**Comment by andrewthauer** [comment]
On the note of security and authentication, this assumes the backstage instance is public. For instance, it may be behind a corporate VPN / intranet, so serving badges may not work in some cases.

To address this, there could possibly be a companion proxy like this https://github.com/tynn/sonar-badge-proxy. Perhaps there is something more generic around that could be used wholesale?

**Comment by benjdlambert** [comment]
Yep - agree with the security issue. I guess it assumes that your browser can hit the backstage instance, which I thought might not be an issue for most companies or people that have secured their VCS system the same way. But I guess that might not work for everyones use case so maybe a proxy could help here.

**Comment by benjdlambert** [comment]
I guess it depends where you want to display your badges

**Comment by kaos** [comment]
I've been looking at this a little bit (good issue to get my feet wet, and my bearings with the project ;) )

Am I correct if we actually will need two plugins for this? (one for the backend api and the other for the Card to be embeddable in the App)

**Comment by taras** [comment]
@kaos yeah, it would need to be 2 plugins. A backend and a frontend plugin - I believe.

**Comment by kaos** [comment]
I've done some POC work for the badge plugins, cross reff'ed above.. here's a screenshot of the "preview" entity card.
![image](https://user-images.githubusercontent.com/72965/108208128-eb956880-7128-11eb-9941-6cac80aaacaa.png)

I'm new to all of this, so I've left a few TODO's in there that needs to be resolved before it will be usable outside of a local dev env.

Also, I'm not sure how this is usually done, for plugins that does not have a routable extension (top level page) how do you develop them?
I opted to add a routable top level page in the plugins /dev folder for the purpose, but I feel that can't be it, really.. ?

**Comment by freben** [comment]
Cool. Short note:

https://backstage.io/docs/architecture-decisions/adrs-adr009#entity-references-in-urls

the url should probably be more like `/badges/entity/default/component/demo` if it's an entity specific badge that is rendered

**Comment by adamdmharvey** [comment]
Awesome @kaos !!!  Really nice.  Can't answer the URL/route question, unfortunately.

Seeing your screen shot brings to mind,

* As taras noted in the initial description above, if we think the primary use case is to be used in the GItHub README of a specific component,  it would seem to make sense that the link default to the exact entity rather than the Backstage homepage.  e.g., maybe the generated link should include the main entity page `http://localhost:3000/catalog/default/component/adams-component`  ?
* I wonder if "getting the badge" should be a link off the About Card? Here I've added the Material-UI icon `<Loyalty>` at the top right but just a possible example.
  ![image](https://user-images.githubusercontent.com/33203301/108242558-0b259480-711b-11eb-84f8-e581078a4f93.png)

**Comment by adamdmharvey** [comment]
Or maybe a UX/UI person would say if it should be the larger button below About, not sure! 😁

**Comment by taras** [comment]
I was just looking at how it works in some CI systems. 


## TravisCI 

![2021-02-17 12 31 45](https://user-images.githubusercontent.com/74687/108243513-2cd34b80-711c-11eb-8df9-2c3a04f83c7b.gif)

## CircleCI

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/74687/108243805-7de33f80-711c-11eb-9673-70f0726dd0ed.png">

What else has badges?

**Comment by taras** [comment]
> GItHub README of a specific component, it would seem to make sense that the link default to the exact entity rather than the Backstage homepage

yeah, I definitely think it's more useful to go to the entity home page. It's kind like the inverse of View Source.

**Comment by adamdmharvey** [comment]
To add to your examples, here's...

## Jenkins

![image](https://user-images.githubusercontent.com/33203301/108244812-9bfd6f80-711d-11eb-8a6d-c56178254a4b.png)
![image](https://user-images.githubusercontent.com/33203301/108244842-a455aa80-711d-11eb-9d31-fdd3219d052b.png)

**Comment by taras** [comment]
One thing that I see is a little different is that all of them show a status. We don't think we have anything equivalent to a status at the moment but the link is still useful.

**Comment by kaos** [comment]
First thing that comes to mind for "status" is the lifecycle value.

I'll look into incorporating the excellent feedback here, for another round :)

**Comment by taras** [comment]
> First thing that comes to mind for "status" is the lifecycle value.

that’s an awesome idea

**Comment by kaos** [comment]
OK, I've come so far, that I feel a draft PR may be valuable to make it easier to discuss/review the code..

Here are some updated screenshots (also in the PR)
![image](https://user-images.githubusercontent.com/72965/108396986-c3386780-7217-11eb-8697-190e1f206d17.png)

Clicking on the badge brings out a drawer on the right with additional information
![image](https://user-images.githubusercontent.com/72965/108396938-b61b7880-7217-11eb-9c9e-d8cb28418034.png)

**Comment by kaos** [comment]
> > First thing that comes to mind for "status" is the lifecycle value.
> 
> that’s an awesome idea

:) I've planned for supporting multiple badges (depending on what you want)
so will look into adding another one for lifecycle, see how it goes...

**Comment by taras** [comment]
@kaos this is looking really great. It's really coming together. Thank you for running with this!

What do think about changing "Powered By" to "Visit in"? I'm not sure what "Powered by" could mean in this context.

**Comment by adamdmharvey** [comment]
Also excited by the direction.  I'll note, I don't think we want to expose the badge IN Backstage.  I dont need Backstage to tell me my component is powered by.... itself.  😁 I think the only exposure of this in Backstage should be an ability to grab the badge, but the badge ITSELF needs to be put ELSEWHERE outside of the system.  (That's where, from a software architecture perspective, I wasn't sure if that's a React route or just more a direct URL element somehow into the front end from anywhere, given the security considerations we had above in this issue.)

So I personally wouldn't DISPLAY it in the Anout Card, but give me a link to GRAB it to put elsewhere?

**Comment by taras** [comment]
We need some UX love here :)

**Comment by freben** [comment]
Yeah maybe this could be an entry "Badges" in the three-dots kebab menu in the top right in the header! And that opening that drawer (which looked great) or a dialog

**Comment by stefanbuck** [comment]
GitHub is exposing the dialog via the three dots menu as well
<img width="655" alt="Bildschirmfoto 2021-02-19 um 00 11 17" src="https://user-images.githubusercontent.com/1393946/108434203-8ab08200-7247-11eb-896f-5392c6d169cd.png">
!

**Comment by kaos** [comment]
Alright, so I got in a bunch of tweaks today. (still have some more work to cleanup after @freben 's review ;)

I've added a config section for badges, so you can define your own set of badges you would like to have. I've included a few examples, to show what's possible. Screenshot demo included below.

Added a new badges context menu for the entity page, much like the github dialog above (except the options etc in there...)
I feel we're getting closer, keep all the good feedback coming :)

*CSS help wanted*: I've stumbled upon a horiz scrolling issue in the dialog. I spend way too much time trying to figure out how css works, so if there's a css guru around, please help :)

![image](https://user-images.githubusercontent.com/72965/108561419-85fad500-72fe-11eb-98bb-ca298eb9f3ac.png)

![image](https://user-images.githubusercontent.com/72965/108561478-a034b300-72fe-11eb-9ceb-9c68faa27a9b.png)

I've included the badges in the dialog there as a preview for what you'd get.

Oh, and the list of badges are now declared in the app config, as mentioned. Here it is for completeness (and of course, open for suggestions if you miss anything or what-ever ;)
```yaml
# sample badges
badges:
  pingback:
    kind: 'entity'
    description: 'Link back to $${app.title}'
    target: '$${entity_url}'
    label: 'View $${entity.metadata.name} in'
    message: '$${app.title}'

  lifecycle:
    kind: 'entity'
    description: 'Entity lifecycle badge'
    target: '$${entity_url}'
    label: 'Lifecycle'
    message: '$${entity.spec.lifecycle}'

  owner:
    kind: 'entity'
    description: 'Entity owner badge'
    target: '$${entity_url}'
    label: 'Owner'
    message: '$${entity.spec.owner}'

```
(docs for the config options in the config.d.ts files in the plugins)
Oh, and yeah, I had to go with double dollars there, since I didn't seem to get the value from config with just a single dollar sign.. ?

Doh, and now I spotted a bug in the links there, but I don't want to re-create the screenshots, so I'll leave them to your imagination that it will be fixed.

**Comment by kaos** [comment]
Also, in case someone does not want the badges plugin, what then?
As it is now hard-wired into the entity page layout context menu.. should there be some kind of detection logic, or...

**Comment by freben** [comment]
Adopters are able to shape their own entity pages in JSX using the new composability system. There will be steps to installing each plugin. Your plugin will be exporting the building blocks that can be wired into a larger whole.

Honestly this would be the first plugin that would be wired into the menu like this. It's actually something we should keep an eye on - what the installation experience would be like.

**Comment by freben** [comment]
Word of warning: we're reserving the `${}` placeholder syntax. The config platform will try to substitute it upon loading the file

**Comment by kaos** [comment]
> Word of warning: we're reserving the `${}` placeholder syntax. The config platform will try to substitute it upon loading the file

I suspected something like that. Maybe I should replace it with some other templating syntax for the config, then.

> Adopters are able to shape their own entity pages in JSX using the new composability system. There will be steps to installing each plugin. Your plugin will be exporting the building blocks that can be wired into a larger whole.

Ah, right. I was about to clean out the drawer and AboutFieldCard and stuff, leaving only the context menu and dialog stuff... maybe I should leave some of it in, in case an adopter want to use it elsewhere?

**Comment by freben** [comment]
Otherwise, this is an example of a thing that configures itself using an apiRef

https://github.com/backstage/backstage/blob/master/packages/app/src/apis.ts#L34

Yeah maybe it makes sense to export both the "naked" innards of the control, as well as the dialog that normally houses it

**Comment by kaos** [comment]
Ok, I've done some refactoring and cleanup. I opted to not leave any extra components and innards exposed at this time, to keep the amount of code down to bare essentials for now. Going to be easy enough to add them later on, if desired.

New screenshot after refactoring:
![image](https://user-images.githubusercontent.com/72965/108730056-71e7eb00-752b-11eb-891c-a7e57f8b9d0a.png)

Thinking that style could be a option one could choose from the Badges dialog, for now, it is config only... here's another pic showcasing what badge-maker has to offer, besides the default flat one...
![image](https://user-images.githubusercontent.com/72965/108730440-d1de9180-752b-11eb-8fb9-165f35e16014.png)

@freben I went with a api call to get the badge data fully processed, rather than doing templaty stuff in the frontend. Feels like its getting closer to being usable now :)
Also changed the template marker in the config to use `_{...}` instead of the double dollar.

**Comment by taras** [comment]
@kaos that's pretty epic!

**Comment by adamdmharvey** [comment]
This looks amazing, nicely done @kaos !

I have some content questions which are nitpicky, but overall the concept and what you've been able to accomplish are great.

Sheilds.io has a defined badge specification here:
https://github.com/badges/shields/blob/master/spec/SPECIFICATION.md

To adhere to that, I recommend the following changes:

* The left side is always supposed to be static. So our first badge should not say "View hello-world in / BACKSTAGE` but instead swap them around.  The dynamic stuff, the entity name and that sort of thing, should always be on the right.
* According to the spec, the badge is supposed to be very concise.  Given that, I suggest that the entity badge is even more simple and just says maybe one of these options:
  * `backstage | entity-name` -> `backstage: hello-world`
  * `backstage | entity-kind:entity-name` -> `backstage: api:report-system`
  * or even `api | report-system`
  * That last one avoids "advertising" Backstage, which the spec indicates should not be done, and also some orgs may rename their Backstage using `app.title` and using Backstage for them in a badge would possibly distract (or confuse) their users who may think it's called the "MyCompany Software Catalog".
* Suggest all elements across the badges should be _all lower case_. The spec doesn't say this, but you can see convention in the industry is not proper case.
* Where possible, the static info on the left should be as short and succinct as possible? so I'd suggest things like:
  * `docs | hello-world`
  * `owner | hello-world`
  * And the value you get from CLICKING them is learning more about them in the catalog itself.  But they don't need to "advertise" backstage per se (which the spec notes should not be done), but gets to the root of the need that Taras noted which is to elevate the info is available and push users into backstage as a source of info!

**Comment by kaos** [comment]
Thank you @taras and @adamdmharvey for those kind words.

I've made a few refactorings, based on review comments. Also cleaned up the default badges a little bit, including force downcase texts, so now it looks like this. It feels like we're getting closer to done each day ;)
![image](https://user-images.githubusercontent.com/72965/108845216-6b19b080-75dd-11eb-9f68-20346fcf45ec.png)

**Comment by taras** [comment]
Amazing work @kaos

Thank you 🙏

**Comment by kaos** [comment]
Thank you. It's been a great first issue to work with to get into the backstage code base. So great suggestion :)

**Comment by taras** [comment]
Let's file this one under _teamwork_.
