### ISSUE TITLE
catalog-import: Visual alignment of multiple component import

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4605]
## Feature Suggestion

The new catalog-import feature (#4271) of providing a repo and it scanning for entities is _super cool_; I've been using it a lot recently. For some of my test repos I have a moderately large list.

I find reading the analysis results a bit tricky, my eyes 👀 go all wobbly.  I suggest that we indent the list items that contain the actual component names to be folded under the description of the entity metadata they've been found in.

### Current View

![image](https://user-images.githubusercontent.com/33203301/108541027-f8909400-72af-11eb-9dbd-98e12d63d906.png)

### Proposal

![image](https://user-images.githubusercontent.com/33203301/108541132-1a8a1680-72b0-11eb-886d-e3fd8abc50a9.png)

## Context

This doesn't change the feature, and so is purely a visual/alignment question. Tagged it with design as others may have counter suggestions that are better.

**Comment by adamdmharvey** [comment]
I also wonder if a `<Divider/>` might help to break it up some.

**Comment by freben** [comment]
Maybe the inner ones can be `dense`, so they get stacked tighter as well. The proposal looks good.

I wonder if this could even be better as a table though ... like, showing the relative paths (from the base URL you gave) instead of the full URL in one column, and the text "3 entities: Component (2), API (1)" or something like that. And expandable rows or a drawer or something to show full details.

Just thinking that maybe the display is basically TOO detailed to begin with 🤷

**Comment by adamdmharvey** [comment]
Checked and they already are dense. This may be superseded by #4741 , but there may be small/easy changes that could be done in meantime, so will continue to keep this open in case anyone has ideas or some time to make quick changes.
