### ISSUE TITLE
Hyperlinks in dark mode have low contrast

### ISSUE THREAD

**Issue by andrewthauer** [backstage/backstage#4615]
The current default theme for dark mode has a low contrast for hyperlinks. This makes it difficult to read them in many cases.

## Expected Behavior

All hyperlinks are easier read in dark mode.

## Current Behavior

Many hyperlinks are quite difficult to read when viewing in dark mode. This includes techdocs and anywhere else they are used (e.g. tables, etc.)

## Possible Solution

Update the colour in the dark theme at https://github.com/backstage/backstage/blob/master/packages/theme/src/themes.ts#L125

## Steps to Reproduce

<img width="662" alt="image" src="https://user-images.githubusercontent.com/6507159/108624359-84bacc80-7412-11eb-8fd3-580aea2f1efb.png">

<img width="327" alt="image" src="https://user-images.githubusercontent.com/6507159/108624369-9ef4aa80-7412-11eb-9500-3d8b4eb00000.png">

**Comment by freben** [comment]
Indeed, that's way too dark!

**Comment by chinmaym07** [comment]
Hey Can I work on this ?
If possible please provide a color to replaced with .? 
I think this color #4A9CFF looks better . Can I go ahead with this ?
![Screenshot_2021-02-22 Home Services Backstage](https://user-images.githubusercontent.com/44670961/108748277-69f86d00-7564-11eb-89de-6404ac72356b.png)

**Comment by wrousseau** [comment]
It looks like material-ui uses #90caf9 by default for dark mode : https://material-ui.com/components/links/#simple-links

What do you think?

**Comment by adamdmharvey** [comment]
If it helps, I think the only place needing to edit this is here:

https://github.com/backstage/backstage/blob/18a9f2f3e32fce6ec9a6bc8cb4b399f0960ac2e4/packages/theme/src/themes.ts#L124-L125

**Comment by freben** [comment]
Yeah use the material-ui default linked above (thanks @wrousseau) unless it for some reason is a really poor fit. Assigned @chinmaym07 !

**Comment by roottool** [comment]
`link` and `linkHover` don't exist in [a palette of Material-UI](https://material-ui.com/customization/default-theme/). The color of this hyperlinks are referred from `main` in `primary`.
Because [the default color which `Link` of the Material-UI component is `primary`](https://material-ui.com/api/link/#props).

I suggest the color of `running` in `status` and `info` of `banner` changes to a new color of `main` in `primary`.
This is because that I think `darkTheme`should unify them too such as `lightThene`.


## Code pointer

https://github.com/backstage/backstage/blob/18a9f2f3e32fce6ec9a6bc8cb4b399f0960ac2e4/packages/theme/src/themes.ts#L105

## Screenshot

![image](https://user-images.githubusercontent.com/11808736/108904819-55020380-7662-11eb-8f1d-2a51006225c5.png)

## FYI

- `link` is used in `packages/core/src/components/MarkdownContent/MarkdownContent.tsx`.
 
  https://github.com/backstage/backstage/blob/18a9f2f3e32fce6ec9a6bc8cb4b399f0960ac2e4/packages/core/src/components/MarkdownContent/MarkdownContent.tsx#L54

- `linkHover` is used in `packages/core/src/layout/Sidebar/Intro.tsx`.
  https://github.com/backstage/backstage/blob/18a9f2f3e32fce6ec9a6bc8cb4b399f0960ac2e4/packages/core/src/layout/Sidebar/Intro.tsx#L52

**Comment by andrewthauer** [comment]
Fixed by #4747
