### ISSUE TITLE
Build backstage core backend and plugin backends on top of a higher level opinionated framework

### ISSUE THREAD

**Issue by shashi-suvarna-tm** [backstage/backstage#4622]
Introduce a framework on top of which backstage core backend and plugin backends can be built.   Currently backend architecture is not as opinionated as the front end architecture (extensive use of backstage component library).

## Feature Suggestion

As backstage community is growing and number of ideas, we are encoding common patterns inside our code that are best solved elsewhere in frameworks (e.g. authorization, dependency injection, GraphQL abstraction etc.)   Suggestion is to use a higher order framework that will help encapsulate those patterns and help backstage codebase remain clean and focused on the vision at hand.   This will also speed up development of plugins as we focus on the business logic.

## Possible Implementation

Use NestJS framework to build the backstage core on.   Some notable feature that could be used to speed up development

- All API backends to use GraphQL (CRUD) in so that authorization (if required) can be standardized. Will help with type validation also and eliminate bugs.
- Use code first development for GraphQL structures (resolvers and mutations) - e.g. Look at [this](https://docs.nestjs.com/graphql/resolvers)
- Identity and Authorization implementation as described [here](https://github.com/backstage/backstage/issues/4089) will get complex as community adopts backstage.  Frameworks like [CASL](https://github.com/stalniy/casl) already integrated with [Nest/react](https://docs.nestjs.com/security/authorization) can provide these abstractions.
- Some use cases for backstage observability #1519 can be best implemented to a framework.
- Validation of backend data api is a place where most bugs reported.   Having a standardized validation pattern integrated into core with help eliminate errors.

## Context

In order to introduce the right framework to build Backstage on, following requirements have to be met:

- First class Typescript support  (Backstage requirement)
- Vibrant community with periodic updates to the framework
- Dependency Injection - Ability to inject data retrieved by backstage core into plugins - 
- Built in authentication (passportjs used by Backstage) and authorization support 
- Most common patterns are available out of the box - Graphql support, Task scheduling, health checks  - Help backstage community with rapid development of plugins
- Monorepo support - Backstage project is built using a monorepo structure
- Easily extensible to build a plugin system around
- Strong testing framework support built in
- License must be present in the CNCF allow list licenses

Frameworks evaluated -  ExpressJS, [Fastify](https://github.com/fastify/fastify), [Loopback 4](https://github.com/strongloop/loopback-next), [NestJS](https://github.com/nestjs/nest)

NestJS is recommended due to the following reasons
- Large community.  34.7K stars on GitHub.   Regular updates.   MIT licensed
- Modular design that helps with maintaining a very large code base.   At some point of time, backstage will become large
- Dependency injection and module system - Required for injecting common backstage utils + context into community written plugins
- NestJS uses Express internally and mostly built on top of already available popular frameworks for other requirements.
- Authorization use cases being discussed here can be met using nest + casl or by writing simple nest modules
- Most backend api code in backstage plugins can be migrated to NesJS as modules with little effort
- A large app built on top of Nestjs is available here [Vendure Ecommerce](https://github.com/vendure-ecommerce/vendure).   It has a [plugin system](https://www.vendure.io/docs/plugins/plugin-architecture/) built on top of Nest.  We can borrow some ideas from here
- This is the best possible framework in the nodejs ecosystem that comes very close to Spring Boot
- My favorite one - I have found a NestJS plugin for almost every possible use case that I had  

Limitations of other frameworks:
- ExpressJS and Fastify are similar and provide good base framework but we have to code/find plugins for higher level patterns ourselves.   Express is used in backstage.   Teams I have worked with have tried Fastify in some of AWS lambda + Nest projects due to performance reasons.   
- Loopback 4’s authorization system is more opinionated (though works for most use cases) but may not meet some of the backstage community requirements.   Also, less GitHub stars compared to NestJS. 

Some caveats:
- NestJS has a learning curve.   If you are an Angular developer then you will be productive fast as it borrows a lot of Angular concepts
- My analysis above may be biased as I have used NestJS, Angular and Spring Boot extensively in my projects
- Above is not an extensive analysis of the requirements of Backstage but happy to discuss further with the community.

**Comment by Rugvip** [comment]
Thank you for the suggestion! 👍 

Overall I think we're very much open to adopt more existing technology to help out structuring the backend. I've especially been thinking lately that we should use some form of express router helper for REST APIs, and likely slim down our volume of custom framework-y bits that end up in the backend package.

To provide some context though, there are a couple of constraints that have led us to the way the backend looks at the moment. Most importantly we do not want to enforce backends to be built with any kind of framework that we provide, or even to have to exist within the Backstage ecosystem at all. Internally we have plenty of plugin backends that are owned and deployed separately from our common backend, and we want this pattern to be possible for other adopters too. We also want it to be possible to split the backend into multiple instances with relative ease, both for deployment lifecycle and ownership reasons, as well as enhanced security. In general we want the different backend plugins to be very loosely coupled, and at this point I don't think we want for example a DI framework for the purpose of communicating between different backend plugins.

That said I think looking at something like NestJS we can both learn and possibly adopt pieces of it if the architecture allows, but adopting the entire framework would require very careful consideration. I also see that it has its own CLI and build system, which of could get a bit troublesome for us too as we are looking to create a very smooth DX and avoid confusion. Lastly we've stayed away from the experimental TypeScript decorators so far, as they didn't make the standard and will likely be replaced by something else in the future.

**Comment by andrewthauer** [comment]
This is a very well thought out and presented RFC. Defiantly worth discussing.

One thing I would point out is that general purpose frameworks tend to start influencing aspects of the system architecture which can seep into various parts of the host system. This can lead to friction and complications later on. There are big trade offs on both sides when comparing a framework influenced solution vs a bespoke solution.

From my perspective Backstage currently follows a bespoke solution pattern, and I get the feeling this may have been intentional? Another solution is to focus on addressing any particular pain points. Expresses itself has a large ecosystem as well for instance which could likely be utilized more.

**Comment by shashi-suvarna-tm** [comment]
@Rugvip - Thanks for the context.   If I understand the Backstage plugin architecture correctly, it has 2 parts, a frontend and a backend.   The frontend portions are coupled with backend's api interface.   Hence a frontend without a backend is not useful at all.   

There are two categories of plugins in the Backstage ecosystem:
- Spotify contributed plugins - My understanding is that these plugins are the ones that Spotify is planning to use internally.   Community will be using these.   Some of them are mandatory for Backstage to work.
- Community contributed plugins - Plugins that Spotify might use internally but mostly available and for  use by the Backstage community.

The appeal of Backstage is the availability of large number of plugins to solve a myriad of use cases.   I understand that Spotify has its own backends built possibly in Java?, Go? etc.  but for backstage community it’s important to be a bit prescriptive on the plugin architecture.   The quality and quantity of these plugins is going to drive the network effects for adoption of this platform.   Hence Backstage platform's stewardship is very important.   

It would be great if we can understand what is the vision for backstage core (must use) and the functionalities that would be covered by it and what is going to be open for development.   E.g. Is the Authorization subsystem  be a part of backstage core or is this open completely for the community to build from scratch. 

Regarding other concerns:

- Experimental decorators - We need not worry about it as long as we are use the Nest framework for creating our own decorators.   The assumption here is that Nest will provide us a migration path if anything changes in future (which is a very solid assumption given the large community).   Popular frameworks like Angular already use decorators extensively and these apps run in production.   The decorators are only compile time dependency. 

- Nest having its own cli - I don’t think this is an issue as the cli is mostly used for development purposes (nest start) and (nest build).   Normally I see issues when we use frontend frameworks like react where the cli comes in the way of bundling and customization but backends should be ok.   Whats kind of issues do you foresee here?

@andrewthauer - Agree that we can look at the express ecosystem also but I was looking for a more opinionated plugin development framework from backstage that is .   Also regarding tradeoffs, I see that Nest is very lightweight (core provides a nice way to modularize codebase) and it’s up to us what portions we want to adopt and what we don’t.  I know that I am getting into the React vs Angular like debate that has been going on for ages now but its important to understand the design choices and thought process before we all go too far into plugin development.

**Comment by adamdmharvey** [comment]
Note not plugin must always have a frontend and backend. If you see the Backstage architecture here:

https://backstage.io/docs/overview/architecture-overview#overview

![image](https://user-images.githubusercontent.com/33203301/108745324-efe6ca80-7508-11eb-89ff-efcbd89e7dc7.png)

CircleCI is an example. The proxy plugin provides that "backend" like service to route direct front end requests out to 3rd party systems to pull data in, without them actually being manipulated by a strict Backstage-installed plugin backend.  TechDocs has one, catalog does, but not all. 

Tech Rader is even easier, JUST a front end with proxy or backend. (it has statically defined "as code" in it, with no pulling from a database for simplicity)

Just helping with some context!

**Comment by shashi-suvarna-tm** [comment]
Yes I have looked at the above architecture.   If you see the above, technically the _plugin_ includes a frontend and a backend.   We need to fix the above architecture diagram to depict what a plugin is.   As you can see service catalog component (marked as plugin in the diagram) requires a Service Catalog backend to function properly.   Hence its a unit.

_For Tech Radar_ - since data is available during compile time, it does not require a backend (haven't reviewed the code).  But organizations will modify this to make it more dynamic i.e. with a backend.

_Proxy/Circle CI_ - This pattern may be ok if we are talking about readonly data (R) with the api key configured in the Proxy backend but any more advanced use cases (CUD) means we have to deal with the Confused Deputy problem where you have to start verifying the tokens and the intent (unless the same OAuth token can be consumed by CircleCI which is not the case here as we are having it to go through the Proxy).

**Comment by Rugvip** [comment]
> Yes I have looked at the above architecture. If you see the above, technically the _plugin_ includes a frontend and a backend. We need to fix the above architecture diagram to depict what a plugin is. As you can see service catalog component (marked as plugin in the diagram) requires a Service Catalog backend to function properly. Hence its a unit.
> 
> _For Tech Radar_ - since data is available during compile time, it does not require a backend (haven't reviewed the code). But organizations will modify this to make it more dynamic i.e. with a backend.

There are more examples of frontend-only plugins, it's not an uncommon pattern.

> _Proxy/Circle CI_ - This pattern may be ok if we are talking about readonly data (R) with the api key configured in the Proxy backend but any more advanced use cases (CUD) means we have to deal with the Confused Deputy problem where you have to start verifying the tokens and the intent (unless the same OAuth token can be consumed by CircleCI which is not the case here as we are having it to go through the Proxy).

A better example here is talking to 3rd party services directly using access delegation through OAuth, such as calling Google APIs directly from the frontend.

It is true that we need to improve the open source backend plugin patterns, but it should not come at the expense of constraints of how internal plugin backends can be set up. Having separate backends is not something we view as a thing that we just happen to be doing internally, it's the way envision that many of the internal plugins out there will work. That stems from the fact that Backstage is a front for your infrastructure, and not the infrastructure itself. Many Backstage plugin backends are in fact existing and vital pieces of infrastructure at organizations, and something that Backstage is just providing a frontend for.

Now something that could be argued is that even if there is existing infra in an org that you want to be calling from Backstage, that should be done through a backend plugin instead of calling the service directly. We want to avoid that requirement as it complicates and slows down plugin development, which we want to be very smooth.

**Comment by shashi-suvarna-tm** [comment]
Thanks for the responses.   This really helps with the parts we need to custom build vs what backstage will provide.

- I am not arguing here that there wont be a pure frontend only plugin.   What I meant to say is that there will be several plugins where backends are required.

- Regarding google API comment, I agree and thats what I meant by the token being consumed directly by the backend comment in Circle CI.   Again not saying that this use case does not exist.

- Regarding Infra backends existing - This will be the case for majority of the backends (whether its Kubernetes, Jenkins, Datadog, etc.) almost all come with APIs.  So most backends just massage the data and handle authentication/authorization.    The idea is to show useful piece of information on the backstage portal and delegate the details to the native backend infra UI (e.g. we don't plan to replicate all the UI components of Kubernetes, Jenkins or the Datadog User Interface)

- The only backends where significant amount of code is present is Techdocs, Catalog, Scaffolder as they are unique.   In our case, we plan to pull some info for catalog using ServiceNow CMDB  api.

**Comment by lowjoel** [comment]
I think @shashi-suvarna-tm brought in several key points that our team experienced as we were building our own plugins.

The first major speed bump we met was that everything felt so _unstructured_. While trying to build a CRUD-like plugin for a given domain, we found ourselves referring to a bunch of different plugins in Backstage that did things all slightly differently. As @shashi-suvarna-tm pointed out, most of the code was in the TechDocs, Catalog, and Scaffolder plugins, and even between them trying to find commonality and knowing what we need is difficult. Personally, I've found myself referring to one plugin, implementing functionality in my plugin in the same way, finding it doesn't exactly meet what I need, reference the other, tweak... it's a little frustrating. In this case, I believe the component I tripped on was the pretty fancy filtering capability that the Entity Catalog had, which to me was non obvious how all the different components interacted with each other (maybe because I'm not as familiar with the React/frontend ecosystem in general)

Backstage also has opinions on how API clients are written, like the Catalog Client. In any frontend/backend piece such a component would be needed. For something done from scratch, the data shapes and interfaces (ignoring GraphQL for now) needed agreement and both ends must match. Granted, this impacts plugins that talk to _existing_ systems less, compared to systems that we need to build from scratch, or is domain specific.

I believe that utilising a higher level framework could be of use here: the higher level framework imposes its own opinions so that building our plugin we need to form fewer of our own. In both situations, there's fewer decisions needing to be made, less reverse/re-engineering needed, and most of all having good examples and references as to what's a "good design" should look like. Some of this can be solved by better documentation, others by better plugins as examples - but these are all specific cases that requires engineers to understand and generalise.

**Comment by freben** [comment]
@lowjoel Thanks for writing that up, it's a great and humbling read. I think that you are hitting some effects of the way that this project is growing - we are pretty aggressively building out something that is in large parts a clean-room reimplementation of the old internal Backstage with less Spotify-specific assumptions, and invent some concepts as we go. As we do that, we eagerly get things out in the public eye so that they can be iterated on and improved, and we try to postpone "heavyweight" decisions and consolidations, until we can clearly see the emerging patterns and gain enough knowledge to make the _right_ choices.

We made some choices early upfront because they either seemed obvious to us, or were what we used before and really wanted to establish in the open source Backstage too. For example, React, Material-UI, Node, Typescript - these were things we could both feel comfortable with being great choices to work with in a given point in time, and choices that also would stand the test of time - that would be stable, and that we could grow with.

There are a lot of surfaces that we have _not_ had that same feeling with - yet. This goes especially for surfaces that become entrenched in code or in data at customer sites. If we choose a framework for backend development, which "leaks" across core-repo and plugin-repo boundaries, then that's a pretty big decision to make. Because that choice has to stand the test of time for a very long time, and it's a dependency chain that we will have to pay extra attention to and not break. Third party plugins will start diverging and use different versions of the library. The core may get harder to evolve at scale.

As time progresses in the project, we will be making more and more choices. Pieces will be leaving alpha. Code duplication will be handled and contained in shared libraries. New libraries and frameworks may come into play where appropriate. APIs will stop changing and abide by >=1 major-version semver.

To address two things you mention explicitly:

Yes, the contract for backend plugins is unclear and maybe overly liberal right now. We're starting to see patterns and may want to eventually settle on something a little higher level than basically just Express as the touch point eventually. Work to be done for sure - but maybe it'll be in the form of a more opinionated Backstage specific library, than in the form of a third party framework being adopted.

Yes, the filters for the catalog were probably an unfortunate example. They are pretty complex and the way that filtering happens in general in the app could be improved. I have it on my wish list since way back (I keep harping on about this!) that the catalog landing page needs to be restructured, and generalised.

**Comment by freben** [comment]
Oops!

**Comment by Rugvip** [comment]
@lowjoel Would love to have something in particular that helps out with creation and implementation of the backend API endpoints and consumption in the frontend. Even better if it comes with stuff like monitoring and doc generation too. We actually used gRPC for that exact purpose early on in the project, but switched it out for REST to use more ubiquitous technology.

So to be clear I think it would be good to adopt a framework or powerful library for building open source plugin backends and perhaps clients too, but I do not want us to lock people in to that solution were you have to build backends with that framework, or do an unreasonable amount of extra work if you're not using the framework. Then ofc I still want to be mindful of the deployment patterns we want to support, like splitting the backend into multiple instances, which is also why I'd want to be mindful of DI solutions apart from the complexity that they add.

I would be all for reintroducing something like gRPC :grin:, but that's perhaps not the best choice here. A REST framework that lets us either do schema-first or generate schema from code would be nice I think, possibly along with client generation too. I think we can go pretty far in providing opinionated solutions in both the backend and the frontend, as long as it's easy to use other options too. For example, let's say we use framework `xyz`, we could build all our open source backends in `xyz`, allow people to use it for internal backends too if they want, and provide `XyzClient` APIs in the frontend that are hooked up with auth and error handling etc. Just as long as we still allow people to use their own tech and it's possible for them to hook up auth etc. anyway.

**Comment by shashi-suvarna-tm** [comment]
Based on what I see above, there are plans to improve the experience of plugin development.   @Rugvip or @freben - Is it possible for you to summarize and open up another RFC/Issue for plugin development experience and close this issue?   If there is already work in progress in other issues the we can link and close this one.   Do let me know your thoughts.

**Comment by andrewthauer** [comment]
> A REST framework that lets us either do schema-first or generate schema from code would be nice I think, possibly along with client generation too.

I recently tried out https://github.com/bee-travels/openapi-comment-parser. I added it to an internal backend plugin we have, commented using the annotations and wrote a script to generate the `openapi` spec from the code. Seemed to work pretty decently, but my routes were pretty straightforward so not sure how it handles more complex cases.
