### ISSUE TITLE
Clicking owner link on an entity with an invalid group results in an empty group page

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4766]
## Expected Behavior

One of three,
* The group page should display when an an invalid group has been provided or does not exist in the catalog.
* I should not be able to register an entity with an invalid group?
* An entity with an invalid group as owner should not be clickable, possibly with a tool tip indicating it's not a valid user and maybe a little red X next to it (or a visual indicator of it being invalid in the instance).

## Current Behavior

If I register an entity with a `spec.owner` of `group:fake-group`, this becomes a link on the entity's main page in both the About card as well as the header. Clicking either of those links, takes me to the group page which is entirely blank: http://localhost:3000/catalog/default/group/fake-group

![image](https://user-images.githubusercontent.com/33203301/109744194-e2cc7a00-7b9f-11eb-9a05-c0a24e4dd662.png)

Clicking either link results in:

![image](https://user-images.githubusercontent.com/33203301/109744232-f081ff80-7b9f-11eb-83a6-160429bca15e.png)

And an HTTP 404 Not Found in my backend:

```
2021-03-03T02:40:29.837Z backstage info ::1 - - [03/Mar/2021:02:40:29 +0000] "GET /api/catalog/entities/by-name/group/default/fake-group HTTP/1.1" 404 239 "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88 blah blah blah" type=incomingRequest
```

## Possible Solution

The easiest is likely to trap empty/invalid groups and display as such in the org plugin, which likely covers this case but also any URL hacking someone might do or just bad copy/pastes say if someone IM'd a group link to someone else. So the empty group should likely print something more friendly.

However, there may be a higher-level method to address such as any time we ingest an entity, maybe it should validate the `spec.owner` before allowing it to be written? Or should we have an owner wrapper component which creates a link to the entity only if it's invalid, and if it's not then putting like a red X next to it with a tool tip saying it's not a valid user. This would help elevate this info into the UI. But open to other opinions on it?

## Steps to Reproduce

1. Register an entity and specify a group that does not exist in your instance, for example,
    ```yaml
    spec:
      owner: group:fake-group
    ```
2. Register the entity in your instance
3. View it's main page
4. Click the owner link in the About card
5. See empty group page

## Context

I have a feeling there's some sort of challenge with passing in the entity as context to the group overview card here:

https://github.com/backstage/backstage/blob/1b8b40cfeeb5c7dfd60cdb36807ba1fa09c092a4/packages/app/src/components/catalog/EntityPage.tsx#L429-L437

There is not actually an entity, so there's no object to pass in.  And not to make this too broad, but this seems to happen for all of the entities, likely again because of needing to pass the context in?  So the solution to this may be some sort of higher wrapper that errors if the entity is not valid.  I see the same if I put in a fake component name as well:

![image](https://user-images.githubusercontent.com/33203301/109745575-15777200-7ba2-11eb-8e52-61a248c9832b.png)

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 WSL2 Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome engine)

**Comment by benjdlambert** [comment]
@adamdmharvey looks like we need a not found page here then right?

**Comment by adamdmharvey** [comment]
@benjdlambert Yep. I think the complexity is that it's coming from the `EntityPage.tsx` itself? If there is no GroupEntity found, then the GroupEntityContent var isn't injected into the group page, and thus blank page.  Thus a fix would need to be done independently by every Backstage integrator, and could change depending on how they've defined their catalog pages.

So it would be nice if this was somehow better handled for integrators by the core, rather than them having to do it themselves?Not sure exactly the best way to do that (hence my not filing a PR!) but open to community input.

Same applies to users, as well. (if I use User:fake-user)

**Comment by freben** [comment]
Indeed, a 404 page (of sorts) for all entities is needed! We cannot forbid, or render impossible, dangling references due to the nature of these fickle changing sources of data. That being said, we should of course guide and assist the user to make as few as possible by accident, where we can.

A page like that should ideally show all _other_ info that is available though. For example, even if the entity itself cannot be found, we should list all relations that "want it to exist". That way we can help the user to clear up those dangling references. A backend api for doing that query doesn't exist yet though - except listing the entire catalog and filtering client side, which under those rare circumstances probably isn't all that crazy.

Regarding early signaling that a link won't lead to an existing entitybif you click it: oh heck yes, absolutely. But it'll probably not be reasonable to realize that until we have a heavily caching graphql layer. It'll be prohibitively expensive to do those lookups individually in large tables and similar.

Come to think of it - actually, the validity of references could be calculated statically by processors. When we finish up the catalog in the coming weeks, maybe that's something we could look into.

**Comment by freben** [comment]
Threw in a PR for it, have a look https://github.com/backstage/backstage/pull/4837
