### ISSUE TITLE
Got issue while installing react-redux at backstage/app

### ISSUE THREAD

**Issue by sanjeetCoder** [backstage/backstage#4779]
While trying to install react-redux it's giving issue.
## Expected Behavior

It should install react-redux.

## Current Behavior

warning " > react-redux@7.2.2" has unmet peer dependency "react@^16.8.3 || ^17".
warning " > react-redux@7.2.2" has unmet peer dependency "redux@^2.0.0 || ^3.0.0 || ^4.0.0-0".
error An unexpected error occurred: "EEXIST: file already exists, mkdir 'C:\\Users\\sanje\\backstage\\backstag\\backstage\\node_modules\\@backstage\\plugin-catalog\\node_modules\\@backstage'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\sanje\\backstage\\backstag\\backstage\\packages\\app\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

C:\Users\sanje\backstage\backstag\backstage\packages\app>

## Possible Solution
Change the version of React

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):v14
- Operating System and Version (e.g. Ubuntu 14.04):Window 64
- Browser Information: Chrome

**Comment by benjdlambert** [comment]
It looks like this issue is actually not related to `redux` install. 

Looks like this is the actual error: `error An unexpected error occurred: "EEXIST: file already exists, mkdir 'C:\Users\sanje\backstage\backstag\backstage\node_modules\@backstage\plugin-catalog\node_modules\@backstage'".`

Maybe remove `node_modules` and do a fresh `yarn install`
