### ISSUE TITLE
Async discoveryApi.getBaseUrl hard to integrate with synchronous API clients

### ISSUE THREAD

**Issue by taras** [backstage/backstage#4788]
`discoveryApi.getBaseUrl('proxy')` returns a Promise. This makes it difficult to integrate with APIs that expect to receive the base URL synchronously. 

## Context

We're planning to create a bunch of REST APIs to integrate with our services. We were hoping to create them in a schema first fashion by starting with OpenAPI spec. Microsoft uses [autorest](https://github.com/Azure/autorest) to automatically generate TypeScript clients for their RESTAPIs. We were hoping to do the same. 

## Feature Suggestion

The code that autorest generates is pretty decent but it expects the host to be provided synchronously. This makes the integration with Backstage more awkward than one would imagine. The challenge is that the factory constructor APIs are synchronous but `discoveryApi.getBaseUrl('proxy')` is asynchronous which means that I don't have the base URL when I'm creating an instance of the service that autorest generates.

## Possible Implementation

I could do something janky where I trigger asynchrony in the constructor but that makes me feel untidy.

**Comment by Rugvip** [comment]
Is this an API client where you want to keep state, or for some other reason don't want to instantiate one per request or couple of requests? We instantiate clients per requests every now and then when needed, for example [here](https://github.com/backstage/backstage/blob/8476322e67ae52362f29d2ded7440646959e341d/plugins/catalog-import/src/api/CatalogImportClient.ts#L179). That one's because of the token though, but same deal

It's nice the keep the method async as it provides a lot more flexibility in the implementation.

**Comment by taras** [comment]
@Rugvip this is a good idea. We'll give it a shot and report back on how it goes. I'll close the issue for now and reopen it if necessary.
