### ISSUE TITLE
To Close Alert Modal on Lighthouse Close Button is clicked multiple times

### ISSUE THREAD

**Issue by chinmaym07** [backstage/backstage#4850]
## Expected Behavior

The alert model should close in one click.
## Current Behavior

When the Create Audit button is clicked the multiple times & if there is an error One has to click multiple times on alert model close button to close it .
![Peek 2021-03-06 15-07](https://user-images.githubusercontent.com/44670961/110202362-01778d00-7e8e-11eb-9537-6830e11dc5e4.gif)

## Steps to Reproduce

1. Go to Lighthouse 
2. Use a sample website 
3. Click on Create Audit Button multiple times
4. If there is an error ,then you will see a modal & to close that model you have to click multiple times.

## Your Environment

- Operating System and Version : Ubuntu 20.04
- Browser Information: Firefox

**Comment by adamdmharvey** [comment]
I'm not fully confident on this, but in previous playing I did with Lighthouse plugin I have a feeling this isn't a modal issue per se, but the root cause is likley the loading is actually triggering multiple errors, which to the end user is being exposed as two errors to the ErrorApi, and thus the experience you see LOOKS like the modal won't close. But I'd guess there are just multiple you NEED to close.

Relates back to my RFC I feel like as I think these high-level modals are too high level / impacting for a casual user trying to open a plugin or an entity page tha tmight have a half dozen other plugins on it: https://github.com/backstage/backstage/issues/3781 Welcome any feedback / experiences / opinions if you have it to that RFC @chinmaym07 !
