### ISSUE TITLE
How to call microservices or entity in front end, No documentation is available

### ISSUE THREAD

**Issue by sanjeetCoder** [backstage/backstage#4862]
How to call microservices or entity in front end, No documentation is available for this.

## Expected Behavior

Front end should call entity 

## Current Behavior

Not sure

## Possible Solution

Not sure
## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):v14
- Operating System and Version (e.g. Ubuntu 14.04):Window 10
- Browser Information: Chrome

**Comment by benjdlambert** [comment]
Need some more information here, what are you trying to do exactly? Are you wanting to call your own microservices?

**Comment by sanjeetCoder** [comment]
-- Actually , I have created Microservices and React template using Backstage but when I am trying to initiate ci/cd it's required login via github

**Comment by freben** [comment]
What do you mean with initiate? This ticket is still totally unclear.

Yes the CI/CD view may show an auth dialog on the first render because it wants to talk to the CI/CD provider's API to get the data for the view, that's expected.

Closing this now because it seems to not be about the initial question anymore. But feel free to open targeted question tickets if you have specific things you run into, but please do provide a lot more info and screenshots and console logs etc if you have them.
