### ISSUE TITLE
Select a sign-in method----Not Configured 

### ISSUE THREAD

**Issue by ravichadda** [backstage/backstage#4863]
When we select any of the sign-in methods, its redirect with the localhost URL: "http://localhost:9393/api/auth/google/start?scope=openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&env=development"

With ERROR message:
NotFoundError: No auth provider registered for 'google'

## Steps to Reproduce

select any of the sign-in methods

## Your Environment

NodeJS Version (v12):v14.15.5
Operating System and Version (e.g. Ubuntu 14.04): Mac OS 11.1
Browser Information: Chrome

**Comment by freben** [comment]
Yes, you have to configure the providers that you want to use; this involves secrets and stuff that we can't provide out of the box.

The example app in the central repo has a lot of examples for various things, that may be helpful to look at. https://github.com/backstage/backstage/blob/master/app-config.yaml#L281

May I suggest that instead of posting a bunch of questions as bugs, you may visit us on Discord instead and ask specific questions like how to configure google auth? https://discord.gg/MUpMjP2
