### ISSUE TITLE
Does the `getIdToken` method on the `IdentityApi` has to return a `Promise` ? 

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#4876]
I do not see a reason why `getIdToken` has to return a `Promise<string | undefined>`. 

In https://github.com/backstage/backstage/blob/master/packages/core-api/src/apis/definitions/IdentityApi.ts#L45, functions like `getProfileInfo` and `getUserId` are already synchronous. 

When a user is logged-in, the `IdToken` is readily available (could be undefined in case of tests or mocked-in users). 
I do not see any reason this has to be a `Promise` as it simply returns the value of a property in an object. 

## Feature Suggestion

De-promisfy `getIdToken` so that it returns `string | undefined` rather than `Promise<string | undefined>` 

## Context
The driving reason behind this is that it Promises make it very hard to compose with other code. 

We were trying to build a plugin to read the token information to fetch the claims, but the presence of a `Promise`, which, IMHO, is unnecessary, makes it harder to compose with other existing code.

**Comment by Rugvip** [comment]
We've chosen a pull-based model for all authentication, as we think that provides a better UX and/or DX when you have multiple providers that you may or may not need at any point when using the app. By setting it up so that tokens are requested by the consumer we can lazily create the tokens when they're needed, rather than making sure they're available upfront. With a more eager model we'd have to make sure tokens are available upfront, which means we'd either be sending unnecessary login requests to the user, or have developers put a bunch of more granular barriers in place that ensures that tokens are loaded for different parts of the react tree.

With the overall auth system being pull-based in the frontend, we stick to having a similar implementation for the identity API as well. It's a lot more convenient if the identity API has a similar signature to the other auth API as you often end up implementing it in terms of another and would have to bridge it otherwise.

When composing code you generally move the fetching of the id token close to the request that is using it. You want to do this to make sure you're making the request with a fresh token, but it also more or less guarantees that you're already in an async method when requesting the token.
