### ISSUE TITLE
Plugins Page Update: Add core features

### ISSUE THREAD

**Issue by katz95** [backstage/backstage#4897]
<img width="1430" alt="Same cards, separated rows" src="https://user-images.githubusercontent.com/61153904/110525223-9f7c8900-8114-11eb-96e1-dc643c6826dc.png">

Would love if someone could help us update the [Plugins page](https://backstage.io/plugins) on backstage.io. We want to add the four Backstage plugins up top. Attaching a ZIP file of the SVGs for the icons (they should be transparent, btw). Let me know if you have any questions!!

[SVG-20210309T191814Z-001.zip](https://github.com/backstage/backstage/files/6110897/SVG-20210309T191814Z-001.zip)

**Comment by BA1RY** [comment]
Hi @katz95 , I would like to work on this 😄

**Comment by katz95** [comment]
@fengypants @AlleyWei  can you assist with these SVGs?

**Comment by fengypants** [comment]
Hi @benjdlambert - Here's a new batch of SVGs, including the K8s icon. These have also been updated with fully transparent fills, so they should look nicer against the off-black background. Let us know if there are any issues with this batch. Thank you!

[SVG-BOSS-features-210317.zip](https://github.com/backstage/backstage/files/6158280/SVG-BOSS-features-210317.zip)

**Comment by BA1RY** [comment]
Hi @fengypants Thank you. But, aren't those svg's different from the ones displayed here https://github.com/backstage/backstage/issues/4897#issue-826503762 ? (Because, only a part of those svg's is being used)

@benjdlambert My current implementation involves, adding data for the new core feature plugins in https://github.com/backstage/backstage/tree/master/microsite/data/plugins and then using the `filter(plugin => plugin.category === 'Core Feature')` to selectively filter them and display.  It's displayed like this.

![image](https://user-images.githubusercontent.com/10570968/111608910-bcdde100-87ff-11eb-93c3-fc0f4541fe1a.png)

But, core feature plugins not displayed in the same order as https://github.com/backstage/backstage/issues/4897#issue-826503762 as it's sorted alphabetically. Is this fine?
(or)
should I implement this by
- write code to display 4 of them individually?
- adding another attribute like `order` and sort them accordingly?

**Comment by fengypants** [comment]
@BA1RY Ah, I think the images in the original comp were animated GIFs, so the screenshot just captured them in the middle of animating. The SVGs are the static versions of the same icons. 

The images are looking good in your screenshot. But can they be more similar in size to each other? Kubernetes looks nice and big, but the others are feeling small in comparison.

Regarding the order, since there are only 4 of them, we thought it would make more sense to put them in the same order as they are on the microsite homepage, with Kubernetes last. (I don't have an opinion on how to implement that technically.)

**Comment by BA1RY** [comment]
Hi @fengypants thanks for clarifying. Will try to implement it.

@benjaminr @OrkoHunter Can i get your views on this https://github.com/backstage/backstage/issues/4897#issuecomment-801801460 with respect to coding part?

**Comment by adamdmharvey** [comment]
Humble opinion: [KISS Principle](https://en.wikipedia.org/wiki/KISS_principle). There are only four core features. Even if there are 5 in the future, maybe they should be just hardcoded? 😁

**Comment by BA1RY** [comment]
@adamdmharvey Haha makes sense. 😁
It's just that I was wondering whether there were more plugins incoming in future. Thanks for clarifying. 😄

**Comment by adamdmharvey** [comment]
Yah.  I would for sure think in future all of the various plugins MIGHT be listed (dozens, for sure).  But (and I'm guessing here) since the intent is to purposely elevate the "core features", if you see them reflected in the documentation, marketing materials, and the suggestions here in, it really sounds like the focus is only on those four.

**Comment by fengypants** [comment]
@adamdmharvey Yep, that's what we were thinking — give more visibility to the four core features on this page (especially since the Kubernetes one is also technically a plugin). And we are not expecting a bunch of additional ones in the near future.

@BA1RY Third time's a charm with the SVGs. Here's a new set you can use — these should be in better proportion with each other now — without any need for manual adjustments on your end. As long as the SVGs are set to display at the same size, they should all appear balanced with each other.

[SVG-BOSS-features-210325.zip](https://github.com/backstage/backstage/files/6206655/SVG-BOSS-features-210325.zip)

**Comment by benjdlambert** [comment]
@BA1RY I think that's fine. Same as @adamdmharvey said, keep it simple. :shipit:

**Comment by BA1RY** [comment]
Hi @katz95 @fengypants @benjdlambert   I've made a PR (#5151). Please have a look at it and let me know if there are any changes to be made. 😄
