### ISSUE TITLE
Expose id and className in plugin pages

### ISSUE THREAD

**Issue by yousifalraheem** [backstage/backstage#5067]
## Feature Suggestion

Please allow us to pass `id` or `className` to plugins that represent pages.

## Possible Implementation
Just expose `id` and `className`

## Context
Styling an element in the UI is really tough since you guys have decided to go with Styled components which not only adds performance issues but changes the class names with every build. Making it impossible to select with CSS. For example, I'm trying to customize the look of few things in the service catalog and I would expect something like this:

```tsx
<CatalogIndexPage id='service-catalog' />
```

This allows me to easily use CSS selector to target elements only inside the service catalog:
```css
#service-catalog > div {
  // rules here
}
```

### Other solutions that might work
Instead of exposing `id` and `className` which might be of a hassle depending on the complexity. Just add a `className` that is not touched by Styled Components. For example, the service catalog page would have a selectable class name like
```html
<div id="root">
  <div class="layout jss6 jss7">
    <div class="service-catalog jss514">
      <div class="service-catalog-tabs jss2259">
      <!-- and so on -->
```

A `data-testid` would also be enough since I can use it as a selector 
```css
#root [data-testid="service-catalog"] {
  // rules
}
```
Just give us anything

**Comment by freben** [comment]
The MUI docs have this page on customization 

https://material-ui.com/customization/components

Those are "the MUI way" of doing things.

On our end, it's probably about becoming better at making conveniently stylable components, for example using the `classes` prop standard like [here](https://github.com/backstage/backstage/blob/master/packages/core/src/layout/ItemCard/ItemCardHeader.tsx#L69)

**Comment by yousifalraheem** [comment]
That would work if you're exposing `className` or `classes` prop, but that's not the case currently. Use the following example, try to pass `classes` to `CatalogIndexPage`:
```tsx
import { CatalogIndexPage } from '@backstage/plugin-catalog';
import { Route } from 'react-router';

const Component = () => (
  <Route
    path='catalog'
    element={<CatalogIndexPage />}
  />
);
```

The only props that it accepts are `key` and `initiallySelectedFilter`

**Comment by benjdlambert** [comment]
If we take a step back here, I think that approaching styling of things inside the any plugin using arbriatary CSS is going to cause problem amongst updates, the DOM changes throughout releases of plugins that you don't control will cause frequent breakages to the page. So whilst we can add these overridable things to each plugin, I still would bear in mind that it's could get tricky.

@freben, maybe this is a good time for the plugin manifest? We could wrap the router in a boundary which has an `id="@backstage/plugin-catalog"` or something?

Otherwise, we can use the `data-test-id` property which would be used for some E2E tests, but again they're not always guaranteed to be there because things change in plugins.

There's also the possibility of forking the `catalog` plugin, but it depends how much you want to change in it.

**Comment by freben** [comment]
I think that our approach will be to support a couple of targeted, well contained customizations in default components - and then make it easy to replace them wholesale with your own tweaked versions, composing little pieces together. I.e. there may be a `DefaultCatalogPage`, but if you don't like it you can route to your own which uses some of the `DefaultCatalogFilters`, `DefaultCatalogTable` etc, or substitute your own.

I'm fine with us establishing the pattern of doing more of the `classes` thing I linked to. This will probably be asked for more and more, and is not a huge burden on us to provide. But prop drilling specific behaviors through the layers and making things excessively tweakable is just asking for trouble long term

**Comment by yousifalraheem** [comment]
- Honestly, I would take any solution that let's me use a CSS selector to target an element in a page. `id`, `data-testid`, `class`, even `aria-label="catalog-header"`. There are many reasons to despise Styled Components including one that caused tremendous performance cut-back. In one plugin for **C**ontinuous **D**eployment **P**latform (CDP), I ran an analysis and found some shocking findings. By replacing Styled components with good old CSS, we improved the performance by 83%. The UI was snappy again. This discussion is long but the gist of it is, a support for CSS is much needed for those of us who finds it crucial. You can see a graph of a function execution time that renders thousands of lines of logs below:

> ![styled-perf](https://user-images.githubusercontent.com/10633734/112646840-300ed500-8e48-11eb-9102-2bcd560c59da.png)

- I don't think you should be worried that much about side-effects from updates. We would expect such changes in `v0.x.x`. The user takes full responsibility of catching-up to changes until it goes to the first major release `v1.x.x`. There are countless times where we update backstage packages and it breaks our code, you guys made sure you have [documented these changes](https://github.com/backstage/backstage/blob/master/CHANGELOG.md) very well. Plus, you can write these CSS classes or IDs in a way that doesn't really causes much breakage. For example, only place them on top-level components, i.e. page, header, article, sidemenu.

- I could fork it, but then it would be very difficult to maintain that fork giving the frequency of all the great updates you guys are releasing 🤘.

**Comment by benjdlambert** [comment]
Yeah, I appreciate your concerns with us using something similar to `styled-components`. But the truth is, is that the benefit that `mui` gives us with clear established and battle tested UI patterns and developer benefit of CSS in JS really outweighs the slight performance cost that we pay for it.

I get that it's frustrating when you just want to style some certain parts and can't because of the classname's that it produces.

We're working on the customisation part and trying to make things more customizable, but the truth is the only way right now is the use the `mui` and our [custom theme](https://backstage.io/docs/getting-started/app-custom-theme#creating-a-custom-theme) rather than arbitrary css route.

We might further down the road automatically add these wrapping divs that can identify plugins, but it's not something that we're working on right now or have a plan for.
