### ISSUE TITLE
Customizing Home table view of the Catalog plugin

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#5070]
As a central feature of Backstage, The catalog plugin defines how users interact with Backstage / Backstage application. 
To provide a good experience we are looking to implement some customization on the home view of the catalog frontend. 

The feature suggestions are as follows:

## Feature Suggestion
1. Custom  (names) and  for the title of the columns on the home . Currently we do not have a `System` model in place and there is no way to hide/rename the `System` column on the home grid
2. Custom or the ability to select the fields in the Entity or the `spec` of the Entity to be displayed on the home grid. 
Currently these seem to be `name`, `system`, `owner`, `lifecycle`, `tags` and `action`. 
we think it will be nice to have the list of columns to be choose-able (with a default that is provided out of the box). 
3. Ability to attach sort functions to these columns. 
A Usecase we have is for applications that need to be reviewed for operational purposes. This information is added to the `spec` of an application and a custom `Needs Review` or `Reviewed Since` column that is sortable will help our engineering related users track applications and their status.
4. Customize and add filters for filtering the results (currently filtering can be done only using tag values). 
5. Customize what `owners` or `groups` by default, the initial list of Entities  are shown. 
Currently this list is by default the `Owned` list of Entities, entities `Starred` by the user and `ALL` entities. 
A nice feature would be to allow the User to save a list of groups or `owner` fields , so that the visualization  brings up all the Entities owned by the saved groups as a quick way to visualize on load, all the relevant application, instead of starring them one by one. 

We think that this customization has merit and would look forward to make the contributions in the open source project and seek feedback from the maintainers and the rest of the community about this.

**Comment by freben** [comment]
Let me start by saying that the catalog is not meant to be the start page. It's just there for now, because we're in the process of settling what the most useful and effective Home / Manage pages will be. Ideally the current catalog page will be deferred to the back of people's minds and rarely visited, mostly replaced by Manage (showing what's yours) and Search (finding anything).

This tells me that not too much effort should be spent on it. Some, sure, but not too much :)

There's two ways to go about this. Either we make the builtin catalog page super flexible and have a ton of options - or, we make it easy to build your own catalog page and route to that instead of the default one. It may be the case that we could make "atoms" of functionality exposed in easy-to-compose ways. Like for example, the filtering system could be made more standalone. And the table could be better componentised and detached from the filtering system. Etc

As for features:

Column selection - sure, but maybe as a static prop to pass in or similar? We probably don't want to go overboard at this point with personal (persisted) column settings, I think.

Sorting - absolutely. There's surely something to be leveraged built-in in the underlying table.

Filters - yes, but, then it's starting to become a bit trickier. Now you have to start tying pluggable visual components into the filter/reduce steps as well.

**Comment by freben** [comment]
linking to this one too https://github.com/backstage/backstage/pull/4845

**Comment by GoWind** [comment]
> Let me start by saying that the catalog is not meant to be the start page.

Yes, agreed. My wording was imprecise.We have a home page that is different from the catalog.
 We observed users spending a big chunk of time on the Catalog plugin, hence we wanted to improve the offering.

> Column selection - sure, but maybe as a static prop to pass in or similar? We probably don't want to go overboard at this point with personal (persisted) column settings, I think.

We do not want to provide personalization at the moment. Just a static props to configure the columns at build time is sufficient.

> Sorting - absolutely. There's surely something to be leveraged built-in in the underlying table.

Sounds great. I would propose that we proceed in a piecewise fashion.

Enable `static` column selection/naming and provide sorting functions via `props`. This will solve the most urgent usecases at the moment. 

While doing this we can consider which approach suits best  : A flexible catalog page that can be re-configured heavily or a composable catalog that requires the user to put together the page as they see fit. 

I would lean towards the latter, as it removes a lot of burden on the platform as to think about what should be configurable and how, but I will discuss this with the frontend engineers in my team to identify a good solution, based on  their experience.

**Comment by benjdlambert** [comment]
Hey @gowind, hopefully the work that @timbonicus did should help with your customization needs, you can find some docs here: https://backstage.io/docs/features/software-catalog/catalog-customization. If there's anything else thats missing maybe you can re-open this ticket? Otherwise are we good to close?

**Comment by GoWind** [comment]
Hi @benjdlambert  : Thanks a lot !
 I will check with my team to see if it suits us (I am mostly the backend guy :sweat_smile: ), if not re-open  the ticket . You  can close this if you'd like.

**Comment by benjdlambert** [comment]
Perfect - thanks!
