### ISSUE TITLE
Logout for every page refresh

### ISSUE THREAD

**Issue by erdoganoksuz** [backstage/backstage#5109]
## Expected Behavior

I must not log out until my token expires.

## Current Behavior

When i refresh any page backstage log out my user and expects log in again.
## Possible Solution

I think there is a problem with timezones or expiration dates.

## Steps to Reproduce

https://user-images.githubusercontent.com/13199681/112480037-a945f380-8d86-11eb-8919-942f00af59fb.mov

1. Create fresh backstage app.
2. Select postgresql for database.
3. Add google auth
4. login and refresh page.
5. I get same result in safari and firefox.
## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by adamdmharvey** [comment]
@erdoganoksuz I notice in your screen cap, that every time you click refresh your browser is blocking a popup.  If you turn off your popup blocker, and attempt again, do you know what is popping up? Maybe it has useful info in the msg that helps identify root cause? OR you're being redirected in some way?

**Comment by erdoganoksuz** [comment]
> @erdoganoksuz I notice in your screen cap, that every time you click refresh your browser is blocking a popup. If you turn off your popup blocker, and attempt again, do you know what is popping up? Maybe it has useful info in the msg that helps identify root cause? OR you're being redirected in some way?

It's opening by google auth and shows login with google account. I closed blocking popup feature but nothing changed did you try steps?

**Comment by adamdmharvey** [comment]
@erdoganoksuz If it's opening constantly, it sounds like it's not actually authenticated or having a valid token?

I did not try any of those steps as I have no access to a Google auth provider; just saw you post in Discord, opened your ticket, and saw your quick video, and noticed the popup blocker.

All in all, constant popping up doesn't sound like accurate behavior I'd say for sure!

**Comment by erdoganoksuz** [comment]
> @erdoganoksuz If it's opening constantly, it sounds like it's not actually authenticated or having a valid token?
> 
> I did not try any of those steps as I have no access to a Google auth provider; just saw you post in Discord, opened your ticket, and saw your quick video, and noticed the popup blocker.
> 
> All in all, constant popping up doesn't sound like accurate behavior I'd say for sure!

It's have valid token and authenticated successfully you can see my user name on the header.

**Comment by sjuxax** [comment]
@adamdmharvey To clarify, I'm the one raising the issue on Discord. We're getting this same behavior with a custom OAuth2 integration to a PingFederate provider. Like I said on Discord, I've debugged it part-way, and it seems to try to acquire a new `access_token` via the `refresh_token` and kicks back to the login page when it fails to do so. Then, when the user clicks "Sign In" again, Backstage acquires a new `access_token` from Ping without having to prompt the user for credentials (since their previous sign-in is still valid on the SSO side) and the login goes through.

The questions are probably why a) Backstage is always trying to use the `refresh_token` on a new page load, even if the current `access_token` isn't due to expire anytime soon; b) whether our SSO-side configuration is invalid, leading the `refresh_token` codepath to fail and Backstage end up in this failure mode; and c) if our SSO-side configuration _is_ valid, why Backstage isn't able to use the `refresh_token` as expected.

**Comment by rmanny** [comment]
I am also seeing this with both OIDC (Dex) and Azure AD SSO

**Comment by younky-yang** [comment]
same behavior with Azure AD SSO.

**Comment by OrkoHunter** [comment]
I am able to reproduce this error on a newly created Backstage app with Google auth provider. After signing in, if I reload the page, or even re-open Backstage in a new tab, I am being logged out.

Looking into it...

**Comment by OrkoHunter** [comment]
Just to share my eureka moment of finding the reason for this bug -

This happens if I have added a SignInPage component with a single `provider` prop e.g.

```tsx
const app = createApp({
  apis,
  bindRoutes({ bind }) {
  <...more stuff...>
  components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        provider={googleProvider}
      />
    ),
  },
});
```

If I replace this with multiple providers, I'm no longer able to reproduce the error. e.g.

```diff
const app = createApp({
  apis,
  bindRoutes({ bind }) {
  <...more stuff...>
  components: {
    SignInPage: props => (
      <SignInPage
        {...props}
---     provider={googleProvider}
+++     providers=['guest', googleProvider]
      />
    ),
  },
});
```

My initial hunch is that there is a potential difference in implementation of [SingleSignInPage](https://github.com/backstage/backstage/blob/0fafe147d2a438bfb295a802aa059d963cabf47b/packages/core/src/layout/SignInPage/SignInPage.tsx#L81) and [MultiSignInPage](https://github.com/backstage/backstage/blob/master/packages/core/src/layout/SignInPage/SignInPage.tsx#L43) components. Hoping to create a PR soon 🤞

**Comment by falconbin** [comment]
@OrkoHunter , the sign page still show when refresh after login. I think we need to skip login page by checking if user has already login. Following code has been tested locally, could you review and try:
![image](https://user-images.githubusercontent.com/20329141/118603427-78ae9300-b7e6-11eb-8d39-3c041b6220ef.png)

**Comment by OrkoHunter** [comment]
> the sign page still show when refresh after login

@falconbin Hey! I believe you mean that the sign-in page shows up for a split second on refresh, but disappears if the user is already logged in?

I think it's worth making an effort to address that as well - let me try out your proposal in the PR :)

**Comment by falconbin** [comment]
> > the sign page still show when refresh after login
> 
> @falconbin Hey! I believe you mean that the sign-in page shows up for a split second on refresh, but disappears if the user is already logged in?
> 
> I think it's worth making an effort to address that as well - let me try out your proposal in the PR :)

yes, exactly.

**Comment by OrkoHunter** [comment]
Thanks for the suggestion @falconbin - updated the PR with it #5702 and it works well!
