### ISSUE TITLE
Support obtaining user auth tokens to pass to scaffolder process 

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#5214]
## Feature Suggestion

Support a way to request user auth tokens for external services as part of the scaffolder frontend and pass them to the backend task process in order to call out to external APIs on behalf of the user.

## Possible Implementation

The may involve refactoring `createTemplateAction` to allow custom actions to specify auth provider(s) and scopes it requires which tells the frontend to retrieve (or trigger the auth flow) the necessary user auth tokens and pass it to the backend task process possibly in the `ctx` object. One thing to consider with this is normalizing the providers and set of scopes defined among all actions in the scaffolder template to trigger an auth flow once per provider and obtain tokens with scopes to satisfy the requirements of all relevant actions. 

If a scaffold template requires auth with multiple providers, its not really great UI to auto open multiple popups for each auth flow so an UI consideration may be to present the user with a form where they click each provider they need to auth with and it allows them to proceed once the form detects each provider auth has been satisfied. 

In terms of defining custom auth providers, it looks like Backstage admins would do this by adding a new auth provider according to the [docs](https://backstage.io/docs/auth/add-auth-provider) in conjunction with installing custom actions that talks to the new external service. Is it possible to make this pluggable via a standalone Backstage app? 

## Context
The new `v1beta2` template schema is awesome and now allows consumers to build template workflows that go beyond basic repo scaffolding like running custom actions to set up related infrastructure. In order to do this we wrote custom actions that call out to external APIs like Heroku to connect to and deploy our new repo. 

However, in order to fully support this we need some way for the scaffolder frontend to trigger a user Oauth flow so they can sign in to and grant access to associated external services.

**Comment by Rugvip** [comment]
This and #5215 is definitely something that we want to add. We want to be a bit careful about the secret handling though, giving it some special treatment throughout the flow, especially how they're stored in the scaffolder-backend DB.

The frontend auth system actually already takes care of all the deduplication of requests, scope merging, and displaying a dialog with all the requests to the user, so expecting we get all of that for free :grin:

Regarding implementation, the fewer things we have to add the better. I was thinking whether it would make sense to simply implement login (and #5215) as special UI components to add to the schema, but then you end up with the problem of proper handling of the secrets. Could be that it makes sense for #5215, but for tokens we just do a more direct list of things we want, essentially

```
tokens: [{
  provider: 'github',
  scope: 'repo user'
}]
```

Again this could cause trouble for organizations that for example mix in multiple GitHub instances, but tbh I think that's something that needs to be solved at a more core frontend authentication level rather than here, so would be fine with just not supporting that yet until we figure that out. Another tricky bit is that we don't actually have a mapping of `provider id -> auth api` in the frontend atm, so we'd already have to add that there.

Finally, this issue is up for grabs if someone wants to take a stab at it. Given the complexity and number of systems that this touches it'd be safest to outline and settling a design before sending PRs :grin:

**Comment by kuangp** [comment]
I would be willing to take a stab at this if no one else does to get the ball rolling here. I'll probably need some more guidance here as I'm not too familiar with the internals of the scaffolder/auth provider setup currently. If someone can help point me to the potential areas that this may touch upon, I'll start doing my homework and try to outline a possible design.

**Comment by benjdlambert** [comment]
@kuangp I'd wait until the preceding PR is complete first as that will likely share the same column in that PR.

**Comment by ConnorDY** [comment]
Any updates on this? We'd love to have this ability for our use case. :)

**Comment by freben** [comment]
This is still up for grabs.

**Comment by sagacity** [comment]
@freben My team would like to spend some time on this. Would we need to wait until https://github.com/backstage/backstage/pull/7002 is merged? Or are there already some ways we could move forward with this?

**Comment by benjdlambert** [comment]
@sagacity I'd suggest that you hold off on this a little bit, as we were probably going to do it to prove that #7002 is valid for use. It's a really interesting use case for that library, and probably going to be a lot of thought around how best to do it.

**Comment by benjdlambert** [comment]
Here's the RFC that we are thinking will close this: https://github.com/backstage/backstage/issues/7684

**Comment by benjdlambert** [comment]
Closed by #9168
