### ISSUE TITLE
APIs explorer with pagination

### ISSUE THREAD

**Issue by anastasiarods** [backstage/backstage#5310]
## Feature Suggestion

Add pagination that is supported by `catalog-backend` to `api-docs` plugin.

## Possible Implementation
Extend `api-docs` components and `catalog-client` to support pagination.

## Context
At Zalando, we would like to add `api-docs` plugin to our system. The absence of pagination prevents us to introduce it since we are having >1k APIs. If there is no ongoing work or if it would be useful to other people, I would be happy to contribute to it.

**Comment by Fox32** [comment]
That would probably require that we move the filtering from frontend to backend, but feel free to create a PR! #4007 will help a bit with a large amount of APIs, but in the long term paging might still be desired.

**Comment by freben** [comment]
@ougfh Let us know if you want to be assigned to the issue! I believe that the catalog backend should be ready to support what you need to do. If the filtering isn't changed to be backend driven, there may still be the ugly option of at least "streaming" in data until the current page is full, I guess...

I wonder if the filter box (that filters client-side) really works when there's paging.

One more thought. The catalog API supports limiting what entity fields that are returned in responses. If you limit the fields to only exactly what the table needs to render itself, then the response payload will probably be a tiny fraction of what it is when all fields are returned. It may be that thousands of APIs actually won't take long at all to fetch from the service if they are small.

**Comment by Fox32** [comment]
> It may be that thousands of APIs actually won't take long at all to fetch from the service if they are small.

Yeah, filtering out the `definition` field could already be a big step. The rest of the data should be quite small.

**Comment by ougfh** [comment]
@Fox32 @freben I've started to look into how to do it, but it seems that in `material-table` it is required to have a total count for pagination. The total count is currently not returned by the catalog backend. I wonder how it can be introduced in the table on the client-side, maybe you had ideas?

Filtering would really significantly reduce payload and solve our case as well! It looks like schema definition is not used in the table for search or filtering anyway. I can open a PR with it.

**Comment by gasandov** [comment]
@ougfh did you received any kind of feedback so far? If not let's chat and I can help you out into this contribution

**Comment by freben** [comment]
@gasandov If you don't hear back, maybe it would be sensible to add a basic `fields` argument to the client call and make a PR for it - I think a oneliner fix here may have a great impact

**Comment by freben** [comment]
@gasandov Oh strike that - 20 days ago a fields selector was actually added.

https://github.com/backstage/backstage/pull/5435

So what remains is to add pagination to the table itself. This should be doable fairly easily

https://github.com/backstage/backstage/blob/master/plugins/api-docs/src/components/ApiExplorerTable/ApiExplorerTable.tsx#L202

And there are other usages of that same Table component throughout the main repo that can serve as inspiration

**Comment by djamaile** [comment]
@ougfh are you picking this up? Else I can give it a shot.

**Comment by ougfh** [comment]
@djamaile I will try to do it (probably today), if no - I will leave a message here

**Comment by kuangp** [comment]
Apologies here as it seems I removed the performance improvement from https://github.com/backstage/backstage/pull/5435 with my #5984 change

It looks like `EntityListProvider` will need to support some sort of entity field selection configurability (maybe similar to how the custom filters are applied?) 

@timbonicus it looks like you left a TODO here that considered this https://github.com/backstage/backstage/blob/112fd4ddb36057065f43a83037bbf363b1cc474a/plugins/catalog-react/src/hooks/useEntityListProvider.tsx#L117-L119

If you had some implementation in mind for this, I would be happy to contribute here

**Comment by timbonicus** [comment]
@kuangp The challenge is the custom table columns that `ApiExplorerPage` accepts, added _after_ #5435; these make the fields required harder to reason about. The columns are typed with [EntityRow](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/types.ts#L18) which has a complete `Entity` type available. If you return a partial (field-filtered) entity, you break this contract. This would need to become `Partial<Entity>` which feels a bit uncomfortable for an author of custom columns. How can I guarantee that I have the data I need?

Beyond that, you need to get the actual list of fields required. I think that should be possible using `Column.field` on the columns plus any default fields we need.

As another idea, I think it's _very specifically_ the `definition` field that's of concern in this case. If you could exclude that field, reasoning about the rest might be a waste of time. So maybe `catalog-backend` should have a way to _exclude_ certain fields, instead of worrying about includes here?

Yet another reference is the [attachment store PR](https://github.com/backstage/backstage/pull/5323); maybe catalog entity definitions shouldn't be carrying such a heavy payload, and this should be stored elsewhere and queried explicitly when desired? I mention it for reference, this is probably the least viable immediate solution here.

**Comment by kuangp** [comment]
FYI for others, I'm using the following workaround to override the `catalogApiRef` on my Backstage instance to strip out loading API definitions in the explorer view:
```ts
export class CatalogClientExt extends CatalogClientWrapper {
  async getEntities(
    request?: CatalogEntitiesRequest,
    options?: CatalogRequestOptions,
  ): Promise<CatalogListResponse<Entity>> {
    const filter = [request?.filter].flat().filter(Boolean);
    if (request && !request.fields && filter.length === 1 && filter[0]?.kind === 'api') {
      request.fields = [
        'apiVersion',
        'kind',
        'metadata',
        'relations',
        'status',
        'spec.lifecycle',
        'spec.owner',
        'spec.type',
        'spec.system',
      ];
    }
    return super.getEntities(request, options);
  }
}
```
```ts
// app/src/apis.ts
...
  createApiFactory({
    api: catalogApiRef,
    deps: { discoveryApi: discoveryApiRef, identityApi: identityApiRef },
    factory: ({ discoveryApi, identityApi }) =>
      new CatalogClientExt({
        client: new CatalogClient({ discoveryApi }),
        identityApi,
      }),
  }),
...
```
This extends the default [catalog client](https://github.com/backstage/backstage/blob/a2fbdfde360d06a6c7c94ded4271f8ecaee907fb/plugins/catalog/src/plugin.ts#L37-L45) to modify the request made by the API explorer page. I also put up this [PR](https://github.com/backstage/backstage/pull/6513) to export `CatalogClientWrapper` in order to inherit from it (I've forked the class for the time being). Hopefully this also helps others for now. 

I think the [attachment store](https://github.com/backstage/backstage/pull/5323) and actual support for pagination is the most appropriate solution here for optimizing load times.

**Comment by freben** [comment]
I want to explore a model where columns and filters explicitly ask for the fields that they want. That way the surrounding context can choose to fetch exactly the necessary fields and no more.

**Comment by timbonicus** [comment]
I started on #11699 in the vein that freben mentions, but this may be overcome by #12247.
