### ISSUE TITLE
Access entity schema definitions via API

### ISSUE THREAD

**Issue by andaziar** [backstage/backstage#5344]
## Feature Suggestion

We have services that need to validate file contents containing `Component`-entries and it would be nice if we could query our backstage instance to fetch the json schema for a specific entity kind and use that to validate the yaml data. Without this, I guess we would be forced to create and maintain separated JSON schemas of all entities.

**Comment by andaziar** [comment]
Would a plugin be preferable for solving this? In that case it would simply expose an endpoint for fetching a json schema for a specific entity kind

**Comment by freben** [comment]
Hi!

This is a little bit tricky. Yes you could validate source files "at rest", and it may work for a lot of simpler cases, but may not always be what you want.

Some background: As the catalog runs, it reads input files basically as raw unstructured data (it only has to pass the very most basic entity envelope requirements, nothing kind specific). Then actual software, the set of so called processors, run on that data and may add in additional fields or change around values or migrate from one version to another or similar. Only after all that, validation is run on the end result. This means that there's a potential disconnect between the input data, and the schemas used for validation. One common example is that the `Component` kind requires that `spec.owner` is present, but there's a `CodeOwnersProcessor` that can populate it for you in-flight if you left it out of the source.

We're rewriting the ingestion part now. We're considering this particular use case, maybe in the form of essentially dry-run processing an input that you POST to the service so that it can go through all of the same steps that the production service will really subject it to in the end.

We could also expose the schemas, but maybe then it's best if they make everything recursively optional or something, just so that only the actual provided values are checked as expected. Which may still not be all you need, but helps slightly.

**Comment by andaziar** [comment]
Hehe tricky indeed. Thanks for highlighting some cases that I didn't know about. With all of that being said, it sounds like validating directly with the schemas will be a bit too restrictive? Especially if the data hasn't gone through all of the processors that may or may not do in-flight changes?

I like the idea of a dry-run approach. Anywhere I can follow your work on rewriting the ingestion?

**Comment by freben** [comment]
You can check our [current project board](https://github.com/backstage/backstage/projects/4). We are basically gradually building out the `mob/catalog-refactor`, on a technical level.

**Comment by andaziar** [comment]
Thanks!

**Comment by timbonicus** [comment]
Somewhat related: #4336 and #4834

**Comment by Xantier** [comment]
We have started to do some initial work to add an external validation based on these schemas to see if the `catalog-info.yaml` files are valid and values are formatted properly. It is usable as a GitHub action in repo workflows if people want to start using it. 

The flow is to simply run through providers and validators that @backstage/catalog-model exposes initially. The second step the validator does is to run through validation of a separate annotations JSON schema file that lists well-known and some other widely used annotations and validates their format based on regex/provided known formats. 

@dtuite mentioned this could be something to contribute to Backstage project directly (maybe the annotations schema at least), @freben what would be your thoughts on merging in a contribution based on this? 

The repo can be found from https://github.com/RoadieHQ/backstage-entity-validator

**Comment by freben** [comment]
Ongoing work that exposes entity validation from catalog-model https://github.com/backstage/backstage/pull/5811
