### ISSUE TITLE
[Plugin] AWS ECS

### ISSUE THREAD

**Issue by grv231** [backstage/backstage#5355]
## Summary

Similar to Kubernetes Plugin, AWS ECS to show up as a tab when viewing entities in catalog

## Project website (if applicable)

https://aws.amazon.com/ecs/

## Context

In our org, apart from Kubernetes, lot of services run in ECS + Fargate clusters. This plugin can assist service owners in looking at the state of the ECS clusters (similar to Kubernetes) in which services are running which are already present in backstage

**Comment by iniinikoski** [comment]
Has anyone started to work on this / planning this yet...? Just thinking out loud of some joint effort...

**Comment by Rugvip** [comment]
@iniinikoski Not that we know of, still up for grabs 😁

**Comment by marcus-crane** [comment]
I got a bit carried away this weekend and started hacking up the Kubernetes plugin to build something similar for ECS

I got a fair amount of a plugin working and while the concepts mostly translate across, there is still a bunch of fiddling needed for the UI to make sense.

Once I get it fleshed out to where it actually uses the AWS APIs (I'm currently using fixtures as I haven't written the backend portion yet), I'll be happy to submit it to the Backstage monorepo 🙂 

Here's a preview of what I've got so far for anyone curious

https://user-images.githubusercontent.com/14816406/180638982-e5c5ffdc-6bfe-409b-b825-066178fbeadf.mp4

**Comment by nvpnathan** [comment]
> Once I get it fleshed out to where it actually uses the AWS APIs (I'm currently using fixtures as I haven't written the backend portion yet), I'll be happy to submit it to the Backstage monorepo 🙂

Hello Marcus, this is fantastic! Would love to help contribute/collaborate on this with you!
-nathan

**Comment by marcus-crane** [comment]
> Hello Marcus, this is fantastic! Would love to help contribute/collaborate on this with you!
> 
> -nathan

I'll try to wrap up the base of what I've got for review shortly and then it'll be easier to collaborate with something already upstreamed to work from 🙂

**Comment by marcus-crane** [comment]
I haven't looked at this plugin in a bit but I picked it up again last night and wired it up to the backend, where the previous video was just local development.

Codebase wise, it's quite a mess but my intention here anyway was to get something working that I can deploy internally and then basically take what worked (from the Kubernetes plugin that I largely hacked up) and what didn't in order to make something more reasonable.

Kubernetes has support for many generic resources whereas ECS only has a few known resources so the ECS codebase probably doesn't benefit very much from keeping things really generic.

The annotation I'm targeting so far is `aws.amazon.com/ecs-service-arn` where the value is the ARN for an ECS service eg; `arn:aws:ecs:us-east-1:123456789:service/blah-production/backstage-production`

Many services we have internally don't use the newer/long form ECS ARN above but you can fake construct it since the backend just pulls apart the `service/blah-production/backstage-production` part rather than the ARN being literally submitted to AWS.

I believe the main difference with the older ARNs was just that the ARN didn't include the cluster which is required to "describe" a service along with the service name in the newer AWS SDKs.

https://user-images.githubusercontent.com/14816406/188442008-c6f6b37c-abee-4582-8f3a-c82b081d9aa8.mp4

**Comment by marcus-crane** [comment]
I'm also keeping an eye on https://github.com/backstage/backstage/issues/12844 as far as ARN naming and credential loading. The above is just pulling credentials from my local environment and presumably it'll pick up on credentials from an ECS instance (circumventing the Backstage config) in the meantime but of course, it should consult the AWS integration in the Backstage config as everything else does

**Comment by nvpnathan** [comment]
Hi Marcus, this is great progress! Would it be possible to make your contributions public? 

> Codebase wise, it's quite a mess but my intention here anyway was to get something working that I can deploy internally and then basically take what worked (from the Kubernetes plugin that I largely hacked up) and what didn't in order to make something more reasonable.

**Comment by adamdmharvey** [comment]
Also super interested in this.  We love the k8s plugin, but as noted in the top of this issue, we have enough apps in ECS to warrant this providing a lot of value.  Any chance to open source even parts of this that others might be able to pick up?

**Comment by cal5barton** [comment]
Any progress with getting this in as a plugin?

**Comment by marcus-crane** [comment]
Hello everyone,

While I've personally been out of the Backstage game for a little while, it looks like AWS themselves have pushed out a plugin in the past couple of days: https://github.com/awslabs/backstage-plugins-for-aws/tree/main/plugins/ecs

I'm not sure what scope it covers (maybe just healthchecks) but it seems like a good base to build extra functionality on top of rather than the now-outdated Kubernetes plugin I hacked together way back when

**Comment by camilaibs** [comment]
Thank you @marcus-crane , closing the issue 🙌🏻

**Comment by niallthomson** [comment]
Thanks for posting the link @marcus-crane 

Because this issue had so much attention: the ECS plugin that repository is an MVP which we can see being developed a lot further. Please create any feature requests or issues in that new repository and we'll do our best to develop it out to meet the community's needs.

**Comment by crickoliveira** [comment]
Good afternoon
The AWS library does not display the details as is done in the kubernetes lib, can you release the fork of the hack used in the kubernets lib?

**Comment by niallthomson** [comment]
We already have work in progress to add this to the AWS plugin.

https://github.com/awslabs/backstage-plugins-for-aws/issues/103
