### ISSUE TITLE
Import errors should be more readily available

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#5525]
## Feature Suggestion

The [GitHub discovery](https://backstage.io/docs/integrations/github/discovery) feature is great for automatically importing `catalog-info.yaml` files in a large organization.

One difference from manually importing `catalog-info.yaml` files, is that there is no opportunity to show error messages to the end user when they make a syntax error in their `catalog-info.yaml` file. In an organization where a Backstage admin team has easy access to the Backstage logs but end users do not, this can lead to confusion where users create broken `catalog-info.yaml` files and then wonder why they are not showing up. The admins may not be looking for the logging which syntax errors output.

## Possible Implementation

So far, we have two ideas to help this problem:
1. Linting. Perhaps a GitHub Pull Requests check could lint the `catalog-info.yaml` file before it is committed and check it for problems.
2. Displaying problems in the UI. If the GitHub discovery feature had a page in the UI where it could report errors then end users could go here to check why their `catalog-info.yaml` file wasn't appearing in Backstage.

**Comment by althafh** [comment]
Related discussion about the feedback loop in [#2876](https://github.com/backstage/backstage/issues/2876)

**Comment by dtuite** [comment]
Thanks @althafh, that does indeed look related.

The only unique part of this issue compared to #2876 is the idea of a `catalog-info.yaml` linter. @freben is that idea something that has come up at all? If the core team would prefer to handle the feedback loop in other ways then I can close this issue in favor of #2876.

**Comment by freben** [comment]
Thanks for raising this!

> 1. Linting. Perhaps a GitHub Pull Requests check could lint the `catalog-info.yaml` file before it is committed and check it for problems.

Yes - this is something we are looking at and have a strong internal desire for as well. As we build out the new catalog refresh engine, we are keeping an eye at making it possible to have sensible early feedback loops for entity owners. Its implementation will likely be similar to the dry-running that already happens when initially attempting to add locations.

> 2. Displaying problems in the UI. If the GitHub discovery feature had a page in the UI where it could report errors then end users could go here to check why their `catalog-info.yaml` file wasn't appearing in Backstage.

Absolutely, we need to find ways of surfacing errors in an easy-to-find and -digest way for end users. Maybe not based on processors, but on locations:

In the new refresh engine, things are internally treated as a directed graph whose nodes are locations / entities. If, while processing one thing, it emits a new thing, then that's kept track of. So if the processor in this case discovers a number of new locations, and some of those in turn are found to be Location entity yaml files, then that entire graph is kept track of. This means that we now have a greater ability to also attach errors to the actual nodes where the processing happens, and to be able to see errors "upwards" in that graph. Let's say for example that you have an entity file A which is a Location entity that points to file B. If processing of A breaks later on, B may suffer as a consequence. But when all of this is settled, we'll have the ability to display in Backstage not only B's issues, but its parents' issues.

The exact manner that this will happen in is still taking form. But the use case is on our radar.

**Comment by dtuite** [comment]
Sounds amazing @freben. Thanks for the update!

Sounds like this is all under control already so I will close in favor of #2876
