### ISSUE TITLE
[RFC] Remove "documentation" tab from CatalogPage

### ISSUE THREAD

**Issue by WillSewell** [backstage/backstage#5582]
**Status:** Open for comments

The other tabs correspond to [well known component types](https://backstage.io/docs/features/software-catalog/descriptor-format#spectype-required), but "documentation" does not. For that reason it seems strange that it is [hard coded as one of the tabs](https://github.com/backstage/backstage/blob/42f2adadc8b1e9c0967be017ae0c2aedbb611dba/plugins/catalog/src/components/CatalogPage/CatalogPage.tsx#L119-L122).

To be honest I'm not really sure what the use-cases are for documentation "components".

For context, the tab was suggested in https://github.com/backstage/backstage/issues/1090 and implemented in https://github.com/backstage/backstage/pull/1161.

## Need

We would rather not have this tab because we don't use the "documentation" component type.

## Proposal

Remove the tab.

## Alternatives

* Make "documentation" a well known component type
* Make the tabs configurable

## Risks

Users are relying on this tab existing.

**Comment by freben** [comment]
Hi! The catalog page is basically being reworked completely. The idea is that the tabs will disappear completely, and a richer, more composable filtering system will take over in the left sidebar. It will then be able to show all kinds and types freely, based on what's actually present in the catalog, instead of any hard coded lists.

Some references: #2791, #5549.

Thanks for the suggestion, but closing since it's being worked on!

**Comment by WillSewell** [comment]
That's exciting! Thanks for the context.
