### ISSUE TITLE
[Catalog] Customize EntityPageLayout Header

### ISSUE THREAD

**Issue by RiyaTyagi** [backstage/backstage#5658]
EntityPageLayout is one of the main components in the catalog plugin which allows interaction with an entity. To provide a good user experience we are looking to be able to customize the header for the entity page.

## Feature Suggestion
Custom Entity Labels on the header with or without entity reference links. 

<img width="1258" alt="Screenshot 2021-05-12 at 8 54 38 PM" src="https://user-images.githubusercontent.com/31857310/118006333-ccddf100-b368-11eb-8ca3-9884fee43fdf.png">

## Context
Currently, at Expedia, we do not have a model to attach group type entity to so we don’t want to show it as an entity link.

**Comment by freben** [comment]
Yes, sorry but these entity layouts are not broken apart into pieces in a composable way right now. So it's not easy to customize just parts of it, rather than replacing the whole shebang.

It's on our radar to some day look into the details of what the component-app interface surface looks like, such that the header is more owned by you than the plugin. But unfortunately not in the very short term.
