### ISSUE TITLE
Make use of versioning for introducing major updates  to Entity model.

### ISSUE THREAD

**Issue by GoWind** [backstage/backstage#5834]
PR https://github.com/backstage/backstage/pull/5787
introduced an addition to the Entity model namely the `status` field.

While this field might have  been a better fit as a value within `metadata` rather than as a top-level field,  my humble opinion is that updates to the core data model of Backstage/Catalog should be versioned. 

The data model , IMHO should be platform agnostic. While code writing using Backstage's plugins/packages will have no trouble adapting to the existence of the newer field, code written assuming Backstage's Entity model in mind in other platforms cannot understand the new field or know  of its existence.

Given that the Entity model already has a way to version the model namely `apiVersion`, any updates to the Entity model must be followed by a bumping up of the version used by the Entity. 

Currently the `status` field on an Entity is optional. While this is backward-compatible, this doesn't really provide any of the guarantees afforded by the type system, such as detecting the absence of a status entry in an Entity that is supposed to have this field.  

## Possible Implementation

Provide types of Entities with updated `apiVersion` when root level fields are added, removed or sub-fields narrowed/broadend. This will allow processors, clients and UIs to identify what fields/data can be expected in an Entity and flag or raise errors when the fields are missing or if values are not in the correct format or are invalid.

**Comment by freben** [comment]
Hi! I can definitely see the angle you're coming from. Let me offer a few counter points.

We're at a stage where we're effectively trying to settle what the `backstage.io/v1` version should be for all of the core kinds. In the pre-v1 stage we're a bit more liberal with changes; for example you'll see the pre-1 versioning of packages also using minor bumps for breaking changes that we're also being a bit more liberal with passing through. After reaching v1 (in either of those spheres), we're likely to be a lot more cautious.

The change was not breaking, as you note. Both on the producer side and on the consumer side, no change in behaviour was needed. We could bump the last digit of the version and add new Typescript types and validators etc for the new modification, but the value is limited since the reader must be defensive and feature detect anyway.

Which I think leads to a higher level point about reader behaviours. Certainly the reader would always have to abide by the type and schema contract offered to them, and use feature detection, in any case. Maintaining a list of versions and different behaviours (code) per unique version per unique kind is a daunting task at best, and one that will struggle in the longer term to stay up to date with the list of available versions as time goes on.

Which, in turn, I think opens the final question of how should we handle evolution of the core kinds longer term. And it is my gut feeling that as we settle on a model, we'll likely "never" - for some definition of never - be able to break that. Just like Kubernetes kinds, we'll probably reach a singular authoritative version and then essentially be stuck, not at all for technical reasons, but only for practical/human reasons. We can not rely on reader code _everywhere_ to stay up to date and bump their dependencies AND their behaviours in lockstep with model changes, because the world is a messy place governed by changing priorities, changing budgets, limited attention spans, highly asynchronous flows of events, and imperfect humans. We could try to make it so that there are server-side converters back and forth between all versions of all kinds, so the reader can say "give me specifically the 1.0.34 variant of this actually 2.4.0 ingested thing", and that's a whole other level of complexity that I don't see happening at least in the near term.

There will always be client code that looks exactly like this:

```ts
const entity: Entity = client.getEntityByName(...);
if (entity.kind === 'Component') {
  const component = entity as SomeComponentType;
  const value = component.fieldThatWeRelyOnExisting;
}
```

that also uses a certain snapshot view of what `SomeComponentType` means, and therefore makes assumptions about the world around it and the choices made in the org. And in that situation, we could not possibly safely remove fields without introducing null pointer exceptions everywhere. And now also consider that there are myriads of actual YAML files that are frozen in time, stored in version control, that back this data. We can't easily start changing the semantics of fields or rename or remove things without starting to consider the much larger task of fleet-wide YAML migrations.

In light of all of the above, I am not sure that there are practical benefits to a highly granular versioning scheme.

Even if we held on to our `v1` for a long time and then introduced a new, completely different `v2`, would consumers actually handle that gracefully? Consumers that maybe were written several years ago and chug along with mission critical software in a basement somewhere. Their code would likely look like above.

This may all sound pessimistic, and damning for the catalog, but I want to stress that it really isn't. My point is that the _core_ of the model should be small and well defined and will likely effectively stay put, for good, practical reasons. On top of that core, there is significant freedom to innovate and add labels, annotations, tags, statuses, additional metadata/spec fields etc - within the small scope of your org, likely using "forgiving" soft feature detection on the reader side. You could add a label saying what your "additions" model version is if you wanted to, but I suspect that it will be hurtful for you to maintain, and for consumers to be effective and productive to read, in the face of a tricky reality.

This vision guides how we look at the choices made for the model. It also is one reason that we move all relations out into the `relations` array and tell users to only ever use that one as an authoritative source for relations. We're even toying with the thought that possibly _all other_ fields also could be extracted into a reader specific form that's more annotations-like, which would mean that the input YAML would be detached from the consumer side, only used as a source format because it's easier and more convenient to write for humans than a flat namespaced versioned key-value thing that's more machine/code friendly.

This was a very long and very ranty comment. I sincerely hope that it doesn't come across as off-putting or negative. I think your idea absolutely has merit and the reason that this got so long and chatty, is that the subject is super interesting from a lot of angles, especially in a harsh unforgiving long timeframe. Let me know what you think!

**Comment by GoWind** [comment]
I understand your points very well @freben . 

**Top-level changes should be anchored to Entity versions, rather than as optional fields.** 

`Entity` is possibly the most core object of Backstage and I do not expect it to change a lot. Therefore, it makes a LOT of sense to type its versions and fields as much as possible using something like the following:


Example:
```
export type Entity = 
{ apiVersion: '1', spec: T, kind: string, metadata: JSONObject } | 
{ apiVersion: '2', spec: T, kind: string, metadata: JSONObject, status: StatusType}
```

### Why ?

1. The problem with adding `status` as an optional type is that missing `status` fields don't really tell if it is an optional field, a bug or is simply not supposed to exist. 

2. We are effectively leveraging the type system. 
2. UI Components, Readers etc that understand only `apiVersion`: `1` can treat status as an optional field.
3. UI Components, Readers etc that understand `apiVersion`: `2` will throw Exceptions when they see Entities with missing or invalid `status`es.



Sure, you can write unit tests on your processors and components that break if you make a bad change, but the context of features/things are obfuscated when you ensure guarantees about schema using unit tests.

This is the exact problem with dynamically-typed languages that was meant to be fixed by statically typed languages (and flexible languages like Typescript).

Using types to guarantee presence of data is a lot more clearer and simpler. 


## Regarding `status` and `metadata`:

The `metadata` is in our opinion, the right place to decorate an Entity with Backstage specific information. Our source of truth provides the `spec` of an Entity  and any information added in the context of backstage (when it was last processed etc) should be `metadata`.

To provide guarantees about any additional fields that we add, we extend the `EntityMeta` type to include the additional fields and works out well for us. 

This is the exact approach we are using (not deployed yet, however) at the moment within Zalando to provide us `meta` information about our Software Entities.

**Comment by GoWind** [comment]
I am not too worried about `status` added to the root of an `Entity`, but rather my concern is that the change was done without an `apiVersion` bump.  I believe my suggestion to bump versions for significant changes have a lot of merit, even if the no. of changes are small and distributed over time.
