### ISSUE TITLE
[RFC] Customizable user profiles and groups

### ISSUE THREAD

**Issue by heatheralee** [backstage/backstage#5930]
**Status:** Open for comments

## Need

We would like to be able to offer customizations to the user profile page so that users can author content about themselves. This is an RFC to address the issue I opened here: https://github.com/backstage/backstage/issues/5382

Here is an example of what this might look like:
<img width="1393" alt="Screen Shot 2021-06-04 at 2 48 04 PM" src="https://user-images.githubusercontent.com/73502014/120865958-e1667100-c543-11eb-8cf3-3f2114a9fe0d.png">

The fields that are shown here should be configurable per organization (I was thinking we could make this configured through `app-config.yaml` or some other `.yaml` config file). For instance, an organization may not find the README or Preferred Mode(s) of Communication helpful, and may prefer to add other fields here.

In terms of groups, we would like to be able to allow users to customize and create groups by decorating existing groups pulled from different locations.

Note: This proposal is written from the perspective where we have already implemented a POC for this functionality. We are open to taking in any suggestions to make this functionality even better and flexible to other orgs' use cases.

## Proposal

This proposal is broken down into two parts.

### 1️⃣ Proposed backend implementation:

![Backstage Org Service - Backend (1)](https://user-images.githubusercontent.com/73502014/120867872-abc38700-c547-11eb-86d7-240d979d707b.png)

**Org Service**
We have an external service that is a Node/Express server with a MongoDB database. I am open to converting this to postgres to maintain parity with Backstage, but did like MongoDB's flatter, flexible document structure to store user profile fields and would rather offload the handling of relationships between users and teams to Backstage's catalog processing phase.
This would be very similar to the Lighthouse Audit Service, where the Org Service would poll LDAP, Gitlab, and other sources directly and aggregate all this data so that it was available to Backstage through the Express API. This would add greater flexibility over what data we wanted to make available to Backstage.

The downside to our current implementation is that we are not able to leverage the existing LDAPOrgReaderProcessor. I ported this logic over to the Org Service. 

After parsing LDAP and other data sources through a cron job, we store this data in MongoDB so that it is available in API endpoints:
- `GET /v1/users`
- `GET /v1/groups`

We do not have any processors configured for users or groups on the Backstage side in app-config.yaml as the Org Service acts as the sole source of truth for users and groups.
Users should be able to pull the external org service code (hosted in a separate repository similar to [lighthouse-audit-service](https://github.com/spotify/lighthouse-audit-service/tree/master/src)) and add new logic to process new data sources.

**Backstage and the org service**
Backstage then ingests the data from the Org Service in its existing processing loop in `HigherOrderOperations` in `catalog-backend`.

### 2️⃣ Proposed frontend implementation:
![Backstage Org Service - Frontend](https://user-images.githubusercontent.com/73502014/120868968-21305700-c54a-11eb-983c-039c6d86d61b.png)

Currently, we allow users to author their user profiles in the Settings page. I added a patch to the org plugin make this possible. Here is what this currently looks like on the frontend:

<img width="584" alt="Screen Shot 2021-06-04 at 2 53 35 PM" src="https://user-images.githubusercontent.com/73502014/120866369-a44eae80-c544-11eb-830d-11228bf4db97.png">

I'd like to make this more scalable and think this can be achieved by a front end, service backed plugin which provides an editing interface so that users can update their user profiles and create/edit groups that were ingested from the Org Service. This is in line with Tim's suggestion on how they do this at Spotify (thanks @timbonicus!). 

We do not support creating new users and only would plan to support creation of teams for this iteration. For us, it would be helpful if we could populate team membership from groups pulled from existing sources (in our case Gitlab). 

Users would go to the front end plugin and update their own respective user profiles and also have the ability to edit existing groups or create new ones.

We'll also need to make some updates to `@backstage/plugin-org` in order to render the new user profile data.

## Alternatives

For the front end, one possible alternative solution would be to integrate this functionality with the existing org plugin. After a bit of consideration, I think it's better to dedicate a brand new plugin for the authoring of enhancements to user profiles and groups and leave plugins/org to handle the rendering of any profile data. This is so that the org plugin isn't so closely tied to the concept of allowing users and groups to be customizable if the user doesn't need that, and makes this feature feel easier to turn on/off.

For the backend, we could have potentially left the responsibility of pulling data from LDAP and other locations to Backstage. One option would be to still use the existing data processors in Backstage and enhance profile/group data by using `postProcessEntity` and in `postProcessEntity` we could make requests to Org Service.

We ended up just choosing to push all the responsibility of data processing to Org Service for several reasons:
1. We're more easily able to pick and choose what data we want and from where. For example, we don't really care to use any of the groups we get from LDAP, and instead would prefer a hybrid of LDAP users and Gitlab groups, which currently does not appear to be supported by Backstage.
2. This one is less important because the catalog processing loop is being worked on, but we are unable to query our LDAP every 100s as this would get us in trouble with IT :-). This option allows us to treat Org Service as a proxy and have Org Service only poll LDAP on our preferred cadence, then just have the Org Service be hit every 100s instead.

All this, however, does come with the tradeoff that if someone does have this Org Service plugin configured, they would not be able to leverage existing and new data processors created for Backstage (but does mean people can contribute to Org Service and add new processors).

## Risks

I really want this to be as least risky as possible, and Backstage should handle user profiles exactly the same if the user has not installed the plugin. 

To mitigate any risky behavior we could key off of the `app-config.yaml` file:
- For the user profile, we can check through `app-config.yaml` if the user has the org service plugin configured. If not, just don't render any user profile card and render the default user profile.
- Users would still be able to configure processors directly in Backstage if they wanted to. The org service processor would just be an additional processor also emitting user and group entities.

**Comment by freben** [comment]
Hey!

First of all, double checking - you intend to use this architecture internally at your company, rather than make an open source thing for general use, right? So this is mostly about fielding for feedback on that. Because that affects the response a whole lot. :)

We actually also have a similar structure, but perhaps for different reasons than you. We could read off of LDAP directly as well (there are fast read slaves etc), but the internally preferred authoritative source is a service that acts as a hub between all different aspects of user and group management in different "worlds" that we touch upon. So it existed even before Backstage, and is completely independent; everybody else uses it as their source as well.

But - we would absolutely not want to build the open source Backstage in such a way that others have to mimic that behaviour or structure. We should instead focus on making it easy to build custom adapters, as we had to do ourselves.

Anyway.

One thing that comes to mind is storage. We tend to tell people to try to store their data as close to the authority as possible, preferably inside it. For example, if this extra data was stored as custom attributes all the way out in LDAP, you would see some gains in terms of consistency and possibility of getting value out of that data in the rest of the org - without tying the rest of the org to your new service. The latter would increase the scope, constraints and risk put upon you, compared to if the service was just treated as a Backstage-only "view service". If you make a local storage in mongodb as proposed, you can perhaps move faster and iterate easier.

So OK, let's assume that you build that service. Then I think the entity format comes into play. If I read things correctly, you'll essentially return a list of User entities on the `users` endpoint. This extra data, such as timezone and location, where is it placed in the entity data? Is it all extra fields in `spec.profile`?

On the point of request rates: the next gen catalog can actually have the update cadence controlled by you, on a per-source basis. But I still think that what you propose sounds potentially better under those circumstances - IF you feel that you can muster the extra complexity that it entails.

OK that's just some mixed thinking out loud, maybe it helps a bit :)

**Comment by freben** [comment]
Oh one more thing. About the frontend parts of this. I do not think that your proposal would be added wholesale in the org plugin as such. What we should do as maintainers, is to make it easy for everybody to compose their own pages as lego pieces, inside their private app, out of building blocks that the org plugin or the core components expose, possibly together with things that they custom-build and keep closed source if those pieces aren't particularly general.

Now IF you propose additions to the _actual public open source core model_ of users and group entities - for example, extending the `profile` section - then that's an entire large discussion unto itself and we'll have to look at those proposals one by one separately. If such an addition gets made (there's a bit of a bar to pass there), then the actual core offering of the org plugin's default looks may also change as a side effect, since it will affect everybody.

If not, it can still sometimes make sense to add individual "lego pieces" of particular public interest to the core packages, of course.

Does that set the stage somewhat? :) It can be a bit confusing.

**Comment by morganmspencer** [comment]
Has there been any movement or updates on this? I think it would be a great feature to have!
