### ISSUE TITLE
[RFC] Bravos for users

### ISSUE THREAD

**Issue by heatheralee** [backstage/backstage#5931]
**Status:** Open for comments

## Need

**Note**: This ties very closely to an existing RFC: https://github.com/backstage/backstage/issues/5930 for user profiles. 

We would like to be able to create a plugin that allows users to give each other a "Bravo." A "Bravo" is essentially a way for employees within an organization to publicly give each other compliments. We would like for this to reside within Backstage as we feel this ties in very closely with the customizable user profile functionality and also enhances Backstage. Imagine the flow: 1. Employee looks at service they have never seen before. 2. They find the owner of the service through Backstage and looks at the user profile of the owner. 3. The owner helps them out with this new service (the employee has successfully found and contacted the user through the preferred modes of communication the owner listed on their user profile) 4. The employee thanks the owner of the service by giving a "Bravo."

## Proposal

User A wants to give User B a "Bravo." User A would go on User B's profile and choose from a pre-selected group of "Bravos" to give out (the maintainer of the Backstage instance could configure this pre-selected group). Once filling out a form to give the Bravo, this would send off a POST request to an external service (I was thinking it could tag along on the Org Service plugin, see this RFC for more details: https://github.com/backstage/backstage/issues/5930) to store this bravo.

When visiting User B's profile, everyone would be able to see User B received this Bravo. The Bravo would contain the type of Bravo (from the pre-selected list), the date given, who gave the bravo, and why.

All of the front end interactions would be supported by a service backed plugin in Backstage. The external service could either be a new service, or we could piggy back off of the Org Service as proposed in #5930.

## Alternatives

We could either piggy back off of the Org Service as proposed in #5930 or create a brand new service. The downside of integrating directly into the existing Org Service is that it would be difficult to split up the two functionalities (what if someone implementing Backstage doesn't want the user profile customizations, but still want the capabilities of giving/receiving bravos?). We could address this concern with a configuration file in Org Service, but am open to hearing everyone's thoughts on this. The upside of piggy backing off of Org Service is more an infrastructure one -- for orgs like Splunk that are implementing both User Profile customizations and Bravos, having one separate Org Service that centralizes all this functionality makes our infrastructure a bit simpler and we don't need to configure a separate instance with separate CI/CD and deployments for both functionalities.

## Risks

Similar to user profiles, we'd like to let users opt out of having Bravos available and this should be configured through `app-config.yaml`.

**Comment by andrewthauer** [comment]
Something like this seems like it could benefit from integration with a 3rd party employee recognition service/software that an organization might be using for bravos, kudus etc. There could be a custom backend for those that don't have a system, but would be nice if the backend could be customized to integrate with something pre-existing within an org.

**Comment by freben** [comment]
Adding on to what @andrewthauer said, this sounds like an absolutely wonderful feature to run on a Backstage instance, but the question is whether it should be "in" the core as such.

So what I mean with that is, if there is a good system in place where recognition is already recorded - as in, what your score is on an internal stack overflow, what your number of followers is on GitHub Enterprise or so - then those are good things to make plugins for or have added to the respective plugins.

But putting into place into the core, a general overarching supports-all-kinds-of-kudos-systems concept / api / etc, may perhaps be a tougher proposition. Sometimes it's a good thing to make these common APIs on top of concepts, but it must be used judiciously because they always run the risk of becoming lowest-common-denominator systems that aren't a great fit for any of the things it hides, and are harder to evolve :)

This all sounds a bit negative, sorry if if comes off that way. I still think it's a great feature, but perhaps it should be geared towards packaging on the provider level.

And all of that being said - building a _custom_ kudos system as a frontend+backend plugin that is backed by the central database, isn't actually all that hard at all with the platform that we have. Maybe that could actually be something you might consider.
