### ISSUE TITLE
Search: `DefaultCatalogCollator` should index `spec.profile` section in group and user entities

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#5943]
## Feature Suggestion

`DefaultCatalogCollator` is only designed for entities of kind Component. It would be neat to support other build in entity kinds too.

Users and groups have a `displayName` field in `spec.profile`. It is important to index this field too, otherwise it's hard to search for users by their name. For example, Backstage comes with the test user `Calum Leavy`, which you can't find by searching for `calum` right now. You can neither find him by full name with a space in between: `Calum Leavy`. You have to explicitly enter the entity name `Calum.Leavy` to find him (with a dot).

## Possible Implementation

Extend `DefaultCatalogCollator.execute()` with different logic for each build in kind.

**Comment by freben** [comment]
@backstage/techdocs-core

**Comment by emmaindal** [comment]
Thank you for opening this issue @Fox32!

**Comment by Fox32** [comment]
I wonder what your thoughts on this is. Is this special, or something we should support out of the box? Is it a separate collator with a separate document type, and a custom `<CatalogResultListItem>`? I could imaging that the `<CatalogResultListItem>` of a user contains an avatar.

What is the general suggestion on this. If I want to index additional fields in my entity, should I replace the `DefaultCatalogCollator`, or create an additional collator that just index my custom field?

**Comment by iamEAP** [comment]
Maybe the guiding light on "what goes in `DefaultCatalogCollator` vs. what should be left to app integrators" is what's required (or even optional) in the [Well-Known Kinds](https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component) documentation?

Although I guess for your `User` example, that doesn't help much, since the `spec.profile` field is quite open-ended.

I think there's still lots of room to flesh out the `DefaultCatalogCollator` to cover the 80% use-case though, so anything that maps to making the experience make sense for the well-known types are definitely welcome.

For anything that seems like an obvious thing to include, but doesn't currently map to the well-known kinds documentation (e.g. your `avatar` suggestion for `User`), I almost feel like it should put weight toward making it a more standard/recommended part of the kind's schema?

I dunno.  What do you think, @Fox32 @emmaindal @freben?

**Comment by emmaindal** [comment]
Our discussion when developing the `DefaultCatalogCollator` was to look into the required fields of all different Kinds and focusing on supporting those in the DefaultCatalogCollator. Looking at those again, it seems like we are missing a few required ones. Here is a collection of all required ones for all kinds:

- [x] kind [required] (All)
- [x] spec.type [required] (Component, API, Group, Resource)
- [x] spec.lifecycle [required] (Component, API)
- [x] spec.owner [required] (Component, API, Resource, System, Domain)
- [ ] metadata.title [required] (Template, API)
- [ ] spec.parameters [required] (Template)
- [ ] spec.children [required] (Group)
- [ ] spec.memberOf [required] (User)

With that said and with a little bit more thinking around this I would say - the DefaultCatalogCollator should support the required fields, if we want to extend a Collator beyond that, it should be created as its own. Could still be contributed, so that others can use it of course. And I'm not saying its the right thing to do!

**Comment by freben** [comment]
I don't worry too much about open endedness I think; let's not support any random unknown extension field from the start, sure. So the candidates can be the fields that are in the core catalog-model.

But optionality is probably not tied to the suitability as a search parameter. Optionality is more about whether we want every single org everywhere to be forced to supply a field whether they want to or not. Those that do, probably care about them.

Just from an end user POV, it's probably fairly reasonable to want to be able to search by full name and email. Or turned the other way around, one might be frustrated or surprised if unable to search by exact email or name match, if you can clearly see it front and center on the user page. I also believe it's not too crazy to have `metadata.name` that's fairly useless or opaque (perhaps machine generated), while the full name and email are fine from the source.

**Comment by freben** [comment]
To clarify the last part, I've seen sentiments similar to "Why can't we have @-signs in the name, we don't have user IDs in our HR system. We key off of full emails where the name part can have collisions across domains. Ok we'll just put the UUID in the name for now or generate something by kebab-case-converting the sanitized email" :) Or so.

**Comment by Fox32** [comment]
Hmm, playing around with it a bit more, im not sure if the decision to only include required fields is a good idea. And it's also not followed properly 😅 For example, `description` is indexed, even though it's optional and I think it's a very valuable field 😉 Also run into `tags` not being indexed, but that would be quite useful too. Like searching for all `tags:go` services that are related to `payments`.

In my option I would expect that the `DefaultCatalogCollator` supports every reasonable field that is part of the [core data model](https://backstage.io/docs/features/software-catalog/descriptor-format). Reasonable excludes for me stuff like `annotations` and `labels` that have a technical background. I wrote my own `DocumentDecorator` to extend the index a bit and it seems to work quite well, but I actually think it should work out of the box.

Another thing I noticed: the `DefaultCatalogCollator` indexes the owner field, but we might also want to take the relations into account - not sure though.

**Comment by freben** [comment]
The drawback with `description` is also that it risks increasing the signal to noise ratio a whole lot, while, in my humble opinion, very very rarely providing intent-matching useful hits :)

But I know that I'm a very opinionated, niche, technical user who almost without exception is interested solely in searching among IDs and sometimes MAYBE some id-like or enum-shaped things. But even then only as an opt-in. The rest just confuses my result set :)

**Comment by Fox32** [comment]
I think that case is already supported quite well. If you know what you are looking for, you can search inside a specific field, like `title:playlist`, ignoring all other fields.

**Comment by camilaibs** [comment]
Hi 👋🏻, just sharing a thought:
For this specific case, my first thought was: when using the Elastic Search engine, could the problem be solved with a custom analyser that disregards the "dot" in the field when searching? But then another question arose, is this something supported by other engines as well? So this seems to be a workaround, not the solution...
Is there any reason the DefaultCatalogCallator doesn't accept which fields to index as an optional setting? Required fields can be the standard fields, but optionally add others?
Sorry if this question has already been answered, I may have missed it in the previous comments.

**Comment by garyniemen** [comment]
@Fox32 where do you see this issue now after all the comments?

**Comment by camilaibs** [comment]
Hi, @Rugvip do you have any additional suggestions for this case?

**Comment by camilaibs** [comment]
Related: https://github.com/backstage/backstage/issues/11407

**Comment by camilaibs** [comment]
Related: https://github.com/backstage/backstage/issues/14530

**Comment by iamEAP** [comment]
Hey everyone following along on this issue!  I'm consolidating this feature idea (as well as others) into a single issue.

I encourage you to continue the discussion (and perhaps, implementation? 😉) here: https://github.com/backstage/backstage/issues/14961
