### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#6003]
Hi, I am wondering if there is any way for signin using LDAP provider?  If have, how could we do?

**Comment by Rugvip** [comment]
There isn't an LDAP provider right now. It's a bit sub-optimal because of the password handling, but it should be possible to implement a provider using for example [passport-ldapauth](http://www.passportjs.org/packages/passport-ldapauth/), with some more information on that in [our docs](https://backstage.io/docs/auth/add-auth-provider). It would probably be best to take inspiration from the existing SAML provider.
