### ISSUE TITLE
[Plugin] Apple Developer Portal

### ISSUE THREAD

**Issue by BalestraPatrick** [backstage/backstage#603]
## Summary

This is a proposal for a new plugin that we would like to open-source called "apple-dev-portal". The goal of this plugin is to make it easier to onboard new iOS engineers in a team and manage common operations that they have to do.

## Project website (if applicable)

Apple Developer Portal: http://developer.apple.com
App Store Connect API: https://developer.apple.com/app-store-connect/api/

## Context

Apple already has a [developer portal](http://developer.apple.com) that can be used to do many different things (create apps, manage code signing assets, invite new members, publish apps, etc.), but we would ideally like to automate most of the manual work to make all these tasks less error-prone. By doing so, we don't need to give write access to all iOS engineers in the company since Backstage is the entity they'll use to perform their tasks. 

So far, we used to invite new joiners manually to our Apple Developer Program in order to give them access to our resources and code signing assets. We automated this task by letting new joiners invite themselves through Backstage as it can be seen in the following screenshot.
<img width="1407" alt="Screen Shot 2020-04-20 at 12 40 19 PM" src="https://user-images.githubusercontent.com/3658887/79743838-98cf0280-8305-11ea-817a-e05979bfe4dc.png">
We have a small Python backend service that uses the official [App Store Connect API](https://developer.apple.com/app-store-connect/api/) to automate the operations and communicate with Apple's servers.

Similarly, we have automated adding devices to the developer portal which is required when developers want to test their changes on a physical iOS device. The developer portal is quite a tricky and dangerous place to make changes, so by making sure that only Backstage can make the right requests, we remove friction from our developer experience. 

<img width="1407" alt="Screen Shot 2020-04-20 at 12 40 26 PM" src="https://user-images.githubusercontent.com/3658887/79744590-e730d100-8306-11ea-8cf8-5ba7b62127b7.png">

I have a few questions on how to proceed if you think it makes sense to include this plugin:
- The current version of the plugin is written in plain JavaScript, do we have to write it in TypeScript to fit into BOSS?
- Is there a strategy on how we open-source backend components that plugins consume? Each company using this plugin would need to add their own API key to communicate with the App Store Connect APIs, so we need some kind of configuration too.

Feedback welcome, happy to hear what you think! 💯

**Comment by freben** [comment]
Cool, happy to see this!

Plugins may be written in either TS or JS; we support both, although we prefer TS. It is usually fairly easy to adopt TS gradually, and it offers long term benefits. If you like, we can offer some assistance to that end, otherwise, don't let it block you from open sourcing the plugin.

We are settling the backend strategy as we speak, so it should be clear (and documented) soon. We recognise that there is demand for plugin backend parts that handle secrets and similar concerns.

**Comment by freben** [comment]
Feedback on the plugin structure:

Would it make sense to have the landing page of the plugin be an "Overview" style page like other plugin roots usually are? For example, could it show your membership status if known, along with a button "Apply" that takes you to an application flow? And could it show the list of known devices, and a button "Register Device" that takes you to the flow for that? This is more in line with how we commonly structure views. Tabs usually aren't action forms themselves.

**Comment by freben** [comment]
@BalestraPatrick Am I right in understanding that you intend to open source that python backend along with some frontend parts?

For backends that are standalone, your strategy regarding secrets and deployment etc will not depend on Backstage as such. You would open source the backend as one repo, and the frontend plugin as one repo. From the integrating company's point of view, they would have to deploy your service somehow and feed it the secrets it needs.

The frontend plugin would be packaged like other plugins in the form of an NPM package, and the integrator would configure the plugin with the URL to the backend. Which possibly could be via the Backstage proxy.

The strategy for configuring plugins in an app is still being settled (see #278). The strategy for how the proxy is deployed and configured is still being settled, but that should not necessarily affect your release schedule.

**Comment by stefanalund** [comment]
@freben if the backend is only intended to be used for the Backstage plugin, why couldn't it also be included together with the plugin frontend code? One convention could be to have a `plugins/my-plugin/backend` folder with a corresponding `README` that outlines how to configure and deploy the service?

**Comment by BalestraPatrick** [comment]
@freben Yes, the plugin is pretty small so porting it to TypeScript shouldn't take too long. Your suggestion on the plugin structure totally make sense, I've tried to keep the plugin features rather small and separate for this initial version (it was literally released internally last week).
In the future, we may add more and more actions, so having a single "Overview" tab with everything in it seemed like a bad idea and not very easily linkable (right now we can easily and directly point developers to the register device page if we know that's what they're looking to do).

Yes, the backend is a flask/helios Python backend that relies on our internal stuff to fetch secrets. We would need a solution for this in BOSS too.

So as far as I understood, we would create a separate repo that contains the frontend and backend code, which would then be pulled in from consumers in their own backstage installation. I initially thought the plugin would live in this repo, but I guess that makes sense now. I was following [this guide](https://github.com/spotify/backstage/blob/master/docs/getting-started/create-a-plugin.md) and it creates a plugin in this repo, so is the idea that we just take the template and push it to a separate repo?

**Comment by mbruggmann** [comment]
Wouldn't it be nice if we could define and run both the frontend and the backend directly from this repo, eg by defining the endpoints in `plugins/apple-dev-portal/backend` as @stefanalund suggested and running that inline in the proxy/backend? The API could be something like the [Zeit Now](https://zeit.co/docs/v2/serverless-functions/introduction) serverless functions?

Looking at the internal implementation, it doesn't do much more than defining a few endpoints, attaching an API key, and forwarding calls to Apple. Should be possible to port it to TypeScript. The advantage would be that you don't need to run a separate service to get this supported in Backstage.

**Comment by freben** [comment]
Agreed, if it's viable to port it to TS, then by all means I think that that would make it easier to adopt, since it aligns with our backend plans.

@BalestraPatrick do develop (at _least_ the frontend part of, or both if ported to TS) the plugin in the open, as `packages/plugin-apple-dev` or so. We try to encourage keeping as much as possible inside this repo for now.

When it comes to having the code for backends and frontends in the same monorepo, I think I will have to invoke @Rugvip. We discussed it briefly before, and I believe that one possible concern is what will happen with dependencies. Specifically the mixing of backend (node specific) and frontend dependencies, and whether the node deps somehow affect the built app package. Just double checking, not sure if it's a problem in reality.

My original plan was `packages/plugin-apple-dev` and `packages/plugin-apple-dev-backend`. Having them inside the exact same npm package, is that even a thing?

**Comment by freben** [comment]
> In the future, we may add more and more actions, so having a single "Overview" tab with everything in it seemed like a bad idea and not very easily linkable (right now we can easily and directly point developers to the register device page if we know that's what they're looking to do).

Right, but even if there is still not a very clear Overview page structure to be had (maybe not enough data yet etc), I still want to say that I want to avoid "Tab == action". A tab should be a view with information, possibly with an Add button for example, _not_ a form.

So you could have the route `apple-dev/devices/list` that lists devices, and that's what the tab takes you to.  If you click a device you get to its info page `apple-dev/devices/item/3476287648`. The Add button on the list page takes you to `apple-dev/devices/add`, which may or may not even show the sidebar at all; it's just the step by step path to adding a device. When you are finished creating the device you are redirected either back to the list or to the info page of the newly added device.

If you prefer, the add wizard could also be a dialog on top of the list. But if you make it a route, you can still link people directly to the Add page.

**Comment by stefanalund** [comment]
Let's say that this wasn't a simple service, would we still recommend it to be ported to Node.js (or whatever becomes the recommended language for our backend)? I don't think that is a viable strategy.

**Comment by freben** [comment]
No, absolutely not. My suggestion was just based on the fact that it matches what we have in our RFC: a small bridge service that basically only adds secret handling. When you are in that situation, if the plugin maker wants to make it easy for integrators to pick up their thing, then they may opt to make it easily integratable into the Backstage backend, but it's still optional.

Making standalone services comes with a cost for the integrating party, and they may choose to turn down the opportunity because it becomes too burdensome to get the thing going. That's still a perfectly valid choice though, and sometimes it even is the only sensible thing to do (large services, services that are consumed as standalone entities by others, services that want to be written in lower level languages, services that have particular deployment/scaling needs, etc etc etc)

**Comment by Adamseyer** [comment]
Is there any recent activity on this?

**Comment by BalestraPatrick** [comment]
@Adamseyer We're still working on this, hopefully we'll have something to share soon.

**Comment by marcuseide** [comment]
@BalestraPatrick Hey, checking in here and wondering if this is something you are planning on picking up and if you have any questions around it?

**Comment by OrkoHunter** [comment]
Re-opening since plugin suggestion issues are now exempt from [stalebot](https://github.com/backstage/backstage/blob/18f7345a6c29dcfccef7df081b1708f2bf8f62ff/.github/stale.yml#L9).

**Comment by tudi2d** [comment]
talked to @BalestraPatrick - closing it for now.
