### ISSUE TITLE
CatalogApi: update entity functionality

### ISSUE THREAD

**Issue by falconbin** [backstage/backstage#6050]
an api that could update entity

## Feature Suggestion
update catalog entity over CatalogApi, current interface doesn't support this, refer to CatalogApi definition:
![image](https://user-images.githubusercontent.com/20329141/122140399-bf42ec00-ce7d-11eb-8409-e2d89805a557.png)
I am not sure if we could update catalog entity over api call(remove and add a new one again ?), maybe I lost something. But from CatalogApi interface, it only supports get, add, delete without update. Are there any special reasons that we don't supply update?

**Comment by benjdlambert** [comment]
So the catalog is built in a way that you only really register `Locations`, and these `Entities` are produced by the `Locations`.  If we were to add the ability to be able to mutate these `Entities` in an API, I think it's get really complex, because then you have the source of truth (these yaml files), and then some state that you've set in the API and merging that state can become really tricky.

We really just recommend updating the source of truth files to reflect what you want in the `CatalogApi`. Is there some particular use case that this doesn't work for you?

**Comment by falconbin** [comment]
> So the catalog is built in a way that you only really register `Locations`, and these `Entities` are produced by the `Locations`. If we were to add the ability to be able to mutate these `Entities` in an API, I think it's get really complex, because then you have the source of truth (these yaml files), and then some state that you've set in the API and merging that state can become really tricky.
> 
> We really just recommend updating the source of truth files to reflect what you want in the `CatalogApi`. Is there some particular use case that this doesn't work for you?

Now no, thank you for your explanation. My initial thought conflict with the design. This issue could be closed.
