### ISSUE TITLE
Support paginating search results

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#6062]
## Feature Suggestion

Support builtin pagination in the new search page which paginates number of results shown and results coming from the backend.

## Possible Implementation

There seems to already be some plumbing already implemented to support pagination like references to a `pageCursor`:
https://github.com/backstage/backstage/blob/9bca8225f06e5855fb90dce83e7d17f5e334bf18/plugins/search/src/components/SearchContext/SearchContext.tsx#L60

It looks like we need to enhance the `SearchResult` component to utilize this? 
## Context

In the new search page setup, all results are returned to the frontend which can cause the browser to hang attempting to render when there is a large amount of results.

**Comment by kuangp** [comment]
FYI, this is how we're currently handling pagination on the frontend side of our search page:
```react.js
<SearchResult>
  {({ results }) => {
    useEffect(() => setPage(1), [results]);

    if (!results.length) {
      return (<EmptyState missing="data" title="Sorry, no results were found" />);
    }

    return (
      <>
        <List>
          {results.slice(20 * (page - 1), 20 * page).map(({ type, document }) => {
            switch (type) {
              case 'software-catalog':
                return (
                  <CatalogResultListItem
                    key={document.location}
                    result={document}
                  />
                );
              default:
                return (
                  <DefaultResultListItem
                    key={document.location}
                    result={document}
                  />
                );
            }
          })}
        </List>
        <Pagination count={Math.ceil(results.length / 20)} page={page} onChange={handlePageChange} />
      </>
    );
  }}
</SearchResult>
```

**Comment by iamEAP** [comment]
Adding a link to a recent conversation in discord: https://discord.com/channels/687207715902193673/770283289327566848/864149979047657472

The conclusion of which, I think, was that perhaps we background the pageCursor support in the `SearchQuery` interface (let it be, make it optional, and then `SearchEngine` implementations can optionally support it at an API level), and instead add a `limit` / `offset` pair to the interface, which we can control in the frontend.

**Comment by Fox32** [comment]
To make paging work properly we should also return the total count of search results in `SearchResultSet`. Otherwise one couldn't use a pager that  shows the available pages. However, I'm not sure if the total count of search results can easily be determined. So it's easy for lunr, a bit more complicated for Postgres (you need a separate query that does no ranking, otherwise the operation is very expensive), but not sure about ElasticSearch (seems to be easy https://stackoverflow.com/a/53909517/218902).

But does it really make sense to keep `pageCursor`? If the UI doesn't support it, it won't be useful. I would suggest to go with one approach. In the best case even one approach for all Backstage APIs, it's not so nice if different Backstage APIs use different patterns.

**Comment by Fox32** [comment]
Btw, just a small thing I noticed some days ago that we could probably change when introducing paging:

```typescript
                  <CatalogResultListItem
                    key={document.location}
                    result={document}
                  />
```

Using `location` as a `key` is not a good idea as it wouldn't be unique if different result entries point to the same URL. We have that issue on our side an are just using the array index as a key.

**Comment by freben** [comment]
I've been wondering, is it enough of a user interface to just have a "next" button? :) Is it really a common use case to want to know the number of pages, or to click on a page far ahead?

Maybe it's kind of a mental expectation rather than an actual use case. I guess sometimes one can get into a search mode with the intent of asking "how many of this thing are there in total", but I kind of expect that to be rare. The usual intent is probably "i'll enter some text and hope that what i want is in the first page, otherwise i'll give up" :D Haha.

**Comment by freben** [comment]
(Let me clarify that this is just me making conversation; not an actual UX design direction or strongly held opinion)

**Comment by Fox32** [comment]
I started some work here: #6815
