### ISSUE TITLE
Initially logging in through Okta with a user that does not have permission to Backstage blocks subsequent attempts to log in with the same auth provider as the initial user is stored in cookies

### ISSUE THREAD

**Issue by jeannieism** [backstage/backstage#6205]
Currently, I have two Okta user accounts. Account1 does not have permission to access Backstage, Account2 has permission. When I log in with Account1 first, I am unable to enter Backstage because permission has not been granted from an Okta admin. This is expected. However, once I attempt to log in with the correct Okta user (Account2), Account1 is stored in cookies so I am no longer given the chance to enter the correct account credentials in the Okta sign-in popup, until I clear my cookies. When I clear cookies, I am then able to see the Okta sign-in widget popup.

## Expected Behaviour

If a user attempts to log in and is denied by the auth provider, they should be able to attempt again without having to clear cookies.

## Current Behaviour

When I log in the second time (after a failed auth on the first account [Note: auth failure not due to incorrect credentials, but failure due to auth provider setting]), I am no longer able to see a popup because Backstage assumes I am the failed auth user.

## Steps to Reproduce

1. Auth through Okta by clicking "Sign in" on the Okta card
2. Enter Okta credential that does not have access to Backstage, hit enter/submit
3. Authentication fails and popup closes, an error message appears
4. Try Step 1 again
5. Step 3 occurs

## Context

Use case 1: Users in our org who have Okta credentials, but do not have permission to access Backstage may attempt to log in without realizing they need permission granted from an Okta admin first. Once an Okta admin grants them access to the Backstage app and they attempt to log in once more, my guess is that they will still encounter the issue described in Step 3 due to the fact that the cookie has already been stored and will not update until a successful log in has occurred.

Use case 2: Users who have more than 1 set of Okta credentials.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Catalina, 10.15.7
- Browser Information: Chrome

**Comment by freben** [comment]
Hi!

Hm, ok. So, not entirely sure while observing this at a distance, but it seems that there may be two things of note going on here.

- The multi-provider sign-in page is used, which has a behaviour of remembering what the last picked provider was (in the browser's local storage). So the second time around, the user seems to get fast-tracked onto the okta flow.
- Okta itself, when challenged for a sign-in, seems to fast-track the user as well if they had signed in before?

Honestly I'm not 100% sure what's the worse culprit here. I'll have to dig a bit. At the very least, it feels unexpected that the chosen sign-in method should be remembered, if the sign-in attempt apparently failed. So that might be a fix to make in the sign-in page.

I just want to add one thing. The multi-provider sign-in page is kind of an example - in any case, it's expected to not be very common that an org would want to ever have more than one sign-in method of choice. They would probably pick one which matches what all of their other internal systems use. There MAY be an argument for getting rid of the `MultiSignInPage` and switch over to the `SingleSignInPage` and see if things work better. If you use the general export [`SignInPage`](https://github.com/backstage/backstage/blob/d9e0f28531c656abade30391a8691a3990e1484b/packages/core-components/src/layout/SignInPage/SignInPage.tsx#L193), you can do so by giving a single `provider` prop to it.

**Comment by jeannieism** [comment]
The multi-provider sign-in page seems to remember the last successfully logged in user for each provider. So if I'm logged out, but have previously successfully logged through Provider1 and Provider2, upon the login page, selecting either Provider1 or Provider2 will automatically log me in—giving me no choice in selecting a different account for Provider1 or Provider2 if desired.

This issue may be specific to Okta as Okta itself requires that we have to manually give access to Backstage to a user..like there's a double layer of authentication. Whereas a provider like Github is simply 'as long as you have a github account, you have access to backstage'.

I should note that _both_ Okta users in the steps to reproduce _have_ valid Okta credentials. The key difference is that one is configured to have access to Backstage, and the other one is not. So logging in first with the one that does not have access to Backstage...we are actually _successful_ in logging in, BUT the check for 'if user has access to backstage' fails. I'm not sure if that is clearer or muddies up the issue!

**Comment by freben** [comment]
Yep got it! But, I think there are two layers to the okta rejection. One is that you provide valid credentials (or get fast-tracked somehow), which actually we never will see. Then, and again I can't know entirely for sure, it seems to me that it actually rejects access in such a way that WE see a rejection after all, even though the credentials were right.

Let me back up a bit and turn this problem around.

The "golden path" of deploying Backstage, is to have it behind an authenticating reverse proxy. This is how we do it at Spotify for example. We use the power of Google's global load balancers and identity-aware proxy features, to make sure that the first network packet Backstage ever sees, is from an already completely authenticated, trusted user. We then have a custom sign-in page that does absolutely nothing except to make a little fetch request to a custom auth endpoint on the backend. This happens through the identity-aware proxy as well, and it will decorate that request with a special header with user info in a JWT. The backend unpacks that JWT, validates it, fetches some more auxiliary info from our backends, and returns that to the frontend sign-in page - which just immediately completes the sign-in process.

So from an end user POV, they never even saw a Backstage specific login. They just used the well established Google sign-in that they already used for a lot of other products, so maybe there was nothing to type in at all because there was already a session. It's super fast, hassle free and the sign-in bounce I described above takes a handful of milliseconds.

So to make a long story short - it may be, that you want to use okta in the reverse proxy mode instead, and use its header decoration feature to do something similar to what we do. Replacing the SignInPage with a very small thing that just bounces via the backend to check the headers and return the necessary auth info to resolve the sign-in process. I am not sure if we have complete guides to how to best do this, and I have to leave for the day. But maybe I can dig up some info and inspiration tomorrow.

**Comment by jeannieism** [comment]
This is all great information for us to have in our back pockets—thank you! I'm sure we'll figure it out if/when we want to improve the login experience on our end.

Enjoy your day off!
