### ISSUE TITLE
Allow to change the commit's name and email of scaffolder-backend commit function

### ISSUE THREAD

**Issue by biki0109** [backstage/backstage#6217]
Hi, as the title has stated, I would like to have a new feature that allow the user to pass in the commit function new username and email, or use something like the user's login email anything apart from the scaffolder default value when creating a new component.
## Feature Suggestion
![image](https://user-images.githubusercontent.com/48164880/123394157-0725e980-d5c9-11eb-83ac-75f2e98fbd3d.png)

The above function is hardcoded with Scaffolder default value, this could become an issue when using scaffolder backend with Github / Gitlab (I'm not sure about Bitbucket or Azure) Enterprise as the Organization wouldn't be able to recognize this as a member, hence not allowed to push to the repo. In the end result in a creation of an empty repo.

**Comment by benjdlambert** [comment]
So as mentioned in the other duplicated tickets, I think theres probably step one which we can do pretty simply by supplying config in the `app-config.yaml` as overrides. 

But there's also the option to consider later down the line where we could take the email and name from the `IdentityApi` and use those details. This hasn't really made any progress yet, but it's something that we've spoken about internally and are looking at implementing maybe later this year. We need to know who the user is to use their `Identity` to create the Github repos using that authentication method too rather than using a PAT or Github App.

**Comment by OrkoHunter** [comment]
Done in https://github.com/backstage/backstage/pull/6275
