### ISSUE TITLE
[Cost Insights Plugin] Provide components to display cost info on Entity pages

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#6223]
## Feature Suggestion

Export components similar to other plugins such as `EntityCostsContent`, `EntityCostsCard`, etc. so that cost data can be embedded on entity pages.

## Possible Implementation

The existing charts/components in the Cost Insights page looks like they could be exported as standalone plugin extensions and possibly powered via entity annotations that define a specific project (and maybe specific product/service) to fetch cost data for.
## Context

I think it would be valuable to bring cost data to the entity level so that you could look at a component page and see the costs associated with its project. Depending on how consumers model their architecture and cost projects, this can also support `Domain`, `System`, and `Resource` views that would surface the costs behind that entity

**Comment by timbonicus** [comment]
This definitely makes sense, and is our ideal state internally at Spotify!

The first hurdle is making sure that all costs incurred by an entity are _associated_ with that entity. A backend service, for example, has obvious runtime cost -- such as a VM or kubernetes pods -- but it may also have storage buckets, a database, pub/sub topics, etc. Engineers will naively assume **all** costs for the entity are being shown, so you either need to have a very complete allocation of these costs up front, or be **extremely explicit** about the potential incompleteness of the costs shown. There could be even more obscure costs to allocate as well - network egress, IP reservations, partial cost allocation of shared infrastructure resources (think builds, event infrastructure, tracing, metrics).

I think cost allocation is the **most** straight-forward at the `Resource` level. In an ideal world, all cloud resources exist as `Resource` entities in the software catalog. These represent a simple bucket, or database, and should have a much more direct mapping to billing data from a cloud provider. Then, if a `Component` has a complete mapping to its resources through [dependsOn](https://backstage.io/docs/features/software-catalog/descriptor-format#specdependson-optional) relationships, calculating costs becomes a simple aggregation of costs from all resources. This follows for `Domain`, or `System` which in turn roll up costs from all descendent entities.

So definitely possible, but this assumes a high level of maturity in capturing cloud resources in the catalog and establishing and maintaining all the proper relationships between those and the software entities associated with them. We haven't gotten there ourselves, even after significant and sustained effort.

The Cost Insights plugin sidesteps this problem at the moment by presenting costs in terms of cloud product first, then by entity. This makes it abundantly clear what category of costs are being shown for that entity, and allows a gradual rollout of allocations and more supported cloud products.

The next hurdle is deciding on a sensible display of these costs on entity pages. There's the aforementioned clarity on what costs are represented, if you haven't achieved that cost maturity. The Cost Insights page also shows costs as comparisons across time periods, mostly -- month over month, quarter over quarter. This makes sense if you're looking broadly at costs for all the things you own, and wanting to see trends over time. For a single entity, it's more likely that you'd want to see day-by-day costs, a simple cost graph over time, perhaps a stacked graph split by the underlying `Resource` entities. Ideally this would also show reference lines for events like deployments, so that a spike in cost could be traced back to a certain event.

Hopefully this isn't discouraging, I think any explorations in this area are extremely valuable -- we have our sights set on this as a north star goal. I have no doubt that this could also be achieved in a step-wise fashion, so long as the limitations are made clear along the way. I just wanted to share the hurdles we're aware of, having explored a little way down this path.

**Comment by kuangp** [comment]
Thanks for your inputs Tim! We definitely understand and agree that proper cloud cost attribution is a difficult problem to solve and something we're also struggling to get right but the Cost Insights plugin has definitely been valuable in surfacing this data for teams.
