### ISSUE TITLE
Backstage - Oracle DB support - has anyone done it?

### ISSUE THREAD

**Issue by vikramaroskar** [backstage/backstage#6235]
I have seen Sqlite3 as default and Postgresql as a possible.

Has anyone done with Oracle as backend DB?

**Comment by freben** [comment]
Just correcting slightly - we are heavily dedicated to postgres, certainly in production - and sqlite is there as a little convenience for local development.

**Comment by vikramaroskar** [comment]
Thanks @freben 

We're looking to deploy backstage internally into my current workplace' customer's work company. And only Oracle is officially allowed to be used for compliance.

Not sure about how much we'll be allowed to explore/spend t & m on that. 

Can you point me to the link for(We've set the stage...)
Will update if exploring that opportunity.  
Thanks again. 
-Vikram.

**Comment by freben** [comment]
On the technical side, the stage is set in a number of ways.

- All database access happens through the [knex library](http://knexjs.org/), which has official support for Postgres, MSSQL, MySQL, MariaDB, SQLite3, Oracle, and Amazon Redshift.
- Database migrations also happen through knex
- We have set up a set of [testing utilities](https://github.com/backstage/backstage/tree/master/packages/backend-test-utils/src/database) that let us perform automated testing in CI toward any number of database engines.
- We are careful to avoid esoteric / engine specific semantics in database code, and if we do because it turns out to be vastly beneficial (e.g. `... FOR UPDATE`) or even necessary (e.g. `datetime()` vs `dateadd()` semantics), we make sure to support both alternatives in dedicated paths to keep compatibility.

I hope this helps.

**Comment by fcorti** [comment]
Hi @vikramaroskar,

if your organization will allow your team to work on this topic let us know because it would be an interesting feature for the product.

Would be great to know if other organizations would be interested. Please drop a message here if interested or contact me in private.

Thanks.

**Comment by vikramaroskar** [comment]
@freben Thanks for the doc and details. Helps me a lot.

@freben @fcorti Like I said, I'm not sure, whether I would find t & m for that in my current work engagement model. Would be sharing this issue/page as a reference for higher ups to make an informed decision.
But am sure, more people would definitely find it useful otherwise as well.

Thanks.
Vikram.

**Comment by freben** [comment]
Yeah for sure, and our intent and desire to support multiple databases has been there from the start. I personally also think that it is important. We'd love to find someone to help make the final pieces fall into place.

**Comment by freben** [comment]
Hey would you mind if I converted this into a question instead under Discussions? Then we can make an issue specifically asking for the Oracle support, and other database vendors can follow later. It's perhaps easier for others to find this question there, and it's probably easier to field for help / input in the form of a feature request ticket. I can help write the latter one with some details of what work would be involved.
