### ISSUE TITLE
"View in Catalog" button in scaffolder no longer appears with new catalog processing engine

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#6301]
## Expected Behavior

A the end of the scaffolder execution, a "View in Catalog" button should appear linking to the newly registered entity (if configured in the template)

## Current Behavior

"View in Catalog" button no longer appears and entity takes a minute before appearing in the catalog.

## Possible Solution

Process newly registered entities instantly?

## Steps to Reproduce

1) Run a scaffold on a template that has `output.entityRef` configured
2) After the scaffold completes, no "View in catalog" link appears
3) New entity does no appear in catalog, it shows up eventually after a minute or so

## Context

I'm assuming this is due to upgrading to the new catalog processing engine where entities are now scheduled for updates which creates a delay between when they are registered and actually appearing in the catalog. I observe the same behavior when manually registering new entities, they take a minute before showing up in the frontend.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 18.04 LTS 
- Browser Information: Chrome

**Comment by Rugvip** [comment]
Thank you for reporting, this does indeed need a fix 👍

**Comment by kiranpatel11** [comment]
In our case, it takes significant times - about 10 mins - for a template to appear after the registration.

**Comment by benjdlambert** [comment]
Hmm - yep so I think there's two parts here @kiranpatel11. Looks like theres the actual feedback with the button when you add to catalog which is due to the async nature of the new catalog, and then there's the actual import and refresh loop which looks like it might have been taking a while for you. Do you have a lot of entities locally? Thinking that the import of the location might be behind the queue of things that you have running already.

**Comment by kiranpatel11** [comment]
@benjdlambert we are having about 90 odd entities only in our catalog atm, and it takes about 2mins for the entity to appear in catalog after the registration. 
is there a way we can see refresh queue in logs or db ? any tuning to optimize the refresh....particularly for new registration ?
Due to this delay....the user experience is bit confusing....most of the time they end-up retrying and that results into location already exists error.

**Comment by freben** [comment]
We really should make the registration "eager" (to complete it immediately upfront) instead of "lazy" for this operation. That would likely be the most proper fix.

We do not have an exposed refresh queue interface, but certainly when checking the backend logs (in particular in debug mode) it outputs a lot of refresh loop info. It's curious that your delay time was so long - sounds like the processing should have proceeded faster than that through your entities. But it also depends on the [refresh timer](https://github.com/backstage/backstage/blob/29862be2bc6847c28f7c47cfff46ec3fcf6f3699/plugins/catalog-backend/src/next/NextCatalogBuilder.ts#L149) that you set [in the catalog builder](https://github.com/backstage/backstage/blob/29862be2bc6847c28f7c47cfff46ec3fcf6f3699/packages/backend/src/plugins/catalog.ts#L27).

**Comment by kuangp** [comment]
> If the refresh is progressing so slowly that everything has its next refresh queued to actually happen in the past, rather than the future, then the newly added things will stand in line waiting for those other things to complete. This should of course not normally happen...

I have a situation which may result in this scenario. We have a large Group entity that contains members representing all our engineers (~4K) and it seems like refreshing all the affected relations on the User entities would clog up the queue

**Comment by freben** [comment]
> I have a situation which may result in this scenario. We have a large Group entity that contains members representing all our engineers (~4K) and it seems like refreshing all the affected relations on the User entities would clog up the queue

Alright! Do you happen to know how long a single refresh of that actually takes end-to-end, and what your refresh interval is set to in your `CatalogBuilder` in the backend? I'm starting to wonder if there are overlaps. I.e., that a refresh starts, which moves a lock timestamp forward by X units, and then the refresh takes so long that another worker deems the process as "stuck" and starts doing the same work in an overlapping fashion. Would be neat if we could deduce whether this is the case.

**Comment by kuangp** [comment]
hm I'm not sure how long the refresh takes, do you have any recommendations on how to measure that? It's the same behavior we [discussed briefly in discord](https://discord.com/channels/687207715902193673/687235481154617364/859455680305037353) where I'm observing the constant "stitching" process in my DB logs 

Our refresh interval is set at 10mins

**Comment by kiranpatel11** [comment]
> We really should make the registration "eager" (to complete it immediately upfront) instead of "lazy" for this operation. That would likely be the most proper fix.

@freben, is this fix being tracked via this issue ? Does it have defined timelined yet ?
