### ISSUE TITLE
Dependencies between systems

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#6312]
As per the Backstage documentation, a System is an entity that gathers several components to achieve a particular task.

For instance We have a set of lambdas an pipelines for a specific data processing, they together can be modeled as one system.

Then we have another system, a set of containers that will access the final data and do other things.

So it seems that the most natural way to model this would be that the second system here depends on the first. 

But `dependsOn` is only available for components. So we need to hack around depending on the last lambda component of the system even when is the whole system we need.

**Comment by freben** [comment]
I wish this would be possible to make as a transitive property instead. For example

```
SYSTEM_ONE
  - Component1  dependsOn:Component2
SYSTEM_TWO
  - Component2
```

translated automatically to

```
SYSTEM_ONE      dependsOn:SYSTEM_TWO
  - Component1  dependsOn:Component2
SYSTEM_TWO
  - Component2
```

Without having to make that claim explicitly as an end user. Unfortunately, currently processors don't have a global view of their surroundings at processing time, at the moment.

So in the mean time, I wonder if this is something that could be done in the caller end instead. With a few API calls, you could grab all of the components in SYSTEM_ONE, gather up the union of their dependencies, etc.

**Comment by andrewthauer** [comment]
The idea of a system to system relation being transitive makes a lot of sense. Systems are typically a logical construct we use to group a series of smaller parts in order to reason about things at a higher level. In this vain a component most likely depends on another component of another system rather then the other system itself. Unless perhaps you have a system gateway, but you could argue this is also just a component of the system.

This sort of thinking / discussion has come up more recently in regards to the system diagram and what it "could be" (#4502). I think it would be really neat if there were extension helpers to build relation graphs between entities in various ways. One of these could be a transitive system to system graph which could then be presented in the Backstage UI in various ways as needed.

**Comment by freben** [comment]
> From this perspective a component most likely depends on another component of another system rather then the other system itself.

Yes, but, in the ideal scenario I think the idea then, is that the other system's API entity would be exposed by the system too, as part of its external surface. Either way you'd perhaps depend on the API, not the component. But I get what you're saying; the same issue might crop up in regards to Resource kinds too. However ... doing too much such cross linking might be indicative either of opportunities for improvement of the actual services, or for redrawing the system boundaries a bit.

> Unless perhaps you have a system gateway, but you could argue this is also just a component of a system.

This might be one of those API + service Component combos though.

We have some examples like that, where there's some core "inner" authoritative service, but a proxy service on top of it that's very lightweight and massively scaled and handles like rate limits, caching and transcoding of responses. You'd be expected to consume the outer one as an end user, unless you had excellent reason not to.

> This sort of thinking / discussion has come up more recently in regards to the system diagram and what it "could be" (#4502). I think it would be really neat if there were extension helpers to build relation graphs between entities in various ways. One of these could be a transitive system to system graph which could then be presented in the Backstage UI in various ways as needed.

Makes sense, it's going to be interesting to see what innovation that happens in the future for these ecosystem overview type things.
