### ISSUE TITLE
dependencyOf relationship is one-sided in the UI

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#6334]
## Expected Behavior

1. Specify a `dependencyOf` relationship indicating that component A is a dependency of component B.
2. Visit component B in the UI.
3. I expect the `EntityDepdendsOnComponentsCard` to list component A.

This behavior is what happens when I instead specify that component B `dependsOn` component A.

## Current Behavior

Component A is not listed.

## Possible solution

1. Fix the code (😄 )

## Steps to Reproduce

1. Load [this catalog-info file](https://github.com/RoadieHQ/sample-service/blob/main/catalog-info-ridesharing.yaml) into Backstage.
2. Ensure the `EntityDepdendsOnComponentsCard` is present in the UI
3. Visit the passenger-backend service.

[Here's a video](https://www.loom.com/share/9cda926759494d21b46af0bf7ed88435) showing me reproducing the problem.

## Context

I'm trying to indicate dependencies between components in Backstage.

## Your Environment

I'm using latest master as of today to reproduce this.

**Comment by freben** [comment]
Alright, I got around to looking at this.

The answer, in the end, turned out to be that there [is no such thing](https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component) as `spec.dependencyOf` in the model at all :) These `spec` fields are added selectively, in places where they make the most sense, and may sometimes even have names that do not correspond to the relation type name at all. So there is no guaranteed relationship between `spec` and `relations` at all; it becomes what we make of it.

Adding the following to the `BuiltinKindsEntityProcessor` [here](https://github.com/backstage/backstage/blob/ef8df1b162df8fa8ee60d360fc98c73e766b8b86/plugins/catalog-backend/src/ingestion/processors/BuiltinKindsEntityProcessor.ts#L178):

```ts
      doEmit(
        (component.spec as any).dependencyOf,
        { defaultNamespace: selfRef.namespace },
        RELATION_DEPENDENCY_OF,
        RELATION_DEPENDS_ON,
      );
```

makes the requested table row appear. Note the `as any` since it does not exist on that type really.

So as far as the bug goes, this works as designed. Question is, should there be a feature request to add the ability to specify the inverse dependency. Maybe? Is that a "good practice" or just confusing? It kind of lets non-owners of a service declare that that service depends on them - confusing or good?

**Comment by freben** [comment]
Let me add that it's super nice how you added video context and even test data, it made it so much easier to zoom in on what to actually look at and what the actual missing piece was. Really appreciated, I know it also takes a lot of effort to make thorough bug reports.

**Comment by dtuite** [comment]
When I was opening the issue, I actually added "remove dependencyOf" as one of then the potential solutions but then I deleted it because I thought it would be too difficult a breaking change.

Just updating the docs to remove any mention of dependencyOf is a reasonable solution now imo.

**Comment by dtuite** [comment]
If you agree, I can finish this out myself btw.

**Comment by freben** [comment]
Oh remove from where? Not sure I follow. Is this wrong in the docs somewhere?

The relation type does exist and should keep existing.

**Comment by dtuite** [comment]
@freben Maybe I'm misunderstanding your message but you seem to be saying that, while the [Well-known Relations docs](https://backstage.io/docs/features/software-catalog/well-known-relations#dependson-and-dependencyof) mention a `spec.dependencyOf` relation, none of the Kinds actually support it.

If that's true, my proposal is just to remove all mentions of `spec.dependencyOf` from the docs to prevent the kind of confusion I experienced.

Once that's done, we can have a separate RFC to discuss whether or not the relation should or should not exist. As you say, it might be a good practice or it might be kinda confusing.

**Comment by freben** [comment]
No, let me clarify again.

Relations are arrows. They can pop into existence in many ways. Maybe by ingesting some third party graph database. Maybe as computed by some `spec` thing. Maybe as a side effect of some other file that lies next to the yaml file. The point is, relations are _an entire thing of their own_ no matter what the entities as such are up to. There may be relations that are generated without ever being mentioned in any entity anywhere.

Relations, as a matter of fact, aren't even strictly attached to entities in the database. You emit arrows that float freely in space, in a table of their own. Then, as we form the actual generated JSON that you see when you query the REST API, we look for arrows that emanate from each entity and "stitch" them in. You are free to emit a relation that starts and/or ends in a void because there is no matching entity; it just won't be seen because it won't get stitched into anybody.

You expressed it as "none of the Kinds actually support it", which given the above is a statement that can never be true. Anything can have any type of relation with anything, in theory. What we do though, is we carefully choose what ways we expose for "popping into existence" of such relations.

Now also remember, these are always generated in PAIRS. Always, no matter what.

What you have seen now, is that there IS an ability to say

> A.spec.dependsOn: B

but there is NOT an ability to say

> A.spec.dependencyOf: B

... _using the spec, specifically, currently_.

However, it is perfectly possible to express the _relation_

> A dependencyOf B

As a matter of fact, the single spec field

> A.spec.dependsOn: B

generates the _pair_ of relations

> A dependsOn B
> B dependencyOf A

And if we happened to introduce the `spec` field

> B.spec.dependencyOf: A

It would generate the _pair_ of relations

> A dependsOn B
> B dependencyOf A

Note how the relations would be the exact same ones, because it doesn't matter from "which side" the relation is generated, the outcome is the same. The same thing happens where you can choose whether you make the claim that your user is a member of a group, or whether the group has a user as a member. The generated relation pairs are identical either way. You can even duplicate the information and redundantly declare it from both ends simultaneously; the generated relations get deduplicated before stitching them into the final entities.

**Comment by freben** [comment]
I think there's an underlying assumption that because `spec.x` exists, the relation `x` exists. But the two just aren't tied to each other. As a matter of fact I was a bit hesitant to introduce `spec` fields that happened to have the exact name as a relation, because this sort of confusion would inevitably arise :) I had hoped that the `spec` fields would typically be more ... you know, "semantic"? At the very least, on a noun form. `spec.owner`, which translates to `ownerOf` + `ownedBy`. `spec.members` which translates to `memberOf` + `hasMember`. Etc

**Comment by freben** [comment]
Oh wait. I see that I am being dense here. I misread what you said but I'll leave in the wall of text just to be sure. What you explicitly said was to address `spec.depencencyOf` occurrences, which indeed would be a good thing to do! But I searched locally real quick here and I don't think I see any occurrences of that?

**Comment by dtuite** [comment]
>  It'd be like me making the claim "I'm a friend of the king", but the king is likely to disagree and prefer to choose his friends himself.

😂 

Totally take your point about specs and relations being different and so on and, like you think I realised late in the conversation, I'm not recommending that the relation be removed. The clarification does help though, because as a lay-person reading the docs and trying to map an architecture to Backstage terms, I didn't really grok that the `spec.x` properties are generators of relations rather than relations themselves.

When I read [The Well-known Relations doc](https://backstage.io/docs/features/software-catalog/well-known-relations#dependson-and-dependencyof), this was my thought process:

1. I see "They can be attached to catalog entities and consumed by plugins as needed." and I think "attached to catalog entities" means I can attach them to the spec section in `catalog-info.yaml` files.
2. Further down I saw "`dependsOn` and `dependencyOf`" and they seem equivalent except for direction.

Through experimentation, I later learned that they are not equivalent because I, as a user, can make things happen with `dependsOn` but not with `dependencyOf`.

Looking again, with the benefit of your explanation above, I can see now that the [YAML file format docs](https://backstage.io/docs/features/software-catalog/descriptor-format#specdependson-optional) do distinguish between `dependsOn` and `dependencyOf`. They don't actually say that `spec.dependencyOf` exists, I just assumed it did because `spec.dependsOn` happens to have the same name as the other side of the relation.

With all of that knowledge now in place, I'm not sure what to do. Either the model needs to be more understandable or I need to be better at understanding it 😄 . I will close this issue though, because like you say, it is working as expected.

**Comment by freben** [comment]
I'm totally understanding that the docs are not yet ascended to their fullest :P

**Comment by andrewthauer** [comment]
I fell into tree same trap actually. We have a shared db resource that I thought it would be quicker and easier to use dependencyOf instead of going to each component using it. I then realized it didn't work the opposite way.

**Comment by gmambro** [comment]
> I fell into tree same trap actually. We have a shared db resource that I thought it would be quicker and easier to use dependencyOf instead of going to each component using it and saying dependsOn. I then realized it didn't work the opposite way.

+1
