### ISSUE TITLE
Scaffolder error for fetch:cookiecutter action - Docker does not appear to be available

### ISSUE THREAD

**Issue by thiago4int** [backstage/backstage#6368]
Being able to deploy Template from catalog utilizing skaffolder

Not able to fecth Docker

## Steps to Reproduce

1.  Create template
2. Fetch Skeleton + Template
3. Fail

## Context

```
2021-07-06T23:42:23.000Z Beginning step Fetch Skeleton + Template
2021-07-06T23:42:23.000Z info: Fetching and then templating using cookiecutter {"timestamp":"2021-07-06T23:42:23.612Z"}
2021-07-06T23:42:24.000Z Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with: connect EACCES /var/run/docker.sock
```

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Debian 10):
- Browser Information: Chrome

**Comment by timbonicus** [comment]
The `fetch:cookiecutter` action requires the [cookiecutter](https://cookiecutter.readthedocs.io/en/1.7.2/) command-line utility to be present. If the cookiecutter command isn't found, the scaffolder attempts to launch a docker container to run cookiecutter. It seems the error here is reporting that neither cookiecutter nor Docker was available in your environment to run this action.

There's a few ways forward:
- Modify your build or environment to include the `cookiecutter` command; documentation on that [here](https://backstage.io/docs/features/software-templates/configuration#disabling-docker-in-docker-situation-optional)
- Enable Docker so that the backstage-cookiecutter Docker image can run instead
- Wait for [fetch:template](https://github.com/backstage/backstage/pull/6322) to shortly become available and use that instead. This is a node-based templater that won't require cookiecutter, which will put an end to this common source of confusion 🙂
