### ISSUE TITLE
docs: Package API Reports should show up on backstage.io/docs

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#6417]
All of our plugins and packages export APIs, and the API reports are generated for each package e.g. https://github.com/backstage/backstage/blob/master/packages/backend-common/api-report.md

It will be nice to see a version of these reports with documentation under https://backstage.io/docs/api/backend

**Comment by OrkoHunter** [comment]
So, it looks like the `yarn build:api-docs` command is supposed to generate these API references inside `docs/references` and docusaurus is able to display them locally!

For some reason, it seems to be disabled. Would love if someone can share the history behind it. cc @backstage/reviewers

**Comment by Rugvip** [comment]
The API reports are optimized for diffing and are therefore not great as docs, most importantly they don't contain any doc comments.

There's indeed the `build:api-docs` command, you can try it out and look around in `docs/reference` if you want. When @grantila and I were looking at this we stopped at shipping the API reports, since the docs required quite a bit more work. The main pain points of the generated docs are that they don't work very well with React components and that functions defined as `const ... = (...) => ...` show up as variables which produce considerably worse documentation. Overall variable docs aren't great, meaning it's not that good for API References either.

The docs generation in API extractor is prolly the best one around still, so I think we should move forward with it, but we need to refactor a bunch of code and possibly create our own markdown generator for it to generate decent docs. It's not a huge amount of work but it hasn't received priority so far

**Comment by OrkoHunter** [comment]
Thanks for the context @Rugvip !

**Comment by OrkoHunter** [comment]
Potentially closed by https://github.com/backstage/backstage/pull/7150 ?
