### ISSUE TITLE
Make it easier to find out how to delete a template

### ISSUE THREAD

**Issue by niallmccullagh** [backstage/backstage#6428]
## Feature Suggestion

Make it easier to find out how to delete a template. 

## Possible Implementation

Create a link on the template `title` to the catalog entry to each of the available templates in `/create`. This would allow  a user to easily follow the normal unregister a component.

## Context

It is diffifult for a user to understand how to delete a template:
1. Lack of documentation
2. Difficult to find template in catalog

**Comment by timbonicus** [comment]
Another possible implementation is showing kinds other than `Component` on the catalog page. So one could select `Template` and see all registered templates through the catalog interface (or `User`, `Group`, `Resource` etc). The capability is there already in [EntityKindPicker](https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/EntityKindPicker/EntityKindPicker.tsx), but it has no UI at the moment since a design proposal is needed.

As a workaround, you can visit `/search` which has a `kind` filter and select `Template` there without any search terms. A bit awkward, to be sure.

**Comment by benjdlambert** [comment]
As discussed on discord, I'm wondering if it makes sense to add a little `View in Catalog` icon on the Template Cards in the `/create` screen list. Right now it's a little abstracted away as they're not in the main `/catalog` view as that default to `Components`.

Maybe the actual solution is to be able to browse everything in the Catalog, but that opens up more questions really in terms of is that really what we want either?

**Comment by benjdlambert** [comment]
Can we close one now as we should be able to see the templates in the entity page now there's a filter for the type of `kind` you want to see?
