### ISSUE TITLE
[RFC] Scaffolder: Unify templating syntax used in template.yaml and the template skeleton

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#6437]
**Status:** Open for comments

## Need

In a standard Backstage Software Template ([Example](https://github.com/backstage/software-templates/tree/main/scaffolder-templates/react-ssr-template)), there is a [`template.yaml`](https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml) file which is an Entity descriptor file of the [Template kind](https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template) and a directory (e.g. [`skeleton`](https://github.com/backstage/software-templates/tree/main/scaffolder-templates/react-ssr-template/skeleton)) which contains all the templated files and folders.

Up until now, we only had one major templating action available called `fetch:cookiecutter`. This resulted in our skeleton files and folders to be templated with [Jinja2](https://jinja.palletsprojects.com/en/2.11.x/) syntax as this is what cookiecutter expects. The templating syntax of Jinja2 looks like `{{ variable | filter }}` and `{% statement %}`.

On top of the skeleton, the `template.yaml` files themselves need to be templated in [places like setting `values` as inputs for the templating action](https://github.com/backstage/software-templates/blob/3bdd183f052f5971379a4bbfe658829de366decb/scaffolder-templates/react-ssr-template/template.yaml#L54-L58). This confusingly looks like a Jinja2 Syntax `'{{ variable }}'` (it isn't exactly) and is managed using a library called [handlebars](https://handlebarsjs.com/).

With this context, we reflect on some of the problems that exist as of now -
* When writing a new Software Template, users need to understand two templating syntaxes, one for template.yaml (handlebars) and one for the skeleton files and folders (Jinja2).
* Using handlebars forces all variables to be wrapped in quotes, since the expression syntax used in handlebars conflicts with YAML object literal syntax.

## Goals/Proposal

**1. Unify templating syntax of `template.yaml` and the `fetch:template` action**

A new `fetch:template` action was introduced in https://github.com/backstage/backstage/pull/6322, which is a node-based templating action and doesn't need Python/Cookiecutter dependencies. This is going to be the "default" or a recommended templating action. With this in mind, we propose updating the syntax used for variables in `template.yaml` to match the syntax used in `fetch:template`, in which expressions are enclosed in `${{ }}`.

**2. Make it more intuitive to insert non-string variables in `template.yaml`**

Right now it's possible to insert non-string variables in `template.yaml`, but the syntax is counter-intuitive - to insert the array variable `myArray` as an array, the parameter needs to be set to `'{{ json parameters.myArray }}'`. It would be preferable to keep the syntax identical to that used inside skeletons, such that the same variable could be inserted with simply `${{ parameters.myArray }}`.

**The [GitHub Actions workflow syntax](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions) is a good inspiration for both of these goals.**

## Alternatives

Open for suggestions!

## Risks

To avoid this being a breaking change, we should create a new `apiVersion` for the `template.yaml` Entity description; most probably `backstage.io/v1beta3`

**Comment by benjdlambert** [comment]
Probably would be good to maybe reference an example here of what it would look like compared to the current implementation, and how we can solve the `registerHelper` calls that have already been setup with the new templating nunjucks for instance (it's pretty simple I know but good to show what it would be converted to, like the new `eq` helper).

Also the migration path should be pretty simple, and we should be able to provide a codemod or something similar to do this I would expect.

**Comment by freben** [comment]
Maybe mention why `${{` would be picked over simply `${`.

**Comment by OrkoHunter** [comment]
Thanks for raising @freben. I'm not sure why. I'll also add that [`${ }`](https://backstage.io/docs/conf/writing#environment-variable-substitution) is being used in `app-config.yaml`.

**Comment by benjdlambert** [comment]
I'd say that the substitution in `app-config.yaml` is only for Environment Variables so and I think it aligns nicely with bash syntax of `${ENV}`.

This I think is still open for discussion if to be honest, but I like `${{ }}` as it's pretty clear when glancing through a document what is a template var coming from using `cookiecutter` and `handlebars` before. It's also pretty widely used in other template languages too, so i'm thinking the familiarity is good.

Thoughts?

**Comment by freben** [comment]
No strong opinions here, just nice to have the rationale, so all good. I was thinking from the angle of ease/convenience of typing out these templates, but it's not a big deal either way

**Comment by Rugvip** [comment]
I think double curlys, both `${{ }}` and `{{ }}` makes a lot of sense in the template contents, as it avoids collisions with for example usage of `${ }` in shell scripts etc. I'd say it's less important for us to use that in the template definition though, as we're not mixing it with shell scripts. GitHub Actions do mix with shell scripts, which is why they need the full `${{ }}` syntax.

Can distill that to two simple rules for templating with curly brackets for our use-cases:

* If the template is defined in YAML, prefix with `$` to make it be treated as a string
* If the template is commonly mixed with syntax that conflicts with the single-bracket variant, use double brackets

So we could either go for `${ }` or `${{ }}` in our template definitions (not that we've been discussing anything else 😅), and so far I can think of the following reasons for either

Reasons to go with `${{ }}`:

* It matches the current syntax of our template actions, making it more familiar
* It's more forwards-compatible with additions to the template definitions that could conflict with the single-bracket version

Reasons to go with `${ }`:

* It more clearly distinguishes the template definitions from the template contents, in the case where those are different.
* It is slightly less noisy to read and write

From my point of view the clarification of the relation between the template definition and contents is the most important reason to go with either syntax. I'm thinking that if we can use the exact same syntax and helpers in the template definitions as in the template action, then we should go with `${{ }}`, otherwise, we should go with `${ }` to avoid confusion between the two templaters. I'd also say that the ease of use of the template definition syntax is a higher priority than using the same templating syntax for the two use-cases, and that support for passing through complex values is very important.

**Comment by OrkoHunter** [comment]
Looking at the activity on this one, let's close this RFC now. Thanks all for the comments! A task meta issue to follow next. 🙏
