### ISSUE TITLE
feat request: support updating the scaffolding template

### ISSUE THREAD

**Issue by missedone** [backstage/backstage#6527]
once the scaffolding template is registered, we're not able to modify on the backstage web UI.

## Feature Suggestion

as the scaffolding template maintainer, after registering it to the backstage, i'd like to modify the template metadata like template name, url (for example, switch from testing branch to release branch), etc.
for now the only way is request the devops has admin access to modify in database directly

**Comment by benjdlambert** [comment]
The demo templates that are shipped with Backstage are designed to be replaced with your own templates. You can of course copy the contents of them from [this](https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates) folder and push them to your own repo, where you can change the name or whatever in the `template.yaml`

**Comment by OrkoHunter** [comment]
@missedone

> for now the only way is request the devops has admin access to modify in database directly

Not really. If you are loading templates from a remote git location like [this](https://github.com/backstage/backstage/blob/5b9e6a78b56533ebb39cbb3b8b55683b0aa09828/app-config.yaml#L248-L249), you can update the templates in their source control repository and they will automatically be updated in the database. Since most of the template is just code, it's easier to modify them using a code editor.

**Comment by missedone** [comment]
ok the template content for sure is reloadable, in case if change the branch, for example, i'd like to change from test branch to the final branch for the template.yaml file
