### ISSUE TITLE
Remove Filtered Table & CheckboxTree from core-components

### ISSUE THREAD

**Issue by tudi2d** [backstage/backstage#6618]
At the moment the Filtered Table component is only used in the FOSSA Plugin. In the catalog & the API docs we decided against this component (Context: https://github.com/backstage/backstage/pull/6397#discussion_r670007241)

| Filtered Table | CheckboxTree |
|:---:|:---:|
| <img width="861" alt="Screenshot 2021-07-27 at 11 06 18" src="https://user-images.githubusercontent.com/8904624/127127823-0e43a08d-f52e-48fc-ae40-95ef95a836a1.png"> | <img width="410" alt="Screenshot 2021-07-27 at 11 06 46" src="https://user-images.githubusercontent.com/8904624/127127842-2a33e764-222b-4b4c-bfbb-0788f258b41c.png"> |

There is nothing bad about this component in general & it is still in the Figma. Nevertheless it is not used & not intended to be used. Additionally to the overhead added to the Table component it adds a new component called "CheckboxTree" to the core, which is only used inside the Filtered Table.

## Feature Suggestion

A good first move could be mark the components as deprecated.

The CheckboxTree component & the modified Table component could be moved to the FOSSA Plugin. This would remove unused code from the core. 

Alternatively the FOSSA Plugin could apply the filter behaviour of the api-docs plugin or catalog plugins.

## Context

- Filtered Table: https://backstage.io/storybook/?path=/story/data-display-table--filter-table
- CheckboxTree:  https://backstage.io/storybook/?path=/story/inputs-checkboxtree--default
- FOSSA Plugin: https://github.com/backstage/backstage/tree/master/plugins/fossa
- Catalog Page decided against using Filtered Table: https://github.com/backstage/backstage/pull/6397
- API Page abandoned Filtered Table: https://github.com/backstage/backstage/pull/5984

**Comment by benjdlambert** [comment]
Do you wanna work on this @tudi2d? or shall we add a `help-wanted` label on it?

**Comment by tudi2d** [comment]
Thanks for asking - feel free to add a `help-wanted` label :)

**Comment by ainhoaL** [comment]
Sounds like a good first issue, grabbing it :)

**Comment by ainhoaL** [comment]
After some investigation on where we are now and discussion with @OrkoHunter these are the steps we could take to complete the task:
- [FOSSA plugin](https://github.com/backstage/backstage/blob/master/plugins/fossa/src/components/FossaPage/FossaPage.tsx#L164) doesn't seem to be using the checkbox filter when using the Table filters (nor any other place), so the CheckboxTree component could just be removed.
- Moving FOSSA Page to use `EntityListProvider` instead of `Table` as a way to phase out the filters for the table as it is the only plugin using them.
- Remove the filters from the Table component (only the FOSSA plugin is using the table with filters).

Removing both CheckboxTree and filters from the Table component would impact any external plugin that uses them. What would be the process for that? minor version bump for breaking changes + migration doc?
@timbonicus, what do you think?

**Comment by timbonicus** [comment]
Yep, sounds good to me. If you want extra credit you could also convert `EntityListProvider` and the hook to use `createVersionedContext` similar to #7149 😄

**Comment by Rugvip** [comment]
@timbonicus possibly, although `createVersionedContext` should only be used when there's a possibility that the provider and consumer of a context are in different installations of a package, since it does add some unnecessary complexity otherwise.

**Comment by ainhoaL** [comment]
Seems like I spoke too soon! After playing around with this I don't think the FOSSA page can move to use EntityListProvider, because it wants to get the entities and then use some of that information to query their own [fossa API](https://github.com/backstage/backstage/blob/master/plugins/fossa/src/components/FossaPage/FossaPage.tsx#L196) and feed all of that info into the [table](https://github.com/backstage/backstage/blob/master/plugins/fossa/src/components/FossaPage/FossaPage.tsx#L232). Correct me if I am wrong but it looks like `EntityListProvider` only deals with entities from the catalog and does not take in external data.

That would mean the FOSSA page still needs to use the Table component (with filters). And so, the best we can achieve right now is to remove the CheckboxTree component.

**Comment by benjdlambert** [comment]
Probably can remove these now as they've been deprecated a long time! :pray:

**Comment by kuangp** [comment]
hm was there a deprecation notice? I'm actually using the Filtered Table component in a new plugin I'm developing and didn't see any warning that it's going away besides this issue.

**Comment by benjdlambert** [comment]
@kuangp where are you importing the `FilteredTable` from?

**Comment by kuangp** [comment]
I'm doing `import { Table } from '@backstage/core-components';` and then setting the `filters` prop as described in the story: https://backstage.io/storybook/?path=/story/data-display-table--filter-table

Are we talking about a different `FilteredTable` component here? 😅

**Comment by benjdlambert** [comment]
I think we are, I'm pretty sure that it's already gone. Think it was something completely different :pray:
