### ISSUE TITLE
Create-plugin does not respect current app dependencies

### ISSUE THREAD

**Issue by laurieontech** [backstage/backstage#6636]
## Expected Behavior

The create-plugin command should respect the versions of backstage packages currently installed in the app.

## Current Behavior

Using the create-plugin command installs a new plugin with backstage dependencies that use caret notation, it then runs a yarn install. This bumps backstage packages in the yarn workspace for the entire project and creates mismatches. 

## Possible Solution

Since the backstage versions that get installed are based on the version of the CLI used it's possible to use yarn resolutions to enforce a CLI version (otherwise the CLI version installed in each new plugin will bump the workspace version). However, removing caret notation would potential solve this and allow users to rely on the version bump command to explicitly change versions across the workspace.

## Steps to Reproduce

1. Start with packages/app with not the latest backstage packages
2. Run create-plugin (this may bump some packages, but will certainly bump the CLI)
3. Run create-plugin and note that it's running with the new CLI version and therefore bumping additional packages, potentially even to major versions

## Context

We have external contributors creating plugins as their first and only interaction in the repo. Creating a scenario where they need to be able to adjust other plugins/the app in order to keep backstage package versions consistent is less than ideal. Additionally, this lack of consistency creates errors when running `yarn tsc` in certain cases.

## Your Environment

- Node 14
- yarn workspaces

**Comment by Rugvip** [comment]
This issue happens when the installed CLI version no longer matches the range query used in the project, since the Backstage CLI will use whatever version it's currently running and doesn't know about the original range. For example if you have `@backstage/cli: ^0.6.2` in your root `package.json` but you've since bumped it in `yarn.lock` to be at something like `^0.6.5`, the query in the new plugin will be `^0.6.5`, which might not exist in `yarn.lock`, and then you might get a duplicate and even newer version of the CLI pulled in for that plugin.

I think we have enough facilities in the CLI to make it reasonably simple to solve this by inspecting `yarn.lock` and picking an existing range query for each installed package if possible.
