### ISSUE TITLE
[RFC] Auth Redirect

### ISSUE THREAD

**Issue by samiramkr** [backstage/backstage#6648]
**Status:** Open for comments

## Need

In the Auth plugin in Backstage, when a request comes for authentication, Backstage detects the redirect URL from the `app-config.yaml` file which can be just an URL. At Spotify, we deploy UIs in a test environment that has a different URL than the production one. We need Backstage to be able to redirect back to a list of valid URLs.

### Current state

Now we can have only one URL as the `app.baseUrl` in the `app-config.yaml` file. 

## Proposal

I propose to add a possibility to handle the redirection by keeping the original URL in a stateless way (in OAuth you generally pass the URL to redirect back as a query param). Also accepting a pattern for defining valid URLs, [like](https://en.wikipedia.org/wiki/Wildcard_DNS_record) *.example.com which provides the possibility of passing a list of valid URLs.

**Comment by freben** [comment]
Hmm.

Usually you would only need one such param _per deployment_ right? What we usually do is to have config that changes per deployment;  by merging in several config files and/or using env variable substitution in the config. Could you set the base url and/or redirect to be something like `${TESTRUNNER_DEPLOYMENT_URL}/api/...` in an `app-config.testrunner.yaml` that's only used in the test env? Or does that not help with this situation

**Comment by joaomilho** [comment]
I would add the risk of not implementing the whitelisting correctly, and therefore allowing some malicious plugin to send users to a different place where they would collect data. Given providers also rely on whitelists this scenario is very unlikely, but it's worth doing the proper security due diligence when implementing it.

**Comment by joaomilho** [comment]
> Hmm.
> 
> Usually you would only need one such param _per deployment_ right? What we usually do is to have config that changes per deployment; by merging in several config files and/or using env variable substitution in the config. Could you set the base url and/or redirect to be something like `${TESTRUNNER_DEPLOYMENT_URL}/api/...` in an `app-config.testrunner.yaml` that's only used in the test env? Or does that not help with this situation

I would say this _is_ a viable option. On the other hand, we don't have any other reason to keep a testrunner specific config and as a principle we want to keep it's config as close to prod as possible (but again, I don't feel this particular case contradicts that). We already do that in the test environment, ofc.

**Comment by freben** [comment]
Right but, I think this solution might be the right one in this case unless I am missing something - remember that the configs are merged together, so the only thing in the test runner config will probably be "in this env I'm deployed on this dynamic host name given through the env" and everything else is the same. Sounds best to me to have that as a strict single setting with the right value for the env in question, rather than having many possible urls in the prod deployment of which only a single one is actually used.

**Comment by joaomilho** [comment]
Oh, I tripped. We decouple the UI deployments from the backend deployments, and the test UI builds point to the production backend, so the backend is not aware of the URLs, therefore rendering the app-config solution not useful for our use case.

**Comment by Rugvip** [comment]
Wanna clarify that it's the `origin` option in the `postMessage` call from the auth popup window that is the thing we want to tweak rather than the redirect, although that doesn't really have any effect on the discussion.

The way we do this atm internally is by passing the extra information through OAuth state, it looks something like this:

1. Frontend initiates auth, it checks its own host and if it's on something matching `https://preview-<id>.example.com`, if that is the case extracts the preview deployment ID and passes it on as a `preview=<id>` query param that gets added to the OAuth state.
2. User goes through the regular OAuth auth flow ending in the backend holding credentials to send back to the user
3. When sending back the result, the backend checks the OAuth state to see if there is a `preview` parameter present. If there is, it reconstructs the `https://preview-<id>.example.com` URL to use as the app origin rather than the configured one.

I expect us to be able to implement a similar flow here as well, but it does require adding new customizability to some places. There should be some significant overlap with #6449 here, as the first step is being able to send over custom OAuth state from the frontend. Then we could do the backend bits as an extension of #6245, probably adding an optional `appOrigin` return value from the `authHandler` or something of that sort, but tbh I think this might fit better as a global configuration for the auth plugin, passed in to the `createRouter`.

**Comment by samiramkr** [comment]
This PR will close https://github.com/backstage/backstage/pull/6772 this

**Comment by Rugvip** [comment]
Closed by #6772
