### ISSUE TITLE
Link group ownership boxes through to filtered catalog page

### ISSUE THREAD

**Issue by prasaria** [backstage/backstage#6681]
## Feature Suggestion

Link group ownership boxes through to filtered catalog page

## Context

In the group page there is Ownerships Card, containing Services , Documentation and other boxes that the particular group owned. I want to implement an active link if one of these boxes (eg: Services) is clicked , the page will moved to a filtered entity catalog page that is belong to that particular group.

<img width="1595" alt="Screen Shot 2021-08-02 at 13 31 56" src="https://user-images.githubusercontent.com/7909323/127814843-85a365b5-13a6-46c1-b8b9-0ae9541153c0.png">

**Comment by benjdlambert** [comment]
I think @timbonicus tried to do this recently, but found it a little harder that first thought, maybe he can share some learnings here :)

**Comment by timbonicus** [comment]
This is made possible by #6367, which added query param support for catalog filters. The URL would end up looking like:

```
/catalog?filters[kind]=component&filters[type][0]=service&filters[user]=all&filters[owners][0]=team-a
```

I think this should handle transitive ownership since it ends up being a catalog relation query. This would be a change in [OwnershipCard](https://github.com/backstage/backstage/blob/master/plugins/org/src/components/Cards/OwnershipCard/OwnershipCard.tsx#L138); could potentially remove the `Tooltip` logic in favor of this. The `useEntity()` hook within these components will return the `Group` entity for the page.

Nothing overly hard I think, but the components in there felt like they could use a reorg -- and rather than being 6 hard-coded tiles, these should probably dynamically reflect the top 6 entity types for that group. Tests, etc.

**Comment by prasaria** [comment]
Yes, it will be a change in OwnershipCard. Thank you @timbonicus for the valuable information that u shared. Ok, I will try to implement this as soon as I can, and you can assign this issue to me.

**Comment by prasaria** [comment]
Hello, I create new PR for this issue : https://github.com/backstage/backstage/pull/6823. Thanks !

**Comment by prasaria** [comment]
Hello @timbonicus , I create new PR for this issue : https://github.com/backstage/backstage/pull/6823. Could u help to review it ? Thanks!

**Comment by prasaria** [comment]
I will close the issue, since the PR related to this issue is already merged. Thank You
