### ISSUE TITLE
GitLab scaffolder visibility not working, private when set to public

### ISSUE THREAD

**Issue by maxhuebler** [backstage/backstage#6689]
## Expected Behavior

When creating a component through backstage, during the publish stage I expect the app to be set to public instead of private.

## Current Behavior

The repository that is created is set to private scope instead to public

## Steps to Reproduce

1. Set visibility to public in app-config.yaml
2. Create component pointing to a public group
3. Repository is private, not public

## Context

`scaffolder:
  gitlab:
    api:
      baseUrl: https://gitlab.com
      token: ${GITLAB_TOKEN}
    visibility: public # or 'internal' or 'private'`

**Comment by benjdlambert** [comment]
@maxhuebler I think this has actually been changed now so that it is a parameter you pass through on the action in the `template.yaml` it's not config driven anymore as sometimes you want the user to say if `private` or `public`.

I think under `publish:gitlab` action you can pass an `input` parameter called `repoVisibility: public`.

We should update the docs or remove the config either way.

**Comment by maxhuebler** [comment]
> @maxhuebler I think this has actually been changed now so that it is a parameter you pass through on the action in the `template.yaml` it's not config driven anymore as sometimes you want the user to say if `private` or `public`.
> 
> I think under `publish:gitlab` action you can pass an `input` parameter called `repoVisibility: public`.
> 
> We should update the docs or remove the config either way.

Okay cool, this solution worked. Thanks for the heads-up!

**Comment by benjdlambert** [comment]
No probs - gonna close this :)
