### ISSUE TITLE
Request to add Timestamps / Date in Changelogs

### ISSUE THREAD

**Issue by NishkarshRaj** [backstage/backstage#6721]
Hi,

I have created a backstage application with `npx @backstage/create-app`
To maintain it,  I would love to be in sync with the changes and for the same, I would like it to be standardized to add a date in the [changelog](https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md) file.

Although it is possible to track date and time by seeing history and matching the commit hash but it would make life easier if the dates are mentioned within the Changelog.

Thanks! 😃

**Comment by Rugvip** [comment]
One way to look up changes by date is to view the GitHub releases instead, https://github.com/backstage/backstage/releases. They include the changes for all packages in that release.

Otherwise this would really need to be a feature requests towards https://github.com/atlassian/changesets, as that's what we're using for change management.

**Comment by NishkarshRaj** [comment]
@Rugvip Thanks! Will track the releases going forward 👍
