### ISSUE TITLE
More flexible discovery processor configuration

### ISSUE THREAD

**Issue by sagacity** [backstage/backstage#6814]
## Feature Suggestion
The current way of configuring discovery processor targets is not flexible enough and should be extended.

## Context
In our organisation we use a self-hosted GitLab instance. I'd like to write a discovery processor for it, since Backstage currently does not have one.

The existing processors (like the one for GitHub) are configured by specifying a kind of glob target for discovering catalog files, e.g.:

```yaml
type: 'github-discovery',
target: 'https://github.com/backstage/*/blob/master/catalog.yaml',
```

This `target` [is parsed](https://github.com/backstage/backstage/blob/a52c5b8/plugins/catalog-backend/src/ingestion/processors/GithubDiscoveryProcessor.ts#L122) as being for organisation `backstage`, and for repositories `*`. In this case that means that all repos under `backstage` will have a `catalog.yaml` file in the root of the `master` branch.

This approach has a few issues:
* In our case we are self-hosting GitLab, so we wouldn't need the `organisation` part of the path. This is currently not supported by the GitHub processor, so I would have to take an alternative approach already for my GitLab processor.
* GitLab groups can be arbitrarily nested, there is not a clear `/org/repo` distinction like in GitHub. For instance, I could have a catalog file at `https://mygitlab/foo/bar/baz/qux/blob/master/catalog.yaml`. However, which part of the target is then the repository search path, and which part is the path to the catalog file? This is pretty ambiguous.
* The above target pattern now expects the main branch to always be called `master`. However, some tooling has been defaulting to `main` instead. This means that _some_ repos might use `master`, while others might use `main`. This is currently not configurable as far as I can tell.

## Possible Implementation
Perhaps the globbing can be extended, but it seems to me that this will become very complicated if it needs to support all use cases.

Instead, could the configuration of these processors be extended so that they may be configured with more than just a `target` string?

So, instead of:
```yaml
type: 'github-discovery',
target: 'https://github.com/backstage/*/blob/master/catalog.yaml',
```

It would be something like:
```yaml
type: 'github-discovery',
target: {
    host: 'https://github.com',
    org: 'backstage', // optional
    repoPattern: '*',
    branches: ['master', 'main'] // note: see below
}
```

Note: In the case of the branch names, the GitLab API also returns the `default_branch` name for a repository. So it could also be possible to just leave out this `branches` key and always assume the default branch. But I'm not sure how this would work for other processors.

## Context
I'm trying to write a Git**Lab** discovery processor and I ran into the above issues when trying to map things to our organisation.

**Comment by freben** [comment]
Locations unfortunately have a fixed shape - a type and a target, both of which are strings. We do not have room for making those complex objects at this point. There's been whispers about considering adding more metadata to locations (essentially more fields next to type and target), but I'm not sure at this point whether that is a realistic thing to hope for.

Your new processor would use a custom location type, `gitlab-discovery`. This lets you make any decision you deem appropriate for the target string. There are no requirements whatsoever on its format; it could be a large JSON document for all we know :) However, there is the additional factor, that these are strings that should be kind of reasonable for a human to look at and work with. More importantly, you do not have to worry at all about what choices the `github-discovery` processor made; if org is not a thing in your domain, just don't use that. Of course it's nice if the two processors work somewhat alike and look familiar to users.

Since you use a custom location type, you are also fully in control of its implementation without having to take any other actors into account. As such, you will be using the gitlab specific API client and can probably use that to decipher a URL to learn what pieces of it are parts of a nested group structure, what the branch is, etc. Or make bespoke code that just assumes that wherever `blob` appears first, is the delimiter. Which of course is risky if somebody names a folder `blob` :)

Regarding the branch name, you are free to use a glob or other bespoke marker there too. Maybe you can let people enter it as `/-/` (just a dash) or something similar, which your processor will handle as meaning "whatever the gitlab API returns as the main branch".

**Comment by freben** [comment]
And let me also add - if you deem it reasonable that users should be permitted to enter for example `https://mygitlab/**/blob/-/**/catalog-info.yaml` then you can, and it would be up to you to solve that using their API.

**Comment by sagacity** [comment]
My original reasoning was indeed that I'd prefer to keep the structure consistent with the other processors. However, if it's deemed acceptable to have different processor have quite different interpretations of the `target` string then that would be fine for me, too.

I'll try to come up with a proposal that encompasses all the use cases and mashes them into a reasonably easy-to-parse string :)

**Comment by freben** [comment]
Yep that's appreciated! I think it'll turn out to be pretty similar actually, with the addition of supporting globs for the left side (org / groups) too.

**Comment by freben** [comment]
Maybe I could mention, too, that if i recall correctly the github API actually has builtin transparent support for treating `main` and `master` equally - if you give the wrong one, it'll work anyway. I wonder if gitlab happens to have the same mechanism.

**Comment by sagacity** [comment]
Good to know! Although I did some checking earlier and I don't think GitLab supports this, but I suppose having a special character as the 'default branch' placeholder would work fine too.

**Comment by Rugvip** [comment]
Should mention here that long term we're leaning towards moving these more complex location processors to be "entity providers" instead, which is a more code-based approach that would allow for a lot more flexibility than configuration purely through yaml.

**Comment by sagacity** [comment]
Ah, that makes sense. For now I'll just start work on a PR that does some more elaborate `target` parsing, then.
