### ISSUE TITLE
Provide users feedback when their entities are "disconnected" due to renaming/moving of source entity files

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#6973]
## Feature Suggestion

Provide some kind of UI feedback on entity pages to alert the user that their entity is "disconnected" from their source entity file. 

## Possible Implementation

Detect that the associated `location` entity has been orphaned and apply a similar status to affected entities which we can use to create UI feedback that suggest that the user should unregister the location and reregister their moved entity file?
## Context

When a user renames or moves their `catalog-info.yaml` file, the associated entity becomes "disconnected" and the user is unaware their entity is no longer being updated. See [discussion](https://discord.com/channels/687207715902193673/687235481154617364/880542549016727582) with @freben for more details.

**Comment by freben** [comment]
See the comment here for some potentially related context. https://github.com/backstage/backstage/issues/6991

I poked around with this to get a feel for the end user experience. So as you note, the entity itself doesn't get marked as no longer being able to update. Instead, the parent generated Location entity is the one that gets the error marker.

<img width="1449" alt="Screenshot 2021-08-30 at 21 44 01" src="https://user-images.githubusercontent.com/3097461/131395897-a23a8f0b-b514-4cb4-99ed-869b1585da99.png">

So just looking at the underlying entity, you actually can't see that it's having issues.

I know when we were drafting this, we discussed error propagation. The idea was not to put a marker on the entity itself, but rather to let the frontend pick out and show errors "up the graph" from the entity instead of just on the entity itself. So it would show both the entity's own errors, if any, and the backing generated Location's errors. I think that would be a reasonable frontend low hanging fruit kind of fix.

Was that clear enough? Typed in a slight rush, let me know if it sounds sensible. :)

**Comment by kuangp** [comment]
That makes sense. Is that something I can do now in my custom `EntityPage`? something like fetching the parent `Location` entity and checking for a `backstage.io/orphan` annotation or the the `status` field on its entity definition and enabling warning on the UI of the child entity?

**Comment by freben** [comment]
This is actually not orphaning. It's a failure to even begin to process the Location entity, which is not the same as functioning correctly and not emitting the child entity.

Apart from that, yeah you have the right idea. You would essentially take what [`EntityProcessingErrorsPanel`](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/EntityProcessingErrorsPanel/EntityProcessingErrorsPanel.tsx?plain=1#L35) does, plus looking up the chain too.

The part of "looking up", now how to do that... Hm I wonder what the best semantics are. You probably want to take the `backstage.io/managed-by-location` annotation and look up all entities that have the exact same value for that annotation. Then show all of their errors.

**Comment by benjdlambert** [comment]
> You probably want to take the backstage.io/managed-by-location 

So I just was playing around to try and get this working, but I think it returns the wrong thing. It returns your siblings rather than reliably the thing that emitted or created you.

Speaking with @ruvip I'm thinking that we should start to add `relations` for things that are part of the emitted chain. So you can look at an entity and find the thing that emitted it, and then we might have to do a recursive lookup in the frontend which is a bit of a workaround for now until we can do some sort of nicer query language for the filters to grab all entities up the chain.

We have the internal ref table which I'm guessing is basically what we want to mirror in these relations block, but we probably make sure that this doesn't cause any problems with the stitching and to make sure it works.

**Comment by benjdlambert** [comment]
Going to build this on top of our mob work #7377
