### ISSUE TITLE
[Catalog] - delete catalog from db(postgres) when catalog is deleted from yaml file

### ISSUE THREAD

**Issue by falconbin** [backstage/backstage#6991]
A catalog is being deleted from yaml file, but in logs we find some errors that still read the non-existing yaml files. I guess this record is still in database. 

## Expected Behavior
Should not read the non-existing yaml files, delete the record from db.

## Current Behavior
error shows that backstage read the non-exiting files

## Possible Solution
delete the record from db if the file doesn't exist ?

## Steps to Reproduce
Remove an existing catalog from yaml file then start backstage again, check logs from console, you'll see some errors like below:
Unable to read url, NotFoundError: https://***/browse/external-catalog-registrations/domains/digitization-of-client-servicing-domain.yaml could not be read as https://***/external-catalog-registrations/domains/digitization-of-client-servicing-domain.yaml?at=, 404 Not Found [36mtype[39m=plugin [36mentity[39m=location:default/example-domains

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu
- Browser Information: Chrome

**Comment by freben** [comment]
Perhaps surprisingly, this is the expected behavior at this point.

As a general rule, the catalog does not silently mess with the locations and entities that were registered as a consequence of direct user action - it requires user action to unregister or move them as well. This is for safety reasons. There is a myriad of reasons that some registration might unexpectedly become corrupt: you could be performing a company reorganization, just rearranging things a little bit within the repo, inadvertently deleting the wrong thing, the security team might be changing read permissions structures, or you just introduce a fatal typo into the file such that it becomes unparseable.

If the catalog eagerly wiped out everything that it could no longer process, it might have dire consequences. Especially when you attach additional tooling onto the catalog - what if your CD system broke down and undeployed important live systems because their catalog data was no longer there, for example?

Instead, we take the safe route and hold on to the "last known good" data and inform the user that something is wrong, so that they can take corrective action in the way that only they know is the correct one. We know that the visual presentation of the error, and the ease of use for taking such corrective action, is still a bit rough around the edges. For example, we have been considering whether we could offer an easier-to-use frontend option to just "move" a registration just like yours by finding nearby files that have the expected name and letting you select them.

For you, the easiest course of action right now might be to unregister the entity and re-register the new, correct URL location. As time goes on, we'll be making this flow easier.

**Comment by freben** [comment]
I'll close the issue for now, but do get back to us here or on Discord if you have additional questions. If you have feature ideas to improve this, you can also make a feature request issue here on GitHub.
