### ISSUE TITLE
Aggregate ownership of entities

### ISSUE THREAD

**Issue by prasaria** [backstage/backstage#6995]
Parent group should aggregate ownership of entities on group page

## Feature Suggestion

I have an idea, if a group has children, the values of entities in the ownership section should recursively aggregate across all of it children and at the current group level. Clicking on the entity type box should take the user to the filtered catalog page and show all of the entities that are included in the aggregated result.

For example: team-a has two children : team-a1 and team a2. Team-a has 2 GRPC API, and each of the children has 3 GRPC API entities, so when I open team-a group page in the `Ownership` Card, the number of services should show the total number of GRPC API (which is 8), and when I click the GRPC box it should show me all those 8 GRPC API in the filtered catalog page.

Is it possible to implement ? Thank You

**Comment by freben** [comment]
Hi!

The easiest way to achieve this, would be to contribute an addition to the group page. It could work as follows:

- Add a dropdown or similar switcher, that lets users pick between "Direct ownership" and "Transitive ownership" view mode.
- If "direct" is shown, everything works as it does today
- If "transitive" is shown, the typescript code in the page actually goes to the catalog to look up what all child groups are of the current group, and show counts based on entities that have an `ownedBy` relation to ANY one of those groups.
- In the "transitive" mode, the query used when clicking to go to the catalog page will be a bit more advanced (it'll select multiple owners instead of one), but will work similarly.

This is kind of a single-purpose local-only fix that makes it work on that particular page. There will be other parts of the interface that may not have the corresponding function. But I think that that's the best we can do for now.

Does that make sense? Is that something you might want to try to contribute?

**Comment by timbonicus** [comment]
@freben Hmm, if I ask "what does team-a own" in this context (or in Spotify context -- what does Tribe X, as an entire organization, own), I would expect the things owned by descendent groups to show up. That follows the principle of least surprise to me, not getting a truncated list and rationale of "oh, Tribe X doesn't own that _specifically_ 🙄 , it's Squad Y (who is directly under Tribe X)". This would imply that the catalog stitching should resolve these transitive relationships and include them on the entity 🤔  then no change would be needed here.

**Comment by prasaria** [comment]
@timbonicus Hmm what is catalog stitching anyway ? can u explain it to me.

**Comment by freben** [comment]
@prasaria Docs are being written: https://github.com/backstage/backstage/pull/6992 :) It's an internal process when different pieces of information are assembled together to form the final entity shape.

**Comment by prasaria** [comment]
Ok, so is this feature / concept already available in backstage or does it still in development process ? I see some code about `Sticther` btw, but not sure if it is already work like @timbonicus said.

**Comment by freben** [comment]
The stitcher is in place and being used, yeah.

@timbonicus I think the `ownedBy` relation is really intended to be used for immediate ownership. I do not think we can readily assume that this kind of transitive _actual ownership_ (which might be said to cover concepts such as perceived or real responsibility, chains of command, on-call etc) is what applies everywhere. This is one reason why the ownership RFC left it up to the org to decide how they want the `ent` claim to be populated - transitively or not.

**Comment by prasaria** [comment]
Hello @freben , if I want to contribute which one should I choose here ? From my understanding here, that we are lean towards your first suggestion, am I correct ?

**Comment by freben** [comment]
I'd vote for that short term yeah.

**Comment by prasaria** [comment]
hello, I want to continue to develop this issue, please dont close it yet. Thank you
