### ISSUE TITLE
BYO docs engine for TechDocs

### ISSUE THREAD

**Issue by hirenoble** [backstage/backstage#7048]
Currently, the only way to integrate your docs into TechDocs is to using the TechDocs CLI and underlying MKDocs engine to generate and consume the documentation. 

Trying to integrate other static site with TechDocs resulted in a broken site due to blocked JS for security. Moreover, TechDocs has some hard dependencies on techdocs_metadata.json to be able to render the site.

Our team at Adobe already has a process to generate the documentation using GatsbyJS with heavy customization on MDX, open API specs, and JSON schemas, the GatsbyJS produces a static site, we would like to integrate the static output of GatsbyJS with backstage tech docs.

## Feature Suggestion
Decouple the TechDocs CLI/MKDocs dependency from TechDocs and making it open that it will connect with any other static site output such as GatsbyJS, Read the Docs, Jekyll etc. 

## Possible Implementation
Adding config options in techdocs config in app-config to configure the trusted sources to allow required JS and CSS.

## Context
To allow freedom of choosing the right tool for documentation with high cohesiveness and loose coupling to Backstage.

**Comment by iamEAP** [comment]
Thanks for opening this up for discussion!

We've landed where we are (fairly tightly coupled to `mkdocs`) because doing so allowed us to get to a robust set of features very quickly (not just generation and display, but also features related to docs authoring, maintenance, feedback, discoverability, etc).

There may be a couple of tweaks here and there that we could make to TechDocs that enables arbitrary SSG-based documentation rendering, but I'm not sure there's a practical path forward for being able to provide all of the features we provide under the TechDocs banner with an API contract like that.

I wonder if what you're trying to achieve (by taking something awesome that you've built internally and integrating it with the Software Catalog in Backstage) would be more easily accomplished as a net-new, standalone plugin?

I also just want to link some prior art for context on past/current/future proposals that you could use as inspiration:

- #4548
- #3998
- #3842

**Comment by iamEAP** [comment]
One more for inspiration:

- #2174
