### ISSUE TITLE
Support of 'kubecost' as a datasource for Cost Insight plugin

### ISSUE THREAD

**Issue by braghettos** [backstage/backstage#7087]
## Feature Suggestion

From the official webpage (kubecost.com): _Kubecost allows you to see allocated spend across all native Kubernetes concepts, so you can provide your teams with transparent, accurate cost data reconciled with your actual cloud bill._.

From the Backstage blog: _Cost Insights will show you trends at a glance and also let you compare costs quarter over quarter. More importantly, you can also evaluate costs against business metrics that you care most about. In the example below, should the upward slope shown in the first screen be cause for worry? Perhaps not — if you switch views, you’ll see that cost per daily average user (DAU) is actually going down. Exactly what you hope to see as you scale._

## Possible Implementation
It would be great to understand if the Cost Insight plugin can interact with Kubecost APIs.

**Comment by freben** [comment]
From the maintainers' side, we always welcome community input for plugins or features like this, but usually don't have the time to spend to dive into individual offerings to see how they fit or how they are to be integrated. If you are interested in exploring this one, I'm happy to assign you to the issue. Otherwise, let's see what others have to say!
