### ISSUE TITLE
Unable to make an API call from Front End 

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#7166]
When trying to make an API call from the front end i am getting the following CSP error: 

_Refused to connect because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback_

![image (6)](https://user-images.githubusercontent.com/6157895/133137400-b8d83a94-417d-4b20-b884-b8030a64905e.png)

I am using the axios client in a react hook and have the default csp settings set in my app-config.yaml more context in this discussion: https://github.com/backstage/backstage/discussions/7132 wasnt sure if anyone else came across this error, i did read 

```
   cors:
      origin: http://localhost:7000
      methods: [GET, POST, PUT, DELETE]
      credentials: true
    csp:
      connect-src: ["'self'", 'http:', 'https:']
```

I am returning the html that is in index.html which is just like the issue encountered here: https://github.com/backstage/backstage/issues/3279 

![image](https://user-images.githubusercontent.com/6157895/133171525-210febe9-e677-476c-9df1-385d15927981.png)

**Comment by freben** [comment]
The bit about `'connect-src' was not explicitly set` does sound interesting. Can you somehow double check that the right config was actually supplied? Play around with the csp values and see if you can coax it into changing the error.

**Comment by regicsolutions** [comment]
@freben The issue ended up being my app-config.yaml was incorrect. I had csp under backend.database once I moved it to backend I was able to get passed this csp error by using the default csp configuration but am now facing a CORS issue (confirmed cors is under backend in my app-config) 

`XMLHttpRequest at 'http://localhost:7000/rest/api/1.0/projects/FIR/repos/demo/commits'
from origin 'https://localhost:7000'
has been blocked by CORS policy: Response to preflight request doesn't pass access control check:
No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Same issue mentioned here: https://community.atlassian.com/t5/Bitbucket-questions/Access-Bitbucket-API-from-Client-Browser-CORS-access-support/qaq-p/1039301?lightbox-message-images-1140566=61603iE998438C4944A5B4 and here https://community.atlassian.com/t5/Bitbucket-questions/Enable-CORS-in-Bitbucket-REST-API/qaq-p/637021

Any idea if there is a workaround for this issue?

**Comment by freben** [comment]
`http://localhost:7000/rest/api/1.0` doesn't sound right at all, so the problem is that the request happens to entirely the wrong URL. I would have expected to see either roughly `http://localhost:7000/api/proxy/bitbucket/rest/api/1.0/...` if you configured it go go via the proxy, or `https://api.bitbucket.mycompany.net/rest/api/1.0/...` if talking to the remote directly.

What does your `integrations.bitbucket` block look like today?

**Comment by regicsolutions** [comment]
@freben thanks for the reply! So i haven't actually configured it to go through the proxy yet, was wondering if this is required in order for me to make API calls from the front-end to APIs that don't support CORS? 

Also wasn't 100% sure if a plugin is actually required to make use of the built in backstage proxy or not?

Was wondering instead of trying to add a new proxy entry under `proxy `in my app-config if i could i just make use if `integration.bitbucket.apiBaseUrl` ? wasn't sure if this will also make use of the backstage proxy or not...

Here's what my `integrations.bitbucket` looks like:

```
integrations:
  bitbucket:
    - host: bitbucket-server.com
      apiBaseUrl: https://bitbucket-server.com/rest/api/1.0
      username: ${BITBUCKET_USERNAME}
      token: ${BITBUCKET_TOKEN}
```

**Comment by freben** [comment]
Sure you could like `useApi(scmIntegrationsApiRef).bitbucket.byHost('bitbucket-server.com').config.apiBaseUrl` if you wanted to grab it out of the config, by URL.

You can for sure make direct calls to backends from the frontend if you like; we have some plugins that do so. However, since the client is a browser, you are subject to all of the security rules and similar that always apply to browsers. For example, the Backstage page needs to be served with a CSP rule that permits it to make requests to those hosts. Those hosts also may need to be CORS aware, such that they can respond to CORS preflight requests allowing Backstage to talk to them. To a web dev these are common challenges, and they are usually solvable. But they are complex topics and you'll have to familiarize yourself with how they work under the hood. AND on top of this, you will not be able to read the secrets part of the config from the frontend for security reasons. That is, the `token` in your config above is not available to you on the frontend.

So with all of that, the proxy is there to make the lives of frontend plugin makers easier. Especially if you host the backend and frontend on the same hostname (for example using the app-backend that's there in the default setup), all of the above things become total non-issues. You'd just make a request to `/api/proxy/<something>` and it'd be routed smoothly without the browser making a fuss, because the default rules always allow you to talk to yourself.

**Comment by Rugvip** [comment]
@regicsolutions are there any open questions left as part of this issue or is it fine to close?

**Comment by regicsolutions** [comment]
Closing for now, need to dig into it a bit more on my end. Thanks @freben for all the help on this!

**Comment by padupe** [comment]
I'm getting a very similar error:

```
Access to XMLHttpRequest at 'https://****.service-now.com/api/****/c***' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Headers:
```
Accept: application/json, text/plain, */*
Access-Control-Allow-Origins: *
Authorization: Basic ****
Referer: http://localhost:3000/
sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
```

I tried initially using proxy. However, I encountered difficulties and now I'm doing tests by making the call directly in the URL.

**Comment by ahmedkhan847** [comment]
If anyone was stuck like me to where to add the csp value here is the complete [app-config.yaml](https://github.com/backstage/backstage/blob/master/app-config.yaml) for backstage

**Comment by fosterm-mw** [comment]
Did this error get resolved? Looks like `localhost:7000` should be `localhost:7007`
