### ISSUE TITLE
Please document how to access Config in frontend on createApp

### ISSUE THREAD

**Issue by rodiongork-genestack** [backstage/backstage#7467]
Sorry if I'm just missing something obvious. In the `createApp` call in `App.tsx` I would like to check configuration for configured authentication methods, so that I can pass proper array here https://github.com/backstage/backstage/blob/master/packages/app/src/App.tsx#L98

I see `configApiRef` is in `apis` but can't seemingly access this properly. 

It would be great to have some example/clarification in relevant documentation page, I guess this one:
https://backstage.io/docs/conf/reading

thanks in advance!

**Comment by Rugvip** [comment]
The config isn't loaded yet at the point of calling `createApp`, that happens a bit later. What you can do though is to access the config inside the `SignInPage` component using `useApi`. So something like this:

```tsx
SignInPage: props => {
  const config = useApi(configApiRef);
  return (
    <SignInPage
      {...props}
      ...
    />
  );
},
```

**Comment by rodiongork-genestack** [comment]
@Rugvip thanks for such a quick reply!

Truly, at this place config seems to be accessible, but lacking `auth` part. May here be some secret about it or it is more likely my configs are misconfigured?

```js
    SignInPage: props => {
      const configApi = useApi(configApiRef);
      console.log("APIS: " + configApi.keys());
```

prints for me ` app,organization,backend,integrations,opsgenie,sentry,techdocs` while I'm sure I have `auth` in config too

**Comment by Rugvip** [comment]
@rodiongork-genestack ah, that's because the auth config is not [visible](https://backstage.io/docs/conf/defining#visibility) by default. I would actually recommend basing the chosen sign-in provider on something else than whether they're present in `auth.providers`, as there are other reasons than sign-in that you might want a given provider. Could be simplest to just define your own local config value in this case
