### ISSUE TITLE
Entity error visual indicator on catalog list page

### ISSUE THREAD

**Issue by ntgussoni** [backstage/backstage#7470]
As per https://github.com/backstage/backstage/pull/6586 we now have errors being displayed on the entity page.
That's nice, but you have to go to the entity to realize it.

## Feature Suggestion

I'd be great if we could have a small visual indicator in the catalog list as well, so that you can see at first glance that something is wrong.

![unknown (1)](https://user-images.githubusercontent.com/10161067/136193337-943390ef-4a82-4de0-b217-a0dcbc979fda.png)

I wonder if there's anything planned or some UI designs,  and I can make a PR to add it.

What do you think?

**Comment by ntgussoni** [comment]
> No plans right now.
> 
> We've thought about this a bit. From the backend's perspective, right now it's not a very cheap operation to fetch errors recursively upward. We could introduce a recursive SQL query on read-time, if the incentives were right (it'd make all reads a bit more costly but it's not a huge deal in the grand scheme of things). Could be worth looking into.
> 
> We could also make these frontend markers a frontend-only thing, such that they'd reach out to the backend ancestry endpoint for each dot component. This is a pattern that we've found to typically be slow and not a great experience - you risk saturating the browser's outgoing request limits, use up resources, cause tons of repaints / reflows, etc.

Hey, thanks for your reply.
If I go to the catalog, the errors are present in the payload for each item on the list,  perhaps we are talking about two different things?
![image](https://user-images.githubusercontent.com/10161067/136518172-c072d205-65ed-404d-b883-cf7a5ce7aef3.png)

My idea is just to display this marker if there are errors present in the payload, maybe a separate filter as well, not more than that.

**Comment by freben** [comment]
Right - those are the errors that are attached _directly_ to that entity. If the entity is being ingested successfully but then has some local validation errors on it or so, then that might be where an error ends up. But what is shown at the top of the entity page, is actually a recursive lookup upwards along the graph that ultimately led to that entity. For example if you register a `kind: Location` entity that then tries to refer to a broken YAML file, then the error of reading that file won't land on that entity but rather on that parent location instead. And that's actually a rather common case, due to how the engine works internally.

Since the entity view shows this more collected view of the "error reality", my previous comment tried to convey that it's probably desirable that the list shows the same state as the entity view. Especially since a fairly large number of error states will be missed if we don't do the expensive, thorough thing.

**Comment by ntgussoni** [comment]
> Quick update on this is that we're moving our focus away from the catalog the coming months, so it is likely that this'll have to wait for a while. If someone does want to take on the challenge it is up for grabs :grin: although it's likely one where it's best to settle a design together first

That's understandable. I think we'll implement something as an internal plugin, and if it's interesting enough we can share it with you guys.

You can close this if you want. Cheers
