### ISSUE TITLE
[RFC] UI for Scorecard component -> Tech Insights stage 2

### ISSUE THREAD

**Issue by Irma12** [backstage/backstage#7576]
**Status:** Open for comments

## Proposal

This RFC contains proposed solution for continuation of [PRFC Tech Insights](https://github.com/backstage/backstage/pull/7193), specifically going into stage 2.
The purpose of this PR is to propose overall UI ‘scorecard’ components generated as a result of stage 1 in a linked Tech Insights PRFC.

Initially we want to focus on entity level, but in the future there might be a possibility to approach this in a more general level, so we would create an aggregation of multiple scorecards and group them per owning group or multiple entities.

Idea we have is to display ‘scorecards’ widget in entity Overview page where it would be easy to see number of checks passed for each scorecard.

<img width="308" alt="Screenshot 2021-10-12 at 15 03 37" src="https://user-images.githubusercontent.com/7230518/137092481-8006d8df-4445-40a3-ad11-8489b8ed16f5.png">

 Just for a general idea purpose, we showed case where there would be multiple scorecards (Production ready and Development ready). Each of the scorecards would contain more details which would be seen when scorecards page is opened

<img width="279" alt="Screenshot 2021-10-13 at 08 49 24" src="https://user-images.githubusercontent.com/7230518/137092498-061ac148-de58-4664-a9ac-6ec4b724f9c4.png">.

 In this overview it is possible to expand checks in order to get information about them and also proposed actions that could be taken in order to pass them. If specific check is calculated based on gauge or graph fact calculations, those would also be displayed in this section. Please keep in mind the checks stated in the wireframe are just example of what could be seen, but it can be anything, such as:

- Service has been deployed at least once in the past 30 days.
- Service has an owner defined.
- Test coverage is greater than 50%
- React package version is greater than 17.0.0
- Service has no critical security vulnerabilities in Snyk

Actions could include various things such as a link to an entity-info file, link to the test coverage calculation, link to vulnerabilities list, link to a package.json file etc. 
For initial version we would hold all  checks equally important so we wouldn’t make a difference in a ‘weight’ of a specific check. However, changes in their importance or value may be introduced afterwards.

**Comment by dtuite** [comment]
@andrewthauer In my mind that's an enhancement which could be built on top of the checks. For example, give the grade E if 2 out of 10 checks are satisfied, and give the grade A if all 10 checks are satisfied. The checks themselves are still boolean values though. Does that cover your need?

**Comment by Xantier** [comment]
> As discussed in #7193, I still think having a single binary check state (pass/fail) is too limiting.

That's a valid point and I agree with you on this. Having scorecards that handle different kinds of checks is valuable and should be considered as well. 

That being said, I'm kinda failing to understand the limitations of these specific mockups when it comes to designing scorecards. Maybe it's because I have too much implicit information about the actual implementation of this first iteration of these components.

If we think about scorecards in general they are variations of the same pattern. They have an identifier, the actual value and how it relates to a 'grading system' (pass/fail, A-F, 4-10, 1-5, w/e) and some extra information. In this case the mocks show 'check name' as the identifier, a type of boolean check - a checkmark - value as, and additional information which may or may not be visible depending on the position of the clickable caret. The debated area is the 'checkmark' component here.

> I do worry that using "checks" as the initial use case might make the grading/scoring systems more difficult to add in afterwards versus up front 

I'm not sure this will end up being a problem. Without going too much into implementation details, we do get the type of the check as part of the result and can swap the rendering path based on that to display different grading systems. The overall design would still work with different grading types, even if they are not explicitly drawn into visuals in these mocks. 

The only problem I'm seeing are cases where for some reason different systems would be used in the same scorecard. Aggregating the scorecard results from those would be impossible without complex comparison table logic. I do believe that is something that we should restrict from being to be done. It is better to create multiple scorecards for those cases.

**Comment by Irma12** [comment]
In addition to what @Xantier elaborated in his comment, and in order to visualize it better, I modified mockups a bit. In a term of 'status' component, I understand checkmark/x sign might be looking a bit too strict, but that would be used only for boolean type of checks. We can display something else (grade, percentage..) all depending on the type.

<img width="697" alt="Screenshot 2021-10-21 at 12 02 00" src="https://user-images.githubusercontent.com/7230518/138267288-4582b63f-1a8d-4bde-b681-e22a8c790a02.png">

<img width="593" alt="Screenshot 2021-10-21 at 12 01 43" src="https://user-images.githubusercontent.com/7230518/138267283-5d73dd13-7a50-4b5d-a753-0f245cb72456.png">

**Comment by seshank-db** [comment]
@Irma12 any update on stage 2?

**Comment by Irma12** [comment]
hey @seshank-db, this is released in[ tech insights plugin ](https://github.com/backstage/backstage/tree/master/plugins/tech-insights) :)

**Comment by seshank-db** [comment]
@Irma12 tech insights README plugin still shows a simple boolean scorecard. Is this view already present? 
![image](https://user-images.githubusercontent.com/64047023/159356334-4522e395-34bd-49df-9233-697c0cead762.png)

**Comment by Irma12** [comment]
@freben Yup, it has been worked on in https://github.com/backstage/backstage/pull/8086. The main idea for this RFC was to get initial thoughts and direction in which we would like to proceed FE wise :) I think we managed to gather the thoughts in tech-insights plugin so I think for other suggestions and continuation we could probably open new RFC.

@seshank-db Yes, currently there is only Boolean scorecard view present, which will show values for the @backstage/tech-insights-backend plugin. Since currently[ tech-insights-backend-module-jsonfc](https://github.com/backstage/backstage/tree/master/plugins/tech-insights-backend-module-jsonfc) (which is an addition to tech-insights-backend) provides functionality to run checks against a [json-rules-engine](https://github.com/CacheControl/json-rules-engine) and return boolean values, we went ahead and created a Boolean Scorecard in order to present this. 

However, if you wish to customize or create new type of scorecard and maybe use other values than boolean, you will firstly need to create a  similar structure to tech-insights-backend-module-jsonfc in order to fetch facts and mangle them into a preferred format, and then create customized scorecard you wish to display instead of Boolean. In [this file](https://github.com/backstage/backstage/blob/master/plugins/tech-insights/src/components/CheckResultRenderer.tsx) you can see that defaultCheckResultRenderers will display BooleanCheck (boolean scorecard) for 'json-rules-engine' type. In similar way you could proceed with some new/customized scorecards. I hope this makes sense :)
