### ISSUE TITLE
[Analytics Event]: Analytics Events for Search

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#7600]
*What search terms are used by the users?*

*Which search box is primarily used by the users?*

Backstage Search provides multiple places to submit search queries: sidebar, search page and the search bar on the homepage. We would like to know which of them is used primarily. In addition we would like to know more about the search terms that our users are using to see if the data that are looking for is both available at all and discoverable through search.

## Feature Suggestion

Capture a search event that includes the search term every time the search is used. How to capture the event for the type ahead search used on the search page, should we include all queries that happen while typing?

## Context

It might also be interesting to see which results are clicked based on a search term, in that case we could provide the current search term in the analytics context around the search results view. That way it can be included in the click events on the search items.

**Comment by iamEAP** [comment]
For simplicity, we may want to set the search bar on the main search page to not use type-ahead, then there is a _very_ clear event we can hook into to know what the term is (click a search icon or press "enter").    Otherwise, we have to do some acrobatics to know what a "search" is (e.g. don't actually trigger an event on the search, but trigger one on blur or a less ideal solution: debounce).

It would also be great to pass the index of the result clicked on (e.g. 1st result, 5th result, 100th result) as the `value`.  ...This may require some more work to do thoughtfully, though.

**Comment by Fox32** [comment]
The index/rank is a bit hard to implement as the consumer code (in every backstage app) is looping through the array:

```tsx
            <SearchResult>
              {({ results }) => (
                <List>
                  {results.map(({ type, document }, i) => {
                    switch (type) {
                      case 'api-docs':
                        return (
                          <ApiDocsResultListItem key={i} result={document} />
                        );
                      case 'releases':
                        return (
                          <ReleasesResultListItem key={i} result={document} />
                        );
…
```

If it was less flexible, we could do stuff like that internally, e.g.:

```tsx
<SearchResult resultComponents={{
  'api-docs': ApiDocsResultListItem,
  'releases': ReleasesResultListItem,
}} />
```

In that case we could just set the analytics context around the result item, right?
