### ISSUE TITLE
Support Google Analytics 4 as a analytics integration

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#7671]
Right now only older versions of Google Analytics are supported by the [`@backstage/plugin-analytics-module-ga`](https://github.com/backstage/backstage/tree/master/plugins/analytics-module-ga).

>  All that's needed is your Universal Analytics tracking ID

Universal tracking IDs are only available for older versions, passing a modern tracking ID leads to errors.
Google Analytics 4 seems to be the new default (but there is still a hidden way to create an old property).

Universal Analytics hits will no longer be processed as of July 1, 2023 for standard properties and July 1, 2024 for 360/Premium properties.

## Feature Suggestion

Support Google Analytics 4.

**Comment by benjdlambert** [comment]
@iamEAP for visibility

**Comment by benjdlambert** [comment]
Looks like the latest comment is basically saying it needs to be community contributed as it won't be built by the core maintainers. https://github.com/react-ga/react-ga/issues/460#issuecomment-820369771 Is this something we want to pick up?

**Comment by iamEAP** [comment]
I would personally defer implementation to someone more familiar with the differences between GA4 and older versions of GA. 😬 

That being said, there appears to be a fork?  https://github.com/PriceRunner/react-ga4

**Comment by Crevil** [comment]
I just looked breifly into this. From the most part the fork supports the same API but the testMode is different.

`react-ga` has a possiblity to inspect the calls and `react-ga4` doesn't. We use this in the tests of the analytics package so a clean switch is not that esay.

There also isn't another way to get a hold of the calls in `react-ga4` it seems.

As this in practice would be a breaking change to the `analytics-module-ga` if we switch them up, maybe we should create a new `anlautics-module-ga4` package with the same external API but with support for GA4? WDYT?

**Comment by iamEAP** [comment]
Thanks for looking into the diff b/w the existing plugin and the fork, @Crevil!  The lack of observability in the tests is unfortunate.

Reading through [Google's comparison guide](https://support.google.com/analytics/answer/9964640?hl=en#zippy=%2Cin-this-article), I'm wondering if it's actually worth writing an entirely different integration with its own config schema, and perhaps backed by an entirely different library, if a nice one is available.  Perhaps we could keep it in the same plugin/module, but instantiated given some identifier in config.

Some initial notes after reading through:

- Possibly different (maybe simpler) custom handling for the core `navigate` event (because everything in GA4 is an event, page views just happen to be named `page_view`.  Maybe needs consideration for capturing `page_title` and other default metadata that `react-ga` theoretically handles for us.
- Since events no longer have a concept of action/category/label, we can probably simplify by removing the opinionated translation layer we have and just pass context/attributes directly as GA4 parameters.  This would probably let us completely remove the custom dimension mapping we have now, and we could instead have a simpler "which attributes do you want to collect" kind of configuration (since [there is a limit of 50](https://support.google.com/analytics/answer/10075209#limits) of each).
- The [concept of a `content_group`](https://support.google.com/analytics/answer/9964640?hl=en&zippy=%2Cin-this-article#content-grouping&zippy=%2Cin-this-article) is interesting and makes me wonder what we should map there. Plugin name?  Extension name?  Allow it to be configured by the user?

**Comment by Rugvip** [comment]
Just wanna add in that I think that adding `analytics-module-ga4` or something like that would be a solid option if they end up being different enough.

**Comment by awanlin** [comment]
Still something that will be needed eventually

**Comment by awanlin** [comment]
Un-stale 🪄

**Comment by danopia** [comment]
Un-stale

The UA data collection freeze is now scheduled less than 6 months away

**Comment by iamEAP** [comment]
Just for full transparency: although we use the GA integration internally, we are GA360 customers, which means we have an extra 12 months before we're forced to transition...  I'm happy to offer advice/help/reviews for anyone who wants to contribute support, but we unfortunately won't be able to prioritize this ourselves.

**Comment by nthings** [comment]
https://github.com/backstage/backstage/pull/16432 Google Analytics 4 Plugin
