### ISSUE TITLE
Expose a Type filter to the `CatalogGraphPage`

### ISSUE THREAD

**Issue by kuangp** [backstage/backstage#7764]
## Feature Suggestion
Adding a `spec.type` filter to make it easier for users to adjust the diagram to filter out some types.

## Possible Implementation

Similar to the `kind` filter, we can source all possible `type` values from the catalog and use these as values to filter entities by. Since `type` is not applicable to all entities, a `no-type` option may be used to match those. 
## Context

As an example, a system may contain dozens of `library` type `components`. It makes it a lot easier to visualize the relations between services and website components if we're able to hide the libraries.

**Comment by freben** [comment]
I've in general for a long time been wondering if it would make sense with a _single_ filter that is a kind + type filter. Essentially you select a kind first and then based on actual server contents, you get to pick any number of types or an "all types" option. I think that might make sense since they are so intrinsically tied to each other.

**Comment by kuangp** [comment]
still interested
