### ISSUE TITLE
[RFC] Listing Error messages while uploading bulk software catalog

### ISSUE THREAD

**Issue by 88pankaj88** [backstage/backstage#7799]
**Status:** Open for comments

### Proposal

The RFC contains problem description of uploading multiple software catalog and proposed solution for same.

### **Problem**
While we upload location.yaml which have multiple spec targets with one or more defective ones, backstage calls /locations API. The API process each target in serial and stops execution when first corrupted yaml is encountered and throws the error. PFB the relevant Screenshots.

<img width="1427" alt="UI upload" src="https://user-images.githubusercontent.com/85473085/139059789-af3cd393-330f-4c00-aa76-4f269e44f7f6.png">

The backend API below is stopping execution while throwing an error.

<img width="1440" alt="Screenshot 2021-10-27 at 10 19 40 PM" src="https://user-images.githubusercontent.com/85473085/139110751-e5f25cfc-4b3a-44b4-857d-3280157fdd0e.png">

This is a tricky behaviour as its ignoring errors in other yamls silently and displaying no status on UI for success & failed imports.

### Solution:

Backend API should continue execution and store error in memory rather than throwing it.
Response from API should contain arrays for success & failure imports.
**It shall need changes in DefaultLocationService.ts in core backstage project**

On UI, there should be a moda/pop-up to show list of success & failer imports along with respective error messages.

<img width="1159" alt="suggested_solution_ss_2" src="https://user-images.githubusercontent.com/85473085/139373185-e56b6dd0-6351-4256-ba10-f0181ece2880.png">

**Comment by Rugvip** [comment]
When registering a new file it's actually intended that it needs to be in a good state, including all of the locations that it in turn may link out to. Do you have a use-case for being able to register locations that already have errors? As in multiple locations being referenced and then ones that aren't broken go through and get registered?

I think returning a list of errors makes a lot of sense though, just to speed up the troubleshooting process if you're hunting down errors in the definition files

**Comment by NishkarshRaj** [comment]
@Rugvip thanks for the follow-up. Taking over from my teammate Pankaj on this.

> Do you have a use case for being able to register locations?

Our adopters are promoted to use a global catalog import strategy with `kind: Locations` referencing all the other `kind` catalog descriptor files for the sake of centralization.

We don't expect them to add all catalogs one by one but since we are doing a global import, we would like to get a list of files + errors (if any) which they might have accidentally created whilst writing the YAML file.

We would like to do the dev effort for this change as well, it would be great if you assign this to us.

Thanks,

**Comment by dublx** [comment]
Related topic to the global import via UI, 
what about when adding via `kind: Location`?

Does Backstage offer any kind of CLI YAML/schema validation that could be run at CI level?
Logic:
- User submits a Pull Request (Gitlab MR our case) adding component descriptor file(s) and referencing them in a `kind: Location` descriptor file
- CI pre-validates YAML using the same Backstage validation the server performs at runtime (this would be the feature Im asking about)
- Depending on CLI return code, the MR is accepted or aborts the merge otherwise and user can troubleshoot via pipeline logs

**Comment by Rugvip** [comment]
@dublx Nothing at the moment but it's something we've planned for and will hopefully be a future improvement to the catalog. Essentially we want to be able to show what impact a particular PR/MR would have on the catalog, probably through a diff. Then ofc validate the addition too, all using the flow you described

**Comment by dublx** [comment]
For our team the VCS is Gitlab so we first need to have the MR publish action available, seems its in-flight already according to https://github.com/backstage/backstage/issues/7828
