### ISSUE TITLE
Group showing multiple parents in the UI

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#7872]
According to the documentation, a group is allowed to have only one parent. In some scenarios, on the UI this is not the case and multiple parents are shown

## Expected Behavior

The group entity page should show a single parent that was specified for that entity

## Current Behavior

The group entity details page shows multiple parents

## Steps to Reproduce

1. Create a group kind with a parent set
2. After a while, modify the created group by setting a different parent
3. Open the group details after the next refresh cycle
4. The details page will show two different groups as a parent

The parent on the group is set correctly, and the children array of the parent group does not contain the related group, therefore I expect the link between the groups does not exist

Is this intended?

## Context

The entities are created with no issues, the problem is that after modifying the group parent, it is not updated correctly in the next refresh cycle

**Comment by Rugvip** [comment]
Yep it's intended for groups to be able to have multiple parents through relations. The only limitation is that when defining a group through the well-known schema you're only allowed to specify one parent. It's for example also possible to create a catalog processor or alternate format that allows for multiple parents.

Why you would want that is a different discussion, but it would be a bit of an unnecessary limitation. Especially since you might end up with it as some transient state that will clean itself up over time.

Now when it comes to the issue you're describing, do the duplicate parents clear up over time or do they stick around? I could imagine there being a caching issue that causes the relation not to be cleared up otherwise

**Comment by ProticM** [comment]
Yes, I see.

We do not need multiple parents therefore current model will suffice at the moment. And the current model with the well-known relations does not support multiple parents thus I opened this discussion.

The duplicate parents are not cleared up even after a couple of refresh cycles, they stick around.

And to add, the parents were cleared/updated when I re-registered the location.

**Comment by tyrken** [comment]
@benjdlambert if talking about "Relations not being deleted properly" please see my new issue https://github.com/backstage/backstage/issues/13774 for similar about `hasMember` between Group & User.  Where would the "discussion" take place?

**Comment by freben** [comment]
If anybody is seeing this: We meant to talk about it among the maintainers. And the great and detailed issue linked above should now be addressed!

However, we need to validate if the update path mentioned in this ticket also needs a similar fix.
