### ISSUE TITLE
Kubernetes plugin: Allow for easy customization of the Kubernetes plugin frontend

### ISSUE THREAD

**Issue by su-gupta** [backstage/backstage#7902]
It would be helpful if users could customize the frontend of kubernetes backend plugin to make them better fit their individual use cases without having to copy the entire project.

## Feature Suggestion

Similar to the experience in the Catalog (https://backstage.io/docs/features/software-catalog/catalog-customization), allow for users to route their Kubernetes tabs to custom frontend.

## Possible Implementation

Not too familiar with React/TS, but potentially expose a router somewhere that can point to the generic KubernetesContent.tsx or a custom one created by the user. Happy to help potentially contribute this if anyone has more insight on how to actually do this properly.

## Context

For our use case, we wanted to add a column to our Pods table (shown below) that would link out to logs associated with that specific pod but this would allow for customization to fit any specific use case to a user.
![k8s_plugin_example](https://user-images.githubusercontent.com/85505764/140767449-8493d8c2-b97f-4251-9b5b-5a2cb0bfc3fe.png)

**Comment by jrusso1020** [comment]
@su-gupta A few ideas on how we could potentially extend the table

1) pass in additional columns as a prop similar to what the CatalogPage allows you to do https://github.com/backstage/backstage/blob/master/plugins/catalog-react/src/components/EntityTable/EntityTable.tsx#L45

2) export all the necessary react components from the kubernetes plugin needed to recreate the K8s page in our FE application (the catalog does this, and the scaffolder recently as well)

3) something fancier like what the scaffolder does for extensions https://github.com/backstage/backstage/blob/master/packages/app/src/App.tsx#L179

I'd probably lean towards 1 if we don't for see additional customizations to this page in the near term, or 2 if we want a bit more freedom on how we can customize everything. Although 2 may be a bit more involved since there are a lot of custom components and functions not currently exported

**Comment by mclarke47** [comment]
This is a great idea, we do something similar with the closed source version to expose log links and I think it would be great to add it here also!

It could be good to do this similarly to how the dashboard linking has been done? https://github.com/backstage/backstage/tree/0492cff96410b483751b07e680897d13bfdc2154/plugins/kubernetes/src/utils/clusterLinks

**Comment by su-gupta** [comment]
Starting on this now, planning on tackling it in the following way (let me know if we shouldn't be doing it this way for any reason!):

1) Similar to how it's done in CatalogTable (https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/columns.tsx), change the hard coded columns in PodsTable (https://github.com/backstage/backstage/blob/master/plugins/kubernetes/src/components/Pods/PodsTable.tsx#L27) to be exported functions in a columns.tsx file

2) Allow users to pass through custom column functions into EntityKubernetesContent via a PodTableColumns prop. Pass that prop down from Router -> KubernetesContent -> Cluster -> DeploymentsAccordion -> PodTable

3) In pod table, check if the PodTableColumns prop is not empty, if so use it, otherwise use the default columns from before

**Comment by su-gupta** [comment]
PR here: https://github.com/backstage/backstage/pull/8308

**Comment by kim5566** [comment]
hi, @github-actions bot, I believe this issue should still be opened as PR not merged yet.

We also look for ability to custom K8s frontend table,  this would be very helpful.
