### ISSUE TITLE
[Catalog] Ability to link external documents to entities

### ISSUE THREAD

**Issue by jrusso1020** [backstage/backstage#7941]
## Feature Suggestion
Currently the AboutCard component has a "View Techdocs" button/link
![Screen Shot 2021-11-10 at 12 19 57 PM](https://user-images.githubusercontent.com/7664106/141161753-2c298fe5-25b6-45e9-84de-07392af04a11.png)

However, not every organization adopts techdocs straightaway. A lot of organizations have existing knowledge bases that they are stilling using (such as Confluence, Google Docs, Notion) and it would be nice to allow organizations to bring there own knowledge bases but still be able to surface the documents natively on the Page outside of adding additional "links" like techdocs does currently.

## Possible Implementation
Possible implementation, make a secondary annotation or a more generic named annotation to link any sorts of docs to an entity. Then use this annotations value to link out to the correct document

Also might be nice to make the button/link more generic "View Documentation"

Sparked from this Discord https://discord.com/channels/687207715902193673/714754240933003266/907677553358172160

## Context
Allow organizations to bring there own knowledge bases and surface them on Backstage. For example we currently use confluence and it's a large undertaking to adopt techdocs, however in the interim we could still natively link to entity documentation on the page. This is doable with "Links" but would be better to make certain documentation links front and center like the techdoc links are

**Comment by kuangp** [comment]
We were able to do this by "hijacking" the `backstage.io/techdocs-ref` annotation to support a `external:<url>` prefix so that we can recognize this in the frontend to link out to external doc sites so people can register existing docs from platforms like confluence, we thought this is a good compromise to have everything at least accounted for from Backstage without having owners rewrite their docs. However we hope that increasing native TechDocs feature support (eg. indexed search) will incentivize users to eventually migrate over to Techdocs.

Here's how we did it locally by abusing the current `backstage.io/techdocs-ref` annotation. These are also areas that will probably need to be refactored to support this officially:

- [`AboutCard`](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/AboutCard/AboutCard.tsx#L115): The "View TechDocs" button will need to recognize the annotation and know when to link externally and probably be renamed to more generic "View Docs"
- [`EntityTechdocsContent`](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/Router.tsx#L48): This tab will need to be hidden in your `EntityPage` if the entity has external docs
- [`DocsCardGrid`](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/home/components/DocsCardGrid.tsx#L59): "Read Docs" links need to recognize and link out to external docs
- `DocsTable`: [name column](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/home/components/columns.tsx#L34) & [copy docs url action](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/home/components/actions.tsx#L31) need to use external links when applicable
- [`TechDocsCustomHome`](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/home/components/TechDocsCustomHome.tsx#L132) and `DefaultTechDocsHome` via [`TechDocsPicker`](https://github.com/backstage/backstage/blob/master/plugins/techdocs/src/home/components/TechDocsPicker.tsx#L28) requests entities with the `backstage.io/techdocs-ref` annotation which is why we hijacked the existing annotation to ensure all documented entities are displayed, external or not.
- Lastly, unfortunately the [`DefaultTechDocsCollator`](https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/search/DefaultTechDocsCollator.ts#L104) fails for each entity that uses `external:` doc urls which results in a bunch of log statements we currently ignore

So most of the above is already customizable on your local Backstage instance out of the box. The only thing that you currently can't override the default of is the `AboutCard` which we chose to fork and customize internally. 

I do think having an alternative annotation makes sense if we were to support this natively in Backstage core since that will be a cleaner semantic from the current `techdocs-ref` annotation intention.

Happy to contribute here if Backstage maintainers are open to native support.

**Comment by iamEAP** [comment]
I remember touching the `<AboutCard />` code recently and thinking, "there's probably some inversion of control that should be introduced here," because it _is_ a bit presumptuous to slap `View TechDocs` (or even `View API`) in there and disabled.

@Rugvip I feel like you mentioned this recently in some forum?

**Comment by emmaindal** [comment]
> docs to an entity. Then use this annotations value to link out to the correct document

@jrusso1020 sometimes there is a need to link many docs sites and not just one TechDocs sites, do you think it would be valuable to have one "primary" docs link (to TechDocs or other) and then to be able to have a list of "other docs"?

**Comment by freben** [comment]
Am I understanding it correctly that [Links](https://backstage.io/docs/features/software-catalog/descriptor-format#links-optional) in essence are featureful enough, and that the primary concern is that you would preferably like to be able to surface one link front and center on the About card, or worst case at least remove the About card link where it doesn't apply?

As you may have seen, the About card hasn't received the composability treatment, and the vertical link component etc aren't cleanly exported so the amount of work to reconstruct the card is unfortunately large. One approach here could be to make the About card composable and make it possible to for example specify a [custom set of links](https://github.com/backstage/backstage/blob/54fe58b85bea9c7bf60e7f3b95292dbf7034c71e/plugins/catalog/src/components/AboutCard/AboutCard.tsx#L163). Then you would just place a custom docs link there that consumed the contextual entity and chose to render whatever it wanted.

Doing that would be some work, but it would be beneficial to everybody and we'd be glad to help out to get you started.

Another approach would be to try to embed some more behavior within the existing, closed, About card. The existing doc link could for example look at more entity data than just the techdocs ref (maybe some other newly invented annotation?) and render itself accordingly to what it finds. This would be less work but more hardcoded in a sense.

Total side note: In an earlier proposal, `metadata.links` entries could have an additional `rel` that defined the purpose/semantics of that particular link. That could have been useful here, to mark one link as `rel: primary-docs` or something so that the card could highlight that one. But it was found to be a bit too complex and lacking a proper use case to drive it.

**Comment by jrusso1020** [comment]
@emmaindal yeah that does sound useful, I agree with @kuangp and having a primary user facing doc front and center but other docs linked as well

**Comment by jcarres-mdsol** [comment]
In our use-case, we have many services (200+) and we are focusing on creating a tight service catalog experience for now. There's a lot to clean up in here so will take a while. Techdocs will not come this year for sure. 
So we have removed it but "View Techdocs" is hardcoded in the AboutCard, so that's the only thing that stays and sounds wrong that it can not be removed as everything else. 

Adding this here because in our particular use-case, we are using confluence as well so the solution proposed above would work for us. Also the idea of inversion of control, probably will work for us, etc.
The ability to remove the link would be less work but this thread seems to be more about better more generic solutions.
