### ISSUE TITLE
search: result items links 404 when mounting the app on a sub-path

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#8002]
## Expected Behavior

Search item results link to the correct path

## Current Behavior

The result item links do not take the app base path into account

<img width="250" alt="lelink" src="https://user-images.githubusercontent.com/4984472/141347045-54d331de-accc-41db-9f37-81810fd287b9.png">

## Possible Solution

Use relative routes or use RouteRefs, probably the former in this case.

## Steps to Reproduce

1. Set `app.baseUrl: http://localhost:3000/example`
1. Search for any item in the catalog and click the result link

## Context

Came across this while investigating #7147

## Your Environment

OS:   Darwin 20.6.0 - darwin/x64
node: v14.17.3
yarn: 1.22.1
cli:  0.8.2 (local)

**Comment by cmpadden** [comment]
Hi @Rugvip , it looks like there are two locations where this fix will need to be applied: the search modal, and the full results page.

```
packages/app/src/components/search/SearchPage.tsx
plugins/search/src/components/SearchModal/SearchModal.tsx
```

I confirmed that using a relative route for `document.location` works for the search modal. I tested this with two approaches;  by updating the location in the `results.map` method of `SearchPage.tsx` and `SearchModal.tsx`, and by directly updating the `<Link>` component in `DefaultResultListItem`, `CatalogResultListItem`, and `DocsResultListItem`. 

Using a relative link **does not** appear to work for `SearchPage.tsx` as the URL becomes _http://localhost:3000/example/search/catalog/default/component/artist-lookup_.

Do you think I should pursue RouteRefs, or possibly update the underlying API response to return the _document.location_ to include _app.basePath_, or something else entirely? Thanks.

**Comment by iamEAP** [comment]
I'm a little hesitant to go down the RouteRef path because things are pretty concentrated in the backend for now (also, not everything that is in the search index necessarily has a corresponding mounted route in Backstage).

Seems like two possible approaches:
- **Documentation-only fix**: Indicate that, if you use a custom `app.baseUrl` in the front-end, you have to instantiate your collators with a modified `locationTemplate` that takes this into account, e.g. here: https://github.com/backstage/backstage/blob/4167f6e/plugins/catalog-backend/src/search/DefaultCatalogCollator.ts#L66
- **Backend code fix**: In each of the default collators, read `app.baseUrl` in from config and adjust the template accordingly.  ...This could be confusing for a variety of reasons: **1)** you would have to explicitly set this, even if you are not running Backstage as a monorepo and the process that handles Search is separate from the App frontend) and **2)** the interaction between the `app.baseUrl` config and the `locationTemplate` would be unintuitive.

**Comment by Rugvip** [comment]
@iamEAP What I was thinking is that perhaps it'd be fine to essentially just throw in `` `${configApi.getString('app.baseUrl')}/${result.location}` `` here? https://github.com/backstage/backstage/blob/63f3b46b8667962f174e951a77a9f9dfe44862de/plugins/search/src/components/DefaultResultListItem/DefaultResultListItem.tsx#L28

The tricky bit with adding `app.baseUrl` to the data in the backend is that you might use different paths in different environments, so your search data would end up not being compatible with all different environments, which is a bummer.

On the topic of ^ though, I could potentially make sense to have the plugin API or smth export an app `appRootRouteRef`? That way it'd be something more like this

```tsx
export const DefaultResultListItem = ({ result }: Props) => {
  const appRoot = useRouteRef(appRootRouteRef);
  return (
    <Link to={`${appRoot()}/${result.location}`}>
       ...
    </Link>
  );
};
```

**Comment by danludwig-happymoney** [comment]
> The tricky bit with adding app.baseUrl to the data in the backend is that you might use different paths in different environments, so your search data would end up not being compatible with all different environments

@Rugvip wouldn't the solution here be to just use an environment-specific app-config.yaml to override the baseUrl for that given environment? We're running into tons of issues trying to host at a path while waiting for a vanity URL to be created. We want to try to host at a path in the meantime, but it sounds like there are still open issues and we won't be able to get 100% there, and we have to wait for a vanity URL in order to get hosted at root?

**Comment by Rugvip** [comment]
@danludwig-happymoney it's kind of the solution I'm suggesting but it doesn't work that way for search results atm

**Comment by iamEAP** [comment]
I like the `appRootRouteRef` approach; just need to be careful to only apply it in cases where the `result.location` is relative.
