### ISSUE TITLE
File modes getting lost

### ISSUE THREAD

**Issue by rpenugonda** [backstage/backstage#8286]
looks like https://github.com/backstage/backstage/issues/7144 is never resoled. assumers and i work in the same team

**Comment by rpenugonda** [comment]
[](url
![Screen Shot 2021-11-30 at 12 10 54 PM](https://user-images.githubusercontent.com/9339957/144103901-85a150fc-3fc5-43f6-8761-50214170aa38.png)
)

**Comment by jhaals** [comment]
Hi @rpenugonda I'm closing this issue since this is a duplicate of #7144.
It would be great if you could reopen the old issue and provide additional context such as the version of the plugin you're using and any other information that might aid the troubleshooting.
`yarn backstage-cli info` will give you a list of your app dependencies.
