### ISSUE TITLE
Warn about deprecated configuration usage

### ISSUE THREAD

**Issue by timbonicus** [backstage/backstage#8311]
Configuration for plugins registered in `app-config.yaml` can become deprecated over time, such as in #8309. The backend startup should warn about any config key that's present and marked as `@deprecated` in the schema. Perhaps with a generic message like:

```
The configuration key 'scaffolder.github' is deprecated and may be removed soon.
```

Or the actual deprecation string that follows `@deprecated`, preferably.

## Possible Implementation

Modify `config-loader` to warn about deprecated keys when parsing the combined configurations.

**Comment by freben** [comment]
The config returned by the loader already contains a list of keys that were masked out by visibility limits. Might it make sense to similarly also return a list of keys (along with their description texts where applicable) that existed but were marked as deprecated in the schema? Instead of doing the warn logging in the read step, to be seen only in the backend logs, the consumer can choose to warn as they see fit instead - perhaps when accessing a deprecated key, or what they deem convenient.
