### ISSUE TITLE
Upgrade docusaurus on the microsite

### ISSUE THREAD

**Issue by freben** [backstage/backstage#8329]
## Feature Suggestion

The `/microsite` directory uses a dependency on an alpha version of `docusaurus`. This version is getting a bit old and has some vulnerable dependencies that we want to get rid of. The docusaurus releases are now at a beta level, are shipped under a `@docusaurus/*` scope, and the generated project structure is different than it used to be in the alpha.

## Possible Implementation

The migration from the alpha project structure to the beta project structure seems to be slightly involved. For example, the way that sidebars are loaded has changed. It may be worth scaffolding an entirely empty fresh docusaurus site, and retro-fitting our content into that.

**Comment by adamdmharvey** [comment]
I actually played around with this the other day. There are some nice steps documented here:

https://docusaurus.io/docs/migration

Although it's called v1 to v2 migration, and we're on a v2 alpha, most of them are simimiar as it seems many of the major structural changes came after the alpha version Backstage.io is on.

Where I ran into the biggest aspect of change is in styling; much of the Docusaurus customizations need to be pulled out into a CSS and referenced externally. Otherwise the other mechanics (changing the package structure, renaming the config file, etc) are relatively straight forward if someone wants to tackle those as a start!  Maybe a collaborative PR.

**Comment by cmpadden** [comment]
Hey @adamdmharvey and @jhaals , let me know if either of you would like to collaborate on tackling this. I also have a Git branch with a work-in-progress v2 migration, but your branches may be cleaner or further along:

https://github.com/cmpadden/backstage/tree/docusaurus-v1-to-v2

I've followed the automated, and manual migration steps, and I've generated a vanilla v2 Docusaurus website to reference. There's a fair bit more work to be done: for instance, the navbar uses new class references so the custom styling is not being applied, images aren't resolving in blog posts, and the custom footer isn't implemented, and so on.

If you'd like me to create a WIP pull request, or add you as contributors to my repo/branch lmk!

**Comment by adamdmharvey** [comment]
Have at @cmpadden ! I've not done anything more in this space; I don't know if @jhaals 's branch is ready to be pushed, but if you open a PR at least we can feedback into it!

**Comment by cmpadden** [comment]
@adamdmharvey it's a bit of a mess, but I've created a draft pull request: #8489. I've also invited you and @jhaals to collaborate on my fork of Backstage if you'd like to work on this pull request too -- if not that's totally fine too.

**Comment by jhaals** [comment]
Hey @cmpadden!

Nice to see that you're interested in taking this up!  💯 
I would love if this could be done in smaller increments otherwise this is going to be hard to review and keep as a working branch :) Migrating away from class components for example could probably be done prior to upgrading to latest. There is probably a lot of other things that could be shipped in chunks as well

**Comment by jhaals** [comment]
Fantastic! You will be at the top of Santa's delivery list for Christmas 🎅

**Comment by benjdlambert** [comment]
Closing in favour #12019
