### ISSUE TITLE
[RFC] Filter the catalog table columns based on the selected kind

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#8336]
**Status:** Open for comments

## Need

Filter the catalog table columns based on the selected kind in the filter.

We have some custom fields in our component kind and we would like to show them in the catalog table as a separate column. I understand that we are able to pass down the columns to the catalog index page, but the issue I'm facing is that there is no way (or I did not recognize one) to filter different columns for the catalog index when we change the kind in the dropdown in the header.

We want to avoid having the component-specific property in the users or groups list for example. Is there a built-in way to achieve this or do I need to customize the catalog index page?

I could not find any hook that will give me the selected filter 🤔 

## Alternatives

Replace the catalog index page and build the columns based on filter inside based on `useEntityListProvider` hook. This is something I would like to be my last resort.

Add another prop that will output the selected kind on change in the select component here https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogKindHeader/CatalogKindHeader.tsx#L45

## Risks

By replacing the catalog index page, we might go out of sync in terms of getting the latest changes.

**Comment by ProticM** [comment]
I had in mind something like this https://github.com/backstage/backstage/pull/8379

**Comment by jhaals** [comment]
Hi! It would be great to know why the `useEntityListProvider` is considered the last resort. It would be the suggested way of doing this.

Looping in @timbonicus as he's a very skilled at filtering :)

**Comment by ProticM** [comment]
Hi @jhaals I was not referring to the hook, but rather to replace the entire catalog index page.

That hook cannot be used outside of `EntityListContext` that is wrapping the `CatalogIndexPage` but I need the output of it outside of the context boundaries thus as the simplest solution I see would be to add the change event

**Comment by ProticM** [comment]
Also, not sure that this one here https://github.com/backstage/backstage/runs/4431263298?check_suite_focus=true failed due to my changes 🤔

**Comment by timbonicus** [comment]
@ProticM I'm not sure the `kind` change event buys you anything, since this could already be done using the hook.

I'd go about this by [customizing the catalog page](https://backstage.io/docs/features/software-catalog/catalog-customization), as you say, and adding a wrapper around the `CatalogTable` that uses the `useEntityListProvider` hook:

```tsx
// packages/app/src/components/catalog/CustomCatalogPage.tsx

export const CustomCatalogPage = () => {
  const orgName =
    useApi(configApiRef).getOptionalString('organization.name') ?? 'Backstage';
  const createComponentLink = useRouteRef(
    catalogPlugin.externalRoutes.createComponent,
  );

  return (
    <PageWithHeader title={`${orgName} Catalog`} themeId="home">
      <EntityListProvider>
        <Content>
          <ContentHeader titleComponent={<CatalogKindHeader />}>
            <CreateButton
              title="Create Component"
              to={createComponentLink && createComponentLink()}
            />
            <SupportButton>All your software catalog entities</SupportButton>
          </ContentHeader>
          <FilteredEntityLayout>
            <FilterContainer>
              <EntityTypePicker />
              <UserListPicker />
              <EntityOwnerPicker />
              <EntityLifecyclePicker />
              <EntityTagPicker />
            </FilterContainer>
            <EntityListContainer>
              <CatalogTableWrapper />
            </EntityListContainer>
          </FilteredEntityLayout>
        </Content>
      </EntityListProvider>
    </PageWithHeader>
  );
};

```

```tsx
// packages/app/src/components/catalog/CatalogTableWrapper.tsx
import React, { useMemo } from 'react';
import { useEntityListProvider } from '@backstage/plugin-catalog-react';
import { CatalogTable, createNameColumn } from '@backstage/plugin-catalog';

export const CatalogTableWrapper = () => {
  const {
    filters: { kind: kindFilter },
  } = useEntityListProvider();

  const columns = useMemo(() => {
    // Logic here
    return [
      createNameColumn({ defaultKind: kindFilter?.value }),
      // ... more columns
    ];
  }, [kindFilter?.value]);

  return <CatalogTable columns={columns} />;
};

```

This is similar to how the [default columns](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L50) (that update slightly based on `kind`) work.

**Comment by ProticM** [comment]
Hi @timbonicus 

The way I see it, It does for sure because of the number one and primary reason which is that `useEntityListProvider` cannot be used at the app level, but rather only inside of components wrapped with `EntityListProvider`.

Considering that the `CatalogIndexPage` is required as a route element and it cannot be rendered by other components (which would be great because in that case I could create a wrapper and use `useParams` hook for example) in order to achieve the columns re-render on kind change, we need changes in the App.tsx:

```
const routes = () => {
// here we need to detect the kind change from the filter and recreate the columns

useEntityListProvider() // this does not work, it needs a proper wrapper component
useParams() // this does not work, outside of the route component

 return (<FlatRoutes>
    ...other routes
   <Route path="/catalog" element={<CatalogIndexPage />} />
    ....other routes
 </FlatRoutes>)
}

// Option 2 (does not work because the CatalogIndexPage must be passed directly as an element)
const MyCustomCatalogPage = () => {
  return <CatalogIndexPage />
}

return (<FlatRoutes>
    ...other routes
   <Route path="/catalog" element={<MyCustomCatalogPage />} />
    ....other routes
 </FlatRoutes>)
}

// Option 3 (with the event and a working version)
const onKindChange = useCallback((kind: EntityKindFilter) => {
  return kind?.value === 'group' ? [col1, col2] : defaultCols;
})

return (<FlatRoutes>
    ...other routes
   <Route path="/catalog" element={<CatalogIndexPage onKindEventChange={onKindChange} columns={columns} />} />
    ....other routes
 </FlatRoutes>)
}
```

By having it the way described in the option 3, we do not need to recreate the same existing page again.

In our case, our "_custom_" catalog index page will be exactly the same except that would have the ability to change the columns based on the selected kind, all other parts would work and look the same.

So, are you saying that I'm better off copping all required parts related to the CatalogIndexPage instead of having some entry point to listen for the changes?

**Comment by timbonicus** [comment]
To be clear, you'd be implementing your own CatalogPage but _importing_ almost all of the components from `@backstage/plugin-catalog-react`. So you're not duplicating the individual parts, only the top-level page that assembles them (those few dozen lines shown above) — in order to customize it.

The `useEntityListProvider` hook can't be used outside of React context because it relies on the `catalogApi` which itself is only available through the `useApi` hook. This is a fundamental architecture decision in Backstage that provides the capability to override frontend APIs as a Backstage adopter through `createApp`.

I totally understand that duplicating this JSX might seem heavy and unnecessary, unfortunate even.

But there are many individual requests to customize the catalog page in different ways; changing the header, adding filters, changing defaults, customizing the table, disabling buttons. Many of these come with a request to add a prop to `CatalogPage` that's very specific to the customization in mind.

This leads to an unfortunate situation over time where there's tons of special-purpose, opaque props on the page. We also need to consider other pages that have similar displays - such as search, the `Create` page for software templates, or the api-docs plugin.

The `EntityListProvider` is there to avoid prop explosion, support these many different use cases of fetching things from the catalog, and to make it possible to customize filters by simply dropping in components that interact with the context.

Your solution avoids the JSX duplication, but falls prey to these broader concerns. I hope this explains a bit why it's undesirable. Until a proposal is levied that can more broadly address page customization needs, preferably in a universal way across the entire app, offering up the catalog building blocks to reassemble seems the most flexible way to support many different customizations.

**Comment by ProticM** [comment]
I understand fully your concern and approach to this.

> To be clear, you'd be implementing your own CatalogPage but importing almost all of the components from @backstage/plugin-catalog-react. So you're not duplicating the individual parts, only the top-level page that assembles them (those few dozen lines shown above) — in order to customize it.

Yes, I'm aware of that, and I've tried with that approach to see what and if something is not exported.

> But there are many individual requests to customize the catalog page in different ways; changing the header, adding filters, changing defaults, customizing the table, disabling buttons. Many of these come with a request to add a prop to CatalogPage that's very specific to the customization in mind.

I see and I was thinking about this and ran a couple of analyses, as the time allowed me, to get to a solution where we will have one single point to listen to all filter changes from the component, but outside of the `EntityListProvider` due to the hook limitations. But in the end, the event was simply firing too many times, and finding out which actual field in the filter got changed would be a bit messy, and adding multiple events would simply introduce the props boom as well that you mentioned.

> Your solution avoids the JSX duplication, but falls prey to these broader concerns. I hope this explains a bit why it's undesirable. Until a proposal is levied that can more broadly address page customization needs, preferably in a universal way across the entire app, offering up the catalog building blocks to reassemble seems the most flexible way to support many different customizations.

Regarding this, my last and sort of a middle-ground solution would be to introduce slots the `CatalogIndexPage` that we can pass down as building blocks thus we keep the required wrappers in place and provide the parts that we want to change outside of the component, and in the end, if this is not enough for someone, they can still replace the entire page as suggested currently.

Do you see any limitations in the last solution?

**Comment by timbonicus** [comment]
That's an interesting idea. There's precedent at the app level using the [components argument](https://github.com/backstage/backstage/blob/master/packages/app/src/App.tsx#L98) to createApp which accepts a select few app-level components for overriding. I've leaned away from considering that exact mechanism since it won't scale, but supporting this on a page level seems interesting. Something like this?

```tsx
export type CatalogPageComponents = {
  ContentHeader?: ComponentType<ContentHeaderProps>;
  CatalogTable?: ComponentType<CatalogTableProps>;
}

export type CatalogPageProps = {
  initiallySelectedFilter?: UserListFilterKind;
  columns?: TableColumn<EntityRow>[];
  actions?: TableProps<EntityRow>['actions'];
  components?: CatalogPageComponents;
};
```

Falling back to the default / current page components if not provided?

I like this idea! 🤔  Any thoughts @backstage/maintainers?

**Comment by ProticM** [comment]
Yes, something like that, to be consistent.

Also, another more intuitive approach IMHO would be to have a static prop on the component and pass it down within the children prop:

```jsx
<CatalogIndexPage>
  <CatalogIndexPage.Header>
     // code
  </CatalogIndexPage.Header>
  <CatalogIndexPage.Content>
     // code
  </CatalogIndexPage.Content>
</CatalogIndexPage>
```

Either way, the output should be the same, so your approach would be good as well because it is something you already have in the app.

**Comment by benjdlambert** [comment]
@timbonicus I do like the components idea, but I think where it falls down is that it doesn't scale to anything that is shipped outside of the core app. I would think that it would be great to have one solution that works for plugins that the `app` doesn't know about already, like being able to override things in plugins later installed for instance.

I know @Rugvip has done some `LayoutExperiments` but it's not really been a focus for us yet. Being able to provide slots and things that are bound by props, and you can decide whatever component to render in the middle providing you meet the prop boundary is probably a nice way to go about this, but again, it's all a little early days right now.

**Comment by timbonicus** [comment]
@benjdlambert How do you mean? Any exported page or component would be free to adopt the `components` prop pattern. Are you thinking that something should be more codified in the plugin extension methods?

@Rugvip's [layout experiments](https://github.com/backstage/backstage/blob/rugvip/layout/docs/plugins/layout.md) focus mainly on actual page layout; I see some mention of overridable components at the bottom of his notes but it's a bit unclear to me 🤔

**Comment by benjdlambert** [comment]
Yeah I think we probably want to settle up some of the outcomes from the layout experiments and throw them into an RFC or hopefully get someone to own this work if we don't have time to complete this. So much to do and not enough time :joy:

**Comment by webark** [comment]
We have been going through the process of passing in a custom set of columns into all the individual places they are used, and overwriting the ones that we can't get to.

I don't think "as it stands now" it's the best pattern, but the api specs uses a api to render the component, so that enables you to extend the api and add your own renderings (we use redoc). It would be nice if you could do something like this, and almost have a "columns" api which could be delimitated by kind, and also by "page|card" (we currently have this in a package that we import places)

Using the regular api factories feels odd (like is done for api specs) but maybe there could be a "component api" or something? Maybe that was the layouts thing you were mentioning.
