### ISSUE TITLE
CatalogIdentityClient does not issue backend tokens

### ISSUE THREAD

**Issue by rv-ddeloff** [backstage/backstage#8344]
The CatalogIdentityClient found in the `auth-backend` plugin does not issue a backend token in the method `resolveCatalogMembership`. 

## Expected Behavior

Like the `findUser` [method](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/lib/catalog/CatalogIdentityClient.ts#L64), I should expect the client to issue a backend token before making a request to the catalogApi.

## Current Behavior

No token is issued, returning a 401 when using a auth middleware.

## Possible Solution

Using the supplied `tokenIssuer`, issue a new backend token and pass it to the `getEntities` call.

## Steps to Reproduce

1. Authenticate requests with an auth middleware 
(for example https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md)
2. Set up a simple sign-in resolver like so 
https://backstage.io/docs/auth/identity-resolver#resolving-membership-through-the-catalog
3. Try to sign in.

## Context

Our team would like to use the provided identity client without creating a hack to inject our own token.

## Your Environment

```OS:   Darwin 20.6.0 - darwin/x64
node: v14.15.1
yarn: 1.22.10
cli:  0.8.0 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.1
  @backstage/backend-common                                0.9.12
  @backstage/catalog-client                                0.5.2
  @backstage/catalog-model                                 0.9.7
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.8.0
  @backstage/config-loader                                 0.7.0, 0.8.1
  @backstage/config                                        0.1.11
  @backstage/core-app-api                                  0.1.24
  @backstage/core-components                               0.7.6
  @backstage/core-plugin-api                               0.2.2
  @backstage/dev-utils                                     0.2.13
  @backstage/errors                                        0.1.5
  @backstage/integration-react                             0.1.14
  @backstage/integration                                   0.6.10
  @backstage/plugin-api-docs                               0.6.16
  @backstage/plugin-app-backend                            0.3.19
  @backstage/plugin-auth-backend                           0.4.10
  @backstage/plugin-catalog-backend                        0.19.0
  @backstage/plugin-catalog-import                         0.7.4
  @backstage/plugin-catalog-react                          0.6.4
  @backstage/plugin-catalog                                0.7.3
  @backstage/plugin-circleci                               0.2.29
  @backstage/plugin-explore-react                          0.0.7
  @backstage/plugin-explore                                0.3.21
  @backstage/plugin-github-actions                         0.4.25
  @backstage/plugin-org                                    0.3.29
  @backstage/plugin-proxy-backend                          0.2.14
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.5
  @backstage/plugin-scaffolder-backend                     0.15.15
  @backstage/plugin-scaffolder-common                      0.1.1
  @backstage/plugin-scaffolder                             0.11.13
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.2.7
  @backstage/plugin-search                                 0.5.0
  @backstage/plugin-tech-radar                             0.4.12
  @backstage/plugin-techdocs-backend                       0.10.9
  @backstage/plugin-techdocs                               0.12.8
  @backstage/plugin-user-settings                          0.3.12
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.10.8
  @backstage/test-utils                                    0.1.23
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.0
✨  Done in 0.85s.```

**Comment by mtlewis** [comment]
Hey @rv-ddeloff! Thanks for flagging this. Since #7943, there is a new standard for generating and validating tokens which authenticate the Backstage backend itself (see the [backend-to-backend auth tutorial](https://github.com/backstage/backstage/blob/master/docs/tutorials/backend-to-backend-auth.md) for details). I'm not familiar with the CatalogIdentityClient, but it looks to me like we should be using the new approach.

This will be a breaking change, so I'm wondering whether we should start by updating `resolveCatalogMembership` to generate tokens the same way `findUser` does, then migrate both to use the `ServerTokenManager` via a separate breaking change. Alongside this, we'll also need to update the docs for auth middlewares to validate both user and backend tokens. WDYT @Rugvip / @nissayeva?

**Comment by Rugvip** [comment]
Yeah indeed, the logic in `resolveCatalogMembership` is from the point of view of a user, and we should really be able to use that user's token in the request. The tricky bit is the intended usage of the `CatalogIdentityClient`, which is to look up information for a user that is being signed in, and what information we want to put in their token. Because of that we end up with a bit of a chicken and egg problem. Creating multiple user tokens during the flow would be a workaround, but I don't think that's a great long-term solution, both because it's arguably wasteful, but also because we leave it up to the sign-in resolver to implement that, which is a place we want to keep very lean.

So as an immediate fix I think replicating the `findUser` logic makes sense, and then we'll switch both of the usages out for a token that we acquire from a `ServerTokenManager` instead.

**Comment by rv-ddeloff** [comment]
Something else that I just realized. Is the `catalog-backend` Service responsible for authenticating backend requests, or do we need to implement that ourselves in a middleware? I know that the tutorial that I linked above uses a static function found in the `IdentityClient` class, however this class fails to authenticate tokens sourced from a backend. And on the flip side, the `ServerTokenManager` class fails when it tries to authenticate tokens created at sign in. Is there a way to know whether a token was originally sourced from one of the two classes?

**Comment by nissayeva** [comment]
it'll be an addition to the middleware, and currently requires both. an approach here could be to first try to check if the token is a server token using the `validate` method in `ServerTokenManager`. if it is, pass that token along, and if it's not, try to check if the token is a backstage user token using the `IdentityClient`. if it's not that either, authentication fails.

**Comment by DaspawnW** [comment]
Everyone who want's can throw now the first stone... ![](https://i.imgur.com/ySqXvJj.gif)

And I will definitely accept it...

But there is a simple hack until at least there is a possible solution for it available. Inside the index.ts there is an async main function. Here a small patch for it:

```diff
// packages/backend/src/index.ts from a create-app deployment

async function main() {
  // ...

  const root = getRootLogger();
  const tokenManager = ServerTokenManager.fromConfig(config, {logger: root})

  const authMiddleware = async (
    // ...
    catch (error) {
      try {
        const token =
            IdentityClient.getBearerToken(req.headers.authorization) ||
            req.cookies['token'];

        await tokenManager.authenticate(token);
        next();
      } catch (error) {
          res.status(401).send(`Unauthorized`);
      }
    }
  };
// ...
}

```
