### ISSUE TITLE
Ability to implement my own GitHub Credentials provider

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#8359]
## Feature Suggestion
If I configure backstage to use a GitHub app, I must place the private key on the file system of the backstage instance. This means that if the backstage filesystem is compromised, the attacker has access to all of the approved permissions on all of the organizations with an installation of the GitHub app.

What we would like to do is to implement our own GitHub credentials provider. It would reach out to an external service that dishes out temporary github installation tokens to backstage.

At present, I dont believe it is possible to configure backstage with a custom provider like I am describing. Although I could be wrong.

## Possible Implementation

Id like to suggest that we provide some ability to pass a custom implementation of the credentials provider via the backend package. I am not exactly sure about the details of how that'd be done but would welcome suggestions.

## Context
The motivation for this ticket is to make the private key of the GitHub app more secure. This key gives great power to the holder and as such is very sensitive. e.g. if you are using the scaffolder, you probably have requested administration write permissions on your installations organizations. We need to protect this key well.

**Comment by Rugvip** [comment]
💯, I think it may be wise to flip around the responsibility of instantiating the SCM Integration utilities so that they're injected rather than created from config, and attach credential providers to that.

It's a bit painful to add things to the backend environment right now though, and we're currently very tempted to introduce some form of DI in the backend system. It's something we'll be taking a look at at the beginning of the next year, but are so far undecided whether we're gonna aim to ship anything then or not.

If there are any suggestions or thoughts in the DI space we'd be glad to hear them btw :grin:

**Comment by punkle** [comment]
I tend to agree that it is painful. I also agree that DI will go a long way to help with customizations like this.

On Friday I had a quick look at one DI container framework for js/ts called inversify. I was fairly quickly able to get something up and running. It requires some experimental features to work. It seems to have some extensions for managing express apps.

I think to integrate it would be quite a change. It could be done incrementally. Although there would be tradeoffs to doing it incrementally vs going all in on it. If it is done incrementally and commitment is lost on the approach, it would be quite a confusing area of code to read.

At this point I have not looked at other DI frameworks.

**Comment by punkle** [comment]
Ive added a proposed implementation of this. Its kind of a step towards DI without adding a full framework. Let me know what you think. :)

**Comment by Rugvip** [comment]
Done in #8619
