### ISSUE TITLE
SECURITY.md file has a dead link to create a security advisory

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#8413]
## Expected Behavior

The link to create a security advisory brings me to a page / service where I can report a security issue.

## Current Behavior

The link to create a security advisory brings me to a page not found error in github https://github.com/backstage/backstage/security/advisories/new

## Possible Solution
I dont have a suggestion at this point.

## Steps to Reproduce

1. Go to the SECURITY.md file and click the link for creating a security advisory.

## Context

I cannot report a security issue.

## Your Environment

N/A

**Comment by jhaals** [comment]
Hi @punkle, we use hackerOne for reporting on vulnerabilities, see the first section of the SECURITY.md https://github.com/backstage/backstage/blob/master/SECURITY.md#reporting-a-vulnerability

If you know of a problem please report it at https://hackerone.com/spotify?type=team

The second part of the document is for the maintainers creating the advisory 
> In the event of a vulnerability the runbook for the maintainers is as follows:

The reason for not seeing the page is simply because of permissions.

If anything is unclear feel free to submit a PR or reopen this issue for further discussion.
