### ISSUE TITLE
Pagerduty plugin get 'undefined' from reading metadata

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#8457]
Hi,

I just updated my catalog plugin recently, but I got an error `Cannot read properties of undefined (reading 'metadata')`, but seemed the catalog plugin read `metadata` successfully. 

![image](https://user-images.githubusercontent.com/56138162/145686270-a769e852-e5ca-4f87-ab90-635b79e85f2c.png)
![image](https://user-images.githubusercontent.com/56138162/145686281-529026f1-e1a1-4893-9541-7ff43085921c.png)

**Comment by OrkoHunter** [comment]
Hi @chuliang014 ! 

When you load the PagerDuty card, it tries to get the Catalog entity (service) from the React context. [Ref](https://github.com/backstage/backstage/blob/a3ec122170e0205fd3f9c307b98b1c5e4f55bf5f/plugins/pagerduty/src/hooks/index.ts#L22). This error means that it was unable to fetch the "dev-eng-hub" entity from context.

One thing I am observing is that the `PagerDutyCard` is designed to be used inside a Catalog entity page rather than a tab. [Ref](https://github.com/backstage/backstage/blob/a3ec122170e0205fd3f9c307b98b1c5e4f55bf5f/packages/app/src/components/catalog/EntityPage.tsx#L284-L291) So, it's possible that the card might not work as a "Page" in the tab.

Can you share
1. The snippet of your EntityPage (packages/app/src/components/catalog/EntityPage.tsx) where you make use of the PagerDutyCard? It could be possible that something is not right for the React context to be set.
2. You say that this used to work before on a older version of `@backstage/plugin-catalog`. Can you try rolling back the version and let us know until what version this page was working? We should look into [Changelogs](https://github.com/backstage/backstage/blob/master/plugins/catalog/CHANGELOG.md) and find something useful.
3. Are there any additional errors in the browser console which can help us debug?

Thank you!

**Comment by chuliang014** [comment]
Hi @OrkoHunter, please take a look the snippet below.
![image](https://user-images.githubusercontent.com/56138162/145701844-62fe26cc-79e8-418f-acb9-9178a290258d.png)
![image](https://user-images.githubusercontent.com/56138162/145701861-f3077e40-2543-4850-a495-4a15e1de58c8.png)

Actually, I upgraded a lot of package today. maybe you can take a look. One is `packages/app/package.json`, the other one is `packages/backend/package.json`.  The working version of `@backstage/plugin-catalog` should be `0.6.1`, it is really old version....
![image](https://user-images.githubusercontent.com/56138162/145701919-95a57d29-34d4-4f41-9efb-bb9e8b1bc74f.png)
![image](https://user-images.githubusercontent.com/56138162/145701938-681e8752-7bf4-4ac2-a6ae-a6323585f481.png)

**Comment by chuliang014** [comment]
@OrkoHunter fixed the issue after removing `node_modules` and executing `yarn install`
