### ISSUE TITLE
OAuth2 Azure AAD user_impersonation scopes support

### ISSUE THREAD

**Issue by samuelhnrq** [backstage/backstage#8522]
## Feature Suggestion

Maybe an implementation detail of the way Azure AAD works, **_the Azure DevOps scope `499b84ac-1321-427f-aa17-267ca6975798/user_impersonation` only works when it's the only one_**. And since the current implementation **always** prepends (maybe order works) the default scopes (`["openid","offline_access", "profile", "email","User.Read"]`)to the manually specified ones  they seem to always take precedence and generate a token with `00000003-0000-0000-c000-000000000000` audience (and without the impersonation scope) instead of the correct `499b84ac-1321-427f-aa17-267ca6975798` audience

## Possible Implementation

I would just like a better API for me to control the scopes field of the final /oauth/token request maybe a boolean flag to the options of  `getAccessToken` 
```javascript
const apiRef = useApi(microsoftAuthApiRef);
const { loading, value: token } = useAsync(() =>
  apiRef.getAccessToken([
    '499b84ac-1321-427f-aa17-267ca6975798/user_impersonation',
  ], { ignoreDefaultScopes: true }),
);
```

## Context

We use Azure DevOps for everything in our organization and we currently are having to mimick Azure DevOps permissions by reading them out of the users profile and manually checking his request to check if he actully is allowed to do given action before using our admin access token to call the API as the user requersted.

- Its incredibly dangerous for we to implement a bug and bypass permissions
- auditing nightmare, since who actully did the action is lost
- and also wasteful since everytime we have to check for (updated) permissions before every action

**Comment by samuelhnrq** [comment]
I could actually try to implement the feature myself if the proposed solution is satisfactory.

**Comment by samuelhnrq** [comment]
Testing this is a little obnoxious because 
1. it needs an azure AAD app, with enabled azure devops delegated API permission ([like this](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-access-web-apis#application-permission-to-microsoft-graph)), 
2. a alternate openid client e.g. postman to compare results against.

Try Calling the ´getAccessToken´ as in the example, and [decoding](https://jwt.io) the jwt, its audience will be 00000003-0000-0000-c000-000000000000, now try doing the oauth flow manually with _only_ the `499b84ac-1321-427f-aa17-267ca6975798/user_impersonation` scope and the audience will be correct. (499b84ac-1321-427f-aa17-267ca6975798)

**Comment by freben** [comment]
Sounds sensible to me. @Rugvip?

I wonder if this one will actually turn out to be a bit tricky. There are some layers involved in the merging of scopes and stuff. These non-merging ones will probably have to turn out to never merge with others, leading to a row all of its own in the popup dialog and stuff like that. But do give it a go!

**Comment by Rugvip** [comment]
Yep I think it makes sense. As freben mentions there's a bit more to the scopes than just the default ones being merged in, there's also merging between simultaneous and old access token requests. I think the proposed solution is the way to go, although I think we could frame it as "isolated" request rather than only omitting the default scopes. With that it'd also serve as a security feature that can be used when requesting very sensitive scope that you wouldn't want to be mixed in with the existing session.

Perhaps the trickiest bit here would be management of the session, I'm thinking we could punt that for now and see if we could make these isolated access token requests not be part of the main session and therefore not support refreshes. Would that work for your case?

**Comment by samuelhnrq** [comment]
Thanks for the info @Rugvip, that actually raised a lot more questions 😆, I had no idea `getAccessToken` ran so deep into session management. 

Incidentally I guess that also answers why the authentication modal wasn't working, does it checks the current session's JWT scopes to see if it already contains the requested scope?

And what do you mean by "_simultaneous and old access token requests_"? Does it mean that when the hook is called after the modal is open waiting and for user input, it has logic for adding up all the scopes of the subsequent calls of `getAccessToken` ? If that is the case is not a issue for this use case, only consideration is some kind of lock to prevent stacked permissions dialog.

And about "_would be management of the session_" do you mean that the front-end code keeps track of all previous requested scopes to preemptively (`setTimeout`) refresh them in the background? It would indeed be a royal pain to have a set of scope lists to refresh individually, having a simple LRU with TTL for the exact & joined scopes list (passed to the proposed new hook) as the key would suffice. And only refreshing after a call resulting in a cache miss. 

My last question is then, what is the current oauth2 flow of the backstage front-end? Which one should I pick for this? There is talk about the removal of cookies which kind of is the last nail of the implicit flow coffin... The [PKCE flow](https://auth0.com/docs/authorization/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce) seems nice but I never actually implemented it... Where to store refresh token & proof key. `window.localStorage`? Or making an ad-hoc implicit flow request on demand is what you meant by "_isolated access token requests_"?

**Comment by Rugvip** [comment]
@samuelhnrq tokens are refreshed on demand, so there's no background timeout, just a refresh as needed if access tokens are about to expire or will expire soon.

"Simultaneous requests" would be multiple calls to `getAccessToken` for the same provider. These all get merged together and shown once in the dialog. The dialog also handled multiple requests at once for different providers so don't need to worry dialog stacking too much. The client keeps track of the scopes that have been granted so far, and iirc most implementations rely on the response from the refresh endpoint to inspect the scopes of the stored session, although it might be that some store them somewhere else too.

Session management is pretty much the same as "refresh token storage" in this case. Right now the typical setup is to store refresh tokens in a cookie, but only one of them at a time per provider. If we start doing isolated quests then we don't currently have a place to store those refresh tokens, and so we wouldn't be able to refresh the session. What that means in practice is that if the user reloads the page or stays on it until the access token expires, then they will have to log in again for this isolated request.

I think these isolated requests make sense for sensitive scopes, but if it's a scope that is used very commonly then It's gonna be a problem, as users will be asked to log in over and over again.

The OAuth flow is pretty much always authorization code flow with the help of the `auth-backend` plugin. It may look a bit different because we execute it in a popup and then `postMessage` the response back to the app.
