### ISSUE TITLE
yarn create-plugin --backend no longer works

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#8581]
## Expected Behavior

Docs for creating a backend plugin should be up-to-date.

## Current Behavior

`yarn create-plugin --backend` is no longer valid after https://github.com/backstage/backstage/pull/8039

## Possible Solution

Update docs https://backstage.io/docs/plugins/backend-plugin with the latest way to create a backend plugin i.e. `yarn backstage-cli create` and choose backend-plugin.

@rugvip Any other thoughts on this? 😁

**Comment by Rugvip** [comment]
The new `create` command isn't actually rolled out in `create-app` yet. The missing piece there is to update the root package.json to have the `backstage-create` script which runs `backstage-cli create` along with locally configured flags. The root package.json in the main repo has the script, so that can be used as a reference. We'd want that change in first, and once it's released it makes sense to update documentation everywhere to reference the new command.

**Comment by genzyy** [comment]
Hey can I take this issue up? Seems easy for me to get started with this project. How should I start this?

**Comment by jhaals** [comment]
Of course you can! :) If I understand @Rugvip the file that need updating before addressing documentation is https://github.com/backstage/backstage/blob/master/packages/create-app/templates/default-app/package.json.hbs#L23

**Comment by genzyy** [comment]
So that means I need to update that file with this right?

https://github.com/backstage/backstage/blob/a356288fceffdde19dcf1e1d1c7b70fc24d135be/package.json#L26 
https://github.com/backstage/backstage/blob/a356288fceffdde19dcf1e1d1c7b70fc24d135be/package.json#L27

**Comment by benjdlambert** [comment]
I think you probably want to copy the existing values that's in there already, so `--scope` internal is probably the change we want to make to the `create-app` template.
