### ISSUE TITLE
[TechInsights] Collision between multiple FactId using the same fact name

### ISSUE THREAD

**Issue by goenning** [backstage/backstage#8655]
## Feature Suggestion

Currently all facts are merged into a single object which is used for checking, which means that when 2 fact ids collect the same fact name, only one of them will be processed as the other is overwritten.

```js
    const factValues = Object.values(facts).reduce((acc, it) => ({ ...acc, ...it.facts }), {});
    try {
      const results = await engine.run(factValues);
      return await this.ruleEngineResultsToCheckResponse(results, techInsightChecks, Object.values(facts));
    } catch (e) {
      throw new Error(`Failed to run rules engine, ${e.message}`);
    }
```

As an example, we could have 2 fact retrievers: "NextJSVersionFactRetriever" and "ReactVersionFactRetriever" and they both collect a `version` fact which is correctly stored separately in the DB. When writing the checks though, if my check targets `ReactVersionFactRetriever` and the `version`, there's a chance it'll use the version from the `NextJSVersionFactRetriever` (or vice-versa).

## Possible Implementation

- Option 1
Drop the factIds from the TechInsightCheck and append it as a namespace directly into the fact condition. This is in my opinion the most flexible as it's possible to combine multiple facts with the same name in a single check.

```js
{
    id: 'NextJSVersionFactRetriever-FactCheck',
    name: 'NextJSVersion',
    type: JSON_RULE_ENGINE_CHECK_TYPE,
    description: 'Next.JS must be on version 11.0.0 or higher',
    rule: {
      conditions: {
        any: [{ fact: 'NextJSVersionFactRetriever.version', operator: 'semver', value: '>=5.0.0' }],
      },
    },
  };

or:

rule: {
  conditions: {
    any: [{ factId: 'NextJSVersionFactRetriever', fact: 'version', operator: 'semver', value: '>=5.0.0' }],
  },
},
```

- Option 2
- Execute the `engine.run` for each check individually, so it doesn't have to bundle all facts together, just the ones the check needs. There is no contract change here, which is great, but it's not possible to have a single check that uses two facts with the same name.

Any thoughts?

**Comment by Xantier** [comment]
Thanks @goenning,

Yeah, I agree this is not ideal. It's is circumventable by naming the facts uniquely (essentially, namespacing them manually) but that is not really ideal. I also don't think option 2 is good since I feel there is a big need to use whatever facts are available, regardless of their retriever association. 

So option number 1 is the likely way we want to go forward. Since the rules-engine itself is stringly typed in this manner, I think we should try to make it a little bit more strict and add the fact retriever id as a separate (optional) field to make the disctinction between fact values. This can be then appended into a concatenated string to the facts registered into the engine itself as well as concatenated into the check itself automatically. 

Though unfortunate, I think the change in API is justified in this case. Adding the fact retriever id as an optional field does not make this a breaking change and gives the ability to to handle this differently in different use cases if integrators want to handle this on their side.
