### ISSUE TITLE
'spec' is required field in Location.v1alpha1.schema.json

### ISSUE THREAD

**Issue by kissmikijr** [backstage/backstage#8906]
Currently the schema  Location.v1alpha1.schema.json requires that the location entity files have a `spec` field. [here](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/schema/kinds/Location.v1alpha1.schema.json#L27) However it is not required for a location spec, backstage is working if we do not give spec to a location since all the properties of a spec object are optional anyways.
## Expected Behavior

```
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: todo-example-project
```
The validator should not fail on this yaml

## Current Behavior

The validator gives the following error: 
```
TypeError: <root> should have required property 'spec' - missingProperty: spec
```

## Possible Solution
Remove `spec` from the required array of the schema. [here](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/schema/kinds/Location.v1alpha1.schema.json#L27)

Or if this is the expected way how it should work, we should update the docs to reflect that the spec key is required. 
https://backstage.io/docs/features/software-catalog/descriptor-format#spectype-optional
## Context
We have [this ](https://github.com/RoadieHQ/backstage-entity-validator)validator tool which uses the validators from the backstage repo. Currently it will fail on location entities if they do not have a spec key defined.

**Comment by freben** [comment]
Hi!

Yep, the spec is indeed required in practice at this point, so the docs are wrong.

I'd suggest updating the docs, rather than the code and schemas. While technically all fields of the spec are optional, it'd be completely useless to have a location with no spec fields at all :) The bare minimum (in terms of making sense) would be to have _either_ `spec.target` _or_ a non-empty `spec.targets` given, but the current schema hasn't gone through the trouble of doing a proper `oneOf` for that.

Would you like to contribute that docs update?

**Comment by kissmikijr** [comment]
Yes I think the same, I'll update the docs.
