### ISSUE TITLE
Improve UX for signed out users

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#9063]
## Feature Suggestion

_I'm going to focus on cases where GitHub is integrated with Backstage, since it's the one I hear about in my conversations with customers, but I believe this issue would apply to other integrations also._

Backstage is useful for users who who do not have GitHub accounts. They can use TechDocs to read about components, they can browse API specs, they can look at the k8s plugin etc. However, the experience of using it could be improved.

For example, viewing a service which displays the latest GitHub actions card, causes a full page popup to the user. This is useful for users who have a GitHub account, because it reminds them to log in, but non-GitHub users have to click the scary "Reject All" button to dismiss it. It pops up every time they try to visit a Component of this kind, which prevents them accessing something useful like TechDocs.

Here's a recording of this in action.

https://user-images.githubusercontent.com/562403/150390129-bd7eeaa2-3507-4140-9cf3-b85dc1575e44.mp4

## Possible Implementation

The modal dialog could be replaced with some more gentle text within the card to remind the user to log into GitHub. It could have a button which triggers the modal dialog when pressed.

**Comment by Rugvip** [comment]
A possible way forward here is to switch some cards to an in-line flow that calls `getAccessToken` using the `optional` and `instantPopup` [options](https://backstage.io/docs/reference/core-plugin-api.authrequestoptions). Setting `optional` to `true` allows you to check if the user is already logged in, and will just return an empty token otherwise. If the user isn't logged in, you can display a hint and a button or such, and when the user clicks that button you can request a token with `instantPopup` set to `true`, which will bypass the full-screen modal and just open the popup window directly. If that ends up being a common pattern for cards I think we can provide some helpers for implementing that as well.

Should also say that the all auth requests are controlled by the [OAuthRequestApi](https://backstage.io/docs/reference/core-plugin-api.oauthrequestapi). The [OAuthRequestDialog](https://github.com/backstage/backstage/blob/ad7780bb4684af1835194eb6371722c9a00ea299/packages/core-components/src/components/OAuthRequestDialog/OAuthRequestDialog.tsx#L53) that you typically put at the [root of your app](https://github.com/backstage/backstage/blob/ad7780bb4684af1835194eb6371722c9a00ea299/packages/app/src/App.tsx#L233) is what consumes this API to show the fullscreen modal, but you can replace that component with anything else that consumes the API and for example shows a more gentle notification.

**Comment by dtuite** [comment]
Thanks @Rugvip. Very interesting. In our implementation we already have a notification for users to sign into GitHub in the sidebar, so potentially we can just set `optional` to true like you suggest, and rely on the sidebar prompt to remind them.

![Screenshot 2022-01-20 at 18 21 54](https://user-images.githubusercontent.com/562403/150398504-a0c2ba49-ee05-411d-aa08-ed2e24bf7ea3.png)

Do you think this would work @iain-b?

**Comment by Rugvip** [comment]
Setting `optional` will not trigger a request though, it will just return an empty response if not already signed in. It would need to be coupled with some logic to detect the empty response and show a login button in the card instead.

**Comment by jarltotland** [comment]
Hi! We struggle with the this exact issue. We are trying to use Backstage as central repository for all our systems knowledge, and reach users in our entire company, not just developers. All our users authenticate with Entra ID but not all have accounts on e.g GitHub, JIRA etc. The popups are keeping them away from adopting Backstage, which is a shame. 

I did not find any work being done on this, is there a recommended workaround aside from forking the plugins we use and add it ourselves?
