### ISSUE TITLE
[RFC] Catalog Refresh Cycle Complete Event

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#9129]
**Status:** Open for comments

## Need

Currently, I'm working on the export functionality of the catalog (I'm exporting the data from the `final_entities` table, is this a proper source for the export?) data to an external database for historical purposes and for the ability to create some reports and analyses.

I want to have the process automated and triggered on a defined schedule. The problem I'm struggling with is that it seems that I'm not able to locate a point where I can hook into the refresh cycle process. I'm looking for a way to trigger some code every time the backstage catalog refresh cycle finishes. Is there such an option?

At the moment, I have the export in place run by a scheduled Fargate task, but this needs to be planned carefully with the backstage refresh cycle in order to minimize the possibility of the data being out of sync.

**Comment by Rugvip** [comment]
It's quite tricky as the catalog doesn't really have a strict processing cycle. You have entities being bumped up to the front of the queue and others that can lag behind. There might be some sort of generation counter that we could introduce so that you can grab `start = max(gen)` of all entities and then wait for `min(gen) > start`. My hunch is that that would be wildly inefficient for what you're doing though tbh. I'd point to #8219 as the best way forward for this use-case

**Comment by ProticM** [comment]
I read that RFC and it makes sense to have something like that. Will check it from time to time 👍 

One last question here related to the table. My plan is to export the data from the `final_entities` table. Is this the right source to be used here compared to the `refresh_state` table?

**Comment by jhaals** [comment]
Yes `final_entities` is the complete entity representation so use that table for exports.

**Comment by ProticM** [comment]
Thanks for the confirmation @jhaals and regarding the event that I need, will follow the changes related to #8219
