### ISSUE TITLE
Cannot read property 'getClient' of undefined

### ISSUE THREAD

**Issue by chuliang014** [backstage/backstage#9249]
Hi,

I'm getting an error after `yarn backstage-cli versions:bump`

![image](https://user-images.githubusercontent.com/56138162/151647908-7ee8fffb-806a-4652-8485-a139c309fc71.png)

**Comment by Rugvip** [comment]
Do you see any errors if you run `yarn tsc`? Might be that you missed a step while upgrading, particularly in the [create-app changelog](https://github.com/backstage/backstage/blob/master/packages/create-app/CHANGELOG.md).

**Comment by siyanew** [comment]
Any fix?

**Comment by chuliang014** [comment]
Hi @siyanew, I saw some errors after `yarn tsc`, so I just temporarily roll back to the old version of the dependencies.

**Comment by backjo** [comment]
We ran into this - turns out, we were missing `cache` being passed through to createRouter for techdocs.

**Comment by benjdlambert** [comment]
@chuliang014 @siyanew running `yarn tsc` will give you the errors to fix and that will remove the `getClient` warning. Looks like it could be something similar to @backjo. Going to close this but feel free to reply if you get stuck fixing the errors from `yarn tsc`

**Comment by backjo** [comment]
@benjdlambert - I think there might be a bug here still. `tsc` did _not_ complain about the lack of cache on the options passed into createRouter function for techdocs.

**Comment by benjdlambert** [comment]
Hmm - so that's interesting, because looking at the latest that was shipped on thursday at least, and looking at the blame it's been there for a while, the `cache` is definitely required. Can you still replicate this by removing the `cache` option passed to `createRouter`? Wondering if there's something deeper going on here as it sure looks like it should complain.
https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/service/router.ts#L43-L71

**Comment by backjo** [comment]
I take it back - there was a dangling ts-ignore in our case that was applying to more properties than expected!
