### ISSUE TITLE
[RFC] node version

### ISSUE THREAD

**Issue by ericis** [backstage/backstage#9278]
**Status:** Open for comments

## Need

PR #1610 removed the Node Version Manager configuration file, ".nvmrc", from the code base in favor of developer choice.

I'd love to see more discussion on this decision. Node / Yarn users have increasingly become concerned with "version pinning", even adding features like pinning `yarn` to a specific version with `yarn set version ...` and ".yarnrc".

While the "package.json" specifies `"node.engines"`, it tends to be more open and permissive out of convenience rather than out of explicit support. Some projects will actually test that developers can use multiple versions.

For an implementation of Backstage, there may only ever be one version that goes to production. So, this presents a challenge... the open source project might support multiple versions an implementation can choose from, but an implementation will ultimately ever target one (or, I can't think of a use case where multiple versions would exist from the same code base).

There are three major node version locations:

- Dockerfile: used to produce deployment container images with a specific version of node
- package.json: `node.engines` used to warn the developer that a specific version or range of versions of node are recommended or required
- .nvmrc: used to install a specific version of node unique to this project when a developer might work across multiple projects with different versions

## Proposal

Unite and standardize the versioning approach. One possible method might be to:

- Continue to allow developer choice through "package.json" `node.engines` by specifying a range of supported node versions
- Provide a specific LTS ".nvmrc" version recommendation and update "Dockerfile" to install a specific version of node using the version from that file

## Alternatives

- Business as usual
- Use a single version in "package.json" `node.engines` and optionally match it in ".nvmrc" and/or "Dockerfile"
- Script a solution that enables an implementation of Backstage to choose and maintain a specific version across all of these

## Risks

People might not like / prefer it.

**Comment by Rugvip** [comment]
Thank you for the suggestion!

I think we definitely want to be strict in what versions we support, both making sure we use LTS releases to avoid bug reports that are due to unstable Node.js releases, but also to move the entire project forward and drop support for older versions as needed.

When it comes to restricting the version beyond what we do right now, I'm very hesitant to be honest. Migrations are always easier if you can do them at your own pace. Take for example the React 16/17 migration, if we enforced a specific version of React rather than allowing each project to select, it would be a bit of a mess to migrate. This is magnified significantly when you consider community plugins outside of the main repo that need time to catch up, making it very disruptive to make immediately breaking migrations.

As for the proposal I kinda like the idea of having a "main" version that we recommend, again just to make sure we keep moving forward and don't leave docs and so on behind. I'd even say that it might be worth adding a Node.js versioning policy for the project, specifying how long we aim to support releases, etc.

When it comes to pinning with `.nvmrc`, I'm not quite sure tbh. What would you say the benefits of that would be as opposed to allowing people to use whatever version is allowed by the engine policy? Would also split that question into main repo vs created apps, but in the end anything created with `@backstage/create-app` is free to modify, including adding a shared `.nvmrc`.

**Comment by ericis** [comment]
@Rugvip these are great comments. This might bubble up to the idea of a "Backstage LTS" version. The real challenge lies in the versions of dependencies beneath that. I'd be curious to study how other open source projects have their own "LTS", but seem to manage their many dependencies as well.

For example, a project having a "lock" file ("package-lock.json" or "yarn.lock" - also applies to other languages) suggests that it's perfectly okay to lock a dependency version in a project, but you make a great point about the upgrade and migration path challenges, like React 16/17. Angular ended up writing a tool to hide upgrade/migration complexities with a robust test suite that they have to maintain.

Perhaps, this RFC is ultimately less about a node version and more about things like `$ backstage list available`, `$ backstage use latest` and $ backstage upgrade`.

**Comment by Rugvip** [comment]
@ericis then you might some of our ongoing work like https://github.com/backstage/backstage/pull/9092 and https://github.com/backstage/backstage/pull/8971 :grin:

**Comment by ericis** [comment]
Closed for lack of community interest. We can always address this in the future and implementations or forks of this project can add a ".nvmrc" file if they wish.
