### ISSUE TITLE
SidebarItem and SidebarSubmenuItem should work with href 

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#9293]
I am trying add add external URL as a menu entry in sidebar. Basically it should redirecting to third party. I am unable to do so. because it supports only "to" parameter as per my understanding.

`<SidebarSubmenuItem title="Go to Example" to={"https://example.com"} icon={BuildRoundedIcon} />`

## Current Behavior

SidebarItem and SidebarSubmenuItem only support to parameter

## Possible Solution

SidebarItem and SidebarSubmenuItem should support href and target too

## Steps to Reproduce

try to add external URL to SidebarItem/SidebarSubmenuItem

## Context

It is blocking me to do customization with sidebar. 

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

**Comment by benjdlambert** [comment]
What is it that's actually happening when you pass in `to`? And what do you expect to hapen?

**Comment by lalit774** [comment]
It does not redirect to another website. It will display like following.

https://localhost:3000/https:/example.com in brwoser bar.

I saw few places in backstage, we are using href/to. But SidebarItem and SidebarSubmenuItem does not support href.

**Comment by freben** [comment]
I think the underlying problem is that they use `Link` from material-ui, not the one from `@backstage/core-components`.

https://github.com/backstage/backstage/blob/bbd59ed35575402e3f46c1443a0afc7450910fe4/packages/core-components/src/layout/Sidebar/SidebarSubmenuItem.tsx#L165

Would you like to try to fix this? I think they should be interchangeable but ours will be handling these links properly. Either way, I do _not_ think we should change this to `href`; keep the original `to` but make it handle both local and external links.

**Comment by lalit774** [comment]
I agree with you. I love to do that change. but I just start to learning react and backstage. I was working in PHP before. I can spend 1 hour per day. But I like to start from low or if someone guide me. How to do that?

**Comment by freben** [comment]
In the _best_ case, if nothing else is going wrong, you could change the import at the top as mentioned in my previous comment. And the same thing presumably then, in the file for `SidebarItem`?

**Comment by lalit774** [comment]
Currently I am using SidebarItem with OnClick event. These small things will improve backstage. I will try to fix that.
