### ISSUE TITLE
Support an annotation that skips building techdocs

### ISSUE THREAD

**Issue by Niksko** [backstage/backstage#9463]
## Feature Suggestion

We'd like it to be possible to define the following `catalog-info.yaml`

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-component-with-docs
  description: My awesome component
  annotations:
    backstage.io/techdocs-ref: dir:.
    my-org.com/skip-techdocs-build: true
spec:
...
```

Adding the annotation `my-org.com/skip-techdocs-build` (potentially customizable in config) with the value `true` would cause the techdocs backend to not attempt to build techdocs for this component. However techdocs would still be fetched from whatever datastore is in use, and the docs for this component would still be displayed in the UI. This would allow users to place their own tech-docs in the correct place and have them served. See the context below for more info on the use case.

## Possible Implementation

Can we add an additional condition to this line? https://github.com/backstage/backstage/blob/9c17a6cdb9be6ba85ef9bfab76b94e672902b9fe/plugins/techdocs-backend/src/service/router.ts#L203

Something like

```
if (config.getString('techdocs.builder') !== 'local' || entity?.metadata?.annotations?.[config.getString('techdocs.builder.ignoreAnnotation'))
```

I'm happy to have a go at implementing this, or an alternate solution.

## Context

At our organisation, we'd like to support a 'hybrid' approach to handling the building of tech docs.

One path would be the 'default'/'out of the box' experience, where the Backstage backend builds the docs for you. The advantage here is that users need only populate their repository with their docs and an `mkdocs.yaml`, and we do the rest for them. For many users, this would work well. The limitation is that the user is bound by the plugins we choose to offer, and other things related to the execution of mkdocs.

We'd like users to have the option of opting out of us building docs for them, if they need added flexibility in how they build their docs, or to customize mkdocs plugins etc. We think a sensible way for them to signal this would be to add an annotation to their `catalog-info.yaml` that indicates that we should not build the docs for them. They would instead build the docs themselves, and write them to the appropriate place for Backstage to serve them from.

If there's a better/easier way to accomplish this, we'd love to hear!

**Comment by kuangp** [comment]
related: https://github.com/backstage/backstage/issues/5905

**Comment by Niksko** [comment]
I've started work on this and hope to have a PR ready shortly

**Comment by Rugvip** [comment]
I wanna bring up the option of adding a bit of indirection in the TechDocs backend rather than adding a new standardized annotation for this use-case. I think the annotation route is a bit scary because it can quickly become messy as these kind of customizations are needed by more orgs.

Gonna need @backstage/techdocs-core to chime in with details, but what I'm suggesting is some form of `EntityTechDocsResolver` interface or something of that sort. For example that something like this mockup, although this is hopefully inaccurate as I don't know the internals of the TechDocs backend :grin:

```ts
interface EntityTechDocsResolver {
  resolveEntityTechDocs(entity: Entity): Promise<{
    type: 'built',
    ...
  } | {
    type: 'published',
    ...
  }>
}
```

That kind of interface would allow for both a custom annotation to be added if you want to solve your use-case that way, but it would also allow for selection with other methods. Perhaps a more user-friendly custom `spec` or `metadata` field? This is also a bit more future-proof in case of additions to the options for how to make TechDocs available on the frontend, with things like MDX possibly on the horizon.

I suspect there's significant overlap here with the publisher interface too, and in that case I suggest to add this kind of things there instead.

**Comment by Niksko** [comment]
Hey @Rugvip, I had a go at implementing a 'strategy' interface for this, see this draft PR: https://github.com/backstage/backstage/pull/9567. Is this more along the lines of what you were thinking? Note: that draft is still early, needs lots of doc updates and some renaming.

**Comment by Rugvip** [comment]
@Niksko yep looks good! 👍 

I also don't have enough context do will wait for @backstage/techdocs-core to chime in x)

**Comment by soapraj** [comment]
@Niksko With #9567 merged can this issue be closed?

**Comment by Niksko** [comment]
@soapraj yep, closing!

**Comment by eliot-pitman-va** [comment]
Is there more example code than the tech-docs how-to-guide to show exactly how this is implemented?
