### ISSUE TITLE
Parametrize hard-coded Ingress preferences in the Helm chart

### ISSUE THREAD

**Issue by zerodayyy** [backstage/backstage#9512]
## Feature Suggestion

At the moment, Backstage has a dependency on Nginx Ingress Controller, forcing the use of a specific platform (also the ingress class annotation in Ingress resource is hard-coded to `nginx`). In case one would like to use an alternative Ingress Controller, they would need to fork and customize the chart.

Another part of the issue is the inclusion of Issuer resource, which, however customizable, is a platform concern and makes platform-related decisions from the scope of application. Issuer should not be included as part of the application, however it should be possible to inject TLS-specific preferences into Ingress configuration.

## Possible Implementation

- Parametrize `kubernetes.io/ingress.class` annotation with `nginx` as the default
- Make annotations parametrized and move Nginx-specific annotations from the Ingress template to values file
- Remove Issuer resource from the chart, and parametrize the Ingress template to allow injecting Issuer-related parameters and annotations

**Comment by Rugvip** [comment]
The helm charts are maintained by the community, so not something we'll focus our efforts on. We'd be happy to review PRs that add this capability though!

@martina-if do you have any comments on the request itself and whether it's something that's feasible/desirable?

**Comment by emalihin** [comment]
I've noticed that `kubernetes.io/ingress.class` annotation is duplicated in the Chart - it's present both in values, and in the template itself. While this works fine with Helm, it doesn't work with Flux which doesn't render duplicate yaml keys. 

Since it is present in values file, my PR removes the hard-coded value: https://github.com/backstage/backstage/pull/9545

**Comment by martina-if** [comment]
Hi @zerodayyy , your comments regarding the ingress make a lot of sense. 

Regarding the issuer, I'm happy to have this being optional. The initial goal with this was to have a full backstage set up for demo, so we didn't want to have to put extra work to get it up and running so the issuer was helping with that case.

I won't have time to work on these changes but I'd be happy to review a PR if you'd like to contribute it?

**Comment by stibi** [comment]
Hello, I'm happy to see that this topic is addressed now. I had to fork the chart when I was playing around with Backstage ~ half year ago, because of Traefik as the ingress controller.

Now I'm again trying to deploy Backstage, for real this time, and I'm facing this problem again :)

So, if needed, I'd be happy to propose an enhancement PR. What do you think, are you on it already @zerodayyy ?

**Comment by zerodayyy** [comment]
Hey @stibi, I'd be happy to see and contribute to your PR, unfortunately I've shifted focus to a custom Backstage chart for now

**Comment by benjdlambert** [comment]
Gonna direct some of this conversation to here too: https://github.com/backstage/backstage/issues/4945
