### ISSUE TITLE
Enabling modal dialog box opening in the same page

### ISSUE THREAD

**Issue by hsparmar1** [backstage/backstage#9582]
The request is to add functionality for the Backstage Login process that makes unnecessary pop-up window. Our understanding is that the OAuth implementation uses a popup-based flow, where auth requests are handled in a new popup window that is opened by the app. One of the well promoting effects of this approach is that it makes it possible to request authentication at any point in the app, without requiring a redirect. Because of this there is no need to ask for all scopes upfront, or interrupt the app with a redirect and forcing plugin authors to take care in restoring state after a redirect has been made. 

However, the Feature Request is that Backstage provide the functionality to eliminate the use of a pop-up for the Sign-In page for OAuth / OIDC. 

## Feature Suggestion

This feature request would enable the agency to have a unified UI experience since an overwhelming majority of the applications do not have a pop-up implementation.

## Context
The situational context is centered around UI experience, and how the user goes about signing into the Backstage application. Given that most of the applications at our agency do not use the pop-up functionality for single sign-on, we are requesting a uniformity in their experience by allowing for a log-in option that does not require the use of a pop-up.

**Comment by Rugvip** [comment]
Yep, spot on with the reasoning and the idea makes sense. It's something we did have in mind in the design of the auth backend, being why we have `/handler/frame` as the callback, in case we need a separate `/handler/redirect` or such. We'd most likely carry that in OAuth state at this point though tbh.

I think there are two types of UX optimizations we can apply to the auth flow, first one being what you suggest with a redirect at sign-in, and the second one would be to use an iframe rather than a popup in for providers where that is possible. We've ofc opted for the LCM for the initial implementation to not spread ourselves too thin.

Happy to help out moving this forward through contributions, but it's not an area I see that we'll be able to spend time from the maintainer team in the predictable future.

**Comment by ericis** [comment]
This would make it possible to embed Backstage into other applications where a pop-up window is not only undesirable, but not possible. For example, MS Teams chat has support for custom "Tabs" that point to a URL and host an embedded browser to display the URL. However, Backstage with authentication fails, because the embedded browser does not support pop-up windows.

**Comment by Rugvip** [comment]
@ericis not super thrilled about that idea for security reasons tbh, but it can be safe in some situations

**Comment by ericis** [comment]
@Rugvip re: security concerns
Are they at all related to requiring a popout window for authentication? I'm assuming you'd agree that Backstage can be as secure as any other site without a popout window. So, also assuming you might be referring to security concerns about using an authenticated site in an embedded browser. Are those assumptions correct?

**Comment by Rugvip** [comment]
@ericis yep sorry wasn't very clear. I was referring to allowing backstage to be embedded in other websites. Reading what you said again I realize that you might be talking about embedding it a native app though, which would be no problem and definitely a reason to support popup-less flows.

**Comment by headphonejames** [comment]
I am currently investigating approaches to implementing this feature.
