### ISSUE TITLE
Disable/enable the github refresh rate

### ISSUE THREAD

**Issue by lalit774** [backstage/backstage#9828]
We are getting the issue due to refresh rate. We have 1800 records. On refresh it send the calls to Github. so we want to disable the refresh rate and we use the user api end point to add/remove and update the apis.

or

If we have any other method expect from polling.

## Expected Behavior
Just need ability to enable and disable the refresh rate

## Actual Behavior
Refresh rate is enable by default

**Comment by lalit774** [comment]
@Rugvip I have 1800 catalog apis. If I use Github App integration and slow down refresh rate suppose 3600 seconds. 
will it do polling(check all data one by one) for all 1800 records or it will refresh only updated API catalog in Github?

I understand, I will get more api calls for Github App Integration.
- In my case, out of 1800 API catalog, There is max cap(as per historic log from our data) only 50 records updated/added/deleted per day. Now, It seems to me overkill for refresh automatically. If I use api end point to refresh location, add location and delete location. It will be simpler as per my understanding.
- do you see any obstacle doing so? 
 
Thank You

**Comment by Rugvip** [comment]
@lalit774 it will poll for each of the records, although some if not all of those requests may be cached in a way where unchanged entities do not count towards the GitHub rate limit.

I wouldn't worry too much about polling unchanged entities to be honest, as long as we're able to keep within the rate limits. We are exploring event driven options though, so that is the way forward for a much more efficient catalog processing loop.
