### ISSUE TITLE
Catalog refetches data on filters being shown/hidden

### ISSUE THREAD

**Issue by DanielTibbing** [backstage/backstage#9904]
## Expected Behavior

Data should persist on screen size change

## Actual Behavior

When resizing the window past the breakpoint of showing and hiding the filters a re-render is triggered, which leads to the catalog refetching data. 

## Steps to Reproduce

1. Go to catalog
2. Resize window past the breakpoint where the filters are being shown/hidden
3. Look in the network tab and see that the data is fetched every time you pass this breakpoint

https://user-images.githubusercontent.com/1080442/156366675-a53037d6-8ec6-47ff-8fdd-533b12b5849d.mov

## Context

Re-fetching data leads to users who have navigated to a different page in the catalog table to be moved back to the first page, also causes unnecessary data fetching.

## Your Environment

- Browser Information: Any browser, can be seen and reproduced on https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned

- Output of `yarn backstage-cli info`:

**Comment by timbonicus** [comment]
This is not re-fetching the data shown in the table, but refetching the list of component types available in the `Type` filter dropdown since that component is recreated and its state is not stored outside the component (e.g. in context). This is made more apparent and significantly improved by #9491 which switches this call to a facets query instead.

Given that facet improvement, and that introducing a new context outside of this component would complicate matters _and_ break existing adopters that have customized their catalog page, I don't think this is worthwhile to fix.

**Comment by DanielTibbing** [comment]
Interesting, this seems to be fixed then.. It is definitely reloading data in our instance of backstage, but we haven't updated everything to the latest version yet.. I'll close this issue :)
